import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 3 HÓA HỌC 10: PHẢN ỨNG OXI HÓA - KHỬ (Phần 2) ---
    # Nhóm 26, 27: Xác định mức oxi hóa phức tạp
    {"id": "mc-c3-061", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Xác định nhanh số OXH",
     "question": "Số oxi hóa của Nitrogen (N) trong phân tử Amoni nitrat ($NH_4NO_3$) lần lượt là:",
     "choices": ["-3 và +5", "+3 và +5", "-3 và -3", "+5 và +5"],
     "answer": 0, "explanation": "Amoni nitrat cấu tạo từ 2 ion: $NH_4^+$ và $NO_3^-$. Trong $NH_4^+$ (N có số OXH là -3). Trong $NO_3^-$ (N có số OXH là +5). Dù cùng là nguyên tố N nhưng chúng nằm ở 2 môi trường khác nhau trong phân tử muối này."},
    {"id": "mc-c3-062", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "OXH hợp chất hữu cơ 2",
     "question": "Xác định số oxi hóa của Carbon trong phân tử Methanal (HCHO):",
     "choices": ["0", "+2", "-2", "+4"],
     "answer": 0, "explanation": "Theo phương pháp trung bình: H là +1, O là -2. Gọi x là số OXH của C. Ta có $x + 2(+1) + 1(-2) = 0 \Rightarrow x = 0$."},
    {"id": "mc-c3-063", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Ngoại lệ Peroxide",
     "question": "Trong hợp chất Hydrogen peroxide ($H_2O_2$), số oxi hóa của Oxygen là:",
     "choices": ["-1", "-2", "0", "+1"],
     "answer": 0, "explanation": "Trong $H_2O_2$, H là +1. Suy ra $2(+1) + 2x = 0 \Rightarrow x = -1$. Liên kết $O-O$ là liên kết giữa 2 nguyên tử giống nhau nên không có sự lệch electron giữa chúng."},
    {"id": "mc-c3-064", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Số OXH của Halogen",
     "question": "Dãy các hợp chất nào sau đây mà Chlorine lần lượt có các số oxi hóa là -1, +1, +3, +5, +7?",
     "choices": ["$HCl, NaClO, HClO_2, KClO_3, HClO_4$", "$NaCl, HClO_4, KClO_3, Cl_2, HClO$", "$HCl, HClO, Cl_2O_3, ClO_2, Cl_2O_7$", "$KCl, Cl_2, HClO, KClO_3, HClO_4$"],
     "answer": 0, "explanation": "Tính Cl trong dãy 1: $HCl$ (-1). $NaClO$ (+1). $HClO_2$ (+3). $KClO_3$ (+5). $HClO_4$ (+7)."},

    # Nhóm 28, 29: Phản ứng Oxi hóa - Khử với Halogen
    {"id": "mc-c3-065", "chapter": "c3", "lesson": "b18", "level": "th", "dang": "Halogen + Kim loại",
     "question": "Khi cho dây Sắt (Fe) cháy trong bình khí Chlorine ($Cl_2$), sản phẩm thu được là gì và Sắt thể hiện tính gì?",
     "choices": ["$FeCl_3$, Sắt thể hiện tính khử", "$FeCl_2$, Sắt thể hiện tính khử", "$FeCl_3$, Sắt thể hiện tính oxi hóa", "$FeCl_2$, Sắt thể hiện tính oxi hóa"],
     "answer": 0, "explanation": "Khí $Cl_2$ có tính oxi hóa rất mạnh, nó oxi hóa Fe thẳng lên mức oxi hóa cao nhất là +3 (tạo muối Sắt(III) clorua). Sắt nhường e nên là chất khử."},
    {"id": "mc-c3-066", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Halogen tác dụng với Nước",
     "question": "Sục khí $Cl_2$ vào nước thu được 'Nước clo'. Thành phần chính của 'Nước clo' (coi như hệ đạt cân bằng) gồm những chất gì?",
     "choices": ["$Cl_2$, $H_2O$, $HCl$, $HClO$", "Chỉ có $HCl$ và $HClO$", "Chỉ có $Cl_2$ và $H_2O$", "$HCl, HClO_3, H_2O$"],
     "answer": 0, "explanation": "Phản ứng: $Cl_2 + H_2O \\rightleftharpoons HCl + HClO$. Phản ứng thuận nghịch, hiệu suất thấp nên trong dung dịch còn tồn tại $Cl_2$ dư, $H_2O$, và sản phẩm $HCl, HClO$ (Hypochlorous acid)."},
    {"id": "mc-c3-067", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Điều chế Cl2 phòng thí nghiệm",
     "question": "Trong phòng thí nghiệm, người ta thường điều chế khí $Cl_2$ bằng cách cho dung dịch $HCl$ đặc tác dụng với chất nào sau đây?",
     "choices": ["$MnO_2$ đun nóng", "$KMnO_4$ đun nóng", "$CaCO_3$", "$NaCl$ tinh thể"],
     "answer": 0, "explanation": "Cho chất oxi hóa mạnh ($MnO_2$, $KMnO_4$) tác dụng với $HCl$ đặc. VD: $MnO_2 + 4HCl \\rightarrow MnCl_2 + Cl_2 + 2H_2O$. (Tùy chọn A đúng nhất vì KMnO4 ko cần đun nóng)."},
    {"id": "mc-c3-068", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Điều chế Cl2 công nghiệp",
     "question": "Trong công nghiệp, khí $Cl_2$ được sản xuất bằng phương pháp nào?",
     "choices": ["Điện phân dung dịch $NaCl$ bão hòa có màng ngăn", "Điện phân $NaCl$ nóng chảy", "Nhiệt phân muối $KClO_3$", "Cho $HCl$ tác dụng với $MnO_2$"],
     "answer": 0, "explanation": "Trong công nghiệp dùng phương pháp điện phân dung dịch có màng ngăn: $2NaCl + 2H_2O \\rightarrow 2NaOH + H_2 \\uparrow + Cl_2 \\uparrow$. Màng ngăn xốp để tránh $Cl_2$ tác dụng lại với NaOH sinh ra nước Javel."},

    # Nhóm 30: Pin điện hóa, ăn mòn hóa học
    {"id": "mc-c3-069", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Ăn mòn hóa học vs điện hóa",
     "question": "Sự khác biệt cơ bản nhất giữa ăn mòn hóa học và ăn mòn điện hóa là gì?",
     "choices": ["Ăn mòn điện hóa có phát sinh dòng điện, còn ăn mòn hóa học thì không", "Ăn mòn hóa học xảy ra nhanh hơn", "Ăn mòn điện hóa chỉ xảy ra với kim loại nguyên chất", "Ăn mòn hóa học sinh ra ion âm"],
     "answer": 0, "explanation": "Ăn mòn hóa học là phản ứng trực tiếp không sinh ra dòng điện. Ăn mòn điện hóa xảy ra khi có 2 điện cực (hợp kim) tiếp xúc với dung dịch điện li, electron di chuyển tạo thành dòng điện nội bộ làm kim loại bị ăn mòn."},
    {"id": "mc-c3-070", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Pin điện và suất điện động",
     "question": "Kí hiệu chuẩn của pin điện hóa $Zn - Cu$ là: $(-) Zn | Zn^{2+} (1M) || Cu^{2+} (1M) | Cu (+)$. Sức điện động chuẩn ($E_{pin}^0$) của pin này được tính bằng công thức nào?",
     "choices": ["$E_{pin}^0 = E_{cathode}^0 - E_{anode}^0$", "$E_{pin}^0 = E_{anode}^0 - E_{cathode}^0$", "$E_{pin}^0 = E_{cathode}^0 + E_{anode}^0$", "$E_{pin}^0 = 0$"],
     "answer": 0, "explanation": "Sức điện động chuẩn của pin = Thế điện cực chuẩn của Cực Dương (Cathode) trừ đi Thế điện cực chuẩn của Cực Âm (Anode). Đại lượng này luôn dương."},
    {"id": "mc-c3-071", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Bảo vệ vật dụng",
     "question": "Đinh sắt (Fe) được quấn bởi dây đồng (Cu) rồi thả vào dung dịch $HCl$ loãng sẽ bị ăn mòn như thế nào so với đinh sắt thả một mình vào $HCl$ loãng?",
     "choices": ["Bị ăn mòn nhanh hơn nhiều (ăn mòn điện hóa)", "Bị ăn mòn chậm hơn", "Không bị ăn mòn", "Tốc độ ăn mòn như nhau"],
     "answer": 0, "explanation": "Fe và Cu tạo thành 2 cực của pin điện (Fe mạnh hơn làm cực âm). Trong dung dịch điện li HCl, xảy ra ăn mòn điện hóa $\\Rightarrow$ Fe bị oxi hóa rất nhanh. Khí $H_2$ thoát ra ở cực đồng (Cu)."},
    {"id": "mc-c3-072", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Định nghĩa mạnh yếu",
     "question": "Tính chất của dãy điện hóa kim loại: Kim loại càng mạnh (dễ nhường e) thì ion dương của nó sẽ có tính chất gì?",
     "choices": ["Tính oxi hóa càng yếu", "Tính oxi hóa càng mạnh", "Tính khử càng mạnh", "Không có tính oxi hóa"],
     "answer": 0, "explanation": "Quy luật 'Tính khử của kim loại và tính oxi hóa của ion kim loại là nghịch biến'. Kim loại Na tính khử rất mạnh $\\Rightarrow ion Na^+$ có tính oxi hóa cực kì yếu. Ngược lại Ag yếu, ion $Ag^+$ oxi hóa mạnh."},

    # Câu 73 - 120: Luyện tập
    {"id": "mc-c3-073", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng NH3",
     "question": "Cân bằng phương trình oxi hóa xúc tác Amoniac: $NH_3 + O_2 \\xrightarrow{Pt, t^\\circ} NO + H_2O$. Tổng hệ số của các chất tham gia và sản phẩm là (hệ số nguyên tối giản):",
     "choices": ["19", "20", "18", "21"],
     "answer": 0, "explanation": "N(-3) $\\rightarrow$ N(+2) + 5e. O2(0) + 4e $\\rightarrow$ 2O(-2). Bội chung 20 $\\Rightarrow$ Nhân 4 vào N và 5 vào O2. Phương trình: $4NH_3 + 5O_2 \\rightarrow 4NO + 6H_2O$. Tổng hệ số = $4 + 5 + 4 + 6 = 19$."},
    {"id": "mc-c3-074", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Cân bằng hữu cơ đơn giản",
     "question": "Đốt cháy hoàn toàn khí Methane ($CH_4$) bằng $O_2$. Phản ứng này có sự thay đổi số oxi hóa của Carbon như thế nào?",
     "choices": ["Từ -4 lên +4", "Từ -2 lên +2", "Từ 0 lên +4", "Từ +4 xuống -4"],
     "answer": 0, "explanation": "Trong $CH_4$, C có số OXH là -4. Sản phẩm cháy là $CO_2$, C có số OXH là +4. Vậy C thay đổi từ -4 lên +4 (tính khử)."},
    {"id": "mc-c3-075", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "PƯ vừa tạo kết tủa vừa OXH-K",
     "question": "Phản ứng nào sau đây là phản ứng oxi hóa - khử có sinh ra kết tủa?",
     "choices": ["$2FeCl_3 + H_2S \\rightarrow 2FeCl_2 + S \\downarrow + 2HCl$", "$BaCl_2 + Na_2SO_4 \\rightarrow BaSO_4 \\downarrow + 2NaCl$", "$AgNO_3 + NaCl \\rightarrow AgCl \\downarrow + NaNO_3$", "$Fe_2(SO_4)_3 + 6NaOH \\rightarrow 2Fe(OH)_3 \\downarrow + 3Na_2SO_4$"],
     "answer": 0, "explanation": "Các phản ứng B, C, D đều là phản ứng trao đổi ion (không thay đổi số OXH). Phản ứng A: $Fe^{3+}$ giảm xuống $Fe^{2+}$, $S^{-2}$ tăng lên $S^0$ (kết tủa vàng)."},
    
    {"id": "mc-c3-076", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bảo toàn khối lượng + bảo toàn e",
     "question": "Nung hỗn hợp gồm 5,6g Fe và 1,6g S trong môi trường không có không khí. Sau phản ứng hoàn toàn thu được chất rắn X. Cho X tác dụng với dung dịch $HCl$ dư thu được khí Y. Y gồm:",
     "choices": ["$H_2S$ và $H_2$", "Chỉ có $H_2S$", "Chỉ có $H_2$", "$SO_2$ và $H_2S$"],
     "answer": 0, "explanation": "n Fe = 0,1 mol. n S = 0,05 mol. Phản ứng: $Fe + S \\rightarrow FeS$. S hết 0,05 mol, Fe dư 0,05 mol. Chất rắn X gồm FeS (0,05 mol) và Fe dư (0,05 mol). Cho vào HCl: $FeS \\rightarrow H_2S$ và $Fe \\rightarrow H_2$. Khí Y gồm $H_2S$ và $H_2$."},
    {"id": "mc-c3-077", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Dự đoán sản phẩm khử",
     "question": "Kẽm (Zn) tác dụng với dung dịch $HNO_3$ rất loãng, nguội. Sản phẩm khử chủ yếu được hình thành thường là:",
     "choices": ["$NH_4NO_3$ (Amoni nitrat)", "$NO_2$", "$NO$", "$N_2O$"],
     "answer": 0, "explanation": "Kim loại càng mạnh (như Mg, Al, Zn) phản ứng với acid càng loãng thì khả năng khử N(+5) của HNO3 xuống mức oxi hóa càng thấp. Mức thấp nhất của N là -3 (trong muối $NH_4NO_3$). ($NO_2$ thường sinh ra với kim loại yếu hoặc acid đặc)."},
    {"id": "mc-c3-078", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Vai trò Nước Gia-ven",
     "question": "Nước Javel (hỗn hợp $NaCl$ và $NaClO$) có tính tẩy màu, sát trùng là do:",
     "choices": ["$NaClO$ là muối của axit rất yếu (yếu hơn $H_2CO_3$), dễ bị phân hủy sinh ra Oxi nguyên tử hoặc HClO có tính oxi hóa rất mạnh", "Vì nó chứa nhiều khí $Cl_2$", "Vì nó có tính bazơ mạnh", "Vì nó có màu trắng"],
     "answer": 0, "explanation": "Ion hypoclorit ($ClO^-$) có tính oxi hóa rất mạnh, phá hủy các cấu trúc mang màu (tẩy trắng) và màng tế bào vi khuẩn (sát trùng)."},
    {"id": "mc-c3-079", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Phản ứng Clorua vôi",
     "question": "Clorua vôi có công thức phân tử là $CaOCl_2$. Xác định số oxi hóa của hai nguyên tử Chlorine trong hợp chất này:",
     "choices": ["-1 và +1", "0 và 0", "-1 và -1", "+1 và +1"],
     "answer": 0, "explanation": "Cấu tạo: $Ca^{2+}$ liên kết với gốc $Cl^-$ (clorua, số OXH -1) và gốc $ClO^-$ (hypoclorit, số OXH +1). Đây là muối hỗn tạp của kim loại Canxi với 2 loại gốc acid khác nhau. Hai nguyên tử Cl có số OXH khác nhau."},
    
    {"id": "mc-c3-080", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Cân bằng vô cơ phức",
     "question": "Trong phản ứng: $FeS_2 + O_2 \\rightarrow Fe_2O_3 + SO_2$. Tổng hệ số của chất tham gia phản ứng (vế trái) là:",
     "choices": ["15", "11", "4", "7"],
     "answer": 0, "explanation": "Coi toàn bộ phân tử $FeS_2$ có số OXH là 0 (cả cụm). Quá trình nhường: $FeS_2 \\rightarrow Fe^{+3} + 2S^{+4} + 11e$. (Nhân 2 để chẵn Fe: $2FeS_2 \\rightarrow 2Fe^{+3} + 4S^{+4} + 22e$). Quá trình nhận: $O_2 + 4e \\rightarrow 2O^{-2}$. Bội chung là 44 $\\Rightarrow$ Nhân 2 vào cụm $FeS_2$ và nhân 11 vào $O_2$. PT: $4FeS_2 + 11O_2 \\rightarrow 2Fe_2O_3 + 8SO_2$. Tổng vế trái = $4 + 11 = 15$."},
    {"id": "mc-c3-081", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Lập luận muối sắt",
     "question": "Hòa tan bột Fe vào dung dịch $HNO_3$ loãng. Nếu phản ứng xong mà bột Fe vẫn còn dư, thì muối thu được trong dung dịch cuối cùng là:",
     "choices": ["Chỉ có $Fe(NO_3)_2$", "Chỉ có $Fe(NO_3)_3$", "Hỗn hợp 2 muối", "Không xác định được"],
     "answer": 0, "explanation": "Fe tác dụng HNO3 ban đầu tạo $Fe^{3+}$. Nhưng nếu Fe vẫn còn dư, nó sẽ khử $Fe^{3+}$ về $Fe^{2+}$ theo phương trình: $Fe + 2Fe^{3+} \\rightarrow 3Fe^{2+}$. Do đó dung dịch chỉ chứa muối Sắt (II)."},
    {"id": "mc-c3-082", "chapter": "c3", "lesson": "b18", "level": "th", "dang": "Phản ứng Halogen đặc biệt",
     "question": "Tại sao dung dịch Fluorine ($F_2$) không thể đẩy được ion Bromide ($Br^-$) hay Iodide ($I^-$) ra khỏi dung dịch muối của chúng, dù $F_2$ là chất oxi hóa mạnh nhất?",
     "choices": ["Vì Fluorine tác dụng mãnh liệt với nước trong dung dịch (cháy trong nước) tạo HF và $O_2$ trước khi kịp tác dụng với muối", "Vì $F_2$ yếu hơn $Br_2$", "Vì F và Br không phản ứng với nhau", "Vì F có bán kính quá nhỏ"],
     "answer": 0, "explanation": "Phản ứng: $2F_2 + 2H_2O \\rightarrow 4HF + O_2$. Nước bốc cháy khi tiếp xúc với $F_2$, nên trong dung dịch $F_2$ bị tiêu diệt ngay lập tức."},
    {"id": "mc-c3-083", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Khắc chữ lên thủy tinh",
     "question": "Acid nào sau đây có khả năng ăn mòn thủy tinh (thành phần chính là $SiO_2$), được ứng dụng để khắc chữ, hoa văn lên kính?",
     "choices": ["Hydrofluoric acid ($HF$)", "Hydrochloric acid ($HCl$)", "Sulfuric acid ($H_2SO_4$ đặc)", "Nitric acid ($HNO_3$)"],
     "answer": 0, "explanation": "Phản ứng: $SiO_2 + 4HF \\rightarrow SiF_4 \\uparrow + 2H_2O$. Đây là phản ứng đặc trưng của dung dịch HF, giải thích vì sao không được đựng HF trong bình thủy tinh (mà phải đựng bằng chai nhựa). Mặc dù là acid yếu, nó lại hòa tan được thủy tinh."},

    {"id": "mc-c3-084", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Hợp chất có số OXH đa dạng",
     "question": "Nitrogen có số oxi hóa -3, 0, +1, +2, +3, +4, +5. Phát biểu nào sai?",
     "choices": ["$N_2$ (số oxh 0) chỉ thể hiện tính oxi hóa, không có tính khử", "$NH_3$ (số oxh -3) chỉ thể hiện tính khử", "$HNO_3$ (số oxh +5) chỉ thể hiện tính oxi hóa", "$NO_2$ (+4) vừa có tính oxi hóa, vừa có tính khử"],
     "answer": 0, "explanation": "$N_2$ ở trạng thái trung gian (0), có thể tăng lên +1, +2... (khi td O2 ở 3000 độ C) hoặc giảm xuống -3 (khi td H2, kim loại). Vậy $N_2$ vừa có tính oxi hóa, vừa có tính khử. Phát biểu A sai."},
    {"id": "mc-c3-085", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bảo toàn e với SO2",
     "question": "Dẫn từ từ V lít khí $SO_2$ (đkc) vào dung dịch chứa 0,1 mol $KMnO_4$. Để làm mất màu hoàn toàn lượng dung dịch thuốc tím này thì giá trị của V là:",
     "choices": ["5,60 lít (quy đổi đkc mới)", "6,1975 lít", "4,958 lít", "2,479 lít"],
     "answer": 0, "explanation": "SO2 nhường e: $S^{+4} \\rightarrow S^{+6} + 2e$. Mn nhận e: $Mn^{+7} + 5e \\rightarrow Mn^{+2}$. $0,1$ mol KMnO4 nhận $0,5$ mol e. Số mol SO2 cần thiết $= 0,5 / 2 = 0,25$ mol. Thể tích $V = 0,25 \\times 24,79 = 6,1975$ lít."},
    {"id": "mc-c3-086", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Tìm điện cực chuẩn",
     "question": "Điện cực Hydrogen chuẩn (SHE) được dùng làm mốc để xác định thế điện cực chuẩn của các kim loại. Thế điện cực chuẩn của SHE được quy ước bằng bao nhiêu?",
     "choices": ["$0,00 \\text{ V}$", "$+1,00 \\text{ V}$", "$-1,00 \\text{ V}$", "$0,76 \\text{ V}$"],
     "answer": 0, "explanation": "Điện cực hydro chuẩn có $E^0 = 0.00 V$ ở mọi nhiệt độ. Các kim loại dễ nhường e hơn Hydro (như Zn, Fe) sẽ có thế điện cực âm. Kim loại khó nhường e hơn (như Cu, Ag) sẽ có thế điện cực dương."},
    {"id": "mc-c3-087", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Tác dụng Iot hồ tinh bột",
     "question": "Hiện tượng đặc trưng để nhận biết Iot ($I_2$) là:",
     "choices": ["Tạo hợp chất màu xanh đen với hồ tinh bột", "Tạo kết tủa vàng với bạc nitrat", "Tạo khói trắng với khí amoniac", "Tạo dung dịch màu tím với nước"],
     "answer": 0, "explanation": "Phân tử Iot ($I_2$) có kích thước vừa khít để chui vào cấu trúc dạng xoắn rỗng của tinh bột, tạo ra phức chất có màu xanh đen đặc trưng. Khi đun nóng màu mất (vì tinh bột duỗi ra I2 thoát ra), để nguội màu xanh lại xuất hiện."},

    {"id": "mc-c3-088", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Xác định nhanh số OXH vô cơ",
     "question": "Số oxi hóa của Lưu huỳnh trong hợp chất Sodium thiosulfate ($Na_2S_2O_3$) tính theo phương pháp trung bình là:",
     "choices": ["+2", "+4", "+6", "+1"],
     "answer": 0, "explanation": "Tính toán: $2(+1) + 2x + 3(-2) = 0 \\Rightarrow 2 + 2x - 6 = 0 \\Rightarrow 2x = 4 \\Rightarrow x = +2$."},
    {"id": "mc-c3-089", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bài toán nhôm và bazơ",
     "question": "Nhôm (Al) tan được trong dung dịch $NaOH$ sinh ra khí $H_2$. Trong phản ứng này, chất oxi hóa là:",
     "choices": ["$H_2O$", "$NaOH$", "Al", "Không có chất oxi hóa"],
     "answer": 0, "explanation": "Phản ứng thực chất là Al tác dụng với nước: $2Al + 6H_2O \\rightarrow 2Al(OH)_3 + 3H_2$. Sau đó $Al(OH)_3$ tan trong $NaOH$: $Al(OH)_3 + NaOH \\rightarrow NaAlO_2 + 2H_2O$. Gộp lại: $2Al + 2NaOH + 2H_2O \\rightarrow 2NaAlO_2 + 3H_2$. Nguyên tử $H^{+1}$ trong $H_2O$ đã nhận e về $H^0$ ($H_2$). NaOH chỉ đóng vai trò môi trường (không thay đổi số OXH). Vậy nước là chất oxi hóa."},
    {"id": "mc-c3-090", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Sự ăn mòn tàu biển",
     "question": "Môi trường nước biển là môi trường gì khiến cho vỏ tàu bằng thép (Sắt - Cacbon) bị ăn mòn điện hóa mạnh?",
     "choices": ["Môi trường chất điện li mạnh (chứa nhiều muối hòa tan như NaCl, MgCl2...)", "Môi trường chân không", "Môi trường axit đặc", "Môi trường không có oxi"],
     "answer": 0, "explanation": "Nước biển chứa nhiều muối phân li thành ion, có độ dẫn điện tốt. Vỏ thép có các tinh thể Fe và C tiếp xúc với nhau. Chúng cùng tiếp xúc với nước biển $\\Rightarrow$ Tỏa mãn 3 điều kiện của ăn mòn điện hóa. $O_2$ hòa tan trong nước sẽ là chất oxi hóa lấy e tại cực dương (C)."},
    {"id": "mc-c3-091", "chapter": "c3", "lesson": "b18", "level": "th", "dang": "Muối Halogenua",
     "question": "Trong các dung dịch sau, dung dịch nào KHÔNG phản ứng với dung dịch $AgNO_3$ tạo kết tủa?",
     "choices": ["$NaF$", "$NaCl$", "$NaBr$", "$NaI$"],
     "answer": 0, "explanation": "AgCl kết tủa trắng, AgBr kết tủa vàng nhạt, AgI kết tủa vàng đậm. Riêng AgF tan tốt trong nước nên không tạo kết tủa."},

    {"id": "mc-c3-092", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Cân bằng rượu tác dụng thuốc tím",
     "question": "Cân bằng phương trình: $5CH_3CH_2OH + 4KMnO_4 + 6H_2SO_4 \\rightarrow 5CH_3COOH + 4MnSO_4 + 2K_2SO_4 + 11H_2O$. Chất oxi hóa là:",
     "choices": ["$KMnO_4$", "$CH_3CH_2OH$", "$H_2SO_4$", "$H_2O$"],
     "answer": 0, "explanation": "$KMnO_4$ (thuốc tím) là chất oxi hóa điển hình, nó nhận electron và giảm từ Mn(+7) xuống Mn(+2)."},
    {"id": "mc-c3-093", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Quy đổi hỗn hợp vô cơ",
     "question": "Bản chất của phương pháp giải bài toán kim loại bị oxi hóa một phần (như Fe thành hỗn hợp oxit) rồi hòa tan trong acid (như HNO3) là gì?",
     "choices": ["Quy đổi quá trình thành: Kim loại nhường e trực tiếp cho 2 chất oxi hóa (Oxygen và HNO3)", "Bắt buộc phải viết và cân bằng mọi phương trình phản ứng hóa học có thể xảy ra", "Tính tổng khối lượng của từng oxit", "Không thể giải được nếu không biết tỉ lệ từng oxit"],
     "answer": 0, "explanation": "Dùng định luật bảo toàn electron, ta chỉ quan tâm trạng thái đầu (Fe) và trạng thái cuối (Fe3+). Nó nhường e cho 2 tác nhân là $O_2$ (trong quá trình cháy) và $N^{+5}$ (trong dung dịch acid). Không cần biết quá trình trung gian tạo ra oxit gì."},
    
    {"id": "mc-c3-094", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Điện phân nóng chảy",
     "question": "Quá trình điện phân là quá trình sử dụng năng lượng điện để tạo ra phản ứng hóa học (ngược với pin điện). Khi điện phân $NaCl$ nóng chảy, ở cực âm (Cathode) xảy ra quá trình gì?",
     "choices": ["Sự khử ion $Na^+$ thành kim loại $Na$", "Sự oxi hóa ion $Na^+$", "Sự oxi hóa ion $Cl^-$ thành khí $Cl_2$", "Sự khử ion $Cl^-$"],
     "answer": 0, "explanation": "Trong bình điện phân, Cực Âm hút các Cation ($Na^+$) và cung cấp electron cho chúng. Quá trình nhận e $\\Rightarrow$ Sự khử. $Na^+ + 1e \\rightarrow Na^0$."},
    {"id": "mc-c3-095", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Cấu tạo liên kết Halogen",
     "question": "Tại sao các phân tử đơn chất Halogen ($F_2, Cl_2, Br_2, I_2$) lại không phân cực?",
     "choices": ["Vì chúng được tạo thành từ 2 nguyên tử của cùng một nguyên tố có độ âm điện bằng nhau", "Vì chúng có liên kết ion", "Vì chúng là các khí trơ", "Vì chúng không có electron lớp ngoài cùng"],
     "answer": 0, "explanation": "Liên kết cộng hóa trị giữa 2 nguyên tử giống hệt nhau thì cặp electron dùng chung sẽ nằm chính giữa, không lệch về phía nào cả $\\Rightarrow$ Phân tử hoàn toàn không phân cực."},

    {"id": "mc-c3-096", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Xác định nhanh số oxh Oxi",
     "question": "Trong hợp chất $KO_2$ (Kali superoxide), số oxi hóa của Oxygen là:",
     "choices": ["-1/2", "-1", "-2", "+2"],
     "answer": 0, "explanation": "K là +1. Trong ion superoxide $O_2^-$, mỗi nguyên tử Oxi có số oxi hóa trung bình là -1/2."},
    {"id": "mc-c3-097", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Độ biến thiên số OXH",
     "question": "Cho phản ứng: $Al + H_2SO_4 \\text{ (đặc, nóng)} \\rightarrow Al_2(SO_4)_3 + H_2S + H_2O$. Độ biến thiên số oxi hóa của Sulfur (Lưu huỳnh) trong một phân tử chất oxi hóa là:",
     "choices": ["Giảm 8", "Giảm 6", "Giảm 2", "Tăng 8"],
     "answer": 0, "explanation": "S trong $H_2SO_4$ (chất oxi hóa) có số OXH là +6. Sản phẩm khử là $H_2S$ có số OXH là -2. Vậy $6 - (-2) = 8$. Độ biến thiên (mức giảm) là 8 (nhận 8e)."},
    {"id": "mc-c3-098", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Sự mạ điện",
     "question": "Trong kĩ thuật mạ điện (ví dụ mạ bạc cho chiếc nĩa sắt), vật cần mạ (chiếc nĩa) phải được nối với cực nào của nguồn điện một chiều?",
     "choices": ["Cực âm (Cathode)", "Cực dương (Anode)", "Nối tiếp cả 2 cực", "Không nối với nguồn điện"],
     "answer": 0, "explanation": "Tại Cathode (cực âm) xảy ra sự khử các ion $Ag^+$ thành lớp bạc kim loại bám lên vật."},
    {"id": "mc-c3-099", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Tính axit của các Halogenua",
     "question": "Sắp xếp tính acid của các dung dịch axit halogenhydric giảm dần là:",
     "choices": ["$HI > HBr > HCl > HF$", "$HF > HCl > HBr > HI$", "$HCl > HBr > HI > HF$", "$HF > HI > HBr > HCl$"],
     "answer": 0, "explanation": "Bán kính nguyên tử tăng từ F đến I $\\Rightarrow$ Chiều dài liên kết H-X tăng $\\Rightarrow$ Năng lượng liên kết H-X giảm, càng dễ phân li ra $H^+$ trong dung dịch. Do đó HI là acid mạnh nhất, HF là acid yếu (do lk H-F quá bền và lk H mạnh)."},

    {"id": "mc-c3-100", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Dự đoán chiều phản ứng",
     "question": "Dựa vào quy tắc alpha ($\\alpha$), phản ứng hóa học tự phát thường xảy ra giữa:",
     "choices": ["Chất oxi hóa mạnh nhất với chất khử mạnh nhất để tạo ra chất oxi hóa yếu hơn và chất khử yếu hơn", "Chất oxi hóa yếu nhất với chất khử yếu nhất", "Hai chất oxi hóa phản ứng với nhau", "Hai chất khử phản ứng với nhau"],
     "answer": 0, "explanation": "Phản ứng tự nhiên đi theo chiều hướng giảm dần năng lượng tự do, tức là chất oxi hóa MẠNH sẽ lấy electron của chất khử MẠNH, để sinh ra các sản phẩm (chất oxh và chất khử mới) YẾU HƠN, bền vững hơn."},
    
    # 20 Câu luyện tập hỗn hợp
    {"id": "mc-c3-101", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Tổng kết khái niệm PƯ",
     "question": "Phát biểu nào sau đây ĐÚNG về phản ứng oxi hóa - khử?",
     "choices": ["Sự oxi hóa và sự khử luôn xảy ra đồng thời", "Có thể chỉ có sự oxi hóa mà không có sự khử", "Chất bị oxi hóa là chất nhận electron", "Số oxi hóa của tất cả các nguyên tố đều phải thay đổi"],
     "answer": 0, "explanation": "Electron không thể tự nhiên sinh ra hay biến mất (ở mức độ hóa học). Nếu có 1 chất nhường e (bị oxi hóa) thì bắt buộc phải có 1 chất nhận e (bị khử). Hai quá trình này song hành và đồng thời."},
    {"id": "mc-c3-102", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng với P",
     "question": "Cân bằng phản ứng: $P + HNO_3 \\text{ (đặc)} \\rightarrow H_3PO_4 + NO_2 + H_2O$. Tổng các hệ số tối giản là:",
     "choices": ["13", "12", "14", "10"],
     "answer": 0, "explanation": "P(0) $\\rightarrow$ P(+5) + 5e. N(+5) + 1e $\\rightarrow$ N(+4). Nhân 5 vào NO2 (và HNO3). PT: $1 P + 5 HNO_3 \\rightarrow 1 H_3PO_4 + 5 NO_2 + 1 H_2O$. (Kiểm tra Oxi: $5 \\times 3 = 15$. Vế phải: $4 + 10 + 1 = 15$. Đúng). Tổng = $1 + 5 + 1 + 5 + 1 = 13$."},
    {"id": "mc-c3-103", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Cực của acquy chì",
     "question": "Trong acquy chì (chứa $H_2SO_4$), khi acquy phóng điện (cung cấp điện), cực âm được làm bằng vật liệu gì?",
     "choices": ["Pb (Chì dạng xốp)", "$PbO_2$ (Chì(IV) oxide)", "$Cu$", "$Zn$"],
     "answer": 0, "explanation": "Cực âm là Chì (Pb), cực dương là $PbO_2$. Tại cực âm: $Pb \\rightarrow Pb^{2+} + 2e$. Tại cực dương: $PbO_2 + 4H^+ + 2e \\rightarrow Pb^{2+} + 2H_2O$. (Cả 2 cực sau đó tạo kết tủa $PbSO_4$)."},
    {"id": "mc-c3-104", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Thuốc thử Iot",
     "question": "Để chứng minh khí $Cl_2$ có tính oxi hóa mạnh hơn $Br_2$ và $I_2$, ta có thể thực hiện thí nghiệm cho giấy quấn tẩm hỗn hợp hồ tinh bột và muối nào sau đây tiếp xúc với khí $Cl_2$?",
     "choices": ["Muối $KI$ hoặc $NaI$", "Muối $NaCl$", "Muối $NaF$", "Muối $CaCO_3$"],
     "answer": 0, "explanation": "Sử dụng KI hoặc NaI (muối Iodide)."},
    
    {"id": "mc-c3-105", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Cân bằng ion",
     "question": "Cho bán phản ứng: $MnO_4^- + 8H^+ + 5e \\rightarrow Mn^{2+} + 4H_2O$. Đây là quá trình gì?",
     "choices": ["Quá trình khử", "Quá trình oxi hóa", "Quá trình trao đổi ion", "Sự điện li"],
     "answer": 0, "explanation": "Phân tử/ion nhận thêm electron vào ($+ 5e$ ở bên trái) $\\Rightarrow$ Số oxh giảm $\\Rightarrow$ Đây là quá trình khử (sự khử) ion Pemanganat."},
    {"id": "mc-c3-106", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bài toán khí N2 và N2O",
     "question": "Hòa tan m gam Zn vào dung dịch $HNO_3$ dư, thu được hỗn hợp khí A gồm $N_2$ và $N_2O$. Biết tỉ khối của A so với $H_2$ là 18. Tỉ lệ mol của $N_2$ và $N_2O$ trong hỗn hợp là:",
     "choices": ["1 : 1", "2 : 1", "1 : 2", "3 : 1"],
     "answer": 0, "explanation": "$M_A = 18 \\times 2 = 36$. Khối lượng mol của $N_2$ là 28, $N_2O$ là 44. Dùng sơ đồ đường chéo: $N_2$ (28) cách 36 là 8; $N_2O$ (44) cách 36 là 8. Tỉ lệ khoảng cách là $8/8 = 1/1$. Vậy tỉ lệ mol là 1:1."},
    {"id": "mc-c3-107", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Chống ăn mòn phủ bề mặt",
     "question": "Sắt tây (sắt tráng thiếc) dùng làm hộp thực phẩm. Khi hộp bị xước sâu đến lớp sắt bên trong và để ngoài không khí ẩm, kim loại nào sẽ bị ăn mòn điện hóa?",
     "choices": ["Sắt (Fe)", "Thiếc (Sn)", "Cả hai cùng bị ăn mòn như nhau", "Không kim loại nào bị ăn mòn"],
     "answer": 0, "explanation": "Trong dãy điện hóa, Fe mạnh hơn Sn (Fe đứng trước Sn). Khi bị xước tạo pin điện, kim loại mạnh hơn (Fe) sẽ làm cực âm và bị oxi hóa, tức là bị ăn mòn. Sắt hỏng rất nhanh từ bên trong."},
    {"id": "mc-c3-108", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Ứng dụng Halogen",
     "question": "Hợp chất nào của Fluorine được thêm vào kem đánh răng để ngăn ngừa sâu răng?",
     "choices": ["$NaF$ hoặc $SnF_2$", "$HF$", "$CF_4$", "$F_2$"],
     "answer": 0, "explanation": "Ion $F^-$ thay thế nhóm $OH^-$ trong men răng (hydroxyapatite) tạo thành fluorapatite cứng hơn, chống lại sự ăn mòn của axit do vi khuẩn sinh ra. $NaF$ là chất phụ gia phổ biến."},

    {"id": "mc-c3-109", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Cân bằng hữu cơ phức tạp",
     "question": "Số oxi hóa của nguyên tử Carbon có nhóm $-CHO$ trong phân tử Acetaldehyde ($CH_3CHO$) là:",
     "choices": ["+1", "-3", "0", "+3"],
     "answer": 0, "explanation": "Theo phương pháp tính theo từng nhóm nguyên tử liên kết, C trong nhóm -CHO có số oxh là +1."},
    {"id": "mc-c3-110", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Tính khối lượng từ bảo toàn e",
     "question": "Hòa tan hoàn toàn 11,2 gam Fe bằng dung dịch $HNO_3$ dư thu được khí NO duy nhất. Khối lượng dung dịch sau phản ứng nặng hơn hay nhẹ hơn khối lượng dung dịch $HNO_3$ ban đầu bao nhiêu gam?",
     "choices": ["Nặng hơn 5,2 gam", "Nặng hơn 11,2 gam", "Nhẹ hơn 6 gam", "Nặng hơn 6 gam"],
     "answer": 0, "explanation": "Khối lượng dung dịch tăng = Khối lượng kim loại cho vào - Khối lượng khí thoát ra = 11,2 - 6,0 = 5,2 gam."},
    {"id": "mc-c3-111", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Nhôm Anode",
     "question": "Trong công nghiệp luyện nhôm, người người ta điện phân nóng chảy $Al_2O_3$ (có mặt criolit). Tại Cực dương (Anode) làm bằng than chì (C), khí sinh ra chủ yếu là:",
     "choices": ["$O_2$ (và có thể tác dụng với C tạo $CO, CO_2$)", "$Cl_2$", "$H_2$", "$O_3$"],
     "answer": 0, "explanation": "Khí Oxi thoát ra tại cực dương (Anode)."},
    {"id": "mc-c3-112", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Điều chế HF",
     "question": "Axit Hydrofluoric (HF) có thể được điều chế bằng phản ứng nào?",
     "choices": ["Cho $CaF_2$ rắn tác dụng với $H_2SO_4$ đặc, nóng", "Điện phân dung dịch $NaF$", "Cho $F_2$ tác dụng với nước", "Cho $F_2$ tác dụng với $H_2$ ở nhiệt độ phòng"],
     "answer": 0, "explanation": "CaF2 rắn (florit) phản ứng với H2SO4 đặc tạo khí HF."},

    {"id": "mc-c3-113", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Xác định nhanh số OXH",
     "question": "Số oxi hóa của Lưu huỳnh trong ion Sulfite ($SO_3^{2-}$ ) là:",
     "choices": ["+4", "+6", "-2", "+2"],
     "answer": 0, "explanation": "Tổng số OXH bằng điện tích ion: $x + 3(-2) = -2 \Rightarrow x - 6 = -2 \Rightarrow x = +4$."},
    {"id": "mc-c3-114", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Lập PT dạng tổng quát",
     "question": "Hệ số của $HNO_3$ trong phản ứng: $M + HNO_3 \\rightarrow M(NO_3)_n + N_2O + H_2O$ là:",
     "choices": ["10n", "12n", "8n", "n"],
     "answer": 0, "explanation": "Bảo toàn nguyên tố Nitơ: N(muối) + N(khí) = 8n + 2n = 10n."},
    {"id": "mc-c3-115", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Pin nhiên liệu",
     "question": "Pin nhiên liệu $H_2 - O_2$ có ưu điểm nổi bật là:",
     "choices": ["Chỉ sinh ra nước tinh khiết, không gây ô nhiễm môi trường, hiệu suất chuyển hóa năng lượng cao", "Có thể sạc lại hàng nghìn lần", "Giá thành rất rẻ, vật liệu làm từ nhựa", "Sản sinh ra $CO_2$ rất tốt cho cây xanh"],
     "answer": 0, "explanation": "Sản phẩm duy nhất của quá trình này là Nước (H2O)."},
    {"id": "mc-c3-116", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Đặc tính thăng hoa của Iot",
     "question": "Để làm sạch hỗn hợp bột lẫn $NaCl$ và $I_2$, phương pháp đơn giản nhất là:",
     "choices": ["Đun nóng nhẹ hỗn hợp để $I_2$ thăng hoa, sau đó thu hồi $I_2$ bằng cách làm lạnh", "Hòa tan vào nước rồi lọc", "Cho tác dụng với dung dịch $AgNO_3$", "Dùng nam châm hút"],
     "answer": 0, "explanation": "Tính chất đặc trưng của Iot là dễ thăng hoa (chuyển trực tiếp từ rắn sang hơi) khi đun nóng nhẹ. NaCl là muối rất bền nhiệt, không bay hơi ở nhiệt độ đó. Hơi Iot ngưng tụ lại thành tinh thể tinh khiết."},
    
    {"id": "mc-c3-117", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Số oxh của nguyên tố khối d",
     "question": "Titanium (Ti, $Z=22$) thuộc nhóm IVB. Số oxi hóa cao nhất của Ti trong hợp chất thường là:",
     "choices": ["+4", "+2", "+6", "+8"],
     "answer": 0, "explanation": "Cấu hình e: $1s^2 2s^2 2p^6 3s^2 3p^6 3d^2 4s^2$. Tổng electron hóa trị ở phân lớp 3d và 4s là 4 $\\Rightarrow$ Nhường tối đa 4e, số oxi hóa cực đại là +4 (VD: $TiO_2$)."},
    {"id": "mc-c3-118", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Phản ứng phức tạo amoni",
     "question": "Trong phản ứng: $4Mg + 10HNO_3 \\rightarrow 4Mg(NO_3)_2 + NH_4NO_3 + 3H_2O$. Axit $HNO_3$ đóng vai trò gì?",
     "choices": ["Vừa là chất oxi hóa, vừa làm môi trường (tạo muối)", "Chỉ là chất oxi hóa", "Chỉ làm môi trường", "Vừa là chất khử, vừa làm môi trường"],
     "answer": 0, "explanation": "Đây là phản ứng oxi hóa khử mà HNO3 vừa cung cấp gốc NO3- (môi trường), vừa bị khử tạo muối amoni (chất oxi hóa)."},
    {"id": "mc-c3-119", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Tính E pin",
     "question": "Cho thế điện cực chuẩn: $E^0_{Zn^{2+}/Zn} = -0,76V$; $E^0_{Ag^+/Ag} = +0,80V$. Sức điện động chuẩn của pin điện hóa $Zn - Ag$ là:",
     "choices": ["$1,56V$", "$0,04V$", "$-1,56V$", "$1,00V$"],
     "answer": 0, "explanation": "Anode (cực âm, có thế nhỏ hơn): Zn. Cathode (cực dương, có thế lớn hơn): Ag. Sức điện động $E^0_{pin} = E^0_{Cathode} - E^0_{Anode} = (+0,80) - (-0,76) = 1,56 V$."},
    {"id": "mc-c3-120", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Hỗn hợp Halogen",
     "question": "Chất nào sau đây được gọi là 'nước Gia-ven' trong công nghiệp (dung dịch dùng để tẩy rửa, sát trùng)?",
     "choices": ["Dung dịch hỗn hợp $NaCl$ và $NaClO$ (Sodium hypochlorite)", "Dung dịch hỗn hợp $KCl$ và $KClO_3$", "Dung dịch $Ca(OCl)_2$", "Dung dịch chứa $HCl$ và $HClO_3$"],
     "answer": 0, "explanation": "Nước Javel được sản xuất bằng cách điện phân dung dịch NaCl không màng ngăn, hoặc sục Cl2 vào dung dịch NaOH loãng: $Cl_2 + 2NaOH \\rightarrow NaCl + NaClO + H_2O$. Thành phần chính là dung dịch NaCl và NaClO."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C3 Part 2 written successfully.")
