import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 2 HÓA HỌC 10: LIÊN KẾT HÓA HỌC ---
    # Nhóm 1, 2, 3: Quy tắc Octet
    {"id": "mc-c2-001", "chapter": "c2", "lesson": "b8", "level": "nb", "dang": "Quy tắc Octet",
     "question": "Quy tắc octet (bát tử) do Lewis đề xuất phát biểu rằng trong quá trình hình thành liên kết hóa học, các nguyên tử có xu hướng:",
     "choices": ["Nhường, nhận hoặc dùng chung electron để đạt cấu hình electron bền vững với 8 electron ở lớp ngoài cùng (giống khí hiếm)", "Luôn luôn nhường 8 electron", "Luôn luôn nhận 8 electron", "Tạo ra đúng 8 liên kết hóa học"],
     "answer": 0, "explanation": "Quy tắc Octet: Nguyên tử có xu hướng đạt cấu hình vỏ bão hòa (thường là 8 electron ngoài cùng, riêng He có 2e) giống khí hiếm gần nhất để trở nên bền vững."},
    {"id": "mc-c2-002", "chapter": "c2", "lesson": "b8", "level": "nb", "dang": "Áp dụng Octet cho Kim loại",
     "question": "Để đạt được cấu hình bền vững theo quy tắc octet, nguyên tử của các nguyên tố kim loại (nhóm IA, IIA, IIIA) thường có xu hướng:",
     "choices": ["Nhường các electron ở lớp ngoài cùng để trở thành ion dương (cation)", "Nhận thêm electron để trở thành ion âm (anion)", "Góp chung electron với các nguyên tử kim loại khác", "Giữ nguyên cấu hình electron"],
     "answer": 0, "explanation": "Kim loại có ít electron vỏ ngoài (1, 2, 3). Nhường số e này đi thì vỏ ngoài cùng mới lộ ra vỏ sát bên trong đã bão hòa 8e (hoặc 2e)."},
    {"id": "mc-c2-003", "chapter": "c2", "lesson": "b8", "level": "th", "dang": "Áp dụng Octet cho Phi kim",
     "question": "Khi hình thành liên kết với kim loại, nguyên tử phi kim nhóm VIIA (Halogen) có xu hướng:",
     "choices": ["Nhận 1 electron để đạt cấu hình 8 electron ngoài cùng", "Nhường 7 electron để đạt cấu hình bão hòa", "Góp chung 1 electron", "Nhận 2 electron"],
     "answer": 0, "explanation": "Phi kim nhóm VIIA có 7e ngoài cùng. Chạm tới 8e chỉ cần nhận thêm 1e từ kim loại (tạo anion $X^-$)."},
    {"id": "mc-c2-004", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Ngoại lệ Octet",
     "question": "Trong phân tử nào sau đây, nguyên tử trung tâm KHÔNG tuân theo quy tắc octet?",
     "choices": ["$PCl_5$", "$H_2O$", "$NH_3$", "$CO_2$"],
     "answer": 0, "explanation": "Trong $PCl_5$, nguyên tử P xung quanh nó có tới 5 liên kết $\\Rightarrow 10$ electron (bát tử mở rộng - hypervalent). $H_2O, NH_3, CO_2$ đều tuân thủ đúng 8e quanh nguyên tử trung tâm."},

    {"id": "mc-c2-005", "chapter": "c2", "lesson": "b8", "level": "th", "dang": "Khí hiếm",
     "question": "Nguyên tử Helium (He) không tuân theo quy tắc 8 electron nhưng vẫn rất bền vững vì:",
     "choices": ["Lớp electron ngoài cùng (lớp 1) đã bão hòa với 2 electron", "Nó có 8 proton trong hạt nhân", "Nó có độ âm điện lớn nhất", "Nó nằm ở chu kì 8"],
     "answer": 0, "explanation": "He (Z=2) có cấu hình $1s^2$. Lớp 1 (K) chỉ chứa tối đa 2e, nên có 2e đã là bão hòa và bền vững (quy tắc duet - nhị tử)."},
    {"id": "mc-c2-006", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Biểu diễn quá trình nhường nhận",
     "question": "Quá trình hình thành ion của nguyên tử Calcium (Ca, Z=20) theo quy tắc octet được viết là:",
     "choices": ["$\\text{Ca} \\rightarrow \\text{Ca}^{2+} + 2e^-$", "$\\text{Ca} + 2e^- \\rightarrow \\text{Ca}^{2-}$", "$\\text{Ca} \\rightarrow \\text{Ca}^+ + 1e^-$", "$\\text{Ca} \\rightarrow \\text{Ca}^{6+} + 6e^-$"],
     "answer": 0, "explanation": "Ca thuộc nhóm IIA, có 2e hóa trị. Ca có xu hướng nhường 2e để tạo cation $Ca^{2+}$ có cấu hình của Argon."},
    {"id": "mc-c2-007", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Cấu hình giống nhau",
     "question": "Các ion $Na^+, Mg^{2+}, F^-, O^{2-}$ đều có cùng cấu hình electron. Đó là cấu hình của khí hiếm nào?",
     "choices": ["Neon (Ne, Z=10)", "Argon (Ar, Z=18)", "Helium (He, Z=2)", "Krypton (Kr, Z=36)"],
     "answer": 0, "explanation": "Na (11) nhường 1e = 10e. Mg (12) nhường 2e = 10e. F (9) nhận 1e = 10e. O (8) nhận 2e = 10e. Tất cả đều đạt cấu hình $1s^2 2s^2 2p^6$ của Neon."},
    {"id": "mc-c2-008", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Đếm số electron hóa trị",
     "question": "Nguyên tử nguyên tố X có số hiệu nguyên tử Z=15. Để đạt cấu hình bền vững, X sẽ nhận thêm bao nhiêu electron khi tạo liên kết ion?",
     "choices": ["Nhận 3 electron", "Nhường 5 electron", "Nhận 5 electron", "Nhường 3 electron"],
     "answer": 0, "explanation": "Z=15 (Phosphorus). Cấu hình: $1s^2 2s^2 2p^6 3s^2 3p^3$. Có 5e lớp ngoài. Thiếu 3e để đạt 8. Vậy X có xu hướng nhận 3e (tạo ion $P^{3-}$ trong các phosphide)."},

    # Nhóm 4, 5, 6: Liên kết Ion
    {"id": "mc-c2-009", "chapter": "c2", "lesson": "b9", "level": "nb", "dang": "Khái niệm liên kết ion",
     "question": "Liên kết ion là liên kết hóa học được hình thành bởi:",
     "choices": ["Lực hút tĩnh điện giữa các ion mang điện tích trái dấu", "Sự dùng chung các cặp electron", "Lực hấp dẫn giữa các hạt nhân", "Sự che phủ các orbital nguyên tử"],
     "answer": 0, "explanation": "Bản chất liên kết ion: Lực hút tĩnh điện (Coulomb) giữa Cation (+) và Anion (-)."},
    {"id": "mc-c2-010", "chapter": "c2", "lesson": "b9", "level": "nb", "dang": "Điều kiện tạo liên kết ion",
     "question": "Liên kết ion thường được hình thành giữa hai loại nguyên tố nào?",
     "choices": ["Kim loại điển hình và phi kim điển hình", "Hai phi kim giống nhau", "Hai kim loại khác nhau", "Một phi kim và một khí hiếm"],
     "answer": 0, "explanation": "Kim loại điển hình (nhóm IA, IIA) dễ nhường e. Phi kim điển hình (nhóm VIA, VIIA) dễ nhận e. Sự trao đổi e này tạo ra các ion trái dấu."},
    {"id": "mc-c2-011", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Dự đoán loại liên kết",
     "question": "Trong các hợp chất sau: $NaCl, H_2O, CO_2, CH_4$. Hợp chất nào có liên kết ion?",
     "choices": ["$NaCl$", "$H_2O$", "$CO_2$", "$CH_4$"],
     "answer": 0, "explanation": "Na (kim loại kiềm) và Cl (phi kim mạnh - halogen). Liên kết tạo thành là liên kết ion ($Na^+$ và $Cl^-$). Còn lại đều là phi kim với phi kim (liên kết cộng hóa trị)."},
    {"id": "mc-c2-012", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Cấu tạo muối",
     "question": "Phân tử Calcium chloride ($CaCl_2$) được hình thành từ sự kết hợp của các ion nào?",
     "choices": ["Một ion $Ca^{2+}$ và hai ion $Cl^-$", "Một ion $Ca^{2+}$ và một ion $Cl_2^{2-}$", "Hai ion $Ca^+$ và một ion $Cl^{2-}$", "Một ion $Ca^+$ và một ion $Cl^-$"],
     "answer": 0, "explanation": "Ca nhường 2e thành $Ca^{2+}$. Cl nhận 1e thành $Cl^-$. Cần 2 nguyên tử Cl nhận 2e từ 1 nguyên tử Ca $\\Rightarrow Ca^{2+}$ và $2Cl^-$."},

    {"id": "mc-c2-013", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Viết PT tạo ion",
     "question": "Phương trình biểu diễn sự hình thành hợp chất ion $MgO$ từ các nguyên tử tương ứng là:",
     "choices": ["$\\text{Mg} \\rightarrow \\text{Mg}^{2+} + 2e$ ; $\\text{O} + 2e \\rightarrow \\text{O}^{2-}$ ; $\\text{Mg}^{2+} + \\text{O}^{2-} \\rightarrow \\text{MgO}$", "$\\text{Mg} + 2e \\rightarrow \\text{Mg}^{2-}$ ; $\\text{O} \\rightarrow \\text{O}^{2+} + 2e$ ; $\\text{Mg}^{2-} + \\text{O}^{2+} \\rightarrow \\text{MgO}$", "$\\text{Mg} \\rightarrow \\text{Mg}^+ + e$ ; $\\text{O} + e \\rightarrow \\text{O}^-$ ; $\\text{Mg}^+ + \\text{O}^- \\rightarrow \\text{MgO}$", "$\\text{Mg} \\rightarrow \\text{Mg}^{2+} + 2e$ ; $\\text{O}_2 + 4e \\rightarrow 2\\text{O}^{2-}$ ; $\\text{Mg}^{2+} + \\text{O}^{2-} \\rightarrow \\text{MgO}$"],
     "answer": 0, "explanation": "Đáp án đúng biểu diễn đầy đủ quá trình tạo ion đơn giản: Mg nhường 2e tạo $Mg^{2+}$, O nhận 2e tạo $O^{2-}$, sau đó lực tĩnh điện hút 2 ion lại tạo phân tử MgO (viết gọn)."},
    {"id": "mc-c2-014", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Bài tập tìm ion qua electron",
     "question": "Một cation $M^{3+}$ và một anion $X^-$ đều có 10 electron. Công thức của hợp chất tạo bởi M và X là:",
     "choices": ["$AlF_3$", "$AlCl_3$", "$MgF_2$", "$FeCl_3$"],
     "answer": 0, "explanation": "$M^{3+}$ có 10e $\\Rightarrow M = 13$ (Aluminium). $X^-$ có 10e $\\Rightarrow X = 9$ (Fluorine). Hợp chất là $AlF_3$."},
    {"id": "mc-c2-015", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Điện hóa trị",
     "question": "Điện hóa trị của nguyên tố Nitrogen (N) và Magnesium (Mg) trong hợp chất Magnesium nitride ($Mg_3N_2$) lần lượt là:",
     "choices": ["3- và 2+", "3+ và 2-", "-3 và +2", "III và II"],
     "answer": 0, "explanation": "Hợp chất ion: điện hóa trị bằng điện tích của ion đó. Trong $Mg_3N_2$, ion là $Mg^{2+}$ (điện hóa trị 2+) và $N^{3-}$ (điện hóa trị 3-). (Chú ý cách viết điện hóa trị: số trước, dấu sau)."},
    {"id": "mc-c2-016", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Cấu trúc mạng tinh thể",
     "question": "Mạng tinh thể muối ăn ($NaCl$) có đặc điểm nào sau đây?",
     "choices": ["Mạng lập phương tâm diện, mỗi ion $Na^+$ được bao quanh bởi 6 ion $Cl^-$ và ngược lại", "Mạng lục giác, các phân tử NaCl xếp chồng lên nhau", "Chỉ gồm các phân tử NaCl độc lập chuyển động tự do", "Các ion $Na^+$ và $Cl^-$ nằm xen kẽ ở các đỉnh của hình tứ diện"],
     "answer": 0, "explanation": "Tinh thể NaCl có cấu trúc lập phương tâm diện (FCC), số phối trí là 6 (mỗi Na+ được bao bọc bởi 6 Cl- ở 6 hướng vuông góc và ngược lại). Không tồn tại phân tử NaCl độc lập trong tinh thể rắn."},

    # Nhóm 7, 8, 9: Liên kết cộng hóa trị
    {"id": "mc-c2-017", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Khái niệm liên kết CHT",
     "question": "Liên kết cộng hóa trị là liên kết hóa học được hình thành giữa hai nguyên tử bằng:",
     "choices": ["Một hay nhiều cặp electron dùng chung", "Sự nhường hoàn toàn electron", "Lực hút tĩnh điện giữa các ion", "Đám mây electron tự do"],
     "answer": 0, "explanation": "Cộng hóa trị (Covalent bond) là sự góp chung electron để cùng nhau đạt octet (do 2 nguyên tử đều thiếu e nên không ai nhường ai)."},
    {"id": "mc-c2-018", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Liên kết CHT không phân cực",
     "question": "Liên kết cộng hóa trị KHÔNG PHÂN CỰC thường xuất hiện trong các phân tử nào?",
     "choices": ["Các phân tử đơn chất được tạo bởi hai nguyên tử phi kim giống nhau (như $H_2, Cl_2, N_2$)", "Hợp chất giữa kim loại và phi kim (như $NaCl$)", "Hợp chất giữa hai phi kim khác nhau có độ âm điện chênh lệch lớn (như $HCl$)", "Tất cả các loại hợp chất hóa học"],
     "answer": 0, "explanation": "Giữa 2 nguyên tử giống hệt nhau (cùng độ âm điện), cặp electron dùng chung nằm CHÍNH GIỮA, không bị lệch về bên nào $\\Rightarrow$ Liên kết không phân cực."},
    {"id": "mc-c2-019", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Liên kết CHT phân cực",
     "question": "Trong phân tử Hydrogen chloride ($HCl$), cặp electron dùng chung có đặc điểm gì?",
     "choices": ["Bị lệch về phía nguyên tử Chlorine do Chlorine có độ âm điện lớn hơn", "Bị lệch về phía nguyên tử Hydrogen do Hydrogen nhẹ hơn", "Nằm chính giữa hai nguyên tử", "Chuyển hẳn sang nguyên tử Chlorine để tạo ion"],
     "answer": 0, "explanation": "Độ âm điện $Cl (3.16) > H (2.20)$. Cặp e dùng chung bị kéo lệch về phía Cl $\\Rightarrow$ Liên kết CHT phân cực (có cực)."},
    {"id": "mc-c2-020", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Liên kết cho nhận",
     "question": "Liên kết cho - nhận (liên kết phối trí) là một trường hợp đặc biệt của liên kết cộng hóa trị, trong đó:",
     "choices": ["Cặp electron dùng chung chỉ do một nguyên tử đóng góp", "Hai nguyên tử mỗi bên đóng góp một electron", "Một nguyên tử nhường hẳn electron cho nguyên tử kia", "Không có cặp electron nào được dùng chung"],
     "answer": 0, "explanation": "Trong liên kết cho - nhận (kí hiệu mũi tên $\\rightarrow$), cặp e dùng chung do 1 nguyên tử có dư cặp e tự do cung cấp toàn bộ, nguyên tử kia chỉ cung cấp AO trống để nhận."},

    {"id": "mc-c2-021", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Công thức electron",
     "question": "Trong công thức electron của phân tử Nitrogen ($N_2$), giữa hai nguyên tử N có bao nhiêu cặp electron dùng chung?",
     "choices": ["3 cặp", "1 cặp", "2 cặp", "4 cặp"],
     "answer": 0, "explanation": "N (nhóm VA) có 5e ngoài cùng. Để đạt 8e, mỗi N cần thêm 3e. Hai nguyên tử N sẽ góp chung 3e tạo thành 3 CẶP e dùng chung (Liên kết ba: $N \\equiv N$)."},
    {"id": "mc-c2-022", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Biểu diễn liên kết đôi",
     "question": "Phân tử nào sau đây có chứa liên kết đôi trong công thức cấu tạo?",
     "choices": ["$CO_2$", "$H_2$", "$N_2$", "$HCl$"],
     "answer": 0, "explanation": "C: 4e (cần 4), O: 6e (cần 2). C góp 2e với O thứ nhất (tạo 1 nối đôi), góp 2e với O thứ hai (tạo nối đôi thứ 2). Cấu tạo: $O = C = O$."},
    {"id": "mc-c2-023", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Phân biệt loại liên kết trong phân tử phức tạp",
     "question": "Trong phân tử acid $H_2SO_4$, liên kết giữa nguyên tử S và nguyên tử O (không gắn với H) thường được biểu diễn theo quy tắc bát tử là loại liên kết gì?",
     "choices": ["Liên kết cho - nhận", "Liên kết ion", "Liên kết ba", "Liên kết kim loại"],
     "answer": 0, "explanation": "Để S và O đều thỏa mãn bát tử, S (có 6e) dùng 2e độc thân tạo 2 lk đơn với 2 nhóm -OH. Còn 2 nguyên tử O còn lại (mỗi O cần 2e) sẽ nhận 2 cặp e tự do từ S. Biểu diễn này là liên kết cho-nhận ($S \\rightarrow O$). (Thuyết hiện đại cho phép S vượt bát tử tạo nối đôi S=O, nhưng theo SGK phổ thông cũ quy tắc octet thì là cho-nhận)."},
    {"id": "mc-c2-024", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Cộng hóa trị của nguyên tố",
     "question": "Cộng hóa trị của nguyên tố Carbon trong phân tử $CH_4$ và nguyên tố Oxygen trong phân tử $H_2O$ lần lượt là:",
     "choices": ["4 và 2", "4+ và 2-", "+4 và -2", "4 và 8"],
     "answer": 0, "explanation": "Cộng hóa trị = số liên kết cộng hóa trị mà nguyên tử đó tạo ra. C tạo 4 liên kết đơn với H $\\Rightarrow$ cộng hóa trị 4. O tạo 2 lk đơn với H $\\Rightarrow$ cộng hóa trị 2. (Không có dấu)."},

    # Nhóm 10, 11, 12: Sự phân cực dựa trên Hiệu độ âm điện
    {"id": "mc-c2-025", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Quy ước hiệu độ âm điện",
     "question": "Theo quy ước thông thường, liên kết giữa hai nguyên tử được coi là liên kết ION khi hiệu độ âm điện ($\\Delta\\chi$) giữa chúng thỏa mãn điều kiện nào?",
     "choices": ["$\\Delta\\chi \\ge 1,7$", "$0,4 \\le \\Delta\\chi < 1,7$", "$0 \\le \\Delta\\chi < 0,4$", "$\\Delta\\chi = 0$"],
     "answer": 0, "explanation": "Quy ước Pauling: $\\Delta\\chi < 0.4$ (CHT ko phân cực); $0.4 \\le \\Delta\\chi < 1.7$ (CHT phân cực); $\\Delta\\chi \\ge 1.7$ (Ion)."},
    {"id": "mc-c2-026", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Tính hiệu độ âm điện",
     "question": "Cho độ âm điện của $H=2,20$; $O=3,44$. Liên kết O-H trong phân tử nước thuộc loại liên kết gì?",
     "choices": ["Liên kết cộng hóa trị phân cực", "Liên kết ion", "Liên kết cộng hóa trị không phân cực", "Liên kết kim loại"],
     "answer": 0, "explanation": "$\\Delta\\chi = 3.44 - 2.20 = 1.24$. Nằm trong khoảng $[0.4; 1.7) \\Rightarrow$ Liên kết CHT phân cực."},
    {"id": "mc-c2-027", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Kiểm tra ranh giới",
     "question": "Cho độ âm điện của $K=0,82$; $Cl=3,16$. Liên kết trong phân tử KCl thuộc loại:",
     "choices": ["Liên kết ion", "Liên kết cộng hóa trị phân cực", "Liên kết cộng hóa trị không phân cực", "Liên kết cho - nhận"],
     "answer": 0, "explanation": "$\\Delta\\chi = 3.16 - 0.82 = 2.34 > 1.7$. Là liên kết ion (Kim loại điển hình - phi kim điển hình)."},
    {"id": "mc-c2-028", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Ngoại lệ hiệu độ âm điện",
     "question": "Mặc dù hiệu độ âm điện của $H$ (2,2) và $F$ (3,98) là 1,78 ($> 1,7$), hợp chất $HF$ (Hydrogen fluoride) ở thể khí thực chất là hợp chất có liên kết:",
     "choices": ["Cộng hóa trị phân cực rất mạnh", "Ion hoàn toàn", "Cộng hóa trị không phân cực", "Liên kết hydro"],
     "answer": 0, "explanation": "Đây là một ngoại lệ của quy tắc 1,7. HF là chất khí ở điều kiện thường, tạo bởi 2 phi kim. Mặc dù $\\Delta\\chi = 1,78$, thực nghiệm xác nhận liên kết trong HF mang bản chất cộng hóa trị phân cực rất mạnh (không phải ion 100%)."},

    # Nhóm 13, 14: Sự lai hóa và Hình học phân tử
    {"id": "mc-c2-029", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Khái niệm Lai hóa",
     "question": "Sự lai hóa orbital nguyên tử là sự:",
     "choices": ["Tổ hợp (trộn lẫn) các orbital nguyên tử khác nhau trong cùng một nguyên tử để tạo ra các orbital lai hóa có năng lượng và hình dạng giống hệt nhau", "Sự xen phủ các orbital của hai nguyên tử khác nhau để tạo liên kết", "Sự nhường electron từ AO này sang AO khác", "Sự chuyển e lên trạng thái kích thích"],
     "answer": 0, "explanation": "Lai hóa (Hybridization) là mô hình trộn lẫn các AO (ví dụ 1 AO s và 3 AO p) tạo ra các AO mới đồng nhất ($sp^3$) để tham gia liên kết, giải thích hình học phân tử."},
    {"id": "mc-c2-030", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Lai hóa sp3",
     "question": "Trong phân tử Methane ($CH_4$), nguyên tử Carbon ở trạng thái lai hóa nào và phân tử có hình dạng hình học gì?",
     "choices": ["Lai hóa $sp^3$, hình tứ diện đều", "Lai hóa $sp^2$, hình tam giác phẳng", "Lai hóa $sp$, hình đường thẳng", "Không lai hóa, hình vuông"],
     "answer": 0, "explanation": "Nguyên tử C liên kết với 4 nguyên tử H $\\Rightarrow$ dùng 4 AO lai hóa $sp^3$ hướng về 4 đỉnh của hình tứ diện đều (góc liên kết $\\approx 109.5^\\circ$)."},
    {"id": "mc-c2-031", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Lai hóa sp2",
     "question": "Phân tử nào sau đây có nguyên tử trung tâm ở trạng thái lai hóa $sp^2$?",
     "choices": ["$BF_3$ (Boron trifluoride)", "$NH_3$", "$H_2O$", "$BeCl_2$"],
     "answer": 0, "explanation": "$BF_3$ có B trung tâm liên kết với 3 nguyên tử F, không còn cặp e tự do $\\Rightarrow 3$ vùng mật độ electron $\\Rightarrow$ lai hóa $sp^2$ (hình tam giác phẳng, góc $120^\\circ$)."},
    {"id": "mc-c2-032", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Dự đoán góc liên kết",
     "question": "Tại sao góc liên kết H-O-H trong phân tử nước ($104,5^\\circ$) lại nhỏ hơn góc tứ diện đều ($109,5^\\circ$) dù nguyên tử Oxi cũng lai hóa $sp^3$?",
     "choices": ["Do sự đẩy của 2 cặp electron chưa tham gia liên kết trên nguyên tử Oxi ép các liên kết O-H lại gần nhau hơn", "Do nguyên tử Hydro quá lớn", "Do nguyên tử Oxi lai hóa $sp^2$", "Do nước ở trạng thái lỏng"],
     "answer": 0, "explanation": "Theo thuyết đẩy cặp electron hóa trị (VSEPR), cặp e tự do (lone pair) đẩy mạnh hơn cặp e liên kết (bond pair). Nước có 2 cặp e tự do $\\Rightarrow$ đẩy mạnh, ép góc H-O-H hẹp lại thành $104.5^\\circ$."},

    # Nhóm 15, 16: Liên kết Sigma và Pi
    {"id": "mc-c2-033", "chapter": "c2", "lesson": "b12", "level": "nb", "dang": "Định nghĩa Sigma",
     "question": "Liên kết $\\sigma$ (sigma) được hình thành do sự xen phủ:",
     "choices": ["Xen phủ trục (trục liên kết đi qua vùng xen phủ)", "Xen phủ bên (vùng xen phủ nằm hai bên trục liên kết)", "Lực tĩnh điện", "Không xen phủ"],
     "answer": 0, "explanation": "Liên kết $\\sigma$ là liên kết bền vững nhất trong CHT, tạo ra do các AO xen phủ dọc theo trục nối 2 hạt nhân (xen phủ trục)."},
    {"id": "mc-c2-034", "chapter": "c2", "lesson": "b12", "level": "nb", "dang": "Định nghĩa Pi",
     "question": "Liên kết $\\pi$ (pi) thường xuất hiện khi nào và được hình thành do sự xen phủ gì?",
     "choices": ["Xuất hiện trong liên kết đôi hoặc ba, do sự xen phủ bên của các orbital p", "Xuất hiện trong mọi liên kết đơn, do xen phủ trục", "Là liên kết ion biến dạng", "Chỉ xuất hiện ở phân tử khí hiếm"],
     "answer": 0, "explanation": "Liên kết $\\pi$ yếu hơn $\\sigma$, tạo ra do 2 AO p song song xen phủ bên. Luôn đi kèm với 1 liên kết $\\sigma$ trong các nối đôi, nối ba."},
    {"id": "mc-c2-035", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Đếm sigma và pi",
     "question": "Trong phân tử Ethyne (Acetylene, $HC \\equiv CH$), số lượng liên kết $\\sigma$ và liên kết $\\pi$ là bao nhiêu?",
     "choices": ["3 liên kết $\\sigma$ và 2 liên kết $\\pi$", "1 liên kết $\\sigma$ và 2 liên kết $\\pi$", "2 liên kết $\\sigma$ và 3 liên kết $\\pi$", "5 liên kết $\\sigma$"],
     "answer": 0, "explanation": "Phân tử có 2 liên kết đơn C-H (đều là $\\sigma$). Giữa 2 nguyên tử C có 1 liên kết ba (chứa 1 $\\sigma$ và 2 $\\pi$). Tổng cộng: $2 + 1 = 3\\sigma$ và $2\\pi$."},
    {"id": "mc-c2-036", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Đếm sigma phân tử lớn",
     "question": "Trong phân tử acid acetic ($CH_3COOH$), tổng số liên kết $\\sigma$ là bao nhiêu?",
     "choices": ["7", "6", "8", "5"],
     "answer": 0, "explanation": "Khai triển CTCT: Nhóm CH3 có 3 lk C-H. Lk C-C. Nối đôi C=O (có 1 $\\sigma$, 1 $\\pi$). Nhóm O-H có lk C-O và lk O-H. Tổng $\\sigma = 3(C-H) + 1(C-C) + 1(C=O) + 1(C-O) + 1(O-H) = 7$ liên kết $\\sigma$."},

    # Nhóm 17, 18, 19: Tính chất các loại hợp chất
    {"id": "mc-c2-037", "chapter": "c2", "lesson": "b9", "level": "nb", "dang": "Tính chất hợp chất ion",
     "question": "Các hợp chất ion thường có tính chất vật lí nào sau đây?",
     "choices": ["Thể rắn ở điều kiện thường, nhiệt độ nóng chảy và nhiệt độ sôi cao", "Thể lỏng hoặc khí, dễ bay hơi", "Dễ hòa tan trong các dung môi không phân cực như benzen", "Nhiệt độ nóng chảy rất thấp"],
     "answer": 0, "explanation": "Lực hút tĩnh điện trong mạng tinh thể ion rất mạnh, cần nhiệt năng lớn để phá vỡ. Do đó muối ăn và các hợp chất ion có nhiệt độ nóng chảy cao, cứng nhưng giòn."},
    {"id": "mc-c2-038", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Khả năng dẫn điện ion",
     "question": "Hợp chất ion có khả năng dẫn điện trong điều kiện nào?",
     "choices": ["Khi ở trạng thái nóng chảy hoặc khi tan trong nước (tạo dung dịch)", "Khi ở trạng thái tinh thể rắn", "Không bao giờ dẫn điện", "Luôn dẫn điện trong mọi trạng thái"],
     "answer": 0, "explanation": "Dẫn điện cần các hạt mang điện di chuyển TỰ DO. Ở thể rắn, ion bị cố định trong mạng lưới (không dẫn điện). Khi nóng chảy hoặc hòa tan, lưới bị phá vỡ, ion tự do di chuyển (dẫn điện)."},
    {"id": "mc-c2-039", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Tính chất hợp chất CHT",
     "question": "Trái ngược với hợp chất ion, các chất có liên kết cộng hóa trị phân tử (như $I_2, CO_2$) thường:",
     "choices": ["Có nhiệt độ nóng chảy và nhiệt độ sôi thấp, có thể tồn tại ở thể khí, lỏng, rắn", "Đều là chất rắn rất cứng", "Luôn dẫn điện tốt trong dung dịch", "Không tan trong bất kì dung môi nào"],
     "answer": 0, "explanation": "Giữa các phân tử CHT chỉ có lực hút liên phân tử (lực van der Waals) rất yếu, nên chúng dễ nóng chảy, bay hơi."},
    {"id": "mc-c2-040", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Nhận biết chất mạng tinh thể",
     "question": "Chất rắn nào sau đây không phải là mạng tinh thể ion mà là mạng tinh thể nguyên tử (cộng hóa trị) rất cứng và có nhiệt độ nóng chảy cực kì cao?",
     "choices": ["Kim cương (C)", "Muối ăn (NaCl)", "Đá vôi (CaCO3)", "Nước đá (H2O)"],
     "answer": 0, "explanation": "Kim cương (hoặc thạch anh SiO2) là mạng tinh thể CỘNG HÓA TRỊ KHỔNG LỒ (tinh thể nguyên tử). Các nguyên tử C liên kết vô tận bằng lk cộng hóa trị rất bền vững $\\Rightarrow$ Cực kì cứng, nóng chảy $> 3500^\\circ\\text{C}$."},

    # Nhóm 20, 21: Liên kết Hydrogen
    {"id": "mc-c2-041", "chapter": "c2", "lesson": "b13", "level": "nb", "dang": "Điều kiện liên kết H",
     "question": "Liên kết hydrogen được hình thành giữa nguyên tử Hydrogen và các nguyên tử nào?",
     "choices": ["Các nguyên tử có độ âm điện lớn và có cặp electron tự do (thường là F, O, N)", "Các nguyên tử kim loại kiềm", "Mọi nguyên tử phi kim", "Các khí hiếm"],
     "answer": 0, "explanation": "Điều kiện: H phải liên kết cộng hóa trị với 1 nguyên tử rất âm điện (F, O, N) để bị phân cực dương ($H^{\\delta+}$). Sau đó $H^{\\delta+}$ này hút cặp e tự do của 1 nguyên tử F, O, N khác."},
    {"id": "mc-c2-042", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Vai trò liên kết H",
     "question": "Liên kết hydrogen có ảnh hưởng như thế nào đến tính chất vật lí của nước ($H_2O$)?",
     "choices": ["Làm cho nước có nhiệt độ sôi cao bất thường so với hợp chất của các nguyên tố cùng nhóm (như $H_2S$)", "Làm cho nước dễ bay hơi hơn", "Làm cho nước không thể đóng băng", "Làm nước đổi màu"],
     "answer": 0, "explanation": "Các phân tử $H_2O$ tụ tập lại thành cụm lớn nhờ liên kết H (lực hút tĩnh điện yếu giữa H của phân tử này và O của phân tử kia). Cần thêm nhiệt lượng để phá vỡ liên kết H này $\\Rightarrow$ Nhiệt độ sôi rất cao ($100^\\circ\\text{C}$) so với $H_2S$ ($-60^\\circ\\text{C}$)."},
    {"id": "mc-c2-043", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Biểu diễn liên kết H",
     "question": "Liên kết hydrogen giữa 2 phân tử Ethanol ($C_2H_5OH$) được biểu diễn bằng nét đứt (...) tại vị trí nào sau đây?",
     "choices": ["$C_2H_5O-H \\dots O(H)-C_2H_5$", "$C_2H_5-O \\dots H-O-C_2H_5$", "$C-C \\dots O-H$", "$H-C \\dots O-H$"],
     "answer": 0, "explanation": "Liên kết H hình thành giữa nguyên tử H linh động (của nhóm -OH thứ nhất) với cặp e tự do của nguyên tử O (của nhóm -OH thứ hai). Biểu diễn đúng: $-O-H \\dots O-$."},
    {"id": "mc-c2-044", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Tính chất băng đá",
     "question": "Vì sao nước đá nổi trên nước lỏng?",
     "choices": ["Vì ở trạng thái rắn, các phân tử nước sắp xếp tạo mạng lưới tinh thể tứ diện với nhiều khoảng trống nhờ liên kết hydrogen, làm thể tích tăng và khối lượng riêng giảm", "Vì nước đá hấp thụ không khí vào bên trong", "Vì phân tử nước đá nhẹ hơn phân tử nước lỏng", "Vì nước đá bị mất đi một số nguyên tử Hydrogen"],
     "answer": 0, "explanation": "Tinh thể nước đá có cấu trúc rỗng (do mỗi nguyên tử O tạo 4 liên kết H hướng ra 4 phía tứ diện). Khi nóng chảy, cấu trúc này vỡ, phân tử xếp khít lại $\\Rightarrow D_{\\text{rắn}} < D_{\\text{lỏng}}$."},

    # Nhóm 22, 23: Tương tác Van der Waals
    {"id": "mc-c2-045", "chapter": "c2", "lesson": "b13", "level": "nb", "dang": "Khái niệm Van der waals",
     "question": "Tương tác van der Waals là gì?",
     "choices": ["Lực hút tĩnh điện rất yếu giữa các phân tử (hoặc nguyên tử) do sự xuất hiện các lưỡng cực tạm thời và lưỡng cực cảm ứng", "Lực liên kết rất mạnh giữa các nguyên tử cacbon", "Lực đẩy giữa hai hạt nhân nguyên tử", "Lực hạt nhân yếu"],
     "answer": 0, "explanation": "Lực van der Waals là tương tác liên phân tử yếu, có mặt ở MỌI phân tử, phụ thuộc lớn vào khối lượng, kích thước và hình dạng phân tử."},
    {"id": "mc-c2-046", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Ảnh hưởng đến nhiệt độ sôi",
     "question": "Trong dãy Halogen: $F_2$ (khí), $Cl_2$ (khí), $Br_2$ (lỏng), $I_2$ (rắn). Trạng thái tồn tại và nhiệt độ sôi tăng dần là do đâu?",
     "choices": ["Do khối lượng phân tử và kích thước đám mây electron tăng, làm tương tác van der Waals giữa các phân tử mạnh lên", "Do độ âm điện tăng", "Do tính phi kim tăng", "Do số liên kết cộng hóa trị trong phân tử tăng"],
     "answer": 0, "explanation": "Từ $F_2$ đến $I_2$, số lượng electron tăng, đám mây electron càng to thì càng dễ bị phân cực tạm thời (độ phân cực hóa tăng). Tương tác VDW càng mạnh $\\Rightarrow$ Trạng thái chuyển từ khí $\\rightarrow$ lỏng $\\rightarrow$ rắn."},
    {"id": "mc-c2-047", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "So sánh VDW",
     "question": "Cho các khí hiếm: He, Ne, Ar, Kr, Xe. Khí hiếm nào có nhiệt độ sôi CAO NHẤT?",
     "choices": ["Xe", "He", "Ne", "Ar"],
     "answer": 0, "explanation": "Khí hiếm không có liên kết hóa học, chỉ hút nhau bằng tương tác VDW. Xe có phân tử khối lớn nhất (131), đám mây e lớn nhất $\\Rightarrow$ tương tác VDW lớn nhất $\\Rightarrow$ nhiệt độ sôi cao nhất."},
    {"id": "mc-c2-048", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Phân biệt LK H và VDW",
     "question": "Hợp chất nào sau đây có nhiệt độ sôi cao nhất? (Cho phân tử khối xấp xỉ nhau: $CH_3-CH_2-OH, CH_3-O-CH_3, CH_3-CH_2-CH_3$)",
     "choices": ["$CH_3-CH_2-OH$ (Ethanol)", "$CH_3-O-CH_3$ (Dimethyl ether)", "$CH_3-CH_2-CH_3$ (Propane)", "Bằng nhau"],
     "answer": 0, "explanation": "Propane chỉ có VDW (ko phân cực). Ether có VDW (hơi phân cực). Ethanol có VDW và có LIÊN KẾT HYDROGEN liên phân tử (rất mạnh so với VDW). Do đó nhiệt độ sôi của rượu (ethanol) lớn hơn hẳn ($78^\\circ\\text{C}$ so với âm độ của 2 chất kia)."},

    # 12 Câu cuối củng cố kiến thức
    {"id": "mc-c2-049", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Viết CT Lewis",
     "question": "Trong công thức Lewis của phân tử $SO_2$ (lưu huỳnh dioxide), để thỏa mãn quy tắc bát tử, phân tử phải có:",
     "choices": ["Một liên kết đôi $S=O$, một liên kết cho-nhận $S \\rightarrow O$, và S còn 1 cặp e tự do", "Hai liên kết đôi $S=O$", "Hai liên kết đơn $S-O$", "Một liên kết ba"],
     "answer": 0, "explanation": "S có 6e. O có 6e. S=O lấy đi 2e của S (còn 4e). S và O này đều đủ 8e. Nguyên tử O thứ 2 cần 2e $\\Rightarrow$ S sẽ lấy 2e dư để tạo liên kết cho-nhận cho O kia. Vậy S còn lại $4-2 = 2e$ (1 cặp e tự do). Hình dạng góc."},
    {"id": "mc-c2-050", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Phân tích trạng thái phân tử",
     "question": "Chất nào sau đây KHÔNG có phân tử riêng rẽ trong trạng thái tinh thể ở điều kiện thường?",
     "choices": ["$KCl$", "$H_2O$ (nước đá)", "$I_2$", "$CO_2$ (đá khô)"],
     "answer": 0, "explanation": "KCl là hợp chất ion. Mạng tinh thể ion là sự luân phiên của vô số ion $K^+$ và $Cl^-$ nối tiếp nhau, không có ranh giới phân tử KCl độc lập. (Các chất kia là tinh thể phân tử)."},
    {"id": "mc-c2-051", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Cộng hóa trị phân tử G",
     "question": "Phân tử nào sau đây có liên kết cộng hóa trị phân cực MẠNH NHẤT? (Biết $\\chi$: $H(2.2), C(2.55), N(3.04), O(3.44), F(3.98)$)",
     "choices": ["H-F", "H-O (trong nước)", "H-N (trong $NH_3$)", "C-H (trong $CH_4$)"],
     "answer": 0, "explanation": "Tính hiệu độ âm điện: $H-F (1.78) > H-O (1.24) > H-N (0.84) > C-H (0.35)$. HF phân cực mạnh nhất."},
    
    {"id": "mc-c2-052", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Góc liên kết 180",
     "question": "Phân tử $BeCl_2$ (beryllium chloride ở thể khí) có góc liên kết $Cl-Be-Cl$ là bao nhiêu độ?",
     "choices": ["$180^\\circ$ (Đường thẳng)", "$120^\\circ$ (Tam giác)", "$109,5^\\circ$ (Tứ diện)", "$90^\\circ$ (Vuông)"],
     "answer": 0, "explanation": "Be (Z=4) có 2 electron hóa trị. Góp chung với 2 Cl tạo 2 liên kết, không còn e tự do $\\Rightarrow 2$ đám mây e đẩy nhau xa nhất $\\Rightarrow$ góc $180^\\circ$ (lai hóa sp)."},
    {"id": "mc-c2-053", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Số lk pi của CO2",
     "question": "Trong phân tử $CO_2$ ($O=C=O$), tổng số liên kết $\\sigma$ và $\\pi$ là:",
     "choices": ["2 $\\sigma$ và 2 $\\pi$", "4 $\\sigma$", "2 $\\sigma$ và 1 $\\pi$", "1 $\\sigma$ và 3 $\\pi$"],
     "answer": 0, "explanation": "Mỗi liên kết đôi chứa 1 $\\sigma$ và 1 $\\pi$. Có 2 lk đôi $\\Rightarrow 2 \\sigma + 2 \\pi$."},
    {"id": "mc-c2-054", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Dấu hiệu VDW",
     "question": "Lực van der Waals có vai trò cực kì quan trọng trong hiện tượng tự nhiên nào dưới đây?",
     "choices": ["Khả năng bám dính siêu việt trên trần nhà của thạch sùng (tắc kè)", "Sự tạo thành mây mưa", "Từ trường Trái Đất", "Sự nổ của thuốc súng"],
     "answer": 0, "explanation": "Bàn chân tắc kè (gecko) có hàng triệu sợi lông siêu nhỏ, tương tác với bề mặt tường bằng hàng tỷ lực van der Waals cộng dồn lại, giúp nó bám dính chắc chắn."},
    
    {"id": "mc-c2-055", "chapter": "c2", "lesson": "b8", "level": "th", "dang": "Công thức electron",
     "question": "Nguyên tử S có 6 electron hóa trị. Trong hợp chất $H_2S$, để đạt cấu hình bát tử, nguyên tử S có tổng cộng bao nhiêu CẶP electron không tham gia liên kết (cặp e tự do)?",
     "choices": ["2 cặp", "1 cặp", "3 cặp", "0 cặp"],
     "answer": 0, "explanation": "S có 6e. Dùng 2e để tạo 2 liên kết đơn với 2 H. Còn lại 4e $\\Rightarrow 2$ cặp electron chưa liên kết."},
    {"id": "mc-c2-056", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Phát biểu muối",
     "question": "Cho các chất: $NH_4Cl, K_2O, BaCl_2, HCl$. Trong số các chất trên, có bao nhiêu chất chứa liên kết ion?",
     "choices": ["3 chất ($NH_4Cl, K_2O, BaCl_2$)", "2 chất", "1 chất", "Tất cả"],
     "answer": 0, "explanation": "$K_2O$ (ion), $BaCl_2$ (ion). $NH_4Cl$ gồm cation $NH_4^+$ và anion $Cl^-$ (liên kết giữa 2 cụm này là liên kết ion, dù trong $NH_4^+$ là cộng hóa trị). HCl là hợp chất cộng hóa trị. Có 3 chất."},
    {"id": "mc-c2-057", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Hiệu độ âm điện 2",
     "question": "Tính chất của liên kết trong phân tử nhôm clorua ($AlCl_3$) là gì? (Biết $\\chi_{Al} = 1.61, \\chi_{Cl} = 3.16$)",
     "choices": ["Cộng hóa trị phân cực", "Ion", "Kim loại", "Cộng hóa trị không phân cực"],
     "answer": 0, "explanation": "$\\Delta\\chi = 3.16 - 1.61 = 1.55 < 1.7$. Hợp chất này thể hiện tính cộng hóa trị phân cực (thăng hoa ở nhiệt độ thấp), không phải là muối ion điển hình."},
    
    {"id": "mc-c2-058", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Sự đẩy VSEPR",
     "question": "Theo thuyết VSEPR, trật tự lực đẩy giữa các cặp electron (Chưa liên kết - Không chia - E, và Liên kết - X) sắp xếp giảm dần là:",
     "choices": ["Lực đẩy E-E > Lực đẩy E-X > Lực đẩy X-X", "Lực đẩy X-X > Lực đẩy E-X > Lực đẩy E-E", "Tất cả bằng nhau", "Lực đẩy E-X > Lực đẩy E-E > Lực đẩy X-X"],
     "answer": 0, "explanation": "Cặp e không phân chia (Lone pair - E) không bị kéo bởi hạt nhân thứ 2 nên nó phình to ra, đẩy mạnh hơn. Do đó Cặp tự do - Cặp tự do đẩy mạnh nhất, yếu nhất là Lk - Lk."},
    {"id": "mc-c2-059", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Độ bền liên kết",
     "question": "Phân tử Nitrogen ($N_2$) rất trơ về mặt hóa học ở nhiệt độ thường (không phản ứng với các chất khác). Nguyên nhân chính là do:",
     "choices": ["Giữa 2 nguyên tử N có một liên kết ba ($N \\equiv N$) có năng lượng liên kết cực kì lớn (khoảng 946 kJ/mol)", "Vì N2 là chất khí", "Vì N2 chiếm 78% thể tích không khí", "Vì Nitơ là phi kim yếu"],
     "answer": 0, "explanation": "Liên kết ba gồm $1\\sigma$ và $2\\pi$. Tổng năng lượng phá vỡ nó rất cao, cần nhiệt độ $3000^\\circ\\text{C}$ (tia chớp) mới bẻ gãy được phân tử N2, nên nó rất trơ."},
    {"id": "mc-c2-060", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Tính chất dung môi",
     "question": "Câu châm ngôn 'Giống nhau thì hòa tan nhau' (Like dissolves like) có nghĩa là:",
     "choices": ["Các chất có liên kết phân cực (hoặc ion) dễ hòa tan trong dung môi phân cực (như nước), còn các chất không phân cực hòa tan tốt trong dung môi không phân cực (như hexane)", "Chất rắn tan trong chất rắn", "Axit chỉ tan trong axit", "Chất hữu cơ chỉ tan trong chất vô cơ"],
     "answer": 0, "explanation": "Nước (phân cực mạnh) dễ hòa tan muối ăn (ion), đường (có liên kết H phân cực). Dầu mỡ (không phân cực) thì không tan trong nước, nhưng tan trong xăng, benzen (không phân cực)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C2 Part 1 written successfully.")
