import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 4: CHUYỂN ĐỘNG TRÒN VÀ BIẾN DẠNG CƠ ---
    # Nhóm 1: Khái niệm Chuyển động tròn đều
    {"id": "mc-c4-001", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Chuyển động tròn đều",
     "question": "Chuyển động tròn đều là chuyển động có quỹ đạo là một đường tròn và có đặc điểm nào sau đây?",
     "choices": ["Tốc độ của vật không đổi theo thời gian", "Vận tốc của vật không đổi theo thời gian", "Gia tốc của vật bằng 0", "Lực tác dụng lên vật bằng 0"],
     "answer": 0, "explanation": "Chuyển động tròn đều có TỐC ĐỘ (độ lớn của vận tốc) không đổi, nhưng VẬN TỐC (là vectơ) luôn thay đổi hướng. Gia tốc khác 0 (gia tốc hướng tâm)."},
    {"id": "mc-c4-002", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Vectơ vận tốc",
     "question": "Vectơ vận tốc trong chuyển động tròn đều có phương như thế nào?",
     "choices": ["Tiếp tuyến với đường tròn quỹ đạo tại điểm đó", "Hướng vào tâm quỹ đạo", "Hướng ra xa tâm quỹ đạo", "Luôn nằm ngang"],
     "answer": 0, "explanation": "Vận tốc tức thời của vật chuyển động trên quỹ đạo cong luôn có phương tiếp tuyến với quỹ đạo tại điểm đang xét."},
    {"id": "mc-c4-003", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Tốc độ góc",
     "question": "Tốc độ góc $\\omega$ trong chuyển động tròn đều được tính bằng công thức nào? (Với $\\Delta\\alpha$ là góc quét được trong thời gian $\\Delta t$)",
     "choices": ["$\\omega = \\Delta\\alpha / \\Delta t$", "$\\omega = \\Delta\\alpha \\cdot \\Delta t$", "$\\omega = \\Delta t / \\Delta\\alpha$", "$\\omega = v / \\Delta t$"],
     "answer": 0, "explanation": "Tốc độ góc đặc trưng cho sự quay nhanh hay chậm, tính bằng góc quét được chia cho thời gian quét góc đó."},
    {"id": "mc-c4-004", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Đơn vị tốc độ góc",
     "question": "Đơn vị đo chuẩn của tốc độ góc là:",
     "choices": ["rad/s", "độ/s", "m/s", "vòng/phút"],
     "answer": 0, "explanation": "Góc đo bằng radian (rad), thời gian đo bằng giây (s). Nên đơn vị chuẩn hệ SI là rad/s."},

    # Nhóm 2: Chu kì và Tần số
    {"id": "mc-c4-005", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Chu kì",
     "question": "Chu kì (T) của chuyển động tròn đều là:",
     "choices": ["Thời gian để vật đi được đúng một vòng tròn", "Số vòng vật đi được trong 1 giây", "Đoạn đường vật đi được trong 1 giây", "Thời gian để vật quay được 1 radian"],
     "answer": 0, "explanation": "Chu kì T là khoảng thời gian ngắn nhất để trạng thái chuyển động lặp lại như cũ (đi hết 1 vòng). Đơn vị là giây (s)."},
    {"id": "mc-c4-006", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Tần số",
     "question": "Tần số (f) của chuyển động tròn đều là:",
     "choices": ["Số vòng vật đi được trong 1 giây", "Thời gian để vật đi được một vòng", "Vận tốc góc của vật", "Số độ quay được trong 1 giây"],
     "answer": 0, "explanation": "Tần số là số chu kì (vòng) thực hiện được trong 1 đơn vị thời gian (1 giây). Đơn vị Hertz (Hz) = vòng/s."},
    {"id": "mc-c4-007", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Công thức Chu kì, Tần số",
     "question": "Mối liên hệ giữa tốc độ góc $\\omega$, chu kì T và tần số f là:",
     "choices": ["$\\omega = 2\\pi / T = 2\\pi f$", "$\\omega = T / 2\\pi = f / 2\\pi$", "$\\omega = 2\\pi T = 2\\pi / f$", "$\\omega = 2\\pi + T = 2\\pi + f$"],
     "answer": 0, "explanation": "Góc quét một vòng là $2\\pi$ (rad), thời gian là T. Suy ra $\\omega = 2\\pi / T$. Mà $f = 1/T \Rightarrow \\omega = 2\\pi f$."},
    {"id": "mc-c4-008", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Tính toán chu kì kim đồng hồ",
     "question": "Tốc độ góc của kim giây đồng hồ chạy đúng là:",
     "choices": ["$\\pi/30$ rad/s", "$2\\pi/60$ vòng/s", "$\\pi/60$ rad/s", "$2\\pi/3600$ rad/s"],
     "answer": 0, "explanation": "Kim giây quay 1 vòng hết 60s $\\Rightarrow T = 60\\text{ s}$. $\\omega = 2\\pi / T = 2\\pi / 60 = \\pi / 30\\text{ rad/s}$."},

    # Nhóm 3: Liên hệ giữa tốc độ dài và tốc độ góc
    {"id": "mc-c4-009", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Liên hệ v và w",
     "question": "Biểu thức liên hệ giữa tốc độ (dài) $v$, tốc độ góc $\\omega$ và bán kính quỹ đạo $r$ trong chuyển động tròn đều là:",
     "choices": ["$v = r\\omega$", "$v = \\omega / r$", "$v = r / \\omega$", "$v = r\\omega^2$"],
     "answer": 0, "explanation": "Độ dài cung $\\Delta s = r\\cdot\\Delta\\alpha$. Chia 2 vế cho $\\Delta t$ ta được $v = r\\omega$."},
    {"id": "mc-c4-010", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Tính toán v và w",
     "question": "Một chất điểm chuyển động tròn đều trên quỹ đạo bán kính $0,5\\text{ m}$ với tốc độ góc $4\\text{ rad/s}$. Tốc độ của chất điểm là:",
     "choices": ["2 m/s", "8 m/s", "0,125 m/s", "12,5 m/s"],
     "answer": 0, "explanation": "$v = r\\omega = 0,5 \\times 4 = 2\\text{ m/s}$."},
    {"id": "mc-c4-011", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Tính toán chu kì từ v",
     "question": "Một ô tô chạy với tốc độ không đổi 10 m/s trên một vòng xuyến tròn bán kính 50 m. Thời gian để ô tô chạy hết 1 vòng xuyến là:",
     "choices": ["$10\\pi\\text{ s}$", "$5\\pi\\text{ s}$", "31,4 s", "6,28 s"],
     "answer": 0, "explanation": "Chu vi vòng xuyến $S = 2\\pi r = 100\\pi\\text{ m}$. Thời gian đi 1 vòng (Chu kì) $T = S/v = 100\\pi / 10 = 10\\pi\\text{ s} \approx 31,4\\text{ s}$."},
    {"id": "mc-c4-012", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Liên hệ hệ truyền động",
     "question": "Hai bánh xe răng cưa khớp vào nhau (truyền động bánh răng). Bánh 1 có bán kính $R_1$, bánh 2 có bán kính $R_2 = 2R_1$. Nhận xét nào ĐÚNG về tốc độ góc của hai bánh?",
     "choices": ["$\\omega_1 = 2\\omega_2$", "$\\omega_1 = \\omega_2$", "$\\omega_1 = 0,5\\omega_2$", "$\\omega_1 = 4\\omega_2$"],
     "answer": 0, "explanation": "Khớp răng (hay dây curoa) làm cho tốc độ dài ở vành bánh xe bằng nhau: $v_1 = v_2 \Rightarrow R_1\\omega_1 = R_2\\omega_2 \Rightarrow R_1\\omega_1 = 2R_1\\omega_2 \Rightarrow \\omega_1 = 2\\omega_2$. Bánh nhỏ quay nhanh hơn bánh lớn."},

    # Nhóm 4, 5: Gia tốc hướng tâm
    {"id": "mc-c4-013", "chapter": "c4", "lesson": "b34", "level": "nb", "dang": "Gia tốc hướng tâm",
     "question": "Trong chuyển động tròn đều, vectơ gia tốc có đặc điểm gì?",
     "choices": ["Luôn hướng vào tâm quỹ đạo (gia tốc hướng tâm)", "Luôn hướng ra xa tâm quỹ đạo", "Luôn tiếp tuyến với quỹ đạo", "Bằng 0 vì tốc độ không đổi"],
     "answer": 0, "explanation": "Vì vectơ vận tốc luôn thay đổi hướng nên sinh ra gia tốc. Gia tốc này có phương vuông góc với vận tốc và hướng vào tâm, gọi là gia tốc hướng tâm."},
    {"id": "mc-c4-014", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Công thức gia tốc hướng tâm",
     "question": "Công thức tính độ lớn gia tốc hướng tâm là:",
     "choices": ["$a_{ht} = v^2/r = \\omega^2 r$", "$a_{ht} = v/r^2 = \\omega r$", "$a_{ht} = v^2 r = \\omega^2 / r$", "$a_{ht} = v r = \\omega r^2$"],
     "answer": 0, "explanation": "Công thức chuẩn: $a_{ht} = \\frac{v^2}{r} = r\\omega^2$."},
    {"id": "mc-c4-015", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Tính toán gia tốc",
     "question": "Một chất điểm quay đều trên đường tròn bán kính 2m. Biết nó thực hiện 5 vòng trong 10 giây. Lấy $\\pi^2 = 10$. Gia tốc hướng tâm của chất điểm là:",
     "choices": ["20 m/s²", "10 m/s²", "5 m/s²", "40 m/s²"],
     "answer": 0, "explanation": "Tần số $f = 5/10 = 0.5\\text{ Hz}$. $\\omega = 2\\pi f = \\pi\\text{ rad/s}$. Gia tốc $a_{ht} = \\omega^2 r = (\\pi)^2 \\cdot 2 = 10 \\cdot 2 = 20\\text{ m/s}^2$."},
    {"id": "mc-c4-016", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Tính chất gia tốc hướng tâm",
     "question": "Nếu bán kính quỹ đạo của một vật chuyển động tròn đều giảm đi một nửa nhưng tốc độ (vận tốc dài) vẫn giữ nguyên, thì gia tốc hướng tâm của vật sẽ:",
     "choices": ["Tăng gấp đôi", "Tăng gấp 4 lần", "Giảm đi một nửa", "Giảm 4 lần"],
     "answer": 0, "explanation": "$a_{ht} = v^2 / r$. Nếu v không đổi, r giảm một nửa ($r' = r/2$) thì $a_{ht}$ tăng gấp đôi."},

    {"id": "mc-c4-017", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Gia tốc hướng tâm Trái Đất",
     "question": "Gia tốc hướng tâm của một điểm trên xích đạo Trái Đất (do Trái Đất tự quay quanh trục) so với một điểm ở vĩ độ $60^\\circ$ thì:",
     "choices": ["Lớn hơn (vì bán kính quay lớn hơn, tốc độ góc như nhau)", "Nhỏ hơn (vì tốc độ góc nhỏ hơn)", "Bằng nhau", "Nhỏ hơn (vì bán kính quay nhỏ hơn)"],
     "answer": 0, "explanation": "Cùng nằm trên Trái Đất nên mọi điểm có chung $\\omega$. Điểm ở xích đạo cách trục quay một đoạn $r = R$ (lớn nhất). Điểm ở vĩ độ 60 độ có $r = R\\cos 60^\\circ = 0.5 R$. Vì $a_{ht} = \\omega^2 r$ nên gia tốc hướng tâm ở xích đạo lớn hơn."},
    {"id": "mc-c4-018", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "So sánh 2 vật",
     "question": "Vật A quay tròn đều với bán kính $R_A = 2R_B$. Chu kì của vật A bằng một nửa chu kì của vật B ($T_A = 0.5 T_B$). So sánh gia tốc hướng tâm của chúng?",
     "choices": ["$a_A = 8 a_B$", "$a_A = 4 a_B$", "$a_A = 2 a_B$", "$a_A = a_B$"],
     "answer": 0, "explanation": "$\\omega = 2\\pi/T$. $T_A = T_B/2 \Rightarrow \\omega_A = 2\\omega_B$. Gia tốc $a_A = R_A \\omega_A^2 = (2R_B)(2\\omega_B)^2 = 2R_B (4\\omega_B^2) = 8 R_B \\omega_B^2 = 8 a_B$."},
    {"id": "mc-c4-019", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Chuyển động vệ tinh",
     "question": "Một vệ tinh địa tĩnh bay tròn đều quanh Trái Đất ở mặt phẳng xích đạo. Chu kì quay của vệ tinh này là:",
     "choices": ["24 giờ", "1 năm", "1 tháng", "12 giờ"],
     "answer": 0, "explanation": "Vệ tinh địa tĩnh là vệ tinh luôn đứng yên so với một điểm trên mặt đất, nên nó phải quay đồng bộ với Trái Đất. Chu kì của Trái Đất tự quay quanh trục là 1 ngày (24 giờ)."},
    {"id": "mc-c4-020", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Khoảng cách kim đồng hồ",
     "question": "Vào lúc 12 giờ đúng, kim phút và kim giờ trùng nhau. Thời điểm tiếp theo (gần nhất) mà hai kim này lại trùng nhau là khoảng:",
     "choices": ["1 giờ 5 phút", "1 giờ", "1 giờ 15 phút", "1 giờ 10 phút"],
     "answer": 0, "explanation": "Tốc độ góc kim phút $\\omega_p = 2\\pi / 1\\text{h}$. Kim giờ $\\omega_h = 2\\pi / 12\\text{h}$. Góc quay: $\\omega_p t - \\omega_h t = 2\\pi \Rightarrow (2\\pi - 2\\pi/12)t = 2\\pi \Rightarrow (11/12)t = 1 \Rightarrow t = 12/11\\text{ h} = 1\\text{h } 5\\text{ phút } 27\\text{ giây}."},

    # Nhóm 6, 7: Lực hướng tâm
    {"id": "mc-c4-021", "chapter": "c4", "lesson": "b35", "level": "nb", "dang": "Lực hướng tâm",
     "question": "Lực hướng tâm là:",
     "choices": ["Tổng hợp các lực tác dụng lên vật chuyển động tròn đều, có hướng vào tâm quỹ đạo", "Một loại lực mới trong tự nhiên, giống như lực hấp dẫn hay lực ma sát", "Lực do vật tác dụng lên trục quay", "Lực li tâm tác dụng lên vật"],
     "answer": 0, "explanation": "Lực hướng tâm KHÔNG phải là một loại lực mới, nó chỉ là tên gọi của HỢP LỰC (hoặc thành phần hợp lực) của các lực hiện có (như trọng lực, ma sát, căng dây...) đóng vai trò gây ra gia tốc hướng tâm."},
    {"id": "mc-c4-022", "chapter": "c4", "lesson": "b35", "level": "nb", "dang": "Công thức Lực hướng tâm",
     "question": "Biểu thức tính độ lớn của lực hướng tâm tác dụng lên vật khối lượng m chuyển động tròn đều là:",
     "choices": ["$F_{ht} = m\\frac{v^2}{r}$", "$F_{ht} = mvr$", "$F_{ht} = m\\omega r$", "$F_{ht} = m\\frac{v}{r}$"],
     "answer": 0, "explanation": "Theo ĐL 2 Newton: $F_{ht} = m a_{ht} = m \\frac{v^2}{r} = m \\omega^2 r$."},
    {"id": "mc-c4-023", "chapter": "c4", "lesson": "b35", "level": "th", "dang": "Vai trò lực hướng tâm",
     "question": "Khi ô tô chạy vào một khúc cua tròn trên mặt đường ngang, lực nào đóng vai trò là lực hướng tâm giữ ô tô không bị văng ra khỏi đường?",
     "choices": ["Lực ma sát nghỉ ngang do mặt đường tác dụng lên lốp xe", "Trọng lực của ô tô", "Lực đẩy của động cơ", "Lực cản không khí"],
     "answer": 0, "explanation": "Để xe quay đầu (chuyển động tròn), phải có lực hướng vào tâm cong. Trên đường ngang, chỉ có lực ma sát nghỉ (hướng vuông góc với vận tốc, vào tâm) mới đóng vai trò này."},
    {"id": "mc-c4-024", "chapter": "c4", "lesson": "b35", "level": "th", "dang": "Vai trò lực hướng tâm",
     "question": "Trong nguyên tử, electron chuyển động tròn quanh hạt nhân nguyên tử. Lực nào đóng vai trò lực hướng tâm?",
     "choices": ["Lực hút tĩnh điện (lực Coulomb) giữa hạt nhân và electron", "Lực hấp dẫn", "Lực đàn hồi", "Lực từ"],
     "answer": 0, "explanation": "Lực tĩnh điện giữa proton (dương) và electron (âm) hướng vào tâm, giữ electron trên quỹ đạo."},

    {"id": "mc-c4-025", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Tính toán lực hướng tâm",
     "question": "Buộc một vật 500g vào đầu một sợi dây dài 1m rồi quay tròn đều trong mặt phẳng nằm ngang với chu kì 2s. Lực căng của sợi dây (bỏ qua trọng lực) là: (Lấy $\\pi^2 = 10$)",
     "choices": ["5 N", "10 N", "2,5 N", "20 N"],
     "answer": 0, "explanation": "$\\omega = 2\\pi / 2 = \\pi\\text{ rad/s}$. Lực căng dây đóng vai trò lực hướng tâm: $T = F_{ht} = m\\omega^2 r = 0.5 \cdot 10 \cdot 1 = 5\\text{ N}."},
    {"id": "mc-c4-026", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Vận tốc an toàn khúc cua",
     "question": "Một xe máy vào khúc cua tròn bán kính 40m trên đường ngang. Hệ số ma sát trượt giữa lốp và đường là $\\mu = 0,4$. Để xe không bị trượt (văng ra ngoài), tốc độ tối đa an toàn của xe là: (g=10)",
     "choices": ["16 m/s", "12,6 m/s", "4 m/s", "40 m/s"],
     "answer": 0, "explanation": "Lực ma sát nghỉ cực đại $\mu mg$ đóng vai trò lực hướng tâm $m v^2 / r$. Để không trượt: $m v^2 / r \le \\mu mg \Rightarrow v \le \\sqrt{\\mu gr} = \\sqrt{0.4 \\cdot 10 \\cdot 40} = \\sqrt{160} \approx 12,6\\text{ m/s}."},
    {"id": "mc-c4-027", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Góc nghiêng đường",
     "question": "Để giảm thiểu nguy cơ lật xe khi vào đường vòng với tốc độ cao, mặt đường tại các khúc cua thường được thiết kế như thế nào?",
     "choices": ["Mặt đường nghiêng vào phía trong tâm cong", "Mặt đường nghiêng ra phía ngoài", "Mặt đường làm thật phẳng và nhẵn", "Rải thật nhiều cát"],
     "answer": 0, "explanation": "Đường nghiêng vào trong để một thành phần của phản lực pháp tuyến $N$ (hướng vào tâm) kết hợp cùng ma sát cung cấp lực hướng tâm, giúp xe qua cua an toàn hơn."},
    {"id": "mc-c4-028", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Cầu vồng",
     "question": "Một ô tô chạy qua một chiếc cầu vồng (cầu vồng lên như một cung tròn). Tại điểm cao nhất của cầu, áp lực của xe lên mặt cầu so với trọng lượng P của xe sẽ:",
     "choices": ["Nhỏ hơn P", "Lớn hơn P", "Bằng P", "Bằng 0"],
     "answer": 0, "explanation": "Hợp lực hướng vào tâm $P - N = m v^2 / R \Rightarrow N = P - m v^2 / R$. Vậy áp lực $N$ lên cầu nhỏ hơn trọng lượng $P$. (Cảm giác nhẹ hẫng)."},

    # Nhóm 8, 9, 10: Chuyển động li tâm, Mô hình hành tinh
    {"id": "mc-c4-029", "chapter": "c4", "lesson": "b35", "level": "nb", "dang": "Lực li tâm",
     "question": "Hiện tượng văng ra khỏi quỹ đạo tròn (chuyển động li tâm) xảy ra khi nào?",
     "choices": ["Khi lực hướng tâm không đủ lớn để giữ vật chuyển động trên quỹ đạo", "Khi lực hướng tâm quá lớn", "Khi vật chuyển động chậm lại", "Khi vật có khối lượng quá nhỏ"],
     "answer": 0, "explanation": "Khi lực ma sát hoặc lực liên kết nhỏ hơn $mv^2/r$, vật không thể bám quỹ đạo tròn mà có xu hướng bay thẳng theo tiếp tuyến (quán tính), dẫn đến văng ra xa tâm."},
    {"id": "mc-c4-030", "chapter": "c4", "lesson": "b35", "level": "th", "dang": "Ứng dụng máy li tâm",
     "question": "Máy vắt quần áo trong máy giặt hoạt động dựa trên nguyên lí nào?",
     "choices": ["Quay lồng giặt với tốc độ góc lớn để lực liên kết không đủ giữ các giọt nước bám vào vải, khiến nước bị văng ra ngoài", "Sấy nóng bằng thanh nhiệt", "Dùng bơm hút không khí để hút nước", "Ép bằng một khối lượng lớn"],
     "answer": 0, "explanation": "Ứng dụng chuyển động li tâm. Khi lồng quay rất nhanh ($v^2/r$ rất lớn), lực bám dính của nước vào quần áo nhỏ hơn lực hướng tâm yêu cầu, nên nước không quay theo mà văng ra lỗ."},
    {"id": "mc-c4-031", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Tính toán vệ tinh (Kepler)",
     "question": "Lực hướng tâm giữ Mặt Trăng quay quanh Trái Đất chính là Lực vạn vật hấp dẫn. Từ đó, vận tốc quay của Mặt Trăng (v) phụ thuộc vào bán kính quỹ đạo (R) theo tỉ lệ:",
     "choices": ["$v \\sim 1/\\sqrt{R}$", "$v \\sim R$", "$v \\sim R^2$", "$v \\sim 1/R$"],
     "answer": 0, "explanation": "Ta có $F_{ht} = F_{hd} \Rightarrow m v^2 / R = G mM / R^2 \Rightarrow v^2 = GM/R \Rightarrow v = \\sqrt{GM/R}$. Vậy $v$ tỉ lệ với $1/\\sqrt{R}$."},
    {"id": "mc-c4-032", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Mặt phẳng nghiêng (Lực hướng tâm)",
     "question": "Một chiếc xe đạp chạy trong một lòng chảo hình nón úp ngược (Tiết mục xe bay). Để xe không rơi xuống đất, lực hướng tâm sinh ra nhờ yếu tố nào?",
     "choices": ["Thành phần phản lực pháp tuyến của vách lòng chảo hướng vào trục quay", "Lực ma sát nghỉ hướng vào tâm", "Trọng lượng của xe đạp", "Lực đạp của người"],
     "answer": 0, "explanation": "Vách thẳng đứng hoặc nghiêng nón sẽ tạo phản lực $N$ vuông góc mặt vách. Phản lực này có một thành phần hướng vào tâm quay (trục nằm ở giữa lòng chảo) đóng vai trò lực hướng tâm lớn nhất. Lực ma sát hướng lên chống lại trọng lực rơi xuống."},

    # Nhóm 11, 12: Biến dạng đàn hồi của vật rắn
    {"id": "mc-c4-033", "chapter": "c4", "lesson": "b36", "level": "nb", "dang": "Khái niệm biến dạng đàn hồi",
     "question": "Thế nào là biến dạng đàn hồi của một vật rắn?",
     "choices": ["Biến dạng mà khi ngừng tác dụng ngoại lực, vật lấy lại được hình dạng và kích thước ban đầu", "Biến dạng mà khi ngừng lực, vật bị móp luôn", "Biến dạng làm thay đổi thể tích vật mà không đổi hình dạng", "Biến dạng do nhiệt độ"],
     "answer": 0, "explanation": "Tính đàn hồi là khả năng phục hồi hoàn toàn trạng thái cũ sau khi ngoại lực gây biến dạng ngừng tác dụng."},
    {"id": "mc-c4-034", "chapter": "c4", "lesson": "b36", "level": "nb", "dang": "Giới hạn đàn hồi",
     "question": "Nếu lực tác dụng lên một lò xo vượt quá 'giới hạn đàn hồi' thì hiện tượng gì sẽ xảy ra?",
     "choices": ["Lò xo không thể phục hồi lại hình dạng ban đầu sau khi bỏ lực", "Lò xo bị nổ tung", "Lò xo biến dạng hoàn toàn đàn hồi mạnh hơn", "Hệ số góc k của lò xo sẽ tăng gấp đôi"],
     "answer": 0, "explanation": "Khi vượt qua giới hạn đàn hồi, vật rắn bị biến dạng dẻo (biến dạng vĩnh viễn, tàn dư)."},
    {"id": "mc-c4-035", "chapter": "c4", "lesson": "b36", "level": "th", "dang": "Định luật Hooke cơ bản",
     "question": "Đối với một lò xo, định luật Hooke phát biểu rằng trong giới hạn đàn hồi, độ lớn lực đàn hồi:",
     "choices": ["Tỉ lệ thuận với độ biến dạng của lò xo", "Tỉ lệ nghịch với độ giãn", "Bằng hằng số không đổi", "Tỉ lệ thuận với bình phương độ biến dạng"],
     "answer": 0, "explanation": "$F = k|\\Delta l|$. Lực đàn hồi tỉ lệ thuận với độ giãn hoặc nén (độ biến dạng)."},
    {"id": "mc-c4-036", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Tính toán lò xo",
     "question": "Một lò xo dài tự nhiên 20cm, có độ cứng k = 50 N/m. Kéo lò xo dài ra đến 25cm. Lực đàn hồi của lò xo là:",
     "choices": ["2,5 N", "12,5 N", "10 N", "25 N"],
     "answer": 0, "explanation": "Độ giãn $\\Delta l = 25 - 20 = 5\\text{ cm} = 0.05\\text{ m}$. Lực $F = k\\Delta l = 50 \\times 0.05 = 2.5\\text{ N}."},

    # Nhóm 13, 14, 15: Ghép lò xo và Ứng suất
    {"id": "mc-c4-037", "chapter": "c4", "lesson": "b36", "level": "th", "dang": "Ghép nối tiếp lò xo",
     "question": "Hai lò xo có độ cứng lần lượt là $k_1$ và $k_2$ được ghép nối tiếp với nhau. Độ cứng tương đương $k$ của hệ là:",
     "choices": ["$1/k = 1/k_1 + 1/k_2$", "$k = k_1 + k_2$", "$k = |k_1 - k_2|$", "$k = (k_1+k_2)/2$"],
     "answer": 0, "explanation": "Khi ghép nối tiếp, lực kéo T như nhau trên cả 2 lò xo, độ giãn tổng $\\Delta l = \\Delta l_1 + \\Delta l_2 \Rightarrow F/k = F/k_1 + F/k_2 \Rightarrow 1/k = 1/k_1 + 1/k_2$ (Hệ mềm hơn lò xo thành phần)."},
    {"id": "mc-c4-038", "chapter": "c4", "lesson": "b36", "level": "th", "dang": "Ghép song song lò xo",
     "question": "Hai lò xo $k_1$ và $k_2$ được ghép song song (hai lò xo cùng chịu tải từ một thanh ngang). Độ cứng tương đương $k$ của hệ là:",
     "choices": ["$k = k_1 + k_2$", "$1/k = 1/k_1 + 1/k_2$", "$k = \\sqrt{k_1 k_2}$", "$k = k_1$"],
     "answer": 0, "explanation": "Ghép song song, độ giãn 2 lò xo như nhau $\\Delta l$, tổng lực kéo $F = F_1 + F_2 = k_1\\Delta l + k_2\\Delta l = (k_1+k_2)\\Delta l \Rightarrow k = k_1 + k_2$ (Hệ cứng hơn)."},
    {"id": "mc-c4-039", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Độ cứng thanh đàn hồi",
     "question": "Độ cứng $k$ của một thanh thép đồng chất có chiều dài tự nhiên $l_0$, tiết diện ngang $S$ và suất Young $E$ được tính bằng:",
     "choices": ["$k = \\frac{E S}{l_0}$", "$k = E \\cdot S \\cdot l_0$", "$k = \\frac{E}{S \\cdot l_0}$", "$k = \\frac{S l_0}{E}$"],
     "answer": 0, "explanation": "Từ định luật Hooke cho thanh rắn: $\\Delta l / l_0 = F / (E\\cdot S) \Rightarrow F = (ES/l_0)\\Delta l$. Suy ra độ cứng tương đương là $k = ES/l_0$."},
    {"id": "mc-c4-040", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Định luật Hooke mở rộng",
     "question": "Một dây thép dài 2m có suất đàn hồi (suất Young) $E = 2 \\cdot 10^{11}\\text{ Pa}$, tiết diện $1\\text{ mm}^2$. Để dây giãn ra 1mm thì cần treo vật nặng khối lượng khoảng bao nhiêu? ($g=10$)",
     "choices": ["10 kg", "100 kg", "20 kg", "5 kg"],
     "answer": 0, "explanation": "$S = 1\\text{ mm}^2 = 10^{-6}\\text{ m}^2$. Độ cứng $k = ES/l_0 = (2\\cdot 10^{11} \\cdot 10^{-6}) / 2 = 10^5\\text{ N/m}$. $\\Delta l = 1\\text{mm} = 10^{-3}\\text{m}$. Lực kéo $F = k\\Delta l = 10^5 \\cdot 10^{-3} = 100\\text{ N}$. Khối lượng vật $m = F/g = 10\\text{ kg}."},

    # Nhóm 16, 17, 18: Thêm về Áp suất và Chất lỏng (nếu theo SGK KNTT)
    {"id": "mc-c4-041", "chapter": "c4", "lesson": "b37", "level": "nb", "dang": "Áp suất",
     "question": "Áp suất là đại lượng được định nghĩa bằng:",
     "choices": ["Độ lớn của áp lực trên một đơn vị diện tích bị ép", "Độ lớn của lực đẩy chia cho thời gian", "Trọng lượng của chất lỏng", "Tích của lực và diện tích"],
     "answer": 0, "explanation": "$p = F/S$, đặc trưng cho mức độ tác dụng lực ép lên 1 đơn vị diện tích mặt tiếp xúc."},
    {"id": "mc-c4-042", "chapter": "c4", "lesson": "b37", "level": "th", "dang": "Đơn vị áp suất",
     "question": "1 Pascal (Pa) tương đương với:",
     "choices": ["$1\\text{ N/m}^2$", "$1\\text{ N.m}$", "$1\\text{ J/s}$", "$1\\text{ kg/m}^3$"],
     "answer": 0, "explanation": "Do $p = F/S$, đơn vị chuẩn của áp lực là N, diện tích là $m^2$. Suy ra $1\\text{ Pa} = 1\\text{ N/m}^2$."},
    {"id": "mc-c4-043", "chapter": "c4", "lesson": "b37", "level": "vd", "dang": "Tính áp suất",
     "question": "Một người nặng 60kg đứng bằng hai bàn chân. Diện tích mỗi bàn chân là $150\\text{ cm}^2$. Áp suất người đó tác dụng lên mặt đất là: ($g=10$)",
     "choices": ["$20000\\text{ Pa}$", "$40000\\text{ Pa}$", "$2\\text{ Pa}$", "$4\\text{ Pa}$"],
     "answer": 0, "explanation": "Áp lực $F = P = 600\\text{ N}$. Tổng diện tích $S = 2 \\times 150 = 300\\text{ cm}^2 = 0,03\\text{ m}^2$. Áp suất $p = F/S = 600 / 0,03 = 20000\\text{ Pa}."},
    {"id": "mc-c4-044", "chapter": "c4", "lesson": "b37", "level": "vd", "dang": "Áp suất thủy tĩnh",
     "question": "Một tàu ngầm lặn dưới biển ở độ sâu 50m. Biết khối lượng riêng của nước biển là $1030\\text{ kg/m}^3, g=10$. Áp suất nước tác dụng lên vỏ tàu ngầm (chưa tính áp suất khí quyển) là:",
     "choices": ["$515000\\text{ Pa}$", "$500000\\text{ Pa}$", "$10300\\text{ Pa}$", "$515\\text{ Pa}$"],
     "answer": 0, "explanation": "Công thức áp suất thủy tĩnh $p = \\rho g h = 1030 \\cdot 10 \\cdot 50 = 515,000\\text{ Pa}$ (tương đương 5,15 atm)."},

    {"id": "mc-c4-045", "chapter": "c4", "lesson": "b37", "level": "nb", "dang": "Bình thông nhau",
     "question": "Trong bình thông nhau chứa cùng một loại chất lỏng đứng yên, mặt thoáng của chất lỏng ở các nhánh:",
     "choices": ["Luôn ở cùng một độ cao", "Nhánh nào to hơn thì mặt thoáng thấp hơn", "Nhánh nào to hơn thì mặt thoáng cao hơn", "Độ cao phụ thuộc lượng nước mỗi nhánh"],
     "answer": 0, "explanation": "Nguyên lí bình thông nhau: Áp suất ở cùng 1 mức ngang phải bằng nhau $\Rightarrow$ độ sâu h phải bằng nhau $\Rightarrow$ mặt thoáng nằm trên cùng 1 mặt phẳng ngang."},
    {"id": "mc-c4-046", "chapter": "c4", "lesson": "b37", "level": "th", "dang": "Máy nén thủy lực",
     "question": "Máy nén thủy lực (kích thủy lực) hoạt động dựa trên nguyên lí nào?",
     "choices": ["Nguyên lí Pascal: Áp suất tác dụng lên chất lỏng bị nhốt kín được truyền đi nguyên vẹn theo mọi hướng", "Lực đẩy Archimedes", "Sự bảo toàn năng lượng", "Định luật Bernoulli"],
     "answer": 0, "explanation": "Nguyên lí Pascal cho phép truyền nguyên vẹn áp suất $p = F_1/S_1 = F_2/S_2$. Từ đó giúp khuếch đại lực bằng cách dùng tiết diện $S_2 \gg S_1$."},
    {"id": "mc-c4-047", "chapter": "c4", "lesson": "b37", "level": "vd", "dang": "Tính toán máy nén",
     "question": "Một máy nâng thủy lực có pittông nhỏ diện tích $10\\text{ cm}^2$, pittông lớn diện tích $500\\text{ cm}^2$. Tác dụng lực 100N lên pittông nhỏ có thể nâng được vật nặng bao nhiêu trên pittông lớn?",
     "choices": ["5000 N", "1000 N", "500 N", "10000 N"],
     "answer": 0, "explanation": "$F_2 = F_1 \\cdot (S_2 / S_1) = 100 \\times (500 / 10) = 100 \\times 50 = 5000\\text{ N}$."},
    {"id": "mc-c4-048", "chapter": "c4", "lesson": "b37", "level": "vd", "dang": "Lực nâng khí cầu",
     "question": "Khí cầu thể tích $V = 100\\text{ m}^3$ chứa khí Heli (khối lượng riêng $0,18\\text{ kg/m}^3$). Không khí bên ngoài có khối lượng riêng $1,29\\text{ kg/m}^3$. Lực nâng tổng cộng tác dụng lên khí cầu là (g=10):",
     "choices": ["1110 N", "1290 N", "180 N", "1470 N"],
     "answer": 0, "explanation": "Lực đẩy Archimedes $F_A = \\rho_{kk} g V = 1.29 \\times 10 \\times 100 = 1290\\text{ N}$. Trọng lượng khí Heli $P_{He} = \\rho_{He} g V = 0.18 \\times 10 \\times 100 = 180\\text{ N}$. Lực nâng tịnh = $F_A - P_{He} = 1290 - 180 = 1110\\text{ N}$."},

    # Nhóm 19, 20: Tĩnh học Vật rắn (Cân bằng, Trọng tâm)
    {"id": "mc-c4-049", "chapter": "c4", "lesson": "b38", "level": "nb", "dang": "Điều kiện cân bằng tổng quát",
     "question": "Một vật rắn chịu tác dụng của các lực đồng phẳng nằm cân bằng khi và chỉ khi:",
     "choices": ["Tổng các lực tác dụng lên vật bằng 0 và tổng momen lực đối với một trục quay bất kì bằng 0", "Chỉ cần tổng các lực bằng 0", "Chỉ cần tổng momen lực bằng 0", "Lực kéo lớn nhất phải bằng lực ma sát"],
     "answer": 0, "explanation": "Điều kiện CÂN BẰNG TỔNG QUÁT: $\\sum\\vec{F} = 0$ (cân bằng tịnh tiến) và $\\sum M = 0$ (cân bằng quay)."},
    {"id": "mc-c4-050", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Cân bằng của thang",
     "question": "Một cái thang tựa vào tường nhẵn thẳng đứng và đặt trên mặt sàn ngang có ma sát. Những lực nào làm thang KHÔNG bị trượt xuống?",
     "choices": ["Lực ma sát nghỉ của sàn hướng vào chân tường", "Phản lực của tường đẩy ra", "Trọng lượng thang đè xuống", "Lực đàn hồi của thang"],
     "answer": 0, "explanation": "Tường nhẵn nên không có ma sát. Đầu trên thang trượt xuống, chân thang có xu hướng trượt ra xa tường. Nên ma sát nghỉ tại sàn (hướng vào tường) đóng vai trò giữ chân thang không trượt."},
    {"id": "mc-c4-051", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Treo khung ảnh",
     "question": "Một bức tranh nặng 20N được treo cân bằng bằng 2 sợi dây đối xứng, mỗi dây hợp với phương thẳng đứng góc 30 độ. Lực căng của mỗi sợi dây là: (Lấy $\\cos 30^\\circ = \\sqrt{3}/2$)",
     "choices": ["$20/\\sqrt{3}\\text{ N}$", "10 N", "20 N", "11,5 N"],
     "answer": 0, "explanation": "Thành phần đứng của mỗi dây là $T_y = T\\cos 30^\\circ$. Có 2 dây nên $2 T\\cos 30^\\circ = P \Rightarrow 2 T \\cdot (\\sqrt{3}/2) = 20 \Rightarrow T\\sqrt{3} = 20 \Rightarrow T = 20/\\sqrt{3} \approx 11,5\\text{ N}$."},
    {"id": "mc-c4-052", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Momen lật",
     "question": "Một khối hộp chữ nhật có khối lượng đồng chất đứng trên sàn nghiêng. Góc nghiêng tăng dần. Hộp sẽ bị lật khi:",
     "choices": ["Đường thẳng đứng qua trọng tâm đi ra ngoài mặt chân đế của hộp", "Góc nghiêng vượt quá 45 độ", "Lực ma sát trượt lớn hơn trọng lượng", "Góc nghiêng bằng 90 độ"],
     "answer": 0, "explanation": "Điều kiện cân bằng bền là giá của trọng lực đè lên mặt chân đế. Khi dốc nghiêng quá mức, đường thẳng qua trọng tâm rơi ra ngoài góc tiếp xúc thấp nhất $\\Rightarrow$ sinh ra momen lật hộp."},

    # Các câu còn lại bù vào cho C4 Part 1
    {"id": "mc-c4-053", "chapter": "c4", "lesson": "b35", "level": "vd", "dang": "Gia tốc hướng tâm",
     "question": "Một vòng đu quay khổng lồ bán kính 20m quay 1 vòng hết 1 phút. Gia tốc hướng tâm mà một người ngồi trong cabin cảm nhận được xấp xỉ bằng:",
     "choices": ["$0,22\\text{ m/s}^2$", "$2,2\\text{ m/s}^2$", "$0,05\\text{ m/s}^2$", "$9,8\\text{ m/s}^2$"],
     "answer": 0, "explanation": "$T = 60\\text{ s}$. $\\omega = 2\\pi / 60 = \\pi / 30\\text{ rad/s} \approx 0,105$. Gia tốc $a_{ht} = r\\omega^2 = 20 \\cdot (0,105)^2 \approx 0,22\\text{ m/s}^2$."},
    {"id": "mc-c4-054", "chapter": "c4", "lesson": "b35", "level": "th", "dang": "Gia tốc tiếp tuyến",
     "question": "Khi ô tô chạy vào một khúc cua nhưng đồng thời ĐẠP GA TĂNG TỐC, gia tốc tổng cộng của xe gồm những thành phần nào?",
     "choices": ["Gồm gia tốc hướng tâm (vuông góc quỹ đạo) và gia tốc tiếp tuyến (dọc theo quỹ đạo)", "Chỉ có gia tốc tiếp tuyến", "Chỉ có gia tốc hướng tâm", "Bằng 0"],
     "answer": 0, "explanation": "Đang cua nên quỹ đạo cong $\\Rightarrow$ có $a_{ht}$ (chuyển hướng). Đạp ga $\\Rightarrow$ tốc độ dài $v$ tăng $\\Rightarrow$ có gia tốc tiếp tuyến $a_t$."},
    {"id": "mc-c4-055", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Cắt lò xo",
     "question": "Cắt một lò xo (k=100 N/m) thành 3 đoạn bằng nhau. Ghép song song 3 đoạn đó lại với nhau. Hệ lò xo mới có độ cứng là:",
     "choices": ["900 N/m", "300 N/m", "100 N/m", "33,3 N/m"],
     "answer": 0, "explanation": "Cắt làm 3, chiều dài mỗi đoạn giảm 3 lần $\\Rightarrow$ độ cứng mỗi đoạn tăng 3 lần ($k' = 300$). Ghép 3 đoạn song song $\\Rightarrow k_{songsong} = 300 + 300 + 300 = 900\\text{ N/m}."},
    {"id": "mc-c4-056", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Chuyển động trên đĩa quay",
     "question": "Đặt một đồng xu trên một bàn quay đĩa than. Từ từ tăng tốc độ quay của bàn. Đồng xu sẽ bị văng ra khi nào?",
     "choices": ["Khi lực hướng tâm cần thiết lớn hơn lực ma sát nghỉ cực đại giữa đồng xu và đĩa", "Khi lực ma sát trượt lớn hơn trọng lượng", "Ngay khi bàn bắt đầu quay", "Khi bàn quay với tốc độ ánh sáng"],
     "answer": 0, "explanation": "Lực giữ xu trên đĩa là ma sát nghỉ: $F_{ms} \le \\mu N = \\mu mg$. Lực yêu cầu: $m\\omega^2 r$. Khi $m\\omega^2 r > \\mu mg$, xu bị văng."},
    {"id": "mc-c4-057", "chapter": "c4", "lesson": "b37", "level": "nb", "dang": "Áp suất khí quyển",
     "question": "Nhà khoa học nào đã thực hiện thí nghiệm đo áp suất khí quyển bằng một ống thủy tinh dài 1m chứa đầy thủy ngân lộn ngược vào chậu thủy ngân?",
     "choices": ["Torricelli", "Pascal", "Newton", "Archimedes"],
     "answer": 0, "explanation": "Torricelli là người phát minh ra phong vũ biểu thủy ngân, đo được áp suất khí quyển 1 atm xấp xỉ 760 mmHg."},
    {"id": "mc-c4-058", "chapter": "c4", "lesson": "b37", "level": "vd", "dang": "Áp suất không khí",
     "question": "Một cốc nước đầy, úp một tờ giấy cứng lên miệng cốc rồi lật ngược. Nước không chảy ra ngoài. Tại sao?",
     "choices": ["Áp suất khí quyển tác dụng lên tờ giấy từ dưới lên lớn hơn áp suất thủy tĩnh của cột nước đè xuống", "Do nước có lực dính ướt lớn dán chặt tờ giấy vào cốc", "Do tạo ra chân không bên trong", "Trọng lượng nước bằng 0 khi úp xuống"],
     "answer": 0, "explanation": "Áp suất khí quyển ($10^5\\text{ Pa}$) tương đương cột nước cao 10m. Cốc cao 10-20cm tạo ra áp suất thủy tĩnh rất nhỏ so với áp suất khí quyển đẩy từ ngoài vào."},
    {"id": "mc-c4-059", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Tính chất momen lực",
     "question": "Lực nào không sinh ra momen làm quay vật quanh một trục cố định?",
     "choices": ["Lực có giá cắt ngang trục quay (hoặc song song với trục quay)", "Lực vuông góc với cánh tay đòn", "Lực rất lớn", "Lực ma sát"],
     "answer": 0, "explanation": "Nếu giá của lực đâm thẳng vào trục quay thì cánh tay đòn d = 0, nên M = F*d = 0. Lực song song với trục quay cũng không làm vật quay quanh trục đó."},
    {"id": "mc-c4-060", "chapter": "c4", "lesson": "b34", "level": "th", "dang": "Tổng hợp động học",
     "question": "Kim phút dài 10cm, kim giờ dài 8cm. Tỉ số TỐC ĐỘ DÀI của đầu kim phút so với đầu kim giờ là:",
     "choices": ["15 lần", "12 lần", "10 lần", "20 lần"],
     "answer": 0, "explanation": "$\\omega_p / \\omega_h = 12$ (kim phút quay 1 vòng/h, kim giờ 1 vòng/12h). Tốc độ $v = r\\omega$. Tỉ số $v_p/v_h = (r_p/r_h) \\cdot (\\omega_p/\\omega_h) = (10/8) \\cdot 12 = 1.25 \\times 12 = 15$ lần."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C4 Part 1 written successfully.")
