import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 4 (TIẾP THEO): TĨNH HỌC VẬT RẮN & CHẤT LƯU ---
    # Nhóm 16: Momen lực
    {"id": "mc-c4-061", "chapter": "c4", "lesson": "b38", "level": "nb", "dang": "Khái niệm momen lực",
     "question": "Momen lực đối với một trục quay là đại lượng đặc trưng cho:",
     "choices": ["Tác dụng làm quay của lực", "Khả năng dịch chuyển vật của lực", "Công mà lực sinh ra", "Độ bền của vật"],
     "answer": 0, "explanation": "Momen lực ($M = F \\cdot d$) là đại lượng vật lí đặc trưng cho tác dụng làm quay vật của lực xung quanh một trục."},
    {"id": "mc-c4-062", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Cánh tay đòn",
     "question": "Cánh tay đòn của lực là khoảng cách:",
     "choices": ["Từ trục quay đến giá của lực", "Từ trục quay đến điểm đặt của lực", "Từ điểm đặt lực đến tâm vật", "Từ giá của lực đến tâm vật"],
     "answer": 0, "explanation": "Theo định nghĩa, cánh tay đòn ($d$) là khoảng cách vuông góc từ trục quay đến đường thẳng chứa vectơ lực (giá của lực)."},
    {"id": "mc-c4-063", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Đơn vị momen lực",
     "question": "Đơn vị của momen lực trong hệ SI là:",
     "choices": ["Niu-tơn mét (N.m)", "Jun (J)", "Niu-tơn trên mét (N/m)", "Oát (W)"],
     "answer": 0, "explanation": "Vì $M = F \\cdot d$ (F đo bằng N, d đo bằng m) nên đơn vị của momen lực là N.m. (Không gọi là Jun dù thứ nguyên giống nhau)."},
    {"id": "mc-c4-064", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Tính momen lực",
     "question": "Một người dùng cờ lê dài 20cm để vặn ốc. Lực tác dụng có độ lớn 50N hướng vuông góc với cờ lê tại điểm cầm. Momen lực tác dụng lên ốc là:",
     "choices": ["10 N.m", "1000 N.m", "2,5 N.m", "100 N.m"],
     "answer": 0, "explanation": "Cánh tay đòn $d = 20\\text{ cm} = 0.2\\text{ m}$. Lực vuông góc nên $d$ chính là chiều dài cờ lê. $M = F \\cdot d = 50 \\cdot 0.2 = 10\\text{ N.m}."},

    # Nhóm 17: Quy tắc momen lực
    {"id": "mc-c4-065", "chapter": "c4", "lesson": "b38", "level": "nb", "dang": "Quy tắc momen",
     "question": "Điều kiện cân bằng của một vật có trục quay cố định (Quy tắc momen lực) là:",
     "choices": ["Tổng momen lực có xu hướng làm vật quay theo chiều kim đồng hồ bằng tổng momen lực có xu hướng làm vật quay ngược chiều kim đồng hồ", "Tổng các lực tác dụng lên vật bằng 0", "Các momen lực phải triệt tiêu lẫn nhau tạo thành các cặp ngẫu lực", "Momen của lực lớn nhất phải bằng 0"],
     "answer": 0, "explanation": "Quy tắc momen: Tổng các momen làm quay thuận phải cân bằng với tổng các momen làm quay nghịch."},
    {"id": "mc-c4-066", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Áp dụng quy tắc momen",
     "question": "Một đòn bẩy dài 1m, tựa trên điểm tựa O nằm cách đầu A 20cm, cách đầu B 80cm. Treo vật 40kg ở đầu A. Để đòn bẩy cân bằng, phải treo vật nặng bao nhiêu ở đầu B? (Bỏ qua khối lượng đòn bẩy)",
     "choices": ["10 kg", "20 kg", "160 kg", "40 kg"],
     "answer": 0, "explanation": "Quy tắc momen quanh O: $P_A \\cdot OA = P_B \\cdot OB \Rightarrow (40\\cdot g) \\cdot 20 = (m_B \\cdot g) \\cdot 80 \Rightarrow 40 \\cdot 20 = m_B \\cdot 80 \Rightarrow 800 = 80 m_B \Rightarrow m_B = 10\\text{ kg}."},
    {"id": "mc-c4-067", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Momen và góc",
     "question": "Cùng kéo một cánh cửa bằng lực 50N tại tay nắm cửa cách bản lề 0.8m. Trạng thái nào tạo ra momen lực lớn nhất?",
     "choices": ["Kéo theo hướng vuông góc với mặt cánh cửa", "Kéo theo hướng tạo góc 45 độ với mặt cánh cửa", "Kéo theo hướng song song với mặt cánh cửa", "Cả 3 trường hợp momen như nhau"],
     "answer": 0, "explanation": "Momen lớn nhất khi cánh tay đòn dài nhất. $d = r\\sin\\alpha$. Lớn nhất khi $\\alpha = 90^\\circ$, tức kéo vuông góc cửa."},
    {"id": "mc-c4-068", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Tính momen chéo",
     "question": "Một thanh thẳng OA dài 50cm có thể quay quanh trục O. Tác dụng lực F = 100N tại điểm A, lực này hợp với thanh OA một góc 30 độ. Momen lực làm quay thanh quanh O là: (Lấy $\\sin 30^\\circ = 0.5$)",
     "choices": ["25 N.m", "50 N.m", "43,3 N.m", "0 N.m"],
     "answer": 0, "explanation": "Cánh tay đòn $d = OA \\sin 30^\\circ = 0.5 \cdot 0.5 = 0.25\\text{m}$. $M = F \cdot d = 100 \cdot 0.25 = 25\\text{ N.m}."},

    # Nhóm 18: Ngẫu lực
    {"id": "mc-c4-069", "chapter": "c4", "lesson": "b38", "level": "nb", "dang": "Ngẫu lực",
     "question": "Ngẫu lực là hệ gồm:",
     "choices": ["Hai lực song song, ngược chiều, có độ lớn bằng nhau và cùng tác dụng vào một vật", "Hai lực cùng phương, cùng chiều, cùng độ lớn", "Hai lực vuông góc với nhau", "Hai lực có giá đồng quy tại một điểm"],
     "answer": 0, "explanation": "Định nghĩa ngẫu lực. Ngẫu lực chỉ có tác dụng làm quay vật mà không làm vật tịnh tiến (do tổng lực = 0)."},
    {"id": "mc-c4-070", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Đặc điểm ngẫu lực",
     "question": "Nhận định nào sau đây về ngẫu lực là SAI?",
     "choices": ["Ngẫu lực có thể hợp lại thành một lực duy nhất (hợp lực khác 0)", "Ngẫu lực không làm vật tịnh tiến", "Momen của ngẫu lực không phụ thuộc vào vị trí trục quay", "Momen ngẫu lực tính bằng $M = F\\cdot d$, với d là khoảng cách giữa 2 giá của lực"],
     "answer": 0, "explanation": "Ngẫu lực không có hợp lực (vì 2 lực song song ngược chiều bằng nhau cộng lại bằng vectơ 0). Do đó không thể thay thế ngẫu lực bằng một lực duy nhất."},
    {"id": "mc-c4-071", "chapter": "c4", "lesson": "b38", "level": "th", "dang": "Momen ngẫu lực",
     "question": "Một người dùng vô lăng ô tô có đường kính 40cm. Hai tay đặt ở mép vô lăng đối diện nhau, tác dụng một ngẫu lực, mỗi tay tác dụng lực 10N. Momen của ngẫu lực là:",
     "choices": ["4 N.m", "8 N.m", "2 N.m", "0 N.m"],
     "answer": 0, "explanation": "$M = F \\cdot d$, với $F$ là độ lớn của MỘT lực, $d$ là khoảng cách 2 lực (đường kính). $M = 10 \\times 0.4 = 4\\text{ N.m}."},
    {"id": "mc-c4-072", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Trục quay",
     "question": "Một vật chịu tác dụng của ngẫu lực sẽ quay quanh trục quay nào nếu vật không có trục quay cố định bị kẹp?",
     "choices": ["Trục đi qua khối tâm của vật", "Trục đi qua điểm đặt của một trong hai lực", "Trục quay ở xa vô cực", "Vật không quay mà chỉ tịnh tiến"],
     "answer": 0, "explanation": "Dưới tác dụng của ngẫu lực, do tổng lực bằng 0, khối tâm không dịch chuyển. Vật tự quay quanh một trục đi qua khối tâm (trọng tâm) của nó."},

    # Nhóm 19, 20: Trọng tâm và Cân bằng
    {"id": "mc-c4-073", "chapter": "c4", "lesson": "b39", "level": "nb", "dang": "Trọng tâm",
     "question": "Trọng tâm của một vật rắn là gì?",
     "choices": ["Điểm đặt của trọng lực tác dụng lên vật", "Tâm hình học của vật", "Điểm chính giữa vật", "Nơi tập trung khối lượng lớn nhất"],
     "answer": 0, "explanation": "Trọng tâm là điểm đặt của hợp lực các lực hấp dẫn tác dụng lên các phần tử của vật (điểm đặt của trọng lực)."},
    {"id": "mc-c4-074", "chapter": "c4", "lesson": "b39", "level": "nb", "dang": "Vị trí Trọng tâm",
     "question": "Đối với các vật đồng chất, có hình dạng đối xứng, trọng tâm nằm ở đâu?",
     "choices": ["Nằm ở tâm đối xứng hình học của vật", "Nằm ở mép vật", "Nằm ngoài vật", "Luôn nằm ở điểm thấp nhất"],
     "answer": 0, "explanation": "Khối tâm/Trọng tâm của vật đồng chất đối xứng luôn trùng với tâm đối xứng của nó (VD: tâm của hình cầu, giao điểm 2 đường chéo của chữ nhật)."},
    {"id": "mc-c4-075", "chapter": "c4", "lesson": "b39", "level": "th", "dang": "Cân bằng phiếm định",
     "question": "Quả bóng đặt trên mặt bàn phẳng nằm ngang nằm trong trạng thái cân bằng nào?",
     "choices": ["Cân bằng phiếm định", "Cân bằng bền", "Cân bằng không bền", "Không cân bằng"],
     "answer": 0, "explanation": "Nếu dịch chuyển quả bóng một chút, nó vẫn tiếp tục cân bằng ở vị trí mới mà không tự trở về vị trí cũ (không bền) cũng không bị lật (bền) - gọi là cân bằng phiếm định."},
    {"id": "mc-c4-076", "chapter": "c4", "lesson": "b39", "level": "th", "dang": "Cân bằng bền",
     "question": "Để tăng mức vững vàng (cân bằng bền) của một vật trên mặt chân đế, người ta cần phải:",
     "choices": ["Hạ thấp trọng tâm và mở rộng mặt chân đế", "Nâng cao trọng tâm và thu hẹp mặt chân đế", "Tăng khối lượng ở phần ngọn", "Sơn màu tối cho vật"],
     "answer": 0, "explanation": "Mức vững vàng phụ thuộc vào chiều cao trọng tâm (càng thấp càng bền) và diện tích mặt chân đế (càng rộng càng khó lật). Ví dụ: Xe đua F1."},

    {"id": "mc-c4-077", "chapter": "c4", "lesson": "b39", "level": "vd", "dang": "Tính vị trí trọng tâm",
     "question": "Một hệ gồm hai khối điểm $m_1 = 2\\text{kg}$ và $m_2 = 6\\text{kg}$ nối với nhau bằng một thanh thẳng siêu nhẹ dài 80cm. Vị trí trọng tâm của hệ cách $m_1$ một đoạn là:",
     "choices": ["60 cm", "20 cm", "40 cm", "80 cm"],
     "answer": 0, "explanation": "Sử dụng đòn bẩy $m_1 d_1 = m_2 d_2$ và $d_1+d_2 = 80$. $2 d_1 = 6 (80 - d_1) \Rightarrow 2 d_1 = 480 - 6 d_1 \Rightarrow 8 d_1 = 480 \Rightarrow d_1 = 60\\text{ cm}$. Trọng tâm sẽ gần vật nặng hơn ($m_2$)."},
    {"id": "mc-c4-078", "chapter": "c4", "lesson": "b39", "level": "vd", "dang": "Lực đỡ dầm",
     "question": "Một cái xà ngang đồng chất dài 10m, nặng 200kg. Xà được kê lên hai trụ đỡ ở hai đầu A và B. Một người nặng 50kg đứng ở vị trí cách đầu A 2m. Phản lực của trụ đỡ tại B lên xà là: (g=10)",
     "choices": ["1100 N", "1400 N", "2500 N", "1000 N"],
     "answer": 0, "explanation": "Trọng lượng xà $P_x = 2000\\text{N}$ (đặt tại giữa xà, cách A 5m). Trọng lượng người $P_n = 500\\text{N}$ (cách A 2m). Xét momen tại A: $N_B \cdot 10 = P_n \cdot 2 + P_x \cdot 5 = 500 \cdot 2 + 2000 \cdot 5 = 1000 + 10000 = 11000 \Rightarrow N_B = 1100\\text{ N}."},
    {"id": "mc-c4-079", "chapter": "c4", "lesson": "b39", "level": "vd", "dang": "Lực đỡ dầm",
     "question": "Từ câu trên, phản lực của trụ đỡ tại A là bao nhiêu?",
     "choices": ["1400 N", "1100 N", "2000 N", "500 N"],
     "answer": 0, "explanation": "Tổng lực đẩy lên = Tổng trọng lượng kéo xuống: $N_A + N_B = P_x + P_n \Rightarrow N_A + 1100 = 2000 + 500 = 2500 \Rightarrow N_A = 1400\\text{ N}."},
    {"id": "mc-c4-080", "chapter": "c4", "lesson": "b39", "level": "vd", "dang": "Sự lật",
     "question": "Một tủ lạnh hình hộp chữ nhật có khối lượng đồng đều, cao 2m, đáy vuông rộng 0.8m. Bị đẩy theo phương ngang ở đỉnh tủ. Hệ số ma sát đủ lớn để không trượt. Để tủ bắt đầu bị lật cong chân, lực đẩy F tối thiểu là: (g=10, khối lượng tủ 50kg)",
     "choices": ["100 N", "500 N", "200 N", "250 N"],
     "answer": 0, "explanation": "Tủ bị lật quanh mép đáy. Trọng lực tạo momen giữ $M_P = P \\cdot d_P = 500 \\times (0.8 / 2) = 200\\text{ N.m}$. Lực đẩy tạo momen lật $M_F = F \\cdot d_F = F \\times 2$. Để lật: $F \times 2 > 200 \Rightarrow F > 100\\text{ N}."},

    # Nhóm 21, 22: Cơ học lưu chất (Áp suất tĩnh, Lực Acsimet)
    {"id": "mc-c4-081", "chapter": "c4", "lesson": "b40", "level": "nb", "dang": "Định luật Acsimet",
     "question": "Lực đẩy Archimedes tác dụng lên một vật nhúng trong chất lỏng có độ lớn bằng:",
     "choices": ["Trọng lượng của phần chất lỏng bị vật chiếm chỗ", "Trọng lượng của toàn bộ vật", "Trọng lượng của toàn bộ chất lỏng trong bình", "Thể tích của phần vật chìm nhân với khối lượng vật"],
     "answer": 0, "explanation": "Đây là định luật Archimedes: Một vật nhúng trong chất lỏng bị chất lỏng đẩy thẳng đứng từ dưới lên với lực có độ lớn bằng trọng lượng phần chất lỏng mà vật chiếm chỗ."},
    {"id": "mc-c4-082", "chapter": "c4", "lesson": "b40", "level": "nb", "dang": "Sự nổi",
     "question": "Một vật sẽ nổi lên mặt thoáng của chất lỏng khi nào?",
     "choices": ["Khi khối lượng riêng của vật nhỏ hơn khối lượng riêng của chất lỏng", "Khi trọng lượng của vật lớn hơn lực đẩy Acsimet", "Khi thể tích vật lớn", "Khi chất lỏng không có ma sát"],
     "answer": 0, "explanation": "Điều kiện nổi là $d_v < d_l$ (hoặc $\\rho_{vật} < \\rho_{lỏng}$). Lúc đó lực đẩy tối đa lớn hơn trọng lượng vật."},
    {"id": "mc-c4-083", "chapter": "c4", "lesson": "b40", "level": "th", "dang": "Công thức Acsimet",
     "question": "Công thức tính lực đẩy Archimedes là:",
     "choices": ["$F_A = \\rho g V$", "$F_A = m g h$", "$F_A = p S$", "$F_A = \\frac{1}{2}\\rho v^2$"],
     "answer": 0, "explanation": "$F_A = d_l V = \\rho_l g V$. Với $\\rho_l$ là KLR chất lỏng, V là thể tích phần chìm."},
    {"id": "mc-c4-084", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Tính lực Acsimet",
     "question": "Một khối sắt có thể tích $0,002\\text{ m}^3$ được nhúng chìm hoàn toàn trong nước (KLR nước là $1000\\text{ kg/m}^3, g=10$). Lực đẩy Acsimet tác dụng lên khối sắt là:",
     "choices": ["20 N", "20000 N", "2 N", "200 N"],
     "answer": 0, "explanation": "$F_A = \\rho_l g V_{\\text{chìm}} = 1000 \\times 10 \\times 0.002 = 20\\text{ N}."},

    {"id": "mc-c4-085", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Tính trọng lượng biểu kiến",
     "question": "Một vật nặng 50N trong không khí, nhưng khi cân chìm hoàn toàn trong nước thì chỉ còn 40N. Thể tích của vật này là bao nhiêu? ($g=10, \\rho_{\\text{nước}}=1000$)",
     "choices": ["$0,001\\text{ m}^3$", "$0,004\\text{ m}^3$", "$0,005\\text{ m}^3$", "$10\\text{ m}^3$"],
     "answer": 0, "explanation": "Độ giảm trọng lượng khi ở trong nước chính là Lực đẩy Acsimet: $F_A = 50 - 40 = 10\\text{ N}$. Lại có $F_A = \\rho g V \Rightarrow 10 = 1000 \\times 10 \times V \Rightarrow 10000 V = 10 \Rightarrow V = 0,001\\text{ m}^3$."},
    {"id": "mc-c4-086", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Sự nổi tỉ lệ",
     "question": "Một khối gỗ hình lập phương nổi trên mặt nước. Khối lượng riêng của gỗ là $600\\text{ kg/m}^3$, của nước là $1000\\text{ kg/m}^3$. Tỉ lệ phần thể tích gỗ CHÌM trong nước so với tổng thể tích là:",
     "choices": ["60%", "40%", "100%", "50%"],
     "answer": 0, "explanation": "Khi nổi cân bằng: $P = F_A \Rightarrow \\rho_{go} g V_{tong} = \\rho_{nuoc} g V_{chim} \Rightarrow V_{chim}/V_{tong} = \\rho_{go} / \\rho_{nuoc} = 600 / 1000 = 60\\%$."},
    {"id": "mc-c4-087", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Tàu thủy",
     "question": "Một con tàu có khối lượng m = 5000 tấn nổi trên biển. Biết KLR nước biển $\\approx 1025\\text{ kg/m}^3$. Thể tích nước biển mà phần chìm của tàu chiếm chỗ là khoảng:",
     "choices": ["$4878\\text{ m}^3$", "$5000\\text{ m}^3$", "$5125\\text{ m}^3$", "$1000\\text{ m}^3$"],
     "answer": 0, "explanation": "Tàu nổi nên $P = F_A \Rightarrow m \cdot g = \\rho \cdot V_c \cdot g \Rightarrow V_c = m / \\rho = (5,000,000\\text{ kg}) / 1025 \approx 4878\\text{ m}^3$."},
    {"id": "mc-c4-088", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Bình thông nhau (2 chất lỏng)",
     "question": "Ống chữ U chứa thủy ngân (KLR 13600 kg/m³). Đổ thêm vào nhánh trái một cột nước (KLR 1000 kg/m³) cao 13.6 cm. Mặt thủy ngân ở nhánh phải sẽ dâng cao hơn mặt thủy ngân ở nhánh trái một đoạn h. Giá trị h là:",
     "choices": ["1 cm", "13,6 cm", "0,5 cm", "136 cm"],
     "answer": 0, "explanation": "Áp suất tại đáy cột nước (trên mặt tiếp xúc thủy ngân) phải bằng áp suất trong cột thủy ngân ở cùng độ cao ngang đó bên nhánh phải. $\\rho_{nước} g h_{nước} = \\rho_{Hg} g h \Rightarrow 1000 \\times 13.6 = 13600 \times h \Rightarrow 13600 = 13600 h \Rightarrow h = 1\\text{ cm}."},

    # Nhóm 23, 24: Động lực học chất lưu (Bernoulli)
    {"id": "mc-c4-089", "chapter": "c4", "lesson": "b41", "level": "nb", "dang": "Định luật Bernoulli",
     "question": "Theo phương trình Bernoulli cho chất lỏng lí tưởng chảy trong ống nằm ngang, mối quan hệ giữa áp suất tĩnh p và vận tốc chảy v là:",
     "choices": ["Nơi nào vận tốc chảy càng lớn thì áp suất tĩnh càng nhỏ", "Nơi nào vận tốc chảy càng lớn thì áp suất tĩnh càng lớn", "Áp suất tĩnh không đổi dọc theo ống", "Vận tốc không đổi dọc theo ống"],
     "answer": 0, "explanation": "Phương trình: $p + 0.5\\rho v^2 = \\text{const}$. Tổng áp suất tĩnh và áp suất động là hằng số. Vậy $v$ tăng thì $p$ tĩnh phải giảm."},
    {"id": "mc-c4-090", "chapter": "c4", "lesson": "b41", "level": "nb", "dang": "Ứng dụng Bernoulli",
     "question": "Hiện tượng nào sau đây được giải thích bằng định luật Bernoulli?",
     "choices": ["Mái tôn nhà có thể bị tốc lên trên khi có gió bão lớn thổi mạnh ngang qua", "Đinh dễ dàng đóng vào gỗ vì mũi đinh nhọn", "Quả bóng nổi trên mặt nước", "Lò xo bị giãn khi treo vật nặng"],
     "answer": 0, "explanation": "Gió bão thổi trên mái tôn có tốc độ $v$ lớn $\\Rightarrow$ áp suất tĩnh $p$ giảm. Áp suất trong nhà bình thường ($v=0$) lớn hơn $\\Rightarrow$ đẩy mái tôn lật lên."},
    {"id": "mc-c4-091", "chapter": "c4", "lesson": "b41", "level": "th", "dang": "Phương trình liên tục",
     "question": "Trong một ống nước không rò rỉ có thiết diện biến thiên, nước chảy từ phần có thiết diện S1 sang phần thiết diện nhỏ hơn S2. Vận tốc dòng chảy thay đổi như thế nào?",
     "choices": ["Vận tốc tăng lên ($v_2 > v_1$)", "Vận tốc giảm đi ($v_2 < v_1$)", "Vận tốc không đổi", "Dòng nước dừng lại"],
     "answer": 0, "explanation": "Phương trình liên tục: $S_1 v_1 = S_2 v_2$. Khi ống hẹp lại ($S_2 < S_1$), dòng nước phải chảy nhanh hơn ($v_2 > v_1$) để bù lại lưu lượng."},
    {"id": "mc-c4-092", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Tính vận tốc chảy",
     "question": "Ống tiêm có tiết diện thân ống lớn gấp 20 lần tiết diện kim tiêm. Nếu đẩy pit-tông với vận tốc 1 cm/s thì nước phụt ra khỏi kim với vận tốc là:",
     "choices": ["20 cm/s", "0,05 cm/s", "10 cm/s", "400 cm/s"],
     "answer": 0, "explanation": "$S_1 v_1 = S_2 v_2 \Rightarrow v_2 = v_1 \\cdot (S_1/S_2) = 1 \\cdot 20 = 20\\text{ cm/s}."},

    {"id": "mc-c4-093", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Tính áp suất Bernoulli",
     "question": "Nước chảy trong ống nằm ngang. Tại điểm A vận tốc 2 m/s, áp suất 1,5 atm. Tại điểm B ống hẹp hơn nên vận tốc tăng lên 4 m/s. Áp suất tại B là bao nhiêu? (Lấy $1\\text{ atm} = 100,000\\text{ Pa}, \\rho = 1000\\text{ kg/m}^3$)",
     "choices": ["1,44 atm", "1,56 atm", "1,3 atm", "1,0 atm"],
     "answer": 0, "explanation": "$p_A + 0.5\\rho v_A^2 = p_B + 0.5\\rho v_B^2 \Rightarrow 150000 + 0.5(1000)(4) = p_B + 0.5(1000)(16) \Rightarrow 152000 = p_B + 8000 \Rightarrow p_B = 144000\\text{ Pa} = 1,44\\text{ atm}."},
    {"id": "mc-c4-094", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Lực nâng cánh máy bay",
     "question": "Cánh máy bay có hình dáng khí động học (mặt trên cong hơn mặt dưới). Khi bay ngang, không khí chảy qua mặt trên so với mặt dưới có đặc điểm:",
     "choices": ["Vận tốc chảy lớn hơn, áp suất tĩnh nhỏ hơn mặt dưới", "Vận tốc chảy nhỏ hơn, áp suất tĩnh lớn hơn", "Vận tốc bằng nhau nhưng áp suất khác nhau", "Vận tốc lớn hơn và áp suất lớn hơn"],
     "answer": 0, "explanation": "Đường đi không khí trên mặt cong (mặt trên) dài hơn $\\Rightarrow$ không khí phải chảy nhanh hơn để bắt kịp phía sau $\\Rightarrow$ vận tốc lớn $\\Rightarrow$ áp suất giảm theo Bernoulli. Sự chênh lệch áp suất tạo lực nâng thẳng đứng."},
    {"id": "mc-c4-095", "chapter": "c4", "lesson": "b41", "level": "th", "dang": "Hiệu ứng Magnus",
     "question": "Cầu thủ đá một quả bóng phạt góc tạo ra độ xoáy xoáy cực mạnh (đá phạt 'quả chuối'). Quả bóng bay liệng vòng cung trong không khí. Hiệu ứng này là do:",
     "choices": ["Sự chênh lệch áp suất không khí ở hai bên quả bóng do không khí bị cuốn theo chiều quay của bóng (Hiệu ứng Magnus - hệ quả của Bernoulli)", "Lực hấp dẫn kéo quả bóng", "Quả bóng bị lực đàn hồi uốn cong", "Không khí có tính dính"],
     "answer": 0, "explanation": "Bóng quay làm một bên luồng không khí đi cùng chiều quay (tăng vận tốc dòng $\\Rightarrow$ giảm áp suất), bên kia ngược chiều quay (giảm vận tốc $\\Rightarrow$ tăng áp). Chênh lệch này sinh ra lực ngang làm lệch quỹ đạo bóng."},
    {"id": "mc-c4-096", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Định luật Torricelli",
     "question": "Một bình chứa nước rất rộng mở hở, cao H. Khoét một lỗ thủng nhỏ ở độ sâu h (so với mặt nước). Vận tốc nước phụt ra khỏi lỗ là:",
     "choices": ["$v = \\sqrt{2gh}$", "$v = \\sqrt{gh}$", "$v = \\sqrt{2gH}$", "$v = \\rho gh$"],
     "answer": 0, "explanation": "Theo định luật Torricelli (một dạng của Bernoulli cho mặt hở): Vận tốc phụt ra ở độ sâu $h$ bằng đúng vận tốc của vật rơi tự do từ độ cao $h$. $v = \\sqrt{2gh}$."},

    # Nhóm 25, 26, 27, 28, 29, 30: Mở rộng cơ học, Vũ trụ, Bài tập chốt
    {"id": "mc-c4-097", "chapter": "c4", "lesson": "b42", "level": "nb", "dang": "Định luật vạn vật hấp dẫn",
     "question": "Lực hấp dẫn giữa hai chất điểm khối lượng $m_1, m_2$ cách nhau khoảng $r$ có độ lớn:",
     "choices": ["Tỉ lệ thuận với tích khối lượng và tỉ lệ nghịch với bình phương khoảng cách", "Tỉ lệ thuận với tổng khối lượng", "Tỉ lệ nghịch với khoảng cách", "Tỉ lệ nghịch với khối lượng"],
     "answer": 0, "explanation": "$F = G \\frac{m_1 m_2}{r^2}$."},
    {"id": "mc-c4-098", "chapter": "c4", "lesson": "b42", "level": "th", "dang": "Gia tốc rơi tự do",
     "question": "Gia tốc rơi tự do (g) ở bề mặt Trái Đất phụ thuộc vào:",
     "choices": ["Khối lượng và bán kính của Trái Đất", "Khối lượng của vật rơi", "Vận tốc của vật", "Nhiệt độ của không khí"],
     "answer": 0, "explanation": "$mg = G \frac{mM}{R^2} \Rightarrow g = G \frac{M}{R^2}$, phụ thuộc vào khối lượng $M$ và bán kính $R$ của hành tinh, không phụ thuộc khối lượng vật $m$."},
    {"id": "mc-c4-099", "chapter": "c4", "lesson": "b42", "level": "vd", "dang": "Tính G ở độ cao",
     "question": "Ở độ cao nào so với mặt đất thì gia tốc rơi tự do g giảm đi một nửa so với mặt đất? (R là bán kính Trái Đất)",
     "choices": ["$h = R(\\sqrt{2} - 1)$", "$h = R$", "$h = R/2$", "$h = 2R$"],
     "answer": 0, "explanation": "$g' = G \frac{M}{(R+h)^2}$. $g = G \frac{M}{R^2}$. Để $g' = 0.5 g \Rightarrow (R+h)^2 = 2 R^2 \Rightarrow R+h = R\\sqrt{2} \Rightarrow h = R(\\sqrt{2}-1) \approx 0.414 R$."},
    {"id": "mc-c4-100", "chapter": "c4", "lesson": "b42", "level": "vd", "dang": "Thay đổi lực hấp dẫn",
     "question": "Nếu khoảng cách giữa hai hành tinh tăng lên gấp 3 lần, thì lực hấp dẫn giữa chúng sẽ:",
     "choices": ["Giảm 9 lần", "Giảm 3 lần", "Tăng 9 lần", "Không đổi"],
     "answer": 0, "explanation": "$F \sim 1/r^2$. Bán kính tăng 3 thì bình phương lên là 9, lực giảm 9 lần."},

    {"id": "mc-c4-101", "chapter": "c4", "lesson": "b42", "level": "th", "dang": "Định luật Kepler 1",
     "question": "Theo Định luật Kepler thứ nhất, các hành tinh chuyển động quanh Mặt Trời theo quỹ đạo có hình dạng gì?",
     "choices": ["Hình elip với Mặt Trời nằm ở một trong hai tiêu điểm", "Hình tròn tâm là Mặt Trời", "Hình parabol", "Hình elip với Mặt Trời ở tâm"],
     "answer": 0, "explanation": "Quỹ đạo là hình elip, Mặt Trời không nằm ở tâm hình elip mà ở tiêu điểm (focus)."},
    {"id": "mc-c4-102", "chapter": "c4", "lesson": "b42", "level": "th", "dang": "Định luật Kepler 2",
     "question": "Theo Định luật Kepler thứ hai (định luật diện tích), hành tinh chuyển động nhanh nhất khi ở vị trí nào trên quỹ đạo?",
     "choices": ["Vị trí cận nhật (gần Mặt Trời nhất)", "Vị trí viễn nhật (xa Mặt Trời nhất)", "Tốc độ của hành tinh là không đổi ở mọi vị trí", "Khi đi qua điểm cắt với trục phụ của elip"],
     "answer": 0, "explanation": "Đoạn thẳng nối Mặt Trời và hành tinh quét những diện tích bằng nhau trong các khoảng thời gian bằng nhau. Gần Mặt Trời bán kính nhỏ $\\Rightarrow$ độ dài cung (vận tốc) phải lớn để bù lại diện tích."},
    {"id": "mc-c4-103", "chapter": "c4", "lesson": "b42", "level": "vd", "dang": "Định luật Kepler 3",
     "question": "Hành tinh Mộc (Jupiter) có bán kính quỹ đạo lớn gấp khoảng 5,2 lần bán kính quỹ đạo Trái Đất. Theo định luật Kepler 3 ($T^2/R^3 = \text{const}$), chu kì quay quanh Mặt Trời của sao Mộc xấp xỉ:",
     "choices": ["11,9 năm Trái Đất", "5,2 năm Trái Đất", "27 năm Trái Đất", "1 năm Trái Đất"],
     "answer": 0, "explanation": "$(T_M/T_D)^2 = (R_M/R_D)^3 \Rightarrow (T_M/1)^2 = (5.2)^3 \approx 140.6 \Rightarrow T_M = \sqrt{140.6} \approx 11,86 \approx 11,9\\text{ năm}."},
    {"id": "mc-c4-104", "chapter": "c4", "lesson": "b42", "level": "vd", "dang": "Tốc độ vũ trụ cấp 1",
     "question": "Một vệ tinh bay ở quỹ đạo sát mặt đất (h $\\approx$ 0). Biết $g = 9,8\\text{ m/s}^2, R = 6400\\text{ km}$. Tốc độ dài của vệ tinh này (Vận tốc vũ trụ cấp I) xấp xỉ:",
     "choices": ["$7,9\\text{ km/s}$", "$11,2\\text{ km/s}$", "$3\\text{ km/s}$", "$9,8\\text{ km/s}$"],
     "answer": 0, "explanation": "Trọng lực là lực hướng tâm: $mg = m v^2 / R \Rightarrow v = \\sqrt{gR} = \\sqrt{9.8 \times 6400 \times 1000} = \\sqrt{62720000} \approx 7920\\text{ m/s} \approx 7,9\\text{ km/s}."},

    {"id": "mc-c4-105", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Lực căng dây (Con lắc đơn)",
     "question": "Một con lắc đơn ($m=1\\text{kg}, l=1\\text{m}$) dao động qua lại. Khi vật qua vị trí thấp nhất (VTCB) với vận tốc $2\\text{ m/s}$, lực căng dây treo vật là: ($g=10$)",
     "choices": ["14 N", "10 N", "4 N", "6 N"],
     "answer": 0, "explanation": "Tại VTCB, quỹ đạo có bán kính cong r = l. Hợp lực hướng tâm $T - P = m v^2 / l \Rightarrow T = mg + m v^2 / l = 1\\cdot 10 + 1\\cdot 2^2 / 1 = 10 + 4 = 14\\text{ N}."},
    {"id": "mc-c4-106", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Cảm giác trọng lượng",
     "question": "Một phi công lái máy bay tiêm kích nhào lộn theo một vòng tròn bán kính 250m trong mặt phẳng đứng với tốc độ không đổi 360 km/h (100 m/s). Tại điểm thấp nhất của quỹ đạo, phi công ép lên ghế một lực bằng mấy lần trọng lượng của anh ta? (Lấy $g=10$)",
     "choices": ["5 lần", "4 lần", "1 lần", "0 (không trọng lượng)"],
     "answer": 0, "explanation": "Tại điểm thấp, lực ép N (ghế đẩy lên) - P (kéo xuống) = Lực hướng tâm. $N - mg = m v^2 / R \Rightarrow N = mg + m(100^2)/250 = mg + m(10000/250) = mg + m(40) = mg + 4mg = 5mg$. Vậy gấp 5 lần (5G)."},
    {"id": "mc-c4-107", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Chuyển động trên cầu",
     "question": "Nếu ô tô chạy qua cầu vồng (bán kính cong 100m) với vận tốc bao nhiêu thì áp lực của xe lên mặt cầu tại điểm cao nhất bằng 0 (xe bay hẫng lên)? (g=10)",
     "choices": ["$31,6\\text{ m/s}$ (khoảng 114 km/h)", "10 m/s", "100 m/s", "Không bao giờ xảy ra"],
     "answer": 0, "explanation": "Tại đỉnh cầu: $P - N = m v^2 / R$. Nếu $N = 0 \Rightarrow P = m v^2 / R \Rightarrow mg = m v^2 / R \Rightarrow v = \\sqrt{gR} = \\sqrt{10 \\times 100} = \\sqrt{1000} \approx 31,6\\text{ m/s}."},
    {"id": "mc-c4-108", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Bài toán va chạm nén lò xo",
     "question": "Vật 1kg rơi tự do từ độ cao 5m xuống một lò xo thẳng đứng (k=1000 N/m) đặt trên mặt đất. Bỏ qua ma sát. Độ nén cực đại của lò xo là bao nhiêu? ($g=10$, x là độ nén lớn nhất)",
     "choices": ["0,32 m", "0,1 m", "1 m", "0,05 m"],
     "answer": 0, "explanation": "Bảo toàn cơ năng: Chọn mốc thế năng trọng trường tại vị trí lò xo nén cực đại (dưới đất x). Thế năng đầu $mg(h+x)$. Thế năng cuối (tại đó vận tốc = 0) chỉ còn đàn hồi $0.5 k x^2$. $mg(h+x) = 0.5 k x^2 \Rightarrow 10(5+x) = 500 x^2 \Rightarrow 500x^2 - 10x - 50 = 0 \Rightarrow 50x^2 - x - 5 = 0$. $x = \\frac{1 + \\sqrt{1 + 1000}}{100} \approx 32.6/100 = 0.32\\text{ m}."},

    {"id": "mc-c4-109", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Cân bằng của trục quay",
     "question": "Một đĩa tròn mỏng đồng chất bị khoét một lỗ tròn nhỏ có bán kính bằng R/2 (tâm lỗ ở giữa tâm đĩa và mép đĩa). Trọng tâm của đĩa bị khoét nằm ở đâu?",
     "choices": ["Nằm trên đường nối tâm đĩa và tâm lỗ, cách tâm đĩa đoạn R/6 về phía đối diện lỗ", "Trùng với tâm đĩa", "Nằm ở tâm lỗ", "Nằm ở mép đối diện"],
     "answer": 0, "explanation": "Dùng phương pháp khối lượng âm (lỗ khoét coi như đĩa có $m_{am}$). Đĩa lớn bán kính R khối lượng M (tâm O, tọa độ 0). Lỗ bán kính R/2 khối lượng -M/4 (tâm O1, tọa độ R/2). Trọng tâm $X = \frac{M(0) + (-M/4)(R/2)}{M - M/4} = \frac{-MR/8}{3M/4} = -R/6$. Tức là dịch ra phía xa lỗ đoạn R/6."},
    {"id": "mc-c4-110", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Trạng thái con rơm",
     "question": "Đồ chơi Lật đật không bao giờ bị đổ là ứng dụng của loại cân bằng nào?",
     "choices": ["Cân bằng bền (do có trọng tâm rất thấp)", "Cân bằng không bền", "Cân bằng phiếm định", "Cân bằng động"],
     "answer": 0, "explanation": "Con lật đật có phần đáy rất nặng (chì), trọng tâm ở sát mặt đáy. Khi bị nghiêng, trọng tâm bị nâng lên cao. Trọng lực tạo ra một momen lực có xu hướng kéo nó quay trở về vị trí cân bằng cũ (Cân bằng bền)."},
    {"id": "mc-c4-111", "chapter": "c4", "lesson": "b40", "level": "vd", "dang": "Pha trộn chất lỏng",
     "question": "Pha 2 lít chất lỏng 1 (KLR $\\rho_1 = 800\\text{ kg/m}^3$) với 3 lít chất lỏng 2 (KLR $\\rho_2 = 1200\\text{ kg/m}^3$) (giả sử thể tích bảo toàn). Khối lượng riêng của hỗn hợp là:",
     "choices": ["1040 kg/m³", "1000 kg/m³", "2000 kg/m³", "1100 kg/m³"],
     "answer": 0, "explanation": "Tổng khối lượng $m = V_1 \\rho_1 + V_2 \\rho_2 = 2 \\times 800 + 3 \\times 1200 = 1600 + 3600 = 5200\\text{ g} = 5,2\\text{ kg}$ (nếu lít). Tổng V = 5 L. $\\rho = 5200 / 5 = 1040\\text{ kg/m}^3$."},
    {"id": "mc-c4-112", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Lưu lượng vòi xịt",
     "question": "Vòi bơm nước vườn có đường kính ống 2 cm. Khi không bóp đầu vòi, nước chảy ra với vận tốc 1 m/s. Để xịt nước đi xa, người ta dùng ngón tay bóp nghẹt 3/4 diện tích lỗ. Vận tốc tia nước xịt ra lúc này là:",
     "choices": ["4 m/s", "1,33 m/s", "0,25 m/s", "16 m/s"],
     "answer": 0, "explanation": "Bóp 3/4 tức là diện tích còn hở $S_2 = S_1/4$. Phương trình liên tục $S_1 v_1 = S_2 v_2 \Rightarrow v_2 = v_1 \\cdot (S_1 / (S_1/4)) = 4 v_1 = 4\\text{ m/s}."},

    {"id": "mc-c4-113", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Lực căng bề mặt",
     "question": "Giọt sương trên lá cỏ thường có dạng hình cầu vì:",
     "choices": ["Do lực căng bề mặt có xu hướng thu nhỏ diện tích mặt ngoài chất lỏng đến mức tối thiểu", "Do lực hấp dẫn của Trái Đất", "Do không khí ép vào", "Do cấu trúc phân tử lá cỏ hình cầu"],
     "answer": 0, "explanation": "Với một thể tích nhất định, hình cầu là hình có diện tích bề mặt nhỏ nhất. Lực căng bề mặt luôn kéo màng mặt thoáng co lại tới diện tích nhỏ nhất có thể."},
    {"id": "mc-c4-114", "chapter": "c4", "lesson": "b41", "level": "th", "dang": "Hiện tượng mao dẫn",
     "question": "Tại sao rễ cây có thể hút nước từ dưới đất sâu lên các nhánh cây cao?",
     "choices": ["Nhờ hiện tượng mao dẫn trong các ống mạch gỗ rất nhỏ của thân cây", "Nhờ rễ cây có một máy bơm tự nhiên cơ học", "Nhờ áp suất khí quyển ép nước lên", "Do nước tự chảy ngược chiều trọng lực"],
     "answer": 0, "explanation": "Mạch dẫn của cây có tiết diện rất bé (như ống mao dẫn), nước làm ướt thành mạch nên lực dính ướt kéo nước dâng cao trong ống ngược lại trọng lực."},
    {"id": "mc-c4-115", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Hệ hai lò xo",
     "question": "Treo vật m = 1kg vào hệ hai lò xo ghép nối tiếp $k_1 = 100\\text{ N/m}$ và $k_2 = 100\\text{ N/m}$. Độ giãn tổng cộng của hệ là: (g=10)",
     "choices": ["20 cm", "10 cm", "5 cm", "40 cm"],
     "answer": 0, "explanation": "Hệ nối tiếp $1/k = 1/100 + 1/100 = 2/100 \Rightarrow k = 50\\text{ N/m}$. Trọng lượng $P = 10\\text{ N}$. $\\Delta l = P / k = 10 / 50 = 0.2\\text{ m} = 20\\text{ cm}."},
    {"id": "mc-c4-116", "chapter": "c4", "lesson": "b36", "level": "vd", "dang": "Cân bằng trên mặt phẳng nghiêng",
     "question": "Vật 2kg đứng yên trên mặt dốc nghiêng $30^\\circ$. Hệ số ma sát trượt là $\\mu=0,8$. Lực ma sát nghỉ tác dụng lên vật là bao nhiêu? ($g=10, \sin 30^\\circ=0.5$)",
     "choices": ["10 N", "16 N", "13,8 N", "0 N"],
     "answer": 0, "explanation": "Vì đứng yên, lực ma sát nghỉ chỉ cần cân bằng đúng với thành phần trọng lực trượt xuống: $F_{ms} = P\\sin 30^\\circ = 20 \\times 0.5 = 10\\text{ N}$. (Bẫy: Không được dùng $\\mu N$ vì đó là ma sát cực đại, lớn hơn 10N)."},
    
    {"id": "mc-c4-117", "chapter": "c4", "lesson": "b38", "level": "vd", "dang": "Điều kiện không trượt và không lật",
     "question": "Một khối lập phương cạnh a đứng trên sàn. Dùng ngón tay đẩy ngang vào điểm giữa mặt bên khối. Để khối trượt mà KHÔNG BỊ LẬT, hệ số ma sát $\\mu$ phải thỏa mãn điều kiện nào?",
     "choices": ["$\\mu < 1$", "$\\mu > 1$", "$\\mu < 0,5$", "$\\mu = 1$"],
     "answer": 0, "explanation": "Đẩy ở điểm giữa (độ cao a/2). Lực đẩy F. Lực lật $M_F = F \\times (a/2)$. Momen giữ $M_P = P \\times (a/2)$. Để lật $F > P$. Để trượt $F > \mu P$. Muốn trượt trước khi lật (không lật) thì $\mu P < P \Rightarrow \mu < 1$."},
    {"id": "mc-c4-118", "chapter": "c4", "lesson": "b42", "level": "vd", "dang": "Trọng lượng hố sâu",
     "question": "Nếu mang một quả cân chuẩn 1kg đào hố xuống sâu trong lòng Trái Đất (giả sử Trái Đất đồng chất). Ở độ sâu R/2 (R là bán kính Trái Đất), quả cân sẽ:",
     "choices": ["Nhẹ hơn trên mặt đất", "Nặng hơn trên mặt đất", "Nặng bằng mặt đất", "Không trọng lượng"],
     "answer": 0, "explanation": "Bên trong quả cầu đồng chất, lực hấp dẫn giảm tuyến tính với bán kính (do lớp vỏ ngoài triệt tiêu lực). Tại r = R/2, g giảm một nửa, nên nhẹ hơn."},
    {"id": "mc-c4-119", "chapter": "c4", "lesson": "b41", "level": "vd", "dang": "Áp suất chân không",
     "question": "Bơm hút chân không tạo ra môi trường có áp suất rất thấp. Nếu áp suất trong bóng đèn sợi đốt là $10^4\\text{ Pa}$. Áp suất không khí ngoài là $10^5\\text{ Pa}$. Bóng đèn có bán kính 2cm, bề mặt hình cầu ($S = 4\\pi R^2 \\approx 50\\text{ cm}^2$). Tổng lực ép của khí quyển làm đèn dễ nổ tung vào trong là khoảng:",
     "choices": ["450 N", "50 N", "1000 N", "5000 N"],
     "answer": 0, "explanation": "Chênh lệch áp suất $\\Delta p = 10^5 - 10^4 = 9\\cdot 10^4\\text{ Pa}$. $S = 0.005\\text{ m}^2$. $F = \\Delta p \cdot S = 90000 \times 0.005 = 450\\text{ N}."},
    {"id": "mc-c4-120", "chapter": "c4", "lesson": "b34", "level": "vd", "dang": "Truyền động xích",
     "question": "Đĩa xích xe đạp có 40 răng, líp (đĩa nhỏ sau) có 20 răng. Khi người đạp quay đĩa xích 1 vòng/giây thì bánh xe sau (gắn với líp) sẽ quay với tốc độ góc bao nhiêu vòng/giây?",
     "choices": ["2 vòng/giây", "1 vòng/giây", "0,5 vòng/giây", "4 vòng/giây"],
     "answer": 0, "explanation": "Líp nhỏ hơn 2 lần nên sẽ quay nhanh gấp 2 lần. $n_{lip} = n_{dia} \cdot (Z_{dia}/Z_{lip}) = 1 \cdot (40/20) = 2$ vòng/giây."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C4 Part 2 written successfully.")
