import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 5 HÓA HỌC 10: TỐC ĐỘ PHẢN ỨNG HÓA HỌC (Phần 2) ---
    # Nhóm 1, 2, 3: Năng lượng hoạt hóa Ea và Phương trình Arrhenius
    {"id": "mc-c5-061", "chapter": "c5", "lesson": "b27", "level": "nb", "dang": "Khái niệm Năng lượng hoạt hóa",
     "question": "Năng lượng hoạt hóa ($E_a$) của một phản ứng là:",
     "choices": ["Năng lượng tối thiểu mà các phân tử chất phản ứng cần phải có để va chạm có hiệu quả (xảy ra phản ứng)", "Năng lượng tỏa ra môi trường sau khi phản ứng kết thúc", "Năng lượng liên kết của sản phẩm", "Nhiệt độ tối thiểu để dung dịch sôi"],
     "answer": 0, "explanation": "Các chất không tự nhiên phản ứng với nhau nếu không có động năng đủ lớn để bẻ gãy liên kết cũ. Rào cản năng lượng tối thiểu đó gọi là Năng lượng hoạt hóa (Activation Energy - $E_a$)."},
    {"id": "mc-c5-062", "chapter": "c5", "lesson": "b27", "level": "th", "dang": "Nhiệt độ và va chạm",
     "question": "Khi tăng nhiệt độ, số lượng va chạm giữa các phân tử tăng lên một lượng NHỎ, nhưng tốc độ phản ứng lại tăng lên rất LỚN. Lí do chính là:",
     "choices": ["Tỉ lệ số phân tử có động năng lớn hơn năng lượng hoạt hóa ($E_a$) tăng lên theo cấp số mũ", "Phân tử to ra nên dễ va chạm hơn", "Chất xúc tác được sinh ra ở nhiệt độ cao", "Áp suất tự động giảm đi"],
     "answer": 0, "explanation": "Tăng nhiệt độ $10^\\circ\\text{C}$ chỉ làm số va chạm tổng cộng tăng $\\sim 2\\%$, nhưng làm SỐ PHÂN TỬ VƯỢT QUA NGƯỠNG $E_a$ tăng $200\\% - 300\\%$ (tăng gấp 2-3 lần). Đó mới là yếu tố quyết định."},
    {"id": "mc-c5-063", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "Phương trình Arrhenius",
     "question": "Theo phương trình Arrhenius $k = A \\cdot e^{-E_a / (RT)}$, khẳng định nào sau đây ĐÚNG về mối quan hệ giữa $k$ và $E_a$ (ở cùng một nhiệt độ T)?",
     "choices": ["Phản ứng có $E_a$ càng LỚN thì hằng số tốc độ $k$ càng NHỎ (phản ứng xảy ra càng chậm)", "Phản ứng có $E_a$ càng LỚN thì $k$ càng LỚN", "$k$ và $E_a$ tỉ lệ thuận tuyến tính", "$k$ không phụ thuộc vào $E_a$"],
     "answer": 0, "explanation": "Do có dấu trừ ở số mũ ($-E_a / RT$), $E_a$ càng lớn thì giá trị cụm mũ càng âm sâu $\\Rightarrow e^{-\\text{lớn}}$ càng tiến về 0 $\\Rightarrow k$ càng nhỏ. Rào cản lớn thì ít hạt qua được $\\Rightarrow$ Tốc độ chậm."},
    {"id": "mc-c5-064", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "Ảnh hưởng thực tế của Ea",
     "question": "Hai phản ứng (1) và (2) cùng thực hiện ở $25^\\circ\\text{C}$. Phản ứng (1) có $E_a = 40 \\text{ kJ/mol}$, phản ứng (2) có $E_a = 120 \\text{ kJ/mol}$. Phản ứng nào xảy ra nhanh hơn?",
     "choices": ["Phản ứng (1) xảy ra nhanh hơn rất nhiều", "Phản ứng (2) xảy ra nhanh hơn", "Hai phản ứng nhanh như nhau", "Phản ứng (1) không xảy ra được"],
     "answer": 0, "explanation": "Phản ứng (1) có rào cản năng lượng thấp (40 kJ/mol), dễ dàng bị vượt qua bởi nhiệt năng ở phòng, nên sẽ xảy ra rất nhanh so với (2)."},

    # Nhóm 4, 5, 6: Bài tập tổng hợp các yếu tố ảnh hưởng
    {"id": "mc-c5-065", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Biện pháp bảo quản Gỗ",
     "question": "Để bảo vệ gỗ khỏi bị mối mọt và mục nát (các quá trình phân hủy), người ta thường ngâm gỗ vào hóa chất hoặc sơn phủ bề mặt. Việc làm này ứng dụng yếu tố nào để giảm tốc độ phản ứng?",
     "choices": ["Giảm nồng độ/diện tích tiếp xúc của các tác nhân phân hủy ($O_2$, hơi nước, vi khuẩn) với bề mặt gỗ", "Giảm áp suất không khí", "Tăng nhiệt độ của gỗ", "Sử dụng xúc tác dương"],
     "answer": 0, "explanation": "Lớp sơn hoặc hóa chất tạo màng cách li, làm giảm bề mặt tiếp xúc trực tiếp giữa xenlulozo và các tác nhân oxi hóa sinh học, từ đó giảm tốc độ phân hủy."},
    {"id": "mc-c5-066", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tăng tốc độ pư dị thể",
     "question": "Hòa tan $Zn$ rắn vào dung dịch $H_2SO_4$ loãng. Thay đổi nào sau đây sẽ làm tăng tốc độ thoát khí $H_2$ MẠNH NHẤT?",
     "choices": ["Dùng kẽm bột thay cho kẽm viên, đồng thời đun nóng dung dịch", "Dùng kẽm viên và pha loãng thêm dung dịch", "Làm lạnh dung dịch $H_2SO_4$", "Thêm một lượng nước cất lớn vào dung dịch"],
     "answer": 0, "explanation": "Kẽm bột $\\Rightarrow$ Tăng diện tích bề mặt. Đun nóng $\\Rightarrow$ Tăng nhiệt độ. Kết hợp 2 yếu tố này tốc độ sẽ tăng vọt mạnh nhất. Pha loãng hay làm lạnh đều làm giảm tốc độ."},
    {"id": "mc-c5-067", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Nồng độ sau t",
     "question": "Cho đồ thị Nồng độ - Thời gian của chất A: $t=0, [A] = 1,0 \\text{ M}$; $t=10, [A] = 0,5 \\text{ M}$; $t=20, [A] = 0,25 \\text{ M}$. Ở $t=30$, nồng độ [A] gần với giá trị nào nhất? (Biết đây là phản ứng bậc 1 có chu kì bán hủy không đổi)",
     "choices": ["0,125 M", "0,0 M", "0,15 M", "0,5 M"],
     "answer": 0, "explanation": "Cứ 10 giây nồng độ giảm đi một nửa (Chu kì bán hủy $t_{1/2} = 10s$). Từ 20s đến 30s (qua 10s nữa), nồng độ sẽ tiếp tục giảm một nửa: $0,25 / 2 = 0,125 \\text{ M}$."},
    {"id": "mc-c5-068", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Áp suất có tác dụng?",
     "question": "Xét phản ứng nung vôi: $CaCO_3(s) \\rightleftharpoons CaO(s) + CO_2(g)$. Để tăng TỐC ĐỘ phản ứng theo CHIỀU THUẬN (phân hủy), ta NÊN thay đổi áp suất như thế nào?",
     "choices": ["Áp suất của hệ không làm thay đổi tốc độ phản ứng theo chiều thuận", "Nén áp suất cao để tăng tốc độ", "Bơm thêm khí N2 vào", "Hút chân không"],
     "answer": 0, "explanation": "Chiều thuận là chất rắn bị nhiệt phân. Chất phản ứng chỉ có $CaCO_3(s)$, KHÔNG CÓ chất khí. Vậy tốc độ chiều thuận KHÔNG phụ thuộc vào áp suất khí quyển phía trên (nó chỉ phụ thuộc nhiệt độ và diện tích bề mặt rắn). (Việc hút chân không giúp cân bằng CHUYỂN DỊCH, chứ không làm TĂNG TỐC ĐỘ phản ứng thuận ở thời điểm $t_0$)."},
    
    # Nhóm 7, 8, 9: Bài toán Định luật tác dụng khối lượng 2
    {"id": "mc-c5-069", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Viết biểu thức v",
     "question": "Cho phản ứng đơn giản: $H_2(g) + I_2(g) \\rightarrow 2HI(g)$. Biểu thức tốc độ phản ứng thuận là:",
     "choices": ["$v = k \\cdot [H_2] \\cdot [I_2]$", "$v = k \\cdot [H_2] \\cdot [I_2]^2$", "$v = k \\cdot [HI]^2$", "$v = k \\cdot \\frac{[H_2]}{[I_2]}$"],
     "answer": 0, "explanation": "Vì là phản ứng đơn giản, bậc của mỗi chất bằng đúng hệ số tỉ lượng của nó trong phương trình. $H_2$ hệ số 1, $I_2$ hệ số 1. $\\Rightarrow v = k[H_2]^1[I_2]^1$."},
    {"id": "mc-c5-070", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Xác định bậc từ bảng số liệu",
     "question": "Cho phản ứng $A + B \\rightarrow C$. Khi giữ nguyên nồng độ B, tăng nồng độ A gấp đôi thì tốc độ phản ứng KHÔNG ĐỔI. Bậc của phản ứng theo chất A là:",
     "choices": ["Bậc 0", "Bậc 1", "Bậc 2", "Bậc -1"],
     "answer": 0, "explanation": "Tốc độ không bị ảnh hưởng bởi sự thay đổi nồng độ của A $\\Rightarrow v$ tỉ lệ với $[A]^0$. Bậc phản ứng theo chất A là 0. (Biểu thức $v = k[B]^x$)."},
    {"id": "mc-c5-071", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Xác định bậc từ bảng số liệu 2",
     "question": "Trong phản ứng $A + B \\rightarrow C$. Khi tăng $[A]$ gấp đôi ($[B]$ giữ nguyên) thì tốc độ tăng gấp đôi. Khi tăng $[B]$ gấp đôi ($[A]$ giữ nguyên) thì tốc độ tăng gấp 4 lần. Biểu thức tốc độ phản ứng là:",
     "choices": ["$v = k[A][B]^2$", "$v = k[A][B]$", "$v = k[A]^2[B]^2$", "$v = k[A]^2[B]$"],
     "answer": 0, "explanation": "$[A]$ tăng 2, v tăng 2 $\\Rightarrow$ Tỉ lệ thuận bậc 1 theo A ($[A]^1$). $[B]$ tăng 2, v tăng 4 ($2^2$) $\\Rightarrow$ Tỉ lệ thuận bậc 2 theo B ($[B]^2$). Vậy $v = k[A][B]^2$."},
    {"id": "mc-c5-072", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tốc độ trung bình",
     "question": "Tính tốc độ trung bình của phản ứng $2SO_2 + O_2 \\rightarrow 2SO_3$ theo $SO_2$. Biết trong 40 giây, nồng độ $SO_2$ giảm từ $0,80 \\text{ M}$ xuống $0,20 \\text{ M}$.",
     "choices": ["$0,015 \\text{ M/s}$", "$0,0075 \\text{ M/s}$", "$0,020 \\text{ M/s}$", "$0,030 \\text{ M/s}$"],
     "answer": 0, "explanation": "Tốc độ phản ứng chung $\\bar{v} = -\\frac{1}{2} \\frac{\\Delta [SO_2]}{\\Delta t} = -\\frac{1}{2} \\frac{-0,60}{40} = 0,0075 \\text{ M/s}$."},
    
    # Nhóm 10, 11, 12: Động học xúc tác
    {"id": "mc-c5-073", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Xúc tác sinh học",
     "question": "Chất xúc tác có trong các tế bào sinh vật, có bản chất là protein, xúc tác cho các phản ứng sinh hóa ở nhiệt độ cơ thể được gọi chung là:",
     "choices": ["Enzyme", "Hormone", "Vitamin", "Kháng sinh"],
     "answer": 0, "explanation": "Enzyme (men) là các chất xúc tác sinh học cực kì quan trọng. Mỗi loại enzyme thường chỉ xúc tác đặc hiệu cho một loại phản ứng hoặc một loại cơ chất duy nhất."},
    {"id": "mc-c5-074", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Biểu diễn xúc tác trên PT",
     "question": "Trong phương trình hóa học, chất xúc tác thường được ghi ở vị trí nào?",
     "choices": ["Viết trên (hoặc dưới) mũi tên phản ứng", "Viết cùng với các chất tham gia bên trái", "Viết cùng với sản phẩm bên phải", "Không bao giờ được ghi vào phương trình"],
     "answer": 0, "explanation": "Vì chất xúc tác không bị tiêu hao, không phải chất tham gia gốc, cũng không phải sản phẩm cuối, nên người ta ghi nó trên mũi tên điều kiện. Ví dụ: $\\xrightarrow{MnO_2}$."},
    {"id": "mc-c5-075", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Xúc tác đồng thể",
     "question": "Phản ứng ester hóa giữa Axit axetic (lỏng) và Ethanol (lỏng) sử dụng $H_2SO_4$ đặc (lỏng) làm chất xúc tác. Xúc tác trong trường hợp này thuộc loại:",
     "choices": ["Xúc tác đồng thể", "Xúc tác dị thể", "Xúc tác sinh học", "Xúc tác tự động"],
     "answer": 0, "explanation": "Cả axit, rượu và chất xúc tác $H_2SO_4$ đều ở trạng thái lỏng (tan lẫn vào nhau thành một pha đồng nhất). Không có ranh giới pha. Gọi là xúc tác đồng thể."},
    {"id": "mc-c5-076", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Chất xúc tác làm cân bằng",
     "question": "Việc sử dụng chất xúc tác $V_2O_5$ trong phản ứng tổng hợp $SO_3$ (từ $SO_2$ và $O_2$) có làm tăng HIỆU SUẤT TỐI ĐA (lượng $SO_3$ thu được ở trạng thái cân bằng) không?",
     "choices": ["Không, xúc tác chỉ làm phản ứng ĐẠT đến trạng thái cân bằng NHANH HƠN, không làm thay đổi vị trí cân bằng", "Có, xúc tác làm tăng lượng sản phẩm thu được", "Có, xúc tác làm chuyển dịch cân bằng sang phải", "Làm giảm hiệu suất nhưng chạy nhanh hơn"],
     "answer": 0, "explanation": "Chất xúc tác làm giảm $E_a$ cho CẢ chiều thuận và chiều nghịch như nhau $\\Rightarrow$ Tốc độ 2 chiều tăng như nhau $\\Rightarrow$ Cân bằng hóa học KHÔNG bị chuyển dịch, hằng số cân bằng $K_c$ không đổi. Lượng sản phẩm max là không đổi, chỉ là thu hoạch nhanh hơn."},
    
    # Nhóm 13, 14, 15: Nhiệt độ chuyên sâu
    {"id": "mc-c5-077", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Độ nhạy của phản ứng với Nhiệt",
     "question": "Hệ số nhiệt độ $\\gamma$ của một phản ứng nằm trong khoảng từ 2 đến 4. Nếu phản ứng có $E_a$ (Năng lượng hoạt hóa) CÀNG CAO thì $\\gamma$ sẽ:",
     "choices": ["Thường có giá trị CÀNG LỚN (phản ứng rất nhạy cảm với sự thay đổi nhiệt độ)", "Thường có giá trị càng nhỏ", "Luôn luôn bằng 2", "Bằng 0"],
     "answer": 0, "explanation": "Phản ứng có rào cản $E_a$ lớn thì ở nhiệt độ thấp gần như không xảy ra. Khi đun nóng, số hạt vượt rào cản tăng lên theo cấp số mũ rất dốc. Do đó tốc độ tăng vọt mạnh ($\\gamma$ lớn). Phản ứng $E_a$ nhỏ thì $\\gamma$ nhỏ (vd $\\gamma \\approx 1$)."},
    {"id": "mc-c5-078", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Thời Gian Giảm",
     "question": "Nếu thời gian hoàn thành một phản ứng ở $60^\\circ\\text{C}$ là 3 phút. Hỏi ở $30^\\circ\\text{C}$ thì phản ứng đó cần bao nhiêu phút? Biết $\\gamma = 2$.",
     "choices": ["24 phút", "12 phút", "1,5 phút", "9 phút"],
     "answer": 0, "explanation": "Giảm nhiệt độ từ $60$ xuống $30$ (giảm $30^\\circ = 3$ khoảng). Tốc độ sẽ GIẢM $2^3 = 8$ lần. Tốc độ chậm đi 8 lần $\\Rightarrow$ THỜI GIAN sẽ KÉO DÀI gấp 8 lần. $3 \\text{ phút} \\times 8 = 24 \\text{ phút}$."},
    {"id": "mc-c5-079", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Chất ức chế",
     "question": "Vì sao các chất chống oxi hóa (như Vitamin E, C) được thêm vào dầu mỡ hoặc mĩ phẩm?",
     "choices": ["Chúng đóng vai trò như chất ức chế (xúc tác âm) tiêu diệt các gốc tự do, làm giảm mạnh tốc độ phản ứng oxi hóa lipid, giúp lâu hỏng", "Chúng tăng tốc độ oxi hóa để diệt khuẩn", "Chúng làm tăng nhiệt độ của mĩ phẩm", "Chúng là chất tạo màu"],
     "answer": 0, "explanation": "Quá trình ôi thiu dầu mỡ là phản ứng dây chuyền qua trung gian gốc tự do. Các chất chống oxi hóa chặn đứng chuỗi phản ứng này, làm tốc độ phản ứng giảm gần như bằng 0 (chất ức chế)."},
    {"id": "mc-c5-080", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Sự rỉ sét",
     "question": "Để giảm tốc độ ăn mòn (rỉ sét) của sắt thép, người ta thường dùng phương pháp nào liên quan đến yếu tố tốc độ phản ứng?",
     "choices": ["Sơn mạ, bôi dầu mỡ để giảm/triệt tiêu bề mặt tiếp xúc của sắt với Oxi và nước", "Đun nóng sắt liên tục", "Đập nhỏ khối sắt ra", "Thêm chất xúc tác vào"],
     "answer": 0, "explanation": "Lớp mạ (sơn, kẽm, dầu) cô lập sắt khỏi môi trường. Yếu tố nồng độ và diện tích tiếp xúc với tác nhân ăn mòn bị triệt tiêu $\\Rightarrow v = 0$."},
    
    # Nhóm 16, 17, 18: Đồ thị thể tích / khối lượng theo thời gian
    {"id": "mc-c5-081", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Đồ thị khối lượng",
     "question": "Thả đá vôi vào axit HCl chứa trong một cốc mở. Đặt cốc trên một cái cân. Số chỉ của cân sẽ thay đổi như thế nào theo thời gian?",
     "choices": ["Giảm dần với tốc độ nhanh lúc đầu, sau đó chậm lại và cuối cùng đứng yên (không đổi)", "Tăng dần liên tục", "Giảm đều đặn tạo thành một đường thẳng chéo", "Không thay đổi vì khối lượng bảo toàn"],
     "answer": 0, "explanation": "Phản ứng sinh khí $CO_2$ bay mất, nên khối lượng cốc + hóa chất giảm. Tốc độ sinh khí nhanh nhất lúc đầu (nồng độ HCl lớn) nên cân giảm nhanh. Càng về sau tốc độ chậm lại, đến khi phản ứng hết thì cân đứng yên. Khối lượng bảo toàn áp dụng cho toàn hệ (kể cả khí bay đi), còn cân chỉ đo khối lượng cốc."},
    {"id": "mc-c5-082", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Phân tích 2 đồ thị",
     "question": "Thực hiện 2 thí nghiệm hòa tan Kẽm vào HCl. Thí nghiệm 1 dùng Kẽm viên. Thí nghiệm 2 dùng Kẽm bột (cùng khối lượng). Đồ thị biểu diễn V($H_2$) theo thời gian của TN2 so với TN1 sẽ:",
     "choices": ["Dốc đứng hơn và đạt đến thể tích tối đa sớm hơn, nhưng thể tích tối đa của hai thí nghiệm bằng nhau", "Đạt thể tích tối đa lớn hơn gấp đôi", "Nằm dưới đường cong của TN1", "Dốc hơn và thể tích tối đa nhỏ hơn"],
     "answer": 0, "explanation": "Do dùng bột nên diện tích tiếp xúc lớn, tốc độ nhanh $\\Rightarrow$ đồ thị dốc cao và kết thúc sớm (thời gian ngắn). Tuy nhiên lượng Kẽm bằng nhau nên TỔNG lượng $H_2$ sinh ra là NHƯ NHAU (hai đường cong chụm lại 1 điểm ở cuối)."},
    {"id": "mc-c5-083", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Tốc độ từ Đồ thị",
     "question": "Khối lượng của cốc phản ứng giảm từ 100,00g xuống 99,56g trong 2 phút đầu tiên do $CO_2$ bay ra. Tốc độ trung bình tiêu thụ $CaCO_3$ trong thời gian này là: (C=12, O=16, Ca=40)",
     "choices": ["0,005 mol/phút", "0,01 mol/phút", "0,22 mol/phút", "0,44 mol/phút"],
     "answer": 0, "explanation": "Độ giảm khối lượng chính là lượng $CO_2$ bay ra = $0,44$ g. $\\Rightarrow n(CO_2) = 0,44 / 44 = 0,01$ mol. Bảo toàn Ca: $n(CaCO_3) = n(CO_2) = 0,01$ mol. $\\bar{v}(\\text{theo mol}) = \\frac{0,01 \\text{ mol}}{2 \\text{ phút}} = 0,005 \\text{ mol/phút}$."},
    
    # Nhóm 19, 20: Ứng dụng thực tiễn của Tốc độ phản ứng
    {"id": "mc-c5-084", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Quạt than",
     "question": "Khi quạt gió vào bếp than đang cháy, than sẽ cháy rực và mạnh hơn. Tại sao?",
     "choices": ["Làm tăng nồng độ khí Oxi cung cấp liên tục cho bề mặt than", "Vì gió chứa chất xúc tác", "Làm tăng diện tích bề mặt của than", "Vì gió hút nhiệt của than"],
     "answer": 0, "explanation": "Khi cháy, lớp Oxi mỏng bao quanh cục than bị cạn kiệt thành $CO_2$. Quạt gió thổi $CO_2$ đi và mang lớp $O_2$ mới tinh với nồng độ cao (21%) tới $\\Rightarrow$ tăng nồng độ chất phản ứng tại bề mặt $\\Rightarrow$ tăng tốc độ cháy."},
    {"id": "mc-c5-085", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Nồi áp suất",
     "question": "Vì sao ninh xương, hầm thịt bằng \"Nồi áp suất\" lại cực kì nhanh nhừ so với nồi bình thường?",
     "choices": ["Áp suất hơi nước nén lại làm nhiệt độ sôi của nước tăng lên cao hơn $100^\\circ\\text{C}$ (thường khoảng $120^\\circ\\text{C}$). Nhiệt độ cao làm tốc độ phân hủy protein tăng vọt", "Vì áp suất cao bóp nát xương", "Vì nồi áp suất không cho oxi thoát ra ngoài", "Vì nồi bằng nhôm có chất xúc tác"],
     "answer": 0, "explanation": "Tốc độ phản ứng phân cắt collagen/protein quyết định độ nhừ. Nồi thường nước chỉ sôi ở max $100^\\circ\\text{C}$. Nồi nén hơi kín làm áp suất tăng $\\Rightarrow$ nước sôi ở $\\sim 115-120^\\circ\\text{C}$. Đun ở $120^\\circ\\text{C}$ làm tốc độ nhừ tăng gấp $2^{(120-100)/10} = 4$ lần."},
    {"id": "mc-c5-086", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Hàn xì đá",
     "question": "Khi dùng đèn xì Oxi-Axetilen để hàn cắt kim loại, tại sao người ta phải cung cấp khí $O_2$ nguyên chất từ bình thay vì dùng không khí tự nhiên?",
     "choices": ["Vì $O_2$ nguyên chất có nồng độ $100\\%$ (cao gấp 5 lần không khí), làm tốc độ cháy cực nhanh và sinh ra nhiệt độ tập trung rất cao (lên tới $3000^\\circ\\text{C}$)", "Vì không khí có chứa bụi làm hỏng mối hàn", "Vì Axetilen không cháy trong không khí", "Vì $O_2$ là chất xúc tác"],
     "answer": 0, "explanation": "Tăng nồng độ chất tham gia ($O_2$) $\\Rightarrow$ Tốc độ phản ứng cháy tăng kịch liệt. Hơn nữa không phải tốn nhiệt để hâm nóng $78\\%$ khí $N_2$ dư thừa trong không khí, nên nhiệt độ ngọn lửa đạt cực đại để cắt đứt sắt thép."},
    
    # 34 câu củng cố đa dạng (chống lặp form)
    {"id": "mc-c5-087", "chapter": "c5", "lesson": "b25", "level": "nb", "dang": "Điều kiện hệ kín",
     "question": "Khái niệm \"Tốc độ phản ứng trung bình\" thường được áp dụng cho:",
     "choices": ["Một khoảng thời gian nhất định ($\\Delta t$)", "Một thời điểm tức thời ($dt$)", "Toàn bộ chu kì sống của trái đất", "Không phụ thuộc vào thời gian"],
     "answer": 0, "explanation": "Trung bình (Average rate) đo sự thay đổi từ lúc $t_1$ đến $t_2$. Tức thời (Instantaneous rate) đo tại một mốc $t$ xác định (tiếp tuyến đồ thị)."},
    {"id": "mc-c5-088", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Nhiệt độ và Enzyme",
     "question": "Enzyme sinh học hoạt động tốt nhất ở $37^\\circ\\text{C}$. Nếu đun nóng dung dịch lên $100^\\circ\\text{C}$ thì phản ứng sinh hóa sẽ:",
     "choices": ["Bị dừng lại hoàn toàn vì enzyme có bản chất là protein, bị biến tính và mất tác dụng ở nhiệt độ cao", "Xảy ra cực kì nhanh theo định luật Van't Hoff", "Không đổi", "Phát nổ"],
     "answer": 0, "explanation": "Khác với hóa học vô cơ, xúc tác sinh học (protein) cấu trúc không gian 3D bị phá vỡ (chín, đông tụ) khi đun nóng. Khi xúc tác hỏng, phản ứng không thể xảy ra được nữa."},
    {"id": "mc-c5-089", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Ảnh hưởng Kích thước tiểu phân",
     "question": "Phản ứng đốt cháy than: $C(s) + O_2(g) \\rightarrow CO_2(g)$. Các hành động: (1) Nghiền than thành bột. (2) Đốt trong bình $O_2$ nguyên chất. (3) Trộn thêm khí $N_2$. Hành động nào LÀM CHẬM tốc độ phản ứng?",
     "choices": ["(3) Trộn thêm khí $N_2$", "(1) Nghiền than", "(2) Đốt trong $O_2$", "Cả 1 và 2"],
     "answer": 0, "explanation": "Nghiền than (tăng diện tích bề mặt) $\\rightarrow$ Nhanh. Bơm $O_2$ tinh khiết (tăng nồng độ $O_2$) $\\rightarrow$ Nhanh. Bơm thêm $N_2$ vào bình (ở thể tích cố định không đổi hoặc bơm làm pha loãng $O_2$) sẽ làm giảm hoặc không ảnh hưởng. Nếu cùng áp suất chung thì bơm N2 làm GIẢM phần áp của $O_2$ (Pha loãng) $\\rightarrow$ Chậm lại."},
    {"id": "mc-c5-090", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "So sánh Ea hai phản ứng",
     "question": "Một phản ứng có Năng lượng hoạt hóa $E_a = 50 \\text{ kJ/mol}$. Khi thêm chất xúc tác, $E_a$ mới là $30 \\text{ kJ/mol}$. Khẳng định nào sau đây SAI?",
     "choices": ["Nhiệt lượng tỏa ra của phản ứng ($\\Delta H$) bị tăng thêm 20 kJ", "Tốc độ phản ứng tăng mạnh", "Đỉnh của đường cong năng lượng bị hạ thấp", "Cơ chế của phản ứng đã bị thay đổi"],
     "answer": 0, "explanation": "Xúc tác KHÔNG làm thay đổi mức năng lượng của chất tham gia và sản phẩm, nên biến thiên Enthalpy $\\Delta_r H$ của hệ là ĐỊNH MỨC KHÔNG ĐỔI. Xúc tác chỉ can thiệp vào đường đi trung gian."},
    
    {"id": "mc-c5-091", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Tổng hợp Bậc PƯ",
     "question": "Cho phản ứng $2A + B \\rightarrow C$. Biểu thức tốc độ thực nghiệm là $v = k[A]^1 \\cdot [B]^1$. Bậc tổng hợp của phản ứng này là:",
     "choices": ["Bậc 2", "Bậc 3", "Bậc 1", "Không xác định"],
     "answer": 0, "explanation": "Bậc phản ứng theo thực nghiệm = tổng các số mũ = $1 + 1 = 2$. Lưu ý nó CÓ THỂ KHÁC VỚI HỆ SỐ TỈ LƯỢNG (hệ số là $2A + 1B = 3$) vì phản ứng này có thể xảy ra qua nhiều bước, bước chậm nhất quyết định phương trình tốc độ."},
    {"id": "mc-c5-092", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Cân bằng tốc độ",
     "question": "Phản ứng đạt trạng thái cân bằng động khi:",
     "choices": ["Tốc độ phản ứng thuận BẰNG tốc độ phản ứng nghịch ($v_{thuận} = v_{nghịch} \\neq 0$)", "Phản ứng dừng lại hoàn toàn ($v=0$)", "Nồng độ chất tham gia bằng nồng độ sản phẩm", "Khối lượng 2 bên bằng nhau"],
     "answer": 0, "explanation": "Định nghĩa Cân bằng động hóa học: Phản ứng thuận và nghịch vẫn đang diễn ra, nhưng với tốc độ bằng nhau nên sự tạo ra và sự tiêu hao bù trừ cho nhau, làm nồng độ các chất trong hệ không đổi."},
    {"id": "mc-c5-093", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Suy luận Tốc độ theo thời gian",
     "question": "Đối với phản ứng phân hủy $N_2O_5 \\rightarrow 2NO_2 + \\frac{1}{2}O_2$. Ở nhiệt độ $45^\\circ\\text{C}$, tốc độ tức thời đo được tại thời điểm $t = 10 \\text{ s}$ là $v_{10}$, tại $t = 50 \\text{ s}$ là $v_{50}$. So sánh hai giá trị này?",
     "choices": ["$v_{10} > v_{50}$", "$v_{10} < v_{50}$", "$v_{10} = v_{50}$", "Không so sánh được"],
     "answer": 0, "explanation": "Nồng độ chất phản ứng $N_2O_5$ luôn giảm dần theo thời gian. Tốc độ tức thời tỉ lệ với nồng độ hiện có. Tại giây 10 nồng độ đang cao hơn giây 50 $\\Rightarrow$ Tốc độ $v_{10}$ lớn hơn $v_{50}$."},
    {"id": "mc-c5-094", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Hiệu suất vs Tốc độ",
     "question": "Quá trình ủ men rượu từ gạo. Để rượu nhanh lên men hơn (tăng tốc độ), người ta ủ ấm. Nhưng nếu ủ quá nóng (vd $80^\\circ\\text{C}$) thì hiện tượng gì sẽ xảy ra?",
     "choices": ["Nấm men (vi sinh vật tiết enzyme xúc tác) bị chết ở nhiệt độ quá cao, phản ứng lên men bị ngừng trệ hoàn toàn", "Phản ứng xảy ra trong chớp mắt thành cồn nguyên chất", "Rượu biến thành khí bay mất", "Gạo chín thành cơm"],
     "answer": 0, "explanation": "Các phản ứng sinh học có điểm cực đại nhiệt độ (Optimum temperature). Dưới nhiệt độ đó thì Van't Hoff đúng (tăng T $\\rightarrow$ tăng V). Vượt quá thì bản thân bộ máy xúc tác sinh học (tế bào men, enzyme) bị phân hủy/chết $\\rightarrow$ Tốc độ rơi thẳng đứng về 0."},

    {"id": "mc-c5-095", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Chất xúc tác có trong sp không?",
     "question": "Kết luận nào ĐÚNG về khối lượng của chất xúc tác trong một bình phản ứng kín, từ lúc bắt đầu cho đến lúc phản ứng kết thúc?",
     "choices": ["Khối lượng chất xúc tác không thay đổi", "Khối lượng chất xúc tác tăng lên", "Khối lượng chất xúc tác giảm dần về 0", "Lúc đầu giảm, lúc sau tăng vượt mức ban đầu"],
     "answer": 0, "explanation": "Chất xúc tác tái sinh hoàn toàn $\\Rightarrow$ Khối lượng và bản chất hóa học ở trạng thái ban đầu và sau khi kết thúc phản ứng là Y HỆT NHAU."},
    {"id": "mc-c5-096", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Ví dụ phân biệt yếu tố",
     "question": "Sử dụng tủ sấy khô ở $100^\\circ\\text{C}$ để làm vải ướt nhanh khô hơn. Yếu tố nào đã làm tăng tốc độ quá trình hóa hơi của nước?",
     "choices": ["Nhiệt độ", "Nồng độ", "Áp suất", "Chất xúc tác"],
     "answer": 0, "explanation": "Tủ sấy cung cấp nhiệt $\\Rightarrow$ Tăng nhiệt độ làm động năng phân tử nước lỏng vượt ngưỡng liên kết hidro $\\Rightarrow$ Hóa hơi cực nhanh."},
    {"id": "mc-c5-097", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Bài toán Van't Hoff 3",
     "question": "Ở nhiệt độ $20^\\circ\\text{C}$, tốc độ một phản ứng là $v$. Khi đun lên $60^\\circ\\text{C}$, tốc độ phản ứng là $16v$. Nếu đun lên $80^\\circ\\text{C}$ thì tốc độ phản ứng sẽ gấp bao nhiêu lần $v$ ban đầu?",
     "choices": ["64 lần", "32 lần", "128 lần", "256 lần"],
     "answer": 0, "explanation": "Từ $20$ lên $60$ (4 khoảng), tốc độ tăng $16 = 2^4 \Rightarrow \gamma = 2$. Từ $20$ lên $80$ (6 khoảng), tốc độ tăng $\\gamma^6 = 2^6 = 64$ lần."},
    {"id": "mc-c5-098", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Hiểu hằng số k",
     "question": "Đơn vị của hằng số tốc độ $k$ trong phản ứng Bậc 1 là:",
     "choices": ["$s^{-1}$ (hoặc phút$^{-1}$...)", "$M \\cdot s^{-1}$", "$L \\cdot mol^{-1} \\cdot s^{-1}$", "Không có đơn vị"],
     "answer": 0, "explanation": "Bậc 1: $v = k[A]$. $v$ có đơn vị là $M \\cdot s^{-1}$, $[A]$ có đơn vị $M$. Do đó $k = v / [A] = (M \\cdot s^{-1}) / M = s^{-1}$. Đơn vị của $k$ phụ thuộc vào BẬC của phản ứng."},

    {"id": "mc-c5-099", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Thí nghiệm H2O2",
     "question": "Oxy già ($H_2O_2$) tự phân hủy rất chậm ở nhiệt độ phòng. Nhưng nếu nhỏ vài giọt máu (hoặc củ khoai tây sống) vào, bọt khí $O_2$ thoát ra dữ dội. Máu/khoai tây chứa:",
     "choices": ["Enzyme Catalase đóng vai trò chất xúc tác phân hủy $H_2O_2$", "Hóa chất tác dụng trực tiếp với oxy già tạo kết tủa", "Dung dịch kiềm làm tăng nhiệt độ", "Vi khuẩn ăn oxy già"],
     "answer": 0, "explanation": "Trong máu và tế bào thực vật có enzyme Catalase. H2O2 là chất độc sinh ra trong quá trình trao đổi chất, enzyme này xúc tác giải độc H2O2 thành H2O và O2 cực nhanh."},
    {"id": "mc-c5-100", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Phân biệt Nồng độ / Áp suất",
     "question": "Khi hòa tan 1 viên kẽm vào $HCl$ 1M. Hành động nào sau đây làm TĂNG NỒNG ĐỘ để tăng tốc độ phản ứng?",
     "choices": ["Dùng dung dịch $HCl$ 2M thay thế", "Nén áp suất cao lên bình dung dịch", "Khuấy đều dung dịch", "Dùng kẽm bột"],
     "answer": 0, "explanation": "Tăng nồng độ chất phản ứng dạng dung dịch (HCl) bằng cách pha đặc hơn (2M > 1M). Áp suất KHÔNG làm tăng nồng độ chất lỏng (nước không chịu nén). Kẽm bột là diện tích tiếp xúc."},

    # Nhóm 21-34: Các câu luyện kĩ năng tính toán và lập luận
    {"id": "mc-c5-101", "chapter": "c5", "lesson": "b25", "level": "nb", "dang": "Sự xuất hiện Sản phẩm",
     "question": "Đối với sản phẩm B trong phản ứng $A \\rightarrow B$, tốc độ phản ứng trung bình được tính bằng công thức $\\bar{v} = \\frac{\\Delta [B]}{\\Delta t}$. Biểu thức này không có dấu trừ phía trước là vì:",
     "choices": ["Nồng độ sản phẩm B TĂNG dần theo thời gian ($\\Delta [B] > 0$)", "B là chất khí", "B là chất lỏng", "Tốc độ có thể mang giá trị âm"],
     "answer": 0, "explanation": "Nồng độ chất đầu giảm $\\Rightarrow \\Delta C < 0 \Rightarrow$ cần dấu trừ để ra Tốc độ dương. Nồng độ sản phẩm tăng $\\Rightarrow \\Delta C > 0 \Rightarrow$ không cần thêm dấu trừ."},
    {"id": "mc-c5-102", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Nhiên liệu rắn lỏng khí",
     "question": "Xếp loại các nhiên liệu Than (rắn), Xăng (lỏng), Gas (khí) theo tốc độ cháy từ NHANH NHẤT đến CHẬM NHẤT (ở cùng một điều kiện tự nhiên):",
     "choices": ["Gas > Xăng > Than", "Than > Xăng > Gas", "Xăng > Gas > Than", "Bằng nhau"],
     "answer": 0, "explanation": "Chất khí hòa trộn phân tử hoàn hảo với $O_2$ (diện tích bề mặt lớn nhất, hệ đồng thể) $\\rightarrow$ tốc độ rất nhanh. Chất lỏng hóa hơi trên bề mặt. Rắn chỉ cháy ở lớp vỏ ngoài."},
    {"id": "mc-c5-103", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Đồ thị 2 chất",
     "question": "Trong phản ứng $A + 3B \\rightarrow 2C$. Trên đồ thị biểu diễn tốc độ tạo thành $C$ ($v_C$) và tốc độ tiêu thụ $B$ ($v_B$). Mối quan hệ nào đúng?",
     "choices": ["$v_C = \\frac{2}{3} v_B$", "$v_C = v_B$", "$v_C = 3 v_B$", "$v_C = 1,5 v_B$"],
     "answer": 0, "explanation": "Tỉ lệ tốc độ tương ứng hệ số cân bằng: $\\frac{v_C}{2} = \\frac{v_B}{3} \\Rightarrow v_C = \\frac{2}{3} v_B$."},
    {"id": "mc-c5-104", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "Vượt Ea",
     "question": "Khi nào thì một phân tử bị \"dội lại\" (bounce off) khi va chạm mà KHÔNG tạo ra phản ứng?",
     "choices": ["Khi động năng va chạm nhỏ hơn Năng lượng hoạt hóa ($E_a$), hoặc hướng va chạm không đúng vị trí tạo liên kết", "Khi 2 phân tử mang cùng điện tích", "Khi nhiệt độ môi trường là $0^\\circ\\text{C}$", "Khi phân tử có kích thước quá to"],
     "answer": 0, "explanation": "Thuyết va chạm (Collision Theory): Va chạm chỉ hiệu quả khi có đủ ĐỘNG NĂNG ($> E_a$) và HƯỚNG không gian thích hợp (Steric factor). Thiếu 1 trong 2 thì bật ra."},

    {"id": "mc-c5-105", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Cách dập tắt đám cháy",
     "question": "Phun bọt chữa cháy hoặc trùm chăn ướt lên đám cháy là ứng dụng của việc kiểm soát yếu tố nào để làm tốc độ cháy giảm về 0?",
     "choices": ["Ngăn cách nồng độ $O_2$ (cách li bề mặt tiếp xúc) và làm hạ nhiệt độ", "Tăng áp suất đám cháy", "Làm pha loãng xăng", "Thêm chất xúc tác âm"],
     "answer": 0, "explanation": "Bọt (Foam) nổi trên bề mặt cắt đứt tiếp xúc với Oxi không khí, đồng thời chứa nước giúp thu nhiệt mạnh (hạ nhiệt độ dưới điểm chớp cháy)."},
    {"id": "mc-c5-106", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Toán Van't Hoff 4",
     "question": "Ở nhiệt độ $35^\\circ\\text{C}$ một lượng thịt bị ôi thiu trong 4 giờ. Hệ số nhiệt độ $\\gamma = 2,5$. Nếu bảo quản ở $5^\\circ\\text{C}$ (giảm $30^\\circ$) thì lượng thịt này giữ được trong bao lâu?",
     "choices": ["62,5 giờ (khoảng 2,6 ngày)", "15,6 giờ", "1 giờ", "10 giờ"],
     "answer": 0, "explanation": "Giảm 30 độ (3 khoảng 10 độ). Tốc độ ôi thiu bị CHẬM đi $2,5^3 = 15,625$ lần. Tốc độ chậm 15,625 lần $\\Rightarrow$ Thời gian kéo dài gấp 15,625 lần. $4 \\text{ giờ} \\times 15,625 = 62,5 \\text{ giờ}$."},
    {"id": "mc-c5-107", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Suy luận phản ứng phức tạp",
     "question": "Một phản ứng tổng cộng là $2NO_2 + F_2 \\rightarrow 2NO_2F$. Thực nghiệm cho thấy biểu thức tốc độ là $v = k[NO_2][F_2]$. Điều này chứng tỏ:",
     "choices": ["Đây là một phản ứng phức tạp xảy ra qua nhiều bước, và bước chậm nhất (quyết định tốc độ) chỉ có sự va chạm của 1 phân tử $NO_2$ và 1 phân tử $F_2$", "Phương trình đã cân bằng sai", "Bậc của phản ứng là bậc 3", "Định luật tác dụng khối lượng bị sai"],
     "answer": 0, "explanation": "Biểu thức tốc độ THỰC NGHIỆM không trùng với hệ số tỉ lượng (ở đây [NO2] mũ 1, dù hệ số là 2). Suy ra phản ứng qua nhiều giai đoạn. Giai đoạn chậm nhất (Rate-determining step) có dạng $NO_2 + F_2 \\rightarrow ...$"},
    {"id": "mc-c5-108", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Pha loãng dung dịch",
     "question": "Cho $Zn$ vào dung dịch $CuSO_4$ 1M, tốc độ phản ứng là $v$. Nếu pha thêm 100ml nước cất vào 100ml dung dịch $CuSO_4$ này rồi mới thả $Zn$ vào thì tốc độ phản ứng sẽ:",
     "choices": ["Giảm đi một nửa (còn khoảng $0,5v$)", "Tăng gấp đôi", "Không đổi", "Phản ứng không xảy ra"],
     "answer": 0, "explanation": "Pha thêm thể tích nước bằng thể tích dung dịch $\\Rightarrow$ Thể tích V tăng gấp đôi $\\Rightarrow$ Nồng độ C giảm một nửa. Do nồng độ dung dịch giảm 2 lần, tốc độ phản ứng giảm theo tỉ lệ tương đương."},

    {"id": "mc-c5-109", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Sử dụng tủ sấy, quạt mát",
     "question": "Muốn hoa quả khô nhanh trong xí nghiệp, người ta dùng máy sấy hút chân không (rút bớt không khí, tạo áp suất thấp) kết hợp đun nóng. Yếu tố nào làm NƯỚC bay hơi nhanh hơn?",
     "choices": ["Nhiệt độ cao làm nước hóa hơi nhanh. Áp suất thấp làm giảm nhiệt độ sôi, hơi nước dễ thoát ra ngoài", "Áp suất thấp làm tăng nồng độ hoa quả", "Khí chân không là chất xúc tác", "Quạt gió làm tăng diện tích"],
     "answer": 0, "explanation": "Đây là quá trình vật lí, không hẳn là phản ứng hóa học, nhưng nguyên lý bay hơi: Nhiệt độ tăng $\\rightarrow$ Động năng phân tử nước tăng. Áp suất ngoài giảm $\\rightarrow$ Ít va chạm cản trở $\\rightarrow$ Dễ bốc hơi hơn."},
    {"id": "mc-c5-110", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Ý nghĩa Hằng số tốc độ 2",
     "question": "Hai phản ứng (A) và (B) ở cùng $25^\\circ\\text{C}$. Hằng số tốc độ của (A) là $k = 10^3 \\text{ s}^{-1}$, của (B) là $k = 10^{-2} \\text{ s}^{-1}$. Có thể kết luận:",
     "choices": ["Phản ứng (A) về bản chất xảy ra nhanh hơn rất rất nhiều so với (B)", "Phản ứng (A) cần nhiều chất xúc tác hơn", "Phản ứng (B) tỏa nhiều nhiệt hơn", "Phản ứng (A) là phản ứng thu nhiệt"],
     "answer": 0, "explanation": "Giá trị k càng lớn, năng lực phản ứng ở cùng điều kiện nồng độ càng mạnh. $10^3 \\gg 10^{-2}$ nên phản ứng (A) nhanh hơn hàng trăm nghìn lần."},
    {"id": "mc-c5-111", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Phản ứng 2 pha (Dị thể)",
     "question": "Đối với phản ứng phân hủy Canxi Cacbonat: $CaCO_3(s) \\rightleftharpoons CaO(s) + CO_2(g)$. Việc nghiền nhỏ bột $CaCO_3$ có ảnh hưởng gì?",
     "choices": ["Làm tăng tốc độ phản ứng thuận (phân hủy) nhờ tăng diện tích bề mặt rắn nhận nhiệt và giải phóng khí", "Không ảnh hưởng gì", "Làm cân bằng chuyển dịch theo chiều thuận", "Làm thay đổi hằng số cân bằng Kc"],
     "answer": 0, "explanation": "Nghiền nhỏ rắn = Tăng diện tích tiếp xúc với tác nhân nhiệt truyền từ ngoài vào, đồng thời dễ dàng giải phóng $CO_2$ khỏi mạng lưới hạt $\\Rightarrow$ Tốc độ phân hủy tăng mạnh."},
    {"id": "mc-c5-112", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "Đồ thị Arrhenius",
     "question": "Nếu vẽ đồ thị biểu diễn $\\ln(k)$ theo $\\frac{1}{T}$ (với T là nhiệt độ Kelvin), ta sẽ được một đường thẳng (theo PT Arrhenius). Độ dốc của đường thẳng này bằng:",
     "choices": ["$-\\frac{E_a}{R}$ (tỉ lệ nghịch với Năng lượng hoạt hóa)", "Năng lượng hoạt hóa $E_a$", "Hằng số khí R", "$\\Delta H$"],
     "answer": 0, "explanation": "Từ $k = A \\cdot e^{-E_a / RT} \Rightarrow \\ln(k) = \\ln(A) - \\frac{E_a}{R} \\cdot \\frac{1}{T}$. Phương trình đường thẳng $y = b + m \\cdot x$. Hệ số góc $m = -E_a/R$. Dùng đồ thị này để tính thực nghiệm $E_a$."},

    {"id": "mc-c5-113", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Thí nghiệm đơn giản",
     "question": "Trong phản ứng tạo gỉ sét của đinh sắt ngoài không khí ẩm. Yếu tố nào ĐÓNG VAI TRÒ CHÍNH quyết định tốc độ rỉ?",
     "choices": ["Sự có mặt của hơi nước, $O_2$ và các ion điện li (như muối trong sương biển) làm tăng tính dẫn điện $\\rightarrow$ tăng tốc độ ăn mòn điện hóa", "Sắt có độ tinh khiết cao 100%", "Nhiệt độ nóng bức của sa mạc khô", "Áp suất khí quyển cao"],
     "answer": 0, "explanation": "Ăn mòn sắt tự nhiên là ăn mòn điện hóa. Nó cần dung dịch điện li (nước ẩm chứa $CO_2$ hoặc muối) để làm môi trường dẫn truyền electron. Muối đóng vai trò như \"chất xúc tác / dung môi dẫn\" làm tốc độ rỉ cực nhanh (bơm xe máy đi biển nhanh hỏng)."},
    {"id": "mc-c5-114", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Điều kiện Tốc độ tức thời",
     "question": "Tại sao trong công nghiệp hóa chất, người ta phải liên tục khuấy trộn các bồn phản ứng lỏng?",
     "choices": ["Để duy trì nồng độ đồng đều, liên tục đưa các phân tử mới chưa phản ứng vào tiếp xúc với nhau (bù đắp phần nồng độ bị sụt giảm cục bộ)", "Để làm lạnh bồn phản ứng", "Để tạo ra chất xúc tác", "Để hòa tan bình phản ứng"],
     "answer": 0, "explanation": "Nếu không khuấy, các phân tử tại điểm tiếp xúc sẽ phản ứng hết tạo thành lớp \"cạn kiệt\" nồng độ, làm tốc độ rơi về 0 cục bộ. Khuấy tạo đối lưu, đảm bảo nồng độ $[A], [B]$ duy trì cao $\\rightarrow$ duy trì $v$ lớn."},
    {"id": "mc-c5-115", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Bài toán thực tế áp suất lốp",
     "question": "Tốc độ thoái hóa (lão hóa) của lốp xe cao su khi bơm căng để ngoài nắng cao hơn nhiều so với lốp xẹp để trong gara. Nguyên nhân kết hợp là:",
     "choices": ["Ngoài nắng có Nhiệt độ cao, tia UV (xúc tác quang) và lốp căng làm phân tử cao su bị kéo giãn dễ bị Oxi tấn công", "Vì ngoài nắng có nhiều khí trơ", "Vì lốp căng giảm diện tích tiếp xúc", "Vì lốp trong gara bị nén áp suất"],
     "answer": 0, "explanation": "Cao su lưu hóa bị đứt gãy mạch polymer do tác động của UV (năng lượng hoạt hóa), Nhiệt độ cao, và $O_3$/$O_2$. Sợi căng thì năng lượng liên kết bị kéo căng dễ đứt hơn."},
    {"id": "mc-c5-116", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Toán Tổng hợp Nồng độ $H^+$",
     "question": "Tốc độ hòa tan hạt $CaCO_3$ trong dạ dày theo phản ứng với $HCl$ (dịch vị dạ dày pH=2, nồng độ $H^+$ khoảng 0,01M). Nếu người bệnh uống thuốc kháng axit làm pH dạ dày tăng lên 3 (Nồng độ $H^+$ còn 0,001M). Tốc độ hòa tan $CaCO_3$ sẽ:",
     "choices": ["Giảm đi 10 lần (do nồng độ $H^+$ giảm 10 lần)", "Tăng 10 lần", "Không đổi", "Giảm 100 lần"],
     "answer": 0, "explanation": "pH tăng từ 2 lên 3 nghĩa là nồng độ $[H^+]$ giảm từ $10^{-2}$ xuống $10^{-3}$ (giảm 10 lần). Phương trình bậc 1 đối với $[H^+]$, do đó tốc độ hòa tan giảm 10 lần."},
    
    {"id": "mc-c5-117", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Hiểu lầm Áp suất",
     "question": "Việc nén khí $O_2$ từ 1 bar lên 200 bar trong một bình thép cường lực có làm TĂNG tốc độ của một quá trình tự nhiên nào đó bên trong bình (ví dụ rỉ sét vách bình) không?",
     "choices": ["Có, vì áp suất nén $O_2$ cực cao làm nồng độ hạt $O_2$ đập vào vách bình tăng vọt, tốc độ rỉ hoặc tự cháy tăng hàng trăm lần", "Không, vì thép không rỉ", "Không, vì áp suất không làm tăng nồng độ", "Có, vì $O_2$ hóa lỏng"],
     "answer": 0, "explanation": "Áp suất $O_2$ nguyên chất 200 bar cực kì nguy hiểm. Nồng độ quá cao khiến mọi chất hữu cơ (dầu mỡ dính trên ren van) hay sắt thép đều có thể bốc cháy tức thời nếu có ma sát (tia lửa). Tốc độ phản ứng tăng hàng vạn lần so với khí quyển."},
    {"id": "mc-c5-118", "chapter": "c5", "lesson": "b27", "level": "vd", "dang": "Ý nghĩa $e^{-Ea/RT}$",
     "question": "Trong phương trình Arrhenius, cụm đại lượng $e^{-\\frac{E_a}{RT}}$ mang ý nghĩa vật lí trực quan là gì?",
     "choices": ["Là TỈ LỆ (%) SỐ PHÂN TỬ trong hệ thống có mức động năng lớn hơn hoặc bằng Năng lượng hoạt hóa $E_a$ ở nhiệt độ T", "Là vận tốc của phân tử khí", "Là khối lượng bị mất đi do phản ứng", "Là thời gian sống của xúc tác"],
     "answer": 0, "explanation": "Đây là Thừa số Boltzmann. Ví dụ $e^{-E_a/RT} = 0,001$ nghĩa là chỉ có $0,1\\%$ số lượng va chạm có đủ năng lượng để phản ứng. Khi đun nóng (T tăng) hoặc có xúc tác ($E_a$ giảm), con số này nhảy lên $1\\%$ hoặc $10\\%$, làm tốc độ tăng vọt."},
    {"id": "mc-c5-119", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "So sánh Các Yếu tố",
     "question": "Nếu muốn phản ứng lên men làm sữa chua NHANH HƠN (nhưng chất lượng vẫn tốt), người nội trợ nên can thiệp yếu tố nào an toàn và hiệu quả nhất?",
     "choices": ["Nhiệt độ (Ủ sữa chua ở khoảng $40-45^\\circ\\text{C}$ ấm áp)", "Thêm acid mạnh $HCl$ (Xúc tác)", "Bơm khí nén vào bình sữa", "Cho sữa vào tủ đá"],
     "answer": 0, "explanation": "Men lactic hoạt động tối ưu ở $40-45^\\circ\\text{C}$. Ủ nước ấm làm tăng tốc độ lên men vừa đủ, không làm chết men như nước sôi, cũng không ngưng trệ như tủ lạnh."},
    {"id": "mc-c5-120", "chapter": "c5", "lesson": "b27", "level": "th", "dang": "Tổng kết Chương",
     "question": "Ý nghĩa to lớn nhất của việc làm chủ \"Động học hóa học\" (Tốc độ phản ứng) là:",
     "choices": ["Giúp con người KIỂM SOÁT TỐC ĐỘ theo ý muốn: Kích thích nhanh các quá trình sản xuất có lợi (phân bón, lọc dầu) và Kìm hãm các quá trình có hại (ôi thiu, rỉ sét, lão hóa)", "Chỉ để tính thời gian thí nghiệm", "Để biết phản ứng nào tỏa nhiệt", "Để cân bằng phương trình hóa học"],
     "answer": 0, "explanation": "Nhiệt động học (Chương 4) cho biết phản ứng CÓ THỂ xảy ra hay không. Động học (Chương 5) cho ta CÔNG CỤ (Nhiệt, Xúc tác, Nồng độ...) để ĐIỀU KHIỂN NÓ NHANH HAY CHẬM phục vụ đời sống."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C5 Part 2 written successfully.")
