import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 4: ĐỒ THỊ ĐỘ DỊCH CHUYỂN - THỜI GIAN ---
    # Nhóm 15: Đọc đồ thị d-t cơ bản
    {"id": "mc-c1-057", "chapter": "c1", "lesson": "b4", "level": "nb", "dang": "Đồ thị d-t",
     "question": "Trong đồ thị độ dịch chuyển - thời gian (d-t) của một vật chuyển động thẳng, độ dốc của đồ thị cho biết đại lượng nào?",
     "choices": ["Vận tốc", "Gia tốc", "Quãng đường", "Thời gian"],
     "answer": 0, "explanation": "Độ dốc (hệ số góc) của đồ thị d-t bằng tỉ số $\\Delta d / \\Delta t$, chính là định nghĩa của vận tốc."},
    {"id": "mc-c1-058", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Đồ thị d-t",
     "question": "Nếu đồ thị độ dịch chuyển - thời gian là một đường thẳng song song với trục thời gian, kết luận nào sau đây đúng?",
     "choices": ["Vật đang đứng yên", "Vật chuyển động thẳng đều", "Vật đang tăng tốc", "Vật đang chuyển động ngược chiều dương"],
     "answer": 0, "explanation": "Đường song song với trục thời gian nghĩa là độ dịch chuyển d không đổi theo thời gian. Vật không thay đổi vị trí nên vật đang đứng yên."},
    {"id": "mc-c1-059", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đồ thị d-t",
     "question": "Trên đồ thị (d-t), đường thẳng của vật A dốc hơn đường thẳng của vật B. Điều này chứng tỏ:",
     "choices": ["Vật A có tốc độ lớn hơn vật B", "Vật A xuất phát trước vật B", "Vật A có gia tốc lớn hơn vật B", "Vật A đi được quãng đường dài hơn vật B"],
     "answer": 0, "explanation": "Độ dốc của đồ thị (d-t) thể hiện độ lớn vận tốc (tốc độ). Đường càng dốc thì tốc độ càng lớn."},
    {"id": "mc-c1-060", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đồ thị d-t",
     "question": "Đồ thị d-t của một vật là một đường cong parabol (bề lõm hướng lên). Trạng thái chuyển động của vật là:",
     "choices": ["Chuyển động thẳng nhanh dần", "Chuyển động thẳng đều", "Chuyển động thẳng chậm dần", "Đứng yên"],
     "answer": 0, "explanation": "Đường cong parabol có bề lõm hướng lên nghĩa là độ dốc (vận tốc) đang tăng dần theo thời gian. Vậy vật đang chuyển động nhanh dần."},

    # Nhóm 16: Tính toán từ đồ thị d-t
    {"id": "mc-c1-061", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Tính toán đồ thị d-t",
     "question": "Một vật có đồ thị d-t là đoạn thẳng từ điểm (t=0, d=2m) đến điểm (t=4s, d=10m). Vận tốc của vật là:",
     "choices": ["2 m/s", "2,5 m/s", "10 m/s", "8 m/s"],
     "answer": 0, "explanation": "Vận tốc $v = \\frac{d_2 - d_1}{t_2 - t_1} = \\frac{10 - 2}{4 - 0} = \\frac{8}{4} = 2\\text{ m/s}$."},
    {"id": "mc-c1-062", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Tính toán đồ thị d-t",
     "question": "Đồ thị d-t của một vật là đoạn thẳng từ (0s, 10m) xuống điểm (5s, 0m). Vận tốc của vật là:",
     "choices": ["-2 m/s", "2 m/s", "10 m/s", "-10 m/s"],
     "answer": 0, "explanation": "Vận tốc $v = \\frac{d_2 - d_1}{t_2 - t_1} = \\frac{0 - 10}{5 - 0} = -2\\text{ m/s}$. Dấu âm chỉ chiều chuyển động ngược chiều dương."},
    {"id": "mc-c1-063", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đồ thị d-t",
     "question": "Một vật chuyển động có đồ thị d-t gồm 2 đoạn: đoạn 1 từ (0s, 0m) đến (2s, 10m); đoạn 2 từ (2s, 10m) đến (5s, 10m). Tốc độ trung bình trên toàn bộ khoảng thời gian 5s là:",
     "choices": ["2 m/s", "5 m/s", "0 m/s", "3,33 m/s"],
     "answer": 0, "explanation": "Quãng đường tổng cộng đi được là 10m (đi từ 0 đến 10m, sau đó đứng yên 3s). Tốc độ trung bình = Tổng quãng đường / Tổng thời gian = $10 / 5 = 2\\text{ m/s}$."},
    {"id": "mc-c1-064", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đồ thị d-t",
     "question": "Đồ thị toạ độ x-t của hai vật là hai đường thẳng cắt nhau. Giao điểm của hai đồ thị cho ta biết điều gì?",
     "choices": ["Thời điểm và vị trí hai vật gặp nhau", "Thời điểm hai vật có cùng vận tốc", "Khoảng cách lớn nhất giữa hai vật", "Vị trí hai vật cách đều gốc toạ độ"],
     "answer": 0, "explanation": "Giao điểm có cùng tung độ (toạ độ x) và hoành độ (thời gian t), nghĩa là tại thời điểm t đó, hai vật ở cùng một vị trí (chúng gặp nhau)."},

    # --- BÀI 5: GIA TỐC VÀ CHUYỂN ĐỘNG BIẾN ĐỔI ĐỀU ---
    # Nhóm 17: Gia tốc cơ bản
    {"id": "mc-c1-065", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Gia tốc",
     "question": "Gia tốc là đại lượng đặc trưng cho:",
     "choices": ["Sự thay đổi nhanh hay chậm của vận tốc", "Quãng đường đi được trong một đơn vị thời gian", "Độ dời của vật trong một đơn vị thời gian", "Sự thay đổi nhanh hay chậm của toạ độ"],
     "answer": 0, "explanation": "Định nghĩa gia tốc $\\vec{a} = \\frac{\\Delta \\vec{v}}{\\Delta t}$ đặc trưng cho tốc độ thay đổi của vận tốc."},
    {"id": "mc-c1-066", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Gia tốc",
     "question": "Trong chuyển động thẳng chậm dần đều, vectơ gia tốc và vectơ vận tốc có đặc điểm gì?",
     "choices": ["Ngược chiều nhau", "Cùng chiều nhau", "Vuông góc với nhau", "Độ lớn bằng nhau"],
     "answer": 0, "explanation": "Chậm dần $\\Rightarrow$ vận tốc giảm $\\Rightarrow \\Delta \\vec{v}$ ngược chiều với $\\vec{v}$ $\\Rightarrow \\vec{a}$ ngược chiều với $\\vec{v}$ (tích $a\\cdot v < 0$)."},
    {"id": "mc-c1-067", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Gia tốc",
     "question": "Một ô tô đang chạy với vận tốc 10 m/s thì tăng tốc đều, sau 5s đạt vận tốc 20 m/s. Gia tốc của ô tô là:",
     "choices": ["2 m/s²", "10 m/s²", "4 m/s²", "0,5 m/s²"],
     "answer": 0, "explanation": "$a = \\frac{v_2 - v_1}{t} = \\frac{20 - 10}{5} = 2\\text{ m/s}^2$."},
    {"id": "mc-c1-068", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Gia tốc",
     "question": "Một xe lửa đang chạy với vận tốc 20 m/s thì hãm phanh chậm dần đều và dừng lại sau 10s. Gia tốc của xe lửa là:",
     "choices": ["-2 m/s²", "2 m/s²", "-20 m/s²", "0 m/s²"],
     "answer": 0, "explanation": "Dừng lại nghĩa là $v_2 = 0$. $a = \\frac{0 - 20}{10} = -2\\text{ m/s}^2$."},

    # Nhóm 18: Đồ thị vận tốc - thời gian (v-t)
    {"id": "mc-c1-069", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Đồ thị v-t",
     "question": "Trong đồ thị vận tốc - thời gian (v-t), độ dốc của đồ thị cho biết đại lượng nào?",
     "choices": ["Gia tốc", "Quãng đường", "Vận tốc trung bình", "Độ dịch chuyển"],
     "answer": 0, "explanation": "Độ dốc của đồ thị v-t là $\\Delta v / \\Delta t$, chính là gia tốc $a$."},
    {"id": "mc-c1-070", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Đồ thị v-t",
     "question": "Đồ thị v-t của một vật là đường thẳng đi qua gốc toạ độ và nghiêng góc 45 độ so với trục thời gian (tỉ lệ 1:1). Gia tốc của vật là:",
     "choices": ["1 m/s²", "0 m/s²", "45 m/s²", "9,8 m/s²"],
     "answer": 0, "explanation": "Độ dốc $a = \\tan(45^\\circ) = 1$. Vậy gia tốc là 1 m/s²."},
    {"id": "mc-c1-071", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Đồ thị v-t",
     "question": "Diện tích hình phẳng giới hạn bởi đồ thị vận tốc - thời gian (v-t), trục hoành và hai đường thẳng t1, t2 có độ lớn bằng:",
     "choices": ["Quãng đường vật đi được trong khoảng thời gian đó (nếu v không đổi dấu)", "Gia tốc của vật", "Vận tốc trung bình", "Vị trí của vật lúc t2"],
     "answer": 0, "explanation": "Diện tích dưới đồ thị v-t chính là tích phân của v theo t, $\\int v dt$, cho ta độ dịch chuyển. Nếu v > 0 không đổi dấu, nó chính là quãng đường."},
    {"id": "mc-c1-072", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Đồ thị v-t",
     "question": "Đồ thị v-t của vật là đường thẳng cắt trục tung tại v=10, cắt trục hoành tại t=5. Nhận xét nào đúng?",
     "choices": ["Vật chuyển động chậm dần đều với gia tốc -2 m/s²", "Vật chuyển động nhanh dần đều với gia tốc 2 m/s²", "Vật chuyển động chậm dần đều với gia tốc 2 m/s²", "Tại t=5s vật quay đầu đi ngược lại với gia tốc thay đổi"],
     "answer": 0, "explanation": "$v_1 = 10$, tại $t=5$ thì $v_2 = 0$. $a = \\frac{0 - 10}{5} = -2\\text{ m/s}^2$. Do v giảm từ 10 về 0 nên là chuyển động chậm dần đều."},

    # Nhóm 19: Các công thức chuyển động biến đổi đều
    {"id": "mc-c1-073", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Công thức CĐ BĐĐ",
     "question": "Hệ thức độc lập với thời gian trong chuyển động thẳng biến đổi đều là:",
     "choices": ["$v^2 - v_0^2 = 2as$", "$v = v_0 + at$", "$s = v_0t + 0.5at^2$", "$v - v_0 = 2as$"],
     "answer": 0, "explanation": "Hệ thức độc lập thời gian kết nối vận tốc, gia tốc và quãng đường: $v^2 - v_0^2 = 2as$ (hoặc 2ad)."},
    {"id": "mc-c1-074", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Tính toán bằng công thức",
     "question": "Một ô tô bắt đầu chuyển động nhanh dần đều ($v_0 = 0$) với gia tốc $2\\text{ m/s}^2$. Quãng đường ô tô đi được sau 4 giây là:",
     "choices": ["16 m", "8 m", "32 m", "4 m"],
     "answer": 0, "explanation": "Dùng công thức $s = v_0t + \\frac{1}{2}at^2 = 0 + 0.5 \\cdot 2 \\cdot 4^2 = 16\\text{ m}."},
    {"id": "mc-c1-075", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Tính toán bằng công thức",
     "question": "Một vật đang chuyển động với vận tốc 5 m/s thì tăng tốc với gia tốc 1 m/s². Tính quãng đường vật đi được cho đến khi đạt vận tốc 7 m/s.",
     "choices": ["12 m", "24 m", "6 m", "10 m"],
     "answer": 0, "explanation": "Dùng $v^2 - v_0^2 = 2as \\Rightarrow 7^2 - 5^2 = 2 \\cdot 1 \\cdot s \\Rightarrow 49 - 25 = 2s \\Rightarrow 24 = 2s \\Rightarrow s = 12\\text{ m}."},
    {"id": "mc-c1-076", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tính toán bằng công thức (bẫy)",
     "question": "Một xe đang chạy với vận tốc 72 km/h thì hãm phanh, chuyển động chậm dần đều với gia tốc 2 m/s². Quãng đường xe đi được CÙNG LÚC DỪNG HẲN và SAU ĐÓ 1 giây là:",
     "choices": ["100 m", "101 m", "102 m", "98 m"],
     "answer": 0, "explanation": "Bẫy lừa! 72 km/h = 20 m/s. Xe dừng lại khi $v=0 \\Rightarrow t = 20/2 = 10s$. Quãng đường tới lúc dừng $s = v_0^2 / 2a = 20^2 / (2\\times 2) = 100\\text{ m}$. SAU KHI DỪNG HẲN (ô tô hãm phanh thì dừng luôn chứ không lùi lại), quãng đường không tăng thêm. Nên đáp án vẫn là 100m."},

    # Nhóm 20: Rơi tự do cơ bản
    {"id": "mc-c1-077", "chapter": "c1", "lesson": "b6", "level": "nb", "dang": "Rơi tự do",
     "question": "Sự rơi tự do là gì?",
     "choices": ["Sự rơi chỉ dưới tác dụng của trọng lực", "Sự rơi của vật có khối lượng rất lớn", "Sự rơi trong không khí với vận tốc đều", "Sự rơi của vật được ném từ trên xuống"],
     "answer": 0, "explanation": "Rơi tự do là sự rơi chỉ dưới tác dụng của trọng lực (bỏ qua sức cản không khí)."},
    {"id": "mc-c1-078", "chapter": "c1", "lesson": "b6", "level": "nb", "dang": "Rơi tự do",
     "question": "Gia tốc rơi tự do (g) tại một điểm trên Trái Đất có đặc điểm:",
     "choices": ["Thay đổi theo vĩ độ và độ cao", "Là một hằng số tuyệt đối $9,81\\text{ m/s}^2$ ở mọi nơi trên vũ trụ", "Chỉ phụ thuộc vào khối lượng của vật rơi", "Chỉ phụ thuộc vào hình dạng của vật rơi"],
     "answer": 0, "explanation": "g không phải hằng số tuyệt đối. Nó thay đổi theo độ cao (càng lên cao g càng giảm) và vĩ độ (lớn nhất ở cực, nhỏ nhất ở xích đạo)."},
    {"id": "mc-c1-079", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Rơi tự do",
     "question": "Đặc điểm của chuyển động rơi tự do là:",
     "choices": ["Chuyển động thẳng nhanh dần đều", "Chuyển động thẳng đều", "Chuyển động thẳng chậm dần đều", "Chuyển động tròn đều"],
     "answer": 0, "explanation": "Vật rơi từ không vận tốc đầu ($v_0=0$) dưới tác dụng của trọng lực có gia tốc $a=g$ không đổi $\\Rightarrow$ là chuyển động thẳng nhanh dần đều."},
    {"id": "mc-c1-080", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Rơi tự do",
     "question": "Một hòn đá rơi tự do không vận tốc đầu từ đỉnh tháp. Biểu thức tính quãng đường hòn đá rơi được sau thời gian t là:",
     "choices": ["$h = \\frac{1}{2}gt^2$", "$h = gt$", "$h = gt^2$", "$h = \\sqrt{2gt}$"],
     "answer": 0, "explanation": "Thay $v_0 = 0, a = g$ vào $s = v_0t + \\frac{1}{2}at^2$ ta được $h = \\frac{1}{2}gt^2$."},

    # Nhóm 21: Tính toán Rơi tự do
    {"id": "mc-c1-081", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Tính toán rơi tự do",
     "question": "Thả một vật rơi tự do từ độ cao 20m xuống đất. Lấy $g = 10\\text{ m/s}^2$. Thời gian vật rơi tới đất là:",
     "choices": ["2 s", "4 s", "$\\sqrt{2}$ s", "20 s"],
     "answer": 0, "explanation": "$h = \\frac{1}{2}gt^2 \\Rightarrow 20 = \\frac{1}{2} \\cdot 10 \\cdot t^2 \\Rightarrow 5t^2 = 20 \\Rightarrow t^2 = 4 \\Rightarrow t = 2\\text{ s}."},
    {"id": "mc-c1-082", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Tính toán rơi tự do",
     "question": "Một vật rơi tự do từ độ cao h. Lấy $g = 10\\text{ m/s}^2$. Vận tốc của vật ngay trước khi chạm đất là 30 m/s. Thời gian rơi của vật là:",
     "choices": ["3 s", "1,5 s", "9 s", "30 s"],
     "answer": 0, "explanation": "$v = gt \\Rightarrow 30 = 10t \\Rightarrow t = 3\\text{ s}."},
    {"id": "mc-c1-083", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Tính toán rơi tự do",
     "question": "Một vật rơi tự do. Quãng đường vật rơi được trong giây thứ 3 là bao nhiêu? (Lấy $g = 10\\text{ m/s}^2$)",
     "choices": ["25 m", "45 m", "5 m", "15 m"],
     "answer": 0, "explanation": "Quãng đường rơi sau 3s: $h_3 = 0.5 \\cdot 10 \\cdot 3^2 = 45\\text{ m}$. Quãng đường rơi sau 2s: $h_2 = 0.5 \\cdot 10 \\cdot 2^2 = 20\\text{ m}$. Quãng đường rơi TRONG giây thứ 3 = $h_3 - h_2 = 45 - 20 = 25\\text{ m}."},
    {"id": "mc-c1-084", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Rơi tự do (Lừa)",
     "question": "Thả hai vật rơi tự do từ cùng một độ cao, vật A có khối lượng gấp đôi vật B. Bỏ qua sức cản không khí. Nhận xét nào đúng?",
     "choices": ["Hai vật chạm đất cùng lúc", "Vật A chạm đất trước vật B", "Vật B chạm đất trước vật A", "Thời gian rơi phụ thuộc thể tích vật"],
     "answer": 0, "explanation": "Rơi tự do là sự rơi chỉ dưới tác dụng trọng lực. Gia tốc $g$ của mọi vật tại cùng 1 vị trí là như nhau, KHÔNG phụ thuộc khối lượng. Nên 2 vật chạm đất cùng lúc."},

    # Nhóm 22: Chuyển động ném ngang cơ bản
    {"id": "mc-c1-085", "chapter": "c1", "lesson": "b7", "level": "nb", "dang": "Chuyển động ném ngang",
     "question": "Trong chuyển động ném ngang, chuyển động của vật trên phương ngang (trục Ox) là chuyển động gì?",
     "choices": ["Chuyển động thẳng đều", "Chuyển động thẳng nhanh dần đều", "Chuyển động rơi tự do", "Chuyển động thẳng chậm dần đều"],
     "answer": 0, "explanation": "Trên phương ngang không có lực nào tác dụng (bỏ qua cản không khí), theo định luật 1 Newton, vật duy trì vận tốc đầu $v_0$ nên là chuyển động thẳng đều."},
    {"id": "mc-c1-086", "chapter": "c1", "lesson": "b7", "level": "nb", "dang": "Chuyển động ném ngang",
     "question": "Trong chuyển động ném ngang, chuyển động của vật trên phương thẳng đứng (trục Oy, hướng xuống) là chuyển động gì?",
     "choices": ["Sự rơi tự do", "Chuyển động thẳng đều", "Chuyển động chậm dần đều", "Chuyển động có gia tốc biến thiên"],
     "answer": 0, "explanation": "Theo phương đứng, vật chịu tác dụng duy nhất của trọng lực, và vận tốc ban đầu theo phương đứng $v_{0y} = 0$, do đó chuyển động thành phần này chính là sự rơi tự do."},
    {"id": "mc-c1-087", "chapter": "c1", "lesson": "b7", "level": "th", "dang": "Chuyển động ném ngang",
     "question": "Thời gian chạm đất của một vật ném ngang từ độ cao h với vận tốc ban đầu $v_0$ phụ thuộc vào yếu tố nào?",
     "choices": ["Chỉ phụ thuộc vào độ cao h", "Chỉ phụ thuộc vào vận tốc đầu $v_0$", "Phụ thuộc vào cả h và $v_0$", "Phụ thuộc vào khối lượng của vật"],
     "answer": 0, "explanation": "Thời gian rơi của vật ném ngang hoàn toàn do thành phần chuyển động rơi tự do theo phương đứng quyết định. $h = 0.5gt^2 \\Rightarrow t = \\sqrt{2h/g}$. Vậy $t$ chỉ phụ thuộc $h$ (và $g$), độc lập với $v_0$."},
    {"id": "mc-c1-088", "chapter": "c1", "lesson": "b7", "level": "th", "dang": "Chuyển động ném ngang",
     "question": "Tầm ném xa (L) của một vật ném ngang từ độ cao h với vận tốc $v_0$ được tính bằng công thức nào?",
     "choices": ["$L = v_0 \\sqrt{\\frac{2h}{g}}$", "$L = \\frac{v_0^2}{g}$", "$L = v_0 \\frac{2h}{g}$", "$L = h \\sqrt{\\frac{2v_0}{g}}$"],
     "answer": 0, "explanation": "Tầm xa $L = x_{\\max} = v_0 \\cdot t$. Thay $t = \\sqrt{2h/g}$ vào ta được $L = v_0 \\sqrt{\\frac{2h}{g}}$."},

    # Nhóm 23: Tính toán ném ngang
    {"id": "mc-c1-089", "chapter": "c1", "lesson": "b7", "level": "th", "dang": "Tính toán ném ngang",
     "question": "Ném ngang một hòn đá từ độ cao 5m với vận tốc ban đầu 10 m/s. Lấy $g = 10\\text{ m/s}^2$. Tầm bay xa của hòn đá là:",
     "choices": ["10 m", "5 m", "15 m", "20 m"],
     "answer": 0, "explanation": "Thời gian rơi $t = \\sqrt{2h/g} = \\sqrt{2\\cdot 5/10} = 1\\text{s}$. Tầm xa $L = v_0t = 10 \\cdot 1 = 10\\text{ m}."},
    {"id": "mc-c1-090", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Tính toán ném ngang",
     "question": "Một viên đạn được bắn ngang từ một khẩu súng ở độ cao 1,25m. Viên đạn chạm đất cách điểm bắn 200m (theo phương ngang). Tính vận tốc bắn viên đạn ($g=10\\text{ m/s}^2$).",
     "choices": ["400 m/s", "100 m/s", "200 m/s", "50 m/s"],
     "answer": 0, "explanation": "Thời gian rơi $t = \\sqrt{2 \\cdot 1,25 / 10} = \\sqrt{0,25} = 0,5\\text{s}$. Tầm xa $L = 200\\text{m} = v_0 \\cdot 0,5 \\Rightarrow v_0 = 400\\text{ m/s}."},
    {"id": "mc-c1-091", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Vận tốc chạm đất ném ngang",
     "question": "Ném một vật theo phương ngang với vận tốc $v_0 = 15\\text{ m/s}$ từ một độ cao h. Khi chạm đất, vectơ vận tốc của vật hợp với phương ngang một góc 45 độ. Vận tốc chạm đất của vật là:",
     "choices": ["$15\\sqrt{2}\\text{ m/s}$", "$15\\text{ m/s}$", "$30\\text{ m/s}$", "$30\\sqrt{2}\\text{ m/s}$"],
     "answer": 0, "explanation": "Góc 45 độ chứng tỏ thành phần ngang $v_x$ và thành phần đứng $v_y$ bằng nhau. $v_x = v_0 = 15\\text{ m/s} \\Rightarrow v_y = 15\\text{ m/s}$. Vận tốc tổng hợp $v = \\sqrt{v_x^2 + v_y^2} = \\sqrt{15^2 + 15^2} = 15\\sqrt{2}\\text{ m/s}."},
    {"id": "mc-c1-092", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "So sánh 2 vật ném ngang",
     "question": "Từ cùng một độ cao, vật A được ném ngang với vận tốc $v_A$, vật B được ném ngang với vận tốc $v_B = 2v_A$. Tỉ số thời gian rơi $t_A / t_B$ và tỉ số tầm xa $L_A / L_B$ lần lượt là:",
     "choices": ["1 và 1/2", "1/2 và 1", "2 và 2", "1 và 2"],
     "answer": 0, "explanation": "Thời gian rơi chỉ phụ thuộc độ cao $h$, do cùng $h$ nên $t_A = t_B \\Rightarrow t_A/t_B = 1$. Tầm xa $L = v_0t \\Rightarrow L_A / L_B = v_{0A} / v_{0B} = 1/2$."},

    # Nhóm 24: Tính tương đối của chuyển động
    {"id": "mc-c1-093", "chapter": "c1", "lesson": "b8", "level": "nb", "dang": "Tính tương đối",
     "question": "Tính tương đối của chuyển động có nghĩa là:",
     "choices": ["Quỹ đạo và vận tốc của một vật thay đổi tùy thuộc vào hệ quy chiếu được chọn", "Quỹ đạo luôn thẳng nhưng vận tốc thay đổi theo người quan sát", "Vận tốc đứng yên tuyệt đối chỉ tồn tại ở Trái Đất", "Gia tốc của một vật luôn khác nhau trong mọi hệ quy chiếu"],
     "answer": 0, "explanation": "Tính tương đối của chuyển động thể hiện ở việc: Vận tốc và quỹ đạo có tính tương đối, chúng có thể khác nhau trong các hệ quy chiếu khác nhau."},
    {"id": "mc-c1-094", "chapter": "c1", "lesson": "b8", "level": "th", "dang": "Tính tương đối",
     "question": "Một người ngồi trên một toa tàu đang chạy thẳng đều. Đối với người đó, một giọt nước rơi từ trần toa tàu xuống sàn sẽ có quỹ đạo là:",
     "choices": ["Một đường thẳng đứng", "Một đường parabol", "Một đường xiên góc", "Một đường cong bất kì"],
     "answer": 0, "explanation": "Đối với hệ quy chiếu gắn với toa tàu (đứng yên đối với tàu), giọt nước có vận tốc ngang bằng 0, chỉ rơi dưới tác dụng của trọng lực nên quỹ đạo là đường thẳng đứng. (Người đứng trên sân ga sẽ thấy là parabol)."},
    {"id": "mc-c1-095", "chapter": "c1", "lesson": "b8", "level": "th", "dang": "Tính tương đối",
     "question": "Hệ quy chiếu bao gồm những yếu tố nào?",
     "choices": ["Vật làm mốc, hệ toạ độ, mốc thời gian và đồng hồ", "Vật làm mốc và trục toạ độ Ox", "Không gian 3 chiều và thời gian", "Trái Đất và Mặt Trời"],
     "answer": 0, "explanation": "Một hệ quy chiếu hoàn chỉnh gồm: Vật làm mốc, hệ toạ độ (gắn với vật mốc) để xác định vị trí; mốc thời gian và đồng hồ để xác định thời gian."},
    {"id": "mc-c1-096", "chapter": "c1", "lesson": "b8", "level": "vd", "dang": "Tính tương đối",
     "question": "Hành khách A ngồi trên tàu Hỏa 1, nhìn qua cửa sổ thấy tàu Hỏa 2 bên cạnh đang chuyển động lùi. Kết luận nào sau đây CHẮC CHẮN đúng?",
     "choices": ["Tàu 1 có vận tốc hướng tới trước lớn hơn vận tốc hướng tới trước của tàu 2", "Tàu 2 đang chạy lùi so với mặt đất", "Tàu 1 đang chạy tới còn tàu 2 đứng yên", "Tàu 1 đang đứng yên còn tàu 2 chạy lùi"],
     "answer": 0, "explanation": "Vận tốc tương đối $\\vec{v}_{21} = \\vec{v}_{2đ} - \\vec{v}_{1đ}$. Nếu hành khách A thấy tàu 2 lùi (tức $\\vec{v}_{21}$ ngược chiều dương), thì $v_{2đ} < v_{1đ}$. Nghĩa là tàu 1 chạy nhanh hơn tàu 2 về phía trước. Các phương án khác chỉ là 1 trường hợp cụ thể, chưa chắc đúng."},

    # Nhóm 25: Cộng vận tốc (cùng chiều, ngược chiều)
    {"id": "mc-c1-097", "chapter": "c1", "lesson": "b8", "level": "nb", "dang": "Công thức cộng vận tốc",
     "question": "Cho vật (1) chuyển động so với vật (2), vật (2) chuyển động so với vật (3). Công thức cộng vận tốc nào sau đây đúng?",
     "choices": ["$\\vec{v}_{13} = \\vec{v}_{12} + \\vec{v}_{23}$", "$\\vec{v}_{13} = \\vec{v}_{12} - \\vec{v}_{23}$", "$\\vec{v}_{13} = \\vec{v}_{21} + \\vec{v}_{32}$", "$v_{13} = v_{12} + v_{23}$"],
     "answer": 0, "explanation": "Công thức cộng vận tốc theo vectơ: Vận tốc tuyệt đối = Vận tốc tương đối + Vận tốc kéo theo $\\Rightarrow \\vec{v}_{13} = \\vec{v}_{12} + \\vec{v}_{23}$."},
    {"id": "mc-c1-098", "chapter": "c1", "lesson": "b8", "level": "th", "dang": "Cộng vận tốc",
     "question": "Một thang cuốn đi lên với vận tốc 1 m/s. Một người bước lên các bậc thang cuốn với vận tốc 0,5 m/s so với thang. Vận tốc của người đó so với mặt đất là:",
     "choices": ["1,5 m/s", "0,5 m/s", "1 m/s", "0,75 m/s"],
     "answer": 0, "explanation": "Cùng chiều: $v_{13} = v_{12} + v_{23} = 0,5 + 1 = 1,5\\text{ m/s}$."},
    {"id": "mc-c1-099", "chapter": "c1", "lesson": "b8", "level": "th", "dang": "Cộng vận tốc",
     "question": "Một tàu hỏa dài 100m chạy thẳng đều với vận tốc 15 m/s. Một người đi bộ ngược chiều tàu trên trần tàu với vận tốc 1 m/s so với tàu. Vận tốc của người đó so với mặt đất là:",
     "choices": ["14 m/s", "16 m/s", "1 m/s", "15 m/s"],
     "answer": 0, "explanation": "Ngược chiều: Chọn chiều dương là chiều tàu chạy. $v_{t/d} = 15$; $v_{ng/t} = -1$. Vận tốc tuyệt đối $v_{ng/d} = v_{ng/t} + v_{t/d} = -1 + 15 = 14\\text{ m/s}$."},
    {"id": "mc-c1-100", "chapter": "c1", "lesson": "b8", "level": "vd", "dang": "Cộng vận tốc",
     "question": "Một chiếc thuyền chạy ngược dòng nước, vận tốc của thuyền so với nước là 10 km/h, vận tốc của dòng nước so với bờ là 3 km/h. Vận tốc của thuyền so với bờ là:",
     "choices": ["7 km/h hướng ngược chiều nước chảy", "13 km/h hướng ngược chiều nước chảy", "7 km/h hướng xuôi dòng", "10 km/h hướng ngược chiều nước chảy"],
     "answer": 0, "explanation": "Thuyền ngược dòng, vận tốc nước đẩy ngược lại. $v_{th/b} = 10 - 3 = 7\\text{ km/h}$. Thuyền khỏe hơn nước nên vẫn đi ngược dòng."},

    # Nhóm 26: Cộng vận tốc vuông góc
    {"id": "mc-c1-101", "chapter": "c1", "lesson": "b8", "level": "th", "dang": "Cộng vận tốc vuông góc",
     "question": "Một chiếc canô chạy từ bờ bên này sang bờ bên kia của một con sông, luôn hướng mũi canô vuông góc với bờ. Vận tốc canô so với nước là 4 m/s. Nước chảy với vận tốc 3 m/s. Vận tốc của canô so với bờ sông là:",
     "choices": ["5 m/s", "7 m/s", "1 m/s", "3,5 m/s"],
     "answer": 0, "explanation": "Vận tốc tương đối (canô so nước) vuông góc với vận tốc kéo theo (nước so bờ). Vận tốc tuyệt đối $v = \\sqrt{4^2 + 3^2} = 5\\text{ m/s}$."},
    {"id": "mc-c1-102", "chapter": "c1", "lesson": "b8", "level": "vd", "dang": "Cộng vận tốc vuông góc",
     "question": "Trong bài toán canô sang sông (canô hướng vuông góc bờ, v_canô=4m/s, v_nước=3m/s), nếu bề rộng con sông là 40m, thời gian canô sang đến bờ bên kia là:",
     "choices": ["10 s", "8 s", "13,3 s", "12 s"],
     "answer": 0, "explanation": "Thời gian sang sông chỉ phụ thuộc vào thành phần vận tốc phương vuông góc bờ (v=4 m/s) và bề rộng sông. $t = d/v_y = 40/4 = 10\\text{ s}$. (Vận tốc nước không giúp ích cũng không cản trở việc qua sông)."},
    {"id": "mc-c1-103", "chapter": "c1", "lesson": "b8", "level": "vd", "dang": "Cộng vận tốc vuông góc",
     "question": "Cũng với canô trên, khoảng cách bị nước cuốn trôi dọc theo bờ sông khi sang đến đích là:",
     "choices": ["30 m", "40 m", "50 m", "10 m"],
     "answer": 0, "explanation": "Thời gian trôi $t = 10\\text{s}$. Vận tốc trôi dọc bờ chính là vận tốc dòng nước $v_x = 3\\text{ m/s}$. Quãng đường trôi $x = v_x \\cdot t = 3 \\cdot 10 = 30\\text{ m}."},
    {"id": "mc-c1-104", "chapter": "c1", "lesson": "b8", "level": "vd", "dang": "Cộng vận tốc góc bất kì",
     "question": "Trời không gió, những giọt mưa rơi thẳng đứng với vận tốc 5 m/s. Một người lái xe máy chạy với tốc độ 18 km/h. Người này sẽ thấy các giọt mưa rơi hợp với phương thẳng đứng một góc bao nhiêu?",
     "choices": ["45 độ", "30 độ", "60 độ", "0 độ"],
     "answer": 0, "explanation": "Vận tốc xe $v_x = 18\\text{ km/h} = 5\\text{ m/s}$. Vận tốc mưa so với đất $\\vec{v}_{mđ}$ hướng xuống (5 m/s). Vận tốc mưa so với xe $\\vec{v}_{mx} = \\vec{v}_{mđ} - \\vec{v}_{xđ}$. Hợp lực tạo tam giác vuông cân có hai cạnh góc vuông bằng 5 $\\Rightarrow$ góc là 45 độ."},

    # Nhóm 27: Chuyển động ném xiên (Khái niệm cơ bản)
    {"id": "mc-c1-105", "chapter": "c1", "lesson": "b9", "level": "nb", "dang": "Ném xiên",
     "question": "Quỹ đạo của một vật ném xiên trong trường trọng lực (bỏ qua lực cản không khí) có hình dạng gì?",
     "choices": ["Parabol", "Hyperbol", "Đường thẳng xiên", "Cung tròn"],
     "answer": 0, "explanation": "Phương trình quỹ đạo ném xiên là phương trình bậc 2 có dạng $y = ax^2 + bx$, biểu diễn một parabol."},
    {"id": "mc-c1-106", "chapter": "c1", "lesson": "b9", "level": "th", "dang": "Ném xiên",
     "question": "Trong chuyển động ném xiên, vận tốc tại điểm cao nhất của quỹ đạo có đặc điểm gì?",
     "choices": ["Chỉ còn thành phần phương ngang $v_x$, thành phần thẳng đứng $v_y = 0$", "Bằng 0 hoàn toàn", "Hướng thẳng đứng xuống dưới", "Chỉ còn thành phần phương thẳng đứng"],
     "answer": 0, "explanation": "Tại đỉnh parabol, vật đổi chiều chuyển động theo phương đứng nên $v_y = 0$. Thành phần phương ngang $v_x = v_0\\cos(\\alpha)$ vẫn giữ nguyên."},
    {"id": "mc-c1-107", "chapter": "c1", "lesson": "b9", "level": "th", "dang": "Ném xiên",
     "question": "Tầm bay xa của vật ném xiên đạt giá trị lớn nhất khi góc ném $\\alpha$ (hợp với phương ngang) bằng bao nhiêu? (bỏ qua cản không khí, ném từ mặt đất)",
     "choices": ["45 độ", "90 độ", "30 độ", "60 độ"],
     "answer": 0, "explanation": "Công thức tầm xa $L = \\frac{v_0^2 \\sin(2\\alpha)}{g}$. $L$ max khi $\\sin(2\\alpha) = 1 \\Rightarrow 2\\alpha = 90^\\circ \\Rightarrow \\alpha = 45^\\circ$."},
    {"id": "mc-c1-108", "chapter": "c1", "lesson": "b9", "level": "vd", "dang": "Ném xiên",
     "question": "Hai quả pháo được bắn lên với cùng vận tốc đầu từ mặt đất, góc bắn lần lượt là 30 độ và 60 độ. So sánh tầm bay xa của hai quả pháo?",
     "choices": ["Bằng nhau", "Quả 60 độ bay xa hơn", "Quả 30 độ bay xa hơn", "Phụ thuộc vào khối lượng của pháo"],
     "answer": 0, "explanation": "Nếu hai góc ném phụ nhau (tổng bằng $90^\\circ$) và cùng $v_0$ thì tầm xa bằng nhau, vì $\\sin(2\\cdot 30) = \\sin(60)$ và $\\sin(2\\cdot 60) = \\sin(120)$ đều bằng $\\frac{\\sqrt{3}}{2}$."},

    # Nhóm 28: Bài toán Ném xiên
    {"id": "mc-c1-109", "chapter": "c1", "lesson": "b9", "level": "vd", "dang": "Tính toán ném xiên",
     "question": "Đá một quả bóng từ mặt đất với góc 30 độ, vận tốc đầu 20 m/s. Thời gian từ lúc đá đến lúc bóng chạm đất là: (Lấy $g = 10\\text{ m/s}^2$)",
     "choices": ["2 s", "1 s", "3 s", "4 s"],
     "answer": 0, "explanation": "Thời gian chạm đất (ném từ đất) $t = \\frac{2v_0\\sin\\alpha}{g} = \\frac{2 \\cdot 20 \\cdot 0.5}{10} = 2\\text{ s}."},
    {"id": "mc-c1-110", "chapter": "c1", "lesson": "b9", "level": "vd", "dang": "Tính toán ném xiên",
     "question": "Cũng quả bóng ném xiên $v_0 = 20\\text{ m/s}$, góc 30 độ. Độ cao cực đại mà bóng đạt được là:",
     "choices": ["5 m", "10 m", "15 m", "20 m"],
     "answer": 0, "explanation": "$H_{\\max} = \\frac{(v_0\\sin\\alpha)^2}{2g} = \\frac{(20 \\cdot 0.5)^2}{2 \\cdot 10} = \\frac{10^2}{20} = \\frac{100}{20} = 5\\text{ m}."},
    {"id": "mc-c1-111", "chapter": "c1", "lesson": "b9", "level": "vd", "dang": "Tính toán ném xiên",
     "question": "Cũng quả bóng ném xiên $v_0 = 20\\text{ m/s}$, góc 30 độ. Tầm xa của quả bóng là: (Lấy $\\sqrt{3} \\approx 1,73$)",
     "choices": ["34,6 m", "17,3 m", "40 m", "20 m"],
     "answer": 0, "explanation": "$L = v_0\\cos\\alpha \\cdot t_{\\text{bay}} = 20 \\cdot \\frac{\\sqrt{3}}{2} \\cdot 2 = 20\\sqrt{3} \\approx 34,6\\text{ m}."},
    {"id": "mc-c1-112", "chapter": "c1", "lesson": "b9", "level": "vd", "dang": "Bài toán thực tế",
     "question": "Một vận động viên nhảy xa. Nếu anh ta muốn đạt thành tích tốt nhất, anh ta nên nhảy với góc cất cánh khoảng bao nhiêu so với mặt đất (bỏ qua cản không khí, xem trọng tâm ném từ đất)?",
     "choices": ["45 độ", "30 độ", "60 độ", "80 độ"],
     "answer": 0, "explanation": "Tương đương bài ném xiên, góc tối ưu để có tầm ném (nhảy) cực đại là 45 độ."},

    # Nhóm 29: Tổng hợp Động học (đồ thị v-t)
    {"id": "mc-c1-113", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tổng hợp đồ thị",
     "question": "Đồ thị v-t của thang máy gồm 3 đoạn: từ t=0 đến 2s v tăng từ 0 đến 4; từ 2s đến 8s v=4 không đổi; từ 8s đến 10s v giảm từ 4 về 0. Quãng đường thang máy đi được là:",
     "choices": ["32 m", "40 m", "24 m", "28 m"],
     "answer": 0, "explanation": "Quãng đường bằng diện tích hình thang dưới đồ thị v-t. Đáy lớn = 10, đáy bé = 8-2 = 6, chiều cao = 4. Diện tích $S = (10+6) \\cdot 4 / 2 = 32\\text{ m}."},
    {"id": "mc-c1-114", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tổng hợp đồ thị",
     "question": "Từ dữ kiện trên, gia tốc của thang máy trong 2 giây đầu tiên là:",
     "choices": ["2 m/s²", "4 m/s²", "1 m/s²", "0 m/s²"],
     "answer": 0, "explanation": "Gia tốc bằng độ dốc $\\Delta v / \\Delta t = (4-0)/(2-0) = 2\\text{ m/s}^2$."},
    {"id": "mc-c1-115", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tổng hợp phương trình",
     "question": "Phương trình chuyển động của một vật là $x = 10 - 4t + 2t^2$ (x tính bằng m, t tính bằng s). Gia tốc và vận tốc ban đầu của vật là:",
     "choices": ["$a = 4\\text{ m/s}^2; v_0 = -4\\text{ m/s}$", "$a = 2\\text{ m/s}^2; v_0 = -4\\text{ m/s}$", "$a = 2\\text{ m/s}^2; v_0 = 4\\text{ m/s}$", "$a = 4\\text{ m/s}^2; v_0 = 4\\text{ m/s}$"],
     "answer": 0, "explanation": "So sánh với pt gốc $x = x_0 + v_0t + 0.5at^2$. Suy ra $0.5a = 2 \\Rightarrow a = 4\\text{ m/s}^2$. $v_0 = -4\\text{ m/s}$."},
    {"id": "mc-c1-116", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tổng hợp",
     "question": "Hai vật A và B rơi tự do từ cùng độ cao, nhưng B rơi sau A 1 giây. Trong quá trình cả hai cùng rơi, khoảng cách giữa hai vật sẽ:",
     "choices": ["Tăng dần theo thời gian", "Không thay đổi", "Giảm dần theo thời gian", "Tăng rồi giảm"],
     "answer": 0, "explanation": "Phương trình A: $y_A = 0.5gt^2$. B: $y_B = 0.5g(t-1)^2$. Khoảng cách $\\Delta y = 0.5g(t^2 - (t-1)^2) = 0.5g(2t - 1)$. Biểu thức phụ thuộc t bậc 1 và hệ số dương, nên khoảng cách tăng đều theo thời gian."},

    # Nhóm 30: Tổng hợp Mở đầu + Sai số
    {"id": "mc-c1-117", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Tổng hợp",
     "question": "Tại sao trong nghiên cứu Vật lí, đôi khi ta phải đưa ra các mô hình thay vì khảo sát trực tiếp vật thật?",
     "choices": ["Vì vật thật quá phức tạp, có quá nhiều yếu tố phụ làm nhiễu kết quả", "Vì làm mô hình rẻ tiền hơn", "Vì Vật lí là môn khoa học trừu tượng không có thật", "Vì các vật thật luôn thay đổi tính chất"],
     "answer": 0, "explanation": "Mô hình giúp đơn giản hóa hiện tượng, loại bỏ các chi tiết thứ yếu (ví dụ bỏ qua ma sát) để tìm ra quy luật chính."},
    {"id": "mc-c1-118", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Tổng hợp",
     "question": "Ghi kết quả đo khối lượng $m = 5,023 \\pm 0,05$ kg là SAI nguyên tắc vì sao?",
     "choices": ["Sai số ở hàng phần trăm mà kết quả trung bình lại ghi đến hàng phần nghìn", "Giá trị trung bình phải luôn là số nguyên", "Sai số luôn phải có 1 chữ số khác không", "Không được ghi đơn vị kg ở ngoài dấu ngoặc"],
     "answer": 0, "explanation": "Độ chính xác (sai số) nằm ở hàng phần trăm ($0,05$), do đó giá trị trung bình chỉ được phép viết đến hàng phần trăm (tức là 5,02) chứ không được giữ lại số 3 ở hàng phần nghìn vô nghĩa."},
    {"id": "mc-c1-119", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bẫy Động học",
     "question": "Một chiếc xe đang lùi với tốc độ 5 m/s thì tài xế đạp ga để tăng tốc về phía trước với gia tốc 2 m/s². Tính từ lúc đạp ga, sau bao lâu xe dừng lại (chuyển trạng thái lùi sang tiến)?",
     "choices": ["2,5 s", "5 s", "10 s", "Xe không thể dừng lại"],
     "answer": 0, "explanation": "Vận tốc ban đầu theo chiều tiến là $v_0 = -5\\text{ m/s}$. Gia tốc $a = 2\\text{ m/s}^2$. Lúc xe dừng lại (chuyển trạng thái) là lúc $v = 0$. Áp dụng $v = v_0 + at \\Rightarrow 0 = -5 + 2t \\Rightarrow t = 2,5\\text{ s}."},
    {"id": "mc-c1-120", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Bẫy Ném ngang",
     "question": "Từ một máy bay đang bay thẳng ngang với vận tốc 200 m/s ở độ cao 2000m, người ta thả một thùng hàng. Đối với phi công trên máy bay, quỹ đạo rơi của thùng hàng là hình gì?",
     "choices": ["Một đường thẳng đứng", "Một đường parabol cong về phía trước", "Một đường parabol cong về phía sau", "Một đường xiên thẳng"],
     "answer": 0, "explanation": "Khi vừa thả, thùng hàng có cùng vận tốc ngang với máy bay. Trong hệ quy chiếu gắn với máy bay (phi công), thùng hàng không có vận tốc ngang, chỉ rơi xuống do trọng lực. Vì vậy, phi công thấy nó rơi theo đường thẳng đứng ngay bên dưới máy bay."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Part 2 written successfully.")
