import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 23: NĂNG LƯỢNG. CÔNG CƠ HỌC ---
    # Nhóm 1: Khái niệm năng lượng và công
    {"id": "mc-c3-001", "chapter": "c3", "lesson": "b23", "level": "nb", "dang": "Khái niệm Năng lượng",
     "question": "Năng lượng là đại lượng đặc trưng cho khả năng gì của vật?",
     "choices": ["Khả năng sinh công", "Khả năng truyền nhiệt", "Khả năng sinh lực", "Khả năng tăng tốc độ"],
     "answer": 0, "explanation": "Theo định nghĩa vật lí, năng lượng là đại lượng đặc trưng cho khả năng sinh công của vật."},
    {"id": "mc-c3-002", "chapter": "c3", "lesson": "b23", "level": "nb", "dang": "Công cơ học",
     "question": "Một lực sinh công khi nào?",
     "choices": ["Khi lực tác dụng lên vật và làm vật dịch chuyển (hoặc biến dạng) theo phương không vuông góc với lực", "Khi lực tác dụng lên vật nhưng vật đứng yên", "Khi lực tác dụng lên vật luôn vuông góc với phương dịch chuyển", "Khi lực tác dụng rất lớn"],
     "answer": 0, "explanation": "Công cơ học $A = F \\cdot s \\cdot \\cos\\alpha$. Để $A \\ne 0$ thì $s \\ne 0$ (vật dịch chuyển) và $\\alpha \\ne 90^\\circ$ (phương dịch chuyển không vuông góc với lực)."},
    {"id": "mc-c3-003", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Trường hợp không sinh công",
     "question": "Trường hợp nào sau đây lực KHÔNG sinh công?",
     "choices": ["Trọng lực tác dụng lên vệ tinh đang bay tròn đều quanh Trái Đất", "Lực kéo của trâu làm cày di chuyển trên ruộng", "Trọng lực tác dụng lên quả táo đang rơi tự do", "Lực ma sát tác dụng lên ô tô đang hãm phanh"],
     "answer": 0, "explanation": "Trong chuyển động tròn đều, trọng lực (đóng vai trò lực hướng tâm) luôn vuông góc với vectơ vận tốc (phương dịch chuyển) tại mọi thời điểm, nên $\\cos 90^\\circ = 0$, lực không sinh công."},
    {"id": "mc-c3-004", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Công cản",
     "question": "Khi góc $\\alpha$ hợp bởi vectơ lực và vectơ độ dịch chuyển thỏa mãn $90^\\circ < \\alpha \\le 180^\\circ$ thì:",
     "choices": ["Công của lực có giá trị âm, lực là lực cản", "Công của lực có giá trị dương, lực là lực phát động", "Lực không sinh công", "Công của lực luôn bằng 0"],
     "answer": 0, "explanation": "Với $\\alpha > 90^\\circ$, $\\cos\\alpha < 0 \\Rightarrow A < 0$. Công âm gọi là công cản, tức là lực có tác dụng cản trở chuyển động."},

    # Nhóm 2: Công thức tính công
    {"id": "mc-c3-005", "chapter": "c3", "lesson": "b23", "level": "nb", "dang": "Công thức Công",
     "question": "Công thức tính công của một lực không đổi $\\vec{F}$ làm vật dịch chuyển một đoạn độ dời $\\vec{s}$ là:",
     "choices": ["$A = F \\cdot s \\cdot \\cos\\alpha$", "$A = F \\cdot s \\cdot \\sin\\alpha$", "$A = F + s$", "$A = F / s$"],
     "answer": 0, "explanation": "Công bằng tích vô hướng của vectơ lực và vectơ độ dời: $A = \\vec{F} \\cdot \\vec{s} = F s \\cos\\alpha$ (với $\\alpha$ là góc giữa $\\vec{F}$ và $\\vec{s}$)."},
    {"id": "mc-c3-006", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Đơn vị",
     "question": "1 Joule (J) bằng:",
     "choices": ["1 N.m", "1 kg.m/s", "1 W/s", "1 N/m"],
     "answer": 0, "explanation": "Đơn vị của công là Joule (J). $1\\text{ J} = 1\\text{ N} \\cdot 1\\text{ m} = 1\\text{ N.m}$."},
    {"id": "mc-c3-007", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Tính Công",
     "question": "Người ta kéo một cái thùng gỗ nặng trượt trên sàn ngang bằng một sợi dây hợp với phương ngang một góc $60^\\circ$. Lực kéo dây là 200 N. Công của lực kéo khi thùng trượt được 10m là:",
     "choices": ["1000 J", "2000 J", "1732 J", "0 J"],
     "answer": 0, "explanation": "$A = F \\cdot s \\cdot \\cos\\alpha = 200 \\cdot 10 \\cdot \\cos(60^\\circ) = 2000 \\cdot 0.5 = 1000\\text{ J}."},
    {"id": "mc-c3-008", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Công cản (ma sát)",
     "question": "Một ô tô chạy trên đường ngang được quãng đường 50m. Biết lực ma sát giữa đường và xe không đổi bằng 500N. Công của lực ma sát là:",
     "choices": ["-25000 J", "25000 J", "0 J", "-10 J"],
     "answer": 0, "explanation": "Lực ma sát luôn ngược chiều chuyển động nên $\\alpha = 180^\\circ$. $A_{ms} = F_{ms} \\cdot s \\cdot \\cos(180^\\circ) = 500 \\cdot 50 \\cdot (-1) = -25000\\text{ J}."},

    # Nhóm 3: Công của Trọng lực
    {"id": "mc-c3-009", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Công của Trọng lực",
     "question": "Một vật nặng 2kg rơi tự do từ độ cao 5m xuống đất ($g=10\\text{ m/s}^2$). Công của trọng lực là:",
     "choices": ["100 J", "-100 J", "0 J", "10 J"],
     "answer": 0, "explanation": "Vật rơi xuống nên trọng lực cùng chiều dịch chuyển ($\\alpha = 0^\\circ$). $A = P \\cdot h \\cdot \\cos(0^\\circ) = (mg) \\cdot h = 2 \\cdot 10 \\cdot 5 = 100\\text{ J}."},
    {"id": "mc-c3-010", "chapter": "c3", "lesson": "b23", "level": "th", "dang": "Công của Trọng lực",
     "question": "Một cần cẩu nâng một khối bê tông 1 tấn (1000kg) lên cao 4m. Công của TRỌNG LỰC tác dụng lên khối bê tông là: ($g=10$)",
     "choices": ["-40000 J", "40000 J", "4000 J", "0 J"],
     "answer": 0, "explanation": "Vật đi lên trong khi trọng lực hướng xuống ($\\alpha = 180^\\circ$). $A_P = -P \\cdot h = -(1000 \\cdot 10) \\cdot 4 = -40000\\text{ J}$. (Công cản)."},
    {"id": "mc-c3-011", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Tính chất công trọng lực",
     "question": "Công của trọng lực có đặc điểm gì đặc biệt so với công của lực ma sát?",
     "choices": ["Chỉ phụ thuộc vào độ cao của điểm đầu và điểm cuối, không phụ thuộc vào hình dạng đường đi", "Phụ thuộc vào quãng đường đi được", "Luôn mang dấu âm", "Luôn bằng không"],
     "answer": 0, "explanation": "Trọng lực là một \"Lực thế\" (conservative force). Công của nó bằng $mg(h_1 - h_2)$ độc lập với quỹ đạo, chỉ phụ thuộc tọa độ điểm đầu và cuối."},
    {"id": "mc-c3-012", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Tính công trọng lực mặt nghiêng",
     "question": "Một vật khối lượng $m=5\\text{kg}$ trượt từ đỉnh dốc nghiêng dài 10m cao 6m xuống chân dốc. Công của trọng lực trong quá trình này là: ($g=10$)",
     "choices": ["300 J", "500 J", "400 J", "0 J"],
     "answer": 0, "explanation": "Do công trọng lực chỉ phụ thuộc chênh lệch độ cao $h=6\\text{m}$, bỏ qua hình dạng dốc. $A_P = P \\cdot h_{\\text{chênh}} = mg \\cdot h = 5 \\cdot 10 \\cdot 6 = 300\\text{ J}."},

    # Nhóm 4, 5: Công suất
    {"id": "mc-c3-013", "chapter": "c3", "lesson": "b24", "level": "nb", "dang": "Khái niệm Công suất",
     "question": "Công suất là đại lượng đặc trưng cho:",
     "choices": ["Tốc độ thực hiện công nhanh hay chậm của người hay máy", "Khả năng sinh công nhiều hay ít", "Thời gian làm việc của máy", "Lực tác dụng của máy"],
     "answer": 0, "explanation": "Công suất $P = A / t$, biểu thị lượng công thực hiện được trong 1 đơn vị thời gian (tốc độ sinh công)."},
    {"id": "mc-c3-014", "chapter": "c3", "lesson": "b24", "level": "nb", "dang": "Đơn vị Công suất",
     "question": "Đơn vị của công suất là Watt (W). 1 W tương đương với:",
     "choices": ["1 J/s", "1 N.m", "1 kg.m/s", "1 J.s"],
     "answer": 0, "explanation": "Do $P = A/t$ (A đo bằng Joule, t đo bằng giây), 1 W = 1 J/s."},
    {"id": "mc-c3-015", "chapter": "c3", "lesson": "b24", "level": "th", "dang": "Tính Công suất",
     "question": "Một động cơ điện nâng một vật nặng 200kg lên độ cao 15m trong thời gian 30 giây với vận tốc không đổi ($g=10$). Công suất của động cơ bằng bao nhiêu?",
     "choices": ["1000 W", "3000 W", "100 W", "30000 W"],
     "answer": 0, "explanation": "Lực nâng (do v không đổi) bằng trọng lượng vật $F = P = 2000\\text{ N}$. Công thực hiện $A = F \\cdot h = 2000 \\cdot 15 = 30000\\text{ J}$. Công suất $\\mathcal{P} = A/t = 30000/30 = 1000\\text{ W}$."},
    {"id": "mc-c3-016", "chapter": "c3", "lesson": "b24", "level": "th", "dang": "Công suất trung bình/tức thời",
     "question": "Biểu thức nào sau đây dùng để tính công suất khi vật chuyển động đều với vận tốc v cùng hướng với lực kéo F?",
     "choices": ["$P = F \\cdot v$", "$P = F \\cdot s$", "$P = F / v$", "$P = A \\cdot t$"],
     "answer": 0, "explanation": "Do $\\mathcal{P} = A/t = (F \\cdot s \\cdot 1)/t$. Mà $s/t = v \Rightarrow \\mathcal{P} = F \\cdot v$ (nếu lực F cùng hướng v)."},

    {"id": "mc-c3-017", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Ứng dụng Công suất",
     "question": "Tại sao ô tô khi đi lên dốc cao (lực cản trọng lực lớn), tài xế phải sang số thấp (giảm tốc độ)?",
     "choices": ["Để tăng lực kéo của động cơ khi công suất tối đa không đổi", "Để động cơ nghỉ ngơi", "Để giảm hao phí xăng", "Để tăng khối lượng xe"],
     "answer": 0, "explanation": "Công suất tối đa của động cơ có giới hạn $\\mathcal{P}_{\\max}$. Vì $\\mathcal{P} = F \\cdot v$, muốn tăng lực kéo $F$ (để thắng lực cản lớn khi lên dốc) thì phải giảm vận tốc $v$ (sang số thấp)."},
    {"id": "mc-c3-018", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Tính công suất lực kéo ngang",
     "question": "Một ô tô có công suất động cơ 50 kW chạy trên đường ngang với vận tốc không đổi 72 km/h. Lực kéo của động cơ lúc này là bao nhiêu?",
     "choices": ["2500 N", "694 N", "50000 N", "7200 N"],
     "answer": 0, "explanation": "Đổi $72\\text{ km/h} = 20\\text{ m/s}$. Công suất $\\mathcal{P} = 50\\text{ kW} = 50000\\text{ W}$. Lực kéo $F = \\mathcal{P} / v = 50000 / 20 = 2500\\text{ N}."},
    {"id": "mc-c3-019", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Đổi đơn vị",
     "question": "Trong kĩ thuật, người ta thường dùng đơn vị đo năng lượng là Kilôoát giờ (kWh). 1 kWh bằng:",
     "choices": ["$3,6 \\cdot 10^6\\text{ J}$", "$1000\\text{ J}$", "$3600\\text{ J}$", "$1\\text{ J}$"],
     "answer": 0, "explanation": "$1\\text{ kW.h} = 1000\\text{ W} \\times 3600\\text{ s} = 3,6 \\times 10^6\\text{ W.s} = 3,6 \\times 10^6\\text{ J}$."},
    {"id": "mc-c3-020", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Tính thời gian bằng công suất",
     "question": "Một máy bơm nước có công suất 2 kW. Để bơm được $10\\text{ m}^3$ nước lên bể trên cao 10m (bỏ qua ma sát), máy cần thời gian ít nhất là bao lâu? (Lấy khối lượng riêng nước $1000\\text{ kg/m}^3, g=10$)",
     "choices": ["500 s", "50 s", "5 s", "100 s"],
     "answer": 0, "explanation": "Khối lượng nước $m = V\\cdot\\rho = 10 \\cdot 1000 = 10000\\text{ kg}$. Trọng lượng $P = mg = 10^5\\text{ N}$. Công cần thiết để nâng nước lên $A = P\\cdot h = 10^5 \\cdot 10 = 10^6\\text{ J}$. Thời gian $t = A / \\mathcal{P} = 10^6 / 2000 = 500\\text{ s}."},

    # Nhóm 6, 7: Động năng
    {"id": "mc-c3-021", "chapter": "c3", "lesson": "b25", "level": "nb", "dang": "Khái niệm Động năng",
     "question": "Động năng là dạng năng lượng vật có được do đâu?",
     "choices": ["Do vật chuyển động", "Do vật ở trên cao so với mặt đất", "Do vật bị biến dạng đàn hồi", "Do vật có khối lượng lớn"],
     "answer": 0, "explanation": "Động năng (Kinetic Energy) là dạng cơ năng của vật xuất hiện do nó đang chuyển động."},
    {"id": "mc-c3-022", "chapter": "c3", "lesson": "b25", "level": "nb", "dang": "Công thức Động năng",
     "question": "Biểu thức tính động năng của một vật khối lượng m, đang chuyển động với vận tốc v là:",
     "choices": ["$W_d = \\frac{1}{2}mv^2$", "$W_d = mv^2$", "$W_d = \\frac{1}{2}m^2v$", "$W_d = mgh$"],
     "answer": 0, "explanation": "Động năng được tính bằng một nửa tích khối lượng với bình phương tốc độ: $W_d = 0.5 mv^2$."},
    {"id": "mc-c3-023", "chapter": "c3", "lesson": "b25", "level": "th", "dang": "Tính chất Động năng",
     "question": "Nếu khối lượng của vật không đổi, nhưng vận tốc của vật tăng lên 3 lần thì động năng của vật sẽ:",
     "choices": ["Tăng 9 lần", "Tăng 3 lần", "Giảm 9 lần", "Tăng 6 lần"],
     "answer": 0, "explanation": "Do $W_d \\sim v^2$. Vận tốc tăng 3 thì động năng tăng $3^2 = 9$ lần."},
    {"id": "mc-c3-024", "chapter": "c3", "lesson": "b25", "level": "th", "dang": "Tính chất Động năng",
     "question": "Động năng của một vật ĐỨNG YÊN bằng bao nhiêu?",
     "choices": ["Bằng 0", "Lớn nhất", "Phụ thuộc độ cao", "Phụ thuộc khối lượng"],
     "answer": 0, "explanation": "Khi vật đứng yên $v=0 \Rightarrow W_d = 0$."},

    {"id": "mc-c3-025", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Tính Động năng",
     "question": "Một ô tô 1000 kg chạy với tốc độ 72 km/h. Động năng của ô tô là:",
     "choices": ["200000 J", "2592000 J", "100000 J", "400000 J"],
     "answer": 0, "explanation": "Đổi $v = 72\\text{ km/h} = 20\\text{ m/s}$. $W_d = \\frac{1}{2}mv^2 = 0.5 \\cdot 1000 \\cdot 20^2 = 500 \\cdot 400 = 200000\\text{ J} = 200\\text{ kJ}."},
    {"id": "mc-c3-026", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Liên hệ động lượng và động năng",
     "question": "Mối liên hệ giữa động năng $W_d$ và động lượng $p$ của một vật là:",
     "choices": ["$W_d = \\frac{p^2}{2m}$", "$W_d = pm$", "$W_d = \\frac{p}{2m}$", "$W_d = \\frac{p^2}{m}$"],
     "answer": 0, "explanation": "$p = mv \Rightarrow v = p/m$. Thay vào $W_d = 0.5 mv^2 = 0.5 m (p/m)^2 = p^2 / 2m$."},
    {"id": "mc-c3-027", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Định lí động năng",
     "question": "Nội dung của Định lí động năng là gì?",
     "choices": ["Độ biến thiên động năng của một vật bằng tổng công của các ngoại lực tác dụng lên vật đó", "Động năng của vật luôn được bảo toàn", "Động năng của vật bằng công của trọng lực", "Độ biến thiên động năng bằng lực tác dụng"],
     "answer": 0, "explanation": "Định lí (hay nguyên lí) động năng: $\\Delta W_d = W_{d2} - W_{d1} = A_{\\text{ngoại lực}}$."},
    {"id": "mc-c3-028", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Áp dụng định lí động năng",
     "question": "Một vật khối lượng 2kg đang chạy với vận tốc 4 m/s thì bị hãm phanh trượt trên đường ngang. Lực cản (ma sát) là 8N. Vật đi được thêm quãng đường bao nhiêu thì dừng lại?",
     "choices": ["2 m", "4 m", "1 m", "8 m"],
     "answer": 0, "explanation": "Động năng ban đầu $W_{d1} = 0.5 \\cdot 2 \\cdot 4^2 = 16\\text{ J}$. Động năng sau $W_{d2} = 0$. $\\Delta W_d = -16\\text{ J}$. Công của lực cản $A = -F_{ms} \\cdot s = -8s$. Ta có $-8s = -16 \Rightarrow s = 2\\text{ m}."},

    # Nhóm 8, 9, 10: Thế năng trọng trường, Thế năng đàn hồi
    {"id": "mc-c3-029", "chapter": "c3", "lesson": "b26", "level": "nb", "dang": "Khái niệm Thế năng",
     "question": "Thế năng trọng trường của một vật phụ thuộc vào:",
     "choices": ["Vị trí tương đối của vật so với Trái Đất (mốc thế năng)", "Vận tốc của vật", "Nhiệt độ của vật", "Lực cản không khí"],
     "answer": 0, "explanation": "Thế năng trọng trường là năng lượng tương tác giữa Trái Đất và vật, phụ thuộc vào vị trí (độ cao z) so với một mốc quy ước."},
    {"id": "mc-c3-030", "chapter": "c3", "lesson": "b26", "level": "nb", "dang": "Công thức Thế năng TT",
     "question": "Biểu thức tính thế năng trọng trường của một vật khối lượng m đặt ở độ cao z so với mốc thế năng là:",
     "choices": ["$W_t = mgz$", "$W_t = mgh^2$", "$W_t = \\frac{1}{2}mgz$", "$W_t = mg/z$"],
     "answer": 0, "explanation": "Công thức chuẩn $W_t = mgz$ (trong đó $z$ có thể mang giá trị âm nếu vật ở dưới mốc)."},
    {"id": "mc-c3-031", "chapter": "c3", "lesson": "b26", "level": "th", "dang": "Đặc điểm Thế năng",
     "question": "Đại lượng nào sau đây có thể nhận giá trị dương, âm hoặc bằng 0 tùy thuộc vào hệ quy chiếu (mốc)?",
     "choices": ["Thế năng trọng trường", "Động năng", "Khối lượng", "Nhiệt độ tuyệt đối (Kelvin)"],
     "answer": 0, "explanation": "Thế năng trọng trường phụ thuộc vào việc chọn mốc $z=0$. Vật ở dưới mốc thì $z < 0 \Rightarrow W_t < 0$. Động năng và Khối lượng thì luôn $\\ge 0$."},
    {"id": "mc-c3-032", "chapter": "c3", "lesson": "b26", "level": "th", "dang": "Mối quan hệ Thế năng và Công",
     "question": "Công của trọng lực thực hiện khi vật di chuyển từ vị trí 1 đến vị trí 2 bằng:",
     "choices": ["Độ giảm thế năng trọng trường ($W_{t1} - W_{t2}$)", "Độ tăng thế năng trọng trường ($W_{t2} - W_{t1}$)", "Động năng của vật", "Lực hấp dẫn"],
     "answer": 0, "explanation": "Công của lực thế (trọng lực) luôn bằng ĐỘ GIẢM thế năng. $A_{12} = W_{t1} - W_{t2} = -\\Delta W_t$."},

    {"id": "mc-c3-033", "chapter": "c3", "lesson": "b26", "level": "vd", "dang": "Tính Thế năng trọng trường",
     "question": "Một vật khối lượng 2 kg được đặt ở độ cao 5m so với mặt đất. Lấy $g=10$, mốc thế năng tại mặt đất. Thế năng của vật là:",
     "choices": ["100 J", "50 J", "20 J", "-100 J"],
     "answer": 0, "explanation": "$W_t = mgz = 2 \\cdot 10 \\cdot 5 = 100\\text{ J}."},
    {"id": "mc-c3-034", "chapter": "c3", "lesson": "b26", "level": "vd", "dang": "Tính Thế năng thay đổi mốc",
     "question": "Giả sử một quả bóng đang ở tầng 2 (cách đất 4m). Tầng 1 cách đất 4m, tầng 3 cách đất 8m. Nếu chọn mốc thế năng tại sàn tầng 3, thế năng của quả bóng nặng 1kg ($g=10$) là:",
     "choices": ["-40 J", "40 J", "0 J", "-80 J"],
     "answer": 0, "explanation": "Mốc $z=0$ ở 8m. Bóng ở 4m, tức là cách mốc -4m (dưới mốc 4m). Vậy $z = -4\\text{m}$. $W_t = 1 \\cdot 10 \\cdot (-4) = -40\\text{ J}."},
    {"id": "mc-c3-035", "chapter": "c3", "lesson": "b26", "level": "nb", "dang": "Thế năng đàn hồi",
     "question": "Thế năng đàn hồi của một lò xo bị biến dạng một đoạn $\\Delta l$ là:",
     "choices": ["$W_t = \\frac{1}{2}k(\\Delta l)^2$", "$W_t = k\\Delta l$", "$W_t = \\frac{1}{2}k\\Delta l$", "$W_t = k(\\Delta l)^2$"],
     "answer": 0, "explanation": "Công thức thế năng đàn hồi của lò xo lí tưởng là $W_{t\\text{đh}} = 0.5 k (\\Delta l)^2$."},
    {"id": "mc-c3-036", "chapter": "c3", "lesson": "b26", "level": "vd", "dang": "Tính Thế năng đàn hồi",
     "question": "Lò xo có độ cứng $k=200\\text{ N/m}$, bị nén lại 10cm. Thế năng đàn hồi của lò xo là:",
     "choices": ["1 J", "1000 J", "10 J", "0,1 J"],
     "answer": 0, "explanation": "Đổi $\\Delta l = 10\\text{cm} = 0,1\\text{m}$. $W_t = 0.5 \\cdot 200 \\cdot (0,1)^2 = 100 \\cdot 0,01 = 1\\text{ J}."},

    # Nhóm 11, 12, 13, 14, 15: Cơ năng và Định luật bảo toàn cơ năng
    {"id": "mc-c3-037", "chapter": "c3", "lesson": "b27", "level": "nb", "dang": "Khái niệm Cơ năng",
     "question": "Cơ năng của một vật là gì?",
     "choices": ["Tổng động năng và thế năng của vật", "Động lượng của vật", "Hiệu giữa động năng và thế năng", "Tích của lực và quãng đường"],
     "answer": 0, "explanation": "Cơ năng $W = W_d + W_t$."},
    {"id": "mc-c3-038", "chapter": "c3", "lesson": "b27", "level": "nb", "dang": "Bảo toàn cơ năng",
     "question": "Định luật bảo toàn cơ năng được phát biểu như thế nào?",
     "choices": ["Khi một vật chuyển động chỉ chịu tác dụng của trọng lực (hoặc lực đàn hồi), cơ năng của vật là một đại lượng bảo toàn", "Cơ năng luôn luôn được bảo toàn trong mọi trường hợp", "Trong một hệ kín, thế năng luôn được bảo toàn", "Động năng của một vật rơi tự do được bảo toàn"],
     "answer": 0, "explanation": "Cơ năng chỉ bảo toàn nếu KHÔNG có công của các lực không thế (như lực cản, ma sát, lực kéo ngoài...). Chỉ lực trọng trường hoặc lực đàn hồi tác dụng thì cơ năng mới bảo toàn."},
    {"id": "mc-c3-039", "chapter": "c3", "lesson": "b27", "level": "th", "dang": "Sự chuyển hóa năng lượng",
     "question": "Khi một vật được ném thẳng đứng lên cao (bỏ qua sức cản), trong quá trình vật đi lên thì:",
     "choices": ["Động năng giảm dần chuyển hóa thành thế năng", "Động năng và thế năng đều giảm", "Thế năng giảm dần chuyển hóa thành động năng", "Cơ năng của vật tăng dần"],
     "answer": 0, "explanation": "Vật đi lên chậm dần $\\Rightarrow$ Động năng giảm, độ cao tăng $\\Rightarrow$ Thế năng tăng. Tổng không đổi $\\Rightarrow$ Động năng đang chuyển hóa thành thế năng."},
    {"id": "mc-c3-040", "chapter": "c3", "lesson": "b27", "level": "th", "dang": "Không bảo toàn cơ năng",
     "question": "Khi nào cơ năng của vật bị biến đổi (không bảo toàn)?",
     "choices": ["Khi có lực cản, lực ma sát tác dụng sinh công", "Khi vật rơi tự do", "Khi vật ném ngang trong chân không", "Khi vật trượt không ma sát trên mặt dốc"],
     "answer": 0, "explanation": "Lực cản, ma sát sinh công làm cơ năng tiêu hao (biến thành nhiệt năng)."},

    {"id": "mc-c3-041", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Tính cơ năng",
     "question": "Thả rơi một vật khối lượng 1kg từ độ cao 10m ($g=10$). Chọn mốc thế năng tại mặt đất. Cơ năng của vật ngay lúc thả là:",
     "choices": ["100 J", "0 J", "10 J", "50 J"],
     "answer": 0, "explanation": "Lúc thả $v=0 \Rightarrow W_d = 0$. $W_t = mgz = 1 \\cdot 10 \\cdot 10 = 100\\text{ J}$. Cơ năng $W = 100 + 0 = 100\\text{ J}."},
    {"id": "mc-c3-042", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bảo toàn cơ năng (Vận tốc)",
     "question": "Thả rơi tự do một hòn đá từ độ cao 20m. Vận tốc của hòn đá ngay trước khi chạm đất là bao nhiêu? ($g=10\\text{ m/s}^2$)",
     "choices": ["20 m/s", "10 m/s", "400 m/s", "14,1 m/s"],
     "answer": 0, "explanation": "Bảo toàn cơ năng $W_{\\text{đỉnh}} = W_{\\text{đáy}} \Rightarrow mgh = \frac{1}{2}mv^2 \Rightarrow v = \\sqrt{2gh} = \\sqrt{2 \\cdot 10 \\cdot 20} = \\sqrt{400} = 20\\text{ m/s}."},
    {"id": "mc-c3-043", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bảo toàn cơ năng (Độ cao cực đại)",
     "question": "Ném một vật thẳng đứng lên cao từ mặt đất với vận tốc ban đầu 10 m/s ($g=10$). Bỏ qua cản không khí. Độ cao cực đại mà vật đạt được là:",
     "choices": ["5 m", "10 m", "2,5 m", "100 m"],
     "answer": 0, "explanation": "Tại mặt đất $W_t=0$, $W = W_d = 0.5 mv^2 = 0.5 \\cdot m \\cdot 10^2 = 50m$. Tại đỉnh $W_d=0$, $W = W_t = mgh_{\\max}$. Bằng nhau $\\Rightarrow mgh_{\\max} = 50m \Rightarrow 10h_{\\max} = 50 \Rightarrow h_{\\max} = 5\\text{ m}."},
    {"id": "mc-c3-044", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bài toán Wd = Wt",
     "question": "Một vật được thả rơi tự do từ độ cao 20m. Ở độ cao nào thì Động năng bằng Thế năng của vật?",
     "choices": ["10 m", "5 m", "15 m", "2 m"],
     "answer": 0, "explanation": "Cơ năng tại đỉnh $W = mgh = 20mg$. Tại vị trí cần tìm: $W_d = W_t$. Mà $W = W_d + W_t = 2W_t = 2mgz$. Vậy $2mgz = 20mg \Rightarrow z = 10\\text{ m}."},

    {"id": "mc-c3-045", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bài toán Wd = n Wt",
     "question": "Cũng vật rơi tự do từ 20m. Ở độ cao nào thì Động năng bằng 3 lần Thế năng?",
     "choices": ["5 m", "15 m", "10 m", "6,67 m"],
     "answer": 0, "explanation": "$W_d = 3W_t \Rightarrow W = W_d + W_t = 4W_t$. $W = 20mg = 4(mgz) \Rightarrow 4z = 20 \Rightarrow z = 5\\text{ m}."},
    {"id": "mc-c3-046", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Định lí biến thiên cơ năng",
     "question": "Định lí biến thiên cơ năng phát biểu:",
     "choices": ["Độ biến thiên cơ năng của vật bằng công của các lực không thế (như lực cản, lực ma sát) tác dụng lên vật", "Độ biến thiên cơ năng bằng công của trọng lực", "Cơ năng luôn không đổi", "Độ biến thiên cơ năng bằng độ biến thiên động lượng"],
     "answer": 0, "explanation": "$\\Delta W = A_{\\text{ms}}$. Nếu có ma sát, cơ năng giảm đi một lượng đúng bằng giá trị tuyệt đối của công ma sát (vì công ma sát âm)."},
    {"id": "mc-c3-047", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Định lí BT Cơ năng",
     "question": "Một vật 2kg trượt không vận tốc đầu từ đỉnh dốc dài 10m, cao 5m xuống chân dốc. Do có ma sát nên vận tốc tại chân dốc chỉ là 6 m/s. Công của lực ma sát là: ($g=10$)",
     "choices": ["-64 J", "-100 J", "-36 J", "64 J"],
     "answer": 0, "explanation": "Cơ năng tại đỉnh: $W_1 = mgh = 2 \\cdot 10 \\cdot 5 = 100\\text{ J}$. Cơ năng tại đáy: $W_2 = W_d = 0.5 \\cdot 2 \\cdot 6^2 = 36\\text{ J}$. Công ma sát $A_{ms} = W_2 - W_1 = 36 - 100 = -64\\text{ J}."},
    {"id": "mc-c3-048", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Định lí BT Cơ năng",
     "question": "Từ kết quả trên, tính độ lớn của lực ma sát tác dụng lên vật trên đoạn dốc dài 10m đó.",
     "choices": ["6,4 N", "10 N", "3,6 N", "64 N"],
     "answer": 0, "explanation": "Ta có $A_{ms} = -F_{ms} \\cdot s \Rightarrow -64 = -F_{ms} \\cdot 10 \Rightarrow F_{ms} = 6,4\\text{ N}."},

    {"id": "mc-c3-049", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Cơ năng con lắc đơn",
     "question": "Một con lắc đơn gồm vật nặng m treo vào dây l = 1m. Kéo lệch dây góc $60^\\circ$ so với phương thẳng đứng rồi thả nhẹ ($g=10$). Vận tốc vật nặng khi qua vị trí cân bằng là:",
     "choices": ["$\\sqrt{10}\\text{ m/s}$", "$10\\text{ m/s}$", "$3,16\\text{ m/s}$", "Cả A và C đều đúng"],
     "answer": 0, "explanation": "Độ cao ban đầu của vật so với vị trí thấp nhất (VTCB) là $h = l - l\\cos\\alpha = 1 - 1\\cdot 0.5 = 0.5\\text{ m}$. Bảo toàn cơ năng: $mgh = 0.5mv^2 \Rightarrow v = \\sqrt{2gh} = \\sqrt{2 \\cdot 10 \\cdot 0.5} = \\sqrt{10} \\approx 3,16\\text{ m/s}."},
    {"id": "mc-c3-050", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bảo toàn cơ năng đàn hồi",
     "question": "Một khẩu súng đồ chơi bắn viên đạn nhựa 10g theo phương ngang bằng cách nén lò xo (độ cứng 1000 N/m) một đoạn 5cm. Bỏ qua ma sát. Vận tốc đạn khi vừa rời nòng là:",
     "choices": ["$15,8\\text{ m/s}$", "$50\\text{ m/s}$", "$5\\text{ m/s}$", "$25\\text{ m/s}$"],
     "answer": 0, "explanation": "Thế năng đàn hồi ban đầu hoàn toàn chuyển hóa thành động năng viên đạn. $0.5 k (\\Delta l)^2 = 0.5 m v^2 \Rightarrow 1000 \\cdot (0,05)^2 = 0,01 \\cdot v^2 \Rightarrow 1000 \\cdot 0,0025 = 0,01 \\cdot v^2 \Rightarrow 2,5 = 0,01v^2 \Rightarrow v^2 = 250 \Rightarrow v = \\sqrt{250} \\approx 15,8\\text{ m/s}."},
    {"id": "mc-c3-051", "chapter": "c3", "lesson": "b27", "level": "th", "dang": "Bảo toàn cơ năng",
     "question": "Một quả bóng bàn rơi xuống mặt sàn cứng và nảy lên, nhưng không bao giờ nảy đạt được độ cao ban đầu lúc thả. Lí do là:",
     "choices": ["Một phần cơ năng đã chuyển hóa thành nhiệt và âm thanh trong quá trình va chạm", "Lực hấp dẫn tăng lên khi nó chạm sàn", "Động năng của nó bị mất hoàn toàn vĩnh viễn", "Định luật bảo toàn cơ năng không áp dụng cho quả bóng"],
     "answer": 0, "explanation": "Va chạm thực tế không đàn hồi tuyệt đối, sinh ra nhiệt, làm biến dạng bóng và âm thanh (công của lực không thế). Vì vậy cơ năng bị suy hao."},
    {"id": "mc-c3-052", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Tổng hợp Năng lượng",
     "question": "Hai vật có khối lượng $m_1 = 2m_2$. Vật 1 chuyển động với vận tốc $v$, vật 2 chuyển động với vận tốc $2v$. So sánh động năng của chúng?",
     "choices": ["$W_{d2} = 2 W_{d1}$", "$W_{d1} = 2 W_{d2}$", "$W_{d1} = W_{d2}$", "$W_{d2} = 4 W_{d1}$"],
     "answer": 0, "explanation": "$W_{d1} = 0.5 (2m) v^2 = mv^2$. $W_{d2} = 0.5 m (2v)^2 = 0.5 m \\cdot 4v^2 = 2mv^2$. Vậy $W_{d2} = 2 W_{d1}$."},

    {"id": "mc-c3-053", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Hiệu suất",
     "question": "Hiệu suất H của một động cơ được định nghĩa như thế nào?",
     "choices": ["Tỉ số giữa công có ích và công toàn phần", "Tỉ số giữa công hao phí và công toàn phần", "Tỉ số giữa công toàn phần và công có ích", "Tổng công có ích và hao phí"],
     "answer": 0, "explanation": "$H = (A_{\\text{có ích}} / A_{\\text{toàn phần}}) \\times 100\\%$. Đánh giá mức độ chuyển hóa năng lượng hữu ích của máy."},
    {"id": "mc-c3-054", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Tính Hiệu suất",
     "question": "Một động cơ điện tiêu thụ năng lượng 5000 J để nâng vật nặng sinh công có ích là 4000 J. Hiệu suất của động cơ là:",
     "choices": ["80%", "20%", "125%", "40%"],
     "answer": 0, "explanation": "$H = 4000 / 5000 = 0,8 = 80\\%$."},
    {"id": "mc-c3-055", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Tính năng lượng tiêu thụ",
     "question": "Động cơ của một xe máy có hiệu suất 25%. Biết xe sinh ra công suất cơ học (hữu ích) là 2 kW. Công suất tiêu thụ (nhiên liệu) của động cơ là:",
     "choices": ["8 kW", "0,5 kW", "2 kW", "4 kW"],
     "answer": 0, "explanation": "$H = P_{\\text{có ích}} / P_{\\text{tiêu thụ}} \Rightarrow 0,25 = 2 / P_{tp} \Rightarrow P_{tp} = 2 / 0,25 = 8\\text{ kW}."},
    {"id": "mc-c3-056", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bẫy cơ năng",
     "question": "Trong con lắc đơn dao động, nếu ma sát không đáng kể, đại lượng nào sau đây đạt cực đại khi vật đi qua vị trí cân bằng?",
     "choices": ["Động năng", "Thế năng", "Cơ năng", "Gia tốc hướng tâm"],
     "answer": 0, "explanation": "Tại VTCB, $h=0$ (thế năng cực tiểu = 0). Cơ năng bảo toàn nên Động năng phải bù lại đạt cực đại (vận tốc lớn nhất). Mẹo: Cơ năng là hằng số, không cực đại cục bộ, nên đáp án C sai."},
    {"id": "mc-c3-057", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Ném ngang (Năng lượng)",
     "question": "Một hòn đá được ném ngang từ độ cao 5m với vận tốc ban đầu 10m/s ($g=10, m=1\\text{kg}$). Bỏ qua cản. Dùng định luật bảo toàn cơ năng, vận tốc chạm đất là:",
     "choices": ["$14,1\\text{ m/s}$", "$10\\text{ m/s}$", "$20\\text{ m/s}$", "$15\\text{ m/s}$"],
     "answer": 0, "explanation": "Cơ năng lúc ném $W_1 = W_{t1} + W_{d1} = mgh + 0.5mv_0^2 = 1\\cdot 10\\cdot 5 + 0.5\\cdot 1\\cdot 100 = 50 + 50 = 100\\text{ J}$. Cơ năng lúc chạm đất $W_2 = W_{d2} = 0.5mv_2^2$. Do bảo toàn $0.5\\cdot 1\\cdot v_2^2 = 100 \Rightarrow v_2^2 = 200 \Rightarrow v_2 = \\sqrt{200} \\approx 14,1\\text{ m/s}."},
    {"id": "mc-c3-058", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Tổng hợp năng lượng",
     "question": "Để đưa một vật 50kg lên cao 2m, người công nhân dùng một mặt phẳng nghiêng dài 10m. Lực kéo của người đó là 150N. Công hao phí (do ma sát) của mặt phẳng nghiêng là:",
     "choices": ["500 J", "1500 J", "1000 J", "2000 J"],
     "answer": 0, "explanation": "Công toàn phần người sinh ra $A_{tp} = F \\cdot s = 150 \\cdot 10 = 1500\\text{ J}$. Công có ích (chỉ là nâng lên 2m thẳng đứng): $A_{ci} = P \\cdot h = 500 \\cdot 2 = 1000\\text{ J}$. Công hao phí = Toàn phần - Có ích = $1500 - 1000 = 500\\text{ J}."},
    {"id": "mc-c3-059", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Công do lò xo",
     "question": "Công cần thiết để kéo giãn lò xo (k = 100 N/m) từ trạng thái tự nhiên ra thêm 10cm là bao nhiêu?",
     "choices": ["0,5 J", "5 J", "1 J", "10 J"],
     "answer": 0, "explanation": "Công ngoại lực thực hiện đúng bằng sự thay đổi thế năng đàn hồi (từ 0 lên): $A = \\Delta W_t = 0.5 k (\\Delta l)^2 = 0.5 \\cdot 100 \\cdot (0.1)^2 = 50 \\cdot 0.01 = 0.5\\text{ J}."},
    {"id": "mc-c3-060", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Đồ thị công",
     "question": "Diện tích hình giới hạn bởi đồ thị lực kéo $F$ theo li độ $x$ (trục ngang) biểu diễn đại lượng nào?",
     "choices": ["Công của lực", "Công suất", "Động lượng", "Xung lượng"],
     "answer": 0, "explanation": "Vì công $A = F \\cdot s$, diện tích dưới đồ thị F-x chính là tích phân của lực theo quãng đường $\\int F dx$, tức là Công của lực."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C3 Part 1 written successfully.")
