import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 4 HÓA HỌC 10: NĂNG LƯỢNG HÓA HỌC ---
    # Nhóm 1, 2, 3: Phản ứng tỏa nhiệt - thu nhiệt
    {"id": "mc-c4-001", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Khái niệm tỏa thu",
     "question": "Phản ứng tỏa nhiệt là phản ứng có đặc điểm gì?",
     "choices": ["Giải phóng năng lượng ra môi trường dưới dạng nhiệt", "Hấp thụ năng lượng từ môi trường dưới dạng nhiệt", "Chỉ xảy ra khi được đun nóng liên tục", "Không có sự trao đổi nhiệt với môi trường"],
     "answer": 0, "explanation": "Phản ứng tỏa nhiệt (Exothermic reaction) là phản ứng giải phóng nhiệt năng ra môi trường xung quanh, làm môi trường xung quanh nóng lên."},
    {"id": "mc-c4-002", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Ví dụ thực tế",
     "question": "Quá trình nào sau đây là phản ứng THU nhiệt?",
     "choices": ["Nung đá vôi ($CaCO_3$) để sản xuất vôi sống ($CaO$)", "Đốt cháy khí gas (Methane, Propane) trong bếp", "Hòa tan $NaOH$ rắn vào nước (cốc nước nóng lên)", "Quá trình hô hấp của động vật"],
     "answer": 0, "explanation": "Phản ứng nung đá vôi ($CaCO_3 \\xrightarrow{t^\\circ} CaO + CO_2$) cần cung cấp nhiệt độ rất cao liên tục ($>900^\\circ\\text{C}$). Nếu ngừng cung cấp nhiệt, phản ứng sẽ dừng lại ngay $\\Rightarrow$ Đây là phản ứng hấp thu nhiệt từ môi trường (thu nhiệt)."},
    {"id": "mc-c4-003", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Nhận biết qua $\\Delta H$",
     "question": "Cho phương trình nhiệt hóa học: $H_2 (g) + I_2 (g) \\rightarrow 2HI (g)$ có $\\Delta_r H_{298}^0 = +52,96 \\text{ kJ}$. Phát biểu nào sau đây ĐÚNG?",
     "choices": ["Đây là phản ứng thu nhiệt", "Đây là phản ứng tỏa nhiệt", "Nhiệt độ của hệ sẽ tăng lên khi phản ứng xảy ra", "Phản ứng này giải phóng 52,96 kJ nhiệt lượng"],
     "answer": 0, "explanation": "Quy ước dấu: $\\Delta H > 0$ (dương) là phản ứng THU nhiệt. $\\Delta H < 0$ (âm) là phản ứng TỎA nhiệt. Do $\\Delta H = +52,96$ kJ > 0 nên đây là PƯ thu nhiệt."},
    {"id": "mc-c4-004", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "Lập luận nhiệt độ môi trường",
     "question": "Khi cho một viên Vitamin C sủi vào cốc nước, ta thấy nước trong cốc mát hơn so với ban đầu. Hiện tượng này chứng tỏ quá trình hòa tan viên sủi là:",
     "choices": ["Quá trình thu nhiệt (hệ thống lấy nhiệt từ nước làm nước lạnh đi)", "Quá trình tỏa nhiệt (hệ thống truyền nhiệt cho nước)", "Không có sự trao đổi nhiệt", "Quá trình phân hủy hạt nhân"],
     "answer": 0, "explanation": "Nước (môi trường xung quanh) bị lạnh đi, tức là nó đã bị mất nhiệt. Nhiệt này đã truyền vào viên sủi (hệ thống) để thực hiện quá trình phản ứng/hòa tan $\\Rightarrow$ Quá trình hòa tan là THU nhiệt ($\\Delta H > 0$)."},

    # Nhóm 4, 5, 6: Khái niệm Enthalpy tạo thành chuẩn
    {"id": "mc-c4-005", "chapter": "c4", "lesson": "b22", "level": "nb", "dang": "Định nghĩa Nhiệt tạo thành",
     "question": "Nhiệt tạo thành chuẩn (hay enthalpy tạo thành chuẩn, $\\Delta_f H_{298}^0$) của một chất là lượng nhiệt kèm theo của phản ứng tạo thành 1 mol chất đó từ:",
     "choices": ["Các đơn chất ở trạng thái bền vững nhất ở điều kiện chuẩn", "Các hợp chất bất kì ở điều kiện chuẩn", "Các nguyên tử khí ở điều kiện chuẩn", "Các ion ở trạng thái chuẩn"],
     "answer": 0, "explanation": "Định nghĩa: $\\Delta_f H_{298}^0$ là nhiệt lượng tỏa ra hay thu vào khi tạo thành 1 mol hợp chất TỪ CÁC ĐƠN CHẤT BỀN VỮNG NHẤT ở điều kiện chuẩn ($25^\\circ\\text{C}$ hay 298K, 1 bar)."},
    {"id": "mc-c4-006", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Nhiệt tạo thành của đơn chất",
     "question": "Nhiệt tạo thành chuẩn ($\\Delta_f H_{298}^0$) của khí Oxygen ($O_2$) và than chì (C graphite) có giá trị bằng bao nhiêu?",
     "choices": ["Luôn bằng 0", "Lớn hơn 0", "Nhỏ hơn 0", "Không xác định được"],
     "answer": 0, "explanation": "Theo quy ước, enthalpy tạo thành chuẩn của các ĐƠN CHẤT ở trạng thái bền vững nhất ở điều kiện chuẩn (như $O_2$ khí, $H_2$ khí, C than chì, $Fe$ rắn...) ĐỀU BẰNG 0."},
    {"id": "mc-c4-007", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Nhận biết PT nhiệt tạo thành",
     "question": "Phương trình nhiệt hóa học nào sau đây biểu diễn NHIỆT TẠO THÀNH CHUẨN của nước lỏng ($H_2O$)?",
     "choices": ["$H_2(g) + \\frac{1}{2} O_2(g) \\rightarrow H_2O(l)$", "$2H_2(g) + O_2(g) \\rightarrow 2H_2O(l)$", "$H^+(aq) + OH^-(aq) \\rightarrow H_2O(l)$", "$H_2O(g) \\rightarrow H_2O(l)$"],
     "answer": 0, "explanation": "Nhiệt tạo thành phải thỏa mãn 2 điều kiện: (1) Tạo ra đúng 1 MOL SẢN PHẨM. (2) Chất tham gia phải là CÁC ĐƠN CHẤT BỀN NHẤT ($H_2, O_2$). Đáp án B tạo 2 mol nên sai. Đáp án C đi từ ion nên sai. Đáp án D là quá trình ngưng tụ."},
    {"id": "mc-c4-008", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Độ bền qua $\\Delta H_f$",
     "question": "Cho enthalpy tạo thành chuẩn của $CO_2(g)$ là $-393,5 \\text{ kJ/mol}$, của $NO(g)$ là $+90,29 \\text{ kJ/mol}$. Phân tử nào bền vững hơn về mặt năng lượng?",
     "choices": ["$CO_2$ bền vững hơn nhiều so với $NO$", "$NO$ bền vững hơn nhiều so với $CO_2$", "Cả hai bền vững như nhau", "Không thể so sánh được"],
     "answer": 0, "explanation": "$\\Delta_f H^0$ càng âm thì hợp chất đó càng tỏa ra nhiều năng lượng khi hình thành (tức là nó rơi xuống trạng thái năng lượng thấp hơn) $\\Rightarrow$ CÀNG BỀN VỮNG. Ngược lại $\\Delta_f H^0 > 0$ (như NO) là hợp chất thu nhiệt, mức năng lượng cao, kém bền, dễ bị phân hủy trở lại thành đơn chất."},

    # Nhóm 7, 8, 9: Tính Biến thiên Enthalpy từ Nhiệt tạo thành
    {"id": "mc-c4-009", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Công thức tính $\\Delta_r H$",
     "question": "Công thức tính biến thiên enthalpy chuẩn của một phản ứng hóa học ($\\Delta_r H_{298}^0$) dựa vào nhiệt tạo thành chuẩn ($\\Delta_f H_{298}^0$) của các chất là:",
     "choices": ["$\\Delta_r H^0 = \\sum \\Delta_f H^0 (\\text{Sản phẩm}) - \\sum \\Delta_f H^0 (\\text{Chất đầu})$", "$\\Delta_r H^0 = \\sum \\Delta_f H^0 (\\text{Chất đầu}) - \\sum \\Delta_f H^0 (\\text{Sản phẩm})$", "$\\Delta_r H^0 = \\sum \\Delta_f H^0 (\\text{Sản phẩm}) + \\sum \\Delta_f H^0 (\\text{Chất đầu})$", "$\\Delta_r H^0 = \\prod \\Delta_f H^0 (\\text{Sản phẩm}) / \\prod \\Delta_f H^0 (\\text{Chất đầu})$"],
     "answer": 0, "explanation": "Quy tắc: Biến thiên ($\\Delta$) luôn bằng TRẠNG THÁI CUỐI (Sản phẩm) trừ đi TRẠNG THÁI ĐẦU (Chất tham gia). (Nhớ nhân thêm hệ số cân bằng của phương trình)."},
    {"id": "mc-c4-010", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính cơ bản 1",
     "question": "Cho phản ứng: $CO(g) + \\frac{1}{2} O_2(g) \\rightarrow CO_2(g)$. Biết nhiệt tạo thành chuẩn của CO(g) là $-110,5 \\text{ kJ/mol}$, của $CO_2(g)$ là $-393,5 \\text{ kJ/mol}$. Biến thiên enthalpy của phản ứng ($\\Delta_r H_{298}^0$) là:",
     "choices": ["-283,0 kJ", "+283,0 kJ", "-504,0 kJ", "+504,0 kJ"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = \\Delta_f H^0 (CO_2) - [\\Delta_f H^0 (CO) + \\frac{1}{2} \\Delta_f H^0 (O_2)]$. Biết $\\Delta_f H^0 (O_2) = 0$. $\\Delta_r H^0 = -393,5 - (-110,5) = -393,5 + 110,5 = -283,0 \\text{ kJ}$."},
    {"id": "mc-c4-011", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính cơ bản 2 có hệ số",
     "question": "Tính $\\Delta_r H^0_{298}$ của phản ứng: $2Al(s) + Fe_2O_3(s) \\rightarrow 2Fe(s) + Al_2O_3(s)$. Cho biết $\\Delta_f H^0_{298}$ của $Fe_2O_3$ là -824,2 kJ/mol; của $Al_2O_3$ là -1675,7 kJ/mol.",
     "choices": ["-851,5 kJ", "+851,5 kJ", "-2499,9 kJ", "+2499,9 kJ"],
     "answer": 0, "explanation": "Al và Fe là đơn chất $\\Rightarrow \\Delta_f H^0 = 0$. $\\Delta_r H^0 = [2(0) + 1(-1675,7)] - [2(0) + 1(-824,2)] = -1675,7 - (-824,2) = -851,5 \\text{ kJ}$."},
    {"id": "mc-c4-012", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính nhiệt lượng tỉ lệ",
     "question": "Cho phản ứng nhiệt phân: $CaCO_3(s) \\rightarrow CaO(s) + CO_2(g)$ có $\\Delta_r H^0_{298} = +178,29 \\text{ kJ}$. Để nhiệt phân hoàn toàn 200 gam $CaCO_3$ (M=100) thì cần cung cấp một nhiệt lượng là bao nhiêu?",
     "choices": ["356,58 kJ", "178,29 kJ", "89,145 kJ", "713,16 kJ"],
     "answer": 0, "explanation": "Nhiệt phản ứng $\\Delta_r H^0$ được tính cho SỐ MOL tương ứng với hệ số phương trình. Phương trình trên ghi cho hệ số 1 mol $CaCO_3$ $\\Rightarrow$ Cần +178,29 kJ nhiệt lượng. Ta có 200 gam $CaCO_3 = 2$ mol. Vậy lượng nhiệt cần thiết $= 2 \\times 178,29 = 356,58 \\text{ kJ}$."},

    # Nhóm 10, 11, 12: Đồ thị Enthalpy (Giản đồ năng lượng)
    {"id": "mc-c4-013", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Đọc giản đồ PƯ Tỏa",
     "question": "Trong giản đồ năng lượng (Enthalpy diagram) của một phản ứng, nếu mức năng lượng (Enthalpy) của các chất SẢN PHẨM thấp hơn mức năng lượng của các CHẤT THAM GIA, thì đây là phản ứng gì?",
     "choices": ["Phản ứng tỏa nhiệt", "Phản ứng thu nhiệt", "Phản ứng thuận nghịch", "Phản ứng không xảy ra"],
     "answer": 0, "explanation": "Sản phẩm thấp hơn $\\Rightarrow$ hệ đã mất đi năng lượng $\\Rightarrow$ năng lượng đó được tỏa ra môi trường. (Và toán học: $\\Delta H = H_{\\text{sp}} - H_{\\text{tg}} < 0$)."},
    {"id": "mc-c4-014", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Đọc giản đồ PƯ Thu",
     "question": "Trong giản đồ năng lượng của phản ứng thu nhiệt, mũi tên biểu diễn $\\Delta_r H$ sẽ hướng như thế nào?",
     "choices": ["Hướng từ dưới lên trên (từ mức năng lượng chất tham gia thấp lên mức sản phẩm cao)", "Hướng từ trên xuống dưới", "Nằm ngang", "Hướng vòng tròn"],
     "answer": 0, "explanation": "Thu nhiệt (H hấp thụ) $\\Rightarrow$ Năng lượng của hệ tăng lên. Vậy mức SẢN PHẨM cao hơn CHẤT THAM GIA. Mũi tên đi từ chất tham gia đến sản phẩm sẽ đi LÊN ($\\Delta H > 0$)."},
    {"id": "mc-c4-015", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính ngược từ $\\Delta H$",
     "question": "Phản ứng $N_2(g) + O_2(g) \\rightarrow 2NO(g)$ là phản ứng thu nhiệt với $\\Delta_r H^0_{298} = +180,58 \\text{ kJ}$. Mức năng lượng của chất tham gia bằng 0. Hỏi mức năng lượng của 1 mol khí NO trên giản đồ là bao nhiêu?",
     "choices": ["+90,29 kJ", "+180,58 kJ", "-90,29 kJ", "-180,58 kJ"],
     "answer": 0, "explanation": "Theo phương trình tạo ra 2 mol NO thì $\\Delta H = +180,58$ kJ. Tức là năng lượng hệ thống (chứa 2 mol NO) cao hơn chất tham gia ($N_2, O_2$) 180,58 kJ. Mức chất tham gia = 0 $\\Rightarrow$ Năng lượng của 2 mol NO là +180,58 kJ. Vậy 1 mol NO có năng lượng (tức là Nhiệt tạo thành) $= +180,58 / 2 = +90,29 \\text{ kJ}$."},
    {"id": "mc-c4-016", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Ứng dụng Đồ thị",
     "question": "Dựa vào giản đồ năng lượng, tại sao các phản ứng tỏa nhiệt mạnh ($\\Delta H$ rất âm) thường dễ tự xảy ra (tự phát) hơn các phản ứng thu nhiệt mạnh?",
     "choices": ["Vì chúng có xu hướng đi đến trạng thái năng lượng thấp hơn (bền vững hơn), phù hợp với quy luật tự nhiên", "Vì phản ứng tỏa nhiệt tạo ra nhiều chất hơn", "Vì chúng không cần chất xúc tác", "Vì chúng diễn ra trong dung dịch"],
     "answer": 0, "explanation": "Mọi hệ thống trong tự nhiên (hòn đá trên dốc, phân tử hóa học...) đều có xu hướng tự phát giảm thiểu năng lượng thế năng của mình để đạt trạng thái bền vững nhất. Tỏa nhiệt = vứt bớt năng lượng $\\Rightarrow$ bền hơn $\\Rightarrow$ dễ xảy ra."},

    # Nhóm 13, 14: Biến thiên Enthalpy theo Năng lượng liên kết
    {"id": "mc-c4-017", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Công thức Eb",
     "question": "Công thức tính $\\Delta_r H^0$ của phản ứng dựa vào Năng lượng liên kết ($E_b$) TẤT CẢ các chất ở thể KHÍ là:",
     "choices": ["$\\Delta_r H^0 = \\sum E_b (\\text{Chất đầu}) - \\sum E_b (\\text{Sản phẩm})$", "$\\Delta_r H^0 = \\sum E_b (\\text{Sản phẩm}) - \\sum E_b (\\text{Chất đầu})$", "$\\Delta_r H^0 = \\sum E_b (\\text{Chất đầu}) + \\sum E_b (\\text{Sản phẩm})$", "Không có công thức nào"],
     "answer": 0, "explanation": "Chú ý: Tính theo năng lượng liên kết ($E_b$) thì CÔNG THỨC BỊ NGƯỢC LẠI so với tính theo Nhiệt tạo thành ($\\Delta_f H$). Bản chất: Để chất đầu biến thành SP, phải THU năng lượng BẺ GÃY liên kết chất đầu (mang dấu +), sau đó TỎA năng lượng TẠO THÀNH liên kết SP (mang dấu -). Do đó: $\\Delta H = E_{\\text{đầu}} - E_{\\text{sau}}$."},
    {"id": "mc-c4-018", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Điều kiện áp dụng Eb",
     "question": "Điều kiện QUAN TRỌNG NHẤT để có thể áp dụng công thức tính $\\Delta_r H^0 = \\sum E_b (\\text{đầu}) - \\sum E_b (\\text{sau})$ một cách chính xác là gì?",
     "choices": ["Tất cả các chất tham gia và sản phẩm đều phải ở trạng thái KHÍ", "Phản ứng phải là phản ứng thuận nghịch", "Phản ứng phải có nhiệt độ cao", "Tất cả các chất phải là đơn chất"],
     "answer": 0, "explanation": "Năng lượng liên kết $E_b$ được định nghĩa cho sự phá vỡ liên kết của các phân tử ở TRẠNG THÁI KHÍ. Nếu có chất lỏng, chất rắn (VD: nước lỏng, carbon than chì) thì phải tốn thêm năng lượng bay hơi, thăng hoa... công thức trên sẽ bị sai số lớn."},
    {"id": "mc-c4-019", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính toán Eb đơn giản",
     "question": "Tính $\\Delta_r H^0$ của phản ứng: $H_2(g) + Cl_2(g) \\rightarrow 2HCl(g)$. Biết Năng lượng liên kết (kJ/mol): $E_b(H-H) = 436$, $E_b(Cl-Cl) = 243$, $E_b(H-Cl) = 432$.",
     "choices": ["-185 kJ", "+185 kJ", "-432 kJ", "-243 kJ"],
     "answer": 0, "explanation": "Tổng $E_b$ (đầu) $= 436 (H_2) + 243 (Cl_2) = 679$ kJ. Tổng $E_b$ (sau) $= 2 \\times 432 (HCl) = 864$ kJ. $\\Delta_r H^0 = E_{\\text{đầu}} - E_{\\text{sau}} = 679 - 864 = -185 \\text{ kJ}$."},
    {"id": "mc-c4-020", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính toán Eb với chất hữu cơ",
     "question": "Đốt cháy Methane: $CH_4(g) + 2O_2(g) \\rightarrow CO_2(g) + 2H_2O(g)$. Biết $E_b(C-H) = 414$, $E_b(O=O) = 498$, $E_b(C=O) = 799$, $E_b(O-H) = 464$ (kJ/mol). Biến thiên enthalpy phản ứng là:",
     "choices": ["-802 kJ", "+802 kJ", "-401 kJ", "-654 kJ"],
     "answer": 0, "explanation": "Đứt: $CH_4$ có 4 C-H $\\Rightarrow 4 \\times 414 = 1656$. $2 O_2$ có 2 O=O $\\Rightarrow 2 \\times 498 = 996$. Tổng đứt $= 2652$. Nối: $CO_2$ có 2 C=O $\\Rightarrow 2 \\times 799 = 1598$. $2 H_2O$ có 4 O-H $\\Rightarrow 4 \\times 464 = 1856$. Tổng nối $= 3454$. $\\Delta H = 2652 - 3454 = -802 \\text{ kJ}$."},

    # Nhóm 15, 16, 17: Phản ứng tỏa/thu trong đời sống
    {"id": "mc-c4-021", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Đánh giá chất đốt",
     "question": "Khí gas, than đá, xăng dầu được sử dụng làm nhiên liệu trong đời sống và sản xuất vì các phản ứng đốt cháy chúng là:",
     "choices": ["Phản ứng tỏa nhiệt mạnh, cung cấp lượng lớn nhiệt năng", "Phản ứng thu nhiệt", "Phản ứng không cần oxi", "Phản ứng tạo ra nước"],
     "answer": 0, "explanation": "Các phản ứng cháy của nhiên liệu hóa thạch có $\\Delta H \\ll 0$ (tỏa rất nhiều nhiệt), nên được con người khai thác để đun nấu, chạy động cơ."},
    {"id": "mc-c4-022", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Túi chườm lạnh",
     "question": "Trong y tế, người ta sử dụng 'túi chườm lạnh' chứa bột Amoni nitrat ($NH_4NO_3$) và một túi nước nhỏ. Khi bóp mạnh làm vỡ túi nước, muối hòa tan vào nước làm túi lạnh đi nhanh chóng. Đây là ứng dụng của:",
     "choices": ["Quá trình thu nhiệt", "Quá trình tỏa nhiệt", "Quá trình hóa lỏng", "Phản ứng cháy"],
     "answer": 0, "explanation": "Hòa tan $NH_4NO_3$ vào nước là một quá trình THU NHIỆT MẠNH (hấp thụ nhiệt từ môi trường xung quanh là cái túi và cơ thể người), nên túi bị lạnh đi $\\Rightarrow$ dùng chườm lạnh giảm sưng đau."},
    {"id": "mc-c4-023", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Túi chườm nóng",
     "question": "Túi sưởi ấm (túi chườm nóng) quân đội chứa bột Sắt, muối, than hoạt tính và nước. Khi xé bao bì tiếp xúc không khí, túi sẽ nóng lên giữ ấm được nhiều giờ. Bản chất phản ứng là:",
     "choices": ["Phản ứng oxi hóa chậm sắt (tạo gỉ sắt) là phản ứng tỏa nhiệt", "Phản ứng cháy nổ của bột sắt", "Sắt tan trong muối tạo phản ứng thu nhiệt", "Sắt phản ứng với nước tạo Hydro"],
     "answer": 0, "explanation": "Sự oxi hóa Sắt (Iron oxidation) bằng $O_2$ trong không khí (có muối làm xúc tác) là phản ứng TỎA NHIỆT nhưng tốc độ chậm $\\Rightarrow$ Tỏa nhiệt đều đặn trong nhiều giờ."},
    {"id": "mc-c4-024", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "Năng lượng thực phẩm",
     "question": "Trên vỏ hộp sữa ghi \"Năng lượng: 70 kcal / 100ml\". Đơn vị kcal (kilocalorie) liên quan mật thiết với kJ (kilojoule) như thế nào trong hóa học?",
     "choices": ["$1 \\text{ kcal} \\approx 4,184 \\text{ kJ}$", "$1 \\text{ kcal} = 1000 \\text{ kJ}$", "$1 \\text{ kJ} \\approx 4,184 \\text{ kcal}$", "$1 \\text{ kcal} = 1 \\text{ kJ}$"],
     "answer": 0, "explanation": "Calorie là đơn vị đo nhiệt lượng vật lí cũ (nhiệt để làm 1g nước tăng 1 độ C). $1 \\text{ cal} \\approx 4,184 \\text{ Joule}$. Tương tự $1 \\text{ kcal} = 4,184 \\text{ kJ}$. Năng lượng thực phẩm chính là $\\Delta H$ tỏa ra khi cơ thể oxi hóa (đốt cháy sinh học) thức ăn."},

    # Nhóm 18, 19, 20: Các bài toán mở rộng (Định luật Hess ẩn, tính toán % khối lượng)
    {"id": "mc-c4-025", "chapter": "c4", "lesson": "b24", "level": "th", "dang": "Nhiệt phản ứng nghịch",
     "question": "Nếu phản ứng $A \\rightarrow B$ có $\\Delta_r H = -100 \\text{ kJ}$, thì phản ứng nghịch $B \\rightarrow A$ sẽ có $\\Delta_r H$ bằng bao nhiêu?",
     "choices": ["+100 kJ", "-100 kJ", "0 kJ", "Không tính được"],
     "answer": 0, "explanation": "Hệ quả của Nguyên lí I Nhiệt động lực học: Đảo ngược phương trình thì ĐẢO DẤU của $\\Delta H$. Chiều đi tỏa 100 kJ thì chiều về phải thu đúng 100 kJ."},
    {"id": "mc-c4-026", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhân hệ số PT nhiệt",
     "question": "Biết: $H_2(g) + \\frac{1}{2}O_2(g) \\rightarrow H_2O(l)$ có $\\Delta H = -285,8 \\text{ kJ}$. Biến thiên enthalpy của phản ứng $2H_2O(l) \\rightarrow 2H_2(g) + O_2(g)$ là:",
     "choices": ["+571,6 kJ", "-571,6 kJ", "+285,8 kJ", "-285,8 kJ"],
     "answer": 0, "explanation": "Phản ứng hỏi bị ĐẢO NGƯỢC (đổi dấu thành dương) và NHÂN ĐÔI HỆ SỐ. Do đó $\\Delta H_{mới} = (-285,8) \\times (-2) = +571,6 \\text{ kJ}$."},
    {"id": "mc-c4-027", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Định luật Hess cơ bản 1",
     "question": "Cho hai phương trình:\n(1) $C(s) + \\frac{1}{2}O_2(g) \\rightarrow CO(g) \\quad \\Delta H_1 = -110,5 \\text{ kJ}$\n(2) $CO(g) + \\frac{1}{2}O_2(g) \\rightarrow CO_2(g) \\quad \\Delta H_2 = -283,0 \\text{ kJ}$\nTính $\\Delta H_3$ của phản ứng tổng hợp: $C(s) + O_2(g) \\rightarrow CO_2(g)$?",
     "choices": ["-393,5 kJ", "+172,5 kJ", "-172,5 kJ", "+393,5 kJ"],
     "answer": 0, "explanation": "Theo định luật Hess, hiệu ứng nhiệt của quá trình hóa học chỉ phụ thuộc vào trạng thái đầu và cuối, không phụ thuộc đường đi. Lấy (1) + (2) ta triệt tiêu được trung gian CO, ra phương trình (3). Vậy $\\Delta H_3 = \\Delta H_1 + \\Delta H_2 = (-110,5) + (-283,0) = -393,5 \\text{ kJ}$."},
    {"id": "mc-c4-028", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhiệt cháy",
     "question": "Đốt cháy 12 gam Cacbon (C, graphite) tỏa ra 393,5 kJ nhiệt. Đốt cháy m gam Lưu huỳnh (S, rhombic) tỏa ra 148,4 kJ nhiệt. Biết $\\Delta_f H^0(CO_2) = -393,5 \\text{ kJ/mol}$ và $\\Delta_f H^0(SO_2) = -296,8 \\text{ kJ/mol}$. Giá trị của m là:",
     "choices": ["16,0 gam", "32,0 gam", "8,0 gam", "64,0 gam"],
     "answer": 0, "explanation": "Đốt cháy 1 mol S (32g) tạo 1 mol $SO_2$ thì tỏa ra 296,8 kJ (dấu âm thể hiện tỏa). Phản ứng thực tế tỏa 148,4 kJ (bằng một nửa). Vậy số mol S đã đốt là $0,5$ mol. $m_S = 0,5 \\times 32 = 16,0$ gam."},

    # Nhóm 21, 22, 23: Bài toán hỗn hợp nhiên liệu
    {"id": "mc-c4-029", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Hỗn hợp khí gas",
     "question": "Một bình gas chứa 12 kg hỗn hợp Propane ($C_3H_8$) và Butane ($C_4H_{10}$) với tỉ lệ mol tương ứng 1:2. Biết khi đốt cháy 1 mol Propane tỏa ra 2220 kJ, 1 mol Butane tỏa ra 2850 kJ. Tổng nhiệt lượng tỏa ra khi đốt hết bình gas là: (C=12, H=1)",
     "choices": ["594000 kJ", "654000 kJ", "593400 kJ", "285000 kJ"],
     "answer": 0, "explanation": "Gọi n(C3H8)=x, n(C4H10)=2x. $m = 44x + 58(2x) = 160x = 12000 \\Rightarrow x = 75$. Tổng nhiệt $= 75 \\times 2220 + 150 \\times 2850 = 594000 \\text{ kJ}$."},
    {"id": "mc-c4-030", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "So sánh năng suất tỏa nhiệt",
     "question": "Năng suất tỏa nhiệt của nhiên liệu là nhiệt lượng tỏa ra khi đốt cháy hoàn toàn 1 KILOGRAM (hoặc 1 gam) nhiên liệu đó. So sánh năng suất tỏa nhiệt (kJ/g) của $H_2$ (biết 1 mol tỏa 286 kJ) và $CH_4$ (biết 1 mol tỏa 890 kJ)?",
     "choices": ["$H_2$ cao hơn ($143 \\text{ kJ/g}$) so với $CH_4$ ($55,6 \\text{ kJ/g}$)", "$CH_4$ cao hơn vì 1 mol tỏa nhiều nhiệt hơn", "Cả hai bằng nhau", "Không thể so sánh được vì khối lượng mol khác nhau"],
     "answer": 0, "explanation": "$H_2$ có M=2 g/mol $\\Rightarrow$ năng suất = $286 / 2 = 143 \\text{ kJ/g}$. $CH_4$ có M=16 g/mol $\\Rightarrow$ năng suất = $890 / 16 \\approx 55,6 \\text{ kJ/g}$. Do $H_2$ rất nhẹ nên tính theo khối lượng, Hydro là nhiên liệu có năng suất tỏa nhiệt cao nhất tự nhiên (dùng cho tên lửa)."},
    {"id": "mc-c4-031", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính thể tích nước đun sôi",
     "question": "Giả sử 1 bình gas (tỏa ra 594000 kJ) được dùng để đun nước sôi. Biết để 1 kg nước (1 lít) nóng từ $25^\\circ\\text{C}$ lên $100^\\circ\\text{C}$ (sôi) cần khoảng 315 kJ. Và hiệu suất hấp thụ nhiệt của ấm nước là 60%. Hỏi bình gas đó đun sôi được bao nhiêu lít nước?",
     "choices": ["$\sim 1131 \\text{ lít}$", "$\sim 1885 \\text{ lít}$", "$\sim 679 \\text{ lít}$", "$\sim 2500 \\text{ lít}$"],
     "answer": 0, "explanation": "Nhiệt lượng HỮU ÍCH cung cấp cho nước là $Q_{ich} = 594000 \\times 60\\% = 356400 \\text{ kJ}$. Số lít nước đun được $= 356400 / 315 \approx 1131,4$ lít (Hơn 1 mét khối nước)."},

    # Nhóm 24, 25: Nâng cao Enthalpy tạo thành - Nhiệt dung
    {"id": "mc-c4-032", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Quy ước điều kiện chuẩn",
     "question": "Điều kiện chuẩn (Standard state) trong nhiệt động học đối với chất khí và dung dịch là gì?",
     "choices": ["Khí ở áp suất 1 bar, dung dịch ở nồng độ 1 mol/L, thường xét ở $25^\\circ\\text{C}$ (298K)", "Khí ở áp suất 1 atm, nhiệt độ $0^\\circ\\text{C}$", "Khí ở áp suất 1 bar, dung dịch bão hòa", "Khí ở áp suất 2 bar, nhiệt độ $100^\\circ\\text{C}$"],
     "answer": 0, "explanation": "Theo quy ước quốc tế IUPAC mới: Áp suất chuẩn là 1 bar (không phải 1 atm). Nhiệt độ không quy định cứng nhưng thường dùng 298.15 K ($25^\\circ\\text{C}$). Nồng độ chuẩn 1 M ($1 \\text{ mol/L}$)."},
    {"id": "mc-c4-033", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Enthalpy đơn chất ngoại lệ",
     "question": "Nhiệt tạo thành chuẩn của $O_2(g)$ bằng 0. Vậy nhiệt tạo thành chuẩn của Ozone ($O_3(g)$) có bằng 0 không?",
     "choices": ["Không, vì $O_3$ không phải là dạng đơn chất bền vững nhất của nguyên tố Oxi (khác 0, thường $>0$)", "Có, vì nó cũng là đơn chất Oxi", "Bằng 0 vì nó tồn tại tự nhiên trên tầng bình lưu", "Nhỏ hơn 0 vì nó độc"],
     "answer": 0, "explanation": "Quy ước chỉ áp dụng cho DẠNG THÙ HÌNH BỀN VỮNG NHẤT ở đk chuẩn (là $O_2$). $O_3$ kém bền hơn, dễ phân hủy thành $O_2$ và tỏa nhiệt, do đó $O_3$ có mức năng lượng cao hơn $\\Rightarrow \\Delta_f H^0(O_3) > 0$ (+142,7 kJ/mol)."},
    {"id": "mc-c4-034", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Năng lượng lk vs Phản ứng",
     "question": "Vì sao phản ứng giữa $N_2$ và $O_2$ tạo NO (trong động cơ ô tô hoặc khi có sét) lại là phản ứng thu nhiệt và cần nhiệt độ rất cao ($\\sim 3000^\\circ\\text{C}$)?",
     "choices": ["Vì năng lượng liên kết ba trong phân tử $N_2$ ($N\\equiv N$) rất lớn (945 kJ/mol), cần rất nhiều năng lượng để bẻ gãy nó trước khi tạo liên kết mới", "Vì $N_2$ và $O_2$ là hai khí trơ", "Vì NO là một chất khí không màu", "Vì phản ứng tỏa ra quá ít nhiệt"],
     "answer": 0, "explanation": "Nitơ rất trơ ở nhiệt độ thường do liên kết ba $N\\equiv N$ quá bền chặt. Để phản ứng (bẻ gãy) phải cung cấp lượng nhiệt khổng lồ ban đầu (tia lửa điện, sét). Dẫn đến tổng $\\Delta H > 0$ (thu nhiệt)."},
    {"id": "mc-c4-035", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính Enthalpy phân hủy",
     "question": "Nếu $\\Delta_f H^0_{298} (CaCO_3(s)) = -1207 \\text{ kJ/mol}$, $\\Delta_f H^0_{298} (CaO(s)) = -635 \\text{ kJ/mol}$, $\\Delta_f H^0_{298} (CO_2(g)) = -393,5 \\text{ kJ/mol}$. Tính $\\Delta_r H^0_{298}$ của phản ứng phân hủy $CaCO_3 \\rightarrow CaO + CO_2$.",
     "choices": ["+178,5 kJ", "-178,5 kJ", "+2235,5 kJ", "-2235,5 kJ"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = (\\Delta_f H(CaO) + \\Delta_f H(CO_2)) - \\Delta_f H(CaCO_3) = (-635 - 393,5) - (-1207) = -1028,5 + 1207 = +178,5 \\text{ kJ}$."},

    # 25 Câu tiếp theo: Đa dạng bài tập, thực hành, nhận thức
    {"id": "mc-c4-036", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Nhiệt hóa học phương trình",
     "question": "Phương trình nhiệt hóa học là phương trình hóa học có kèm theo thông tin gì?",
     "choices": ["Kèm theo trạng thái vật lí của các chất và giá trị biến thiên enthalpy ($\\Delta H$)", "Chỉ kèm theo màu sắc của các chất", "Kèm theo tốc độ phản ứng", "Kèm theo tên người phát hiện"],
     "answer": 0, "explanation": "VD: $C(s) + O_2(g) \\rightarrow CO_2(g); \\Delta_r H^0 = -393.5 \\text{ kJ}$. Chữ (s), (g) chỉ trạng thái Rắn, Khí (Solid, Gas). Đây là thông số bắt buộc vì trạng thái khác nhau thì năng lượng khác nhau."},
    {"id": "mc-c4-037", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Ý nghĩa trạng thái chất",
     "question": "Tại sao trong phương trình nhiệt hóa học, bắt buộc phải ghi rõ trạng thái vật lí (rắn s, lỏng l, khí g) của các chất?",
     "choices": ["Vì enthalpy của một chất phụ thuộc rất nhiều vào trạng thái vật lí của nó (VD: $H_2O$ khí có năng lượng cao hơn $H_2O$ lỏng)", "Để phương trình dài và đẹp hơn", "Vì quy định của sách giáo khoa", "Để tính toán số mol dễ hơn"],
     "answer": 0, "explanation": "Để hóa hơi 1 mol nước lỏng thành hơi nước cần hấp thu khoảng 44 kJ. Do đó $H_{H_2O(g)} = H_{H_2O(l)} + 44$. Nếu ghi sai trạng thái sẽ dẫn đến sai số $\\Delta H$ của phản ứng hàng chục kJ."},
    {"id": "mc-c4-038", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Dấu của phân hủy",
     "question": "Phản ứng nhiệt phân (phân hủy bằng nhiệt) các hợp chất như $KMnO_4, KClO_3, Cu(OH)_2$ thường có dấu của $\\Delta_r H$ như thế nào?",
     "choices": ["$\\Delta_r H > 0$ (Thu nhiệt)", "$\\Delta_r H < 0$ (Tỏa nhiệt)", "$\\Delta_r H = 0$", "Tùy thuộc vào áp suất"],
     "answer": 0, "explanation": "Hầu hết các phản ứng nhiệt phân muối, bazơ đều cần bẻ gãy liên kết hóa trị/ion mạng lưới, nên là phản ứng thu nhiệt $\\Delta H > 0$."},
    {"id": "mc-c4-039", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Nhiệt trung hòa",
     "question": "Phản ứng trung hòa giữa axit mạnh ($HCl$) và bazơ mạnh ($NaOH$) trong dung dịch loãng luôn tỏa ra một nhiệt lượng không đổi (khoảng -57,3 kJ/mol). Giải thích nào sau đây đúng nhất?",
     "choices": ["Vì bản chất của mọi phản ứng trung hòa axit-bazơ mạnh là sự kết hợp của $H^+$ và $OH^-$ tạo ra $H_2O$: $H^+ + OH^- \\rightarrow H_2O$", "Vì Na tác dụng với Cl luôn tỏa -57,3 kJ", "Vì nước là chất cách nhiệt tốt", "Vì $HCl$ và $NaOH$ có khối lượng mol tương đương nhau"],
     "answer": 0, "explanation": "Dù dùng $HNO_3 + KOH$ hay $HCl + NaOH$ loãng thì phương trình ion thu gọn đều là 1 phương trình duy nhất: $H^+ + OH^- \\rightarrow H_2O$. Do đó Nhiệt trung hòa chuẩn của mọi axit mạnh - bazơ mạnh đều $\\approx -57,3 \\text{ kJ/mol}$ nước tạo thành."},
    
    {"id": "mc-c4-040", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Năng lượng trung bình",
     "question": "Biết phân tử $CH_4$ có cấu trúc tứ diện đều với 4 liên kết C-H giống hệt nhau. Để phá vỡ hoàn toàn 1 mol $CH_4$ thành $C(g) + 4H(g)$ cần tiêu tốn 1656 kJ. Năng lượng liên kết trung bình của 1 liên kết C-H là bao nhiêu?",
     "choices": ["414 kJ/mol", "1656 kJ/mol", "828 kJ/mol", "207 kJ/mol"],
     "answer": 0, "explanation": "$CH_4$ có 4 liên kết C-H giống nhau. Năng lượng phá vỡ cả 4 là 1656. Năng lượng 1 liên kết = $1656 / 4 = 414 \\text{ kJ/mol}$."},
    {"id": "mc-c4-041", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Bài toán nghịch",
     "question": "Cho phản ứng $2SO_2(g) + O_2(g) \\rightarrow 2SO_3(g)$ có $\\Delta_r H^0 = -198,4 \\text{ kJ}$. Biết $\\Delta_f H^0 (SO_2) = -296,8 \\text{ kJ/mol}$. Tính enthalpy tạo thành chuẩn của $SO_3(g)$?",
     "choices": ["-396,0 kJ/mol", "-495,2 kJ/mol", "+99,2 kJ/mol", "-198,4 kJ/mol"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = 2 \\times \\Delta_f H(SO_3) - [2 \\times \\Delta_f H(SO_2) + 0]$. Thay số: $-198,4 = 2 \\times x - 2 \\times (-296,8) \Rightarrow 2x = -198,4 - 593,6 = -792,0 \Rightarrow x = -396,0 \\text{ kJ/mol}$."},
    {"id": "mc-c4-042", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Hess vòng kín",
     "question": "Cho:\n$A \\rightarrow B \\quad \\Delta H_1 = +50 \\text{ kJ}$\n$B \\rightarrow C \\quad \\Delta H_2 = -20 \\text{ kJ}$\n$C \\rightarrow A \\quad \\Delta H_3 = ?$ Mối quan hệ vòng kín theo nguyên lí 1 nhiệt động lực học.",
     "choices": ["$\\Delta H_3 = -30 \\text{ kJ}$", "$\\Delta H_3 = +30 \\text{ kJ}$", "$\\Delta H_3 = +70 \\text{ kJ}$", "$\\Delta H_3 = -70 \\text{ kJ}$"],
     "answer": 0, "explanation": "Quá trình vòng kín: A về lại A, tổng $\\Delta H$ của cả vòng phải = 0 (bảo toàn năng lượng). $\\Delta H_1 + \\Delta H_2 + \\Delta H_3 = 0 \Rightarrow 50 - 20 + \\Delta H_3 = 0 \Rightarrow \\Delta H_3 = -30 \\text{ kJ}$."},
    {"id": "mc-c4-043", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Xác định môi trường",
     "question": "Khi thực hiện phản ứng giữa Barium hydroxide octahydrate ($Ba(OH)_2\\cdot 8H_2O$) và Amoni chloride ($NH_4Cl$) trong 1 becher, ta thấy phía ngoài đáy becher ngưng tụ các giọt nước và lạnh buốt, có thể làm đông đá một giọt nước đặt dưới đáy cốc. Phản ứng này là:",
     "choices": ["Phản ứng thu nhiệt rất mạnh", "Phản ứng tỏa nhiệt", "Sự thăng hoa", "Sự ngưng tụ"],
     "answer": 0, "explanation": "Hệ phản ứng rút nhiệt từ cốc và nước lót dưới đáy cốc, khiến nhiệt độ hạ đột ngột $\\Rightarrow$ Thu nhiệt mạnh."},

    {"id": "mc-c4-044", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Eb hợp chất phân nhánh",
     "question": "Để tính chính xác Enthalpy của phản ứng cháy Isooctane (xăng, lỏng) theo Năng lượng liên kết $E_b$, ta sẽ gặp khó khăn gì (sai số lớn)?",
     "choices": ["Phải cộng thêm nhiệt hóa hơi của xăng (từ lỏng sang khí) và nhiệt hóa hơi của H2O lỏng (nếu sản phẩm có nước lỏng) vào phép tính", "Vì không biết công thức cấu tạo của Isooctane", "Vì $E_b$ của các liên kết C-C trong phân tử nhánh rất khó đo chính xác", "Vì phản ứng cháy xăng luôn có xúc tác"],
     "answer": 0, "explanation": "$E_b$ chỉ áp dụng cho khí. Xăng ở thể lỏng. Quá trình thực tế gồm 2 bước: Xăng(lỏng) $\\rightarrow$ Xăng(khí) (THU nhiệt hóa hơi). Xăng(khí) cháy $\\rightarrow$ SP (tính bằng $E_b$). Bỏ qua nhiệt hóa hơi sẽ làm $\\Delta H$ tính được âm hơn thực tế (sai số)."},
    {"id": "mc-c4-045", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "Nhiệt lượng tỏa ra cơ thể",
     "question": "Glucose ($C_6H_{12}O_6$) cung cấp năng lượng cho cơ thể: $C_6H_{12}O_6(s) + 6O_2(g) \\rightarrow 6CO_2(g) + 6H_2O(l)$, $\\Delta_r H^0 = -2803 \\text{ kJ}$. Một người tiêu thụ 1 chai nước ngọt chứa 36g đường Glucose. Năng lượng người đó nhận được từ lượng đường này tương đương bao nhiêu kJ?",
     "choices": ["560,6 kJ", "2803 kJ", "140,15 kJ", "100908 kJ"],
     "answer": 0, "explanation": "1 mol Glucose (180 gam) tỏa 2803 kJ. 36 gam = 0,2 mol. Năng lượng $= 0,2 \\times 2803 = 560,6 \\text{ kJ}$."},
    {"id": "mc-c4-046", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Dấu $\\Delta H$ khi đổi thể",
     "question": "Quá trình chuyển từ nước đá (rắn) sang nước lỏng, rồi từ lỏng sang hơi nước (khí) là các quá trình có $\\Delta H$:",
     "choices": ["Đều dương ( $>0$, thu nhiệt)", "Đều âm ( $<0$, tỏa nhiệt)", "Rắn $\\rightarrow$ Lỏng $>0$, Lỏng $\\rightarrow$ Hơi $<0$", "Thay đổi tùy áp suất"],
     "answer": 0, "explanation": "Nước đá cần ĐUN/CẤP NHIỆT để tan chảy (thu nhiệt). Nước lỏng cần ĐUN để hóa hơi (thu nhiệt). Cả hai quá trình phá vỡ mạng tinh thể/liên kết liên phân tử đều là thu nhiệt ($\\Delta H > 0$)."},
    {"id": "mc-c4-047", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Hess ứng dụng 2",
     "question": "Biết $S(s) + O_2(g) \\rightarrow SO_2(g) \\quad (\\Delta H = -296,8 \\text{ kJ/mol})$ và $S(s) + \\frac{3}{2}O_2(g) \\rightarrow SO_3(g) \\quad (\\Delta H = -395,7 \\text{ kJ/mol})$. Tính $\\Delta H$ của quá trình oxi hóa $SO_2$ thành $SO_3$: $SO_2(g) + \\frac{1}{2}O_2(g) \\rightarrow SO_3(g)$?",
     "choices": ["-98,9 kJ/mol", "+98,9 kJ/mol", "-692,5 kJ/mol", "+692,5 kJ/mol"],
     "answer": 0, "explanation": "Bằng tổ hợp phương trình: PT(3) = PT(2) - PT(1). $\\Delta H = -395,7 - (-296,8) = -98,9 \\text{ kJ/mol}$."},

    {"id": "mc-c4-048", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Nhận xét Bền vững",
     "question": "Cho $\\Delta_f H^0$ (kJ/mol) của các hợp chất hydrogen của nhóm VIA: $H_2O$ (-285,8), $H_2S$ (-20,6), $H_2Se$ (+29,7), $H_2Te$ (+99,6). Nhận xét nào sau đây ĐÚNG về độ bền nhiệt của các hợp chất từ $H_2O$ đến $H_2Te$?",
     "choices": ["Độ bền nhiệt giảm dần", "Độ bền nhiệt tăng dần", "Bền nhất là $H_2Se$", "Không xác định được xu hướng"],
     "answer": 0, "explanation": "Từ $H_2O$ đến $H_2Te$, $\\Delta_f H^0$ đi từ âm nhiều (rất bền) tăng dần lên dương nhiều (Rất kém bền, dễ phân hủy thu nhiệt ngược lại). Vậy độ bền giảm dần. H2O đun $2000^\\circ\\text{C}$ mới phân hủy nhẹ, H2Te để nhiệt độ thường tự phân hủy ra Te đen."},
    {"id": "mc-c4-049", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Năng lượng sinh học",
     "question": "Thực vật lấy năng lượng ở đâu để thực hiện quá trình quang hợp: $6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2$?",
     "choices": ["Hấp thụ năng lượng ánh sáng mặt trời (quá trình thu nhiệt/thu quang năng)", "Lấy nhiệt từ đất", "Từ quá trình hô hấp", "Từ phân bón"],
     "answer": 0, "explanation": "Đây là quá trình nội nhiệt (thu năng lượng). Môi trường cung cấp quang năng (ánh sáng mặt trời) được diệp lục hấp thu để chuyển hóa các chất vô cơ bền vững ($CO_2, H_2O$) thành hợp chất hữu cơ tích lũy năng lượng cao (Glucose)."},
    {"id": "mc-c4-050", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Sự phụ thuộc cấu trúc",
     "question": "Than chì (Graphite) có $\\Delta_f H^0 = 0 \\text{ kJ/mol}$. Kim cương (Diamond) có $\\Delta_f H^0 = +1,9 \\text{ kJ/mol}$. Có thể kết luận điều gì?",
     "choices": ["Than chì là dạng thù hình bền vững hơn kim cương ở điều kiện chuẩn", "Kim cương bền vững hơn than chì", "Than chì có giá trị kinh tế cao hơn", "Có thể dễ dàng biến than chì thành kim cương ở nhiệt độ phòng"],
     "answer": 0, "explanation": "Than chì có Enthalpy thấp hơn $\\Rightarrow$ Bền vững hơn ở điều kiện thường ($25^\\circ\\text{C}, 1 \\text{ bar}$). Kim cương chỉ bền vững ở áp suất cực cao."},
    {"id": "mc-c4-051", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Tính Toán Hiệu Suất Nhiệt",
     "question": "Một bóng đèn sợi đốt 100W tiêu thụ 100 Joule điện năng mỗi giây, nhưng chỉ $5\\%$ lượng đó thành quang năng (ánh sáng), $95\\%$ thành nhiệt năng. Nhiệt lượng tỏa ra môi trường trong 1 giờ thắp sáng là:",
     "choices": ["$342 \\text{ kJ}$", "$360 \\text{ kJ}$", "$342000 \\text{ kJ}$", "$18 \\text{ kJ}$"],
     "answer": 0, "explanation": "Nhiệt tỏa mỗi giây = $100 \\text{ J} \\times 0.95 = 95 \\text{ J}$. 1 giờ = 3600 giây. Nhiệt lượng Q = $95 \\times 3600 = 342000 \\text{ J} = 342 \\text{ kJ}$."},

    {"id": "mc-c4-052", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính Enthalpy từ Phản ứng Oxi hóa",
     "question": "Đốt 1 mol $H_2(g)$ tạo $H_2O(l)$ có $\\Delta H = -285,8 \\text{ kJ}$. Đốt 1 mol $H_2(g)$ tạo $H_2O(g)$ có $\\Delta H = -241,8 \\text{ kJ}$. Nhiệt hóa hơi của 1 mol nước lỏng (quá trình $H_2O(l) \\rightarrow H_2O(g)$) là bao nhiêu?",
     "choices": ["+44,0 kJ", "-44,0 kJ", "+527,6 kJ", "-527,6 kJ"],
     "answer": 0, "explanation": "PT1: $H_2 + 1/2 O_2 \\rightarrow H_2O(l) \\quad \\Delta H = -285,8$. PT2: $H_2 + 1/2 O_2 \\rightarrow H_2O(g) \\quad \\Delta H = -241,8$. Lấy PT2 - PT1: $H_2O(l) \\rightarrow H_2O(g)$. $\\Delta H = -241,8 - (-285,8) = +44,0 \\text{ kJ}$ (Thu nhiệt để bốc hơi)."},
    {"id": "mc-c4-053", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Vận dụng tính chất Tỏa",
     "question": "Khi pha loãng acid $H_2SO_4$ đặc, người ta luôn phải từ từ rót acid vào nước mà tuyệt đối không làm ngược lại. Nguyên nhân chính do nhiệt hóa học là:",
     "choices": ["Quá trình hiđrat hóa (hòa tan) $H_2SO_4$ đặc tỏa ra lượng nhiệt cực kì lớn và đột ngột làm sôi nước", "Phản ứng thu nhiệt làm đóng băng nước", "Để acid không phản ứng với bình", "Để nhìn thấy rõ dòng acid"],
     "answer": 0, "explanation": "$\\Delta H_{hòa \\tan}$ của H2SO4 đặc rất âm (tỏa nhiệt rất mạnh). Rót nước vào acid $\\Rightarrow$ lượng nhỏ nước sôi đột ngột, nổ bắn acid ra ngoài. Rót acid vào lượng lớn nước $\\Rightarrow$ nước hấp thu nhiệt từ từ, an toàn."},
    {"id": "mc-c4-054", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Năng lượng lk đa",
     "question": "Tính năng lượng liên kết $N\\equiv N$ (kJ/mol) trong $N_2$. Biết PƯ $N_2 + 3H_2 \\rightarrow 2NH_3$ có $\\Delta H = -92 \\text{ kJ}$. Cho $E_b(H-H) = 436 \\text{ kJ/mol}$, $E_b(N-H) = 391 \\text{ kJ/mol}$.",
     "choices": ["946", "391", "46", "892"],
     "answer": 0, "explanation": "$\\Delta H = E(N\\equiv N) + 3 E(H-H) - 2 \\times 3 E(N-H) = -92$. $\\Rightarrow x + 3 \\times 436 - 6 \\times 391 = -92 \Rightarrow x + 1308 - 2346 = -92 \Rightarrow x - 1038 = -92 \Rightarrow x = 946 \\text{ kJ/mol}$."},
    {"id": "mc-c4-055", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tìm CT phân tử dựa vào nhiệt",
     "question": "Đốt cháy 1 mol Alkane X ($C_n H_{2n+2}$) ở thể khí tỏa ra 2040 kJ nhiệt lượng. Biết $\\Delta_f H(CO_2) = -393,5$, $\\Delta_f H(H_2O, g) = -241,8$. Năng lượng tạo thành $C_n H_{2n+2}$ có $\\Delta_f H = -104,7 \\text{ kJ/mol}$. Tính n?",
     "choices": ["3", "2", "4", "5"],
     "answer": 0, "explanation": "Dùng công thức tính: $\\Delta H = n(-393,5) + (n+1)(-241,8) - (-104,7) = -2040 \\Rightarrow n=3$."},

    {"id": "mc-c4-056", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Khái niệm biến thiên",
     "question": "Kí hiệu chữ '0' và '298' trong biểu thức $\\Delta_r H^0_{298}$ mang ý nghĩa gì?",
     "choices": ["'0' chỉ điều kiện chuẩn (Standard), '298' chỉ nhiệt độ 298 Kelvin ($25^\\circ\\text{C}$)", "'0' chỉ nhiệt độ $0^\\circ\\text{C}$, '298' là áp suất", "'0' là nhiệt lượng ban đầu bằng không", "Không có ý nghĩa cụ thể"],
     "answer": 0, "explanation": "Số '0' (thực ra là kí hiệu độ, đọc là naught/standard) báo hiệu áp suất $1 \\text{ bar}$ và nồng độ 1M. 298 là nhiệt độ Kelvin."},
    {"id": "mc-c4-057", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Bản chất năng lượng liên kết",
     "question": "Vì sao khi một liên kết hóa học được hình thành (từ các nguyên tử cô lập), quá trình này luôn TỎA NHIỆT?",
     "choices": ["Vì các nguyên tử cô lập đi từ trạng thái năng lượng cao (kém bền) xuống trạng thái có liên kết mang năng lượng thấp hơn (bền vững hơn), phần năng lượng dư thừa bị phát xạ ra ngoài", "Vì có sự cọ xát giữa các electron", "Vì liên kết hóa học có sinh ra ngọn lửa", "Vì theo định luật bảo toàn khối lượng"],
     "answer": 0, "explanation": "Tạo liên kết $\\rightarrow$ Bền hơn $\\rightarrow$ Năng lượng thế năng của hệ giảm $\\rightarrow$ Phần chênh lệch bức xạ ra môi trường (Tỏa nhiệt). Ngược lại bẻ gãy liên kết $\\rightarrow$ Kém bền $\\rightarrow$ Bắt buộc phải cung cấp năng lượng từ ngoài vào (Thu nhiệt)."},
    {"id": "mc-c4-058", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Lập PT Nhiệt tạo thành H2SO4",
     "question": "Phương trình nào sau đây đúng với quá trình ứng với Nhiệt tạo thành chuẩn của $H_2SO_4(l)$?",
     "choices": ["$H_2(g) + S(s, \\text{rhombic}) + 2O_2(g) \\rightarrow H_2SO_4(l)$", "$H_2O(l) + SO_3(g) \\rightarrow H_2SO_4(l)$", "$SO_2(g) + H_2O(l) + \\frac{1}{2}O_2(g) \\rightarrow H_2SO_4(l)$", "$2H^+(aq) + SO_4^{2-}(aq) \\rightarrow H_2SO_4(l)$"],
     "answer": 0, "explanation": "Định nghĩa: Từ các ĐƠN CHẤT CƠ BẢN NHẤT. H là từ khí $H_2$, S là từ Lưu huỳnh rắn tà phương (rhombic), Oxi là từ khí $O_2$. Chỉ đáp án A thỏa mãn xuất phát từ các đơn chất thuần túy."},
    {"id": "mc-c4-059", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhiệt phản ứng PƯ dư",
     "question": "Cho phản ứng: $H_2(g) + Cl_2(g) \\rightarrow 2HCl(g) \\quad \\Delta H = -184,6 \\text{ kJ}$. Nếu trộn 2 mol $H_2$ và 1 mol $Cl_2$ vào bình kín rồi kích thích phản ứng hoàn toàn, nhiệt lượng tỏa ra của hệ thống là bao nhiêu?",
     "choices": ["184,6 kJ", "369,2 kJ", "92,3 kJ", "553,8 kJ"],
     "answer": 0, "explanation": "Phản ứng bị giới hạn bởi 1 mol Cl2 (vừa đúng hệ số 1 của phương trình), do đó lượng nhiệt tỏa ra là 184,6 kJ (H2 dư không tính)."},
    {"id": "mc-c4-060", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Tổng quan Enthalpy",
     "question": "Đại lượng Enthalpy (H) của một hệ thống nhiệt động biểu thị cho:",
     "choices": ["Nhiệt hàm của hệ, đo lường tổng mức năng lượng dự trữ bên trong hệ thống ở áp suất không đổi", "Động năng di chuyển của các phân tử", "Vận tốc phản ứng", "Nhiệt độ của môi trường"],
     "answer": 0, "explanation": "Enthalpy H (Heat content / Nhiệt hàm) là tổng năng lượng dự trữ, bao gồm nội năng U và công giãn nở P.V. Thực tế ta không thể đo tuyệt đối H, mà chỉ đo được SỰ BIẾN THIÊN $\\Delta H$ (hiệu ứng nhiệt của phản ứng)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C4 Part 1 written successfully.")
