import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 1: ĐỐI TƯỢNG VÀ MỤC TIÊU CỦA VẬT LÍ ---
    # Nhóm 1: Đối tượng nghiên cứu
    {"id": "mc-c1-001", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Đối tượng nghiên cứu của Vật lí",
     "question": "Đối tượng nghiên cứu chính của Vật lí học là gì?",
     "choices": ["Các dạng vận động của vật chất và năng lượng", "Các phản ứng biến đổi chất này thành chất khác", "Sự hình thành và phát triển của sinh vật", "Cấu tạo phân tử của các hợp chất hữu cơ"],
     "answer": 0, "explanation": "Vật lí học nghiên cứu về vật chất, năng lượng và sự vận động của chúng. Các đáp án khác thuộc về Hóa học hoặc Sinh học."},
    {"id": "mc-c1-002", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Đối tượng nghiên cứu của Vật lí",
     "question": "Lĩnh vực nào sau đây KHÔNG thuộc phạm vi nghiên cứu của Vật lí?",
     "choices": ["Sự lai tạo các giống cây trồng mới", "Chuyển động của các hành tinh", "Sự truyền ánh sáng trong cáp quang", "Hiện tượng phóng xạ của hạt nhân"],
     "answer": 0, "explanation": "Lai tạo giống thuộc về Sinh học (di truyền học), không phải Vật lí."},
    {"id": "mc-c1-003", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Đối tượng nghiên cứu của Vật lí",
     "question": "Nghiên cứu về cơ chế truyền nhiệt của một vật liệu cách nhiệt mới thuộc về phân ngành nào của Vật lí?",
     "choices": ["Nhiệt học", "Cơ học", "Quang học", "Điện từ học"],
     "answer": 0, "explanation": "Cơ chế truyền nhiệt liên quan trực tiếp đến phân ngành Nhiệt học (Nhiệt động lực học)."},
    {"id": "mc-c1-004", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Đối tượng nghiên cứu của Vật lí",
     "question": "Một kĩ sư thiết kế vỏ xe đua F1 sao cho lực cản của không khí là nhỏ nhất. Công việc này ứng dụng kiến thức của lĩnh vực nào trong Vật lí?",
     "choices": ["Khí động học (Cơ học chất lưu)", "Nhiệt động lực học", "Vật lí hạt nhân", "Quang hình học"],
     "answer": 0, "explanation": "Khí động học nghiên cứu sự chuyển động của chất khí và tác dụng lực của nó lên vật thể chuyển động trong đó, rất quan trọng trong thiết kế xe đua."},
    
    # Nhóm 2: Mục tiêu của Vật lí
    {"id": "mc-c1-005", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Mục tiêu của Vật lí",
     "question": "Mục tiêu cơ bản nhất của Vật lí học là gì?",
     "choices": ["Khám phá ra quy luật tổng quát nhất chi phối sự vận động của vật chất và năng lượng", "Chế tạo ra các cỗ máy hoạt động với hiệu suất 100%", "Tìm ra các nguyên tố hóa học mới trên Trái Đất", "Giải quyết các bài toán về cấu trúc tế bào sinh vật"],
     "answer": 0, "explanation": "Mục tiêu tối thượng là tìm ra quy luật chi phối tự nhiên. Hiệu suất 100% là vi phạm định luật 2 Nhiệt động lực học."},
    {"id": "mc-c1-006", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Mục tiêu của Vật lí",
     "question": "Trong việc dự báo thời tiết, Vật lí đóng vai trò gì?",
     "choices": ["Cung cấp các mô hình dòng chảy và truyền nhiệt của khí quyển", "Xác định sự thay đổi màu sắc của mây", "Tính toán chi phí sản xuất năng lượng mặt trời", "Phân tích thành phần hóa học của nước mưa"],
     "answer": 0, "explanation": "Khí tượng học ứng dụng cơ học chất lưu và nhiệt động lực học để dự báo thời tiết thông qua các mô hình toán lí."},
    {"id": "mc-c1-007", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Mục tiêu của Vật lí",
     "question": "Khi nghiên cứu về sóng điện từ, việc Maxwell chỉ ra ánh sáng cũng là một dạng sóng điện từ thể hiện mục tiêu nào của Vật lí?",
     "choices": ["Hợp nhất các quy luật vật lí (Điện, Từ, Quang)", "Bác bỏ hoàn toàn các lí thuyết cũ", "Chỉ mang tính chất lí thuyết, không có tính ứng dụng", "Chứng minh ánh sáng không mang năng lượng"],
     "answer": 0, "explanation": "Việc Maxwell chỉ ra ánh sáng là sóng điện từ đã hợp nhất hai lĩnh vực Điện-Từ học và Quang học thành một lí thuyết thống nhất, đây là mục tiêu lớn của Vật lí."},
    {"id": "mc-c1-008", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Mục tiêu của Vật lí",
     "question": "Tại sao không có một định luật Vật lí nào được coi là 'đúng tuyệt đối' cho mọi thời đại?",
     "choices": ["Vì khoa học luôn phát triển, các định luật luôn có giới hạn áp dụng và có thể bị thay thế/mở rộng", "Vì Vật lí dựa trên cảm tính chủ quan", "Vì máy móc đo lường luôn bị hỏng", "Vì các nhà Vật lí luôn mâu thuẫn với nhau"],
     "answer": 0, "explanation": "Vật lí là môn khoa học thực nghiệm. Một định luật (như Cơ học Newton) có thể rất chính xác ở thế giới vĩ mô, nhưng lại không đúng ở thế giới lượng tử hoặc ở vận tốc gần ánh sáng (Thuyết Tương đối)."},

    # Nhóm 3: Phương pháp nghiên cứu
    {"id": "mc-c1-009", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Phương pháp thực nghiệm",
     "question": "Galileo Galilei được coi là cha đẻ của phương pháp nghiên cứu nào trong Vật lí?",
     "choices": ["Phương pháp thực nghiệm", "Phương pháp mô hình", "Phương pháp suy luận logic tuần túy", "Phương pháp thống kê"],
     "answer": 0, "explanation": "Galileo là người đầu tiên đặt nền móng cho phương pháp thực nghiệm, dùng thí nghiệm để kiểm chứng giả thuyết (ví dụ thí nghiệm rơi tự do ở tháp Pisa)."},
    {"id": "mc-c1-010", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Phương pháp mô hình",
     "question": "Trong Vật lí, 'chất điểm' là một ví dụ về:",
     "choices": ["Mô hình vật chất", "Mô hình lí thuyết", "Mô hình toán học", "Mô hình thực nghiệm"],
     "answer": 0, "explanation": "Chất điểm là việc bỏ qua kích thước của vật (khi kích thước rất nhỏ so với quãng đường), đây là một mô hình vật chất lí tưởng hóa."},
    {"id": "mc-c1-011", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Phương pháp nghiên cứu",
     "question": "Quá trình nghiên cứu bằng phương pháp thực nghiệm thường bắt đầu bằng bước nào?",
     "choices": ["Quan sát, xác định đối tượng cần nghiên cứu", "Đề xuất giả thuyết", "Thiết kế thí nghiệm", "Xử lí số liệu"],
     "answer": 0, "explanation": "Bước đầu tiên của phương pháp khoa học luôn là quan sát hiện tượng và xác định vấn đề cần nghiên cứu, từ đó mới đề xuất giả thuyết."},
    {"id": "mc-c1-012", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Phương pháp nghiên cứu",
     "question": "Khi nghiên cứu về chuyển động rơi, Aristotle cho rằng 'vật nặng rơi nhanh hơn vật nhẹ', trong khi Galileo cho rằng 'mọi vật rơi nhanh như nhau nếu bỏ qua lực cản'. Sự khác biệt lớn nhất trong cách tiếp cận của hai ông là gì?",
     "choices": ["Galileo tiến hành thí nghiệm để kiểm chứng, còn Aristotle chỉ suy luận bằng trực giác", "Aristotle làm thí nghiệm nhiều hơn Galileo", "Galileo sử dụng toán học giải tích phức tạp", "Aristotle có các thiết bị đo chính xác hơn"],
     "answer": 0, "explanation": "Aristotle hoàn toàn dựa vào suy luận chủ quan (trực giác), trong khi Galileo dùng thực nghiệm (thả vật từ tháp nghiêng Pisa hoặc trên mặt phẳng nghiêng) để đo đạc và kiểm chứng."},

    # Nhóm 4, 5, 6: Các phương pháp mô hình, ảnh hưởng của Vật lí... (tiếp tục b1)
    {"id": "mc-c1-013", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Phương pháp mô hình",
     "question": "Để tính quỹ đạo của Trái Đất quay quanh Mặt Trời, người ta coi Trái Đất là một chất điểm. Thao tác này thuộc phương pháp nào?",
     "choices": ["Phương pháp mô hình", "Phương pháp thực nghiệm", "Phương pháp thống kê", "Phương pháp quy nạp"],
     "answer": 0, "explanation": "Việc coi một vật có kích thước khổng lồ thành một 'chất điểm' (bỏ qua kích thước, giữ lại khối lượng) là một thao tác lí tưởng hóa, thuộc phương pháp mô hình vật chất."},
    {"id": "mc-c1-014", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Phương pháp mô hình",
     "question": "Đồ thị vận tốc - thời gian (v-t) mô tả chuyển động của một xe ô tô là loại mô hình nào?",
     "choices": ["Mô hình toán học", "Mô hình vật chất", "Mô hình lí thuyết", "Mô hình không gian"],
     "answer": 0, "explanation": "Đồ thị, phương trình, công thức (như v = v0 + at) là các biểu diễn bằng toán học để mô tả các quy luật vật lí, được gọi là mô hình toán học."},
    {"id": "mc-c1-015", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Ảnh hưởng của Vật lí",
     "question": "Cuộc cách mạng công nghiệp lần thứ nhất gắn liền với thành tựu Vật lí nào?",
     "choices": ["Sự ra đời của động cơ hơi nước (Nhiệt động lực học)", "Sự phát minh ra máy phát điện", "Sự xuất hiện của máy tính điện tử", "Sự ra đời của Internet"],
     "answer": 0, "explanation": "Động cơ hơi nước (thế kỷ 18) là cốt lõi của CMCN lần thứ nhất, thay thế sức lao động chân tay."},
    {"id": "mc-c1-016", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Ảnh hưởng của Vật lí",
     "question": "Định vị toàn cầu GPS trên điện thoại di động là ứng dụng trực tiếp của những thành tựu Vật lí nào?",
     "choices": ["Sóng điện từ và Thuyết tương đối", "Nhiệt động lực học và Cơ học chất lưu", "Vật lí hạt nhân và Phóng xạ", "Quang hình học và Quang học lượng tử"],
     "answer": 0, "explanation": "GPS dùng sóng điện từ để truyền tín hiệu từ vệ tinh. Ngoài ra, đồng hồ trên vệ tinh phải được hiệu chỉnh theo Thuyết tương đối (của Einstein) do vệ tinh chuyển động nhanh và ở xa Trái Đất."},

    # --- BÀI 2: AN TOÀN TRONG PHÒNG THỰC HÀNH ---
    # Nhóm 7: Biển cảnh báo
    {"id": "mc-c1-017", "chapter": "c1", "lesson": "b2", "level": "nb", "dang": "An toàn phòng thực hành",
     "question": "Biển báo có hình tam giác đều, viền đen, nền vàng, bên trong có hình một tia sét tượng trưng cho điều gì?",
     "choices": ["Cảnh báo nguy hiểm điện", "Cảnh báo chất độc", "Cảnh báo chất dễ cháy", "Khu vực cấm lửa"],
     "answer": 0, "explanation": "Biển tam giác nền vàng là biển cảnh báo nguy hiểm. Hình tia sét là cảnh báo điện giật."},
    {"id": "mc-c1-018", "chapter": "c1", "lesson": "b2", "level": "nb", "dang": "An toàn phòng thực hành",
     "question": "Biển báo hình tròn, viền đỏ, nền trắng, vạch chéo màu đỏ mang ý nghĩa gì?",
     "choices": ["Biển cấm", "Biển cảnh báo nguy hiểm", "Biển bắt buộc thực hiện", "Biển chỉ dẫn"],
     "answer": 0, "explanation": "Theo chuẩn quốc tế, hình tròn viền đỏ có vạch chéo là biểu tượng của việc Cấm một hành động nào đó."},
    {"id": "mc-c1-019", "chapter": "c1", "lesson": "b2", "level": "th", "dang": "An toàn phòng thực hành",
     "question": "Trong phòng thực hành, hành động nào sau đây là KHÔNG an toàn?",
     "choices": ["Dùng tay trần chạm vào các linh kiện khi mạch điện đang có điện", "Rửa tay sạch sẽ sau khi làm thí nghiệm", "Đọc kĩ hướng dẫn sử dụng trước khi bật máy", "Mặc áo choàng và đeo kính bảo hộ"],
     "answer": 0, "explanation": "Chạm tay vào mạch đang có điện có nguy cơ bị điện giật cao. Phải ngắt nguồn trước khi điều chỉnh mạch."},
    {"id": "mc-c1-020", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "An toàn phòng thực hành",
     "question": "Khi sử dụng đồng hồ vạn năng (multimeter) để đo dòng điện, thao tác nào sau đây có thể làm HỎNG thiết bị?",
     "choices": ["Chọn nhầm thang đo ampe kế rồi mắc song song với linh kiện cần đo", "Mắc nối tiếp ampe kế vào mạch cần đo", "Chọn thang đo lớn nhất lúc bắt đầu đo", "Ngắt nguồn trước khi chuyển đổi thang đo"],
     "answer": 0, "explanation": "Ampe kế có điện trở rất nhỏ. Nếu mắc song song với linh kiện (giống như cách mắc vôn kế), nó sẽ tạo ra hiện tượng đoản mạch, dòng điện qua ampe kế quá lớn làm đứt cầu chì hoặc cháy đồng hồ."},
    
    # Nhóm 8, 9, 10: Các tình huống an toàn điện và hóa chất trong Vật lí
    {"id": "mc-c1-021", "chapter": "c1", "lesson": "b2", "level": "nb", "dang": "An toàn điện",
     "question": "Để đảm bảo an toàn điện, trên các thiết bị thí nghiệm có vỏ bằng kim loại, người ta thường làm gì?",
     "choices": ["Nối đất (tiếp địa) cho vỏ kim loại", "Sơn màu đỏ cho dễ nhìn", "Bọc thêm một lớp kim loại khác", "Ngâm thiết bị vào nước trước khi dùng"],
     "answer": 0, "explanation": "Nối đất (tiếp địa) giúp truyền dòng điện rò rỉ xuống đất, ngăn ngừa điện giật khi người chạm vào vỏ thiết bị bị chạm mạch."},
    {"id": "mc-c1-022", "chapter": "c1", "lesson": "b2", "level": "th", "dang": "An toàn nhiệt",
     "question": "Khi làm thí nghiệm về sự nở vì nhiệt, việc nung nóng quả cầu kim loại bằng đèn cồn cần lưu ý điều gì nhất?",
     "choices": ["Không được chạm tay trực tiếp vào quả cầu ngay cả khi vừa tắt đèn cồn", "Phải thổi thật mạnh để tắt đèn cồn", "Đổ thêm cồn ngay khi đèn đang cháy để lửa to hơn", "Ngâm ngay quả cầu đang nung đỏ vào nước đá để tiết kiệm thời gian"],
     "answer": 0, "explanation": "Kim loại truyền và giữ nhiệt rất tốt. Chạm tay vào sẽ gây bỏng nặng. Tắt đèn cồn phải dùng nắp đậy, cấm thổi. Không đổ cồn khi lửa đang cháy. Ngâm nước đá đột ngột có thể làm nứt hỏng dụng cụ."},
    {"id": "mc-c1-023", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "An toàn phòng thí nghiệm",
     "question": "Một bạn học sinh bị hóa chất văng vào mắt khi đang làm thực hành. Hành động sơ cứu ĐÚNG NHẤT ngay lúc đó là gì?",
     "choices": ["Lập tức rửa mắt dưới vòi nước sạch liên tục trong ít nhất 15 phút và báo cho giáo viên", "Lấy tay dụi mắt liên tục để hóa chất chảy ra", "Nhỏ thuốc nhỏ mắt V-Rohto", "Chạy ngay đi tìm phòng y tế mà không làm gì thêm"],
     "answer": 0, "explanation": "Rửa mắt ngay dưới vòi nước chảy là sơ cứu cơ bản và quan trọng nhất để pha loãng và loại bỏ hóa chất khỏi mắt, tránh tổn thương giác mạc."},
    {"id": "mc-c1-024", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "An toàn đo lường",
     "question": "Khi cắm một mỏ hàn điện loại 220V vào nguồn điện thực hành, nếu nguồn điện ghi 'Output: 12V - 3A', hiện tượng gì sẽ xảy ra?",
     "choices": ["Mỏ hàn sẽ không nóng lên đủ để sử dụng", "Mỏ hàn sẽ nổ ngay lập tức", "Mỏ hàn sẽ nóng chảy vì dòng điện quá mạnh", "Cầu chì của phòng thực hành chắc chắn sẽ đứt"],
     "answer": 0, "explanation": "Mỏ hàn 220V có điện trở lớn ($R = U^2/P$). Khi cắm vào nguồn chỉ 12V, công suất tỏa nhiệt $P = U^2/R$ sẽ rất rất nhỏ, nên mỏ hàn gần như không nóng."},

    # --- BÀI 3: ĐƠN VỊ VÀ SAI SỐ TRONG VẬT LÍ ---
    # Nhóm 11: Hệ đơn vị SI cơ bản
    {"id": "mc-c1-025", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Hệ đơn vị SI",
     "question": "Trong hệ SI, có bao nhiêu đơn vị cơ bản?",
     "choices": ["7", "6", "5", "8"],
     "answer": 0, "explanation": "Hệ SI quy định 7 đơn vị cơ bản: mét, kilôgam, giây, ampe, kelvin, mol, candela."},
    {"id": "mc-c1-026", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Hệ đơn vị SI",
     "question": "Đơn vị nào sau đây KHÔNG phải là đơn vị cơ bản của hệ SI?",
     "choices": ["Newton (N)", "Kilôgam (kg)", "Giây (s)", "Kelvin (K)"],
     "answer": 0, "explanation": "Newton (N) là đơn vị dẫn xuất, nó được định nghĩa từ các đơn vị cơ bản: $1\\text{ N} = 1\\text{ kg}\\cdot\\text{m/s}^2$."},
    {"id": "mc-c1-027", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Hệ đơn vị SI",
     "question": "Kí hiệu đơn vị của cường độ dòng điện và cường độ sáng trong hệ SI lần lượt là:",
     "choices": ["A và cd", "I và L", "V và cd", "A và lx"],
     "answer": 0, "explanation": "Cường độ dòng điện là Ampe (A), cường độ sáng là Candela (cd). Kí hiệu 'lx' là lux (đơn vị độ rọi - dẫn xuất)."},
    {"id": "mc-c1-028", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Thứ nguyên",
     "question": "Đại lượng 'Công' ($A = F\\cdot s$) có thứ nguyên là gì? (Kí hiệu khối lượng M, chiều dài L, thời gian T)",
     "choices": ["$M\\cdot L^2\\cdot T^{-2}$", "$M\\cdot L\\cdot T^{-2}$", "$M\\cdot L^2\\cdot T^{-1}$", "$L\\cdot T^{-1}$"],
     "answer": 0, "explanation": "Lực $F$ có thứ nguyên là $[M][L][T]^{-2}$. Quãng đường $s$ có thứ nguyên $[L]$. Vậy Công = Lực $\\times$ Quãng đường $\\Rightarrow [M][L]^2[T]^{-2}$."},

    # Nhóm 12: Đổi đơn vị
    {"id": "mc-c1-029", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Đổi đơn vị",
     "question": "Tiếp đầu ngữ 'micro' (kí hiệu $\\mu$) tương ứng với hệ số nhân bằng bao nhiêu?",
     "choices": ["$10^{-6}$", "$10^{-3}$", "$10^{-9}$", "$10^{6}$"],
     "answer": 0, "explanation": "mili là $10^{-3}$, micro là $10^{-6}$, nano là $10^{-9}$, mega là $10^{6}$."},
    {"id": "mc-c1-030", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Đổi đơn vị",
     "question": "$72\\text{ km/h}$ tương đương với bao nhiêu $\\text{m/s}$?",
     "choices": ["$20\\text{ m/s}$", "$25\\text{ m/s}$", "$15\\text{ m/s}$", "$72000\\text{ m/s}$"],
     "answer": 0, "explanation": "Quy tắc: Chia cho 3,6. Vậy $72 / 3.6 = 20\\text{ m/s}$. ($72\\text{ km} = 72000\\text{ m}$; $1\\text{ h} = 3600\\text{ s}$; $72000/3600 = 20$)."},
    {"id": "mc-c1-031", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Thứ nguyên",
     "question": "Biết phương trình vận tốc theo thời gian là $v = At^2 + Bt$. Thứ nguyên của hằng số $A$ là gì?",
     "choices": ["$L\\cdot T^{-3}$", "$L\\cdot T^{-2}$", "$L\\cdot T^{-1}$", "$M\\cdot L\\cdot T^{-3}$"],
     "answer": 0, "explanation": "Thứ nguyên của $v$ là $[L][T]^{-1}$. Các số hạng trong phương trình cộng lại phải cùng thứ nguyên $\\Rightarrow$ Thứ nguyên của $At^2$ phải là $[L][T]^{-1}$. Do $t^2$ có thứ nguyên $[T]^2$, nên $A$ có thứ nguyên là $[L][T]^{-1} / [T]^2 = [L][T]^{-3}$."},
    {"id": "mc-c1-032", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Đổi đơn vị phức tạp",
     "question": "Khối lượng riêng của nước là $1\\text{ g/cm}^3$. Giá trị này tính theo hệ SI (chuẩn $\\text{kg/m}^3$) là:",
     "choices": ["$1000\\text{ kg/m}^3$", "$100\\text{ kg/m}^3$", "$1\\text{ kg/m}^3$", "$10\\text{ kg/m}^3$"],
     "answer": 0, "explanation": "$1\\text{ g} = 10^{-3}\\text{ kg}$; $1\\text{ cm}^3 = 10^{-6}\\text{ m}^3$. Do đó $1\\text{ g/cm}^3 = \\frac{10^{-3}}{10^{-6}}\\text{ kg/m}^3 = 1000\\text{ kg/m}^3$."},

    # Nhóm 13: Các loại sai số
    {"id": "mc-c1-033", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Các loại sai số",
     "question": "Sai số nào do dụng cụ không được hiệu chỉnh chuẩn (ví dụ kim cân không chỉ số 0 khi chưa cân)?",
     "choices": ["Sai số hệ thống", "Sai số ngẫu nhiên", "Sai số tuyệt đối", "Sai số tỉ đối"],
     "answer": 0, "explanation": "Sai số do cấu tạo dụng cụ, hoặc do không hiệu chỉnh điểm 0 luôn làm kết quả lệch về một phía, được gọi là sai số hệ thống."},
    {"id": "mc-c1-034", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Các loại sai số",
     "question": "Sai số ngẫu nhiên là gì?",
     "choices": ["Sai số không có nguyên nhân rõ ràng, gây ra bởi những thay đổi nhỏ không kiểm soát được trong mỗi lần đo", "Sai số luôn làm kết quả lớn hơn giá trị thực", "Sai số do người đo đọc sai vạch chia một cách cố ý", "Sai số có thể loại bỏ hoàn toàn nếu dùng máy móc xịn"],
     "answer": 0, "explanation": "Sai số ngẫu nhiên sinh ra do điều kiện đo lường không bao giờ ổn định tuyệt đối (gió, run tay, dao động nhiệt...). Dù máy xịn đến đâu cũng vẫn tồn tại sai số ngẫu nhiên ở các số thập phân siêu nhỏ."},
    {"id": "mc-c1-035", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Các loại sai số",
     "question": "Để giảm thiểu sai số ngẫu nhiên, người ta thường dùng phương pháp nào?",
     "choices": ["Đo nhiều lần và lấy giá trị trung bình", "Hiệu chỉnh lại điểm 0 của dụng cụ", "Chỉ cần đo một lần bằng thiết bị điện tử", "Thay đổi người đo liên tục"],
     "answer": 0, "explanation": "Sai số ngẫu nhiên có tính dao động 2 chiều (lúc lớn hơn, lúc nhỏ hơn giá trị thực). Việc đo nhiều lần và tính trung bình sẽ giúp triệt tiêu bớt các dao động này."},
    {"id": "mc-c1-036", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Các loại sai số",
     "question": "Một cái thước kẹp ghi sai số dụng cụ là $\\Delta x_{dc} = 0,02\\text{ mm}$. Sai số này thuộc loại sai số nào?",
     "choices": ["Sai số hệ thống", "Sai số ngẫu nhiên", "Sai số tỉ đối", "Sai số chủ quan"],
     "answer": 0, "explanation": "Sai số dụng cụ là giới hạn độ chính xác do nhà sản xuất chế tạo, nó mang tính cố định của thiết bị, do đó được xếp vào nhóm sai số hệ thống."},

    # Nhóm 14: Cách tính sai số trực tiếp
    {"id": "mc-c1-037", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Tính sai số đo trực tiếp",
     "question": "Kết quả đo lường một đại lượng $A$ thường được viết dưới dạng nào?",
     "choices": ["$A = \\bar{A} \\pm \\Delta A$", "$A = \\bar{A} + \\Delta A$", "$A = \\Delta A \\pm \\bar{A}$", "$A = \\bar{A} \\pm \\delta A$"],
     "answer": 0, "explanation": "Kết quả đo ghi bằng giá trị trung bình $\\bar{A}$ cộng trừ sai số tuyệt đối $\\Delta A$."},
    {"id": "mc-c1-038", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Tính sai số đo trực tiếp",
     "question": "Công thức tính sai số tuyệt đối của phép đo đại lượng $A$ gồm nhiều lần đo là:",
     "choices": ["$\\Delta A = \\overline{\\Delta A} + \\Delta A_{dc}$", "$\\Delta A = \\overline{\\Delta A} \\times \\Delta A_{dc}$", "$\\Delta A = \\Delta A_1 + \\Delta A_2 + ...$", "$\\Delta A = \\overline{\\Delta A} - \\Delta A_{dc}$"],
     "answer": 0, "explanation": "Sai số tuyệt đối của phép đo bằng tổng của sai số ngẫu nhiên trung bình $\\overline{\\Delta A}$ và sai số dụng cụ $\\Delta A_{dc}$."},
    {"id": "mc-c1-039", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Tính sai số đo trực tiếp",
     "question": "Đo 5 lần thời gian rơi của một vật được các giá trị: 0,40s; 0,42s; 0,39s; 0,41s; 0,38s. Giá trị trung bình $\\bar{t}$ là bao nhiêu?",
     "choices": ["0,40s", "0,39s", "0,41s", "0,42s"],
     "answer": 0, "explanation": "$\\bar{t} = (0,40 + 0,42 + 0,39 + 0,41 + 0,38) / 5 = 2,00 / 5 = 0,40$ (s)."},
    {"id": "mc-c1-040", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Tính sai số đo trực tiếp",
     "question": "Tiếp tục với 5 lần đo: 0,40s; 0,42s; 0,39s; 0,41s; 0,38s (có $\\bar{t} = 0,40s$). Bỏ qua sai số dụng cụ. Sai số tuyệt đối của phép đo thời gian này là:",
     "choices": ["0,012s", "0,02s", "0,04s", "0,00s"],
     "answer": 0, "explanation": "Tính sai số của từng lần: $\\Delta t_1 = 0$, $\\Delta t_2 = 0,02$, $\\Delta t_3 = 0,01$, $\\Delta t_4 = 0,01$, $\\Delta t_5 = 0,02$. Trung bình: $\\overline{\\Delta t} = (0 + 0,02 + 0,01 + 0,01 + 0,02) / 5 = 0,06 / 5 = 0,012$ (s)."},

    # Nhóm 15: Chữ số có nghĩa và làm tròn số
    {"id": "mc-c1-041", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Chữ số có nghĩa",
     "question": "Quy tắc xác định chữ số có nghĩa (CSCN) nào sau đây là SAI?",
     "choices": ["Các chữ số 0 ở bên trái chữ số khác 0 đầu tiên đều là CSCN", "Các chữ số khác 0 đều là CSCN", "Các chữ số 0 nằm giữa hai chữ số khác 0 đều là CSCN", "Các chữ số 0 nằm bên phải chữ số khác 0 ở phần thập phân đều là CSCN"],
     "answer": 0, "explanation": "Các số 0 ở bên trái (ví dụ $0,0025$) chỉ để định vị dấu phẩy, KHÔNG phải là CSCN. Số $0,0025$ chỉ có 2 CSCN là 2 và 5."},
    {"id": "mc-c1-042", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Chữ số có nghĩa",
     "question": "Số $0,05040$ có bao nhiêu chữ số có nghĩa?",
     "choices": ["4", "3", "5", "6"],
     "answer": 0, "explanation": "Hai số 0 đầu tiên không tính. Các số $5, 0, 4, 0$ (số 0 cuối cùng nằm bên phải số thập phân nên được tính) là CSCN. Tổng cộng có 4 CSCN."},
    {"id": "mc-c1-043", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Chữ số có nghĩa",
     "question": "Quy tắc làm tròn khi ghi kết quả đo lường với sai số $\\Delta A = 0,0145$ (lấy 1 chữ số có nghĩa cho sai số) thì $\\Delta A$ được viết là:",
     "choices": ["0,01", "0,015", "0,02", "0,014"],
     "answer": 0, "explanation": "Sai số thường được làm tròn tới 1 hoặc 2 chữ số có nghĩa. Ở mức cơ bản phổ thông, nếu lấy 1 CSCN, ta xét số 1 ở hàng phần trăm. Phía sau là số 4 < 5, nên làm tròn thành 0,01."},
    {"id": "mc-c1-044", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Cách ghi kết quả",
     "question": "Nếu giá trị trung bình là $\\bar{v} = 12,3456$ và sai số là $\\Delta v = 0,02$ thì kết quả đo nên được ghi như thế nào?",
     "choices": ["$v = 12,35 \\pm 0,02$", "$v = 12,3456 \\pm 0,02$", "$v = 12,3 \\pm 0,02$", "$v = 12,34 \\pm 0,02$"],
     "answer": 0, "explanation": "Vì sai số nằm ở hàng phần trăm (0,02), nên giá trị trung bình phải được quy tròn đến hàng phần trăm. Số sau hàng phần trăm là 5, nên $12,3456$ làm tròn thành $12,35$. Kết quả: $12,35 \\pm 0,02$."},
    
    # Nhóm 16: Sai số tương đối (Sai số tỉ đối)
    {"id": "mc-c1-045", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Sai số tỉ đối",
     "question": "Sai số tỉ đối (sai số tương đối) $\\delta A$ được tính bằng công thức:",
     "choices": ["$\\delta A = \\frac{\\Delta A}{\\bar{A}} \\cdot 100\\%$", "$\\delta A = \\frac{\\bar{A}}{\\Delta A} \\cdot 100\\%$", "$\\delta A = \\Delta A - \\bar{A}$", "$\\delta A = \\Delta A + \\bar{A}$"],
     "answer": 0, "explanation": "Sai số tỉ đối là tỉ số giữa sai số tuyệt đối và giá trị trung bình, thường tính theo phần trăm."},
    {"id": "mc-c1-046", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Sai số tỉ đối",
     "question": "Phép đo 1: $l_1 = 10,0 \\pm 0,1\\text{ m}$. Phép đo 2: $l_2 = 1,00 \\pm 0,05\\text{ m}$. Phép đo nào chính xác hơn?",
     "choices": ["Phép đo 1 chính xác hơn vì sai số tỉ đối nhỏ hơn", "Phép đo 2 chính xác hơn vì sai số tuyệt đối nhỏ hơn", "Hai phép đo chính xác như nhau", "Không thể so sánh được"],
     "answer": 0, "explanation": "Độ chính xác của phép đo được đánh giá qua sai số tỉ đối. $\\delta_1 = 0,1 / 10 = 1\\%$. $\\delta_2 = 0,05 / 1 = 5\\%$. Phép đo 1 có sai số tỉ đối nhỏ hơn nên chính xác hơn."},
    {"id": "mc-c1-047", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Sai số gián tiếp",
     "question": "Đo diện tích hình chữ nhật $S = a \\cdot b$. Biết sai số tỉ đối của các phép đo chiều dài $a$ là $2\\%$ và chiều rộng $b$ là $3\\%$. Sai số tỉ đối của phép đo diện tích S là:",
     "choices": ["5%", "1%", "6%", "1.5%"],
     "answer": 0, "explanation": "Khi một đại lượng tính bằng phép nhân (hoặc chia), sai số tỉ đối của kết quả bằng TỔNG các sai số tỉ đối của các đại lượng thành phần. $\\delta S = \\delta a + \\delta b = 2\\% + 3\\% = 5\\%$."},
    {"id": "mc-c1-048", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Sai số gián tiếp",
     "question": "Tính thể tích một viên bi hình cầu $V = \\frac{4}{3}\\pi R^3$. Nếu đo bán kính R với sai số tỉ đối là $1\\%$ thì thể tích V sẽ có sai số tỉ đối là:",
     "choices": ["3%", "1%", "4%", "1/3%"],
     "answer": 0, "explanation": "Sai số tỉ đối của hàm luỹ thừa $A = x^n$ là $\\delta A = n \\cdot \\delta x$. Do đó $\\delta V = 3 \\cdot \\delta R = 3 \\cdot 1\\% = 3\\%$. (Bỏ qua sai số của số $\\pi$)."},

    # Nhóm 17: Tính vận tốc trung bình (Động học sơ bộ)
    {"id": "mc-c1-049", "chapter": "c1", "lesson": "b4", "level": "nb", "dang": "Độ dịch chuyển và Quãng đường",
     "question": "Độ dịch chuyển (độ dời) của một vật là:",
     "choices": ["Một đại lượng vectơ nối từ vị trí ban đầu đến vị trí cuối", "Tổng chiều dài quỹ đạo vật đã đi qua", "Luôn là một số dương", "Luôn luôn bằng quãng đường đi được"],
     "answer": 0, "explanation": "Độ dịch chuyển là vectơ $\\Delta \\vec{r} = \\vec{r_2} - \\vec{r_1}$. Quãng đường là chiều dài quỹ đạo (vô hướng)."},
    {"id": "mc-c1-050", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Độ dịch chuyển và Quãng đường",
     "question": "Một người bơi dọc theo chiều dài $50\\text{ m}$ của bể bơi rồi quay lại điểm xuất phát. Độ dịch chuyển và quãng đường bơi được lần lượt là:",
     "choices": ["0 m và 100 m", "100 m và 100 m", "50 m và 100 m", "0 m và 50 m"],
     "answer": 0, "explanation": "Quay về điểm xuất phát nên vị trí đầu trùng vị trí cuối $\\Rightarrow$ độ dịch chuyển = 0. Quãng đường bơi đi và về = 50 + 50 = 100 m."},
    {"id": "mc-c1-051", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Tốc độ và Vận tốc",
     "question": "Tốc độ trung bình và vận tốc trung bình của một vật chuyển động có cùng độ lớn khi nào?",
     "choices": ["Vật chuyển động thẳng và không đổi chiều", "Vật chuyển động tròn đều", "Vật đứng yên", "Vật chuyển động theo bất kì quỹ đạo nào nhưng với tốc độ không đổi"],
     "answer": 0, "explanation": "Khi chuyển động thẳng một chiều (không quay đầu), quãng đường $s$ bằng độ lớn độ dịch chuyển $d$. Do đó $v_{\\text{tb}} = s/t$ bằng độ lớn $\\vec{v}_{\\text{tb}} = d/t$."},
    {"id": "mc-c1-052", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tính Tốc độ trung bình",
     "question": "Một xe đi nửa quãng đường đầu với tốc độ $40\\text{ km/h}$, nửa quãng đường sau với tốc độ $60\\text{ km/h}$. Tốc độ trung bình trên cả quãng đường là:",
     "choices": ["48 km/h", "50 km/h", "24 km/h", "100 km/h"],
     "answer": 0, "explanation": "Bẫy kinh điển: Không được cộng lại chia đôi ($50$). Thời gian đi nửa đầu $t_1 = (S/2)/40$. Nửa sau $t_2 = (S/2)/60$. $v_{\\text{tb}} = S / (t_1 + t_2) = 1 / (1/80 + 1/120) = 48\\text{ km/h}."},
    
    # Nhóm 18: Tính Vận tốc trung bình vectơ
    {"id": "mc-c1-053", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tính Vận tốc trung bình",
     "question": "Một kiến đi từ góc A đến góc B của mặt bàn hình chữ nhật kích thước $30\\text{ cm} \\times 40\\text{ cm}$ theo hai mép bàn (A $\\to$ góc C $\\to$ B) mất 10 giây. Độ lớn vận tốc trung bình của kiến là:",
     "choices": ["5 cm/s", "7 cm/s", "1 cm/s", "50 cm/s"],
     "answer": 0, "explanation": "Vận tốc trung bình tính bằng $\\text{Độ dịch chuyển} / \\text{thời gian}$. Độ dịch chuyển là đường chéo AB $= \\sqrt{30^2 + 40^2} = 50\\text{ cm}$. $v = 50 / 10 = 5\\text{ cm/s}$. (Nếu là tốc độ trung bình thì $s/t = 70/10 = 7\\text{ cm/s}$)."},
    {"id": "mc-c1-054", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Tính Vận tốc trung bình",
     "question": "Một người chạy bộ một vòng sân vận động tròn chu vi 400m mất 1 phút 40 giây. Độ lớn vận tốc trung bình của người đó trong suốt một vòng là:",
     "choices": ["0 m/s", "4 m/s", "40 m/s", "6,67 m/s"],
     "answer": 0, "explanation": "Chạy hết 1 vòng thì về lại điểm xuất phát $\\Rightarrow$ độ dịch chuyển $\\Delta x = 0$. Vận tốc trung bình $= \\Delta x / \\Delta t = 0$. Tốc độ trung bình mới là $400/100 = 4\\text{ m/s}$."},
    {"id": "mc-c1-055", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tốc độ trung bình theo thời gian",
     "question": "Một ô tô đi với tốc độ $60\\text{ km/h}$ trong nửa thời gian đầu và $40\\text{ km/h}$ trong nửa thời gian sau. Tốc độ trung bình trên toàn bộ chuyến đi là:",
     "choices": ["50 km/h", "48 km/h", "24 km/h", "100 km/h"],
     "answer": 0, "explanation": "Khác với bài 'nửa quãng đường'. Ở đây là 'nửa thời gian'. $S_1 = 60 \\cdot (t/2)$, $S_2 = 40 \\cdot (t/2)$. $v_{\\text{tb}} = (S_1 + S_2)/t = (60+40)/2 = 50\\text{ km/h}."},
    {"id": "mc-c1-056", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tổng hợp Quãng đường và Độ dịch chuyển",
     "question": "Một quả bóng được ném thẳng đứng lên cao $5\\text{m}$ từ mặt đất, sau đó rơi xuống và bị bắt lại ở độ cao $2\\text{m}$ so với mặt đất. Quãng đường và độ dịch chuyển của quả bóng là:",
     "choices": ["Quãng đường 8m, độ dịch chuyển hướng lên độ lớn 2m", "Quãng đường 5m, độ dịch chuyển hướng xuống độ lớn 2m", "Quãng đường 8m, độ dịch chuyển hướng xuống độ lớn 3m", "Quãng đường 10m, độ dịch chuyển 0m"],
     "answer": 0, "explanation": "Quãng đường $s = 5\\text{m (lên)} + (5-2)\\text{m (xuống)} = 8\\text{m}$. Vị trí đầu ở mặt đất ($0$), vị trí cuối ở độ cao $+2\\text{m}$. Độ dịch chuyển $= 2 - 0 = +2\\text{m}$ (hướng lên)."}
]

# Write to JSON
for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Part 1 written successfully.")
