import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 5 (TIẾP THEO): CƠ SỞ NHIỆT ĐỘNG LỰC HỌC VÀ CHẤT RẮN, CHẤT LỎNG, CHUYỂN THỂ ---
    # Nhóm 16, 17: Nội năng và Nguyên lí I Nhiệt động lực học
    {"id": "mc-c5-061", "chapter": "c5", "lesson": "b49", "level": "nb", "dang": "Nội năng",
     "question": "Nội năng của một vật là:",
     "choices": ["Tổng động năng và thế năng của các phân tử cấu tạo nên vật", "Tổng động năng và thế năng của vật đó trong trọng trường", "Động năng chuyển động nhiệt của vật", "Nhiệt lượng vật nhận được"],
     "answer": 0, "explanation": "Nội năng (U) là năng lượng BÊN TRONG của vật, gồm động năng chuyển động hỗn loạn của các phân tử và thế năng tương tác giữa các phân tử."},
    {"id": "mc-c5-062", "chapter": "c5", "lesson": "b49", "level": "nb", "dang": "Nội năng khí lí tưởng",
     "question": "Nội năng của khí lí tưởng chỉ phụ thuộc vào thông số nào?",
     "choices": ["Nhiệt độ", "Thể tích", "Áp suất", "Khối lượng riêng"],
     "answer": 0, "explanation": "Khí lí tưởng bỏ qua lực tương tác nên không có thế năng tương tác phân tử. Nội năng chỉ gồm động năng phân tử $\\Rightarrow$ chỉ phụ thuộc vào Nhiệt độ $U = f(T)$."},
    {"id": "mc-c5-063", "chapter": "c5", "lesson": "b49", "level": "th", "dang": "Sự biến thiên nội năng",
     "question": "Có mấy cách làm thay đổi nội năng của một vật?",
     "choices": ["Hai cách: Thực hiện công và Truyền nhiệt", "Một cách: Thực hiện công", "Một cách: Truyền nhiệt", "Ba cách: Thực hiện công, Truyền nhiệt, Bức xạ"],
     "answer": 0, "explanation": "Có 2 cách cơ bản: Thực hiện công (có sự dịch chuyển vĩ mô) và Truyền nhiệt (chỉ có truyền động năng vi mô). (Bức xạ là một hình thức của truyền nhiệt)."},
    {"id": "mc-c5-064", "chapter": "c5", "lesson": "b49", "level": "th", "dang": "Nguyên lí 1 NĐLH",
     "question": "Biểu thức của Nguyên lí I Nhiệt động lực học là $\\Delta U = A + Q$. Theo quy ước dấu, nếu khối khí NHẬN NHIỆT và THỰC HIỆN CÔNG thì:",
     "choices": ["$Q > 0, A < 0$", "$Q > 0, A > 0$", "$Q < 0, A < 0$", "$Q < 0, A > 0$"],
     "answer": 0, "explanation": "Quy ước: Nhận (được cho) thì dương ($>0$), Cho (thực hiện ra ngoài) thì âm ($<0$). Nhận nhiệt $Q > 0$. Thực hiện công đẩy môi trường $A < 0$."},

    {"id": "mc-c5-065", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Áp dụng Nguyên lí 1",
     "question": "Một khối khí lí tưởng nhận nhiệt lượng 2500 J từ nguồn nhiệt và nó giãn nở thực hiện công 1000 J đẩy pittông. Độ biến thiên nội năng của khối khí là:",
     "choices": ["Tăng 1500 J", "Tăng 3500 J", "Giảm 1500 J", "Tăng 2500 J"],
     "answer": 0, "explanation": "Nhận nhiệt $Q = +2500\\text{ J}$. Thực hiện công $A = -1000\\text{ J}$. $\\Delta U = A + Q = -1000 + 2500 = +1500\\text{ J}$ (Nội năng tăng 1500 J)."},
    {"id": "mc-c5-066", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Áp dụng cho đẳng tích",
     "question": "Cung cấp một nhiệt lượng 500J cho một khối khí đựng trong bình thép KÍN (không giãn nở). Sự thay đổi nội năng của khối khí là bao nhiêu?",
     "choices": ["Tăng 500 J", "Không đổi", "Giảm 500 J", "Tăng 250 J"],
     "answer": 0, "explanation": "Bình kín là quá trình đẳng tích $\\Rightarrow \\Delta V = 0 \Rightarrow A = 0$ (khí không sinh công). $\\Delta U = A + Q = 0 + 500 = 500\\text{ J}."},
    {"id": "mc-c5-067", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Áp dụng cho đẳng nhiệt",
     "question": "Trong quá trình nén ĐẲNG NHIỆT một lượng khí lí tưởng, người ta phải thực hiện một công 100J. Lượng khí này:",
     "choices": ["Tỏa ra môi trường nhiệt lượng 100 J", "Nhận vào từ môi trường nhiệt lượng 100 J", "Nội năng tăng thêm 100 J", "Không tỏa cũng không nhận nhiệt"],
     "answer": 0, "explanation": "Đẳng nhiệt $\\Rightarrow \\Delta T = 0 \Rightarrow \\Delta U = 0$ (Nội năng không đổi). Người ta thực hiện công lên khí $\\Rightarrow$ Khí nhận công $A = +100\\text{J}$. $\\Delta U = A + Q = 0 \Rightarrow Q = -100\\text{J}$. (Tỏa nhiệt 100J)."},
    {"id": "mc-c5-068", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Tính công giãn nở",
     "question": "Một khối khí được đun nóng ĐẲNG ÁP ở áp suất $2\\cdot 10^5\\text{ Pa}$. Thể tích khối khí tăng từ 2 lít lên 5 lít. Công mà khối khí thực hiện là:",
     "choices": ["600 J", "-600 J", "1000 J", "400 J"],
     "answer": 0, "explanation": "Khí giãn nở thực hiện công $A' = p\\Delta V = 2\cdot 10^5 \\times (0,005 - 0,002) = 2\cdot 10^5 \times 0,003 = 600\\text{ J}$. (Công khí thực hiện $A'=600$, công khí nhận $A=-600$). Tùy cách hỏi, nếu hỏi \"công khối khí thực hiện\" thì nó là giá trị độ lớn 600 J."},

    # Nhóm 18, 19: Nguyên lí II Nhiệt động lực học
    {"id": "mc-c5-069", "chapter": "c5", "lesson": "b50", "level": "nb", "dang": "Phát biểu Clausius",
     "question": "Phát biểu nào sau đây đúng với Nguyên lí II Nhiệt động lực học (theo Clausius)?",
     "choices": ["Nhiệt không thể TỰ ĐỘNG truyền từ một vật sang một vật nóng hơn", "Nhiệt có thể tự truyền từ vật lạnh sang vật nóng", "Không thể chế tạo động cơ vĩnh cửu loại 1", "Nhiệt lượng luôn truyền từ vật có khối lượng lớn sang vật có khối lượng nhỏ"],
     "answer": 0, "explanation": "Clausius: Quá trình truyền nhiệt tự nhiên chỉ diễn ra theo một chiều (từ nóng sang lạnh). Muốn truyền từ lạnh sang nóng phải tốn công (như tủ lạnh)."},
    {"id": "mc-c5-070", "chapter": "c5", "lesson": "b50", "level": "nb", "dang": "Phát biểu Kelvin",
     "question": "Theo cách phát biểu của Kelvin - Planck về Nguyên lí II Nhiệt động lực học:",
     "choices": ["Động cơ nhiệt không thể chuyển hóa hoàn toàn nhiệt lượng nhận được thành công cơ học", "Hiệu suất của động cơ nhiệt luôn bằng 100%", "Có thể chế tạo động cơ nhiệt không cần nguồn lạnh", "Nhiệt độ của nguồn nóng không ảnh hưởng đến hiệu suất"],
     "answer": 0, "explanation": "Luôn phải có nguồn lạnh để thải nhiệt (tổn hao). Do đó hiệu suất $H < 1$ (không thể chuyển 100% Q thành A)."},
    {"id": "mc-c5-071", "chapter": "c5", "lesson": "b50", "level": "th", "dang": "Hiệu suất động cơ nhiệt",
     "question": "Động cơ nhiệt nhận từ nguồn nóng nhiệt lượng $Q_1$, nhả cho nguồn lạnh nhiệt lượng $Q_2$. Hiệu suất của động cơ nhiệt là:",
     "choices": ["$H = \\frac{Q_1 - Q_2}{Q_1}$", "$H = \\frac{Q_1}{Q_2}$", "$H = \\frac{Q_2}{Q_1}$", "$H = \\frac{Q_1 - Q_2}{Q_2}$"],
     "answer": 0, "explanation": "Công có ích sinh ra $A = Q_1 - Q_2$. Hiệu suất $H = A / Q_{\\text{nhận}} = (Q_1 - Q_2) / Q_1 = 1 - Q_2/Q_1$."},
    {"id": "mc-c5-072", "chapter": "c5", "lesson": "b50", "level": "vd", "dang": "Tính hiệu suất",
     "question": "Một động cơ nhiệt nhận từ nguồn nóng nhiệt lượng 10 kJ và sinh ra một công cơ học 3 kJ. Nhiệt lượng truyền cho nguồn lạnh và hiệu suất của động cơ là:",
     "choices": ["7 kJ và 30%", "7 kJ và 70%", "13 kJ và 30%", "3 kJ và 30%"],
     "answer": 0, "explanation": "$Q_1 = 10\\text{ kJ}, A = 3\\text{ kJ} \Rightarrow Q_2 = Q_1 - A = 7\\text{ kJ}$ thải ra. Hiệu suất $H = A/Q_1 = 3/10 = 30\\%$."},

    # Nhóm 20, 21: Chất rắn kết tinh và Chất rắn vô định hình
    {"id": "mc-c5-073", "chapter": "c5", "lesson": "b51", "level": "nb", "dang": "Phân loại chất rắn",
     "question": "Chất rắn được phân thành hai loại chính nào dựa trên cấu trúc vi mô?",
     "choices": ["Chất rắn kết tinh và chất rắn vô định hình", "Chất rắn đàn hồi và chất rắn dẻo", "Chất rắn kim loại và chất rắn phi kim", "Chất rắn cách điện và dẫn điện"],
     "answer": 0, "explanation": "Dựa vào sự sắp xếp có trật tự hay hỗn độn của các hạt, chất rắn chia thành kết tinh (có cấu trúc mạng tinh thể) và vô định hình (không có mạng tinh thể)."},
    {"id": "mc-c5-074", "chapter": "c5", "lesson": "b51", "level": "nb", "dang": "Tính chất vô định hình",
     "question": "Vật liệu nào sau đây là chất rắn VÔ ĐỊNH HÌNH?",
     "choices": ["Thủy tinh", "Muối ăn (NaCl)", "Kim cương", "Thạch anh"],
     "answer": 0, "explanation": "Thủy tinh, nhựa, cao su... không có cấu trúc mạng tinh thể cố định, chúng là chất rắn vô định hình."},
    {"id": "mc-c5-075", "chapter": "c5", "lesson": "b51", "level": "th", "dang": "Nhiệt độ nóng chảy",
     "question": "Đặc điểm nào sau đây là sự khác biệt cơ bản về tính chất nhiệt giữa chất rắn kết tinh và chất rắn vô định hình?",
     "choices": ["Chất rắn kết tinh có nhiệt độ nóng chảy xác định, chất rắn vô định hình không có nhiệt độ nóng chảy xác định", "Chất rắn vô định hình không thể bị nung chảy", "Chất rắn kết tinh không dẫn nhiệt", "Cả hai đều có nhiệt độ nóng chảy xác định"],
     "answer": 0, "explanation": "Chất rắn kết tinh nóng chảy ở một nhiệt độ cố định $T_{nc}$ dưới áp suất chuẩn. Vô định hình thì mềm dần rồi chảy ra trong 1 dải nhiệt độ dài (vd: thủy tinh, sáp, hắc ín)."},
    {"id": "mc-c5-076", "chapter": "c5", "lesson": "b51", "level": "th", "dang": "Tính dị hướng",
     "question": "Hiện tượng một viên tinh thể thạch anh có tốc độ truyền ánh sáng hoặc độ nở nhiệt khác nhau theo các phương khác nhau gọi là tính gì?",
     "choices": ["Tính dị hướng", "Tính đẳng hướng", "Tính thù hình", "Tính đàn hồi"],
     "answer": 0, "explanation": "Tính dị hướng (Anisotropy) là tính chất vật lí thay đổi tùy theo phương đo. Tinh thể đơn nguyên (đơn tinh thể) thường có tính dị hướng do cấu trúc mạng lưới không đều đặn về mọi hướng."},

    # Nhóm 22, 23: Sự nở vì nhiệt của chất rắn
    {"id": "mc-c5-077", "chapter": "c5", "lesson": "b52", "level": "nb", "dang": "Sự nở dài",
     "question": "Khi nung nóng, chiều dài của một thanh ray đường sắt tăng lên. Sự tăng chiều dài này gọi là:",
     "choices": ["Sự nở dài", "Sự nở khối", "Sự biến dạng dẻo", "Sự co ngót"],
     "answer": 0, "explanation": "Sự nở dài là sự tăng kích thước theo một phương khi nhiệt độ tăng."},
    {"id": "mc-c5-078", "chapter": "c5", "lesson": "b52", "level": "nb", "dang": "Công thức nở dài",
     "question": "Công thức tính độ nở dài $\\Delta l$ của vật rắn (chiều dài ban đầu $l_0$) khi nhiệt độ tăng $\\Delta t$ là: (với $\\alpha$ là hệ số nở dài)",
     "choices": ["$\\Delta l = \\alpha l_0 \\Delta t$", "$\\Delta l = \\alpha l_0 / \\Delta t$", "$\\Delta l = l_0 + \\alpha \\Delta t$", "$\\Delta l = \\frac{\\alpha \\Delta t}{l_0}$"],
     "answer": 0, "explanation": "Độ nở dài tỉ lệ thuận với chiều dài ban đầu và độ tăng nhiệt độ. $\\Delta l = l - l_0 = \\alpha l_0 \\Delta t$."},
    {"id": "mc-c5-079", "chapter": "c5", "lesson": "b52", "level": "vd", "dang": "Tính nở dài",
     "question": "Một thanh nhôm dài 10m ở $20^\\circ\\text{C}$. Hệ số nở dài của nhôm là $\\alpha = 24\\cdot 10^{-6}\\text{ K}^{-1}$. Khi nhiệt độ tăng lên $50^\\circ\\text{C}$, độ nở dài của thanh nhôm là:",
     "choices": ["7,2 mm", "1,2 mm", "2,4 mm", "72 mm"],
     "answer": 0, "explanation": "$\\Delta t = 50 - 20 = 30\\text{ K}$ (hoặc độ C). $\\Delta l = 24\cdot 10^{-6} \times 10 \times 30 = 7200\cdot 10^{-6}\\text{ m} = 0,0072\\text{ m} = 7,2\\text{ mm}."},
    {"id": "mc-c5-080", "chapter": "c5", "lesson": "b52", "level": "vd", "dang": "Sự nở khối",
     "question": "Một quả cầu kim loại bằng đồng có thể tích 1000 $\\text{cm}^3$ ở $0^\\circ\\text{C}$. Hệ số nở dài của đồng là $\\alpha = 17\\cdot 10^{-6}\\text{ K}^{-1}$. Hệ số nở khối $\\beta$ xấp xỉ bằng bao nhiêu và thể tích quả cầu ở $100^\\circ\\text{C}$ tăng thêm bao nhiêu?",
     "choices": ["$\\beta \\approx 3\\alpha$, tăng thêm 5,1 $\\text{cm}^3$", "$\\beta \\approx \\alpha$, tăng thêm 1,7 $\\text{cm}^3$", "$\\beta \\approx 2\\alpha$, tăng thêm 3,4 $\\text{cm}^3$", "$\\beta \\approx 3\\alpha$, tăng thêm 51 $\\text{cm}^3$"],
     "answer": 0, "explanation": "Hệ số nở khối $\\beta \approx 3\\alpha = 3 \times 17\\cdot 10^{-6} = 51\cdot 10^{-6}$. $\\Delta V = \\beta V_0 \\Delta t = 51\cdot 10^{-6} \times 1000 \times 100 = 5100000 \cdot 10^{-6} = 5,1\\text{ cm}^3$."},

    # Nhóm 24, 25: Sự chuyển thể - Sự nóng chảy, đông đặc
    {"id": "mc-c5-081", "chapter": "c5", "lesson": "b53", "level": "nb", "dang": "Sự nóng chảy",
     "question": "Quá trình chuyển từ thể rắn sang thể lỏng gọi là sự:",
     "choices": ["Nóng chảy", "Đông đặc", "Hóa hơi", "Ngưng tụ"],
     "answer": 0, "explanation": "Rắn $\\rightarrow$ Lỏng: Nóng chảy."},
    {"id": "mc-c5-082", "chapter": "c5", "lesson": "b53", "level": "nb", "dang": "Đặc điểm nóng chảy",
     "question": "Trong suốt thời gian nước đá đang nóng chảy (ở 0 độ C và áp suất chuẩn), nhiệt độ của khối nước đá sẽ:",
     "choices": ["Không thay đổi (giữ ở 0 độ C)", "Tăng dần lên", "Giảm dần xuống", "Tăng vọt rất nhanh"],
     "answer": 0, "explanation": "Với chất rắn kết tinh (như nước đá), trong suốt quá trình nóng chảy (hoặc đông đặc), nhiệt độ không thay đổi mặc dù vẫn tiếp tục cung cấp nhiệt lượng (nhiệt lượng dùng để phá vỡ cấu trúc tinh thể)."},
    {"id": "mc-c5-083", "chapter": "c5", "lesson": "b53", "level": "th", "dang": "Nhiệt nóng chảy",
     "question": "Nhiệt lượng cần cung cấp cho một khối lượng m chất rắn để nó nóng chảy hoàn toàn ở nhiệt độ nóng chảy được tính bằng công thức:",
     "choices": ["$Q = \lambda m$", "$Q = m c \\Delta t$", "$Q = L m$", "$Q = m/\\lambda$"],
     "answer": 0, "explanation": "$\\lambda$ là nhiệt nóng chảy riêng (J/kg). $Q = \lambda m$ là nhiệt nóng chảy (ẩn nhiệt nóng chảy)."},
    {"id": "mc-c5-084", "chapter": "c5", "lesson": "b53", "level": "vd", "dang": "Tính nhiệt nóng chảy",
     "question": "Biết nhiệt nóng chảy riêng của nước đá là $3,4\\cdot 10^5\\text{ J/kg}$. Để làm nóng chảy hoàn toàn 2kg nước đá đang ở $0^\\circ\\text{C}$ thành nước ở $0^\\circ\\text{C}$ cần nhiệt lượng là:",
     "choices": ["$6,8\\cdot 10^5\\text{ J}$", "$1,7\\cdot 10^5\\text{ J}$", "$3,4\\cdot 10^5\\text{ J}$", "$68\\cdot 10^5\\text{ J}$"],
     "answer": 0, "explanation": "$Q = \lambda m = 3,4\cdot 10^5 \times 2 = 6,8\cdot 10^5\\text{ J}$."},

    # Nhóm 26, 27: Sự hóa hơi - Sôi và Bay hơi
    {"id": "mc-c5-085", "chapter": "c5", "lesson": "b54", "level": "nb", "dang": "Sự bay hơi",
     "question": "Sự bay hơi của chất lỏng là quá trình hóa hơi diễn ra ở đâu?",
     "choices": ["Chỉ diễn ra trên bề mặt tự do của chất lỏng", "Diễn ra ở cả trên bề mặt và trong lòng khối chất lỏng", "Chỉ diễn ra ở dưới đáy bình", "Chỉ diễn ra khi nước đạt 100 độ C"],
     "answer": 0, "explanation": "Sự bay hơi xảy ra BẤT KÌ nhiệt độ nào, nhưng CHỈ trên bề mặt chất lỏng. (Sự sôi thì xảy ra cả trong lòng và trên bề mặt ở 1 nhiệt độ cố định)."},
    {"id": "mc-c5-086", "chapter": "c5", "lesson": "b54", "level": "th", "dang": "Yếu tố ảnh hưởng bay hơi",
     "question": "Tốc độ bay hơi của chất lỏng KHÔNG phụ thuộc vào yếu tố nào sau đây?",
     "choices": ["Thể tích của bình chứa bao quanh khối chất lỏng", "Nhiệt độ của chất lỏng", "Diện tích mặt thoáng của chất lỏng", "Gió trên mặt thoáng"],
     "answer": 0, "explanation": "Tốc độ bay hơi phụ thuộc Nhiệt độ, Gió, Diện tích mặt thoáng và Bản chất chất lỏng. Không phụ thuộc vào thể tích toàn bình chứa nếu diện tích mặt thoáng giữ nguyên."},
    {"id": "mc-c5-087", "chapter": "c5", "lesson": "b54", "level": "th", "dang": "Nhiệt hóa hơi",
     "question": "Nhiệt lượng cần cung cấp cho một khối lượng m chất lỏng để nó hóa hơi hoàn toàn ở nhiệt độ sôi (nhiệt hóa hơi) là:",
     "choices": ["$Q = L m$", "$Q = \lambda m$", "$Q = c m \\Delta t$", "$Q = m / L$"],
     "answer": 0, "explanation": "$L$ là nhiệt hóa hơi riêng (J/kg). $Q = L m$."},
    {"id": "mc-c5-088", "chapter": "c5", "lesson": "b54", "level": "vd", "dang": "Tính nhiệt đun sôi",
     "question": "Nước sôi ở $100^\\circ\\text{C}$. Biết nhiệt hóa hơi riêng của nước là $2,3\cdot 10^6\\text{ J/kg}$. Để đun cạn 1 lít nước (1kg) đang sôi ở $100^\\circ\\text{C}$ (biến thành hơi nước $100^\\circ\\text{C}$) cần nhiệt lượng:",
     "choices": ["2.300.000 J", "4.200 J", "340.000 J", "100.000 J"],
     "answer": 0, "explanation": "$Q = L m = 2,3\cdot 10^6 \times 1 = 2,3\cdot 10^6\\text{ J}$ (tức 2,3 triệu Jun). Nước bay hơi tốn rất nhiều năng lượng."},

    # Nhóm 28, 29, 30: Bài toán hỗn hợp nhiệt (Phương trình cân bằng nhiệt)
    {"id": "mc-c5-089", "chapter": "c5", "lesson": "b55", "level": "nb", "dang": "Cân bằng nhiệt",
     "question": "Khi hai vật có nhiệt độ khác nhau trao đổi nhiệt với nhau, quá trình truyền nhiệt sẽ dừng lại khi nào?",
     "choices": ["Khi nhiệt độ của hai vật bằng nhau", "Khi nhiệt lượng của hai vật bằng nhau", "Khi khối lượng hai vật bằng nhau", "Khi nội năng hai vật bằng nhau"],
     "answer": 0, "explanation": "Sự truyền nhiệt chỉ xảy ra khi có chênh lệch nhiệt độ. Khi $t_1 = t_2$ (cân bằng nhiệt), sự truyền nhiệt vĩ mô dừng lại."},
    {"id": "mc-c5-090", "chapter": "c5", "lesson": "b55", "level": "th", "dang": "Phương trình cân bằng nhiệt",
     "question": "Phương trình cân bằng nhiệt cho hệ cô lập (không trao đổi nhiệt với môi trường) là:",
     "choices": ["$Q_{\\text{tỏa}} = Q_{\\text{thu}}$", "$Q_{\\text{tỏa}} > Q_{\\text{thu}}$", "$Q_{\\text{tỏa}} + Q_{\\text{thu}} = 0$ (với quy ước dấu)", "Cả A và C đều đúng trong cách viết khác nhau"],
     "answer": 0, "explanation": "Nếu chỉ xét độ lớn: Tỏa = Thu. Nếu xét đại số theo quy ước (Nhận dương, Cho âm): $\\sum Q = 0 \Rightarrow Q_{\\text{thu}} + Q_{\\text{tỏa}} = 0$."},
    {"id": "mc-c5-091", "chapter": "c5", "lesson": "b55", "level": "vd", "dang": "Bài toán pha nước",
     "question": "Trộn 2 kg nước ở $20^\\circ\\text{C}$ với 3 kg nước ở $70^\\circ\\text{C}$. Bỏ qua sự mất nhiệt ra môi trường và bình chứa. Nhiệt độ của hỗn hợp khi cân bằng là:",
     "choices": ["$50^\\circ\\text{C}$", "$45^\\circ\\text{C}$", "$40^\\circ\\text{C}$", "$60^\\circ\\text{C}$"],
     "answer": 0, "explanation": "Cùng chất (cùng c). $Q_{\\text{thu}} = Q_{\\text{tỏa}} \Rightarrow m_1 c (t - t_1) = m_2 c (t_2 - t) \Rightarrow 2(t - 20) = 3(70 - t) \Rightarrow 2t - 40 = 210 - 3t \Rightarrow 5t = 250 \Rightarrow t = 50^\\circ\\text{C}$."},
    {"id": "mc-c5-092", "chapter": "c5", "lesson": "b55", "level": "vd", "dang": "Bài toán nhôm - nước",
     "question": "Thả một quả cầu nhôm khối lượng 0,5kg ở $100^\\circ\\text{C}$ vào cốc nước chứa 1kg nước ở $20^\\circ\\text{C}$. Biết nhiệt dung riêng của nhôm là 880 J/kg.K, của nước là 4200 J/kg.K. Nhiệt độ hỗn hợp khi cân bằng xấp xỉ:",
     "choices": ["$27,6^\\circ\\text{C}$", "$35^\\circ\\text{C}$", "$60^\\circ\\text{C}$", "$21^\\circ\\text{C}$"],
     "answer": 0, "explanation": "$m_{Al} c_{Al} (100 - t) = m_n c_n (t - 20) \Rightarrow 0.5 \times 880 (100 - t) = 1 \times 4200 (t - 20) \Rightarrow 440(100-t) = 4200(t-20)$. Chia hai vế cho 40: $11(100-t) = 105(t-20) \Rightarrow 1100 - 11t = 105t - 2100 \Rightarrow 116t = 3200 \Rightarrow t \approx 27,58^\\circ\\text{C}$."},

    # Các câu còn lại 93-120 ôn tập mở rộng, Động cơ nhiệt loại 2, Độ ẩm không khí
    {"id": "mc-c5-093", "chapter": "c5", "lesson": "b56", "level": "nb", "dang": "Độ ẩm",
     "question": "Độ ẩm tuyệt đối của không khí là:",
     "choices": ["Khối lượng hơi nước tính bằng gam chứa trong 1 $\\text{m}^3$ không khí", "Phần trăm lượng hơi nước trong không khí", "Áp suất hơi nước trong không khí", "Lượng nước mưa rơi xuống trong ngày"],
     "answer": 0, "explanation": "Độ ẩm tuyệt đối (a) là lượng hơi nước thực tế có trong 1 mét khối không khí, đơn vị g/m³."},
    {"id": "mc-c5-094", "chapter": "c5", "lesson": "b56", "level": "th", "dang": "Độ ẩm cực đại",
     "question": "Độ ẩm cực đại (A) của không khí ở một nhiệt độ t phụ thuộc vào:",
     "choices": ["Chỉ phụ thuộc vào nhiệt độ t (bằng khối lượng riêng của hơi nước bão hòa ở nhiệt độ đó)", "Phụ thuộc vào lượng hơi nước hiện có", "Phụ thuộc vào áp suất khí quyển", "Không phụ thuộc nhiệt độ"],
     "answer": 0, "explanation": "Độ ẩm cực đại là sức chứa hơi nước tối đa (trạng thái bão hòa). Nó tăng khi nhiệt độ tăng."},
    {"id": "mc-c5-095", "chapter": "c5", "lesson": "b56", "level": "th", "dang": "Độ ẩm tương đối",
     "question": "Độ ẩm tương đối của không khí (f) được định nghĩa là:",
     "choices": ["Tỉ số phần trăm giữa độ ẩm tuyệt đối và độ ẩm cực đại ở cùng nhiệt độ ($f = a/A \\times 100\\%$)", "Tỉ số giữa nhiệt độ và áp suất", "Tỉ số khối lượng nước và khối lượng không khí", "Phần trăm oxi trong không khí"],
     "answer": 0, "explanation": "Độ ẩm tương đối (Relative Humidity) $f = (a/A) \\times 100\\%$ hoặc $(p/p_{bh}) \\times 100\\%$. Thể hiện mức độ ẩm ướt, hanh khô."},
    {"id": "mc-c5-096", "chapter": "c5", "lesson": "b56", "level": "vd", "dang": "Sương mù",
     "question": "Ban ngày nhiệt độ $30^\\circ\\text{C}$ không khí chứa 15 g/m³ hơi nước. Ban đêm nhiệt độ giảm xuống $15^\\circ\\text{C}$. Biết độ ẩm cực đại ở $15^\\circ\\text{C}$ là 12,8 g/m³. Hiện tượng gì sẽ xảy ra?",
     "choices": ["Hơi nước ngưng tụ thành giọt sương (hoặc sương mù)", "Không khí trở nên khô hanh hơn", "Độ ẩm tuyệt đối tăng lên 27,8 g/m³", "Nước sẽ sôi lên"],
     "answer": 0, "explanation": "Không khí lạnh đi, sức chứa cực đại (12,8) nhỏ hơn lượng nước thực tế đang có (15). Phần dư $15 - 12.8 = 2.2\\text{ g/m}^3$ sẽ ngưng tụ thành sương. Đây là nguyên nhân hình thành sương giá, sương mù."},

    {"id": "mc-c5-097", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Hiệu suất nhiệt tối đa (Carnot)",
     "question": "Hiệu suất lí tưởng cực đại của một động cơ nhiệt (Chu trình Carnot) hoạt động giữa nguồn nóng nhiệt độ $T_1$ và nguồn lạnh nhiệt độ $T_2$ (tính theo Kelvin) là:",
     "choices": ["$H_{\\max} = \\frac{T_1 - T_2}{T_1}$", "$H_{\\max} = \\frac{T_1}{T_2}$", "$H_{\\max} = 1 - \\frac{T_1}{T_2}$", "$H_{\\max} = \\frac{T_2 - T_1}{T_1}$"],
     "answer": 0, "explanation": "Định lí Carnot: Hiệu suất động cơ nhiệt không thể vượt quá $H = (T_1 - T_2) / T_1 = 1 - T_2/T_1$."},
    {"id": "mc-c5-098", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Tính Hiệu suất Carnot",
     "question": "Một động cơ nhiệt hoạt động với nguồn nóng ở $327^\\circ\\text{C}$ và nguồn lạnh ở $27^\\circ\\text{C}$. Hiệu suất lớn nhất có thể đạt được là:",
     "choices": ["50%", "91,7%", "30%", "100%"],
     "answer": 0, "explanation": "$T_1 = 327 + 273 = 600\\text{ K}$. $T_2 = 27 + 273 = 300\\text{ K}$. $H_{\\max} = (600 - 300) / 600 = 300 / 600 = 0,5 = 50\\%$."},
    {"id": "mc-c5-099", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Bơm nhiệt / Tủ lạnh",
     "question": "Hệ số làm lạnh $\\epsilon$ của một tủ lạnh (lấy nhiệt $Q_2$ từ buồng lạnh bằng cách tốn công A) được định nghĩa là:",
     "choices": ["$\\epsilon = \\frac{Q_2}{A}$", "$\\epsilon = \\frac{A}{Q_2}$", "$\\epsilon = \\frac{Q_1}{A}$", "$\\epsilon = \\frac{Q_1 - Q_2}{A}$"],
     "answer": 0, "explanation": "Mục đích của tủ lạnh là rút nhiệt lượng $Q_2$ ra khỏi đồ ăn, cái giá phải trả là điện năng (Công A). Hiệu quả $\\epsilon = Q_2 / A$. Nó có thể lớn hơn 1 (thường từ 2 đến 5)."},
    {"id": "mc-c5-100", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Bài toán đun nước hở",
     "question": "Đun sôi 1 kg nước đá từ $-20^\\circ\\text{C}$ đến khi hóa hơi hoàn toàn ở $100^\\circ\\text{C}$. Quá trình này gồm mấy giai đoạn cung cấp nhiệt?",
     "choices": ["4 giai đoạn: Nóng lên $0^\\circ\\text{C}$ $\\rightarrow$ Nóng chảy $\\rightarrow$ Nóng lên $100^\\circ\\text{C}$ $\\rightarrow$ Hóa hơi", "2 giai đoạn: Nóng chảy và Hóa hơi", "3 giai đoạn", "1 giai đoạn"],
     "answer": 0, "explanation": "(1) Tăng từ -20 đến 0: $Q_1 = m c_{\\text{đá}} \\Delta t$. (2) Nóng chảy tại 0: $Q_2 = \\lambda m$. (3) Tăng từ 0 đến 100: $Q_3 = m c_{\\text{nước}} \\Delta t$. (4) Hóa hơi tại 100: $Q_4 = L m$."},
    
    {"id": "mc-c5-101", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Pha trộn khí (khác loại)",
     "question": "Một bình 10 lít chứa hỗn hợp 2g $H_2$ và 14g $N_2$ ở $27^\\circ\\text{C}$. Áp suất của hỗn hợp khí là bao nhiêu? ($M_{H2}=2, M_{N2}=28, R=8,31$, V=0.01m³)",
     "choices": ["$3,74\\cdot 10^5\\text{ Pa}$", "$1,25\\cdot 10^5\\text{ Pa}$", "$2,49\\cdot 10^5\\text{ Pa}$", "$4,98\\cdot 10^5\\text{ Pa}$"],
     "answer": 0, "explanation": "Số mol $H_2$: $n_1 = 2/2 = 1\\text{ mol}$. Số mol $N_2$: $n_2 = 14/28 = 0.5\\text{ mol}$. Tổng số mol $n = 1.5\\text{ mol}$. Áp suất $p = nRT/V = 1.5 \times 8.31 \times 300 / 0.01 = 3739.5 / 0.01 = 3,74\\cdot 10^5\\text{ Pa}$."},
    {"id": "mc-c5-102", "chapter": "c5", "lesson": "b53", "level": "vd", "dang": "Va chạm đạn chì",
     "question": "Viên đạn chì bay với vận tốc 400 m/s đâm vào tấm sắt và dừng lại. Giả sử 50% động năng của đạn biến thành nhiệt làm nóng chính viên đạn. Nhiệt độ của đạn sẽ tăng thêm khoảng bao nhiêu? (Biết nhiệt dung riêng của chì là $c = 130\\text{ J/kg.K}$)",
     "choices": ["$307^\\circ\\text{C}$", "$615^\\circ\\text{C}$", "$153^\\circ\\text{C}$", "$100^\\circ\\text{C}$"],
     "answer": 0, "explanation": "$0.5 \cdot (0.5 m v^2) = m c \\Delta t \Rightarrow 0.25 v^2 = c \\Delta t \Rightarrow 0.25 \times 400^2 = 130 \\Delta t \Rightarrow 40000 = 130 \\Delta t \Rightarrow \\Delta t = 40000 / 130 \approx 307.7^\\circ\\text{C}$."},
    {"id": "mc-c5-103", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Bơm bóng bay",
     "question": "Có một bình khí Heli dung tích 50 lít ở 100 atm. Người ta dùng bình này để bơm các quả bóng bay bóp méo, mỗi quả chứa 2 lít khí ở 1 atm. Sau khi bơm xong (áp suất bình còn 1 atm), số bóng bay bơm được là:",
     "choices": ["2475 quả", "2500 quả", "2450 quả", "5000 quả"],
     "answer": 0, "explanation": "Khí ban đầu $p_1 V_1 = 100 \times 50 = 5000$ (atm.L). Khí không thể bơm ra được là khí còn kẹt trong bình ở 1 atm (bằng áp suất ngoài), thể tích 50 lít. Lượng khí bơm ra vỏ bóng: $\\Delta(pV) = 5000 - (1 \times 50) = 4950$. Số bóng = $4950 / 2 = 2475$ quả."},
    {"id": "mc-c5-104", "chapter": "c5", "lesson": "b44", "level": "vd", "dang": "Khí lọt bình",
     "question": "Một bình thủy tinh được đậy nắp chặt ở $27^\\circ\\text{C}$ (áp suất 1 atm). Khi nung nóng bình lên đến $127^\\circ\\text{C}$ thì nắp bình bị bật ra (do áp suất khí tăng). Biết diện tích tiết diện nắp là $10\\text{ cm}^2$. Lực ma sát của nắp với miệng bình (giữ nắp không bung) xấp xỉ:",
     "choices": ["33 N", "100 N", "133 N", "20 N"],
     "answer": 0, "explanation": "Đẳng tích: $p_2 / T_2 = p_1 / T_1 \Rightarrow p_2 = 1 \times (400 / 300) = 1.333\\text{ atm}$. Chênh lệch áp suất so với khí quyển: $\\Delta p = 0.333\\text{ atm} \approx 0.333 \times 10^5 = 33333\\text{ Pa}$. Lực đẩy làm bung nắp $F = \\Delta p \cdot S = 33333 \times 10 \cdot 10^{-4} = 33,3\\text{ N}$. Lực này vừa thắng lực ma sát giữ nắp $\\Rightarrow F_{ms} \approx 33\\text{ N}$."},
    
    {"id": "mc-c5-105", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Cột thủy ngân ống hở",
     "question": "Ống thủy tinh dài, hở 2 đầu. Nhúng thẳng đứng ống vào chậu thủy ngân sao cho một nửa ống ngập trong thủy ngân. Bịt kín đầu trên và rút ống lên từ từ (không rời khỏi mặt thủy ngân). Cột thủy ngân trong ống sẽ:",
     "choices": ["Dâng lên cao hơn mặt ngoài một đoạn", "Vẫn bằng mặt ngoài", "Hạ thấp hơn mặt ngoài", "Tụt hết xuống chậu"],
     "answer": 0, "explanation": "Khi rút lên, thể tích phần không khí bị nhốt (đầu trên) TĂNG LÊN. Theo định luật Boyle, áp suất khí nhốt GIẢM xuống nhỏ hơn áp suất khí quyển $p_0$. Do đó, áp suất khí quyển đè lên mặt thoáng ngoài chậu sẽ đẩy thủy ngân chạy ngược lên ống. Cột thủy ngân cao hơn mặt ngoài."},
    {"id": "mc-c5-106", "chapter": "c5", "lesson": "b51", "level": "vd", "dang": "Mạng tinh thể",
     "question": "Kim cương và than chì đều được cấu tạo từ nguyên tử Cacbon nhưng có tính chất cơ học (độ cứng) khác hẳn nhau. Nguyên nhân là do:",
     "choices": ["Cấu trúc mạng tinh thể của chúng khác nhau", "Kim cương có khối lượng phân tử lớn hơn", "Than chì là chất rắn vô định hình", "Kim cương chứa tạp chất siêu cứng"],
     "answer": 0, "explanation": "Kim cương có mạng tinh thể không gian 3 chiều liên kết cộng hóa trị tứ diện rất bền chắc. Than chì có mạng tinh thể lớp 2 chiều (các lớp liên kết yếu Van der Waals với nhau) nên mềm, dễ trượt."},
    {"id": "mc-c5-107", "chapter": "c5", "lesson": "b52", "level": "vd", "dang": "Băng kép",
     "question": "Băng kép (hai thanh kim loại khác bản chất ghép chặt vào nhau) khi bị nung nóng sẽ cong về phía nào?",
     "choices": ["Cong về phía thanh kim loại có hệ số nở dài NHỎ HƠN", "Cong về phía thanh có hệ số nở dài LỚN HƠN", "Giãn dài ra nhưng vẫn thẳng", "Xoắn lại như lò xo"],
     "answer": 0, "explanation": "Thanh có hệ số lớn hơn sẽ dài hơn, nằm ở vòng cung ngoài (bán kính lớn). Vậy băng kép bị uốn cong về phía thanh ít giãn nở (hệ số nhỏ). (Ứng dụng: rơ-le nhiệt bàn là)."},
    {"id": "mc-c5-108", "chapter": "c5", "lesson": "b54", "level": "vd", "dang": "Đồ thị hal",
     "question": "Tại sao trên núi cao, nước đun lại sôi ở nhiệt độ thấp hơn $100^\\circ\\text{C}$?",
     "choices": ["Vì áp suất khí quyển trên núi thấp hơn ở mặt đất, nước dễ hóa hơi hơn", "Vì trên núi nhiệt độ môi trường lạnh hơn", "Vì trên núi nước tinh khiết hơn", "Vì gió to làm nước bốc hơi nhanh"],
     "answer": 0, "explanation": "Nước sôi khi áp suất hơi bão hòa bên trong bọt khí cân bằng với áp suất ngoài (áp suất khí quyển). Khi áp suất ngoài nhỏ, nước không cần đạt 100 độ C đã đủ áp suất hơi bão hòa để sôi."},

    {"id": "mc-c5-109", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Khái niệm Đoản nhiệt",
     "question": "Quá trình đoạn nhiệt (Adiabatic) là quá trình biến đổi trạng thái trong đó khối khí:",
     "choices": ["Không trao đổi nhiệt lượng với môi trường bên ngoài ($Q = 0$)", "Được giữ ở nhiệt độ tuyệt đối không đổi", "Không sinh công ($A = 0$)", "Áp suất luôn giảm một đoạn xác định"],
     "answer": 0, "explanation": "Đoạn nhiệt là cách li nhiệt. $Q = 0$. Suy ra $\\Delta U = A$. Nén đoạn nhiệt thì khí nóng lên (công chuyển thành nội năng). Giãn đoạn nhiệt khí tự lạnh đi (nội năng sinh công)."},
    {"id": "mc-c5-110", "chapter": "c5", "lesson": "b49", "level": "vd", "dang": "Biến thiên T đoạn nhiệt",
     "question": "Khi bạn dùng bơm tay để bơm lốp xe đạp (nén nhanh), thành ống bơm bị nóng lên rất rõ. Giải thích bằng NĐLH:",
     "choices": ["Quá trình nén xảy ra nhanh gần như đoạn nhiệt, ta thực hiện công lên khí làm nội năng và nhiệt độ khí tăng, sau đó khí truyền nhiệt ra thành ống", "Do ma sát giữa pittong và thành ống sinh nhiệt hoàn toàn", "Do không khí hấp thụ nhiệt từ tay ta", "Do không khí hóa lỏng sinh nhiệt"],
     "answer": 0, "explanation": "Ma sát có góp phần nhưng chủ yếu là quá trình nén nhanh không kịp tỏa nhiệt ($Q \approx 0$), $A > 0 \Rightarrow \Delta U > 0 \Rightarrow$ khí nóng ran lên."},
    
    {"id": "mc-c5-111", "chapter": "c5", "lesson": "b55", "level": "vd", "dang": "Nhiệt lượng kế (mất nhiệt)",
     "question": "Dùng một nhiệt lượng kế (có nhiệt dung $C_k = 100\\text{ J/K}$) đựng 0,2kg nước ở $20^\\circ\\text{C}$. Thả một thỏi đồng 0,5kg ở $100^\\circ\\text{C}$ vào. ($c_{nuoc} = 4200, c_{dong} = 380$). Bỏ qua mất nhiệt ra môi trường phòng. Nhiệt độ cân bằng $t$ là:",
     "choices": ["$34,3^\\circ\\text{C}$", "$26,5^\\circ\\text{C}$", "$36,2^\\circ\\text{C}$", "$42^\\circ\\text{C}$"],
     "answer": 0, "explanation": "Giải phương trình: $Q_{\\text{thu}} = (0.2 \\times 4200 + 100)(t - 20) = 940(t - 20)$. $Q_{\\text{tỏa}} = 0.5 \\times 380(100 - t) = 190(100 - t)$. $940t - 18800 = 19000 - 190t \\Rightarrow 1130t = 37800 \\Rightarrow t \\approx 33,45^\\circ\\text{C}$. (Nếu bỏ qua nhiệt lượng kế Ck = 0 thì $t = 34,7^\\circ\\text{C}$)."},
    {"id": "mc-c5-112", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Trộn khí (Bài khó)",
     "question": "Hai bình cầu được nối thông với nhau bằng một ống nhỏ. Khóa K đang đóng. Bình 1 chứa khí lí tưởng ở nhiệt độ $T_1 = 300\\text{ K}$, áp suất $p_1$. Bình 2 là chân không ($p_2=0$). Mở khóa K cho khí tràn sang (nhiệt độ giữ cố định ở 300K). Thể tích hai bình là bằng nhau. Áp suất cuối cùng trong hệ là:",
     "choices": ["$0,5 p_1$", "$p_1$", "$2 p_1$", "0"],
     "answer": 0, "explanation": "Quá trình giãn nở chân không (đẳng nhiệt). Tổng thể tích tăng gấp đôi (V $\\rightarrow$ 2V). Số mol không đổi, T không đổi. Áp suất $p$ tỉ lệ nghịch $V$ nên $p$ giảm một nửa. $p = 0.5 p_1$."},

    {"id": "mc-c5-113", "chapter": "c5", "lesson": "b54", "level": "th", "dang": "Nhiệt độ tới hạn",
     "question": "Nhiệt độ tới hạn của một chất khí là:",
     "choices": ["Nhiệt độ mà ở trên mức đó, chất khí không thể bị hóa lỏng dù bị nén với áp suất cao đến đâu", "Nhiệt độ mà chất khí bắt đầu đông đặc", "Nhiệt độ mà khí tự cháy nổ", "Nhiệt độ 0 Kelvin tuyệt đối"],
     "answer": 0, "explanation": "Tại nhiệt độ lớn hơn nhiệt độ tới hạn (Critical temperature), động năng phân tử quá lớn nên không có lực ép nào đủ kéo các phân tử lại gần nhau thành chất lỏng. Khí ở trạng thái này gọi là \"khí thực thụ\" (gas), dưới tới hạn gọi là \"hơi\" (vapor)."},
    {"id": "mc-c5-114", "chapter": "c5", "lesson": "b53", "level": "th", "dang": "Chất rắn siêu lạnh",
     "question": "Hiện tượng nước có thể hạ nhiệt độ xuống dưới $0^\\circ\\text{C}$ mà vẫn không đóng băng (giữ trạng thái lỏng) gọi là hiện tượng gì?",
     "choices": ["Trạng thái siêu lạnh (supercooling)", "Sự thăng hoa", "Sự sôi bùng", "Nhiệt động nghịch"],
     "answer": 0, "explanation": "Nước tinh khiết trong môi trường không có \"mầm kết tinh\" (hạt bụi, rung động) có thể làm lạnh xuống -20 độ C vẫn lỏng. Nhưng chỉ cần 1 rung động nhỏ, nó lập tức đóng băng tỏa nhiệt."},
    {"id": "mc-c5-115", "chapter": "c5", "lesson": "b52", "level": "th", "dang": "Khe hở đường sắt",
     "question": "Tại sao giữa hai đầu thanh ray đường sắt luôn phải để lại một khe hở nhỏ?",
     "choices": ["Để tạo không gian cho thanh ray giãn nở (nở dài) khi nhiệt độ tăng vào mùa hè, tránh làm cong vênh đường ray", "Để tiết kiệm thép", "Để tàu chạy qua phát ra tiếng xịch xịch báo hiệu", "Để nước mưa thoát đi"],
     "answer": 0, "explanation": "Nhiệt độ thay đổi 30-40 độ C, thanh ray dài 10m có thể nở thêm gần chục mm. Không có khe hở, ứng suất nhiệt sẽ uốn cong đường ray gây lật tàu."},
    {"id": "mc-c5-116", "chapter": "c5", "lesson": "b55", "level": "vd", "dang": "Bài toán cục đá trong nước",
     "question": "Thả một cục đá 100g ở $-10^\\circ\\text{C}$ vào cốc nước 200g ở $20^\\circ\\text{C}$. Nhiệt dung đá 2100, nước 4200, nhiệt nóng chảy $\\lambda = 340000\\text{ J/kg}$. Hiện tượng xảy ra là:",
     "choices": ["Đá không tan hết, hệ cân bằng ở $0^\\circ\\text{C}$ chứa hỗn hợp nước và đá", "Đá tan hết, nước lạnh xuống còn $5^\\circ\\text{C}$", "Nước đóng băng thêm thành đá", "Nước sôi"],
     "answer": 0, "explanation": "Nhiệt làm đá tăng lên 0 độ: $Q_1 = 0.1 \times 2100 \times 10 = 2100\\text{ J}$. Nhiệt để đá tan hoàn toàn: $Q_2 = 0.1 \times 340000 = 34000\\text{ J}$. Tổng cần thu $Q = 36100\\text{ J}$. Nhiệt tối đa nước có thể tỏa (hạ xuống 0 độ): $Q_{tỏa} = 0.2 \times 4200 \times 20 = 16800\\text{ J}$. Vì Thu (36100) > Tỏa tối đa (16800) $\\Rightarrow$ Nhiệt nước cấp không đủ làm tan hết đá. Hệ dừng ở 0 độ C."},
    
    {"id": "mc-c5-117", "chapter": "c5", "lesson": "b53", "level": "nb", "dang": "Thăng hoa",
     "question": "Hiện tượng một chất rắn chuyển TRỰC TIẾP thành thể khí (bỏ qua thể lỏng) được gọi là:",
     "choices": ["Sự thăng hoa", "Sự bay hơi", "Sự ngưng kết", "Sự thăng thiên"],
     "answer": 0, "explanation": "Thăng hoa (Sublimation). Ví dụ: Băng phiến (hồ điệp), đá khô (CO2 rắn) tự bốc hơi thành khí mà không chảy nước."},
    {"id": "mc-c5-118", "chapter": "c5", "lesson": "b49", "level": "th", "dang": "Sự truyền nhiệt",
     "question": "Bức xạ nhiệt là hình thức truyền nhiệt:",
     "choices": ["Bằng các tia nhiệt (sóng điện từ hồng ngoại), có thể truyền qua cả chân không", "Nhờ sự chuyển động của chất lưu (khí, lỏng)", "Qua sự va chạm trực tiếp của các phân tử", "Chỉ xảy ra ở nhiệt độ cực cao"],
     "answer": 0, "explanation": "Bức xạ nhiệt (Thermal radiation) truyền qua chân không (Mặt Trời truyền nhiệt xuống Trái Đất). Đối lưu cần chất lỏng/khí. Dẫn nhiệt cần chất rắn/tiếp xúc."},
    {"id": "mc-c5-119", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Đồ thị P-T nén",
     "question": "Nén một khối khí lí tưởng trong xilanh, áp suất tăng nhưng nhiệt độ lại giảm. Vậy thể tích của khối khí đã:",
     "choices": ["Chắc chắn giảm", "Có thể tăng hoặc giảm", "Không thay đổi", "Chắc chắn tăng"],
     "answer": 0, "explanation": "$V = nRT / p$. T giảm (tử số giảm), p tăng (mẫu số tăng). Cả hai tác động đều làm V nhỏ đi rất nhanh. Vậy thể tích chắc chắn phải giảm."},
    {"id": "mc-c5-120", "chapter": "c5", "lesson": "b56", "level": "vd", "dang": "Sự tạo mây",
     "question": "Mây trên bầu trời hình thành do quá trình vật lí nào?",
     "choices": ["Không khí ẩm bay lên cao, áp suất giảm làm nó giãn nở đoạn nhiệt, nhiệt độ hạ thấp xuống dưới điểm sương, hơi nước ngưng tụ thành hạt nhỏ", "Khí nóng bay lên kết tủa thành băng", "Gió đưa các khối bọt nước từ biển lên", "Khí Oxi và Hidro trên không gian kết hợp"],
     "answer": 0, "explanation": "Đây là ứng dụng của giãn nở đoạn nhiệt ($Q=0, A>0 \Rightarrow \Delta U < 0$ khí lạnh đi) làm ngưng tụ hơi nước (do độ ẩm cực đại giảm)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C5 Part 2 written successfully.")
