import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 3 HÓA HỌC 10: PHẢN ỨNG OXI HÓA - KHỬ ---
    # Nhóm 1, 2, 3: Số oxi hóa và Quy tắc
    {"id": "mc-c3-001", "chapter": "c3", "lesson": "b15", "level": "nb", "dang": "Khái niệm số Oxi hóa",
     "question": "Số oxi hóa của một nguyên tử trong phân tử là gì?",
     "choices": ["Điện tích giả định của nguyên tử đó trong phân tử, nếu giả định rằng tất cả các liên kết cộng hóa trị đều là liên kết ion (electron chuyển hẳn về nguyên tử có độ âm điện lớn hơn)", "Số liên kết hóa học mà nguyên tử đó tạo ra", "Điện tích thực sự của nguyên tử đó", "Số electron hóa trị của nguyên tử đó"],
     "answer": 0, "explanation": "Số oxi hóa là một khái niệm giả định, coi mọi liên kết là ion hoàn toàn để tính toán sự di chuyển electron trong các phản ứng."},
    {"id": "mc-c3-002", "chapter": "c3", "lesson": "b15", "level": "nb", "dang": "Quy tắc 1 2",
     "question": "Theo quy tắc xác định số oxi hóa, số oxi hóa của các nguyên tử trong đơn chất và tổng số oxi hóa của các nguyên tử trong một phân tử trung hòa bằng bao nhiêu?",
     "choices": ["Trong đơn chất bằng 0; Tổng trong phân tử bằng 0", "Trong đơn chất bằng 1; Tổng trong phân tử bằng 0", "Trong đơn chất bằng 0; Tổng trong phân tử bằng điện tích của hạt nhân", "Trong đơn chất bằng hóa trị; Tổng trong phân tử bằng 0"],
     "answer": 0, "explanation": "Quy tắc 1: Trong đơn chất, số OXH = 0 (vd $Fe^0, O_2^0$). Quy tắc 2: Trong phân tử trung hòa, tổng số OXH của các nguyên tử nhân với số lượng của chúng = 0."},
    {"id": "mc-c3-003", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Quy tắc 3 4",
     "question": "Trong hầu hết các hợp chất, số oxi hóa của Hydrogen (H) và Oxygen (O) thường lần lượt là:",
     "choices": ["+1 và -2", "-1 và +2", "+1 và +1", "0 và -2"],
     "answer": 0, "explanation": "Ngoại trừ hydride kim loại (H có số OXH -1) hoặc peroxide ($H_2O_2$ Oxi có số OXH -1) và $OF_2$ (Oxi có số OXH +2). Trong đa số hợp chất phổ thông: H là +1, O là -2."},
    {"id": "mc-c3-004", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Ngoại lệ số OXH",
     "question": "Trong hợp chất $OF_2$ (Oxygen difluoride), số oxi hóa của Oxygen là bao nhiêu?",
     "choices": ["+2", "-2", "0", "-1"],
     "answer": 0, "explanation": "F là nguyên tố có độ âm điện mạnh nhất, luôn có số OXH -1 trong mọi hợp chất. Tổng: $x + 2(-1) = 0 \Rightarrow x = +2$. Oxygen có số OXH dương (+2) trong trường hợp này."},

    {"id": "mc-c3-005", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Tính số OXH hợp chất vô cơ",
     "question": "Số oxi hóa của Sulfur (S) trong acid sulfuric ($H_2SO_4$) là:",
     "choices": ["+6", "+4", "-2", "+8"],
     "answer": 0, "explanation": "H là +1, O là -2. Gọi số OXH của S là x. Ta có: $2(+1) + x + 4(-2) = 0 \Rightarrow 2 + x - 8 = 0 \Rightarrow x = +6$."},
    {"id": "mc-c3-006", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Tính số OXH trong ion",
     "question": "Số oxi hóa của Chromium (Cr) trong ion dichromate ($Cr_2O_7^{2-}$ ) là:",
     "choices": ["+6", "+3", "+7", "+2"],
     "answer": 0, "explanation": "Tổng số OXH trong một ion đa nguyên tử bằng điện tích của ion đó. Gọi x là số OXH của Cr: $2x + 7(-2) = -2 \Rightarrow 2x - 14 = -2 \Rightarrow 2x = 12 \Rightarrow x = +6$."},
    {"id": "mc-c3-007", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Tính số OXH gốc Hữu cơ",
     "question": "Số oxi hóa trung bình của Carbon trong phân tử Glucose ($C_6H_{12}O_6$) là:",
     "choices": ["0", "+4", "-2", "+2"],
     "answer": 0, "explanation": "Gọi x là số OXH trung bình của C. $6x + 12(+1) + 6(-2) = 0 \Rightarrow 6x + 12 - 12 = 0 \Rightarrow 6x = 0 \Rightarrow x = 0$."},
    {"id": "mc-c3-008", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Bài tập đếm số chất",
     "question": "Cho các chất: $NH_3, HNO_2, N_2O, NO, HNO_3, N_2$. Dãy sắp xếp các chất theo thứ tự số oxi hóa của Nitrogen TĂNG DẦN là:",
     "choices": ["$NH_3, N_2, N_2O, NO, HNO_2, HNO_3$", "$NH_3, N_2O, N_2, NO, HNO_2, HNO_3$", "$HNO_3, HNO_2, NO, N_2O, N_2, NH_3$", "$N_2, NH_3, N_2O, NO, HNO_2, HNO_3$"],
     "answer": 0, "explanation": "Tính số OXH của N: $NH_3$ (-3), $N_2$ (0), $N_2O$ (+1), $NO$ (+2), $HNO_2$ (+3), $HNO_3$ (+5). Dãy tăng dần: -3, 0, +1, +2, +3, +5."},

    # Nhóm 4, 5, 6: Chất khử, chất oxi hóa, quá trình
    {"id": "mc-c3-009", "chapter": "c3", "lesson": "b15", "level": "nb", "dang": "Chất khử oxi hóa",
     "question": "Trong một phản ứng oxi hóa - khử, chất khử (chất bị oxi hóa) là chất:",
     "choices": ["Nhường electron, số oxi hóa tăng lên sau phản ứng", "Nhận electron, số oxi hóa giảm xuống sau phản ứng", "Nhường electron, số oxi hóa giảm xuống", "Nhận electron, số oxi hóa tăng lên"],
     "answer": 0, "explanation": "Câu thần chú: 'Khử cho - O nhận' (Chất khử cho e, chất oxi hóa nhận e). Khi cho e (mang điện âm), bản thân nó sẽ tăng phần dương lên $\\Rightarrow$ số oxi hóa tăng."},
    {"id": "mc-c3-010", "chapter": "c3", "lesson": "b15", "level": "nb", "dang": "Quá trình khử oxi hóa",
     "question": "Quá trình oxi hóa (sự oxi hóa) là quá trình:",
     "choices": ["Chất khử nhường electron", "Chất oxi hóa nhận electron", "Chất khử nhận electron", "Chất oxi hóa nhường electron"],
     "answer": 0, "explanation": "Sự oxi hóa (hay quá trình oxi hóa) là quá trình làm mất đi electron của chất khử. 'Sự' và 'Chất' đi ngược nhau: Sự oxi hóa xảy ra đối với chất khử."},
    {"id": "mc-c3-011", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Xác định vai trò",
     "question": "Cho phản ứng: $Fe + CuSO_4 \\rightarrow FeSO_4 + Cu$. Phát biểu nào sau đây đúng?",
     "choices": ["Fe là chất khử, $Cu^{2+}$ là chất oxi hóa", "Fe là chất oxi hóa, $Cu^{2+}$ là chất khử", "Fe bị khử, $Cu^{2+}$ bị oxi hóa", "Đây không phải là phản ứng oxi hóa - khử"],
     "answer": 0, "explanation": "$Fe^0 \\rightarrow Fe^{+2} + 2e$ (số OXH tăng $\\Rightarrow$ Fe là chất khử). $Cu^{+2} + 2e \\rightarrow Cu^0$ (số OXH giảm $\\Rightarrow Cu^{+2}$ là chất oxi hóa)."},
    {"id": "mc-c3-012", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Biểu diễn quá trình",
     "question": "Trong phản ứng đốt cháy kẽm: $2Zn + O_2 \\rightarrow 2ZnO$. Quá trình nào biểu diễn sự oxi hóa Kẽm?",
     "choices": ["$Zn \\rightarrow Zn^{2+} + 2e^-$", "$Zn^{2+} + 2e^- \\rightarrow Zn$", "$O_2 + 4e^- \\rightarrow 2O^{2-}$", "$2O^{2-} \\rightarrow O_2 + 4e^-$"],
     "answer": 0, "explanation": "Sự oxi hóa kẽm (quá trình kẽm nhường e): $Zn^0 \\rightarrow Zn^{+2} + 2e^-$."},

    {"id": "mc-c3-013", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Bài tập xác định chất khử",
     "question": "Trong phản ứng: $MnO_2 + 4HCl \\rightarrow MnCl_2 + Cl_2 + 2H_2O$. Chất oxi hóa và chất khử lần lượt là:",
     "choices": ["$MnO_2$ (chất oxi hóa) và $HCl$ (chất khử)", "$HCl$ (chất oxi hóa) và $MnO_2$ (chất khử)", "$MnCl_2$ (chất oxi hóa) và $Cl_2$ (chất khử)", "$Cl_2$ (chất oxi hóa) và $MnO_2$ (chất khử)"],
     "answer": 0, "explanation": "$Mn^{+4} \\rightarrow Mn^{+2}$ (giảm $\\Rightarrow MnO_2$ là chất oxi hóa). $Cl^{-1} \\rightarrow Cl^0$ (tăng $\\Rightarrow HCl$ là chất khử). (Một phần HCl làm môi trường)."},
    {"id": "mc-c3-014", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Phản ứng tự OXH Khử",
     "question": "Trong phản ứng: $Cl_2 + 2NaOH \\rightarrow NaCl + NaClO + H_2O$. Khí $Cl_2$ đóng vai trò gì?",
     "choices": ["Vừa là chất oxi hóa, vừa là chất khử", "Chỉ là chất oxi hóa", "Chỉ là chất khử", "Không là chất oxi hóa, không là chất khử"],
     "answer": 0, "explanation": "$Cl_2$ có số OXH ban đầu là 0. Sau phản ứng tạo ra $Cl^{-1}$ (trong NaCl, giảm) và $Cl^{+1}$ (trong NaClO, tăng). Vậy $Cl_2$ vừa thể hiện tính oxi hóa, vừa thể hiện tính khử (phản ứng tự oxi hóa - khử)."},
    {"id": "mc-c3-015", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Phản ứng nội OXH Khử",
     "question": "Trong phản ứng nhiệt phân muối Kali chlorate: $2KClO_3 \\xrightarrow{t^\\circ} 2KCl + 3O_2$. Phản ứng này thuộc loại phản ứng oxi hóa - khử nào?",
     "choices": ["Phản ứng oxi hóa - khử nội phân tử", "Phản ứng tự oxi hóa - khử", "Phản ứng oxi hóa - khử liên phân tử", "Không phải phản ứng oxi hóa khử"],
     "answer": 0, "explanation": "Chất oxi hóa và chất khử NẰM TRONG CÙNG MỘT PHÂN TỬ nhưng là CÁC NGUYÊN TỬ KHÁC NHAU. $Cl^{+5} \\rightarrow Cl^{-1}$ (giảm, Oxi hóa). $O^{-2} \\rightarrow O_2^0$ (tăng, Khử). Đây là phản ứng oxi hóa - khử nội phân tử."},
    {"id": "mc-c3-016", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Lập luận tính chất",
     "question": "Dựa vào mức oxi hóa lớn nhất và nhỏ nhất, nguyên tử hoặc ion nào sau đây CHỈ CÓ tính oxi hóa (không có tính khử)?",
     "choices": ["$Fe^{3+}$", "$Fe^{2+}$", "$S^{2-}$", "$Cl_2$"],
     "answer": 0, "explanation": "Tính oxi hóa $\\sim$ nhận electron $\\sim$ số OXH giảm. Để CHỈ có tính oxi hóa (chỉ có thể giảm, không thể tăng nữa), nó phải đang ở SỐ OXI HÓA CAO NHẤT (Max). $Fe^{3+}$ là mức cao nhất của Fe, chỉ có thể giảm về +2, 0 $\\Rightarrow$ Chỉ có tính oxi hóa. (Ngược lại $S^{2-}$ thấp nhất chỉ có tính khử. $Fe^{2+}, Cl_2$ ở giữa, có cả hai tính)."},

    # Nhóm 7, 8, 9: Cân bằng phản ứng đơn giản
    {"id": "mc-c3-017", "chapter": "c3", "lesson": "b16", "level": "th", "dang": "Nguyên tắc thăng bằng",
     "question": "Nguyên tắc của phương pháp thăng bằng electron để cân bằng phương trình hóa học là:",
     "choices": ["Tổng số electron do chất khử nhường BẰNG tổng số electron do chất oxi hóa nhận", "Tổng số nguyên tử oxi trước và sau phản ứng bằng nhau", "Tổng khối lượng chất khử bằng tổng khối lượng chất oxi hóa", "Tổng số phân tử chất khử bằng tổng số phân tử chất oxi hóa"],
     "answer": 0, "explanation": "Định luật bảo toàn electron: Tổng e nhường = Tổng e nhận."},
    {"id": "mc-c3-018", "chapter": "c3", "lesson": "b16", "level": "th", "dang": "Cân bằng cơ bản 1",
     "question": "Hệ số cân bằng tối giản của phương trình $Al + O_2 \\rightarrow Al_2O_3$ lần lượt là:",
     "choices": ["4, 3, 2", "2, 3, 1", "4, 1, 2", "2, 1, 1"],
     "answer": 0, "explanation": "Nhường: $Al \\rightarrow Al^{3+} + 3e$. Nhận: $O_2 + 4e \\rightarrow 2O^{2-}$. Bội chung nhỏ nhất của 3 và 4 là 12. Nhân chéo: $4 \times (Al)$ và $3 \times (O_2)$. Phương trình: $4Al + 3O_2 \\rightarrow 2Al_2O_3$."},
    {"id": "mc-c3-019", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng có môi trường 1",
     "question": "Trong phương trình $Cu + HNO_3 \\text{ (loãng)} \\rightarrow Cu(NO_3)_2 + NO + H_2O$. Hệ số của $HNO_3$ sau khi cân bằng (với các hệ số là số nguyên nhỏ nhất) là:",
     "choices": ["8", "4", "6", "10"],
     "answer": 0, "explanation": "Nhường: $Cu \\rightarrow Cu^{+2} + 2e$. Nhận: $N^{+5} + 3e \\rightarrow N^{+2}$ (trong NO). Bội chung của 2 và 3 là 6. Hệ số: 3 Cu và 2 NO. Phương trình: $3Cu + x HNO_3 \\rightarrow 3Cu(NO_3)_2 + 2NO + H_2O$. Bảo toàn N: vế phải có $3 \times 2 + 2 = 8$ Nitơ. Vậy hệ số $HNO_3$ là 8. (Và 4 $H_2O$)."},
    {"id": "mc-c3-020", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Tổng hệ số",
     "question": "Cho phản ứng: $Zn + H_2SO_4 \\text{ (đặc, nóng)} \\rightarrow ZnSO_4 + SO_2 + H_2O$. Tổng các hệ số (nguyên, tối giản) của tất cả các chất trong phương trình là:",
     "choices": ["7", "6", "8", "9"],
     "answer": 0, "explanation": "$Zn \\rightarrow Zn^{+2} + 2e$. $S^{+6} + 2e \\rightarrow S^{+4}$. Hệ số 1 Zn và 1 SO2. PT: $1Zn + 2H_2SO_4 \\rightarrow 1ZnSO_4 + 1SO_2 + 2H_2O$. Tổng hệ số = $1 + 2 + 1 + 1 + 2 = 7$."},

    # Nhóm 10, 11, 12: Cân bằng phản ứng mức độ khá
    {"id": "mc-c3-021", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng Fe oxit",
     "question": "Cân bằng phương trình sau: $Fe_3O_4 + HNO_3 \\rightarrow Fe(NO_3)_3 + NO_2 + H_2O$. Hệ số của phân tử $HNO_3$ là:",
     "choices": ["10", "28", "8", "14"],
     "answer": 0, "explanation": "Trong $Fe_3O_4$, coi trung bình Fe là $+8/3$. Nhường: $3Fe^{+8/3} \\rightarrow 3Fe^{+3} + 1e$. Nhận: $N^{+5} + 1e \\rightarrow N^{+4}$ (NO2). Hệ số 1 $Fe_3O_4$ và 1 $NO_2$. PT: $1 Fe_3O_4 + 10 HNO_3 \\rightarrow 3 Fe(NO_3)_3 + 1 NO_2 + 5 H_2O$. Bảo toàn N: $3 \times 3 + 1 = 10$. Hệ số HNO3 là 10."},
    {"id": "mc-c3-022", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng tạo sản phẩm khử đôi",
     "question": "Khi cho Mg tác dụng với $HNO_3$ loãng thu được khí $N_2O$. Phương trình: $Mg + HNO_3 \\rightarrow Mg(NO_3)_2 + N_2O + H_2O$. Tổng hệ số của các chất tham gia phản ứng (vế trái) là:",
     "choices": ["14", "10", "15", "12"],
     "answer": 0, "explanation": "Mg $\\rightarrow$ Mg(+2) + 2e. 2N(+5) + 8e $\\rightarrow$ N2(+1). Bội chung là 8. $\\Rightarrow$ 4 Mg và 1 N2O. PT: $4 Mg + 10 HNO_3 \\rightarrow 4 Mg(NO_3)_2 + 1 N_2O + 5 H_2O$. Vế trái gồm 4 Mg và 10 HNO3. Tổng = 14."},
    {"id": "mc-c3-023", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Lập tỉ lệ sản phẩm khử",
     "question": "Hòa tan hỗn hợp nhôm vào $HNO_3$ loãng thu được hỗn hợp khí NO và $N_2O$ với tỉ lệ mol 1:1. Số electron do $HNO_3$ nhận trung bình cho 1 mol hỗn hợp khí này là:",
     "choices": ["11 mol", "5,5 mol", "3 mol", "8 mol"],
     "answer": 0, "explanation": "Để tạo 1 mol NO cần nhận 3 mol e. Để tạo 1 mol N2O cần nhận 8 mol e. Hỗn hợp tỉ lệ 1:1 $\\Rightarrow$ Trung bình tạo 1 mol khí cần $(3+8)/2 = 5,5$ mol electron."},
    {"id": "mc-c3-024", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng với KMnO4",
     "question": "Trong phản ứng: $KMnO_4 + HCl \\rightarrow KCl + MnCl_2 + Cl_2 + H_2O$. Hệ số của HCl đóng vai trò chất khử (bị oxi hóa) là bao nhiêu phần tổng số HCl phản ứng?",
     "choices": ["5/8", "10/16", "2/16", "Chỉ 1 nửa"],
     "answer": 0, "explanation": "Mn(+7) + 5e $\\rightarrow$ Mn(+2). 2Cl(-1) $\\rightarrow$ Cl2(0) + 2e. Hệ số: 2 KMnO4 và 5 Cl2. PT: $2KMnO_4 + 16HCl \\rightarrow 2KCl + 2MnCl_2 + 5Cl_2 + 8H_2O$. Tổng 16 phân tử HCl tham gia, nhưng chỉ có $5 \times 2 = 10$ phân tử HCl (tạo 5 Cl2) là đóng vai trò chất khử. Tỉ lệ: 10/16 (hoặc 5/8). 6 HCl còn lại tạo muối KCl, MnCl2 đóng vai trò môi trường."},

    # Nhóm 13, 14: Tính toán thể tích, khối lượng cơ bản
    {"id": "mc-c3-025", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Tính khối lượng kim loại",
     "question": "Cho m gam bột sắt tác dụng hoàn toàn với dung dịch $H_2SO_4$ loãng dư, thu được 3,7185 lít khí $H_2$ (đkc, ở 25 độ C, 1 bar). Giá trị của m là: (Biết 1 mol khí đkc = 24,79 lít, Fe = 56)",
     "choices": ["8,4 gam", "5,6 gam", "2,8 gam", "11,2 gam"],
     "answer": 0, "explanation": "$n_{H_2} = 3,7185 / 24,79 = 0,15$ mol. Fe tác dụng acid loãng tạo $Fe^{2+}$ và $H_2$. Bảo toàn electron: $n_{Fe} \times 2 = n_{H_2} \times 2 \Rightarrow n_{Fe} = 0,15$ mol. Khối lượng m = $0,15 \times 56 = 8,4$ gam."},
    {"id": "mc-c3-026", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bài toán nhường nhận electron",
     "question": "Hòa tan hoàn toàn 2,7 gam nhôm (Al) bằng dung dịch $HNO_3$ loãng dư thu được V lít (đkc) khí NO (sản phẩm khử duy nhất). Giá trị của V là: (1 mol đkc = 24,79L)",
     "choices": ["2,479 lít", "4,958 lít", "7,437 lít", "1,2395 lít"],
     "answer": 0, "explanation": "$n_{Al} = 2,7 / 27 = 0,1$ mol. Al nhường 3e $\\Rightarrow n_e$ nhường = 0,3 mol. NO là sản phẩm khử: $N^{+5} + 3e \\rightarrow N^{+2}$. $n_{NO} = n_e / 3 = 0,3 / 3 = 0,1$ mol. Thể tích $V = 0,1 \times 24,79 = 2,479$ lít."},
    {"id": "mc-c3-027", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bảo toàn e hỗn hợp kim loại",
     "question": "Cho hỗn hợp gồm 0,1 mol Fe và 0,05 mol Cu tác dụng hoàn toàn với dung dịch $H_2SO_4$ đặc, nóng, dư. Thể tích khí $SO_2$ (sản phẩm khử duy nhất, ở đkc 25C 1 bar) thu được là:",
     "choices": ["4,958 lít", "7,437 lít", "6,197 lít", "9,916 lít"],
     "answer": 0, "explanation": "Fe lên Fe(+3) nhường 3e $\\Rightarrow 0,1 \\times 3 = 0,3$ mol. Cu lên Cu(+2) nhường 2e $\\Rightarrow 0,05 \\times 2 = 0,1$ mol. Tổng e nhường = 0,4 mol. $S^{+6} + 2e \\rightarrow SO_2$. Bảo toàn e: $2 n_{SO_2} = 0,4 \Rightarrow n_{SO_2} = 0,2$ mol. Thể tích = $0,2 \\times 24,79 = 4,958$ lít."},
    {"id": "mc-c3-028", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Xác định muối sau phản ứng",
     "question": "Đốt cháy hoàn toàn 2,4 gam Magie (Mg) trong khí Oxi dư, sau đó hòa tan chất rắn sinh ra vào lượng dư dung dịch HCl. Khối lượng muối clorua thu được là:",
     "choices": ["9,5 gam", "4,75 gam", "19,0 gam", "14,25 gam"],
     "answer": 0, "explanation": "$n_{Mg} = 2,4 / 24 = 0,1$ mol. $Mg \\rightarrow MgO \\rightarrow MgCl_2$. Bảo toàn nguyên tố Mg: $n_{MgCl_2} = n_{Mg} = 0,1$ mol. Khối lượng muối = $0,1 \times (24 + 71) = 9,5$ gam."},

    # Nhóm 15, 16: Phân loại phản ứng hóa học
    {"id": "mc-c3-029", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Phân loại PƯ",
     "question": "Phản ứng nào sau đây LUÔN LUÔN là phản ứng oxi hóa - khử?",
     "choices": ["Phản ứng thế", "Phản ứng phân hủy", "Phản ứng hóa hợp", "Phản ứng trao đổi"],
     "answer": 0, "explanation": "Phản ứng thế là phản ứng giữa đơn chất và hợp chất ($A + BC \\rightarrow AC + B$). Vì có sự xuất hiện đơn chất trước và sau phản ứng (số OXH 0) nên chắc chắn có sự thay đổi số OXH $\\Rightarrow$ Luôn là PƯ OXH-Khử."},
    {"id": "mc-c3-030", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Nhận biết PƯ trao đổi",
     "question": "Phản ứng nào sau đây KHÔNG PHẢI là phản ứng oxi hóa - khử?",
     "choices": ["$CaCO_3 + 2HCl \\rightarrow CaCl_2 + CO_2 + H_2O$", "$Zn + 2HCl \\rightarrow ZnCl_2 + H_2$", "$2KClO_3 \\rightarrow 2KCl + 3O_2$", "$C + O_2 \\rightarrow CO_2$"],
     "answer": 0, "explanation": "Phản ứng đầu tiên là phản ứng của muối cacbonat với axit (trao đổi) tạo ra axit carbonic không bền (phân hủy ra $CO_2$ và $H_2O$). Không có sự thay đổi số oxi hóa của bất kì nguyên tố nào. Các phản ứng còn lại đều có sinh ra hoặc tiêu thụ đơn chất ($H_2, O_2, C$)."},
    {"id": "mc-c3-031", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Nhận biết PƯ phân hủy đặc biệt",
     "question": "Phản ứng phân hủy nào sau đây là phản ứng oxi hóa - khử?",
     "choices": ["$2KNO_3 \\xrightarrow{t^\\circ} 2KNO_2 + O_2$", "$Cu(OH)_2 \\xrightarrow{t^\\circ} CuO + H_2O$", "$CaCO_3 \\xrightarrow{t^\\circ} CaO + CO_2$", "$2NaHCO_3 \\xrightarrow{t^\\circ} Na_2CO_3 + CO_2 + H_2O$"],
     "answer": 0, "explanation": "Nhiệt phân muối Nitrat tạo ra đơn chất Oxi ($O_2$), do đó $O^{-2} \\rightarrow O^0$ và $N^{+5} \\rightarrow N^{+3}$, là phản ứng oxh-khử nội phân tử. Các PƯ còn lại nhiệt phân hidroxit, muối cacbonat không có sự thay đổi số OXH."},
    {"id": "mc-c3-032", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Sự oxi hóa kim loại",
     "question": "Sự gỉ của sắt trong không khí ẩm ($4Fe + 3O_2 + 6H_2O \\rightarrow 4Fe(OH)_3$) là ví dụ thực tế của hiện tượng nào?",
     "choices": ["Sự oxi hóa kim loại", "Sự khử kim loại", "Sự thăng hoa", "Sự kết tinh"],
     "answer": 0, "explanation": "Fe (số oxh 0) bị $O_2$ lấy mất electron chuyển thành $Fe^{3+}$. Đây là quá trình (sự) oxi hóa kim loại sinh ra gỉ sắt."},

    # Nhóm 17, 18, 19: Pin điện hóa cơ bản, Thế điện cực (Nếu có trong chương trình mới)
    {"id": "mc-c3-033", "chapter": "c3", "lesson": "b17", "level": "nb", "dang": "Khái niệm năng lượng",
     "question": "Phản ứng oxi hóa - khử thường kèm theo sự trao đổi năng lượng dưới hình thức nào?",
     "choices": ["Phát sáng, tỏa nhiệt hoặc sinh ra dòng điện", "Chỉ sinh ra dòng điện", "Chỉ hấp thụ nhiệt", "Hoàn toàn không trao đổi năng lượng"],
     "answer": 0, "explanation": "PƯ oxh-khử có thể gây nổ, tỏa nhiệt (cháy), phát sáng (cháy Mg), hoặc ứng dụng để tạo ra dòng điện một chiều trong pin điện hóa."},
    {"id": "mc-c3-034", "chapter": "c3", "lesson": "b17", "level": "th", "dang": "Cấu tạo pin Galvani",
     "question": "Trong pin điện hóa (ví dụ pin Zn-Cu), dòng electron di chuyển như thế nào ở mạch ngoài?",
     "choices": ["Từ cực âm (anode, nơi xảy ra sự oxi hóa Zn) sang cực dương (cathode, nơi xảy ra sự khử $Cu^{2+}$)", "Từ cực dương sang cực âm", "Di chuyển 2 chiều qua lại", "Chạy từ dung dịch lên dây dẫn điện"],
     "answer": 0, "explanation": "Kẽm (Zn) hoạt động mạnh hơn, đóng vai trò Anode (cực âm). Tại Anode: Zn nhường e ($Zn \\rightarrow Zn^{2+} + 2e$). Electron sinh ra chạy qua dây dẫn (mạch ngoài) sang Cathode (cực dương bằng Cu). Tại Cathode, $Cu^{2+}$ nhận e."},
    {"id": "mc-c3-035", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Xác định Anode Cathode",
     "question": "Khi ghép một nửa pin nhúng thanh Mg vào dung dịch $MgSO_4$ và một nửa pin nhúng thanh Ag vào dung dịch $AgNO_3$, thanh kim loại nào đóng vai trò là Anode (cực âm)?",
     "choices": ["Thanh Magnesium (Mg)", "Thanh Silver (Ag)", "Cả hai đều là cực âm", "Không xác định được"],
     "answer": 0, "explanation": "Kim loại có tính khử mạnh hơn (đứng trước trong dãy hoạt động hóa học) dễ nhường e hơn sẽ làm Anode (-). Mg mạnh hơn Ag nhiều nên Mg là Anode."},
    {"id": "mc-c3-036", "chapter": "c3", "lesson": "b17", "level": "vd", "dang": "Cầu muối",
     "question": "Vai trò chính của cầu muối trong pin điện hóa (pin Galvani) là gì?",
     "choices": ["Trung hòa điện tích của hai dung dịch ở hai nửa pin, khép kín mạch điện", "Cung cấp electron cho cực dương", "Tạo ra dòng điện xoay chiều", "Ngăn chặn các electron di chuyển"],
     "answer": 0, "explanation": "Khi pin hoạt động, một bên (Anode) tích tụ nhiều cation ($Zn^{2+}$), bên kia (Cathode) bị mất cation ($Cu^{2+}$) dư anion ($SO_4^{2-}$). Cầu muối (chứa dung dịch $KCl$ hoặc $KNO_3$...) sẽ di chuyển các ion để trung hòa điện tích 2 bên, giúp pin liên tục hoạt động (kín mạch)."},

    # Nhóm 20, 21: Halogen - Mở rộng Oxh-Khử
    {"id": "mc-c3-037", "chapter": "c3", "lesson": "b18", "level": "th", "dang": "Tính OXH Halogen",
     "question": "Tính oxi hóa của các đơn chất halogen biến đổi như thế nào khi đi từ Fluorine đến Iodine?",
     "choices": ["Giảm dần", "Tăng dần", "Không thay đổi", "Tăng rồi giảm"],
     "answer": 0, "explanation": "Từ $F_2$ đến $I_2$, độ âm điện giảm dần, bán kính nguyên tử tăng dần, khả năng nhận electron (tính oxi hóa) giảm dần. $F_2$ là chất oxi hóa mạnh nhất trong tự nhiên."},
    {"id": "mc-c3-038", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Phản ứng đẩy Halogen",
     "question": "Cho khí Chlorine ($Cl_2$) sục vào dung dịch Sodium bromide ($NaBr$). Hiện tượng xảy ra và bản chất phản ứng là:",
     "choices": ["Dung dịch chuyển sang màu vàng nâu, do $Cl_2$ có tính oxi hóa mạnh hơn đã oxi hóa ion $Br^-$ thành $Br_2$", "Có kết tủa trắng tạo thành", "Không có hiện tượng gì, $Cl_2$ yếu hơn Br", "Dung dịch sủi bọt khí mạnh, $Cl_2$ bị khử thành HCl"],
     "answer": 0, "explanation": "Tính oxi hóa $Cl_2 > Br_2$. Phương trình: $Cl_2 + 2NaBr \\rightarrow 2NaCl + Br_2$. $Br_2$ sinh ra tan trong nước tạo dung dịch màu vàng da cam/vàng nâu."},
    {"id": "mc-c3-039", "chapter": "c3", "lesson": "b18", "level": "vd", "dang": "Bài tập hiệu suất đẩy Halogen",
     "question": "Dẫn 1,2395 lít khí $Cl_2$ (đkc) đi qua dung dịch chứa 15 gam NaI. Tính khối lượng $I_2$ sinh ra sau phản ứng? (Na=23, I=127, Cl=35.5)",
     "choices": ["12,7 gam", "25,4 gam", "1,27 gam", "7,62 gam"],
     "answer": 0, "explanation": "Mol $Cl_2 = 1,2395 / 24,79 = 0,05$ mol. Mol $NaI = 15 / 150 = 0,1$ mol. Phản ứng: $Cl_2 + 2NaI \\rightarrow 2NaCl + I_2$. Tỉ lệ $1:2 \Rightarrow$ Phản ứng vừa đủ. $n_{I_2} = n_{Cl_2} = 0,05$ mol. Khối lượng $I_2 = 0,05 \times (127 \times 2) = 12,7$ gam."},
    {"id": "mc-c3-040", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Cân bằng PƯ phức",
     "question": "Hệ số cân bằng (số nguyên tối giản) của $H_2SO_4$ trong phản ứng: $FeSO_4 + KMnO_4 + H_2SO_4 \\rightarrow Fe_2(SO_4)_3 + MnSO_4 + K_2SO_4 + H_2O$ là:",
     "choices": ["8", "10", "4", "6"],
     "answer": 0, "explanation": "$Fe^{+2} \\rightarrow Fe^{+3} + 1e$. (Vì sản phẩm là $Fe_2(SO_4)_3$ nên viết $2Fe^{+2} \\rightarrow 2Fe^{+3} + 2e$). $Mn^{+7} + 5e \\rightarrow Mn^{+2}$. Nhân chéo: $5 \times (2Fe)$ và $2 \times (Mn)$. Tức là 10 $FeSO_4$ và 2 $KMnO_4$. Sản phẩm: 5 $Fe_2(SO_4)_3$ + 2 $MnSO_4$ + 1 $K_2SO_4$. Tổng gốc $SO_4$ vế phải = $5 \times 3 + 2 \times 1 + 1 \times 1 = 18$ gốc. Trừ đi 10 gốc ở FeSO4 bên trái, còn lại 8 gốc $SO_4$ phải do $H_2SO_4$ cung cấp. Vậy hệ số $H_2SO_4$ là 8."},

    # Nhóm 22, 23: Bài toán bảo toàn Electron phức tạp hơn
    {"id": "mc-c3-041", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bảo toàn e nhiều giai đoạn",
     "question": "Để khử hoàn toàn 8 gam $CuO$ bằng khí $CO$ ở nhiệt độ cao, thu được hỗn hợp rắn X (gồm Cu và CuO dư). Hòa tan hoàn toàn X trong dung dịch $HNO_3$ đặc, nóng, dư thu được V lít khí $NO_2$ (đkc, sản phẩm khử duy nhất). Tính V? (Cu=64, O=16)",
     "choices": ["4,958 lít", "2,479 lít", "7,437 lít", "1,12 lít"],
     "answer": 0, "explanation": "Bài này có thể giải ngắn gọn: Dù CO khử một phần hay toàn bộ, hỗn hợp X khi tác dụng với HNO3 sẽ nhường lại chính số electron mà nó đã nhận từ CO. Số e đó = số e mà $O$ trong CuO đã bị lấy đi. Tóm lại, quy đổi hỗn hợp đầu cuối tương đương nhau. Thể tích $NO_2$ tương ứng với số e của Cu: $0,1 \\times 2 = 0,2$ mol (nếu quy toàn bộ hỗn hợp)."},
    {"id": "mc-c3-042", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Hỗn hợp kim loại 2",
     "question": "Hòa tan hỗn hợp gồm 0,1 mol Mg và 0,1 mol Al vào dung dịch $HNO_3$ loãng dư, thu được khí $NO$ (sản phẩm khử duy nhất). Số mol khí NO thu được là:",
     "choices": ["0,167 mol", "0,5 mol", "0,25 mol", "0,15 mol"],
     "answer": 0, "explanation": "Tổng e nhường: $n_e = 0,1 \times 2 (Mg) + 0,1 \times 3 (Al) = 0,5$ mol. Quá trình nhận e: $N^{+5} + 3e \\rightarrow N^{+2} (NO)$. Bảo toàn e: $3 \cdot n_{NO} = 0,5 \Rightarrow n_{NO} = 0,5 / 3 \approx 0,167$ mol."},
    {"id": "mc-c3-043", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Lập luận tỉ lệ hệ số",
     "question": "Khi cân bằng phản ứng: $Al + HNO_3 \\rightarrow Al(NO_3)_3 + N_2O + NO + H_2O$. Biết tỉ lệ thể tích khí sinh ra là $V(N_2O) : V(NO) = 1 : 3$. Tỉ lệ hệ số của $Al$ và $HNO_3$ trong phương trình (đã cân bằng) là:",
     "choices": ["17 : 66", "1 : 4", "8 : 30", "17 : 60"],
     "answer": 0, "explanation": "Hỗn hợp khí tỉ lệ 1:3 $\\Rightarrow$ Coi hỗn hợp có $1 N_2O$ (nhận 8e) và $3 NO$ (mỗi NO nhận 3e, tổng 9e). Tổng e nhận là $8 + 9 = 17e$. Nhường: $Al \\rightarrow Al^{3+} + 3e$. Nhân chéo: 17 Al và 3(Cụm khí). Cụm khí gồm $3 N_2O$ và $9 NO$. Phương trình: $17 Al + x HNO_3 \\rightarrow 17 Al(NO_3)_3 + 3 N_2O + 9 NO + y H_2O$. Bảo toàn N: $N = 17 \times 3 + 3 \times 2 + 9 \times 1 = 51 + 6 + 9 = 66$. Tỉ lệ $Al : HNO_3 = 17 : 66$."},
    {"id": "mc-c3-044", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Cân bằng ion thu gọn",
     "question": "Cho phản ứng oxi hóa - khử theo phương trình ion thu gọn: $a Cu + b NO_3^- + c H^+ \\rightarrow d Cu^{2+} + e NO + f H_2O$. Tổng $(a+b+c)$ sau khi cân bằng (các hệ số nguyên tối giản) là:",
     "choices": ["13", "11", "9", "10"],
     "answer": 0, "explanation": "$Cu \\rightarrow Cu^{2+} + 2e$. $NO_3^- + 3e + 4H^+ \\rightarrow NO + 2H_2O$. Nhân chéo: 3 Cu và 2 ($NO_3^-$). PT: $3Cu + 2NO_3^- + 8H^+ \\rightarrow 3Cu^{2+} + 2NO + 4H_2O$. Tổng a+b+c = $3 + 2 + 8 = 13$."},

    # Nhóm 24, 25: Ứng dụng Oxi hóa khử
    {"id": "mc-c3-045", "chapter": "c3", "lesson": "b15", "level": "nb", "dang": "Thực tiễn Oxi hóa khử",
     "question": "Quá trình nào sau đây KHÔNG PHẢI là quá trình oxi hóa - khử trong tự nhiên và kĩ thuật?",
     "choices": ["Quá trình bay hơi của nước mưa", "Quá trình quang hợp của cây xanh", "Quá trình đốt cháy nhiên liệu (than, xăng dầu)", "Sự hô hấp của sinh vật"],
     "answer": 0, "explanation": "Bay hơi nước là sự chuyển pha vật lí (từ lỏng sang khí), không có sự thay đổi cấu trúc phân tử hay số oxi hóa. Quang hợp ($CO_2 + H_2O \\rightarrow C_6H_{12}O_6 + O_2$), đốt cháy và hô hấp đều là chuỗi phản ứng oxi hóa - khử sinh hóa."},
    {"id": "mc-c3-046", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Sự ăn mòn",
     "question": "Sự ăn mòn kim loại là sự phá hủy kim loại hoặc hợp kim do tác dụng của các chất trong môi trường xung quanh. Bản chất của sự ăn mòn kim loại là:",
     "choices": ["Quá trình oxi hóa - khử, trong đó kim loại bị oxi hóa thành ion dương", "Quá trình trao đổi chất rắn", "Quá trình vật lí do ma sát", "Phản ứng axit - bazơ"],
     "answer": 0, "explanation": "Kim loại dễ nhường e ($M \\rightarrow M^{n+} + ne$), bị các tác nhân của môi trường (O2, hơi nước, chất điện li) cướp electron $\\Rightarrow$ Kim loại bị oxi hóa, phá vỡ cấu trúc mạng tinh thể."},
    {"id": "mc-c3-047", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Chống ăn mòn",
     "question": "Để bảo vệ vỏ tàu biển làm bằng thép (hợp kim của Sắt), người ta thường gắn những khối kim loại nào sau đây vào phần vỏ tàu chìm dưới nước (phương pháp bảo vệ điện hóa)?",
     "choices": ["Zinc (Zn - Kẽm)", "Copper (Cu - Đồng)", "Silver (Ag - Bạc)", "Lead (Pb - Chì)"],
     "answer": 0, "explanation": "Theo nguyên tắc bảo vệ điện hóa, kim loại bảo vệ (vật hi sinh) phải có tính khử MẠNH HƠN kim loại cần bảo vệ (Sắt). Trong dãy hoạt động, Zn đứng trước Fe nên Zn sẽ bị oxi hóa (nhường e, bị ăn mòn) thay cho Fe."},
    {"id": "mc-c3-048", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Ứng dụng chất chống oxi hóa",
     "question": "Vitamin C (Ascorbic acid) thường được thêm vào thực phẩm đóng hộp để bảo quản. Vai trò hóa học chính của Vitamin C trong trường hợp này là:",
     "choices": ["Là chất khử mạnh, nó sẽ phản ứng với các tác nhân oxi hóa (như $O_2$) thay cho thực phẩm, bảo vệ thực phẩm khỏi bị ôi thiu", "Là chất oxi hóa mạnh để tiêu diệt vi khuẩn", "Tạo môi trường bazơ", "Đóng vai trò xúc tác"],
     "answer": 0, "explanation": "Vitamin C là chất chống oxi hóa (antioxidant) tự nhiên, bản thân nó là một chất khử dễ bị oxi hóa. Nó sẽ hi sinh bản thân phản ứng với gốc tự do và oxi không khí trước khi chúng kịp phá hủy tế bào/thực phẩm."},

    # 12 Câu bổ sung củng cố (26, 27, 28, 29, 30)
    {"id": "mc-c3-049", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Tính chất Mangan",
     "question": "Trong hợp chất $KMnO_4$, Mangan có số oxi hóa cao nhất là +7. Phát biểu nào sau đây đúng về khả năng phản ứng của $KMnO_4$?",
     "choices": ["Chỉ thể hiện tính oxi hóa", "Vừa thể hiện tính oxi hóa, vừa thể hiện tính khử", "Chỉ thể hiện tính khử", "Không thể tham gia phản ứng oxi hóa khử"],
     "answer": 0, "explanation": "Mn có số OXH lớn nhất là +7. Ở mức Max này, nó không thể nhường thêm electron nào nữa $\\Rightarrow$ KHÔNG có tính khử, chỉ có thể NHẬN e (giảm số OXH) $\\Rightarrow$ Chỉ có tính oxi hóa (rất mạnh)."},
    {"id": "mc-c3-050", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng với ẩn số",
     "question": "Cho phản ứng: $Fe_xO_y + HNO_3 \\rightarrow Fe(NO_3)_3 + NO + H_2O$. Hệ số của $Fe_xO_y$ trong phương trình cân bằng là:",
     "choices": ["3", "1", "3x-2y", "x"],
     "answer": 0, "explanation": "Trong $Fe_xO_y$, trung bình 1 nguyên tử Fe có số OXH là $+2y/x$. Có x nguyên tử Fe $\\Rightarrow$ nhường tổng cộng: $x \cdot (+3 - 2y/x) = 3x - 2y$ electron. Nhận: N(+5) + 3e $\\rightarrow$ N(+2). Nhân chéo: 3 vào Fe (nghĩa là 3 $Fe_xO_y$) và $(3x-2y)$ vào NO. Vậy hệ số của $Fe_xO_y$ là 3."},
    {"id": "mc-c3-051", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Xác định nhanh số OXH",
     "question": "Số oxi hóa của Nitrogen trong ion Amoni ($NH_4^+$) là:",
     "choices": ["-3", "+5", "+3", "-1"],
     "answer": 0, "explanation": "H là +1. Gọi số OXH của N là x. $x + 4(+1) = +1 \Rightarrow x + 4 = 1 \Rightarrow x = -3$."},
    {"id": "mc-c3-052", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Lập luận nhiệt độ",
     "question": "Phản ứng tỏa nhiệt là phản ứng có:",
     "choices": ["$\Delta_r H < 0$ (biến thiên enthalpy âm), hệ thống giải phóng nhiệt ra môi trường", "$\Delta_r H > 0$, hệ thống hấp thu nhiệt", "$\Delta_r H = 0$", "Sản phẩm lạnh hơn chất tham gia"],
     "answer": 0, "explanation": "Quy ước Nhiệt động lực học: Tỏa nhiệt (mất đi năng lượng dự trữ để đẩy ra ngoài) $\\Rightarrow$ Enthalpy H giảm $\\Rightarrow \Delta H < 0$."},
    
    {"id": "mc-c3-053", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Chất vừa oxh vừa khử",
     "question": "Chất nào sau đây có thể vừa thể hiện tính oxi hóa, vừa thể hiện tính khử trong các phản ứng hóa học?",
     "choices": ["$SO_2$", "$H_2SO_4$ đặc", "$H_2S$", "$F_2$"],
     "answer": 0, "explanation": "Lưu huỳnh trong $SO_2$ có số OXH là +4, là trạng thái trung gian giữa Min (-2 trong H2S) và Max (+6 trong H2SO4). Do đó S(+4) có thể giảm về 0, -2 (tính oxi hóa) hoặc tăng lên +6 (tính khử)."},
    {"id": "mc-c3-054", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng phản ứng Cl2",
     "question": "Cân bằng phương trình: $Cl_2 + KOH \\xrightarrow{t^\\circ} KCl + KClO_3 + H_2O$. Hệ số của $Cl_2$ là:",
     "choices": ["3", "1", "2", "6"],
     "answer": 0, "explanation": "Phản ứng đun nóng: $Cl_2$ từ 0 giảm xuống -1 (KCl) và tăng lên +5 (KClO3). Quá trình nhường: $Cl_2^0 \\rightarrow 2Cl^{+5} + 10e$. Quá trình nhận: $Cl_2^0 + 2e \\rightarrow 2Cl^{-1}$. Bội chung là 10. Tỉ lệ quá trình nhường/nhận là 1:5. $\\Rightarrow 1 Cl_2$ tạo KClO3 và 5 $Cl_2$ tạo KCl. Tổng cộng cần 6 phân tử $Cl_2$ tham gia. Chia đôi tất cả hệ số: 3 Cl2 + 6 KOH $\\rightarrow$ 5 KCl + 1 KClO3 + 3 H2O. Hệ số Cl2 là 3."},
    
    {"id": "mc-c3-055", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Cân bằng O3",
     "question": "Ozone ($O_3$) có tính oxi hóa rất mạnh, mạnh hơn cả $O_2$. Nó có thể oxi hóa bạc (Ag) ở nhiệt độ thường (phản ứng mà $O_2$ không làm được). Phương trình phản ứng là: $Ag + O_3 \\rightarrow Ag_2O + O_2$. Chất bị khử trong phản ứng này là:",
     "choices": ["$O_3$", "Ag", "$Ag_2O$", "$O_2$"],
     "answer": 0, "explanation": "Ag từ 0 $\\rightarrow$ +1 (nhường e, chất khử $\\Rightarrow$ bị oxi hóa). $O_3$ từ 0 $\\rightarrow$ -2 (trong Ag2O) (nhận e, chất oxi hóa $\\Rightarrow$ chất BỊ KHỬ)."},
    {"id": "mc-c3-056", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Tính khối lượng muối Nitrat",
     "question": "Cho 6,4 gam Cu tác dụng hoàn toàn với dung dịch $HNO_3$ đặc, dư, đun nóng. Khối lượng muối $Cu(NO_3)_2$ sinh ra là bao nhiêu? (Cu=64, N=14, O=16)",
     "choices": ["18,8 gam", "9,4 gam", "12,8 gam", "16,0 gam"],
     "answer": 0, "explanation": "Mol Cu = 6,4 / 64 = 0,1 mol. Bảo toàn nguyên tố Cu (Cu chuyển hết thành muối): $n_{Cu(NO_3)_2} = 0,1$ mol. Phân tử khối của $Cu(NO_3)_2 = 64 + (14 + 16 \times 3) \times 2 = 64 + 124 = 188$. Khối lượng = $0,1 \times 188 = 18,8$ gam."},
    
    {"id": "mc-c3-057", "chapter": "c3", "lesson": "b15", "level": "vd", "dang": "Hợp chất sắt",
     "question": "Chất nào sau đây tác dụng với dung dịch $H_2SO_4$ đặc, nóng KHÔNG tạo ra khí $SO_2$?",
     "choices": ["$Fe_2O_3$", "Fe", "$FeO$", "$Fe_3O_4$"],
     "answer": 0, "explanation": "$H_2SO_4$ đặc nóng là chất oxi hóa mạnh, sẽ oxi hóa các hợp chất Sắt có số OXH thấp (như $Fe, FeO, Fe_3O_4$) lên mức cao nhất $Fe^{3+}$, sinh ra sản phẩm khử $SO_2$. Tuy nhiên $Fe_2O_3$ (Sắt đã ở mức +3 cao nhất) thì không thể bị oxi hóa thêm, nên chỉ xảy ra phản ứng trao đổi tạo muối nước (không sinh $SO_2$)."},
    {"id": "mc-c3-058", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Bảo toàn e H2S",
     "question": "Sục khí $H_2S$ vào dung dịch $KMnO_4$ (môi trường $H_2SO_4$) thấy dung dịch mất màu thuốc tím và xuất hiện vẩn đục màu vàng. Chất tạo thành vẩn đục màu vàng là:",
     "choices": ["Lưu huỳnh đơn chất (S)", "$K_2S$", "$MnS$", "$MnO_2$"],
     "answer": 0, "explanation": "Kết tủa vàng đặc trưng của phản ứng oxi hóa chậm H2S là Lưu huỳnh (S)."},
    {"id": "mc-c3-059", "chapter": "c3", "lesson": "b16", "level": "vd", "dang": "Cân bằng thuốc tím + H2S",
     "question": "Hệ số của $KMnO_4$ và $H_2S$ trong phương trình: $KMnO_4 + H_2S + H_2SO_4 \\rightarrow K_2SO_4 + MnSO_4 + S \\downarrow + H_2O$ là:",
     "choices": ["2 và 5", "5 và 2", "1 và 3", "2 và 3"],
     "answer": 0, "explanation": "Quá trình: $Mn^{+7} + 5e \\rightarrow Mn^{+2}$. $S^{-2} \\rightarrow S^0 + 2e$. Bội chung 10 $\\Rightarrow$ Nhân 2 vào Mn và 5 vào S. Tức là 2 $KMnO_4$ và 5 $H_2S$."},
    {"id": "mc-c3-060", "chapter": "c3", "lesson": "b15", "level": "th", "dang": "Khái niệm năng lượng phân li",
     "question": "Năng lượng cần thiết để bẻ gãy 1 mol liên kết trong phân tử ở thể khí (tạo thành các nguyên tử ở thể khí) được gọi là:",
     "choices": ["Năng lượng phân li liên kết", "Nhiệt hình thành tiêu chuẩn", "Nhiệt thăng hoa", "Nhiệt dung riêng"],
     "answer": 0, "explanation": "Đó chính là định nghĩa của Năng lượng phân li liên kết (Bond Dissociation Energy - BDE), thường kí hiệu là D hoặc $E_b$."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C3 Part 1 written successfully.")
