import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 28: ĐỘNG LƯỢNG VÀ BẢO TOÀN ĐỘNG LƯỢNG (PHẦN MỞ RỘNG VÀ VA CHẠM) ---
    # Nhóm 16: Nhắc lại xung lượng & động lượng
    {"id": "mc-c3-061", "chapter": "c3", "lesson": "b28", "level": "nb", "dang": "Xung lượng",
     "question": "Phát biểu nào sau đây nói đúng về sự liên hệ giữa xung lượng của lực và độ biến thiên động lượng?",
     "choices": ["Xung lượng của tổng hợp các lực tác dụng lên vật bằng độ biến thiên động lượng của vật", "Xung lượng của lực luôn bằng động lượng ban đầu", "Lực càng lớn thì động lượng càng nhỏ", "Độ biến thiên động lượng bằng công của lực"],
     "answer": 0, "explanation": "$\\vec{F}\\Delta t = \\Delta \\vec{p}$. Đây là cách biểu diễn định luật 2 Newton theo động lượng."},
    {"id": "mc-c3-062", "chapter": "c3", "lesson": "b28", "level": "th", "dang": "Va chạm",
     "question": "Tại sao các ô tô hiện đại thường được thiết kế phần đầu xe dễ bị móp méo khi xảy ra va chạm?",
     "choices": ["Để kéo dài thời gian va chạm, qua đó làm giảm lực va chạm truyền vào cabin, bảo vệ người ngồi trong xe", "Để giảm khối lượng xe", "Để xe bị bật ngược lại nhanh hơn", "Để tạo ra va chạm đàn hồi hoàn toàn"],
     "answer": 0, "explanation": "Vì $\\Delta p = F \\cdot \\Delta t$. $\\Delta p$ khi dừng lại là cố định. Phần đầu xe dễ móp méo sẽ làm tăng $\\Delta t$ (thời gian va chạm), từ đó giảm lực $F$ tác dụng vào xe."},
    {"id": "mc-c3-063", "chapter": "c3", "lesson": "b28", "level": "th", "dang": "Động lượng",
     "question": "Một vật khối lượng $m$ chuyển động với vận tốc $v$, một vật khác khối lượng $m/2$ chuyển động cùng phương, ngược chiều với vận tốc $2v$. Tổng động lượng của hệ hai vật này là:",
     "choices": ["0", "$2mv$", "$mv$", "$-mv$"],
     "answer": 0, "explanation": "Chọn chiều dương là chiều của vật m. $\\vec{p}_{\\text{hệ}} = m \\cdot v + (m/2) \\cdot (-2v) = mv - mv = 0$."},
    {"id": "mc-c3-064", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Tính toán xung lượng",
     "question": "Một quả bóng chày khối lượng 145g đang bay với tốc độ 40 m/s thì bị chày đập trúng và bay ngược lại với tốc độ 50 m/s. Thời gian tiếp xúc là 0.01s. Lực trung bình của chày tác dụng lên bóng là:",
     "choices": ["1305 N", "145 N", "130.5 N", "2610 N"],
     "answer": 0, "explanation": "$m = 0.145\\text{ kg}$. Chọn chiều dương là chiều bay ngược lại. $\\Delta v = 50 - (-40) = 90\\text{ m/s}$. $F = m\\Delta v / \\Delta t = 0.145 \\times 90 / 0.01 = 13.05 / 0.01 = 1305\\text{ N}."},

    # Nhóm 17: Va chạm đàn hồi
    {"id": "mc-c3-065", "chapter": "c3", "lesson": "b28", "level": "nb", "dang": "Va chạm đàn hồi",
     "question": "Trong va chạm đàn hồi (xuyên tâm) giữa hai vật, đại lượng nào được bảo toàn?",
     "choices": ["Cả động lượng và động năng", "Chỉ có động lượng", "Chỉ có động năng", "Cả động lượng và cơ năng nhưng không có động năng"],
     "answer": 0, "explanation": "Va chạm đàn hồi là va chạm lí tưởng, không có năng lượng chuyển hóa thành nhiệt hay biến dạng. Do đó, cả động lượng và động năng của hệ đều được bảo toàn."},
    {"id": "mc-c3-066", "chapter": "c3", "lesson": "b28", "level": "th", "dang": "Đặc điểm va chạm đàn hồi",
     "question": "Trong va chạm đàn hồi trực diện giữa vật 1 (đang chạy) và vật 2 (đang đứng yên) có CÙNG khối lượng. Sau va chạm thì:",
     "choices": ["Vật 1 dừng lại, vật 2 chuyển động với đúng vận tốc ban đầu của vật 1", "Hai vật dính vào nhau chuyển động với một nửa vận tốc ban đầu", "Cả hai bật ngược lại", "Vật 1 tiếp tục chuyển động với 1/2 vận tốc"],
     "answer": 0, "explanation": "Sự trao đổi vận tốc: Khi hai vật cùng khối lượng va chạm đàn hồi, chúng trao đổi vận tốc cho nhau. Nên 1 dừng, 2 chạy với $v_1$."},
    {"id": "mc-c3-067", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Tính va chạm đàn hồi",
     "question": "Bi A khối lượng 1kg chuyển động với vận tốc 5 m/s đến va chạm đàn hồi xuyên tâm với bi B khối lượng 2kg đang đứng yên. Vận tốc của bi A sau va chạm là:",
     "choices": ["-1,67 m/s", "1,67 m/s", "3,33 m/s", "-5 m/s"],
     "answer": 0, "explanation": "Công thức $v_1' = \\frac{(m_1-m_2)v_1 + 2m_2v_2}{m_1+m_2} = \\frac{(1-2)5 + 0}{3} = -5/3 \approx -1,67\\text{ m/s}$ (bật ngược lại)."},
    {"id": "mc-c3-068", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Tính va chạm đàn hồi",
     "question": "Tiếp tục bài toán trên, vận tốc của bi B (2kg) sau va chạm là:",
     "choices": ["3,33 m/s", "1,67 m/s", "5 m/s", "2 m/s"],
     "answer": 0, "explanation": "Công thức $v_2' = \\frac{(m_2-m_1)v_2 + 2m_1v_1}{m_1+m_2} = \\frac{0 + 2(1)(5)}{3} = 10/3 \approx 3,33\\text{ m/s}$."},

    # Nhóm 18: Va chạm mềm
    {"id": "mc-c3-069", "chapter": "c3", "lesson": "b28", "level": "nb", "dang": "Va chạm mềm",
     "question": "Trong va chạm mềm (va chạm không đàn hồi hoàn toàn), hai vật sau va chạm sẽ:",
     "choices": ["Dính vào nhau và chuyển động với cùng một vận tốc", "Bật ngược lại với vận tốc bằng nhau", "Trao đổi vận tốc cho nhau", "Bảo toàn hoàn toàn động năng"],
     "answer": 0, "explanation": "Va chạm mềm là va chạm mà sau đó 2 vật kết dính và chuyển động chung 1 vận tốc khối tâm."},
    {"id": "mc-c3-070", "chapter": "c3", "lesson": "b28", "level": "nb", "dang": "Bảo toàn trong va chạm mềm",
     "question": "Trong va chạm mềm, đại lượng nào LUÔN được bảo toàn?",
     "choices": ["Động lượng", "Động năng", "Vận tốc", "Nhiệt năng"],
     "answer": 0, "explanation": "Bất kì va chạm nào trong hệ kín (kể cả va chạm mềm) đều bảo toàn Động Lượng. Động năng thì không được bảo toàn (bị tiêu hao thành nhiệt, biến dạng dẻo)."},
    {"id": "mc-c3-071", "chapter": "c3", "lesson": "b28", "level": "th", "dang": "Tính toán va chạm mềm",
     "question": "Vật 1 có khối lượng m, đang chuyển động với vận tốc v. Vật 2 có khối lượng 2m đang đứng yên. Vật 1 đâm vào vật 2 và xảy ra va chạm mềm. Động năng của hệ sau va chạm bị giảm đi bao nhiêu phần trăm so với ban đầu?",
     "choices": ["66,7%", "50%", "33,3%", "100%"],
     "answer": 0, "explanation": "Vận tốc sau va chạm: $V = (mv) / (m+2m) = v/3$. Động năng ban đầu $W_1 = 0.5 mv^2$. Động năng sau $W_2 = 0.5(3m)(v/3)^2 = 0.5 \\cdot 3m \\cdot v^2/9 = \\frac{1}{3} (0.5 mv^2)$. Giảm đi $2/3$, tức là khoảng 66,7%."},
    {"id": "mc-c3-072", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Tính va chạm mềm",
     "question": "Một người nặng 60kg đang chạy với vận tốc 4 m/s thì nhảy lên một chiếc xe goòng nặng 100kg đang chạy cùng chiều với vận tốc 2 m/s. Vận tốc của cả người và xe ngay sau đó là:",
     "choices": ["2,75 m/s", "3 m/s", "2 m/s", "3,5 m/s"],
     "answer": 0, "explanation": "Động lượng ban đầu: $p = m_1 v_1 + m_2 v_2 = 60 \\cdot 4 + 100 \\cdot 2 = 240 + 200 = 440\\text{ kg.m/s}$. Vận tốc sau $V = p / (m_1+m_2) = 440 / 160 = 2,75\\text{ m/s}."},

    # Nhóm 19, 20: Công suất và Máy cơ đơn giản
    {"id": "mc-c3-073", "chapter": "c3", "lesson": "b29", "level": "nb", "dang": "Định luật về công",
     "question": "Định luật về công đối với các máy cơ đơn giản (ròng rọc, đòn bẩy, mặt phẳng nghiêng...) phát biểu rằng:",
     "choices": ["Không một máy cơ đơn giản nào cho ta lợi về công. Được lợi bao nhiêu lần về lực thì thiệt bấy nhiêu lần về đường đi và ngược lại", "Máy cơ đơn giản luôn giúp ta giảm bớt công sức bỏ ra", "Mặt phẳng nghiêng càng dài thì công càng nhỏ", "Đòn bẩy có lợi về cả lực lẫn công"],
     "answer": 0, "explanation": "Công = Lực x Quãng đường. Nếu giảm được lực kéo (lợi về lực) thì quãng đường kéo phải tăng lên (thiệt về đường đi), sao cho Công (phần hữu ích) không đổi."},
    {"id": "mc-c3-074", "chapter": "c3", "lesson": "b29", "level": "th", "dang": "Ròng rọc",
     "question": "Dùng một palăng gồm 1 ròng rọc cố định và 1 ròng rọc động để kéo vật nặng. Ta được lợi bao nhiêu lần về lực?",
     "choices": ["Lợi 2 lần về lực", "Lợi 4 lần về lực", "Lợi 1 lần về lực", "Không lợi về lực"],
     "answer": 0, "explanation": "Mỗi ròng rọc động giúp giảm phân nửa lực kéo (vì có 2 đoạn dây gánh trọng lượng). Ròng rọc cố định chỉ đổi hướng lực. Vậy lợi 2 lần về lực."},
    {"id": "mc-c3-075", "chapter": "c3", "lesson": "b29", "level": "vd", "dang": "Mặt phẳng nghiêng",
     "question": "Để đưa vật nặng 1000 N lên cao 1 m bằng mặt phẳng nghiêng dài 4 m, lực kéo (song song mặt nghiêng, bỏ qua ma sát) là:",
     "choices": ["250 N", "1000 N", "4000 N", "500 N"],
     "answer": 0, "explanation": "Công đưa vật lên cao $A = P \\cdot h = 1000 \\cdot 1 = 1000\\text{ J}$. Bỏ qua ma sát, $A = F \\cdot s \Rightarrow F \\cdot 4 = 1000 \Rightarrow F = 250\\text{ N}."},
    {"id": "mc-c3-076", "chapter": "c3", "lesson": "b29", "level": "vd", "dang": "Tính hiệu suất máy cơ",
     "question": "Với mặt phẳng nghiêng ở câu trên, nếu trong thực tế có ma sát nên lực kéo phải dùng là 300 N. Hiệu suất của mặt phẳng nghiêng này là:",
     "choices": ["83,3%", "120%", "25%", "33,3%"],
     "answer": 0, "explanation": "Công có ích $A_{ci} = 1000\\text{ J}$. Công toàn phần $A_{tp} = F \\cdot s = 300 \\cdot 4 = 1200\\text{ J}$. Hiệu suất $H = A_{ci} / A_{tp} = 1000 / 1200 = 5/6 \approx 83,3\\%$."},

    # Nhóm 21, 22: Bài toán Hỗn hợp Động lực học & Động lượng
    {"id": "mc-c3-077", "chapter": "c3", "lesson": "b30", "level": "vd", "dang": "Xung lượng tổng hợp",
     "question": "Một vật khối lượng 2kg rơi tự do từ độ cao 5m xuống đất ($g=10$). Độ biến thiên động lượng của vật từ lúc bắt đầu thả đến khi ngay trước khi chạm đất là:",
     "choices": ["20 kg.m/s", "10 kg.m/s", "50 kg.m/s", "0 kg.m/s"],
     "answer": 0, "explanation": "$v = \\sqrt{2gh} = \\sqrt{2\\cdot 10\\cdot 5} = 10\\text{ m/s}$. $\\Delta p = m\\Delta v = 2 \\cdot 10 = 20\\text{ kg.m/s}$."},
    {"id": "mc-c3-078", "chapter": "c3", "lesson": "b30", "level": "vd", "dang": "Phản lực va chạm",
     "question": "Một hòn bi 100g rơi từ độ cao h xuống sàn và bật nảy lên đến đúng độ cao h. Thời gian va chạm với sàn là 0.1s. Biết động lượng trước khi chạm sàn là 0.5 kg.m/s hướng xuống. Lực trung bình sàn tác dụng lên hòn bi là:",
     "choices": ["11 N (hướng lên)", "10 N (hướng lên)", "1 N (hướng lên)", "5 N (hướng lên)"],
     "answer": 0, "explanation": "Động lượng ban đầu $p_1 = 0.5$ (xuống). Sau va chạm $p_2 = -0.5$ (lên). $\\Delta p = -0.5 - 0.5 = -1\\text{ kg.m/s}$. Lực tác dụng $\\vec{F} = \\Delta \\vec{p} / \\Delta t$. F tổng hợp (Sàn đẩy - Trọng lực P) = $-1 / 0.1 = -10\\text{ N}$ (hướng lên). Sàn đẩy $N - P = 10 \Rightarrow N = 10 + 0.1\\cdot 10 = 11\\text{ N}$. (Bẫy lực trung bình: F tổng = 10N, nhưng phản lực sàn = 11N)."},
    {"id": "mc-c3-079", "chapter": "c3", "lesson": "b30", "level": "vd", "dang": "Chuyển động bằng phản lực (Cơ năng)",
     "question": "Một tên lửa khối lượng tổng cộng M (đang đứng yên ở không gian ngoài Trái Đất) phụt ra tức thời khối lượng khí m với vận tốc v ra phía sau. Phần vỏ còn lại có khối lượng (M-m). Động năng phần vỏ còn lại là bao nhiêu?",
     "choices": ["$W_d = \\frac{m^2 v^2}{2(M-m)}$", "$W_d = \\frac{1}{2}(M-m)v^2$", "$W_d = \\frac{1}{2}mv^2$", "$W_d = 0$"],
     "answer": 0, "explanation": "Bảo toàn động lượng: $0 = m(-v) + (M-m)V \Rightarrow V = \\frac{mv}{M-m}$. Động năng $W_d = 0.5 (M-m) V^2 = 0.5 (M-m) \\left(\\frac{mv}{M-m}\\right)^2 = \\frac{m^2 v^2}{2(M-m)}$."},
    {"id": "mc-c3-080", "chapter": "c3", "lesson": "b30", "level": "vd", "dang": "Con lắc đạn đạo",
     "question": "Con lắc thử đạn: Bắn viên đạn khối lượng m vận tốc v vào một bao cát khối lượng M đang treo bằng dây nhẹ, đạn cắm vào bao cát. Sau đó hệ đạn+bao văng lên đến độ cao tối đa h. Biểu thức vận tốc v là:",
     "choices": ["$v = \\frac{M+m}{m} \\sqrt{2gh}$", "$v = \\sqrt{2gh}$", "$v = \\frac{m}{M+m} \\sqrt{2gh}$", "$v = \\frac{M}{m} \\sqrt{2gh}$"],
     "answer": 0, "explanation": "Giai đoạn 1 (va chạm mềm bảo toàn động lượng): $mv = (M+m)V \Rightarrow V = \\frac{m}{M+m}v$. Giai đoạn 2 (Bảo toàn cơ năng lên cao h): $0.5(M+m)V^2 = (M+m)gh \Rightarrow V = \\sqrt{2gh}$. Từ đó suy ra $v = \\frac{M+m}{m}\\sqrt{2gh}$."},

    # Nhóm 23, 24: Va chạm 2 chiều (Mở rộng)
    {"id": "mc-c3-081", "chapter": "c3", "lesson": "b31", "level": "th", "dang": "Động lượng 2 chiều",
     "question": "Hai vật có động lượng $p_1 = 3\\text{ kg.m/s}$ hướng sang Đông và $p_2 = 4\\text{ kg.m/s}$ hướng sang Bắc. Động lượng tổng cộng của hệ có độ lớn là:",
     "choices": ["5 kg.m/s", "7 kg.m/s", "1 kg.m/s", "25 kg.m/s"],
     "answer": 0, "explanation": "Hai vectơ vuông góc nhau. $p = \\sqrt{p_1^2 + p_2^2} = \\sqrt{3^2 + 4^2} = 5\\text{ kg.m/s}$."},
    {"id": "mc-c3-082", "chapter": "c3", "lesson": "b31", "level": "vd", "dang": "Va chạm 2 chiều",
     "question": "Viên đạn khối lượng m nổ thành 2 mảnh bằng nhau. Mảnh 1 bay theo phương ngang với vận tốc v, mảnh 2 bay theo phương thẳng đứng với vận tốc v. Trước khi nổ, viên đạn đang bay theo hướng nào?",
     "choices": ["Hướng xiên góc 45 độ so với phương ngang", "Hướng ngang", "Hướng thẳng đứng", "Đứng yên"],
     "answer": 0, "explanation": "Động lượng tổng của 2 mảnh là $\\vec{p} = \\vec{p}_1 + \\vec{p}_2$. Vì $p_1 = (m/2)v$ (ngang) và $p_2 = (m/2)v$ (đứng) bằng nhau về độ lớn và vuông góc, tổng của chúng là đường chéo hình vuông, tạo góc 45 độ. Viên đạn ban đầu phải có cùng động lượng này."},
    {"id": "mc-c3-083", "chapter": "c3", "lesson": "b31", "level": "vd", "dang": "Va chạm 2 chiều (Bi-a)",
     "question": "Trong trò chơi Bi-a, viên bi chủ đập vào viên bi mục tiêu đang đứng yên (va chạm đàn hồi không xuyên tâm). Giả sử hai bi cùng khối lượng. Góc hợp bởi hai quỹ đạo của hai bi sau va chạm là:",
     "choices": ["90 độ", "45 độ", "180 độ", "60 độ"],
     "answer": 0, "explanation": "Đặc tính toán học của va chạm đàn hồi không xuyên tâm của 2 vật cùng khối lượng (1 vật đứng yên ban đầu) là sau va chạm hai vật bay theo 2 phương vuông góc nhau ($90^\\circ$)."},
    {"id": "mc-c3-084", "chapter": "c3", "lesson": "b31", "level": "th", "dang": "Năng lượng hệ",
     "question": "Có 2 viên bi lăn trên mặt phẳng ngang không ma sát. Viên 1 động lượng 3 kg.m/s, viên 2 động lượng 4 kg.m/s vuông góc nhau. Tổng ĐỘNG NĂNG của hệ bằng:",
     "choices": ["Bằng tổng động năng của 2 viên bi cộng lại", "Bằng động năng tương ứng với động lượng 5 kg.m/s", "Bằng 0", "Không tính được"],
     "answer": 0, "explanation": "Động năng là đại lượng VÔ HƯỚNG. Tổng động năng của hệ bằng tổng đại số các động năng $W_d = W_{d1} + W_{d2}$, không tuân theo quy tắc cộng vectơ như động lượng."},

    # Nhóm 25, 26, 27: Năng lượng thực tiễn (Năng lượng tái tạo, Công suất động cơ)
    {"id": "mc-c3-085", "chapter": "c3", "lesson": "b32", "level": "nb", "dang": "Năng lượng tái tạo",
     "question": "Nguồn năng lượng nào sau đây KHÔNG phải là năng lượng tái tạo?",
     "choices": ["Nhiên liệu hóa thạch (than đá, dầu mỏ)", "Năng lượng Mặt Trời", "Năng lượng gió", "Năng lượng sinh khối"],
     "answer": 0, "explanation": "Nhiên liệu hóa thạch được hình thành qua hàng triệu năm và có hạn, không thể tái tạo trong thời gian ngắn."},
    {"id": "mc-c3-086", "chapter": "c3", "lesson": "b32", "level": "nb", "dang": "Chuyển hóa năng lượng",
     "question": "Trong nhà máy thủy điện, sự chuyển hóa năng lượng chủ yếu diễn ra theo trình tự nào?",
     "choices": ["Thế năng của nước $\\rightarrow$ Động năng của dòng nước $\\rightarrow$ Cơ năng của tuabin $\\rightarrow$ Điện năng", "Thế năng $\\rightarrow$ Nhiệt năng $\\rightarrow$ Điện năng", "Động năng $\\rightarrow$ Hóa năng $\\rightarrow$ Điện năng", "Quang năng $\\rightarrow$ Điện năng"],
     "answer": 0, "explanation": "Nước ở trên cao (Thế năng) chảy xuống thành dòng chảy (Động năng) làm quay tuabin (Cơ năng) kéo máy phát điện sinh ra Điện năng."},
    {"id": "mc-c3-087", "chapter": "c3", "lesson": "b32", "level": "th", "dang": "Công suất gió",
     "question": "Công suất của một tua bin gió tỉ lệ thuận với lập phương vận tốc gió ($v^3$). Nếu vận tốc gió tăng gấp đôi, công suất điện tạo ra sẽ:",
     "choices": ["Tăng gấp 8 lần", "Tăng gấp 4 lần", "Tăng gấp đôi", "Tăng gấp 6 lần"],
     "answer": 0, "explanation": "Vì $P \\sim v^3$, khi $v' = 2v$ thì $(2v)^3 = 8v^3$. Nên công suất tăng 8 lần."},
    {"id": "mc-c3-088", "chapter": "c3", "lesson": "b32", "level": "vd", "dang": "Hiệu suất hệ thống",
     "question": "Một hệ thống gồm động cơ kéo một máy phát điện. Hiệu suất của động cơ là 80%, hiệu suất của máy phát điện là 90%. Hiệu suất tổng cộng của cả hệ thống là:",
     "choices": ["72%", "85%", "170%", "89%"],
     "answer": 0, "explanation": "Hiệu suất của hệ ghép nối tiếp bằng tích các hiệu suất thành phần: $H = 0.8 \\times 0.9 = 0.72 = 72\\%$."},

    {"id": "mc-c3-089", "chapter": "c3", "lesson": "b32", "level": "th", "dang": "Định luật bảo toàn năng lượng",
     "question": "Phát biểu chung nhất của định luật bảo toàn và chuyển hóa năng lượng là:",
     "choices": ["Năng lượng không tự nhiên sinh ra, cũng không tự mất đi, nó chỉ chuyển từ dạng này sang dạng khác, hoặc truyền từ vật này sang vật khác", "Cơ năng luôn không đổi", "Tổng động năng và động lượng luôn không đổi", "Năng lượng vũ trụ đang tăng dần"],
     "answer": 0, "explanation": "Đây là phát biểu cốt lõi của định luật bảo toàn năng lượng trong tự nhiên."},
    {"id": "mc-c3-090", "chapter": "c3", "lesson": "b32", "level": "vd", "dang": "Tiêu hao năng lượng",
     "question": "Một quả bóng cao su rơi từ độ cao 2m xuống đất cứng rồi nảy lên. Biết sau mỗi lần chạm đất, bóng mất 20% cơ năng. Độ cao bóng nảy lên được sau lần chạm đất thứ NHẤT là:",
     "choices": ["1,6 m", "0,4 m", "1,8 m", "2,0 m"],
     "answer": 0, "explanation": "Mất 20% tức là còn lại 80%. Cơ năng sau nảy $W' = 0.8 W$. Mà $W = mgh \Rightarrow mgh' = 0.8 mgh \Rightarrow h' = 0.8 \\times 2 = 1,6\\text{ m}."},
    {"id": "mc-c3-091", "chapter": "c3", "lesson": "b32", "level": "vd", "dang": "Tiêu hao năng lượng (lần 2)",
     "question": "Cũng quả bóng ở câu trên (mất 20% cơ năng mỗi lần nảy). Độ cao bóng đạt được sau lần chạm đất thứ HAI là:",
     "choices": ["1,28 m", "1,2 m", "1,4 m", "1,6 m"],
     "answer": 0, "explanation": "Cơ năng tiếp tục giảm còn 80% của lần nảy trước. $h'' = 0.8 \\times h' = 0.8 \\times 1,6 = 1,28\\text{ m}."},
    {"id": "mc-c3-092", "chapter": "c3", "lesson": "b32", "level": "vd", "dang": "Công suất ôtô",
     "question": "Một xe ô tô cần duy trì công suất 20 kW để chạy đều với tốc độ 72 km/h (20 m/s) trên đường phẳng. Nếu lực cản của không khí tỉ lệ thuận với bình phương tốc độ ($F_c = k v^2$), công suất cần thiết để chạy 144 km/h (40 m/s) là bao nhiêu?",
     "choices": ["160 kW", "80 kW", "40 kW", "320 kW"],
     "answer": 0, "explanation": "Tốc độ $v$ tăng 2 lần. Lực cản $F_c = kv^2$ sẽ tăng $2^2 = 4$ lần. Công suất $\\mathcal{P} = F \\cdot v = F_c \\cdot v$. Vận tốc tăng 2, Lực tăng 4 $\\Rightarrow$ Công suất tăng $4 \\times 2 = 8$ lần. $20 \\times 8 = 160\\text{ kW}."},

    # Nhóm 28, 29, 30: Đồ thị và Bài toán suy luận Cơ năng
    {"id": "mc-c3-093", "chapter": "c3", "lesson": "b33", "level": "vd", "dang": "Đồ thị Cơ năng",
     "question": "Một con lắc lò xo nằm ngang dao động điều hòa (bỏ qua ma sát). Đồ thị của Động năng và Thế năng theo thời gian t là những đường cong có dạng hình gì?",
     "choices": ["Đường hình sin (hoặc cosin) với chu kì bằng một nửa chu kì của vận tốc", "Đường thẳng", "Đường parabol", "Đường tròn"],
     "answer": 0, "explanation": "Vì li độ $x = A\\cos(\\omega t)$, $W_t = 0.5 k x^2 = 0.5 k A^2 \\cos^2(\\omega t) = 0.25 k A^2 (1 + \\cos(2\\omega t))$. Hàm $cos$ bậc 2 chuyển thành bậc 1 thì tần số tăng gấp đôi, chu kì giảm một nửa so với dao động."},
    {"id": "mc-c3-094", "chapter": "c3", "lesson": "b33", "level": "th", "dang": "Tổng động và thế",
     "question": "Trong dao động điều hòa của con lắc lò xo không ma sát, khi Động năng đạt giá trị cực đại thì:",
     "choices": ["Thế năng bằng 0, vật đang qua Vị trí cân bằng", "Thế năng cực đại, vật ở biên", "Gia tốc của vật cực đại", "Cơ năng bằng 0"],
     "answer": 0, "explanation": "Tại VTCB ($x=0$), lò xo không biến dạng $\\Rightarrow$ $W_t = 0$. Vì $W = W_d + W_t$ không đổi nên $W_d$ đạt max tại đây."},
    {"id": "mc-c3-095", "chapter": "c3", "lesson": "b33", "level": "vd", "dang": "Bài toán va chạm - lò xo",
     "question": "Một viên đạn 10g bay ngang với tốc độ 100m/s xuyên vào một khối gỗ 990g đang nằm yên treo ở đầu một lò xo nằm ngang (k = 100 N/m). Va chạm là mềm (đạn nằm trong gỗ). Độ nén cực đại của lò xo sau va chạm là:",
     "choices": ["10 cm", "31,6 cm", "1 cm", "1 m"],
     "answer": 0, "explanation": "Bảo toàn động lượng (va chạm mềm): $0.01 \\times 100 = (0.01 + 0.99) \\times V \Rightarrow 1 = 1 \\times V \Rightarrow V = 1\\text{ m/s}$. Bảo toàn cơ năng cho hệ lò xo sau va chạm: $0.5 M V^2 = 0.5 k (\\Delta x)^2 \Rightarrow 1 \\cdot 1^2 = 100 (\\Delta x)^2 \Rightarrow (\\Delta x)^2 = 0.01 \Rightarrow \\Delta x = 0.1\\text{ m} = 10\\text{ cm}."},
    {"id": "mc-c3-096", "chapter": "c3", "lesson": "b33", "level": "vd", "dang": "Bài toán va chạm - lò xo (Phân tích tổn hao)",
     "question": "Cũng bài toán trên, Động năng của viên đạn TRƯỚC va chạm và Động năng của hệ (gỗ+đạn) NGAY SAU va chạm lần lượt là bao nhiêu?",
     "choices": ["50 J và 0,5 J", "50 J và 50 J", "100 J và 1 J", "1 J và 0,5 J"],
     "answer": 0, "explanation": "Động năng đạn: $0.5 \\cdot 0.01 \\cdot 100^2 = 50\\text{ J}$. Động năng hệ sau va chạm: $0.5 \\cdot (1) \\cdot 1^2 = 0.5\\text{ J}$. Có đến 49,5J biến thành nhiệt (đạn cắm vào gỗ)."},

    {"id": "mc-c3-097", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Công của lực kéo biến thiên",
     "question": "Để kéo một lò xo (k=100N/m) giãn thêm 5cm từ trạng thái ĐANG BỊ GIÃN 5cm. Công của lực kéo phải thực hiện là bao nhiêu?",
     "choices": ["0,375 J", "0,125 J", "0,25 J", "0,5 J"],
     "answer": 0, "explanation": "Thế năng lúc đầu $\\Delta l_1 = 0.05 \Rightarrow W_{t1} = 0.5\\cdot 100 \\cdot (0.05)^2 = 0.125\\text{ J}$. Thế năng lúc sau $\\Delta l_2 = 0.1 \Rightarrow W_{t2} = 0.5\\cdot 100 \\cdot (0.1)^2 = 0.5\\text{ J}$. Công phải thực hiện $A = W_{t2} - W_{t1} = 0.5 - 0.125 = 0.375\\text{ J}."},
    {"id": "mc-c3-098", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Đồ thị lực đàn hồi",
     "question": "Trong đồ thị biểu diễn lực đàn hồi của lò xo theo độ biến dạng, đường biểu diễn là một đường thẳng đi qua gốc tọa độ. Phần diện tích dưới đường thẳng này có ý nghĩa gì?",
     "choices": ["Công của lực đàn hồi (thế năng đàn hồi)", "Độ cứng k của lò xo", "Lực kéo cực đại", "Xung lượng của lực"],
     "answer": 0, "explanation": "Diện tích dưới đồ thị $F(x) = kx$ là diện tích tam giác $= 0.5 \\cdot x \\cdot (kx) = 0.5 k x^2$, chính là Thế năng đàn hồi (công của ngoại lực để kéo ra)."},
    {"id": "mc-c3-099", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Va chạm không trực diện",
     "question": "Hai hòn bi khối lượng bằng nhau va chạm đàn hồi không xuyên tâm. Bi 1 ban đầu chuyển động với $v_0 = 10\\text{ m/s}$, bi 2 đứng yên. Sau va chạm, bi 1 văng ra hợp với hướng cũ một góc 30 độ. Vận tốc bi 2 sau va chạm là: (Lấy $\\sin 30 = 0.5$)",
     "choices": ["5 m/s", "8,66 m/s", "10 m/s", "7,07 m/s"],
     "answer": 0, "explanation": "Va chạm đàn hồi 2 vật cùng khối lượng (1 vật đứng yên): Góc hợp bởi 2 hướng văng là $90^\\circ$. Do bi 1 văng góc $30^\\circ \Rightarrow$ bi 2 văng góc $60^\\circ$ (so với hướng $v_0$). Theo bảo toàn động lượng vẽ tam giác vuông: $v_2 = v_0 \\sin 30^\\circ = 10 \\times 0.5 = 5\\text{ m/s}$."},
    {"id": "mc-c3-100", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Vận tốc vũ trụ",
     "question": "Để đưa một vật từ mặt đất thoát hoàn toàn khỏi lực hấp dẫn của Trái Đất (bay vào không gian vô tận không trở lại), ta phải truyền cho nó vận tốc tối thiểu (Vận tốc vũ trụ cấp II) là bao nhiêu? Biết nó được tính từ nguyên lí bảo toàn cơ năng (Động năng ban đầu = Độ tăng thế năng cực đại).",
     "choices": ["Khoảng 11,2 km/s", "Khoảng 7,9 km/s", "Khoảng 300000 km/s", "Khoảng 340 m/s"],
     "answer": 0, "explanation": "Vận tốc thoát (cấp 2) $v_2 = \\sqrt{2GM/R} \\approx 11,2\\text{ km/s}$. Vận tốc cấp 1 (bay quanh Trái Đất) $\\approx 7,9\\text{ km/s}$."},
    
    # 20 câu bù cho đủ 120 (các ứng dụng mở rộng và kiểm tra tư duy tổng hợp cơ học)
    {"id": "mc-c3-101", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Tư duy năng lượng",
     "question": "Một người chạy bộ khối lượng 60 kg và một ô tô khối lượng 1200 kg. Vận tốc của người là 6 m/s, vận tốc của ô tô là 1,5 m/s. So sánh động năng của người và ô tô?",
     "choices": ["Động năng của người bằng 0,8 lần động năng của ô tô", "Động năng của người lớn hơn ô tô", "Động năng của người nhỏ hơn rất nhiều", "Bằng nhau"],
     "answer": 0, "explanation": "$W_{d,\\text{người}} = 0.5 \\times 60 \\times 6^2 = 30 \\times 36 = 1080\\text{ J}$. $W_{d,\\text{xe}} = 0.5 \\times 1200 \\times (1.5)^2 = 600 \\times 2.25 = 1350\\text{ J}$. Tỉ số $1080/1350 = 0.8$."},
    {"id": "mc-c3-102", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Cơ năng hỗn hợp",
     "question": "Ném một viên đá 200g thẳng đứng lên cao. Lúc ở vị trí cách mặt đất 3m, nó có vận tốc 4m/s. Chọn mốc thế năng mặt đất ($g=10$). Cơ năng của viên đá là:",
     "choices": ["7,6 J", "6 J", "1,6 J", "12 J"],
     "answer": 0, "explanation": "$W_t = mgh = 0.2 \\times 10 \\times 3 = 6\\text{ J}$. $W_d = 0.5 mv^2 = 0.5 \\times 0.2 \\times 16 = 1.6\\text{ J}$. $W = 6 + 1.6 = 7.6\\text{ J}$."},
    {"id": "mc-c3-103", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Độ cao cực đại",
     "question": "Với viên đá ở câu trên ($W = 7,6\\text{ J}, m = 0,2\\text{kg}$), nó sẽ đạt được độ cao cực đại so với mặt đất là bao nhiêu? (Bỏ qua lực cản)",
     "choices": ["3,8 m", "4,0 m", "5,2 m", "3,0 m"],
     "answer": 0, "explanation": "Tại độ cao cực đại $W = W_t = mgh_{\\max} = 7.6 \Rightarrow 0.2 \\times 10 \\times h_{\\max} = 7.6 \Rightarrow 2 h_{\\max} = 7.6 \Rightarrow h_{\\max} = 3.8\\text{ m}."},
    {"id": "mc-c3-104", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Lực cản trung bình",
     "question": "Thả vật 1kg từ độ cao 5m xuống đất ($g=10$). Khi chạm đất vận tốc chỉ đạt 9 m/s. Lực cản trung bình của không khí trong quá trình rơi là:",
     "choices": ["1,9 N", "9,5 N", "10 N", "0,5 N"],
     "answer": 0, "explanation": "Cơ năng đầu $W_1 = 1\\cdot 10\\cdot 5 = 50\\text{ J}$. Cơ năng cuối $W_2 = 0.5\\cdot 1\\cdot 9^2 = 40.5\\text{ J}$. Biến thiên cơ năng $\\Delta W = -9.5\\text{ J}$. Công cản $A_c = -F_c \\cdot h = -5 F_c = -9.5 \Rightarrow F_c = 1.9\\text{ N}."},
    {"id": "mc-c3-105", "chapter": "c3", "lesson": "b25", "level": "vd", "dang": "Định lí động năng",
     "question": "Xe ô tô 1000kg đang đi với 10m/s thì đạp ga tăng tốc lên 20m/s trên quãng đường 50m. Tổng hợp lực (lực kéo trừ lực cản) tác dụng lên xe có độ lớn trung bình là:",
     "choices": ["3000 N", "2000 N", "4000 N", "1000 N"],
     "answer": 0, "explanation": "$\\Delta W_d = 0.5\\cdot 1000\\cdot(20^2 - 10^2) = 500 \\times 300 = 150000\\text{ J}$. Công $A = F \\cdot s \Rightarrow F \\cdot 50 = 150000 \Rightarrow F = 3000\\text{ N}."},
    
    {"id": "mc-c3-106", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Công kéo góc",
     "question": "Trẻ em kéo một chiếc xe trượt tuyết trên mặt đất phẳng. Dây kéo nghiêng góc $45^\\circ$ so với mặt ngang, lực kéo là 100N. Quãng đường đi 20m. Công lực kéo là:",
     "choices": ["$1000\\sqrt{2}\\text{ J}$", "2000 J", "1000 J", "$2000\\sqrt{2}\\text{ J}$"],
     "answer": 0, "explanation": "$A = F s \\cos(45^\\circ) = 100 \\times 20 \\times \\frac{\\sqrt{2}}{2} = 1000\\sqrt{2}\\text{ J}."},
    {"id": "mc-c3-107", "chapter": "c3", "lesson": "b24", "level": "vd", "dang": "Công suất bơm nước",
     "question": "Một dòng thác cao 20m, mỗi giây có $5\\text{ m}^3$ nước đổ xuống. Lấy $\\rho=1000\\text{ kg/m}^3, g=10$. Công suất lớn nhất (nếu biến 100% cơ năng thành điện năng) mà máy phát điện đặt dưới thác có thể tạo ra là:",
     "choices": ["1 MW", "2 MW", "5 MW", "10 MW"],
     "answer": 0, "explanation": "Khối lượng nước rơi mỗi giây: $m = 5000\\text{ kg/s}$. Thế năng mất đi mỗi giây (chính là công suất): $P = mgh / t = 5000 \\times 10 \\times 20 = 1,000,000\\text{ W} = 1\\text{ MW}."},
    {"id": "mc-c3-108", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Xung lực vòi rồng",
     "question": "Một vòi nước cứu hỏa phun ngang với tốc độ 20m/s, lưu lượng 10 kg nước mỗi giây. Khi nước đâm vào tường thẳng đứng rồi chảy rủ xuống (vận tốc dội lại = 0), lực do nước tác dụng lên tường là:",
     "choices": ["200 N", "100 N", "400 N", "0 N"],
     "answer": 0, "explanation": "Trong 1 giây, $m=10\\text{kg}$ nước dừng lại. $\\Delta p = m(v_2 - v_1) = 10(0 - 20) = -200\\text{ kg.m/s}$. Lực tường đẩy nước $F = \\Delta p / \\Delta t = -200 / 1 = -200\\text{ N}$. Theo ĐL 3 Newton, nước đẩy tường 200N."},
    
    {"id": "mc-c3-109", "chapter": "c3", "lesson": "b29", "level": "th", "dang": "Hiệu suất đòn bẩy",
     "question": "Dùng một đòn bẩy để nâng vật nặng. Khi đầu tay đòn bị ép xuống 1 đoạn 0,5m thì vật nặng được nâng lên 0,1m. Hiệu suất của đòn bẩy là 80%. Lực bẩy (tay người) cần dùng để nâng vật nặng 200N là:",
     "choices": ["50 N", "40 N", "80 N", "100 N"],
     "answer": 0, "explanation": "Công có ích $A_{ci} = P \\cdot h = 200 \\times 0,1 = 20\\text{ J}$. Công toàn phần phải cung cấp $A_{tp} = A_{ci} / H = 20 / 0.8 = 25\\text{ J}$. Lực ấn tay $F = A_{tp} / s = 25 / 0,5 = 50\\text{ N}."},
    {"id": "mc-c3-110", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Bài toán dây treo vướng đinh",
     "question": "Con lắc đơn l = 1m. Kéo dây nằm ngang rồi thả không vận tốc đầu. Khi qua vị trí thấp nhất, dây vướng vào một cái đinh đóng cách điểm treo 0,5m ngay trên đường thẳng đứng. Độ cao lớn nhất (so với điểm thấp nhất) mà vật lên được sau đó là:",
     "choices": ["1m", "0,5m", "1,5m", "0m"],
     "answer": 0, "explanation": "Do không ma sát, cơ năng bảo toàn. Độ cao cực đại phải bằng đúng độ cao lúc thả (so với điểm thấp nhất). Vì thả từ vị trí nằm ngang (cao bằng chiều dài dây 1m), nó sẽ cố vươn lên độ cao 1m (mặc dù bán kính quay bây giờ chỉ còn 0,5m, nó sẽ quấn quanh đinh)."},
    
    {"id": "mc-c3-111", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Cơ năng búa máy",
     "question": "Búa máy 100kg rơi từ độ cao 2m đập vào đầu một cọc. Lực cản trung bình của đất là 20000N. Bỏ qua cản không khí. Số mét cọc lún sâu vào đất sau MỖI NHÁT búa (giả sử va chạm mềm búa dính cọc, cọc rất nhẹ) là:",
     "choices": ["10 cm", "5 cm", "20 cm", "1 cm"],
     "answer": 0, "explanation": "Động năng búa khi chạm cọc = $mgh = 100 \\cdot 10 \\cdot 2 = 2000\\text{ J}$. Công của lực cản đất (hút hết động năng và công trọng lực búa trong đoạn lún s): $(F_c - P) \\cdot s = W_d \Rightarrow (20000 - 1000)s = 2000 \Rightarrow 19000s = 2000 \Rightarrow s \approx 0.1\\text{m} = 10\\text{cm}$. (Thường cho làm tròn $F_c \\cdot s = W_d \Rightarrow s = 2000/20000 = 0.1\\text{m}$)."},
    {"id": "mc-c3-112", "chapter": "c3", "lesson": "b27", "level": "vd", "dang": "Vòng xiếc",
     "question": "Một vật trượt từ đỉnh dốc không ma sát nối liền với một vòng xiếc tròn bán kính R. Để vật không rơi khi đến điểm cao nhất của vòng xiếc, độ cao tối thiểu của dốc so với điểm thấp nhất của vòng xiếc phải là:",
     "choices": ["$2,5R$", "$2R$", "$3R$", "$1,5R$"],
     "answer": 0, "explanation": "Tại đỉnh vòng xiếc (cao 2R), lực hướng tâm tối thiểu $mg = mv^2/R \Rightarrow v^2 = gR$. Bảo toàn cơ năng: $mgh = mg(2R) + 0.5mv^2 = 2mgR + 0.5mgR = 2.5mgR \Rightarrow h = 2,5R$."},
    
    {"id": "mc-c3-113", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Va chạm 1D",
     "question": "Xe A (200kg) chạy 5m/s đụng đuôi xe B (800kg) chạy cùng chiều 2m/s. Va chạm là hoàn toàn mềm. Vận tốc hai xe sau va chạm là:",
     "choices": ["2,6 m/s", "3,5 m/s", "4 m/s", "2,0 m/s"],
     "answer": 0, "explanation": "Động lượng hệ $p = 200 \\times 5 + 800 \\times 2 = 1000 + 1600 = 2600$. Vận tốc chung $V = p / (200+800) = 2600 / 1000 = 2,6\\text{ m/s}."},
    {"id": "mc-c3-114", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Tổn hao va chạm mềm",
     "question": "Từ câu trên, phần động năng đã chuyển hóa thành nhiệt trong va chạm là:",
     "choices": ["720 J", "1000 J", "0 J", "4100 J"],
     "answer": 0, "explanation": "ĐN ban đầu $W_1 = 0.5(200)(25) + 0.5(800)(4) = 2500 + 1600 = 4100\\text{ J}$. ĐN lúc sau $W_2 = 0.5(1000)(2.6)^2 = 500 \\times 6.76 = 3380\\text{ J}$. Nhiệt $= 4100 - 3380 = 720\\text{ J}."},
    {"id": "mc-c3-115", "chapter": "c3", "lesson": "b24", "level": "th", "dang": "Hiệu suất ấm điện",
     "question": "Một ấm điện ghi 1000W - 220V. Để đun sôi nước cần cung cấp nhiệt lượng 300,000 J. Biết hiệu suất ấm là 80%. Thời gian đun sôi nước là:",
     "choices": ["375 s", "300 s", "240 s", "500 s"],
     "answer": 0, "explanation": "Công có ích $A_{ci} = 300000\\text{ J}$. Công tiêu thụ (toàn phần) $A = 300000 / 0.8 = 375000\\text{ J}$. Thời gian $t = A / \mathcal{P} = 375000 / 1000 = 375\\text{ s}."},
    {"id": "mc-c3-116", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Công chống trọng lực & ma sát",
     "question": "Người ta kéo đều khối đá 50kg lên dốc nghiêng 30 độ dài 10m ($g=10, \mu=0,1, \sqrt{3} \approx 1,73$). Tổng công kéo đã thực hiện là khoảng:",
     "choices": ["2932 J", "2500 J", "432 J", "3366 J"],
     "answer": 0, "explanation": "Kéo đều $\\Rightarrow$ Lực kéo $F_k = P_t + F_{ms} = mg\\sin 30^\\circ + \\mu mg\\cos 30^\\circ$. $F_k = 500 \\times 0.5 + 0.1 \\times 500 \\times 0.866 = 250 + 43.3 = 293.3\\text{ N}$. Công $A = F_k \cdot s = 293.3 \\times 10 = 2933\\text{ J}$ (Gần đáp án A)."},
    
    {"id": "mc-c3-117", "chapter": "c3", "lesson": "b27", "level": "th", "dang": "Cơ năng lò xo thẳng đứng",
     "question": "Treo vật vào lò xo thẳng đứng. Chọn mốc thế năng trọng trường tại vị trí cân bằng, mốc thế năng đàn hồi khi lò xo không biến dạng. Biểu thức cơ năng tổng cộng của hệ là:",
     "choices": ["$W = W_d + W_t (trọng trường) + W_t (đàn hồi)$", "Chỉ gồm động năng", "Chỉ gồm thế năng đàn hồi", "Chỉ gồm 2 loại thế năng"],
     "answer": 0, "explanation": "Hệ lò xo treo thẳng đứng chịu tác dụng của 2 lực thế (trọng lực và lực đàn hồi). Nên cơ năng = Động năng + Thế năng trọng trường + Thế năng đàn hồi."},
    {"id": "mc-c3-118", "chapter": "c3", "lesson": "b23", "level": "vd", "dang": "Bài toán dây dãn",
     "question": "Một sợi dây đàn hồi (co dãn như lò xo) có k = 200 N/m. Kéo một đầu dây từ từ bằng lực F từ 0 đến 20 N. Công mà lực F đã thực hiện là:",
     "choices": ["1 J", "20 J", "0,1 J", "2 J"],
     "answer": 0, "explanation": "Độ giãn cuối cùng $x = F / k = 20 / 200 = 0,1\\text{m}$. Vì kéo từ từ, F biến thiên tuyến tính từ 0 đến 20N, công $A = 0.5 F x = 0.5 \\times 20 \\times 0.1 = 1\\text{ J}$ (chính là thế năng tích lũy)."},
    {"id": "mc-c3-119", "chapter": "c3", "lesson": "b25", "level": "th", "dang": "Suy luận động lượng",
     "question": "Vật A có động năng bằng một nửa vật B, nhưng khối lượng của A gấp đôi B. So sánh động lượng của A và B?",
     "choices": ["$p_A = p_B$", "$p_A = 2 p_B$", "$p_A = 0,5 p_B$", "$p_A = 4 p_B$"],
     "answer": 0, "explanation": "Ta có $p^2 = 2m W_d$. $p_A^2 = 2 m_A W_{dA} = 2 (2 m_B) (0.5 W_{dB}) = 2 m_B W_{dB} = p_B^2$. Suy ra $p_A = p_B$."},
    {"id": "mc-c3-120", "chapter": "c3", "lesson": "b28", "level": "vd", "dang": "Súng cối",
     "question": "Súng cối 100kg đặt trên sàn phẳng nằm ngang (không ma sát). Nòng súng nghiêng góc 60 độ. Bắn đạn 5kg với vận tốc nòng 100 m/s. Vận tốc giật lùi của súng trên sàn ngang là:",
     "choices": ["2,5 m/s", "5 m/s", "4,3 m/s", "10 m/s"],
     "answer": 0, "explanation": "Chỉ có thành phần động lượng nằm ngang được bảo toàn vì súng bị sàn đỡ thẳng đứng. Ban đầu ngang bằng 0. $0 = -M V + m(v\\cos 60^\\circ) \Rightarrow 100V = 5 \\times (100 \\times 0.5) = 250 \Rightarrow V = 2,5\\text{ m/s}."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C3 Part 2 written successfully.")
