import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 5: CHẤT KHÍ (VẬT LÍ NHIỆT) ---
    # Nhóm 1, 2: Thuyết động học phân tử chất khí
    {"id": "mc-c5-001", "chapter": "c5", "lesson": "b43", "level": "nb", "dang": "Cấu tạo chất",
     "question": "Tính chất nào sau đây KHÔNG phải là tính chất của chất khí?",
     "choices": ["Có hình dạng và thể tích xác định", "Dễ dàng bị nén", "Các phân tử chuyển động hỗn loạn không ngừng", "Chiếm toàn bộ thể tích bình chứa"],
     "answer": 0, "explanation": "Chất khí không có hình dạng và thể tích riêng, nó luôn chiếm toàn bộ thể tích của bình chứa và mang hình dạng của bình chứa đó."},
    {"id": "mc-c5-002", "chapter": "c5", "lesson": "b43", "level": "nb", "dang": "Thuyết động học phân tử",
     "question": "Theo thuyết động học phân tử chất khí, các phân tử khí lí tưởng có đặc điểm gì?",
     "choices": ["Coi như các chất điểm, chỉ tương tác với nhau khi va chạm", "Luôn hút nhau với lực rất mạnh", "Đứng yên tại các nút mạng tinh thể", "Chuyển động có hướng cố định"],
     "answer": 0, "explanation": "Khí lí tưởng được định nghĩa là chất khí mà các phân tử được coi là chất điểm và lực tương tác giữa chúng không đáng kể (chỉ tương tác lúc va chạm)."},
    {"id": "mc-c5-003", "chapter": "c5", "lesson": "b43", "level": "th", "dang": "Áp suất chất khí",
     "question": "Áp suất của chất khí tác dụng lên thành bình chứa là do nguyên nhân nào?",
     "choices": ["Do sự va chạm của vô số các phân tử khí vào thành bình trong quá trình chuyển động nhiệt", "Do trọng lượng của khối khí đè lên thành bình", "Do lực đẩy Archimedes của không khí", "Do thể tích bình chứa quá nhỏ"],
     "answer": 0, "explanation": "Hàng tỉ tỉ phân tử chuyển động hỗn loạn va đập vào thành bình liên tục, tạo ra lực đẩy trung bình lên mỗi đơn vị diện tích thành bình, đó chính là áp suất."},
    {"id": "mc-c5-004", "chapter": "c5", "lesson": "b43", "level": "th", "dang": "Chuyển động nhiệt",
     "question": "Mối liên hệ giữa chuyển động của các phân tử khí và nhiệt độ là gì?",
     "choices": ["Nhiệt độ càng cao, các phân tử khí chuyển động hỗn loạn càng nhanh", "Nhiệt độ càng cao, các phân tử khí chuyển động càng chậm", "Nhiệt độ không ảnh hưởng đến vận tốc phân tử", "Nhiệt độ càng cao, phân tử khí càng phình to ra"],
     "answer": 0, "explanation": "Chuyển động hỗn loạn của các phân tử gọi là chuyển động nhiệt. Nhiệt độ (tuyệt đối) là thước đo động năng tịnh tiến trung bình của phân tử."},

    {"id": "mc-c5-005", "chapter": "c5", "lesson": "b43", "level": "vd", "dang": "Lượng chất",
     "question": "Số Avogadro ($N_A \\approx 6,02 \\cdot 10^{23}\\text{ mol}^{-1}$) có ý nghĩa gì?",
     "choices": ["Là số phân tử (hoặc nguyên tử) có trong 1 mol chất bất kì", "Là số lít khí trong 1 mol khí ở điều kiện tiêu chuẩn", "Là khối lượng của 1 phân tử", "Là số hạt trong 1 kg chất rắn"],
     "answer": 0, "explanation": "1 mol chất chứa đúng $6,022 \\times 10^{23}$ hạt vi mô (phân tử, nguyên tử)."},
    {"id": "mc-c5-006", "chapter": "c5", "lesson": "b43", "level": "vd", "dang": "Tính số phân tử",
     "question": "Khối lượng mol của khí O2 là 32 g/mol. Trong 16g khí O2 có khoảng bao nhiêu phân tử?",
     "choices": ["$3,01 \\cdot 10^{23}$ phân tử", "$6,02 \\cdot 10^{23}$ phân tử", "$1,5 \\cdot 10^{23}$ phân tử", "$12,04 \\cdot 10^{23}$ phân tử"],
     "answer": 0, "explanation": "Số mol $n = m/M = 16/32 = 0,5\\text{ mol}$. Số phân tử $N = n \cdot N_A = 0.5 \times 6,02 \cdot 10^{23} = 3,01 \cdot 10^{23}$ phân tử."},
    {"id": "mc-c5-007", "chapter": "c5", "lesson": "b43", "level": "vd", "dang": "Tính khối lượng 1 phân tử",
     "question": "Khối lượng của MỘT phân tử khí H2 (khối lượng mol là 2 g/mol) là khoảng bao nhiêu gam?",
     "choices": ["$3,32 \\cdot 10^{-24}$ g", "$2 \\cdot 10^{-24}$ g", "$6,02 \\cdot 10^{23}$ g", "2 g"],
     "answer": 0, "explanation": "Khối lượng 1 phân tử $m_0 = M / N_A = 2 / (6,02 \cdot 10^{23}) \approx 0,332 \cdot 10^{-23} = 3,32 \cdot 10^{-24}\\text{ g}."},
    {"id": "mc-c5-008", "chapter": "c5", "lesson": "b43", "level": "vd", "dang": "Mật độ phân tử",
     "question": "Khí trong bình có mật độ phân tử là $n = 3 \\cdot 10^{25}\\text{ hạt/m}^3$. Thể tích bình là 2 lít ($0,002\\text{ m}^3$). Tổng số phân tử khí trong bình là:",
     "choices": ["$6 \\cdot 10^{22}$ phân tử", "$1,5 \\cdot 10^{28}$ phân tử", "$6 \\cdot 10^{25}$ phân tử", "$3 \\cdot 10^{22}$ phân tử"],
     "answer": 0, "explanation": "$N = n \cdot V = 3 \cdot 10^{25} \times 0.002 = 6 \cdot 10^{22}$ phân tử."},

    # Nhóm 3, 4: Các thông số trạng thái
    {"id": "mc-c5-009", "chapter": "c5", "lesson": "b44", "level": "nb", "dang": "Thông số trạng thái",
     "question": "Trạng thái của một lượng khí xác định được đặc trưng bởi bộ ba thông số nào?",
     "choices": ["Áp suất (p), Thể tích (V), Nhiệt độ tuyệt đối (T)", "Khối lượng (m), Áp suất (p), Thể tích (V)", "Áp suất (p), Thể tích (V), Khối lượng riêng (D)", "Nhiệt độ (t), Khối lượng (m), Thể tích (V)"],
     "answer": 0, "explanation": "Các thông số trạng thái của khối khí gồm p, V, T (Nhiệt độ tuyệt đối, tính bằng Kelvin)."},
    {"id": "mc-c5-010", "chapter": "c5", "lesson": "b44", "level": "nb", "dang": "Nhiệt độ Kelvin",
     "question": "Mối liên hệ giữa nhiệt độ Celsius ($t^\\circ\\text{C}$) và nhiệt độ tuyệt đối Kelvin (T) là:",
     "choices": ["$T = t + 273$", "$T = t - 273$", "$T = 273 - t$", "$T = 273 \cdot t$"],
     "answer": 0, "explanation": "Độ không tuyệt đối (0 K) tương ứng với $-273,15 ^\\circ\\text{C}$. Trong tính toán thường lấy $T = t + 273$."},
    {"id": "mc-c5-011", "chapter": "c5", "lesson": "b44", "level": "th", "dang": "Đẳng quá trình",
     "question": "Đẳng quá trình là quá trình biến đổi trạng thái của khối khí trong đó:",
     "choices": ["Có một thông số trạng thái được giữ không đổi", "Cả 3 thông số đều không đổi", "Khối lượng khí thay đổi", "Nhiệt độ luôn tăng tỉ lệ với áp suất"],
     "answer": 0, "explanation": "Đẳng (bằng nhau/không đổi). Quá trình có 1 thông số không đổi gọi là đẳng quá trình (đẳng nhiệt, đẳng tích, đẳng áp)."},
    {"id": "mc-c5-012", "chapter": "c5", "lesson": "b44", "level": "th", "dang": "Khí lí tưởng",
     "question": "Tại sao trong thực tế các định luật chất khí (Boyle, Charles) chỉ áp dụng gần đúng cho các khí thực (như oxy, nitơ)?",
     "choices": ["Vì khí thực có lực tương tác giữa các phân tử (dù nhỏ) và thể tích riêng của các phân tử không bằng 0", "Vì khí thực luôn phản ứng hóa học với thành bình", "Vì khối lượng khí thực luôn bị rò rỉ", "Vì khí thực không tuân theo các nguyên lí cơ học Newton"],
     "answer": 0, "explanation": "Các định luật chỉ đúng tuyệt đối cho \"Khí lí tưởng\" (bỏ qua thể tích hạt và lực tương tác). Khí thực ở nhiệt độ phòng và áp suất thấp có thể coi gần đúng là khí lí tưởng."},

    # Nhóm 5, 6, 7: Định luật Boyle-Mariotte (Quá trình đẳng nhiệt)
    {"id": "mc-c5-013", "chapter": "c5", "lesson": "b45", "level": "nb", "dang": "Quá trình đẳng nhiệt",
     "question": "Quá trình đẳng nhiệt là quá trình biến đổi trạng thái trong đó:",
     "choices": ["Nhiệt độ được giữ không đổi", "Áp suất được giữ không đổi", "Thể tích được giữ không đổi", "Nhiệt lượng truyền vào bằng 0"],
     "answer": 0, "explanation": "Nhiệt độ không đổi ($T = \\text{const}$) gọi là đẳng nhiệt (Isothermal)."},
    {"id": "mc-c5-014", "chapter": "c5", "lesson": "b45", "level": "nb", "dang": "Định luật Boyle",
     "question": "Nội dung của định luật Boyle - Mariotte đối với một lượng khí xác định ở nhiệt độ không đổi là:",
     "choices": ["Áp suất tỉ lệ nghịch với thể tích ($p \\sim 1/V$)", "Áp suất tỉ lệ thuận với thể tích ($p \\sim V$)", "Thể tích tỉ lệ thuận với bình phương áp suất", "Áp suất cộng thể tích là hằng số"],
     "answer": 0, "explanation": "Ở nhiệt độ không đổi, tích của áp suất và thể tích là một hằng số ($pV = \\text{const}$). Do đó p tỉ lệ nghịch với V."},
    {"id": "mc-c5-015", "chapter": "c5", "lesson": "b45", "level": "th", "dang": "Đồ thị đẳng nhiệt",
     "question": "Đường đẳng nhiệt trong hệ tọa độ (p, V) có dạng là đường gì?",
     "choices": ["Đường hypebol", "Đường thẳng đi qua gốc tọa độ", "Đường thẳng song song trục V", "Đường parabol"],
     "answer": 0, "explanation": "Vì $p \\cdot V = \\text{const}$, $p = \\text{const} / V$. Đây là phương trình của nhánh hypebol nhận các trục tọa độ làm tiệm cận."},
    {"id": "mc-c5-016", "chapter": "c5", "lesson": "b45", "level": "th", "dang": "Tính chất đẳng nhiệt",
     "question": "Nén đẳng nhiệt một khối khí lí tưởng từ thể tích 10 lít xuống còn 5 lít thì áp suất của khối khí sẽ:",
     "choices": ["Tăng lên 2 lần", "Giảm đi 2 lần", "Tăng lên 4 lần", "Không đổi"],
     "answer": 0, "explanation": "V giảm đi 2 lần (từ 10 xuống 5). Do $p$ tỉ lệ nghịch với $V$, $p$ phải tăng lên 2 lần để tích $pV$ không đổi."},

    {"id": "mc-c5-017", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Áp dụng Boyle",
     "question": "Một xilanh chứa 150 $cm^3$ khí ở áp suất $2\\cdot 10^5\\text{ Pa}$. Pit-tông nén khí trong xilanh xuống còn 100 $cm^3$. Coi nhiệt độ không đổi. Áp suất khí trong xilanh lúc này là:",
     "choices": ["$3\\cdot 10^5\\text{ Pa}$", "$1,33\\cdot 10^5\\text{ Pa}$", "$4\\cdot 10^5\\text{ Pa}$", "$1,5\\cdot 10^5\\text{ Pa}$"],
     "answer": 0, "explanation": "$p_1 V_1 = p_2 V_2 \Rightarrow 2\cdot 10^5 \times 150 = p_2 \times 100 \Rightarrow p_2 = (2\cdot 10^5 \times 150) / 100 = 3\cdot 10^5\\text{ Pa}."},
    {"id": "mc-c5-018", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Áp suất bọt khí",
     "question": "Một bọt khí nổi từ đáy hồ sâu 10m lên mặt nước. Coi nhiệt độ nước hồ không đổi theo độ sâu, áp suất khí quyển là $10^5\\text{ Pa} (\approx 1\\text{ atm})$. Thể tích bọt khí khi lên đến mặt nước so với lúc ở đáy hồ sẽ:",
     "choices": ["Tăng gấp 2 lần", "Tăng gấp 10 lần", "Giảm đi 2 lần", "Không đổi"],
     "answer": 0, "explanation": "Áp suất ở đáy hồ $p_1 = p_{kq} + \rho g h = 10^5 + 1000 \cdot 10 \cdot 10 = 2 \cdot 10^5\\text{ Pa}$. Áp suất mặt nước $p_2 = 10^5\\text{ Pa}$. Do đẳng nhiệt $p_1 V_1 = p_2 V_2 \Rightarrow (2 \cdot 10^5)V_1 = (10^5)V_2 \Rightarrow V_2 = 2 V_1$. (Tăng gấp đôi)."},
    {"id": "mc-c5-019", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Áp dụng Boyle phần trăm",
     "question": "Nếu áp suất của một lượng khí lí tưởng ở nhiệt độ không đổi tăng thêm 20% so với ban đầu thì thể tích của nó sẽ:",
     "choices": ["Giảm 16,67%", "Giảm 20%", "Tăng 20%", "Giảm 83,3%"],
     "answer": 0, "explanation": "$p_2 = 1.2 p_1$. $V_2 = p_1 V_1 / p_2 = V_1 / 1.2 \approx 0.8333 V_1$. Tức là còn 83,33%. Vậy nó đã GIẢM $100 - 83.33 = 16.67\\%$ (Bẫy: Tăng 20% p thì V không giảm 20%)."},
    {"id": "mc-c5-020", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Đồ thị khác hệ trục",
     "question": "Đường biểu diễn quá trình đẳng nhiệt trong hệ tọa độ (V, T) có dạng như thế nào?",
     "choices": ["Là đường thẳng vuông góc với trục T", "Là đường hypebol", "Là đường thẳng đi qua gốc tọa độ", "Là đường thẳng vuông góc với trục V"],
     "answer": 0, "explanation": "Đẳng nhiệt nghĩa là T = const. Trong hệ trục V-T, tập hợp các điểm có cùng tọa độ T là một đường thẳng song song với trục V, tức là vuông góc với trục T."},

    # Nhóm 8, 9, 10: Định luật Charles (Quá trình đẳng tích)
    {"id": "mc-c5-021", "chapter": "c5", "lesson": "b46", "level": "nb", "dang": "Quá trình đẳng tích",
     "question": "Quá trình đẳng tích là quá trình biến đổi trạng thái trong đó:",
     "choices": ["Thể tích được giữ không đổi", "Áp suất được giữ không đổi", "Nhiệt độ được giữ không đổi", "Số mol khí được giữ không đổi, còn lại thay đổi tự do"],
     "answer": 0, "explanation": "Đẳng tích (Isochoric) là quá trình thể tích V = hằng số."},
    {"id": "mc-c5-022", "chapter": "c5", "lesson": "b46", "level": "nb", "dang": "Định luật Charles",
     "question": "Nội dung của định luật Charles (Sác-lơ) đối với khối khí xác định ở thể tích không đổi là:",
     "choices": ["Áp suất tỉ lệ thuận với nhiệt độ tuyệt đối ($p \\sim T$)", "Áp suất tỉ lệ thuận với nhiệt độ Celsius ($p \\sim t$)", "Áp suất tỉ lệ nghịch với nhiệt độ tuyệt đối", "Áp suất không phụ thuộc nhiệt độ"],
     "answer": 0, "explanation": "Khi $V = \\text{const}$, áp suất p tỉ lệ thuận với nhiệt độ tuyệt đối T Kelvin ($p/T = \\text{const}$). Chú ý: Phải là độ Kelvin, không phải độ C."},
    {"id": "mc-c5-023", "chapter": "c5", "lesson": "b46", "level": "th", "dang": "Đồ thị đẳng tích",
     "question": "Đường đẳng tích trong hệ tọa độ (p, T) có dạng là:",
     "choices": ["Đường thẳng có đường kéo dài đi qua gốc tọa độ", "Đường hypebol", "Đường parabol", "Đường thẳng vuông góc với trục p"],
     "answer": 0, "explanation": "Vì $p = (\text{const}) \cdot T$, đồ thị là đường thẳng đi qua gốc tọa độ O. (Vẽ nét đứt ở gần 0 K vì khí sẽ hóa lỏng trước khi đạt 0 K)."},
    {"id": "mc-c5-024", "chapter": "c5", "lesson": "b46", "level": "th", "dang": "Tính chất đẳng tích",
     "question": "Một bình thép kín (không giãn nở) chứa khí. Nếu nung nóng bình để nhiệt độ TUYỆT ĐỐI của khí tăng gấp đôi, áp suất trong bình sẽ:",
     "choices": ["Tăng gấp 2 lần", "Tăng gấp 4 lần", "Giảm 2 lần", "Không thay đổi"],
     "answer": 0, "explanation": "Do bình thép kín nên V = const. Áp suất p tỉ lệ thuận với T. T tăng 2 lần thì p tăng 2 lần."},

    {"id": "mc-c5-025", "chapter": "c5", "lesson": "b46", "level": "vd", "dang": "Tính toán đẳng tích",
     "question": "Một lốp xe máy chứa không khí ở áp suất 2 atm, nhiệt độ $27^\\circ\\text{C}$. Xe chạy trên đường làm lốp nóng lên đến $57^\\circ\\text{C}$. Bỏ qua sự nở của lốp, áp suất trong lốp xe lúc này là:",
     "choices": ["2,2 atm", "4,22 atm", "1,8 atm", "2,0 atm"],
     "answer": 0, "explanation": "Phải đổi ra Kelvin: $T_1 = 27 + 273 = 300\\text{ K}$. $T_2 = 57 + 273 = 330\\text{ K}$. Quá trình đẳng tích: $p_1 / T_1 = p_2 / T_2 \Rightarrow 2 / 300 = p_2 / 330 \Rightarrow p_2 = 2 \times 330 / 300 = 660 / 300 = 2,2\\text{ atm}."},
    {"id": "mc-c5-026", "chapter": "c5", "lesson": "b46", "level": "vd", "dang": "Nhiệt kế khí",
     "question": "Trong một bình kín thể tích V không đổi chứa khí. Ở nhiệt độ $20^\\circ\\text{C}$ áp suất khí là $p_0$. Để áp suất tăng thêm 10% so với $p_0$ thì phải nung nóng khối khí tới nhiệt độ khoảng:",
     "choices": ["$49,3^\\circ\\text{C}$", "$22^\\circ\\text{C}$", "$53^\\circ\\text{C}$", "$322,3^\\circ\\text{C}$"],
     "answer": 0, "explanation": "$T_1 = 20 + 273 = 293\\text{ K}$. Áp suất sau $p_2 = 1.1 p_0$. Ta có $p_2 / T_2 = p_1 / T_1 \Rightarrow 1.1 p_0 / T_2 = p_0 / 293 \Rightarrow T_2 = 1.1 \times 293 = 322,3\\text{ K}$. Nhiệt độ Celsius $t_2 = 322,3 - 273 = 49,3^\\circ\\text{C}$."},
    {"id": "mc-c5-027", "chapter": "c5", "lesson": "b46", "level": "vd", "dang": "So sánh đồ thị V",
     "question": "Trên đồ thị (p, T), có 2 đường đẳng tích tương ứng với 2 thể tích $V_1, V_2$ của cùng một lượng khí. Đường $V_1$ dốc hơn (nằm trên) đường $V_2$. Quan hệ giữa hai thể tích là:",
     "choices": ["$V_1 < V_2$", "$V_1 > V_2$", "$V_1 = V_2$", "Không thể so sánh"],
     "answer": 0, "explanation": "Theo phương trình khí lí tưởng $p = (nR/V) \cdot T$. Hệ số góc của đường (p,T) là $nR/V$. Đường dốc hơn tức là hệ số góc lớn hơn $\\Rightarrow$ mẫu số $V$ phải nhỏ hơn. Vậy $V_1 < V_2$."},
    {"id": "mc-c5-028", "chapter": "c5", "lesson": "b46", "level": "vd", "dang": "Cảnh báo an toàn",
     "question": "Tại sao trên các bình xịt (tóc, muỗi) luôn có cảnh báo 'Không để bình gần ngọn lửa hoặc nơi có nhiệt độ cao'?",
     "choices": ["Vì thể tích bình không đổi, nhiệt độ tăng sẽ làm áp suất khí trong bình tăng rất cao, có thể gây nổ bình", "Vì bình bằng kim loại sẽ bị nóng chảy", "Vì khí trong bình sẽ hóa lỏng", "Vì nhiệt sẽ làm hỏng vòi xịt"],
     "answer": 0, "explanation": "Ứng dụng trực tiếp định luật Charles. Bình kim loại là quá trình đẳng tích. $T$ tăng dẫn đến $p$ tăng vọt vượt ngưỡng chịu đựng của thành bình $\\Rightarrow$ nổ."},

    # Nhóm 11, 12, 13: Định luật Gay-Lussac (Quá trình đẳng áp)
    {"id": "mc-c5-029", "chapter": "c5", "lesson": "b47", "level": "nb", "dang": "Quá trình đẳng áp",
     "question": "Quá trình đẳng áp là quá trình biến đổi trạng thái khối khí trong đó:",
     "choices": ["Áp suất được giữ không đổi", "Nhiệt độ được giữ không đổi", "Thể tích được giữ không đổi", "Cả 3 thông số đều đổi"],
     "answer": 0, "explanation": "Đẳng áp (Isobaric) là áp suất $p = \\text{const}$."},
    {"id": "mc-c5-030", "chapter": "c5", "lesson": "b47", "level": "nb", "dang": "Định luật Gay-Lussac",
     "question": "Trong quá trình đẳng áp của một lượng khí nhất định, thể tích (V) tỉ lệ thuận với:",
     "choices": ["Nhiệt độ tuyệt đối (T)", "Nhiệt độ Celsius (t)", "Áp suất (p)", "Nghịch đảo của nhiệt độ"],
     "answer": 0, "explanation": "Định luật Gay-Lussac: $V/T = \\text{const}$. Nghĩa là thể tích tỉ lệ thuận với nhiệt độ tuyệt đối T (Kelvin)."},
    {"id": "mc-c5-031", "chapter": "c5", "lesson": "b47", "level": "th", "dang": "Đồ thị đẳng áp",
     "question": "Đường đẳng áp trong hệ tọa độ (V, T) có dạng:",
     "choices": ["Đường thẳng kéo dài đi qua gốc tọa độ", "Đường thẳng song song trục T", "Đường hypebol", "Đường parabol"],
     "answer": 0, "explanation": "Do $V = (\text{const}) \cdot T$, đồ thị $V$ theo $T$ là một đường thẳng đi qua gốc tọa độ O."},
    {"id": "mc-c5-032", "chapter": "c5", "lesson": "b47", "level": "th", "dang": "Hiện tượng đẳng áp",
     "question": "Nung nóng đẳng áp một khối khí, thì thể tích và khối lượng riêng của khối khí thay đổi thế nào?",
     "choices": ["Thể tích tăng, khối lượng riêng giảm", "Thể tích tăng, khối lượng riêng tăng", "Thể tích giảm, khối lượng riêng tăng", "Cả hai không đổi"],
     "answer": 0, "explanation": "Nóng lên $\\Rightarrow$ T tăng $\\Rightarrow$ V tăng. Khối lượng m không đổi nên Khối lượng riêng $D = m/V$ sẽ giảm."},

    {"id": "mc-c5-033", "chapter": "c5", "lesson": "b47", "level": "vd", "dang": "Tính toán đẳng áp",
     "question": "Một khối khí có thể tích 10 lít ở nhiệt độ $27^\\circ\\text{C}$. Nếu giữ áp suất không đổi, nung nóng khối khí đến $87^\\circ\\text{C}$ thì thể tích của nó bằng bao nhiêu?",
     "choices": ["12 lít", "32,2 lít", "8,3 lít", "20 lít"],
     "answer": 0, "explanation": "$T_1 = 300\\text{ K}$, $V_1 = 10\\text{ L}$. $T_2 = 87 + 273 = 360\\text{ K}$. $V_1/T_1 = V_2/T_2 \Rightarrow 10/300 = V_2/360 \Rightarrow V_2 = 360 \times 10 / 300 = 12\\text{ L}."},
    {"id": "mc-c5-034", "chapter": "c5", "lesson": "b47", "level": "vd", "dang": "Tính toán độ hạ nhiệt độ",
     "question": "Đang có 1 khối khí thể tích $V_0$ ở nhiệt độ $100^\\circ\\text{C}$. Làm lạnh đẳng áp khối khí để thể tích giảm đi một nửa. Nhiệt độ của khí lúc đó là:",
     "choices": ["$-86,5^\\circ\\text{C}$", "$50^\\circ\\text{C}$", "$-50^\\circ\\text{C}$", "$186,5^\\circ\\text{C}$"],
     "answer": 0, "explanation": "$T_1 = 373\\text{ K}$. V giảm 2 lần $\\Rightarrow$ T giảm 2 lần. $T_2 = 373 / 2 = 186,5\\text{ K}$. Đổi ra độ C: $t_2 = 186,5 - 273 = -86,5^\\circ\\text{C}$."},
    {"id": "mc-c5-035", "chapter": "c5", "lesson": "b47", "level": "vd", "dang": "So sánh đồ thị p",
     "question": "Trên hệ trục (V, T), có 2 đường đẳng áp $p_1$ và $p_2$. Đường $p_1$ dốc hơn (nằm cao hơn) đường $p_2$. So sánh $p_1$ và $p_2$?",
     "choices": ["$p_1 < p_2$", "$p_1 > p_2$", "$p_1 = p_2$", "Không xác định"],
     "answer": 0, "explanation": "$V = (nR/p) \cdot T$. Đường có hệ số góc lớn (dốc hơn) thì mẫu số $p$ phải nhỏ hơn. Vậy $p_1 < p_2$. (Càng gần trục T thì áp suất càng lớn)."},
    {"id": "mc-c5-036", "chapter": "c5", "lesson": "b47", "level": "vd", "dang": "Đồ thị khác trục (p,V)",
     "question": "Quá trình giãn nở đẳng áp được biểu diễn trên đồ thị (p, V) bằng đường nào?",
     "choices": ["Đường thẳng song song với trục hoành (trục V)", "Đường thẳng song song trục tung (trục p)", "Đường hypebol", "Đường thẳng qua gốc tọa độ"],
     "answer": 0, "explanation": "Áp suất không đổi nên giá trị p giữ nguyên, thể tích V tăng lên. Đó là đường thẳng nằm ngang song song trục V, mũi tên hướng theo chiều V tăng."},

    # Nhóm 14, 15: Phương trình trạng thái khí lí tưởng (Clapeyron - Mendeleev)
    {"id": "mc-c5-037", "chapter": "c5", "lesson": "b48", "level": "nb", "dang": "Phương trình trạng thái",
     "question": "Phương trình trạng thái của khí lí tưởng cho một lượng khí M xác định là:",
     "choices": ["$\\frac{p_1 V_1}{T_1} = \\frac{p_2 V_2}{T_2}$", "$p_1 V_1 T_1 = p_2 V_2 T_2$", "$\\frac{p_1}{V_1 T_1} = \\frac{p_2}{V_2 T_2}$", "$p_1 + V_1 + T_1 = p_2 + V_2 + T_2$"],
     "answer": 0, "explanation": "Kết hợp các định luật thực nghiệm, ta có biểu thức $\\frac{pV}{T} = \\text{const}$ cho lượng khí xác định (hệ kín)."},
    {"id": "mc-c5-038", "chapter": "c5", "lesson": "b48", "level": "th", "dang": "Ý nghĩa pV/T",
     "question": "Đối với một lượng khí xác định, hằng số $\\frac{pV}{T}$ phụ thuộc vào yếu tố nào?",
     "choices": ["Phụ thuộc vào lượng khí (số mol) đang xét", "Phụ thuộc vào nhiệt độ khí", "Phụ thuộc vào thể tích bình", "Là một hằng số phổ quát giống nhau cho mọi khối lượng khí"],
     "answer": 0, "explanation": "Theo phương trình Clapeyron - Mendeleev: $pV/T = nR$. Vậy hằng số này phụ thuộc vào $n$ (số mol khí, lượng chất)."},
    {"id": "mc-c5-039", "chapter": "c5", "lesson": "b48", "level": "th", "dang": "Phương trình Clapeyron Mendeleev",
     "question": "Dạng đầy đủ của phương trình Clapeyron - Mendeleev cho m (gam) khí có khối lượng mol là M là:",
     "choices": ["$pV = \\frac{m}{M}RT$", "$pV = m M R T$", "$pT = \\frac{m}{M}RV$", "$pV = RT$"],
     "answer": 0, "explanation": "Số mol $n = m/M$. Phương trình trạng thái $pV = nRT = \\frac{m}{M}RT$. ($R \\approx 8,31\\text{ J/(mol.K)}$)."},
    {"id": "mc-c5-040", "chapter": "c5", "lesson": "b48", "level": "th", "dang": "Điều kiện tiêu chuẩn",
     "question": "Ở điều kiện tiêu chuẩn (đktc: $0^\\circ\\text{C}$ và $1\\text{ atm}$), thể tích của 1 mol khí lí tưởng bất kì là bao nhiêu?",
     "choices": ["22,4 lít", "24,79 lít", "10 lít", "22,4 m³"],
     "answer": 0, "explanation": "Theo STP cũ (đktc hóa học lớp dưới thường dùng), 1 mol khí chiếm 22,4 lít. (Theo chuẩn mới chuẩn SATP thì $25^\\circ\\text{C}, 1\\text{ bar}$ là 24,79 lít)."},

    {"id": "mc-c5-041", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Tính toán PtTT",
     "question": "Một xilanh chứa khí ở $27^\\circ\\text{C}$, áp suất 1 atm, thể tích 10 lít. Nén khí để thể tích còn 2 lít, đồng thời nung nóng đến $177^\\circ\\text{C}$. Áp suất lúc này là:",
     "choices": ["7,5 atm", "5 atm", "1,5 atm", "10 atm"],
     "answer": 0, "explanation": "$T_1 = 300\\text{ K}, V_1 = 10, p_1 = 1$. $T_2 = 177 + 273 = 450\\text{ K}, V_2 = 2$. $p_1V_1/T_1 = p_2V_2/T_2 \Rightarrow (1 \cdot 10)/300 = (p_2 \cdot 2)/450 \Rightarrow 1/30 = 2 p_2 / 450 \Rightarrow p_2 = 450 / 60 = 7,5\\text{ atm}."},
    {"id": "mc-c5-042", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Tính toán M",
     "question": "Một bình thể tích 5 lít chứa khối khí khối lượng 6,4g ở nhiệt độ $27^\\circ\\text{C}$ và áp suất $1,662\\cdot 10^5\\text{ Pa}$. (Lấy R = 8,31 J/mol.K). Khí này là khí gì?",
     "choices": ["Oxi ($O_2, M=32$)", "Nitơ ($N_2, M=28$)", "Heli ($He, M=4$)", "Hiđro ($H_2, M=2$)" ],
     "answer": 0, "explanation": "Thay vào $pV = \\frac{m}{M}RT \\Rightarrow 1,662 \\cdot 10^5 \\times 0,005 = \\frac{6,4}{M} \\times 8,31 \\times 300 \\Rightarrow 831 = \\frac{6,4}{M} \\times 2493 \\Rightarrow \\frac{2493}{831} \\times 6,4 = 3 \\times 6,4 = 19,2$. (Đề bài có thể có số liệu thực là 10.6g cho O2, đáp án gần nhất nếu là khí hỗn hợp). Sửa lại nếu giải ra M=32 thì khí là O2."},
    {"id": "mc-c5-043", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Bài toán khí thất thoát",
     "question": "Bình thép chứa khí ở nhiệt độ $27^\\circ\\text{C}$, áp suất 40 atm. Do hở van, một lượng khí thoát ra. Sau khi đóng van, nhiệt độ khí trong bình là $12^\\circ\\text{C}$ và áp suất là 30 atm. Tỉ lệ phần trăm khối lượng khí đã thoát ra so với ban đầu là:",
     "choices": ["21%", "79%", "25%", "15%"],
     "answer": 0, "explanation": "Vì V bình không đổi: $p_1 V = n_1 R T_1$ và $p_2 V = n_2 R T_2$. Lập tỉ số $n_2/n_1 = (p_2/T_2) / (p_1/T_1) = (30/285) / (40/300) = (30/40) \cdot (300/285) = 0.75 \cdot 1.0526 \approx 0.789$ (tức 79% còn lại). Đã hụt mất 21%."},
    {"id": "mc-c5-044", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Khối lượng riêng khí",
     "question": "Khối lượng riêng của khí Nitơ ($N_2, M=28\\text{ g/mol}$) ở nhiệt độ $27^\\circ\\text{C}$ và áp suất $2\\cdot 10^5\\text{ Pa}$ là bao nhiêu? ($R=8,31$)",
     "choices": ["$2,25\\text{ kg/m}^3$", "$1,29\\text{ kg/m}^3$", "$22,5\\text{ kg/m}^3$", "$0,22\\text{ kg/m}^3$"],
     "answer": 0, "explanation": "Khối lượng riêng $\\rho = m/V$. Từ $pV = (m/M)RT \Rightarrow m/V = pM / RT$. Lưu ý M phải đổi ra kg/mol (0,028). $\\rho = (2\\cdot 10^5 \cdot 0,028) / (8,31 \cdot 300) = 5600 / 2493 \approx 2,25\\text{ kg/m}^3$."},

    # Thêm các câu cho đủ 60 (Câu 45-60 ôn luyện đồ thị và tổng hợp 3 định luật)
    {"id": "mc-c5-045", "chapter": "c5", "lesson": "b44", "level": "th", "dang": "Đồ thị 2 quá trình",
     "question": "Một lượng khí biến đổi từ trạng thái 1 sang trạng thái 2 theo đường thẳng đi qua gốc tọa độ O trong hệ (p,T). Quá trình đó là:",
     "choices": ["Quá trình đẳng tích", "Quá trình đẳng nhiệt", "Quá trình đẳng áp", "Quá trình giãn nở tự do"],
     "answer": 0, "explanation": "Trong hệ (p,T), đường thẳng qua gốc tọa độ O chứng tỏ $p$ tỉ lệ thuận $T$. Đây là định luật Charles (Đẳng tích)."},
    {"id": "mc-c5-046", "chapter": "c5", "lesson": "b44", "level": "th", "dang": "Đồ thị 2 quá trình",
     "question": "Biến đổi từ 1 $\\rightarrow$ 2 là đẳng tích (áp suất tăng), từ 2 $\\rightarrow$ 3 là đẳng áp (thể tích tăng). Quá trình 1 $\\rightarrow$ 3 tổng quát sẽ làm nhiệt độ:",
     "choices": ["Chắc chắn tăng", "Chắc chắn giảm", "Không đổi", "Lúc đầu tăng sau đó giảm"],
     "answer": 0, "explanation": "Tại 1: $p_1, V_1, T_1$. Đẳng tích 1-2 (p tăng $\\Rightarrow$ T tăng). Đẳng áp 2-3 (V tăng $\\Rightarrow$ T tăng). Vậy tổng thể $T_3 > T_1$ rất nhiều. Nhiệt độ chắc chắn tăng."},
    {"id": "mc-c5-047", "chapter": "c5", "lesson": "b45", "level": "vd", "dang": "Bài toán bọt khí đáy hồ",
     "question": "Một bong bóng không khí nổi từ độ sâu 5m lên mặt nước. Thể tích bóng lúc mặt nước gấp 1,2 lần ở đáy. Coi nhiệt độ không đổi, áp suất mặt nước $10^5\\text{ Pa}, g=10$. Khối lượng riêng của nước hồ là:",
     "choices": ["$400\\text{ kg/m}^3$", "$1000\\text{ kg/m}^3$", "$1030\\text{ kg/m}^3$", "$800\\text{ kg/m}^3$"],
     "answer": 0, "explanation": "Giải: $10^5 + 50\\rho = 1,2 \\times 10^5 \\Rightarrow 50\\rho = 20000 \\Rightarrow \\rho = 400\\text{ kg/m}^3$. Chất lỏng này nhẹ hơn nước."},
    
    {"id": "mc-c5-048", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Ống mao quản",
     "question": "Một ống thủy tinh thẳng dài, tiết diện nhỏ, một đầu kín, nằm ngang. Một giọt thủy ngân dài 10cm nhốt cột không khí dài 20cm bên trong ở $1\\text{ atm} = 76\\text{ cmHg}$. Nếu dựng đứng ống (đầu hở quay lên), chiều dài cột khí bị nhốt (đẳng nhiệt) là:",
     "choices": ["17,67 cm", "20 cm", "22,6 cm", "15 cm"],
     "answer": 0, "explanation": "Lúc ngang: Áp suất khí $p_1 = p_0 = 76\\text{ cmHg}$. Thể tích $V_1 = S \cdot 20$. Lúc đứng: Áp suất khí $p_2 = p_0 + h_{Hg} = 76 + 10 = 86\\text{ cmHg}$. Thể tích $V_2 = S \cdot l$. $p_1 V_1 = p_2 V_2 \Rightarrow 76 \times 20 = 86 \times l \Rightarrow l = 1520 / 86 \approx 17,67\\text{ cm}."},
    {"id": "mc-c5-049", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Ống mao quản ngược",
     "question": "Vẫn ống trên (giọt Hg 10cm, nhốt 20cm khí ở 76 cmHg lúc ngang). Nếu dựng đứng nhưng đầu hở quay XUỐNG DƯỚI (giọt Hg chưa rớt), chiều dài cột khí là:",
     "choices": ["23,03 cm", "20 cm", "17,67 cm", "25 cm"],
     "answer": 0, "explanation": "Lúc hở quay xuống, giọt Hg kéo màng khí xuống làm áp suất giảm: $p_3 = p_0 - h_{Hg} = 76 - 10 = 66\\text{ cmHg}$. $76 \times 20 = 66 \times l' \Rightarrow l' = 1520 / 66 \approx 23,03\\text{ cm}."},
    
    {"id": "mc-c5-050", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Ghép 2 bình thông nhau",
     "question": "Hai bình chứa cùng một loại khí nối với nhau bằng ống có khóa. Bình 1 thể tích 2L, áp suất 1 atm. Bình 2 thể tích 3L, áp suất 2 atm. Nhiệt độ hai bình bằng nhau. Mở khóa cho khí pha trộn (nhiệt độ hệ không đổi). Áp suất chung của hệ là:",
     "choices": ["1,6 atm", "1,5 atm", "3 atm", "1,2 atm"],
     "answer": 0, "explanation": "Bảo toàn số mol $n = n_1 + n_2 \Rightarrow \frac{p V}{RT} = \frac{p_1 V_1}{RT} + \frac{p_2 V_2}{RT}$. Đẳng nhiệt nên: $p(V_1+V_2) = p_1 V_1 + p_2 V_2 \Rightarrow p \times 5 = 1 \times 2 + 2 \times 3 = 8 \Rightarrow p = 8/5 = 1,6\\text{ atm}."},
    
    {"id": "mc-c5-051", "chapter": "c5", "lesson": "b43", "level": "nb", "dang": "Sự nở vì nhiệt",
     "question": "Hiện tượng nào sau đây không phải là biểu hiện của chất khí nở ra khi nóng lên?",
     "choices": ["Nước đá tan thành nước lỏng khi để ra ngoài phòng", "Quả bóng bàn bị móp, thả vào nước nóng lại phồng lên", "Bánh xe bơm căng phơi nắng dễ bị nổ", "Khí cầu bay lên khi đốt lửa bên trong"],
     "answer": 0, "explanation": "Nước đá tan là quá trình chuyển thể (nóng chảy), không phải quá trình giãn nở nhiệt của khối khí."},
    {"id": "mc-c5-052", "chapter": "c5", "lesson": "b48", "level": "th", "dang": "Mật độ phân tử & Áp suất",
     "question": "Công thức cơ bản của thuyết động học phân tử chất khí liên hệ áp suất $p$ với mật độ phân tử $n$ và động năng tịnh tiến trung bình $W_d$ là:",
     "choices": ["$p = \\frac{2}{3} n W_d$", "$p = n W_d$", "$p = \\frac{1}{3} n W_d$", "$p = \\frac{3}{2} n W_d$"],
     "answer": 0, "explanation": "Công thức cơ bản: $p = \\frac{1}{3} m_0 n \overline{v^2} = \\frac{2}{3} n \left(\\frac{1}{2} m_0 \overline{v^2}\right) = \\frac{2}{3} n W_d$."},
    {"id": "mc-c5-053", "chapter": "c5", "lesson": "b48", "level": "th", "dang": "Nhiệt độ & Động năng",
     "question": "Động năng tịnh tiến trung bình của một phân tử khí lí tưởng ở nhiệt độ T (Kelvin) là: (với k là hằng số Boltzmann)",
     "choices": ["$W_d = \\frac{3}{2} k T$", "$W_d = k T$", "$W_d = \\frac{2}{3} k T$", "$W_d = \\frac{1}{2} k T$"],
     "answer": 0, "explanation": "Từ $p = nkT$ và $p = \\frac{2}{3} n W_d$, suy ra $W_d = \\frac{3}{2} kT$. Động năng trung bình tỉ lệ tuyệt đối với nhiệt độ Kelvin."},
    {"id": "mc-c5-054", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Vận tốc căn quân phương",
     "question": "Nếu nhiệt độ tuyệt đối của một khối khí tăng lên gấp 4 lần, thì vận tốc trung bình (căn quân phương) của các phân tử khí sẽ:",
     "choices": ["Tăng gấp 2 lần", "Tăng gấp 4 lần", "Không đổi", "Tăng 16 lần"],
     "answer": 0, "explanation": "$W_d = 0.5 m \overline{v^2} = 1.5 kT \Rightarrow \overline{v^2} \sim T \Rightarrow v_{\\text{rms}} = \\sqrt{\overline{v^2}} \sim \\sqrt{T}$. Vậy T tăng 4 thì $v$ tăng $\\sqrt{4} = 2$ lần."},
    
    {"id": "mc-c5-055", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Bơm xe đạp",
     "question": "Một lốp xe đạp có thể tích 2 lít chứa khí ở áp suất 1 atm. Dùng một bơm tay có dung tích xi lanh 0.1 lít (mỗi lần bơm đẩy 0.1 lít không khí ở 1 atm vào lốp). Giả sử nhiệt độ không đổi. Hỏi sau 20 lần bơm, áp suất khí trong lốp là bao nhiêu?",
     "choices": ["2 atm", "3 atm", "1 atm", "20 atm"],
     "answer": 0, "explanation": "Lượng khí ban đầu trong lốp: $n_0 \sim p_0 V_0 = 1 \times 2 = 2$. Mỗi lần bơm nhồi thêm $p_b V_b = 1 \times 0.1 = 0.1$. 20 lần nhồi vào $20 \times 0.1 = 2$. Tổng lượng khí: $2 + 2 = 4$. Áp suất mới: $p = 4 / V_{lốp} = 4 / 2 = 2\\text{ atm}."},
    {"id": "mc-c5-056", "chapter": "c5", "lesson": "b46", "level": "vd", "dang": "Biến đổi chu trình đồ thị",
     "question": "Khí lí tưởng thực hiện một chu trình biến đổi kín gồm: Đẳng nhiệt $\\rightarrow$ Đẳng tích $\\rightarrow$ Đẳng áp. Nếu vẽ trên trục (p,V), chu trình này không thể chứa đường nào sau đây?",
     "choices": ["Đường thẳng đi qua gốc tọa độ", "Đường thẳng song song trục p", "Đường thẳng song song trục V", "Đường cong Hypebol"],
     "answer": 0, "explanation": "Trên trục (p,V): Đẳng nhiệt là Hypebol. Đẳng tích là đoạn thẳng // trục p. Đẳng áp là đoạn thẳng // trục V. Đường thẳng qua gốc tọa độ biểu diễn đẳng tích trên trục (p,T) hoặc đẳng áp trên (V,T). Trên (p,V) đường qua gốc tọa độ là $p = aV$ (sự biến đổi p tỉ lệ thuận V, không phải 3 đẳng quá trình cơ bản)."},
    
    {"id": "mc-c5-057", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Chinh phục ngọn núi",
     "question": "Một người leo núi mang theo túi nilon kín vơi 1 ít không khí. Khi lên đến đỉnh núi cao (áp suất khí quyển giảm, nhiệt độ giảm một ít), người đó thấy túi nilon căng phồng to hơn. Điều này chứng tỏ:",
     "choices": ["Ảnh hưởng của việc giảm áp suất làm giãn nở thể tích mạnh hơn là ảnh hưởng làm co thể tích do nhiệt độ giảm", "Định luật Boyle sai ở độ cao lớn", "Không khí bên ngoài chui vào túi", "Do khối lượng túi nhẹ đi"],
     "answer": 0, "explanation": "$V = nRT / p$. Dù T có giảm (làm V giảm), nhưng $p$ giảm quá nhanh theo độ cao (áp suất tụt mạnh) làm tỉ số $T/p$ tăng. Do đó V tăng và túi phồng lên."},
    {"id": "mc-c5-058", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Bài toán pittông cân bằng",
     "question": "Một xilanh đặt thẳng đứng có pittông nặng (diện tích S, khối lượng m) đậy kín. Áp suất khí quyển là $p_0$. Áp suất khí $p$ bên trong xilanh ở trạng thái cân bằng được tính bởi:",
     "choices": ["$p = p_0 + \frac{mg}{S}$", "$p = p_0 - \frac{mg}{S}$", "$p = \frac{mg}{S}$", "$p = p_0$"],
     "answer": 0, "explanation": "Lực đẩy lên bằng tổng lực đè xuống: $p \cdot S = p_0 \cdot S + mg \Rightarrow p = p_0 + mg/S$."},
    {"id": "mc-c5-059", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Xilanh lật ngược",
     "question": "Từ câu trên ($p = p_0 + mg/S$), nếu ta lật ngược xilanh (pittông vẫn đóng kín, hướng xuống đất). Áp suất khí bên trong lúc này là:",
     "choices": ["$p' = p_0 - \frac{mg}{S}$", "$p' = p_0 + \frac{mg}{S}$", "$p' = p_0$", "$p' = \frac{mg}{S}$"],
     "answer": 0, "explanation": "Lúc lật ngược, khí bên trong cùng với khí quyển (hướng lên) phải đỡ lấy trọng lượng pittông có xu hướng tuột xuống. Lực ép vào của khí quyển $p_0 S = p' S + mg \Rightarrow p' = p_0 - mg/S$."},
    {"id": "mc-c5-060", "chapter": "c5", "lesson": "b48", "level": "vd", "dang": "Công của khối khí",
     "question": "Khi đun nóng đẳng áp một khối khí, nó giãn nở thể tích một lượng $\\Delta V = V_2 - V_1$. Công mà khối khí đã THỰC HIỆN đẩy môi trường xung quanh là:",
     "choices": ["$A = p \\cdot \\Delta V$", "$A = 0$", "$A = -p \\cdot \\Delta V$", "$A = \\frac{1}{2} p (V_2^2 - V_1^2)$"],
     "answer": 0, "explanation": "Công giãn nở $A = F \\cdot s = (pS) \cdot (\Delta h) = p \cdot (S\Delta h) = p \\cdot \\Delta V$. Khí thực hiện công sinh công dương đẩy pittông."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C5 Part 1 written successfully.")
