import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 5 HÓA HỌC 10: TỐC ĐỘ PHẢN ỨNG HÓA HỌC (Phần 1) ---
    # Nhóm 1, 2, 3: Khái niệm tốc độ phản ứng và Công thức Tốc độ trung bình
    {"id": "mc-c5-001", "chapter": "c5", "lesson": "b25", "level": "nb", "dang": "Khái niệm Tốc độ",
     "question": "Tốc độ phản ứng hóa học là đại lượng đặc trưng cho:",
     "choices": ["Sự thay đổi nồng độ của chất phản ứng hoặc sản phẩm trong một đơn vị thời gian", "Sự thay đổi nhiệt độ của hệ trong một đơn vị thời gian", "Lượng nhiệt tỏa ra hoặc thu vào của phản ứng", "Khối lượng chất rắn sinh ra"],
     "answer": 0, "explanation": "Định nghĩa: Tốc độ phản ứng đánh giá mức độ xảy ra nhanh hay chậm của phản ứng, đo bằng độ biến thiên nồng độ (hoặc thể tích, khối lượng) chia cho khoảng thời gian."},
    {"id": "mc-c5-002", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Đơn vị tốc độ",
     "question": "Đơn vị thường dùng nhất của tốc độ phản ứng trong dung dịch là:",
     "choices": ["mol/(L.s) (hay $M \\cdot s^{-1}$)", "mol/s", "gam/phút", "Lít/giây"],
     "answer": 0, "explanation": "Nồng độ tính bằng mol/L (M). Thời gian tính bằng giây (s). Nên đơn vị tốc độ $\\bar{v}$ là mol/(L.s) hoặc $M \\cdot s^{-1}$."},
    {"id": "mc-c5-003", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Biểu thức Tốc độ trung bình",
     "question": "Cho phản ứng tổng quát: $aA + bB \\rightarrow cC + dD$. Biểu thức tính tốc độ trung bình ($\\bar{v}$) của phản ứng theo chất tham gia A là:",
     "choices": ["$\\bar{v} = -\\frac{1}{a} \\frac{\\Delta C_A}{\\Delta t}$", "$\\bar{v} = \\frac{1}{a} \\frac{\\Delta C_A}{\\Delta t}$", "$\\bar{v} = -a \\frac{\\Delta C_A}{\\Delta t}$", "$\\bar{v} = \\frac{\\Delta C_A}{\\Delta t}$"],
     "answer": 0, "explanation": "Chất A là chất tham gia nên nồng độ giảm dần ($\\Delta C_A < 0$). Để tốc độ $\\bar{v}$ có giá trị dương, phải có dấu trừ đằng trước. Đồng thời phải chia cho hệ số tỉ lượng $a$."},
    {"id": "mc-c5-004", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Toán $\\bar{v}$ cơ bản",
     "question": "Trong phản ứng: $N_2O_4(g) \\rightarrow 2NO_2(g)$. Tại thời điểm $t_1 = 0$, nồng độ của $N_2O_4$ là $0,040 \\text{ M}$. Tại thời điểm $t_2 = 20 \\text{ s}$, nồng độ $N_2O_4$ còn lại $0,024 \\text{ M}$. Tốc độ trung bình của phản ứng trong khoảng thời gian này là:",
     "choices": ["$8,0 \\times 10^{-4} \\text{ M/s}$", "$1,6 \\times 10^{-3} \\text{ M/s}$", "$4,0 \\times 10^{-4} \\text{ M/s}$", "$1,2 \\times 10^{-3} \\text{ M/s}$"],
     "answer": 0, "explanation": "Hệ số của $N_2O_4$ là 1. $\\bar{v} = - \\frac{\\Delta C}{\\Delta t} = - \\frac{0,024 - 0,040}{20} = - \\frac{-0,016}{20} = 0,0008 = 8,0 \\times 10^{-4} \\text{ M/s}$."},
    {"id": "mc-c5-005", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Tốc độ theo SP",
     "question": "Tiếp tục câu trên, tốc độ TẠO THÀNH của khí $NO_2$ trong khoảng thời gian từ 0 đến 20s là bao nhiêu?",
     "choices": ["$1,6 \\times 10^{-3} \\text{ M/s}$", "$8,0 \\times 10^{-4} \\text{ M/s}$", "$4,0 \\times 10^{-4} \\text{ M/s}$", "Không tính được"],
     "answer": 0, "explanation": "Hệ số của $NO_2$ là 2, gấp đôi $N_2O_4$. Do đó tốc độ tạo thành $NO_2 = 2 \\times \\bar{v} = 2 \\times 8,0 \\times 10^{-4} = 1,6 \\times 10^{-3} \\text{ M/s}$."},
    
    # Nhóm 4, 5, 6: Các yếu tố ảnh hưởng - Nồng độ & Áp suất
    {"id": "mc-c5-006", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Lý thuyết ảnh hưởng Nồng độ",
     "question": "Nhìn chung, khi tăng nồng độ của các chất tham gia phản ứng (trong hệ đồng thể), tốc độ phản ứng sẽ:",
     "choices": ["Tăng lên", "Giảm đi", "Không đổi", "Tăng sau đó giảm"],
     "answer": 0, "explanation": "Tăng nồng độ chất phản ứng làm tăng mật độ các hạt (phân tử, ion). Các hạt sẽ va chạm với nhau nhiều hơn (tăng tần số va chạm hiệu quả) $\\Rightarrow$ Tốc độ phản ứng tăng."},
    {"id": "mc-c5-007", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Định luật tác dụng khối lượng",
     "question": "Cho phản ứng đơn giản: $A(g) + 2B(g) \\rightarrow C(g)$. Biểu thức tốc độ phản ứng ($v$) theo định luật tác dụng khối lượng là:",
     "choices": ["$v = k \\cdot C_A \\cdot C_B^2$", "$v = k \\cdot C_A \\cdot C_B$", "$v = k \\cdot C_C$", "$v = k \\cdot (C_A + 2C_B)$"],
     "answer": 0, "explanation": "Đối với PHẢN ỨNG ĐƠN GIẢN (xảy ra 1 bước), tốc độ phản ứng tỉ lệ thuận với tích nồng độ các chất phản ứng, với số mũ bằng hệ số tỉ lượng. $v = k \\cdot [A]^1 \\cdot [B]^2$."},
    {"id": "mc-c5-008", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán tốc độ k[A][B]",
     "question": "Cho phản ứng đơn giản $2NO + O_2 \\rightarrow 2NO_2$. Khi nồng độ của NO tăng lên 2 lần, nồng độ của $O_2$ giữ nguyên thì tốc độ phản ứng sẽ thay đổi như thế nào?",
     "choices": ["Tăng 4 lần", "Tăng 2 lần", "Tăng 8 lần", "Không đổi"],
     "answer": 0, "explanation": "$v = k[NO]^2[O_2]$. Tăng [NO] lên 2 lần $\\Rightarrow v' = k(2[NO])^2[O_2] = 4 \\cdot k[NO]^2[O_2] = 4v$. Tốc độ tăng 4 lần."},
    {"id": "mc-c5-009", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Áp suất với chất khí",
     "question": "Đối với phản ứng có chất KHÍ tham gia, việc TĂNG áp suất của hệ sẽ làm tốc độ phản ứng thay đổi thế nào?",
     "choices": ["Tăng tốc độ phản ứng", "Giảm tốc độ phản ứng", "Không ảnh hưởng", "Chỉ ảnh hưởng nếu là phản ứng tỏa nhiệt"],
     "answer": 0, "explanation": "Tăng áp suất (bằng cách nén thể tích) làm nồng độ các chất khí tăng lên (số phân tử khí trên một đơn vị thể tích tăng). Tăng nồng độ $\\Rightarrow$ tăng tần số va chạm $\\Rightarrow$ Tăng tốc độ phản ứng."},
    {"id": "mc-c5-010", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Áp suất",
     "question": "Xét phản ứng khí đơn giản: $A(g) + B(g) \\rightarrow C(g)$. Nếu tăng áp suất của hệ lên 3 lần (bằng cách nén thể tích còn 1/3) thì tốc độ phản ứng tăng lên bao nhiêu lần?",
     "choices": ["9 lần", "3 lần", "6 lần", "27 lần"],
     "answer": 0, "explanation": "Thể tích giảm 3 lần $\\Rightarrow$ Nồng độ của cả A và B đều tăng 3 lần. $v = k[A][B]$. Do đó $v' = k(3[A])(3[B]) = 9k[A][B] = 9v$."},

    # Nhóm 7, 8, 9: Các yếu tố ảnh hưởng - Diện tích bề mặt
    {"id": "mc-c5-011", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Bề mặt tiếp xúc",
     "question": "Chẻ nhỏ củi trước khi đun sẽ giúp lửa cháy to và mạnh hơn. Hiện tượng này minh họa cho yếu tố nào ảnh hưởng đến tốc độ phản ứng?",
     "choices": ["Diện tích bề mặt tiếp xúc", "Nhiệt độ", "Áp suất", "Chất xúc tác"],
     "answer": 0, "explanation": "Việc chẻ củi, đập nhỏ than, tán nhuyễn thuốc phiện... làm tăng diện tích bề mặt tiếp xúc giữa chất rắn với oxi hoặc dung dịch, qua đó làm tăng tần số va chạm và tăng tốc độ phản ứng."},
    {"id": "mc-c5-012", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Thí nghiệm bột sắt",
     "question": "Cho 2 mẫu Sắt có cùng khối lượng (1 gam): Mẫu 1 là một viên bi sắt, Mẫu 2 là bột sắt mịn. Cho cùng lúc vào 2 ống nghiệm chứa $HCl$ 1M (cùng thể tích). Ống nghiệm nào thoát khí $H_2$ nhanh hơn?",
     "choices": ["Ống 2 (bột sắt)", "Ống 1 (viên bi)", "Cả hai bằng nhau vì cùng khối lượng 1 gam", "Không ống nào phản ứng"],
     "answer": 0, "explanation": "Bột sắt mịn có diện tích bề mặt tiếp xúc lớn hơn hàng vạn lần so với một viên bi sắt có cùng khối lượng. Axit dễ dàng tấn công trên diện rộng $\\Rightarrow$ tốc độ thoát khí nhanh hơn nhiều."},
    {"id": "mc-c5-013", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Điều kiện hệ dị thể",
     "question": "Yếu tố \"diện tích bề mặt tiếp xúc\" CHỈ có ảnh hưởng đến tốc độ của các phản ứng hóa học thuộc loại hệ nào?",
     "choices": ["Hệ dị thể (có pha rắn phản ứng với lỏng/khí)", "Hệ đồng thể (pha khí với khí)", "Hệ đồng thể (pha lỏng với lỏng hòa tan)", "Phản ứng hạt nhân"],
     "answer": 0, "explanation": "Trong hệ đồng thể (VD: 2 chất khí hoặc 2 chất tan trong dung dịch), các phân tử đã được hòa lẫn hoàn toàn vào nhau ở cấp độ phân tử, không có ranh giới pha (bề mặt) nên không xét yếu tố diện tích bề mặt."},
    {"id": "mc-c5-014", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Ứng dụng trong y tế thực phẩm",
     "question": "Tại sao phải nhai kĩ thức ăn trước khi nuốt?",
     "choices": ["Để làm tăng diện tích bề mặt tiếp xúc của thức ăn với các enzyme tiêu hóa, giúp quá trình tiêu hóa (phản ứng hóa học) xảy ra nhanh hơn", "Để làm nóng thức ăn", "Để giảm nồng độ acid trong dạ dày", "Để làm thức ăn biến thành khí"],
     "answer": 0, "explanation": "Nghiền nát thức ăn chính là tăng diện tích bề mặt. Enzyme (chất xúc tác) và Acid có thể tác dụng đồng loạt, giúp phân giải nhanh và tránh đầy hơi khó tiêu."},

    # Nhóm 10, 11, 12: Các yếu tố ảnh hưởng - Nhiệt độ và Hệ số Van't Hoff
    {"id": "mc-c5-015", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Ảnh hưởng nhiệt độ",
     "question": "Khi tăng nhiệt độ của hệ phản ứng, tốc độ phản ứng thay đổi như thế nào?",
     "choices": ["Tăng lên", "Giảm xuống", "Không đổi", "Lúc đầu tăng, sau đó giảm"],
     "answer": 0, "explanation": "Tăng nhiệt độ làm động năng của các phân tử tăng $\\Rightarrow$ Chúng di chuyển nhanh hơn, va chạm nhiều hơn và quan trọng nhất là TỈ LỆ CÁC VA CHẠM CÓ HIỆU QUẢ (có năng lượng lớn hơn năng lượng hoạt hóa $E_a$) tăng vọt $\\Rightarrow$ Tốc độ phản ứng tăng mạnh."},
    {"id": "mc-c5-016", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Công thức Van't Hoff",
     "question": "Định luật Van't Hoff cho biết: Khi nhiệt độ tăng thêm $10^\\circ\\text{C}$, tốc độ phản ứng sẽ tăng lên $\\gamma$ lần. Công thức liên hệ là:",
     "choices": ["$\\frac{v_{T_2}}{v_{T_1}} = \\gamma^{\\frac{T_2 - T_1}{10}}$", "$\\frac{v_{T_2}}{v_{T_1}} = \\gamma \\times \\frac{T_2 - T_1}{10}$", "$v_{T_2} = v_{T_1} + \\gamma \\cdot 10$", "$\\frac{v_{T_2}}{v_{T_1}} = (\\gamma)^{\\frac{T_2}{T_1}}$"],
     "answer": 0, "explanation": "Tốc độ phản ứng tăng theo cấp số nhân. $v_2 / v_1 = \\gamma^{\\Delta T / 10}$. $\\gamma$ gọi là hệ số nhiệt độ (thường từ 2 đến 4)."},
    {"id": "mc-c5-017", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Vant Hoff 1",
     "question": "Một phản ứng hóa học có hệ số nhiệt độ $\\gamma = 3$. Nếu tăng nhiệt độ từ $20^\\circ\\text{C}$ lên $50^\\circ\\text{C}$ thì tốc độ phản ứng sẽ tăng lên bao nhiêu lần?",
     "choices": ["27 lần", "9 lần", "30 lần", "6 lần"],
     "answer": 0, "explanation": "$\\Delta T = 50 - 20 = 30^\\circ\\text{C}$. Tăng $30 / 10 = 3$ khoảng $10^\\circ\\text{C}$. Tốc độ tăng $\\gamma^3 = 3^3 = 27$ lần."},
    {"id": "mc-c5-018", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Thời gian",
     "question": "Ở $30^\\circ\\text{C}$, một phản ứng kết thúc sau 16 phút. Hệ số nhiệt độ $\\gamma = 2$. Hỏi nếu đun nóng hệ lên $50^\\circ\\text{C}$ thì phản ứng kết thúc sau bao lâu?",
     "choices": ["4 phút", "8 phút", "64 phút", "2 phút"],
     "answer": 0, "explanation": "$\\Delta T = 50 - 30 = 20^\\circ\\text{C} \\Rightarrow$ Tốc độ tăng $2^2 = 4$ lần. Tốc độ tăng 4 lần nghĩa là THỜI GIAN phản ứng giảm đi 4 lần. Thời gian mới $= 16 / 4 = 4$ phút."},
    {"id": "mc-c5-019", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính gamma",
     "question": "Khi tăng nhiệt độ từ $10^\\circ\\text{C}$ lên $40^\\circ\\text{C}$, tốc độ của một phản ứng tăng lên 8 lần. Hệ số nhiệt độ $\\gamma$ của phản ứng này là:",
     "choices": ["2", "3", "4", "1,5"],
     "answer": 0, "explanation": "Tốc độ tăng $v_2/v_1 = 8$. Số khoảng $\\Delta T = (40-10)/10 = 3$. Ta có $\\gamma^3 = 8 \\Rightarrow \\gamma = 2$."},
    {"id": "mc-c5-020", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Bảo quản thực phẩm",
     "question": "Tại sao thức ăn để trong tủ lạnh lại lâu bị ôi thiu hơn để bên ngoài?",
     "choices": ["Vì nhiệt độ thấp làm giảm tốc độ của các phản ứng hóa sinh (phân hủy thức ăn bởi vi khuẩn)", "Vì trong tủ lạnh không có không khí", "Vì tủ lạnh sinh ra chất chống ôi thiu", "Vì tủ lạnh nén áp suất thức ăn"],
     "answer": 0, "explanation": "Sự ôi thiu là tập hợp các phản ứng phân hủy hóa học. Hạ nhiệt độ làm các phản ứng này xảy ra chậm lại gấp hàng chục lần (theo Van't Hoff), kéo dài thời gian bảo quản."},

    # Nhóm 13, 14, 15: Các yếu tố ảnh hưởng - Chất xúc tác
    {"id": "mc-c5-021", "chapter": "c5", "lesson": "b26", "level": "nb", "dang": "Định nghĩa chất xúc tác",
     "question": "Chất xúc tác là chất:",
     "choices": ["Làm tăng tốc độ phản ứng, nhưng vẫn được bảo toàn về lượng và chất khi phản ứng kết thúc", "Cung cấp nhiệt lượng cho phản ứng xảy ra", "Làm thay đổi vị trí cân bằng hóa học", "Tiêu hao dần trong quá trình phản ứng"],
     "answer": 0, "explanation": "Định nghĩa: Chất xúc tác (Catalyst) tham gia vào cơ chế phản ứng để tạo ra một con đường mới dễ dàng hơn, sau đó tự tái tạo lại hoàn toàn. Khối lượng và tính chất hóa học của nó không đổi trước và sau phản ứng."},
    {"id": "mc-c5-022", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Cơ chế của chất xúc tác",
     "question": "Bản chất của việc chất xúc tác làm tăng tốc độ phản ứng là do nó:",
     "choices": ["Làm GIẢM năng lượng hoạt hóa ($E_a$) của phản ứng", "Làm TĂNG năng lượng hoạt hóa ($E_a$)", "Làm tăng nhiệt độ của hệ", "Làm tăng nồng độ chất tham gia"],
     "answer": 0, "explanation": "Chất xúc tác thay đổi cơ chế phản ứng, tạo ra các trạng thái chuyển tiếp mới có mức năng lượng thấp hơn $\\Rightarrow$ Rào cản năng lượng hoạt hóa $E_a$ giảm $\\Rightarrow$ Nhiều phân tử có đủ năng lượng để vượt qua hơn $\\Rightarrow$ Tốc độ tăng đột biến."},
    {"id": "mc-c5-023", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Enzyme sinh học",
     "question": "Enzyme Amylase trong nước bọt giúp chuyển hóa tinh bột thành đường ngay trong khoang miệng. Amylase đóng vai trò là:",
     "choices": ["Chất xúc tác sinh học", "Chất tham gia phản ứng", "Sản phẩm của phản ứng", "Dung môi sinh học"],
     "answer": 0, "explanation": "Enzyme là protein có vai trò xúc tác sinh học đặc hiệu, tăng tốc độ phản ứng hóa sinh."},
    {"id": "mc-c5-024", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Xúc tác và Hằng số k",
     "question": "Chất xúc tác có làm thay đổi giá trị của hằng số tốc độ phản ứng ($k$) không?",
     "choices": ["Có, chất xúc tác làm giá trị $k$ tăng lên rất nhiều", "Không, $k$ chỉ phụ thuộc vào nhiệt độ", "Chất xúc tác làm $k$ giảm đi", "Chất xúc tác không liên quan đến $k$"],
     "answer": 0, "explanation": "Theo phương trình Arrhenius $k = A \\cdot e^{-E_a / (RT)}$, khi $E_a$ giảm (nhờ chất xúc tác), hằng số $k$ sẽ tăng lên theo hàm số mũ $\\Rightarrow$ Tốc độ phản ứng $v = k[A][B]$ tăng theo."},
    {"id": "mc-c5-025", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Xúc tác âm",
     "question": "Trong thực tế, người ta còn sử dụng các \"chất ức chế\" (inhibitor) như chất bảo quản thực phẩm, chất làm chậm quá trình gỉ sét. Vai trò của chất ức chế tương tự như:",
     "choices": ["Chất xúc tác âm (Làm giảm tốc độ phản ứng)", "Chất xúc tác dương", "Chất oxi hóa", "Hệ đệm"],
     "answer": 0, "explanation": "Chất ức chế còn được gọi là xúc tác âm, nó làm tàn phá chất xúc tác có sẵn hoặc tạo rào cản làm phản ứng chậm đi, ngăn chặn sự oxi hóa/phân hủy ngoài ý muốn."},

    # Nhóm 16, 17: Tính toán chuyên sâu Tốc độ trung bình
    {"id": "mc-c5-026", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Đồ thị Nồng độ - Thời gian",
     "question": "Trên đồ thị biểu diễn sự biến thiên nồng độ chất C theo thời gian $t$ của phản ứng $A \\rightarrow C$. Độ dốc (hệ số góc) của tiếp tuyến tại một thời điểm $t_1$ biểu thị đại lượng nào?",
     "choices": ["Tốc độ tức thời của phản ứng tại thời điểm $t_1$", "Tốc độ trung bình của phản ứng", "Hằng số tốc độ k", "Năng lượng hoạt hóa"],
     "answer": 0, "explanation": "Tốc độ tức thời $v = \\frac{dC}{dt}$, chính là đạo hàm của Nồng độ theo thời gian, tương đương độ dốc của tiếp tuyến trên đồ thị $C(t)$ tại một điểm cụ thể."},
    {"id": "mc-c5-027", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "So sánh tốc độ các chất",
     "question": "Cho phản ứng tổng hợp Amoniac: $N_2(g) + 3H_2(g) \\rightarrow 2NH_3(g)$. Nếu tốc độ tiêu thụ $H_2$ đo được là $0,060 \\text{ mol/(L.s)}$, thì tốc độ tạo thành của $NH_3$ là bao nhiêu?",
     "choices": ["$0,040 \\text{ mol/(L.s)}$", "$0,060 \\text{ mol/(L.s)}$", "$0,090 \\text{ mol/(L.s)}$", "$0,020 \\text{ mol/(L.s)}$"],
     "answer": 0, "explanation": "Tốc độ pư chung $\\bar{v} = v_{H_2} / 3 = 0,060 / 3 = 0,020$. Tốc độ tạo $NH_3 = 2 \\times \\bar{v} = 0,040 \\text{ mol/L.s}$."},
    {"id": "mc-c5-028", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Toán Khối lượng hao hụt",
     "question": "Phản ứng $Zn + 2HCl \\rightarrow ZnCl_2 + H_2$. Trong 30 giây đầu tiên, khối lượng hạt Zn giảm 0,65 gam. Tốc độ trung bình của phản ứng tính theo số mol Zn là:",
     "choices": ["$3,33 \\times 10^{-4} \\text{ mol/s}$", "$0,01 \\text{ mol/s}$", "$0,02 \\text{ mol/s}$", "$6,67 \\times 10^{-4} \\text{ mol/s}$"],
     "answer": 0, "explanation": "$n_{Zn} = 0,65 / 65 = 0,01$ mol. $\\bar{v} = \\frac{\\Delta n}{\\Delta t} = \\frac{0,01}{30} \\approx 3,33 \\times 10^{-4} \\text{ mol/s}$."},
    
    # Nhóm 18, 19: Các thí nghiệm điển hình
    {"id": "mc-c5-029", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Thí nghiệm $Na_2S_2O_3$ và HCl",
     "question": "Trong thí nghiệm giữa $Na_2S_2O_3$ và $HCl$: $Na_2S_2O_3 + 2HCl \\rightarrow 2NaCl + S\\downarrow + SO_2 + H_2O$. Người ta thường đo thời gian từ lúc đổ dung dịch vào nhau cho đến khi không nhìn thấy chữ X dưới đáy cốc. Dấu hiệu này dùng để:",
     "choices": ["Xác định tốc độ phản ứng thông qua lượng kết tủa S sinh ra đủ để che khuất chữ X", "Kiểm tra xem phản ứng đã tỏa ra bao nhiêu nhiệt", "Xác định hằng số cân bằng", "Xác định khối lượng $SO_2$ thoát ra"],
     "answer": 0, "explanation": "Phản ứng sinh ra Lưu huỳnh (S) dạng huyền phù đục. Thời gian làm mờ chữ X (mức độ đục nhất định) tỉ lệ nghịch với tốc độ phản ứng. Thời gian $t$ càng ngắn $\\Rightarrow$ Tốc độ càng nhanh."},
    {"id": "mc-c5-030", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Phân tích đồ thị Thể tích khí",
     "question": "Làm thí nghiệm đun nóng $KClO_3$ sinh ra khí $O_2$. Đo thể tích $O_2$ thu được theo thời gian và vẽ đồ thị. Đường cong đồ thị sẽ có dạng:",
     "choices": ["Lúc đầu dốc đứng (tốc độ nhanh), sau đó thoải dần và nằm ngang khi phản ứng kết thúc", "Là một đường thẳng tuyến tính đi qua gốc tọa độ", "Lúc đầu thoải (chậm), sau đó dốc đứng", "Là đường nằm ngang liên tục"],
     "answer": 0, "explanation": "Ban đầu nồng độ chất phản ứng lớn nhất $\\Rightarrow$ tốc độ nhanh nhất (độ dốc cao). Khi chất phản ứng cạn dần, tốc độ chậm lại (độ dốc giảm). Khi hết chất, phản ứng dừng, thể tích khí đạt max và nằm ngang."},

    # Nhóm 20-30: Câu hỏi tổng hợp và suy luận
    {"id": "mc-c5-031", "chapter": "c5", "lesson": "b25", "level": "nb", "dang": "Xác định hằng số tốc độ",
     "question": "Hằng số tốc độ phản ứng $k$ phụ thuộc vào yếu tố nào sau đây?",
     "choices": ["Nhiệt độ và bản chất của chất phản ứng (bao gồm chất xúc tác)", "Nồng độ các chất phản ứng", "Áp suất của hệ", "Thể tích của bình chứa"],
     "answer": 0, "explanation": "Theo phương trình Arrhenius, hằng số tốc độ $k$ chỉ phụ thuộc vào nhiệt độ (T), năng lượng hoạt hóa ($E_a$ - liên quan bản chất phản ứng và xúc tác). KHÔNG phụ thuộc nồng độ."},
    {"id": "mc-c5-032", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Điều kiện va chạm hiệu quả",
     "question": "Theo thuyết va chạm, để một va chạm giữa 2 phân tử dẫn đến phản ứng hóa học (va chạm hiệu quả), cần đáp ứng 2 điều kiện nào?",
     "choices": ["Có năng lượng đủ lớn ($> E_a$) và hướng va chạm không gian phù hợp", "Có tốc độ cực cao và kích thước phân tử bằng nhau", "Phải ở nhiệt độ $> 100^\\circ\\text{C}$ và có xúc tác", "Phải là phân tử khí và có ánh sáng"],
     "answer": 0, "explanation": "Thuyết va chạm: Hạt phải va chạm với Động năng đủ lớn (thắng lực đẩy, cắt đứt liên kết cũ) VÀ phải va chạm đúng HƯỚNG không gian để tạo liên kết mới."},
    {"id": "mc-c5-033", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Bài toán Van't Hoff 2",
     "question": "Hệ số nhiệt độ của một phản ứng là $\\gamma = 2,5$. Ở $25^\\circ\\text{C}$ phản ứng có tốc độ là $v_1$. Ở $65^\\circ\\text{C}$ phản ứng có tốc độ là $v_2$. Tỉ số $v_2/v_1$ là:",
     "choices": ["39,06", "10,0", "6,25", "97,65"],
     "answer": 0, "explanation": "$\\Delta T = 65 - 25 = 40^\\circ\\text{C}$. Tỉ số $v_2/v_1 = \\gamma^{\\Delta T / 10} = 2,5^4 = 39,0625 \\approx 39,06$ lần."},
    {"id": "mc-c5-034", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Giải thích Động cơ ô tô",
     "question": "Trong xylanh động cơ đốt trong (ô tô, xe máy), hỗn hợp hơi xăng và không khí bị piston nén lại với áp suất rất cao trước khi bugi đánh lửa. Mục đích của việc nén này là:",
     "choices": ["Làm tăng nồng độ của hỗn hợp khí sinh ra áp suất lớn, giúp tốc độ phản ứng cháy xảy ra cực nhanh tạo ra sức nổ mạnh đẩy piston", "Để làm lạnh hỗn hợp khí", "Để tiết kiệm nhiên liệu", "Làm thay đổi chất xúc tác"],
     "answer": 0, "explanation": "Nén làm tăng áp suất $\\Rightarrow$ tăng nồng độ chất phản ứng $\\Rightarrow$ tốc độ phản ứng tăng mạnh, bùng cháy tức thời."},
    {"id": "mc-c5-035", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Biểu thức v = k... bậc phản ứng",
     "question": "Cho phản ứng $2NO + O_2 \\rightarrow 2NO_2$ là phản ứng đơn giản. Bậc của phản ứng (Reaction Order) tổng cộng là bao nhiêu?",
     "choices": ["Bậc 3", "Bậc 2", "Bậc 1", "Bậc 0"],
     "answer": 0, "explanation": "Với phản ứng đơn giản, biểu thức tốc độ $v = k[NO]^2[O_2]^1$. Bậc tổng hợp = tổng các số mũ = $2 + 1 = 3$. Đây là phản ứng bậc 3 (rất hiếm gặp, do xác suất 3 phân tử va chạm cùng 1 lúc là rất nhỏ)."},
    {"id": "mc-c5-036", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Thí nghiệm nhiệt độ C sủi bọt",
     "question": "Sục 1 viên thuốc sủi vitamin C vào 2 cốc nước: Cốc 1 chứa nước đá ($5^\\circ\\text{C}$), cốc 2 chứa nước nóng ($80^\\circ\\text{C}$). Hiện tượng quan sát được là:",
     "choices": ["Cốc 2 sủi bọt khí mãnh liệt và viên thuốc tan hết nhanh hơn cốc 1", "Cốc 1 sủi bọt nhanh hơn do khí ít tan ở nhiệt độ thấp", "Cả 2 cốc tan nhanh như nhau", "Cốc 2 không sủi bọt vì vitamin C bị phân hủy"],
     "answer": 0, "explanation": "Nhiệt độ cao (cốc 2) làm tăng tốc độ phản ứng giữa axit hữu cơ và $NaHCO_3$ trong viên sủi $\\Rightarrow$ Tốc độ sinh khí $CO_2$ và tan vỡ hạt nhanh hơn rất nhiều so với nước lạnh."},
    {"id": "mc-c5-037", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "So sánh 2 yếu tố đồng thời",
     "question": "Cho phản ứng phân hủy $H_2O_2$ (oxy già) sinh ra $O_2$. Hành động nào sau đây làm tốc độ thoát khí NHANH NHẤT?",
     "choices": ["Đun nóng dung dịch $H_2O_2$ đặc (nồng độ cao) và cho thêm một ít bột $MnO_2$ (chất xúc tác)", "Đun nóng dung dịch $H_2O_2$ loãng", "Để dung dịch $H_2O_2$ đặc ở nhiệt độ phòng", "Làm lạnh dung dịch $H_2O_2$ và cho thêm $MnO_2$"],
     "answer": 0, "explanation": "Hội tụ đủ các yếu tố: Tăng nồng độ, tăng nhiệt độ, có mặt chất xúc tác ($MnO_2$) $\\Rightarrow$ Tốc độ đạt max."},
    {"id": "mc-c5-038", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Hiện tượng Nổ bụi",
     "question": "Bụi than tại các mỏ than hay bụi cám tại các xưởng xay xát có thể gây ra những vụ nổ kinh hoàng nếu vô tình có tia lửa. Nguyên nhân chính do đâu?",
     "choices": ["Bụi có kích thước vô cùng nhỏ, bay lơ lửng tạo diện tích tiếp xúc khổng lồ với Oxi không khí. Phản ứng cháy lan truyền với tốc độ cực kì nhanh tạo thành vụ nổ", "Do bụi có chứa thuốc nổ", "Do bụi hấp thụ nhiệt của mặt trời", "Do bụi làm tăng áp suất của nhà xưởng"],
     "answer": 0, "explanation": "Bụi lơ lửng có diện tích bề mặt riêng khổng lồ. Gặp nguồn nhiệt sẽ bùng cháy tức thời sinh nhiệt và khí (Nổ bụi)."},
    {"id": "mc-c5-039", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Bài toán giảm nửa nồng độ",
     "question": "Phản ứng $A \\rightarrow \\text{Sản phẩm}$ là phản ứng đơn giản bậc 1 ($v = k[A]$). Khi nồng độ của A giảm đi một nửa so với ban đầu thì tốc độ phản ứng sẽ:",
     "choices": ["Giảm đi một nửa", "Giảm đi 4 lần", "Không đổi", "Tăng lên gấp đôi"],
     "answer": 0, "explanation": "Bậc 1: $v = k[A]$. $A$ giảm 2 lần $\\Rightarrow v$ giảm 2 lần."},
    {"id": "mc-c5-040", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Năng lượng hoạt hóa $E_a$ trên đồ thị",
     "question": "Trên đồ thị năng lượng, nếu ta vẽ thêm đường cong phản ứng khi có CHẤT XÚC TÁC, thì đường cong mới này sẽ có đặc điểm gì so với đường cong cũ?",
     "choices": ["Đỉnh của đường cong mới sẽ THẤP HƠN (mức năng lượng hoạt hóa $E_a$ nhỏ hơn)", "Đỉnh của đường cong mới sẽ CAO HƠN", "Mức năng lượng của chất tham gia bị hạ thấp", "Mức năng lượng của sản phẩm bị hạ thấp"],
     "answer": 0, "explanation": "Xúc tác tạo ra \"đường đi\" mới có rào cản năng lượng hoạt hóa ($E_a$) thấp hơn (đỉnh thấp hơn)."},

    # 20 câu thêm - củng cố kỹ năng phân loại, tính toán (41-60)
    {"id": "mc-c5-041", "chapter": "c5", "lesson": "b25", "level": "nb", "dang": "Trạng thái của chất trong biểu thức v",
     "question": "Trong biểu thức tính tốc độ phản ứng $v = k[A]^a[B]^b$, nồng độ của các chất nằm ở trạng thái nào thường KHÔNG được đưa vào biểu thức (do nồng độ coi như không đổi)?",
     "choices": ["Chất rắn (s)", "Chất khí (g)", "Chất tan trong dung dịch (aq)", "Chất lỏng (l) nếu nó không phải là dung môi"],
     "answer": 0, "explanation": "Nồng độ của một chất rắn tinh khiết được coi là hằng số (mật độ không đổi), nên nó được gộp luôn vào hằng số $k$, không hiện diện trong biểu thức. Ví dụ $C(s) + O_2(g) \\rightarrow CO_2$, $v = k'[O_2]$."},
    {"id": "mc-c5-042", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Yếu tố bề mặt",
     "question": "Cho đá vôi ($CaCO_3$) tác dụng với dung dịch $HCl$. Cách nào sau đây KHÔNG làm tăng tốc độ phản ứng?",
     "choices": ["Tăng áp suất của hệ", "Đập nhỏ viên đá vôi", "Tăng nồng độ $HCl$", "Đun nóng nhẹ dung dịch"],
     "answer": 0, "explanation": "Chất tham gia gồm Rắn và Lỏng, không có chất Khí. Việc tăng áp suất ngoài không làm thay đổi nồng độ các chất phản ứng $\\Rightarrow$ Tốc độ không đổi."},
    {"id": "mc-c5-043", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Nồng độ Tăng 2",
     "question": "Phản ứng $2A(g) + B(g) \\rightarrow C(g)$ (đơn giản). Nếu giữ nguyên thể tích, tăng số mol của A lên 2 lần, số mol của B lên 3 lần thì tốc độ phản ứng sẽ:",
     "choices": ["Tăng 12 lần", "Tăng 6 lần", "Tăng 18 lần", "Tăng 5 lần"],
     "answer": 0, "explanation": "Biểu thức: $v = k[A]^2[B]$. Khi $[A] \\rightarrow 2[A]$ và $[B] \\rightarrow 3[B]$, ta có: $v' = k(2A)^2(3B) = k \\cdot 4A^2 \\cdot 3B = 12k[A]^2[B] = 12v$. Tốc độ tăng 12 lần."},
    {"id": "mc-c5-044", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "So sánh Thời gian Vant Hoff",
     "question": "Một phản ứng thực hiện ở $10^\\circ\\text{C}$ tốn 27 phút để hoàn thành. Nếu thực hiện ở $40^\\circ\\text{C}$ thì chỉ tốn 1 phút. Tính hệ số nhiệt độ $\\gamma$?",
     "choices": ["3", "2", "4", "27"],
     "answer": 0, "explanation": "Thời gian giảm từ 27 xuống 1 phút $\\Rightarrow$ Tốc độ tăng 27 lần. $\\Delta T = 40 - 10 = 30^\\circ\\text{C}$ (3 khoảng). $\\gamma^3 = 27 \\Rightarrow \\gamma = 3$."},

    {"id": "mc-c5-045", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Khái niệm Hằng số Tốc độ",
     "question": "Phát biểu nào đúng về hằng số tốc độ $k$?",
     "choices": ["Ý nghĩa vật lí: $k$ chính là tốc độ của phản ứng khi nồng độ của tất cả các chất phản ứng đều bằng 1 M", "Giá trị của $k$ không phụ thuộc vào nhiệt độ", "$k$ có giá trị càng nhỏ thì phản ứng xảy ra càng nhanh", "Đơn vị của $k$ luôn luôn là $s^{-1}$"],
     "answer": 0, "explanation": "Từ $v = k[A]^a[B]^b$, nếu $[A]=[B]=1$, ta có $v = k$. Do đó $k$ là tốc độ riêng của phản ứng ở nồng độ chuẩn. Tốc độ thực tế $v$ phụ thuộc vào nồng độ, còn bản tính nhanh/chậm của phản ứng thể hiện qua độ lớn của $k$."},
    {"id": "mc-c5-046", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Năng lượng hoạt hóa thấp",
     "question": "Một phản ứng hóa học có Năng lượng hoạt hóa ($E_a$) rất NHỎ (gần bằng 0). Ở nhiệt độ phòng, tốc độ của phản ứng này sẽ:",
     "choices": ["Rất nhanh, xảy ra tức thời", "Rất chậm", "Hoàn toàn không xảy ra", "Cần phải đun nóng mới xảy ra được"],
     "answer": 0, "explanation": "Rào cản năng lượng (Ea) thấp $\\Rightarrow$ Phần lớn các hạt có động năng thắng được rào cản $\\Rightarrow$ Phản ứng xảy ra tức thời ở nhiệt độ thường."},
    {"id": "mc-c5-047", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Biểu diễn công thức tốc độ giảm dần",
     "question": "Nồng độ của chất phản ứng theo thời gian thường biến đổi theo dạng đồ thị nào?",
     "choices": ["Đường cong đi xuống, độ dốc giảm dần (Lõm lên)", "Đường thẳng đi xuống với hệ số góc không đổi", "Đường cong đi lên, độ dốc giảm dần", "Đường cong đi xuống nhưng độ dốc tăng dần"],
     "answer": 0, "explanation": "Lúc đầu nồng độ lớn $\\Rightarrow$ v lớn $\\Rightarrow$ nồng độ giảm nhanh (dốc). Càng về sau, nồng độ càng ít $\\Rightarrow$ v chậm lại $\\Rightarrow$ nồng độ giảm từ từ (thoải dần), tiệm cận trục hoành hoặc tiệm cận giá trị cân bằng. Nên là đường cong đi xuống, dốc thoải dần."},
    {"id": "mc-c5-048", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Chất xúc tác có tham gia pư không",
     "question": "Phát biểu \"Chất xúc tác không tham gia vào phản ứng hóa học\" là:",
     "choices": ["Sai, chất xúc tác CÓ tham gia vào các giai đoạn trung gian của phản ứng, nhưng sau đó được tái tạo lại nguyên vẹn", "Đúng, chất xúc tác chỉ đứng ngoài để kích thích", "Đúng, nó tạo từ trường làm tăng tốc độ", "Sai, chất xúc tác bị phân hủy hoàn toàn"],
     "answer": 0, "explanation": "Để hạ năng lượng hoạt hóa, chất xúc tác bắt buộc phải tương tác hóa học tạo phức chất hoạt động với chất phản ứng, sau đó tự tái sinh."},

    {"id": "mc-c5-049", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Nồng độ thay đổi Thể tích",
     "question": "Phản ứng khí $A \\rightarrow B$ (bậc 1). Để tốc độ phản ứng giảm đi 2 lần, ta phải thay đổi thể tích của bình phản ứng như thế nào?",
     "choices": ["Tăng thể tích lên 2 lần", "Giảm thể tích đi 2 lần", "Tăng thể tích lên 4 lần", "Không cần đổi thể tích"],
     "answer": 0, "explanation": "Bậc 1 ($v \\sim C$). Muốn C giảm 2 thì V phải tăng 2 (do $C = n/V$)."},
    {"id": "mc-c5-050", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Nhiệt độ thay đổi 15 độ C",
     "question": "Một phản ứng có $\\gamma = 2$. Nếu tăng nhiệt độ lên $15^\\circ\\text{C}$ thì tốc độ phản ứng tăng lên bao nhiêu lần?",
     "choices": ["2,83 lần", "3 lần", "4 lần", "1,5 lần"],
     "answer": 0, "explanation": "Áp dụng đúng biểu thức $v_2/v_1 = \\gamma^{\\Delta T / 10} = 2^{1,5} \\approx 2,83$."},

    {"id": "mc-c5-051", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Bình ga cháy nổ",
     "question": "Mở khóa bếp gas nhưng không châm lửa ngay, một lúc sau mới bật lửa thì nghe tiếng nổ bùm và ngọn lửa phực rất to. Vì sao?",
     "choices": ["Vì khí gas đã thoát ra trộn với oxi không khí tạo thành hỗn hợp có nồng độ lớn, diện tích tiếp xúc cao, cháy đồng loạt gây nổ", "Vì khí gas tự nóng lên", "Vì có chất xúc tác bay ra", "Vì gas bị tăng áp suất"],
     "answer": 0, "explanation": "Hỗn hợp khí (gas + $O_2$) đã đạt nồng độ lớn. Phản ứng cháy trong không gian rộng diễn ra đồng loạt tạo sức nổ mạnh."},
    {"id": "mc-c5-052", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Tính Toán Tổng hợp Nồng độ và Áp suất",
     "question": "Phản ứng $N_2 + 3H_2 \\rightarrow 2NH_3$ (giả sử là phản ứng đơn giản). Nếu vừa tăng áp suất hệ lên 2 lần, vừa tăng nhiệt độ từ $30^\\circ$ lên $50^\\circ$ ($\\gamma=2$). Tốc độ phản ứng sẽ thay đổi bao nhiêu lần?",
     "choices": ["Tăng 64 lần", "Tăng 16 lần", "Tăng 32 lần", "Tăng 8 lần"],
     "answer": 0, "explanation": "Do Nén (áp suất): $v_P = 2^1 \\times 2^3 = 16$. Do Nhiệt: $v_T = 2^{(50-30)/10} = 4$. Tổng tăng $= 16 \\times 4 = 64$ lần."},
    
    {"id": "mc-c5-053", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Xúc tác đồng thể và dị thể",
     "question": "Phản ứng cracking dầu mỏ dùng chất xúc tác dạng bột nhôm silicat (rắn) trộn vào hơi dầu mỏ (khí). Đây là loại xúc tác nào?",
     "choices": ["Xúc tác dị thể (xúc tác và chất phản ứng khác trạng thái pha)", "Xúc tác đồng thể", "Xúc tác sinh học", "Xúc tác âm"],
     "answer": 0, "explanation": "Chất xúc tác là thể rắn, chất tham gia là thể khí $\\Rightarrow$ Tồn tại ranh giới pha $\\Rightarrow$ Xúc tác dị thể."},
    {"id": "mc-c5-054", "chapter": "c5", "lesson": "b25", "level": "th", "dang": "Tốc độ tại thời điểm t",
     "question": "Trong suốt quá trình phản ứng $A \\rightarrow B$ đang diễn ra (không bổ sung thêm chất A), tốc độ của phản ứng sẽ:",
     "choices": ["Lớn nhất ở thời điểm ban đầu và giảm dần theo thời gian", "Không thay đổi", "Tăng dần theo thời gian", "Chậm lúc đầu, nhanh lúc sau"],
     "answer": 0, "explanation": "Do nồng độ chất phản ứng liên tục sụt giảm, dẫn đến tần số va chạm giảm, kéo theo tốc độ phản ứng luôn có xu hướng giảm dần."},
    
    {"id": "mc-c5-055", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Phản ứng bậc 0",
     "question": "Một số phản ứng quang hóa hoặc phản ứng trên bề mặt kim loại rắn có tốc độ HOÀN TOÀN KHÔNG thay đổi dù nồng độ chất khí tăng lên. Phản ứng này có Bậc phản ứng bằng mấy?",
     "choices": ["Bậc 0 ($v = k$)", "Bậc 1 ($v = k[A]$)", "Bậc 2", "Không xác định được"],
     "answer": 0, "explanation": "Khi tốc độ độc lập với nồng độ chất tham gia, biểu thức có dạng $v=k$. Tương đương nồng độ mũ 0 $\\Rightarrow$ Phản ứng bậc 0."},
    
    {"id": "mc-c5-056", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Cơ chế tác động bề mặt",
     "question": "Nấu cháo bằng thịt băm nhỏ sẽ nhanh nhừ hơn so với nấu nguyên khối thịt. Yếu tố nào KHÔNG liên quan trực tiếp đến hiện tượng này?",
     "choices": ["Chất xúc tác", "Diện tích bề mặt tiếp xúc", "Nhiệt độ (đun nóng)", "Tất cả đều sai"],
     "answer": 0, "explanation": "Quá trình nhừ thịt chủ yếu do phân cắt protein bởi nhiệt và nước. Cắt nhỏ = tăng diện tích tiếp xúc. Không sử dụng thêm hóa chất xúc tác nào."},
    {"id": "mc-c5-057", "chapter": "c5", "lesson": "b26", "level": "vd", "dang": "Bài toán giảm 1 chất tăng 1 chất",
     "question": "Phản ứng $A + 2B \\rightarrow C$ (đơn giản). Nếu tăng nồng độ A lên gấp đôi, đồng thời GIẢM nồng độ B đi một nửa, thì tốc độ phản ứng sẽ:",
     "choices": ["Giảm đi một nửa", "Giữ nguyên", "Tăng gấp đôi", "Giảm 4 lần"],
     "answer": 0, "explanation": "Tỉ lệ tốc độ mới $v' = 2^1 \\times (1/2)^2 = 2 \\times 0,25 = 0,5$. Tốc độ giảm đi 1/2."},
    {"id": "mc-c5-058", "chapter": "c5", "lesson": "b25", "level": "vd", "dang": "Tính Toán $\\bar{v}$ với đồ thị thực tiễn",
     "question": "Sự phân hủy $H_2O_2$: Tại $t=0$, $[H_2O_2] = 1,00 \\text{ M}$. Tại $t = 120 \\text{ s}$, $[H_2O_2] = 0,76 \\text{ M}$. Tốc độ trung bình sự tiêu hao $H_2O_2$ là:",
     "choices": ["$2,0 \\times 10^{-3} \\text{ M/s}$", "$8,3 \\times 10^{-3} \\text{ M/s}$", "$6,3 \\times 10^{-3} \\text{ M/s}$", "$1,0 \\times 10^{-3} \\text{ M/s}$"],
     "answer": 0, "explanation": "Độ giảm nồng độ $= 0,24 \\text{ M}$. Thời gian $= 120 \\text{ s}$. Tốc độ $= 0,24 / 120 = 2 \\times 10^{-3} \\text{ M/s}$."},
    {"id": "mc-c5-059", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Điều kiện hệ xúc tác hoạt động",
     "question": "Bộ chuyển đổi xúc tác (Catalytic converter) ở ống xả ô tô chứa platin/rhodium giúp phân hủy khí độc CO, NO thành $CO_2, N_2$. Xúc tác này thường chỉ hoạt động hiệu quả khi:",
     "choices": ["Khí thải đã đạt nhiệt độ rất cao (động cơ đã nóng)", "Khi động cơ vừa khởi động và còn lạnh", "Khi xe chạy bằng điện", "Khi trời mưa"],
     "answer": 0, "explanation": "Xúc tác rắn (Pt, Rh) cần nhiệt độ đủ cao để đạt trạng thái hoạt hóa mạnh bề mặt, đẩy nhanh phản ứng chuyển hóa khí độc."},
    {"id": "mc-c5-060", "chapter": "c5", "lesson": "b26", "level": "th", "dang": "Tổng quan Ý nghĩa tốc độ",
     "question": "Yếu tố nào có thể KHÔNG làm thay đổi Tốc độ của phản ứng mà chỉ làm thay đổi Lượng sản phẩm cuối cùng sinh ra?",
     "choices": ["Tăng khối lượng chất rắn tham gia phản ứng (mà không đập nhỏ nó)", "Tăng nhiệt độ đun nóng", "Thay đổi nồng độ dung dịch từ 1M lên 5M", "Dùng chất xúc tác bột mịn"],
     "answer": 0, "explanation": "Lượng chất phản ứng (khối lượng dư) quyết định Hậu quả (lượng sản phẩm max), nhưng không quyết định Tốc độ (v)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C5 Part 1 written successfully.")
