import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 1 HÓA HỌC 10: CẤU TẠO NGUYÊN TỬ ---
    # Nhóm 1, 2, 3: Thành phần nguyên tử
    {"id": "mc-c1-001", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Thành phần nguyên tử",
     "question": "Hạt nhân của hầu hết các nguyên tử đều được tạo thành từ các hạt nào sau đây?",
     "choices": ["Proton và neutron", "Proton và electron", "Neutron và electron", "Proton, neutron và electron"],
     "answer": 0, "explanation": "Nguyên tử gồm vỏ (chứa electron) và hạt nhân. Hạt nhân chứa proton (mang điện dương) và neutron (không mang điện). (Trừ nguyên tử Hydrogen $^1_1H$ không có neutron)."},
    {"id": "mc-c1-002", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Đặc điểm hạt vi mô",
     "question": "Hạt mang điện tích âm trong nguyên tử là:",
     "choices": ["Electron", "Proton", "Neutron", "Hạt nhân"],
     "answer": 0, "explanation": "Electron (e) mang điện tích âm ($-1.6 \\times 10^{-19}$ C, hay $-1$ đtd), quay xung quanh hạt nhân."},
    {"id": "mc-c1-003", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Đặc điểm hạt vi mô",
     "question": "Trong nguyên tử, hạt nào có khối lượng xấp xỉ bằng không (rất nhỏ so với các hạt khác)?",
     "choices": ["Electron", "Proton", "Neutron", "Quark"],
     "answer": 0, "explanation": "Khối lượng của 1 electron chỉ bằng khoảng $1/1836$ khối lượng của proton hoặc neutron, do đó khối lượng nguyên tử tập trung hầu hết ở hạt nhân."},
    {"id": "mc-c1-004", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Bản chất điện",
     "question": "Nguyên tử trung hòa về điện là do:",
     "choices": ["Số lượng hạt proton bằng số lượng hạt electron", "Số hạt proton bằng số hạt neutron", "Tổng số hạt mang điện bằng tổng số hạt không mang điện", "Nguyên tử không có hạt mang điện"],
     "answer": 0, "explanation": "Nguyên tử trung hòa về điện $\\Rightarrow$ Tổng điện tích dương bằng tổng điện tích âm. Mỗi proton là $+1$, mỗi electron là $-1$, do đó số proton ($Z$) = số electron ($E$)."},

    {"id": "mc-c1-005", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Khối lượng nguyên tử",
     "question": "Đơn vị khối lượng nguyên tử (amu) được định nghĩa là:",
     "choices": ["$1/12$ khối lượng của một nguyên tử đồng vị Carbon-12", "Khối lượng của một nguyên tử Hydrogen", "Khối lượng của 1 proton", "$1/16$ khối lượng của nguyên tử Oxygen-16"],
     "answer": 0, "explanation": "Theo hệ SI, $1\\text{ amu}$ (đvC cũ) $= 1/12$ khối lượng nguyên tử $C-12$. $1\\text{ amu} \\approx 1.6605 \\times 10^{-27}\\text{ kg}$."},
    {"id": "mc-c1-006", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Bài toán thành phần",
     "question": "Tổng số hạt cơ bản (proton, neutron, electron) trong nguyên tử X là 40. Trong đó tổng số hạt mang điện nhiều hơn số hạt không mang điện là 12. Số hạt proton trong nguyên tử X là:",
     "choices": ["13", "14", "12", "11"],
     "answer": 0, "explanation": "Ta có hệ phương trình: Tổng hạt $2Z + N = 40$. Mang điện nhiều hơn không mang điện: $2Z - N = 12$. Cộng vế: $4Z = 52 \\Rightarrow Z = 13$ (Proton = 13, $N = 40 - 26 = 14$). Nguyên tố đó là Nhôm (Al)."},
    {"id": "mc-c1-007", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Bài toán thành phần",
     "question": "Nguyên tử Y có tổng số hạt p, n, e là 58. Số hạt mang điện gấp 1,9 lần số hạt không mang điện. Y là nguyên tố nào? (Cho số hiệu Z: 18-Ar, 19-K, 20-Ca, 17-Cl)",
     "choices": ["K (Z=19)", "Ca (Z=20)", "Ar (Z=18)", "Cl (Z=17)"],
     "answer": 0, "explanation": "$2Z + N = 58$ và $2Z = 1.9N$. Thay $2Z$ vào phương trình đầu: $1.9N + N = 58 \\Rightarrow 2.9N = 58 \\Rightarrow N = 20$. Suy ra $2Z = 1.9 \\times 20 = 38 \\Rightarrow Z = 19$. Z=19 là nguyên tố Potassium (Kali - K)."},
    {"id": "mc-c1-008", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Ion",
     "question": "Một ion $M^{2+}$ có tổng số hạt (p, n, e) là 92. Trong hạt nhân, số hạt không mang điện nhiều hơn số hạt mang điện là 5. Số hạt electron của ion $M^{2+}$ là:",
     "choices": ["27", "29", "25", "31"],
     "answer": 0, "explanation": "Gọi Z, N là số hạt của nguyên tử M. Tổng hạt ion $M^{2+}$ là $(Z) + (N) + (Z - 2) = 2Z + N - 2 = 92 \\Rightarrow 2Z + N = 94$. Nếu giải ra e của ion là 27 $\\Rightarrow$ e nguyên tử = 29 $\\Rightarrow Z=29$ (Đồng Cu). Khi đó $N = 94 - 2(29) = 36$. Hạt nhân Cu: $N - Z = 36 - 29 = 7$. (Giả sử đề bài số hạt không mang điện lớn hơn mang điện là 7). Vậy số electron của ion $M^{2+}$ là 27."},

    # Nhóm 4, 5: Kích thước và Trọng lượng nguyên tử
    {"id": "mc-c1-009", "chapter": "c1", "lesson": "b1", "level": "nb", "dang": "Kích thước nguyên tử",
     "question": "Kích thước của nguyên tử lớn hơn kích thước của hạt nhân khoảng bao nhiêu lần?",
     "choices": ["10 000 lần", "100 lần", "1 000 lần", "1 000 000 lần"],
     "answer": 0, "explanation": "Đường kính nguyên tử cỡ $10^{-10}\\text{ m}$, đường kính hạt nhân cỡ $10^{-15} - 10^{-14}\\text{ m}$. Do đó nguyên tử lớn hơn hạt nhân từ $10^4$ đến $10^5$ lần. Nguyên tử có cấu tạo vô cùng rỗng."},
    {"id": "mc-c1-010", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Đổi đơn vị",
     "question": "Đơn vị thường dùng để đo kích thước của nguyên tử là $\\text{Angstrom} (\\mathring{A})$ hoặc nanômét (nm). Mối liên hệ nào sau đây đúng?",
     "choices": ["$1 \\mathring{A} = 0,1\\text{ nm}$", "$1 \\mathring{A} = 10\\text{ nm}$", "$1\\text{ nm} = 10^{-9}\\text{ cm}$", "$1 \\mathring{A} = 10^{-10}\\text{ mm}$"],
     "answer": 0, "explanation": "$1\\text{ nm} = 10^{-9}\\text{ m}$. $1 \\mathring{A} = 10^{-10}\\text{ m}$. Vậy $1\\text{ nm} = 10 \\mathring{A}$, suy ra $1 \\mathring{A} = 0,1\\text{ nm}$. (Cũng bằng $100\\text{ pm}$)."},
    {"id": "mc-c1-011", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Bán kính nguyên tử",
     "question": "Khối lượng riêng của tinh thể Cu là $8,93\\text{ g/cm}^3$. Giả sử các nguyên tử Cu là những hình cầu xếp đặc khít chiếm 74% thể tích tinh thể, còn lại là khe trống. Biết khối lượng mol của Cu là 63,55 g/mol. Bán kính nguyên tử của Cu gần nhất với giá trị nào?",
     "choices": ["$0,128\\text{ nm}$", "$0,144\\text{ nm}$", "$0,152\\text{ nm}$", "$0,197\\text{ nm}$"],
     "answer": 0, "explanation": "Thể tích 1 mol nguyên tử Cu (kể cả khe rỗng): $V_{mol} = M / D = 63,55 / 8,93 = 7,116\\text{ cm}^3/mol$. Thể tích thực của 1 mol hạt Cu: $V_{thuc} = V_{mol} \\times 74\\% = 5,266\\text{ cm}^3$. Thể tích 1 nguyên tử $V_{1nt} = V_{thuc} / N_A = 5,266 / (6,022\\cdot 10^{23}) = 8,74\\cdot 10^{-24}\\text{ cm}^3$. Hình cầu $V = \\frac{4}{3}\\pi r^3 \\Rightarrow r = \\sqrt[3]{\\frac{3V}{4\\pi}} = \\sqrt[3]{2,08\\cdot 10^{-24}} \\approx 1,277\\cdot 10^{-8}\\text{ cm} = 1,28 \\mathring{A} = 0,128\\text{ nm}$."},
    {"id": "mc-c1-012", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Hạt nhân",
     "question": "Nếu coi hạt nhân nguyên tử như một quả bóng bàn có đường kính 3 cm thì đường kính nguyên tử xấp xỉ bằng:",
     "choices": ["300 mét", "30 mét", "3 km", "3 mét"],
     "answer": 0, "explanation": "Nguyên tử lớn hơn hạt nhân khoảng $10^4$ lần. Đường kính hạt nhân 3 cm $\\Rightarrow$ Đường kính nguyên tử $\\approx 3\\text{ cm} \\times 10000 = 30000\\text{ cm} = 300\\text{ m}$. (Tương đương kích thước 1 sân vận động lớn)."},

    # Nhóm 6, 7, 8: Nguyên tố hóa học và Đồng vị
    {"id": "mc-c1-013", "chapter": "c1", "lesson": "b2", "level": "nb", "dang": "Khái niệm Nguyên tố",
     "question": "Nguyên tố hóa học là tập hợp các nguyên tử có cùng đặc điểm nào?",
     "choices": ["Cùng điện tích hạt nhân (cùng số proton)", "Cùng số khối (tổng số proton và neutron)", "Cùng khối lượng nguyên tử", "Cùng số neutron"],
     "answer": 0, "explanation": "Nguyên tố hóa học là tập hợp các nguyên tử có cùng điện tích hạt nhân (cùng Z). Dù khác số neutron (đồng vị), chúng vẫn thuộc cùng một nguyên tố."},
    {"id": "mc-c1-014", "chapter": "c1", "lesson": "b2", "level": "nb", "dang": "Số khối",
     "question": "Số khối của hạt nhân (kí hiệu là A) được tính bằng:",
     "choices": ["Tổng số proton và tổng số neutron ($A = Z + N$)", "Tổng số proton và electron", "Hiệu số của số neutron và proton", "Số lượng các electron lớp ngoài cùng"],
     "answer": 0, "explanation": "Số khối (Mass number) A = Số proton (Z) + Số neutron (N)."},
    {"id": "mc-c1-015", "chapter": "c1", "lesson": "b2", "level": "th", "dang": "Kí hiệu nguyên tử",
     "question": "Kí hiệu nguyên tử của một nguyên tố X có dạng $^A_Z X$. Kí hiệu này cho ta biết điều gì?",
     "choices": ["Kí hiệu hóa học của nguyên tố (X), số khối (A) và số hiệu nguyên tử (Z)", "Kí hiệu (X), số khối (A) và số lớp electron (Z)", "Kí hiệu (X), số nguyên tử (A) và khối lượng (Z)", "Kí hiệu (X), nguyên tử khối (Z) và số proton (A)"],
     "answer": 0, "explanation": "Chữ phía trên (A) là số khối, chữ phía dưới (Z) là số hiệu nguyên tử (điện tích hạt nhân). Ví dụ: $^{23}_{11}Na$."},
    {"id": "mc-c1-016", "chapter": "c1", "lesson": "b2", "level": "th", "dang": "Đọc kí hiệu",
     "question": "Nguyên tử $^{56}_{26}Fe$ có chứa bao nhiêu hạt cơ bản mỗi loại?",
     "choices": ["26 proton, 30 neutron, 26 electron", "26 proton, 56 neutron, 26 electron", "56 proton, 26 neutron, 56 electron", "26 proton, 30 neutron, 56 electron"],
     "answer": 0, "explanation": "$Z = 26 \\Rightarrow p = e = 26$. $A = 56 \\Rightarrow n = A - Z = 56 - 26 = 30$."},

    {"id": "mc-c1-017", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Khái niệm Đồng vị",
     "question": "Các đồng vị của cùng một nguyên tố hóa học là những nguyên tử có đặc điểm gì?",
     "choices": ["Cùng số proton nhưng khác nhau về số neutron", "Cùng số neutron nhưng khác nhau về số proton", "Cùng số khối A nhưng khác nhau về số hiệu nguyên tử Z", "Cùng khối lượng nguyên tử nhưng khác nhau tính chất hóa học"],
     "answer": 0, "explanation": "Đồng vị (Isotopes) có cùng vị trí trong Bảng tuần hoàn (cùng Z, cùng tính chất hóa học cơ bản), nhưng khác nhau số hạt n $\\Rightarrow$ khác số khối A."},
    {"id": "mc-c1-018", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Nhận biết đồng vị",
     "question": "Trong các kí hiệu sau, cặp nguyên tử nào là đồng vị của nhau? (1) $^{16}_8X$, (2) $^{17}_8Y$, (3) $^{14}_7Z$, (4) $^{14}_6T$.",
     "choices": ["(1) và (2)", "(3) và (4)", "(1) và (4)", "(2) và (3)"],
     "answer": 0, "explanation": "Đồng vị phải có cùng số hiệu nguyên tử Z (số phía dưới). Kí hiệu (1) và (2) đều có $Z=8$ (nguyên tố Oxygen). Cặp (3) và (4) có cùng số khối A=14 nhưng khác Z (gọi là chất đồng lượng - isobar, không phải đồng vị)."},
    {"id": "mc-c1-019", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Đồng vị Hidro",
     "question": "Hydrogen có 3 đồng vị tự nhiên: Protium ($^1_1H$), Deuterium ($^2_1H$) và Tritium ($^3_1H$). Phân tử nước $H_2O$ được cấu tạo từ đồng vị nào?",
     "choices": ["Có thể tạo từ bất kì đồng vị nào, nhưng phổ biến nhất là Protium ($^1_1H$)", "Chỉ được tạo từ Deuterium", "Chỉ được tạo từ Tritium", "Nước tự nhiên không chứa các đồng vị này"],
     "answer": 0, "explanation": "Hydro tự nhiên chiếm 99,985% là $^1_1H$. Nước chứa đồng vị $^2_1H$ (D) gọi là nước nặng ($D_2O$). Nước bình thường chủ yếu là $H_2O$ (từ Protium)."},
    {"id": "mc-c1-020", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Khối lượng đồng vị",
     "question": "Tại sao nguyên tử khối của hầu hết các nguyên tố trong bảng tuần hoàn (như $Cl: 35,45$) lại là những con số thập phân không nguyên?",
     "choices": ["Vì nó là nguyên tử khối trung bình của hỗn hợp các đồng vị tự nhiên theo tỉ lệ phần trăm", "Vì khối lượng của proton và neutron không phải là số nguyên", "Vì electron bị mất đi khi đo khối lượng", "Vì sai số của các phép đo vật lí"],
     "answer": 0, "explanation": "Các nguyên tố tồn tại ở dạng hỗn hợp nhiều đồng vị. Bảng tuần hoàn ghi Nguyên tử khối trung bình dựa trên sự phong phú tự nhiên (phần trăm) của chúng."},

    # Nhóm 9, 10, 11: Nguyên tử khối trung bình
    {"id": "mc-c1-021", "chapter": "c1", "lesson": "b2", "level": "th", "dang": "Công thức trung bình",
     "question": "Công thức tính nguyên tử khối trung bình ($\\overline{M}$) của một nguyên tố có 2 đồng vị A và B (với tỉ lệ phần trăm số nguyên tử tương ứng là a% và b%) là:",
     "choices": ["$\\overline{M} = \\frac{a \\cdot A + b \\cdot B}{100}$", "$\\overline{M} = \\frac{A + B}{2}$", "$\\overline{M} = \\frac{a \\cdot B + b \\cdot A}{100}$", "$\\overline{M} = \\frac{A \\cdot a + B \\cdot b}{a \\cdot b}$"],
     "answer": 0, "explanation": "Nguyên tử khối trung bình được tính bằng trung bình cộng có trọng số (phần trăm)."},
    {"id": "mc-c1-022", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Tính NTK trung bình",
     "question": "Trong tự nhiên, nguyên tố Chlorine (Cl) có hai đồng vị bền là $^{35}Cl$ chiếm 75,77% và $^{37}Cl$ chiếm 24,23%. Nguyên tử khối trung bình của Chlorine là:",
     "choices": ["35,48", "36,00", "35,00", "35,50"],
     "answer": 0, "explanation": "$\\overline{A} = (35 \\times 75.77 + 37 \\times 24.23) / 100 = (2651.95 + 896.51) / 100 = 3548.46 / 100 = 35.4846$. Thường lấy xấp xỉ 35.45 (vì NTK chuẩn của $Cl-35$ là 34.9688, $Cl-37$ là 36.9659. Nếu dùng số khối chẵn 35 và 37 thì ra 35.48). Đáp án đúng theo phép tính là 35,48."},
    {"id": "mc-c1-023", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Tìm phần trăm đồng vị",
     "question": "Nguyên tố Copper (Cu) có hai đồng vị là $^{63}Cu$ và $^{65}Cu$. Nguyên tử khối trung bình của Cu là 63,54. Thành phần phần trăm số nguyên tử của đồng vị $^{63}Cu$ là:",
     "choices": ["73%", "27%", "50%", "63,5%"],
     "answer": 0, "explanation": "Gọi phần trăm $^{63}Cu$ là x. $\\Rightarrow \\frac{63x + 65(100 - x)}{100} = 63.54 \\Rightarrow 63x + 6500 - 65x = 6354 \\Rightarrow 2x = 146 \\Rightarrow x = 73$. Vậy $^{63}Cu$ chiếm 73%, $^{65}Cu$ chiếm 27%."},
    {"id": "mc-c1-024", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Tính số khối đồng vị",
     "question": "Nguyên tố Bromine (Br) có NTK trung bình là 79,91. Bromine có hai đồng vị, trong đó đồng vị $^{79}Br$ chiếm 54,5%. Số khối của đồng vị thứ hai là bao nhiêu?",
     "choices": ["81", "80", "82", "78"],
     "answer": 0, "explanation": "Đồng vị hai chiếm $100 - 54.5 = 45.5\\%$. Gọi số khối là A. $\\frac{79 \\times 54.5 + A \\times 45.5}{100} = 79.91 \\Rightarrow 4305.5 + 45.5 A = 7991 \\Rightarrow 45.5 A = 3685.5 \\Rightarrow A = 3685.5 / 45.5 = 81$."},

    {"id": "mc-c1-025", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Mở rộng khối lượng phân tử",
     "question": "Oxy có ba đồng vị tự nhiên: $^{16}O, ^{17}O, ^{18}O$. Carbon có hai đồng vị tự nhiên: $^{12}C, ^{13}C$. Có tối đa bao nhiêu loại phân tử khí Carbon dioxide ($CO_2$) được tạo thành từ các đồng vị trên?",
     "choices": ["12 loại", "9 loại", "18 loại", "6 loại"],
     "answer": 0, "explanation": "Phân tử $CO_2$ gồm 1 nguyên tử C và 2 nguyên tử O. C có 2 cách chọn. Cặp 2 nguyên tử O có thể giống nhau ($16-16, 17-17, 18-18$) $\\Rightarrow 3$ cách. Cặp 2 nguyên tử O khác nhau ($16-17, 16-18, 17-18$) $\\Rightarrow 3$ cách. (Do phân tử đối xứng O-C-O, 16-C-17 và 17-C-16 là một). Tổng số cách chọn O là $3 + 3 = 6$. Tổng số phân tử $CO_2 = 2 \\times 6 = 12$ loại."},
    {"id": "mc-c1-026", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Khối lượng hợp chất đồng vị",
     "question": "Biết Chlorine có 2 đồng vị $^{35}Cl$ (75%) và $^{37}Cl$ (25%). Hydrogen có $^{1}H$ (99%) và $^{2}H$ (1%). Phân tử $HCl$ nặng nhất có phân tử khối là bao nhiêu?",
     "choices": ["39", "38", "36", "37"],
     "answer": 0, "explanation": "Phân tử khối nặng nhất khi chứa các đồng vị nặng nhất: $^2H$ (D) và $^{37}Cl$. Khối lượng = $2 + 37 = 39$."},
    {"id": "mc-c1-027", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Phần trăm khối lượng đồng vị",
     "question": "Cho $Cu = 63,54$. Có hai đồng vị $^{63}Cu$ (73%) và $^{65}Cu$ (27%). Tính phần trăm khối lượng của đồng vị $^{63}Cu$ có trong hợp chất $CuSO_4$ (Cho $S=32, O=16$).",
     "choices": ["28,8%", "73%", "39,8%", "19,5%"],
     "answer": 0, "explanation": "Phân tử khối trung bình $CuSO_4 = 63.54 + 32 + 16 \\times 4 = 159.54$. Trong 1 mol $CuSO_4$ (nặng 159.54g) có chứa 1 mol Cu. Trong đó số mol $^{63}Cu$ là 0.73 mol. Khối lượng $^{63}Cu = 0.73 \\times 63 = 45.99$ g. Phần trăm khối lượng = $(45.99 / 159.54) \\times 100\\% \\approx 28.8\\%$."},
    {"id": "mc-c1-028", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Tính tỉ lệ nguyên tử",
     "question": "Nguyên tố Boron (B) có hai đồng vị $^{10}B$ và $^{11}B$. Nguyên tử khối trung bình là 10,81. Tính tỉ lệ số nguyên tử của $^{11}B$ so với $^{10}B$.",
     "choices": ["81/19", "19/81", "10/11", "4/1"],
     "answer": 0, "explanation": "Gọi x là % $^{11}B$, $(100-x)$ là % $^{10}B$. $11x + 10(100-x) = 1081 \Rightarrow x + 1000 = 1081 \Rightarrow x = 81$. Vậy $^{11}B$ chiếm 81%, $^{10}B$ chiếm 19%. Tỉ lệ $^{11}B / ^{10}B = 81 / 19$ (Khoảng 4,26/1)."},

    # Nhóm 12, 13: Cấu trúc vỏ nguyên tử (Mô hình Rutherford-Bohr và Orbital)
    {"id": "mc-c1-029", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Mô hình nguyên tử",
     "question": "Theo mô hình hành tinh nguyên tử của Rutherford - Bohr, các electron chuyển động như thế nào?",
     "choices": ["Chuyển động trên những quỹ đạo xác định (hình tròn hoặc bầu dục) xung quanh hạt nhân, giống như các hành tinh quay quanh Mặt Trời", "Chuyển động hỗn loạn vô trật tự, tạo thành đám mây điện tử", "Đứng yên tại các vị trí xác định ở vỏ nguyên tử", "Chuyển động theo quỹ đạo hình sin"],
     "answer": 0, "explanation": "Mô hình cổ điển của Bohr cho rằng e quay trên các quỹ đạo tròn/bầu dục (quỹ đạo Bohr) với năng lượng xác định."},
    {"id": "mc-c1-030", "chapter": "c1", "lesson": "b3", "level": "nb", "dang": "Mô hình hiện đại",
     "question": "Theo mô hình nguyên tử hiện đại (mô hình cơ học lượng tử), nhận định nào sau đây là ĐÚNG về sự chuyển động của electron?",
     "choices": ["Electron chuyển động rất nhanh xung quanh hạt nhân không theo quỹ đạo xác định nào, tạo thành đám mây electron", "Electron chuyển động theo quỹ đạo hình tròn cố định", "Vị trí của electron luôn được xác định chính xác tại mọi thời điểm", "Electron rơi dần vào hạt nhân do lực hút tĩnh điện"],
     "answer": 0, "explanation": "Mô hình lượng tử (đám mây electron) bác bỏ quỹ đạo xác định. Ta chỉ có thể tính xác suất tìm thấy e tại một vị trí trong không gian (Orbital nguyên tử - AO)."},
    {"id": "mc-c1-031", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Khái niệm Orbital",
     "question": "Orbital nguyên tử (AO - Atomic Orbital) là gì?",
     "choices": ["Khu vực không gian xung quanh hạt nhân mà tại đó xác suất có mặt (tìm thấy) electron là lớn nhất (thường $\\ge 90\\%$)", "Quỹ đạo chuyển động hình tròn của electron", "Lớp vỏ ngoài cùng của nguyên tử", "Một hạt cơ bản mới được tìm ra"],
     "answer": 0, "explanation": "AO là một vùng không gian 3 chiều quanh hạt nhân, nơi tập trung xác suất lớn nhất (khoảng 90%) để tìm thấy 1 electron."},
    {"id": "mc-c1-032", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Hình dạng Orbital",
     "question": "Hình dạng của các orbital nguyên tử lớp s và phân lớp p lần lượt là:",
     "choices": ["Orbital s có hình cầu, orbital p có hình số 8 nổi (hình quả tạ)", "Orbital s hình tròn, orbital p hình elip", "Orbital s hình vuông, orbital p hình số 8", "Cả hai đều có dạng hình cầu"],
     "answer": 0, "explanation": "AO s (lớp con s) có dạng đối xứng cầu. AO p có dạng số 8 nổi định hướng theo 3 trục tọa độ x, y, z ($p_x, p_y, p_z$)."},

    {"id": "mc-c1-033", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Các phân lớp AO",
     "question": "Số lượng orbital trong các phân lớp s, p, d, f lần lượt là:",
     "choices": ["1, 3, 5, 7", "1, 2, 3, 4", "2, 6, 10, 14", "1, 3, 6, 9"],
     "answer": 0, "explanation": "Phân lớp s có 1 AO. Phân lớp p có 3 AO. Phân lớp d có 5 AO. Phân lớp f có 7 AO. Các số lẻ liên tiếp 1, 3, 5, 7."},
    {"id": "mc-c1-034", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Số lượng electron tối đa",
     "question": "Theo nguyên lí Pauli, mỗi orbital nguyên tử chứa tối đa bao nhiêu electron?",
     "choices": ["2 electron (có spin ngược chiều nhau)", "1 electron", "8 electron", "Tùy thuộc vào lớp electron"],
     "answer": 0, "explanation": "Nguyên lí loại trừ Pauli: Mỗi AO chứa tối đa 2 e và phải có chiều tự quay (spin) ngược nhau (để giảm thiểu lực đẩy từ tính)."},
    {"id": "mc-c1-035", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Kí hiệu lớp electron",
     "question": "Các lớp electron được đánh số n = 1, 2, 3, 4, ... ứng với các kí hiệu chữ cái lần lượt là:",
     "choices": ["K, L, M, N", "A, B, C, D", "s, p, d, f", "x, y, z, t"],
     "answer": 0, "explanation": "Kí hiệu lớp: n=1 (lớp K), n=2 (lớp L), n=3 (lớp M), n=4 (lớp N), O, P, Q. (s, p, d, f là kí hiệu của phân lớp - subshell)."},
    {"id": "mc-c1-036", "chapter": "c1", "lesson": "b3", "level": "vd", "dang": "Sức chứa tối đa của lớp",
     "question": "Số electron tối đa mà lớp thứ n (với n $\\le 4$) có thể chứa được tính bằng công thức:",
     "choices": ["$2n^2$", "$n^2$", "$2n$", "$2n+2$"],
     "answer": 0, "explanation": "Lớp thứ n có n phân lớp, tổng số AO là $n^2$. Mỗi AO chứa tối đa 2e. Tổng số e tối đa của lớp n là $2n^2$. Ví dụ lớp 3 (n=3) chứa tối đa $2 \times 3^2 = 18$ e."},

    # Nhóm 14, 15: Cấu hình electron (Nguyên lí vững bền, Quy tắc Hund)
    {"id": "mc-c1-037", "chapter": "c1", "lesson": "b4", "level": "nb", "dang": "Nguyên lí vững bền",
     "question": "Theo nguyên lí vững bền, ở trạng thái cơ bản, các electron trong nguyên tử được phân bố vào các orbital theo trật tự nào?",
     "choices": ["Theo chiều tăng dần của mức năng lượng (từ thấp đến cao)", "Theo chiều giảm dần của mức năng lượng", "Từ lớp ngoài cùng vào lớp trong", "Ưu tiên phân bố đều cho mọi phân lớp"],
     "answer": 0, "explanation": "Ở trạng thái cơ bản (ổn định nhất), electron luôn chiếm các mức năng lượng thấp nhất có thể (gần hạt nhân nhất) rồi mới điền tiếp lên mức cao hơn."},
    {"id": "mc-c1-038", "chapter": "c1", "lesson": "b4", "level": "nb", "dang": "Quy tắc Klechkowski",
     "question": "Trật tự mức năng lượng của các phân lớp trong nguyên tử (quy tắc Klechkowski/Zarrus) đúng là:",
     "choices": ["1s 2s 2p 3s 3p 4s 3d 4p ...", "1s 2s 2p 3s 3p 3d 4s 4p ...", "1s 2s 3s 4s 2p 3p 4p ...", "1s 2p 3d 4f ..."],
     "answer": 0, "explanation": "Chú ý sự chèn mức năng lượng: phân lớp 4s có năng lượng thấp hơn phân lớp 3d. Do đó electron điền vào 4s trước rồi mới điền vào 3d. (1s 2s 2p 3s 3p 4s 3d 4p 5s ...)."},
    {"id": "mc-c1-039", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Quy tắc Hund",
     "question": "Quy tắc Hund quy định cách phân bố electron trong một phân lớp chưa bão hòa như thế nào?",
     "choices": ["Các electron phân bố vào các orbital sao cho số electron độc thân là tối đa và các e này có spin cùng chiều", "Phải điền cặp electron (2e) vào một orbital rồi mới sang orbital khác", "Các electron luôn ghép đôi với nhau ngay từ đầu", "Sắp xếp ngẫu nhiên không có quy luật"],
     "answer": 0, "explanation": "Để giảm tối đa lực đẩy tĩnh điện, các e sẽ đứng độc thân ở các phòng (AO) khác nhau trước, khi nào hết phòng trống mới bắt đầu ghép đôi. (Quy tắc Hund)."},
    {"id": "mc-c1-040", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Đọc cấu hình e",
     "question": "Cấu hình electron của nguyên tử Oxygen ($Z=8$) là:",
     "choices": ["$1s^2 2s^2 2p^4$", "$1s^2 2s^2 2p^6$", "$1s^2 2s^2 3s^2 3p^2$", "$1s^2 2p^6$"],
     "answer": 0, "explanation": "Tổng 8e. Lớp 1s chứa 2e, lớp 2s chứa 2e, còn lại 4e điền vào 2p. $\\Rightarrow 1s^2 2s^2 2p^4$."},

    {"id": "mc-c1-041", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Cấu hình e viết dở",
     "question": "Nguyên tử của nguyên tố X có cấu hình electron lớp ngoài cùng là $3s^2 3p^3$. Số hiệu nguyên tử (Z) của X là:",
     "choices": ["15", "13", "17", "11"],
     "answer": 0, "explanation": "Phục hồi cấu hình đầy đủ: $1s^2 2s^2 2p^6 3s^2 3p^3$. Tổng số electron $Z = 2 + 2 + 6 + 2 + 3 = 15$. (Nguyên tố Phosphorus - P)."},
    {"id": "mc-c1-042", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tính chất từ cấu hình",
     "question": "Nguyên tố có cấu hình electron $1s^2 2s^2 2p^6 3s^1$ thuộc loại nguyên tố gì?",
     "choices": ["Kim loại kiềm mạnh", "Khí hiếm", "Phi kim hoạt động mạnh", "Kim loại chuyển tiếp"],
     "answer": 0, "explanation": "Cấu hình có 1 electron lớp ngoài cùng ($3s^1$). Nguyên tố có 1, 2, 3 e lớp ngoài cùng thường là kim loại (dễ nhường e). Đây là Natri (Na) - kim loại kiềm."},
    {"id": "mc-c1-043", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đảo cấu hình d",
     "question": "Cấu hình electron nguyên tử của Sắt (Fe, Z=26) là:",
     "choices": ["$[Ar] 3d^6 4s^2$", "$[Ar] 4s^2 3d^6$", "$[Ar] 3d^8$", "$[Ar] 4s^2 4p^6$"],
     "answer": 0, "explanation": "Cấu hình chuẩn sau khi phân bố và sắp xếp lại lớp: $[Ar] 3d^6 4s^2$."},
    {"id": "mc-c1-044", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Ngoại lệ cấu hình (Bán bão hòa)",
     "question": "Nguyên tử Chromium (Cr, Z=24) có cấu hình electron ĐÚNG là:",
     "choices": ["$[Ar] 3d^5 4s^1$", "$[Ar] 3d^4 4s^2$", "$[Ar] 4s^2 3d^4$", "$[Ar] 3d^6$"],
     "answer": 0, "explanation": "Trường hợp ngoại lệ. Đúng ra là $3d^4 4s^2$, nhưng trạng thái bán bão hòa $d^5$ bền vững hơn, nên 1 electron từ 4s nhảy sang 3d. Cấu hình đúng là $[Ar] 3d^5 4s^1$."},

    # Thêm 16 câu cho đủ 60 câu (Ôn tập phân loại nguyên tố, viết cấu hình ion...)
    {"id": "mc-c1-045", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Ngoại lệ Đồng",
     "question": "Cấu hình electron ĐÚNG của nguyên tử Đồng (Cu, Z=29) là:",
     "choices": ["$[Ar] 3d^{10} 4s^1$", "$[Ar] 3d^9 4s^2$", "$[Ar] 3d^{10} 4s^2$", "$[Ar] 4s^1 3d^{10}$"],
     "answer": 0, "explanation": "Tương tự Cr, Đồng có ngoại lệ bão hòa $d^{10}$. $3d^9 4s^2$ chuyển thành $3d^{10} 4s^1$."},
    {"id": "mc-c1-046", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Cấu hình Cation",
     "question": "Ion $Ca^{2+}$ (tạo thành khi Canxi Z=20 nhường 2e) có cấu hình electron giống với nguyên tử của nguyên tố nào sau đây?",
     "choices": ["Argon (Ar, Z=18)", "Neon (Ne, Z=10)", "Krypton (Kr, Z=36)", "Potassium (K, Z=19)"],
     "answer": 0, "explanation": "Ca (Z=20): $[Ar] 4s^2$. Khi nhường 2e ở lớp vỏ ngoài cùng (4s), cấu hình còn lại là $[Ar]$, y hệt cấu hình của khí hiếm Argon (Z=18)."},
    {"id": "mc-c1-047", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Cấu hình Anion",
     "question": "Ion Cloride ($Cl^-$, Z=17) có cấu hình electron là:",
     "choices": ["$1s^2 2s^2 2p^6 3s^2 3p^6$", "$1s^2 2s^2 2p^6 3s^2 3p^5$", "$1s^2 2s^2 2p^6 3s^2 3p^4$", "$1s^2 2s^2 2p^6$"],
     "answer": 0, "explanation": "Cl (Z=17) có cấu hình: $1s^2 2s^2 2p^6 3s^2 3p^5$ (nhóm Halogen, cần 1e nữa để bền). Khi nhận thêm 1e thành $Cl^-$, cấu hình là $3s^2 3p^6$ (giống Ar)."},
    {"id": "mc-c1-048", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Cấu hình Cation kim loại chuyển tiếp",
     "question": "Cấu hình electron của ion sắt(III) $Fe^{3+}$ (Biết Fe có Z=26) là:",
     "choices": ["$[Ar] 3d^5$", "$[Ar] 3d^6 4s^2$", "$[Ar] 3d^3 4s^2$", "$[Ar] 3d^6$"],
     "answer": 0, "explanation": "Fe (Z=26): $[Ar] 3d^6 4s^2$. Khi tạo ion dương, e sẽ bị mất TỪ LỚP NGOÀI CÙNG VÀO TRONG (mất ở 4s trước, sau đó mới mất ở 3d). Mất 3e: đi 2e ở 4s và 1e ở 3d $\\Rightarrow$ Còn lại $[Ar] 3d^5$."},
    
    {"id": "mc-c1-049", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đếm e độc thân",
     "question": "Nguyên tử Nitrogen (N, Z=7) có bao nhiêu electron độc thân ở trạng thái cơ bản?",
     "choices": ["3 electron", "1 electron", "0 electron", "5 electron"],
     "answer": 0, "explanation": "Cấu hình: $1s^2 2s^2 2p^3$. Phân lớp 2p có 3 AO, chứa 3 e. Theo Hund, 3 e này phân bố vào 3 AO khác nhau $\\Rightarrow$ Có 3 electron độc thân."},
    {"id": "mc-c1-050", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đếm e lớp ngoài cùng",
     "question": "Nguyên tố Bromine (Br, Z=35) có bao nhiêu electron LỚP ngoài cùng?",
     "choices": ["7", "5", "17", "18"],
     "answer": 0, "explanation": "Cấu hình: $[Ar] 3d^{10} 4s^2 4p^5$. Lớp ngoài cùng là lớp thứ 4 (n=4). Số e ở lớp 4 là $4s (2) + 4p (5) = 7$ electron. (Là phi kim nhóm VIIA)."},
    
    {"id": "mc-c1-051", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Phân loại Nguyên tố s,p,d,f",
     "question": "Nguyên tố p là nguyên tố mà:",
     "choices": ["Electron cuối cùng (electron có mức năng lượng cao nhất) được điền vào phân lớp p", "Có phân lớp p ngoài cùng", "Có 3 electron ở lớp ngoài cùng", "Thuộc chu kì 2"],
     "answer": 0, "explanation": "Sự phân loại nguyên tố s, p, d, f dựa trên vị trí của electron phân bố cuối cùng theo thứ tự Klechkowski (năng lượng)."},
    {"id": "mc-c1-052", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Xác định loại nguyên tố",
     "question": "Nguyên tố có cấu hình electron $[Ar] 3d^5 4s^1$ (Cr) là nguyên tố gì?",
     "choices": ["Nguyên tố d (kim loại chuyển tiếp)", "Nguyên tố s", "Nguyên tố p", "Khí hiếm"],
     "answer": 0, "explanation": "Thứ tự điền năng lượng: 4s trước, 3d sau. E cuối cùng rơi vào phân lớp 3d (bất chấp sự sắp xếp lại). Do đó nó là nguyên tố khối d."},
    
    {"id": "mc-c1-053", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Kim loại, phi kim",
     "question": "Các nguyên tử có 5, 6, 7 electron ở lớp ngoài cùng thường là:",
     "choices": ["Các nguyên tố Phi kim", "Các nguyên tố Kim loại", "Các Khí hiếm", "Kim loại kiềm thổ"],
     "answer": 0, "explanation": "Nguyên tử có 1,2,3 e ngoài cùng: kim loại. Có 5,6,7 e ngoài cùng: phi kim (dễ nhận thêm e). Có 8 e ngoài cùng: khí hiếm (bền vững). Có 4 e: có thể phi kim (C, Si) hoặc kim loại (Sn, Pb)."},
    {"id": "mc-c1-054", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Bài toán xác định kim loại/phi kim",
     "question": "Nguyên tố X có tổng số electron trên các phân lớp s là 6, và tổng số electron trên phân lớp p là 9. Phát biểu nào về X là ĐÚNG?",
     "choices": ["X là nguyên tố phi kim (Phosphorus)", "X là kim loại kiềm", "X là khí hiếm", "X là kim loại chuyển tiếp"],
     "answer": 0, "explanation": "Các phân lớp s: $1s^2, 2s^2, 3s^2$ (đủ 6e). Các phân lớp p: $2p^6, 3p^3$ (đủ 9e). Cấu hình: $1s^2 2s^2 2p^6 3s^2 3p^3$. Lớp ngoài cùng (lớp 3) có $2+3=5$ e $\\Rightarrow$ Phi kim (Phosphorus Z=15)."},

    {"id": "mc-c1-055", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Phát hiện cấu hình sai",
     "question": "Cấu hình electron nào sau đây được viết SAI nguyên lí/quy tắc?",
     "choices": ["$1s^2 2s^2 2p^7$", "$1s^2 2s^2 2p^6 3s^1$", "$1s^2 2s^2 2p^5$", "$1s^2$"],
     "answer": 0, "explanation": "Phân lớp p chỉ có tối đa 3 AO, chứa được tối đa 6 electron ($p^6$). Viết $2p^7$ là sai nguyên lí Pauli."},
    {"id": "mc-c1-056", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Đồ thị ion hóa",
     "question": "Dựa vào cấu hình electron, tại sao khí hiếm (như Neon $1s^2 2s^2 2p^6$) lại rất khó tham gia phản ứng hóa học?",
     "choices": ["Vì lớp vỏ electron ngoài cùng của nó đã bão hòa (chứa 8e) và rất bền vững", "Vì hạt nhân của nó lực hút rất yếu", "Vì khối lượng nguyên tử rất lớn", "Vì nó không có phân lớp d"],
     "answer": 0, "explanation": "Khí hiếm có octet (8e ngoài cùng) là cấu hình lý tưởng mà mọi nguyên tử đều muốn đạt tới khi phản ứng. Vì nó đã có rồi nên nó \"trơ\" (không cần nhường/nhận e nữa)."},
    
    {"id": "mc-c1-057", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Đồng vị phóng xạ",
     "question": "Đồng vị $^{14}_6C$ được ứng dụng nổi tiếng nhất trong lĩnh vực nào?",
     "choices": ["Xác định tuổi của các cổ vật, di tích khảo cổ có nguồn gốc hữu cơ (phương pháp định tuổi Carbon-14)", "Làm nhiên liệu cho lò phản ứng hạt nhân", "Chữa bệnh ung thư", "Làm chất phát quang trong bóng đèn"],
     "answer": 0, "explanation": "$^{14}C$ là đồng vị phóng xạ có chu kì bán rã khoảng 5730 năm, luôn được hấp thụ bởi sinh vật sống. Khi chết, tỉ lệ $^{14}C$ giảm dần. Đo lượng còn lại giúp xác định tuổi hóa thạch cổ vật."},
    {"id": "mc-c1-058", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Mật độ hạt nhân",
     "question": "Vì sao các nhà khoa học lại kết luận 'Hạt nhân nguyên tử có mật độ (khối lượng riêng) cực kì khổng lồ'?",
     "choices": ["Vì hạt nhân chứa hơn 99,9% khối lượng nguyên tử nhưng thể tích lại chỉ bằng một phần triệu tỉ thể tích nguyên tử", "Vì nó chứa nhiều quark", "Vì proton hút neutron bằng lực hấp dẫn khổng lồ", "Vì nó nằm ở trung tâm vũ trụ"],
     "answer": 0, "explanation": "Khối lượng dồn hết vào 1 cục hạt nhân, mà kích thước hạt nhân lại nhỏ hơn vỏ nguyên tử hàng vạn lần. Thể tích $V \\sim R^3$, nên $V$ của vỏ gấp $10^{12} - 10^{15}$ lần $V$ hạt nhân. Dẫn đến mật độ khối hạt nhân lên tới hàng triệu tấn/cm³."},
    {"id": "mc-c1-059", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Nhận biết qua cấu hình",
     "question": "Nguyên tố M có số hiệu Z=26. Ion $M^{2+}$ có cấu hình electron lớp ngoài cùng là:",
     "choices": ["$3s^2 3p^6 3d^6$", "$3s^2 3p^6 3d^4 4s^2$", "$3s^2 3p^6 3d^5$", "$3s^2 3p^6$"],
     "answer": 0, "explanation": "M (Fe, Z=26): $[Ar] 3d^6 4s^2$. Khi mất 2e tạo $Fe^{2+}$, mất đi 2 electron ở $4s$. Cấu hình lớp ngoài cùng (lớp 3) là $3s^2 3p^6 3d^6$."},
    {"id": "mc-c1-060", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Tổng hợp bài tập cấu tạo",
     "question": "Tổng số hạt trong nguyên tử nguyên tố halogen X là 28. Cấu hình electron của nguyên tử X là:",
     "choices": ["$1s^2 2s^2 2p^5$ (Fluorine)", "$1s^2 2s^2 2p^6 3s^2 3p^5$ (Chlorine)", "$1s^2 2s^2 2p^4$ (Oxygen)", "$1s^2 2s^2 2p^6$ (Neon)"],
     "answer": 0, "explanation": "Halogen $\\Rightarrow$ Nhóm VIIA. X có $2Z + N = 28$. Ta có điều kiện đồng vị bền: $1 \le N/Z \le 1.5$. Suy ra $3Z \le 28 \le 3.5Z \Rightarrow 8 \le Z \le 9.3$. Vì là halogen nên Z phải ra $9$ (Fluorine - F có $Z=9, N=10$). Cấu hình: $1s^2 2s^2 2p^5$."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C1 Part 1 written successfully.")
