import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 1: TỔNG HỢP VÀ PHÂN TÍCH LỰC ---
    # Nhóm 1: Lí thuyết tổng hợp lực
    {"id": "mc-c2-001", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Tổng hợp lực",
     "question": "Tổng hợp lực là gì?",
     "choices": ["Thay thế các lực tác dụng đồng thời vào cùng một vật bằng một lực có tác dụng giống hệt các lực ấy", "Thay thế một lực bằng hai hay nhiều lực có tác dụng giống hệt", "Thay thế lực tác dụng lên vật này bằng lực tác dụng lên vật khác", "Triệt tiêu các lực tác dụng lên vật"],
     "answer": 0, "explanation": "Theo định nghĩa, tổng hợp lực là thay thế nhiều lực đồng thời bằng một lực duy nhất (hợp lực) có tác dụng tương đương."},
    {"id": "mc-c2-002", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Tổng hợp lực",
     "question": "Độ lớn của hợp lực $\\vec{F}$ của hai lực đồng quy $\\vec{F}_1$ và $\\vec{F}_2$ hợp với nhau góc $\\alpha$ được tính bằng công thức:",
     "choices": ["$F^2 = F_1^2 + F_2^2 + 2F_1F_2\\cos\\alpha$", "$F = F_1 + F_2$", "$F^2 = F_1^2 + F_2^2 - 2F_1F_2\\cos\\alpha$", "$F = \\sqrt{F_1^2 + F_2^2}$"],
     "answer": 0, "explanation": "Áp dụng định lí hàm cosin cho hình bình hành: $F = \\sqrt{F_1^2 + F_2^2 + 2F_1F_2\\cos\\alpha}$."},
    {"id": "mc-c2-003", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Tổng hợp lực",
     "question": "Giới hạn độ lớn của hợp lực $\\vec{F}$ của hai lực $\\vec{F}_1$ và $\\vec{F}_2$ là:",
     "choices": ["$|F_1 - F_2| \\le F \\le F_1 + F_2$", "$F_1 - F_2 < F < F_1 + F_2$", "$0 \\le F \\le F_1 + F_2$", "$F = F_1 + F_2$"],
     "answer": 0, "explanation": "Hợp lực nhỏ nhất khi 2 lực ngược chiều ($|F_1-F_2|$) và lớn nhất khi 2 lực cùng chiều ($F_1+F_2$)."},
    {"id": "mc-c2-004", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Tổng hợp lực",
     "question": "Cho hai lực đồng quy có độ lớn $F_1 = 6\\text{N}$ và $F_2 = 8\\text{N}$. Độ lớn của hợp lực KHÔNG THỂ nhận giá trị nào sau đây?",
     "choices": ["1\\text{ N}", "2\\text{ N}", "10\\text{ N}", "14\\text{ N}"],
     "answer": 0, "explanation": "Điều kiện hợp lực: $|8 - 6| \\le F \\le 8 + 6 \\Rightarrow 2 \\le F \\le 14$. Do đó $F = 1\\text{N}$ là không thể xảy ra."},

    # Nhóm 2: Bài toán tổng hợp lực
    {"id": "mc-c2-005", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Bài toán tổng hợp",
     "question": "Hai lực đồng quy có độ lớn $3\\text{N}$ và $4\\text{N}$ tác dụng vuông góc với nhau. Độ lớn của hợp lực là:",
     "choices": ["5\\text{ N}", "7\\text{ N}", "1\\text{ N}", "25\\text{ N}"],
     "answer": 0, "explanation": "Khi vuông góc, $\\alpha = 90^\\circ \\Rightarrow F = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5\\text{ N}."},
    {"id": "mc-c2-006", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Bài toán tổng hợp",
     "question": "Hai lực đồng quy $F_1 = 10\\text{N}$, $F_2 = 10\\text{N}$ hợp với nhau một góc $120^\\circ$. Độ lớn của hợp lực là:",
     "choices": ["10\\text{ N}", "0\\text{ N}", "20\\text{ N}", "$10\\sqrt{3}\\text{ N}$"],
     "answer": 0, "explanation": "$F^2 = 10^2 + 10^2 + 2 \\cdot 10 \\cdot 10 \\cdot \\cos(120^\\circ) = 100 + 100 - 100 = 100 \\Rightarrow F = 10\\text{ N}$. (Mẹo: Hai lực bằng nhau hợp góc 120 độ thì hợp lực bằng chính nó)."},
    {"id": "mc-c2-007", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Phân tích lực",
     "question": "Một vật nặng nằm trên mặt phẳng nghiêng góc $\\alpha$ so với phương ngang. Trọng lực $\\vec{P}$ được phân tích thành 2 thành phần: $\\vec{P}_t$ song song mặt nghiêng và $\\vec{P}_n$ vuông góc mặt nghiêng. Biểu thức nào đúng?",
     "choices": ["$P_t = P\\sin\\alpha$; $P_n = P\\cos\\alpha$", "$P_t = P\\cos\\alpha$; $P_n = P\\sin\\alpha$", "$P_t = P\\tan\\alpha$; $P_n = P\\cos\\alpha$", "$P_t = P$; $P_n = 0$"],
     "answer": 0, "explanation": "Thành phần kéo vật trượt xuống dọc mặt nghiêng là $P_t = P\\sin\\alpha$. Thành phần ép lên mặt phẳng là $P_n = P\\cos\\alpha$."},
    {"id": "mc-c2-008", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Phân tích lực",
     "question": "Khi kéo một vật bằng một sợi dây hợp với phương ngang góc $30^\\circ$, lực căng dây $T = 20\\text{N}$. Lực có tác dụng nhấc vật lên theo phương thẳng đứng có độ lớn là:",
     "choices": ["10\\text{ N}", "$10\\sqrt{3}\\text{ N}$", "20\\text{ N}", "0\\text{ N}"],
     "answer": 0, "explanation": "Thành phần hướng lên $T_y = T\\sin\\alpha = 20\\sin(30^\\circ) = 20 \\cdot 0.5 = 10\\text{ N}."},

    # Nhóm 3: Cân bằng lực
    {"id": "mc-c2-009", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Cân bằng lực",
     "question": "Hai lực cân bằng là hai lực có đặc điểm:",
     "choices": ["Cùng điểm đặt, cùng phương, ngược chiều, cùng độ lớn", "Cùng phương, ngược chiều, cùng độ lớn", "Cùng điểm đặt, cùng phương, cùng chiều, cùng độ lớn", "Cùng điểm đặt, vuông góc với nhau, cùng độ lớn"],
     "answer": 0, "explanation": "Định nghĩa chuẩn xác: Hai lực cân bằng phải tác dụng lên CÙNG một vật (cùng điểm đặt), cùng phương, ngược chiều và có độ lớn bằng nhau."},
    {"id": "mc-c2-010", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Cân bằng lực",
     "question": "Một chiếc đèn treo đứng yên dưới trần nhà bằng một sợi dây. Những lực nào tác dụng lên đèn và chúng có quan hệ gì?",
     "choices": ["Trọng lực và lực căng dây; chúng là hai lực cân bằng", "Trọng lực và phản lực trần nhà; chúng là hai lực cân bằng", "Trọng lực và lực căng dây; chúng là lực và phản lực", "Chỉ có trọng lực tác dụng lên đèn"],
     "answer": 0, "explanation": "Đèn chịu tác dụng của trọng lực hướng xuống và lực căng dây hướng lên. Vì đèn đứng yên, hai lực này cân bằng nhau."},
    {"id": "mc-c2-011", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Cân bằng ba lực",
     "question": "Một vật chịu tác dụng đồng thời của ba lực $\\vec{F}_1, \\vec{F}_2, \\vec{F}_3$ và đứng yên. Nhận xét nào sau đây ĐÚNG?",
     "choices": ["Hợp lực của $\\vec{F}_1$ và $\\vec{F}_2$ cân bằng với $\\vec{F}_3$", "Ba lực phải đồng phẳng và từng đôi một vuông góc", "Độ lớn $F_1 + F_2$ phải bằng $F_3$", "Không thể có trường hợp ba lực cùng cân bằng"],
     "answer": 0, "explanation": "Điều kiện cân bằng của hệ lực đồng quy là $\\vec{F}_1 + \\vec{F}_2 + \\vec{F}_3 = 0 \\Rightarrow \\vec{F}_1 + \\vec{F}_2 = -\\vec{F}_3$ (hợp của 2 lực cân bằng với lực thứ 3)."},
    {"id": "mc-c2-012", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Cân bằng ba lực",
     "question": "Ba lực đồng phẳng, đồng quy $10\\text{N}, 10\\text{N}, 10\\text{N}$ tác dụng lên một vật. Để vật cân bằng thì góc hợp bởi bất kì 2 lực nào cũng phải bằng:",
     "choices": ["120 độ", "60 độ", "90 độ", "180 độ"],
     "answer": 0, "explanation": "Hệ 3 lực bằng nhau muốn cân bằng thì chúng phải chia đều không gian $360^\\circ$. Vậy góc giữa chúng là $360^\\circ/3 = 120^\\circ$."},

    # Nhóm 4, 5, 6: Định luật 1 Newton
    {"id": "mc-c2-013", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 1 Newton",
     "question": "Nội dung định luật 1 Newton là gì?",
     "choices": ["Nếu một vật không chịu tác dụng của lực nào hoặc chịu các lực có hợp lực bằng 0 thì vật đứng yên sẽ tiếp tục đứng yên, vật đang chuyển động sẽ tiếp tục chuyển động thẳng đều", "Mọi vật đều có xu hướng bảo toàn vận tốc của mình", "Lực là nguyên nhân làm biến đổi chuyển động của vật", "Gia tốc của một vật tỉ lệ thuận với lực tác dụng lên vật"],
     "answer": 0, "explanation": "Đây là phát biểu chuẩn xác của định luật 1 Newton, còn gọi là định luật quán tính."},
    {"id": "mc-c2-014", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Quán tính",
     "question": "Đại lượng nào đặc trưng cho mức độ quán tính của một vật?",
     "choices": ["Khối lượng", "Vận tốc", "Gia tốc", "Lực"],
     "answer": 0, "explanation": "Khối lượng là đại lượng đặc trưng cho mức quán tính. Khối lượng càng lớn, quán tính càng lớn (càng khó thay đổi vận tốc)."},
    {"id": "mc-c2-015", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Quán tính",
     "question": "Khi ô tô đang chạy thẳng bỗng phanh gấp, hành khách trên xe sẽ có xu hướng ngả người về phía nào?",
     "choices": ["Phía trước", "Phía sau", "Sang trái", "Sang phải"],
     "answer": 0, "explanation": "Theo quán tính, cơ thể người có xu hướng bảo toàn vận tốc cũ (đang lao về phía trước). Khi xe dừng lại đột ngột, nửa trên cơ thể vẫn lao tới nên ngả về phía trước."},
    {"id": "mc-c2-016", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Quán tính",
     "question": "Tại sao việc đóng đinh vào một tấm gỗ treo lơ lửng lại rất khó so với khi đặt nó trên mặt đất kiên cố?",
     "choices": ["Do tấm gỗ treo lơ lửng không có phản lực lớn để giữ cố định, nó dễ dàng chuyển động theo hướng búa đập do quán tính", "Do trọng lực của tấm gỗ mất đi khi treo", "Do không khí xung quanh đẩy tấm gỗ ra", "Do quán tính của đinh thay đổi khi ở trên không"],
     "answer": 0, "explanation": "Khi đập búa, đinh truyền lực đẩy vào gỗ. Nếu gỗ không được tựa vào vật có khối lượng rất lớn (như mặt đất) để tạo phản lực triệt tiêu lực búa, khối lượng nhỏ của tấm gỗ sẽ làm nó dễ dàng thu gia tốc và bay đi, đinh khó ăn sâu vào."},

    {"id": "mc-c2-017", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 1 Newton",
     "question": "Trạng thái 'cân bằng' của một vật trong cơ học mang ý nghĩa vật đang:",
     "choices": ["Đứng yên hoặc chuyển động thẳng đều", "Chỉ đứng yên", "Chuyển động với vận tốc tăng đều", "Chuyển động trên đường tròn với tốc độ không đổi"],
     "answer": 0, "explanation": "Theo Định luật 1, cân bằng ($F_{hl}=0$) tương ứng với gia tốc $a=0$, nghĩa là đứng yên hoặc chuyển động thẳng đều."},
    {"id": "mc-c2-018", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 1",
     "question": "Một tàu vũ trụ đang bay trong không gian sâu thẳm, tắt động cơ và không ở gần bất kì hành tinh nào. Nó sẽ di chuyển như thế nào?",
     "choices": ["Chuyển động thẳng đều mãi mãi", "Chậm dần rồi dừng lại hoàn toàn", "Chuyển động theo đường tròn", "Rơi xuống phía dưới"],
     "answer": 0, "explanation": "Trong không gian không có lực hấp dẫn (ở xa) và không lực cản, hợp lực bằng 0. Theo định luật 1 Newton, nó bảo toàn vận tốc: chuyển động thẳng đều mãi mãi."},
    {"id": "mc-c2-019", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 1",
     "question": "Một cuốn sách đang nằm yên trên bàn ngang. Nếu mặt bàn biến mất ngay lập tức, cuốn sách bắt đầu rơi xuống. Hiện tượng này minh chứng cho điều gì?",
     "choices": ["Ban đầu, phản lực của bàn đã triệt tiêu trọng lực, giữ hợp lực bằng 0. Bàn mất, hợp lực khác 0 nên vận tốc thay đổi", "Cuốn sách mất đi quán tính", "Không khí đẩy cuốn sách xuống", "Lực hấp dẫn chỉ tác dụng khi không có bàn"],
     "answer": 0, "explanation": "Định luật 1: Hợp lực bằng 0 thì đứng yên. Khi mặt bàn mất, phản lực mất, hợp lực chỉ còn trọng lực ($F \\ne 0$) nên sách thu gia tốc và chuyển động rơi."},
    {"id": "mc-c2-020", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Quán tính",
     "question": "Hai quả cầu A bằng gỗ và B bằng thép có cùng kích thước. Quả cầu B nặng hơn quả A nhiều. Khi dùng tay đẩy cả hai với cùng một lực, nhận xét nào ĐÚNG?",
     "choices": ["Quả thép khó bị đẩy đi hơn (gia tốc nhỏ hơn) vì có quán tính lớn hơn", "Quả gỗ khó bị đẩy đi hơn vì có quán tính nhỏ hơn", "Hai quả dễ bị đẩy như nhau vì cùng kích thước", "Không thể so sánh được"],
     "answer": 0, "explanation": "Khối lượng lớn (quả thép) thì quán tính lớn. Quán tính là xu hướng chống lại sự thay đổi vận tốc, nên quả thép khó bị đẩy nhanh (khó thay đổi vận tốc) hơn."},

    {"id": "mc-c2-021", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 1",
     "question": "Theo Aristoteles, lực là nguyên nhân DUY NHẤT duy trì chuyển động. Galilei và Newton đã sửa sai điều này bằng cách khẳng định:",
     "choices": ["Lực là nguyên nhân thay đổi vận tốc, không phải nguyên nhân duy trì chuyển động", "Lực không liên quan gì đến chuyển động", "Lực là nguyên nhân duy trì sự đứng yên", "Chỉ có trọng lực mới duy trì chuyển động"],
     "answer": 0, "explanation": "Lực làm sinh ra gia tốc (thay đổi vận tốc). Nếu không có lực, vật vẫn có thể tiếp tục chuyển động (do quán tính)."},
    {"id": "mc-c2-022", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 1",
     "question": "Một vật trượt trên mặt băng phẳng nằm ngang. Mặc dù không ai đẩy, vật trượt rất xa mới dừng. Hiện tượng này giải thích như thế nào theo Newton?",
     "choices": ["Vật trượt xa là do quán tính, nó dừng lại là do có lực ma sát cản trở", "Vật trượt xa là do có một lực bí ẩn đẩy nó về trước", "Trọng lượng làm vật trượt đi", "Băng truyền động năng liên tục cho vật"],
     "answer": 0, "explanation": "Quán tính giữ cho vật chuyển động. Lực ma sát (tuy nhỏ) đóng vai trò là lực ngoài làm thay đổi vận tốc (giảm về 0)."},
    {"id": "mc-c2-023", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Quán tính",
     "question": "Tại sao tài xế xe tải chở đầy hàng phải phanh xe sớm hơn tài xế xe hơi con khi thấy đèn đỏ từ xa, dù cả hai đi cùng tốc độ?",
     "choices": ["Vì xe tải có khối lượng lớn, quán tính lớn nên khó giảm tốc hơn (cần lực cản lớn hơn hoặc thời gian dài hơn)", "Vì xe tải dễ trượt hơn xe hơi", "Vì phanh xe tải yếu hơn phanh xe hơi", "Vì xe tải đi nhanh hơn xe hơi"],
     "answer": 0, "explanation": "Quán tính tỉ lệ với khối lượng. Khối lượng càng lớn, xu hướng bảo toàn vận tốc cũ càng mạnh, nên việc thay đổi vận tốc từ $v$ về $0$ đòi hỏi một khoảng thời gian/quãng đường phanh dài hơn."},
    {"id": "mc-c2-024", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Quán tính",
     "question": "Giật nhanh một tờ giấy đặt dưới một cốc nước đầy. Cốc nước gần như không di chuyển. Giải thích nào là chính xác nhất?",
     "choices": ["Do thời gian giật quá ngắn, lực ma sát không kịp truyền đủ xung lượng làm thay đổi vận tốc của cốc (do cốc có quán tính)", "Do tờ giấy rất trơn, không có lực ma sát nào", "Do trọng lượng cốc nước đè tờ giấy xuống", "Do cốc nước nhẹ hơn tờ giấy"],
     "answer": 0, "explanation": "Quán tính giữ cốc đứng yên. Thời gian tương tác (giật) quá nhanh $\\Rightarrow \\Delta t$ rất bé, $\\Delta v = (F_{\\text{ms}}/m)\\Delta t$ gần bằng 0."},

    # Nhóm 7, 8, 9: Định luật 2 Newton
    {"id": "mc-c2-025", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 2 Newton",
     "question": "Biểu thức của định luật 2 Newton là:",
     "choices": ["$\\vec{F} = m\\vec{a}$", "$\\vec{a} = m\\vec{F}$", "$F = \\frac{m}{a}$", "$\\vec{F}_{12} = -\\vec{F}_{21}$"],
     "answer": 0, "explanation": "Định luật 2: Gia tốc của một vật cùng hướng với lực tác dụng lên vật. Độ lớn của gia tốc tỉ lệ thuận với độ lớn của lực và tỉ lệ nghịch với khối lượng. Biểu thức: $\\vec{F} = m\\vec{a}$."},
    {"id": "mc-c2-026", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 2 Newton",
     "question": "1 Newton (1N) là lực truyền cho một vật khối lượng:",
     "choices": ["1 kg một gia tốc 1 m/s²", "1 kg một vận tốc 1 m/s", "1 g một gia tốc 1 cm/s²", "1 kg di chuyển được quãng đường 1 m"],
     "answer": 0, "explanation": "Từ $F = ma$, nếu $m=1\\text{kg}$ và $a=1\\text{m/s}^2$ thì $F = 1\\text{ N}$."},
    {"id": "mc-c2-027", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 2",
     "question": "Dưới tác dụng của một lực 20N, một vật thu được gia tốc 4 m/s². Khối lượng của vật là:",
     "choices": ["5 kg", "80 kg", "0,2 kg", "24 kg"],
     "answer": 0, "explanation": "$m = F / a = 20 / 4 = 5\\text{ kg}$."},
    {"id": "mc-c2-028", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 2",
     "question": "Một ô tô có khối lượng 1 tấn (1000 kg) đang chuyển động với vận tốc 72 km/h thì hãm phanh. Ô tô dừng lại sau 5s. Lực hãm (trung bình) tác dụng lên xe có độ lớn là:",
     "choices": ["4000 N", "14400 N", "2000 N", "5000 N"],
     "answer": 0, "explanation": "Đổi $72\\text{ km/h} = 20\\text{ m/s}$. Gia tốc $a = (0 - 20) / 5 = -4\\text{ m/s}^2$. Độ lớn lực hãm $F = |m \\cdot a| = 1000 \\cdot |-4| = 4000\\text{ N}$."},

    {"id": "mc-c2-029", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 2",
     "question": "Nếu tăng lực tác dụng lên một vật lên gấp đôi và đồng thời giảm khối lượng của vật đi một nửa, thì gia tốc của vật sẽ:",
     "choices": ["Tăng gấp 4 lần", "Tăng gấp đôi", "Không đổi", "Giảm đi một nửa"],
     "answer": 0, "explanation": "$a = F / m$. $F' = 2F$, $m' = m/2 \\Rightarrow a' = (2F) / (m/2) = 4(F/m) = 4a$."},
    {"id": "mc-c2-030", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 2",
     "question": "Một vật 2kg trượt trên sàn ngang, chịu tác dụng của lực kéo 10N và lực ma sát 4N (hai lực này ngược chiều). Gia tốc của vật là:",
     "choices": ["3 m/s²", "7 m/s²", "5 m/s²", "2 m/s²"],
     "answer": 0, "explanation": "Hợp lực $F_{hl} = F_k - F_{ms} = 10 - 4 = 6\\text{ N}$. Gia tốc $a = F_{hl} / m = 6 / 2 = 3\\text{ m/s}^2$."},
    {"id": "mc-c2-031", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 2",
     "question": "Cùng một lực F tác dụng lên vật khối lượng $m_1$ thì nó thu gia tốc $a_1=2\\text{m/s}^2$. Nếu tác dụng lên vật $m_2$ thì thu gia tốc $a_2=3\\text{m/s}^2$. Tác dụng lực F lên vật $m = m_1 + m_2$ thì gia tốc thu được là:",
     "choices": ["1,2 m/s²", "5 m/s²", "2,5 m/s²", "1 m/s²"],
     "answer": 0, "explanation": "$m_1 = F/2$, $m_2 = F/3$. $m = m_1 + m_2 = F/2 + F/3 = 5F/6$. Gia tốc mới $a = F/m = F / (5F/6) = 6/5 = 1,2\\text{ m/s}^2$."},
    {"id": "mc-c2-032", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 2",
     "question": "Một vật đang chuyển động thẳng đều trên mặt phẳng ngang. Nếu bỗng nhiên mất đi lực đẩy (chỉ còn lực ma sát), vật sẽ chuyển động như thế nào?",
     "choices": ["Chậm dần đều với gia tốc $a = -F_{ms}/m$", "Dừng lại ngay lập tức", "Chuyển động thẳng đều mãi mãi", "Nhanh dần rồi dừng lại"],
     "answer": 0, "explanation": "Lực đẩy bằng 0, hợp lực là $-F_{ms}$. Theo đl 2 Newton, vật thu gia tốc $a = -F_{ms}/m$ ngược chiều chuyển động, nên nó trượt chậm dần đều rồi dừng lại."},

    {"id": "mc-c2-033", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Tính chất của Lực",
     "question": "Đại lượng nào sau đây là nguyên nhân làm thay đổi vận tốc của một vật?",
     "choices": ["Lực", "Khối lượng", "Quán tính", "Vận tốc ban đầu"],
     "answer": 0, "explanation": "Định luật 2 Newton chỉ ra Lực là nguyên nhân sinh ra gia tốc (thay đổi vận tốc)."},
    {"id": "mc-c2-034", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 2",
     "question": "Phát biểu nào ĐÚNG khi nói về hướng của vectơ gia tốc?",
     "choices": ["Luôn cùng hướng với vectơ hợp lực tác dụng lên vật", "Luôn cùng hướng với vectơ vận tốc", "Luôn ngược hướng với vectơ vận tốc", "Vuông góc với hướng của lực"],
     "answer": 0, "explanation": "Từ $\\vec{a} = \\vec{F}_{hl} / m$ (với m > 0), vectơ gia tốc luôn cùng hướng với vectơ hợp lực tác dụng lên vật."},
    {"id": "mc-c2-035", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 2 - Đồ thị",
     "question": "Cho đồ thị độ lớn gia tốc $a$ phụ thuộc vào độ lớn lực $F$ tác dụng vào một vật. Đồ thị này có dạng:",
     "choices": ["Một đường thẳng đi qua gốc tọa độ", "Một đường cong parabol", "Một đường thẳng song song với trục tung", "Một đường thẳng song song với trục hoành"],
     "answer": 0, "explanation": "$a = (1/m) \\cdot F$. Đây là hàm số bậc nhất $y = kx$ (với $k = 1/m = \\text{const}$). Đồ thị là đường thẳng qua gốc tọa độ."},
    {"id": "mc-c2-036", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 2",
     "question": "Một người đẩy một chiếc hộp khối lượng $M$ trên mặt sàn ngang không ma sát. Hộp thứ hai có khối lượng $2M$ nằm ngay phía trước hộp thứ nhất, bị hộp thứ nhất đẩy đi cùng. Lực tiếp xúc giữa hai hộp là:",
     "choices": ["$\\frac{2}{3}F$", "$\\frac{1}{3}F$", "$F$", "$\\frac{1}{2}F$"],
     "answer": 0, "explanation": "Cả hệ $3M$ có gia tốc $a = F / 3M$. Hộp thứ hai ($2M$) thu gia tốc $a$ do lực tiếp xúc $N$ từ hộp 1. Vậy $N = (2M) \\cdot a = 2M \\cdot (F/3M) = \\frac{2}{3}F$."},

    # Nhóm 10, 11, 12: Định luật 3 Newton
    {"id": "mc-c2-037", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Định luật 3 Newton",
     "question": "Định luật 3 Newton khẳng định điều gì?",
     "choices": ["Trong mọi trường hợp, khi vật A tác dụng lên vật B một lực, vật B cũng tác dụng lại vật A một lực. Hai lực này cùng phương, ngược chiều, cùng độ lớn.", "Gia tốc tỉ lệ thuận với lực tác dụng", "Mọi vật có xu hướng bảo toàn vận tốc", "Lực và phản lực luôn triệt tiêu nhau"],
     "answer": 0, "explanation": "Định luật 3 (Định luật tác dụng - phản tác dụng): $\\vec{F}_{AB} = -\\vec{F}_{BA}$."},
    {"id": "mc-c2-038", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Lực và Phản lực",
     "question": "Lực và phản lực trong Định luật 3 Newton CÓ đặc điểm nào sau đây?",
     "choices": ["Cùng độ lớn, ngược chiều và đặt lên hai vật khác nhau", "Cùng độ lớn, ngược chiều và tác dụng lên cùng một vật", "Cân bằng nhau và làm vật đứng yên", "Xuất hiện không cùng lúc"],
     "answer": 0, "explanation": "Vì đặt lên 2 vật khác nhau nên chúng KHÔNG phải là 2 lực cân bằng (dù ngược chiều, cùng độ lớn). Chúng xuất hiện và mất đi đồng thời."},
    {"id": "mc-c2-039", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Lực và Phản lực",
     "question": "Khi một người bơi vung tay đạp nước về phía sau, lực nào làm cho người đó tiến về phía trước?",
     "choices": ["Phản lực của nước đẩy tay người về phía trước", "Lực tay người đẩy nước", "Trọng lực của cơ thể giảm đi", "Lực cản của nước biến mất"],
     "answer": 0, "explanation": "Người đẩy nước (Tác dụng). Nước đẩy lại người (Phản tác dụng). Chính lực phản tác dụng của nước đã làm người tiến tới."},
    {"id": "mc-c2-040", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 3",
     "question": "Một con muỗi đập vào kính chắn gió của một ô tô đang chạy nhanh. Lực ô tô tác dụng lên con muỗi là $F_1$, lực con muỗi tác dụng lên ô tô là $F_2$. Kết luận nào ĐÚNG?",
     "choices": ["$|F_1| = |F_2|$", "$|F_1| \\gg |F_2|$", "$|F_1| \\ll |F_2|$", "Không có lực tác dụng từ muỗi lên ô tô"],
     "answer": 0, "explanation": "Theo đl 3 Newton, lực tương tác luôn bằng nhau về độ lớn. Dù ô tô rất nặng, lực nó tác dụng lên muỗi hoàn toàn bằng lực muỗi tác dụng lên ô tô. Tuy nhiên gia tốc $a = F/m$ của muỗi rất lớn (do khối lượng nhỏ) nên nó nát vụn, còn ô tô gia tốc gần như 0."},

    {"id": "mc-c2-041", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 3",
     "question": "Một xe tải kéo một xe con bằng một dây cáp. Nếu xe tải tăng tốc, lực mà xe tải kéo dây cáp so với lực dây cáp kéo xe tải sẽ:",
     "choices": ["Luôn bằng nhau về độ lớn", "Xe tải kéo mạnh hơn dây cáp kéo xe tải", "Dây cáp kéo mạnh hơn xe tải kéo", "Chỉ bằng nhau khi chuyển động đều"],
     "answer": 0, "explanation": "Định luật 3 luôn đúng trong mọi hoàn cảnh (đứng yên, đi đều, tăng tốc). Lực tác dụng bằng phản lực ở mọi thời điểm."},
    {"id": "mc-c2-042", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 3",
     "question": "Tại sao tên lửa có thể bay được trong không gian vũ trụ (nơi không có không khí để lực đẩy tác dụng vào)?",
     "choices": ["Tên lửa phụt khí ra phía sau, dòng khí đó tác dụng phản lực đẩy tên lửa về phía trước", "Tên lửa dựa vào lực hút của các hành tinh", "Quán tính tự đẩy tên lửa đi", "Nhiệt lượng tỏa ra làm tên lửa bay"],
     "answer": 0, "explanation": "Tên lửa đẩy khối lượng khí nóng về sau (Lực tác dụng), lượng khí này tác dụng một lực ngược lại lên thân tên lửa (Phản lực), làm nó tiến tới."},
    {"id": "mc-c2-043", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 3",
     "question": "Vận động viên cử tạ đang giữ tạ nặng 1000N đứng yên. Lực người đẩy tạ lên và trọng lượng của tạ có phải là cặp Lực - Phản lực theo Định luật 3 không?",
     "choices": ["Không, đây là hai lực cân bằng tác dụng lên cùng 1 vật (quả tạ)", "Có, vì chúng bằng nhau và ngược chiều", "Có, vì người tác dụng lên tạ và Trái Đất hút tạ", "Không, vì tạ đẩy người xuống mạnh hơn"],
     "answer": 0, "explanation": "Lực tay đẩy tạ và Trọng lượng tạ là 2 lực cùng tác dụng lên quả tạ $\\Rightarrow$ Hai lực CÂN BẰNG. Cặp lực-phản lực của lực tay đẩy tạ phải là lực tạ đè lên tay cơ."},
    {"id": "mc-c2-044", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 3",
     "question": "Một quả táo rơi từ trên cây xuống đất. Lực hấp dẫn của Trái Đất kéo quả táo xuống là F1. Lực hấp dẫn của quả táo kéo Trái Đất lên là F2. Nhận xét ĐÚNG:",
     "choices": ["Độ lớn $F_1 = F_2$, nhưng gia tốc Trái Đất thu được vô cùng nhỏ nên ta không thấy nó di chuyển", "$F_1 > F_2$ vì Trái Đất lớn hơn", "$F_2 = 0$ vì táo quá nhẹ", "Đây không phải là lực và phản lực"],
     "answer": 0, "explanation": "Lực hấp dẫn có tính chất tương hỗ. $F_1 = F_2$. Nhưng $m_{\\text{TĐ}}$ quá lớn nên gia tốc $a_{\\text{TĐ}} = F / m_{\\text{TĐ}}$ gần như bằng 0."},

    {"id": "mc-c2-045", "chapter": "c2", "lesson": "b11", "level": "nb", "dang": "Lực và Phản lực",
     "question": "Sự khác biệt quan trọng nhất giữa hai lực cân bằng và cặp lực - phản lực là:",
     "choices": ["Điểm đặt: Lực cân bằng tác dụng vào 1 vật, lực-phản lực tác dụng vào 2 vật", "Độ lớn: Lực cân bằng bằng nhau, lực-phản lực có thể khác nhau", "Chiều: Lực cân bằng ngược chiều, lực-phản lực cùng chiều", "Phương: Lực cân bằng cùng phương, lực-phản lực vuông góc"],
     "answer": 0, "explanation": "Đặc trưng lớn nhất phân biệt chúng là 'điểm đặt'. Vì lực-phản lực đặt ở 2 vật khác nhau nên không bao giờ triệt tiêu lẫn nhau."},
    {"id": "mc-c2-046", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Định luật 3",
     "question": "Một khẩu súng khối lượng M bắn ra một viên đạn khối lượng m với vận tốc v. Khẩu súng sẽ giật lùi với vận tốc V. Bỏ qua các lực cản, ta có:",
     "choices": ["$V = - (m/M)v$", "$V = v$", "$V = (M/m)v$", "$V = -v$"],
     "answer": 0, "explanation": "Theo ĐL 3 Newton (hoặc bảo toàn động lượng), $F_{đ/s} = -F_{s/đ} \Rightarrow M \\cdot (V/t) = -m \\cdot (v/t) \Rightarrow V = - \\frac{m}{M}v$. Vận tốc giật lùi nhỏ hơn vì súng nặng hơn đạn."},
    {"id": "mc-c2-047", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 3",
     "question": "Tại sao một chiếc búa nhỏ đập vào hòn đá lớn thì búa bật ngược lại, còn đá không sứt mẻ; nhưng búa lớn đập thì đá vỡ?",
     "choices": ["Vì động lượng của búa (kéo theo lực tương tác F sinh ra khi $\\Delta t$ nhỏ) phụ thuộc khối lượng. Búa lớn gây lực F cực lớn vượt quá giới hạn bền của đá", "Vì lực của búa lớn không tuân theo định luật 3", "Vì búa lớn không chịu phản lực", "Vì hòn đá nhường búa lớn"],
     "answer": 0, "explanation": "Lực tương tác khi va chạm phụ thuộc $\\Delta p / \\Delta t$. Búa lớn truyền một xung lượng khổng lồ. Mặc dù đá đẩy lại búa một lực bằng đúng F đó (ĐL 3), nhưng F này đã quá lớn làm phá vỡ cấu trúc của đá."},
    {"id": "mc-c2-048", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Định luật 3",
     "question": "Khi người đi bộ trên mặt đất ngang, lực thực sự làm cho người ấy tiến về phía trước là:",
     "choices": ["Lực ma sát nghỉ do mặt đất đẩy bàn chân người về phía trước", "Lực cơ bắp chân đạp xuống đất", "Trọng lực hướng xuống", "Phản lực pháp tuyến đẩy lên"],
     "answer": 0, "explanation": "Chân đạp đất về phía SÁU (tác dụng). Đất tác dụng lực ma sát nghỉ lên chân về phía TRƯỚC (phản lực). Lực này đẩy người tiến lên."},

    # Nhóm 13, 14, 15: Trọng lực và Lực Hấp Dẫn
    {"id": "mc-c2-049", "chapter": "c2", "lesson": "b12", "level": "nb", "dang": "Trọng lực",
     "question": "Trọng lực tác dụng lên một vật là gì?",
     "choices": ["Là lực hấp dẫn của Trái Đất tác dụng lên vật, gây ra gia tốc rơi tự do", "Là lực ép của vật lên mặt sàn do vật nặng", "Là khối lượng của vật nhân với thể tích", "Là từ trường Trái Đất hút vật"],
     "answer": 0, "explanation": "Trọng lực $\\vec{P} = m\\vec{g}$ bản chất là lực hút tĩnh hấp dẫn của Trái Đất đối với vật."},
    {"id": "mc-c2-050", "chapter": "c2", "lesson": "b12", "level": "nb", "dang": "Trọng lượng và Khối lượng",
     "question": "Sự khác biệt giữa Trọng lượng và Khối lượng là gì?",
     "choices": ["Khối lượng đo lượng vật chất, không đổi; Trọng lượng là độ lớn trọng lực, thay đổi theo vị trí địa lí", "Khối lượng là vectơ, trọng lượng là vô hướng", "Khối lượng đo bằng lực kế, trọng lượng đo bằng cân", "Hai khái niệm là một, chỉ khác tên gọi"],
     "answer": 0, "explanation": "Khối lượng $m$ không đổi mọi nơi. Trọng lượng $P = mg$ thay đổi vì gia tốc $g$ thay đổi theo độ cao và vĩ độ."},
    {"id": "mc-c2-051", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Trọng lượng",
     "question": "Một phi hành gia có khối lượng 60 kg ở Trái Đất. Gia tốc trọng trường trên Mặt Trăng bằng 1/6 Trái Đất. Trọng lượng và khối lượng của người đó trên Mặt Trăng (lấy $g = 10\\text{ m/s}^2$) là:",
     "choices": ["Khối lượng 60 kg, Trọng lượng 100 N", "Khối lượng 10 kg, Trọng lượng 100 N", "Khối lượng 60 kg, Trọng lượng 600 N", "Khối lượng 10 kg, Trọng lượng 600 N"],
     "answer": 0, "explanation": "Khối lượng không đổi = 60 kg. Trọng lượng $P = mg = 60 \\cdot (10/6) = 100\\text{ N}."},
    {"id": "mc-c2-052", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Trọng lực",
     "question": "Gia tốc trọng trường g giảm khi đưa vật lên cao. Gọi $R$ là bán kính Trái Đất. Khi đưa vật lên độ cao $h = R$, trọng lượng của vật sẽ:",
     "choices": ["Giảm đi 4 lần", "Giảm đi 2 lần", "Tăng 2 lần", "Bằng 0"],
     "answer": 0, "explanation": "Công thức lực hấp dẫn: $F = G\\frac{mM}{r^2}$. Ở mặt đất $r = R$. Ở độ cao $h=R$, khoảng cách từ tâm là $r = R+R = 2R$. Lực tỉ lệ nghịch với $r^2$, nên khoảng cách tăng 2 lần, lực (trọng lượng) giảm 4 lần."},
    
    {"id": "mc-c2-053", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Trọng tâm",
     "question": "Điểm đặt của trọng lực được gọi là gì?",
     "choices": ["Trọng tâm của vật", "Tâm đối xứng", "Khối tâm", "Tâm hình học"],
     "answer": 0, "explanation": "Trọng lực tác dụng lên mọi phần tử của vật, hợp lực của chúng có điểm đặt gọi là Trọng tâm của vật (trong trường trọng lực đều, trọng tâm trùng khối tâm)."},
    {"id": "mc-c2-054", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Đo lực",
     "question": "Người ta dùng dụng cụ nào để đo trực tiếp TRỌNG LƯỢNG của một vật?",
     "choices": ["Lực kế", "Cân Roberval (cân đòn)", "Cân đĩa", "Thước kẹp"],
     "answer": 0, "explanation": "Trọng lượng là LỰC, nên đo bằng Lực kế (Lò xo dãn ra tỉ lệ thuận với lực kéo). Cân đòn dùng để so sánh khối lượng chứ không đo trực tiếp trọng lượng."},
    {"id": "mc-c2-055", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Trọng lượng biểu kiến",
     "question": "Một người đứng trên cái cân lò xo đặt trong thang máy. Khi thang máy chuyển động nhanh dần đều đi LÊN, số chỉ của cân so với khi thang máy đứng yên sẽ:",
     "choices": ["Lớn hơn", "Nhỏ hơn", "Bằng nhau", "Chỉ số bằng 0"],
     "answer": 0, "explanation": "Theo ĐL 2 Newton: $N - P = ma \\Rightarrow N = P + ma = m(g+a)$. Số chỉ của cân là áp lực lên mặt cân bằng $N$. Vì $N > P$ nên số chỉ lớn hơn (Trạng thái tăng trọng)."},
    {"id": "mc-c2-056", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Trạng thái không trọng lượng",
     "question": "Nếu thang máy rơi tự do ($a=g$), số chỉ của cân lò xo mà người đứng lên đó sẽ là:",
     "choices": ["Bằng 0 (Trạng thái không trọng lượng)", "Bằng trọng lượng thật", "Lớn gấp đôi", "Âm"],
     "answer": 0, "explanation": "Phương trình $P - N = ma = mg \\Rightarrow N = mg - mg = 0$. Không có áp lực lên sàn cân, cân chỉ 0. Đây là hiện tượng không trọng lượng (Dù trọng lực P vẫn tác dụng)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C2 Part 1 written successfully.")
