import json

with open('data/ly10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- BÀI 13: LỰC MA SÁT ---
    # Nhóm 16: Lực ma sát trượt cơ bản
    {"id": "mc-c2-057", "chapter": "c2", "lesson": "b13", "level": "nb", "dang": "Ma sát trượt",
     "question": "Lực ma sát trượt xuất hiện khi nào?",
     "choices": ["Khi một vật trượt trên bề mặt của vật khác", "Khi một vật có xu hướng chuyển động nhưng chưa chuyển động", "Khi một vật lăn trên bề mặt vật khác", "Khi vật đứng yên không có lực tác dụng"],
     "answer": 0, "explanation": "Ma sát trượt sinh ra ở mặt tiếp xúc khi hai vật trượt lên nhau, có tác dụng cản trở chuyển động trượt."},
    {"id": "mc-c2-058", "chapter": "c2", "lesson": "b13", "level": "nb", "dang": "Độ lớn ma sát trượt",
     "question": "Độ lớn của lực ma sát trượt KHÔNG phụ thuộc vào yếu tố nào sau đây?",
     "choices": ["Diện tích tiếp xúc giữa hai vật", "Vật liệu của hai mặt tiếp xúc", "Tình trạng bề mặt tiếp xúc (nhẵn, nhám)", "Độ lớn của áp lực vuông góc giữa hai bề mặt"],
     "answer": 0, "explanation": "Theo thực nghiệm, lực ma sát trượt $F = \\mu N$ không phụ thuộc vào diện tích tiếp xúc, chỉ phụ thuộc vật liệu, tính chất bề mặt và áp lực $N$."},
    {"id": "mc-c2-059", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Hệ số ma sát trượt",
     "question": "Hệ số ma sát trượt $\\mu$ có đơn vị là gì?",
     "choices": ["Không có đơn vị", "Newton (N)", "m/s²", "N/m"],
     "answer": 0, "explanation": "Do $F_{ms} = \\mu N$, lực $F_{ms}$ và áp lực $N$ đều có đơn vị Newton (N). Tỉ số $\\mu = F/N$ nên nó là đại lượng không thứ nguyên, không có đơn vị."},
    {"id": "mc-c2-060", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Tính toán ma sát trượt",
     "question": "Một thùng hàng khối lượng 50 kg đang trượt thẳng đều trên mặt sàn ngang dưới tác dụng của lực đẩy nằm ngang 100 N. Hệ số ma sát trượt giữa thùng và sàn là: (Lấy $g = 10\\text{ m/s}^2$)",
     "choices": ["0,2", "0,5", "2,0", "0,02"],
     "answer": 0, "explanation": "Trượt thẳng đều $\\Rightarrow F_{\\text{đẩy}} = F_{ms} = 100\\text{ N}$. Áp lực $N = mg = 50 \\cdot 10 = 500\\text{ N}$. $\\mu = F_{ms}/N = 100/500 = 0,2$."},

    # Nhóm 17: Lực ma sát nghỉ
    {"id": "mc-c2-061", "chapter": "c2", "lesson": "b13", "level": "nb", "dang": "Ma sát nghỉ",
     "question": "Lực ma sát nghỉ xuất hiện khi nào?",
     "choices": ["Khi một vật chịu tác dụng của lực ngoại lai có xu hướng làm vật chuyển động nhưng vật vẫn đứng yên", "Khi vật bắt đầu chuyển động chậm dần", "Khi vật chuyển động nhanh dần", "Lúc vật trượt với tốc độ rất nhỏ"],
     "answer": 0, "explanation": "Ma sát nghỉ giữ cho vật đứng yên khi có ngoại lực cố gắng kéo/đẩy nó trượt."},
    {"id": "mc-c2-062", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Ma sát nghỉ",
     "question": "Đặc điểm của lực ma sát nghỉ là:",
     "choices": ["Có độ lớn bằng độ lớn của ngoại lực tác dụng song song với mặt tiếp xúc và thay đổi từ 0 đến giá trị cực đại", "Có độ lớn luôn bằng $\\mu N$", "Luôn hướng theo chiều của ngoại lực", "Không bao giờ cản trở chuyển động"],
     "answer": 0, "explanation": "Ma sát nghỉ có khả năng tự điều chỉnh độ lớn để cân bằng với ngoại lực (nếu ngoại lực chưa vượt quá giới hạn cực đại). Khi vượt quá giới hạn, nó trở thành ma sát trượt."},
    {"id": "mc-c2-063", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Vai trò ma sát nghỉ",
     "question": "Việc xe ô tô có thể tăng tốc và chạy về phía trước trên mặt đường ngang là nhờ lực nào tác dụng lên xe?",
     "choices": ["Lực ma sát nghỉ do mặt đường tác dụng lên lốp xe hướng về phía trước", "Lực ma sát trượt do mặt đường tác dụng lên lốp xe", "Lực động cơ đẩy xe", "Trọng lượng của xe"],
     "answer": 0, "explanation": "Lốp xe xoay đạp vào đường về phía SAU (tác dụng). Đường tác dụng lại lốp xe một phản lực về phía TRƯỚC (ma sát nghỉ). Chính ma sát nghỉ này đẩy xe tới."},
    {"id": "mc-c2-064", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Tính toán ma sát nghỉ/trượt",
     "question": "Một vật khối lượng 2kg nằm yên trên bàn ngang. Cho hệ số ma sát nghỉ cực đại là 0,4 và hệ số ma sát trượt là 0,3. Kéo vật bằng lực ngang F = 5N. Lực ma sát tác dụng lên vật khi đó là bao nhiêu? (g=10 m/s²)",
     "choices": ["5 N (ma sát nghỉ)", "8 N (ma sát nghỉ cực đại)", "6 N (ma sát trượt)", "3 N"],
     "answer": 0, "explanation": "Giới hạn ma sát nghỉ $F_{n\\max} = \\mu_n \\cdot N = 0,4 \\cdot (2 \\cdot 10) = 8\\text{N}$. Vì lực kéo $F = 5\\text{N} < F_{n\\max}$, vật không trượt. Do đó lực ma sát là ma sát nghỉ, có độ lớn cân bằng đúng với F kéo: $F_{ms} = 5\\text{N}$."},

    # Nhóm 18: Lực ma sát trên mặt phẳng nghiêng
    {"id": "mc-c2-065", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Ma sát trên mặt nghiêng",
     "question": "Một vật nằm yên trên mặt phẳng nghiêng góc $\\alpha$ so với mặt ngang. Biểu thức của lực ma sát nghỉ tác dụng lên vật là:",
     "choices": ["$F_{ms} = mg\\sin\\alpha$", "$F_{ms} = mg\\cos\\alpha$", "$F_{ms} = \\mu mg\\cos\\alpha$", "$F_{ms} = mg\\tan\\alpha$"],
     "answer": 0, "explanation": "Vật đứng yên nên lực ma sát nghỉ phải cân bằng với thành phần trọng lực kéo vật xuống dốc: $F_{ms} = P_t = mg\\sin\\alpha$. (Lưu ý: Không dùng công thức $\\mu N$ vì vật chưa trượt)."},
    {"id": "mc-c2-066", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Gia tốc trên dốc",
     "question": "Một vật trượt XUỐNG không vận tốc đầu trên mặt phẳng nghiêng góc $\\alpha$ có ma sát trượt hệ số $\\mu$. Gia tốc của vật là:",
     "choices": ["$a = g(\\sin\\alpha - \\mu\\cos\\alpha)$", "$a = g\\sin\\alpha$", "$a = g(\\cos\\alpha - \\mu\\sin\\alpha)$", "$a = g(\\sin\\alpha + \\mu\\cos\\alpha)$"],
     "answer": 0, "explanation": "Lực kéo xuống $P_t = mg\\sin\\alpha$. Lực cản $F_{ms} = \\mu N = \\mu mg\\cos\\alpha$. Hợp lực $F = P_t - F_{ms} = mg(\\sin\\alpha - \\mu\\cos\\alpha)$. Gia tốc $a = F/m = g(\\sin\\alpha - \\mu\\cos\\alpha)$."},
    {"id": "mc-c2-067", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Gia tốc lên dốc",
     "question": "Một vật bị đẩy trượt LÊN mặt phẳng nghiêng góc $\\alpha$ có ma sát $\\mu$. Biểu thức tính độ lớn gia tốc (làm chậm chuyển động) của vật là:",
     "choices": ["$a = g(\\sin\\alpha + \\mu\\cos\\alpha)$", "$a = g(\\sin\\alpha - \\mu\\cos\\alpha)$", "$a = g\\sin\\alpha$", "$a = g\\mu\\cos\\alpha$"],
     "answer": 0, "explanation": "Khi trượt LÊN, lực ma sát hướng XUỐNG. Thành phần trọng lực $P_t$ cũng hướng XUỐNG. Hợp lực cản trở $F = P_t + F_{ms} = mg\\sin\\alpha + \\mu mg\\cos\\alpha \\Rightarrow a = g(\\sin\\alpha + \\mu\\cos\\alpha)$."},
    {"id": "mc-c2-068", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Tính ma sát mặt nghiêng",
     "question": "Vật khối lượng m trượt đều xuống mặt phẳng nghiêng góc $45^\\circ$. Hệ số ma sát trượt giữa vật và mặt phẳng nghiêng là:",
     "choices": ["1", "0,5", "$\\sqrt{2}/2$", "Không tính được"],
     "answer": 0, "explanation": "Trượt đều nghĩa là $a=0 \\Rightarrow mg\\sin\\alpha = \\mu mg\\cos\\alpha \\Rightarrow \\mu = \\tan\\alpha = \\tan(45^\\circ) = 1$."},

    # Nhóm 19: Lực cản của chất lưu (Không khí, nước)
    {"id": "mc-c2-069", "chapter": "c2", "lesson": "b14", "level": "nb", "dang": "Lực cản",
     "question": "Lực cản của chất lưu (nước, không khí) tác dụng lên vật chuyển động trong nó có đặc điểm gì?",
     "choices": ["Luôn ngược chiều chuyển động và phụ thuộc vào vận tốc, hình dáng của vật", "Luôn cùng chiều chuyển động", "Chỉ phụ thuộc vào khối lượng vật", "Không phụ thuộc vào hình dáng vật"],
     "answer": 0, "explanation": "Lực cản sinh ra do va chạm với các phân tử chất lưu, luôn ngược chiều chuyển động. Độ lớn phụ thuộc vận tốc (càng nhanh cản càng mạnh), hình dáng (khí động học) và kích thước."},
    {"id": "mc-c2-070", "chapter": "c2", "lesson": "b14", "level": "nb", "dang": "Lực cản",
     "question": "Vận tốc cuối (vận tốc giới hạn) của một vật rơi trong chất lưu đạt được khi nào?",
     "choices": ["Khi lực cản của chất lưu có độ lớn cân bằng với trọng lượng của vật", "Khi vật sắp chạm đất", "Khi lực cản bằng 0", "Ngay lúc vừa thả vật"],
     "answer": 0, "explanation": "Khi tốc độ rơi tăng dần, lực cản tăng theo. Đến lúc $F_c = P$, hợp lực bằng 0, vật thôi gia tốc và sẽ chuyển động thẳng đều với vận tốc lớn nhất gọi là vận tốc cuối."},
    {"id": "mc-c2-071", "chapter": "c2", "lesson": "b14", "level": "th", "dang": "Lực nâng",
     "question": "Trong kĩ thuật thiết kế máy bay, cánh máy bay thường có tiết diện mặt trên cong hơn mặt dưới. Mục đích chính là gì?",
     "choices": ["Để tạo ra sự chênh lệch áp suất, sinh ra lực nâng khí động học", "Để giảm khối lượng máy bay", "Để chứa được nhiều nhiên liệu hơn", "Để chống lại lực cản không khí tốt hơn"],
     "answer": 0, "explanation": "Mặt trên cong làm dòng không khí phải lướt qua nhanh hơn, áp suất tĩnh giảm (Định luật Bernoulli). Chênh lệch áp suất (dưới đẩy lên mạnh hơn trên ép xuống) tạo ra lực nâng (Lift force)."},
    {"id": "mc-c2-072", "chapter": "c2", "lesson": "b14", "level": "vd", "dang": "Lực cản (Tính toán)",
     "question": "Một người nhảy dù (tổng khối lượng người và dù là 80 kg) đang rơi đều. Lực cản của không khí tác dụng lên người và dù lúc đó là bao nhiêu? ($g=10\\text{ m/s}^2$)",
     "choices": ["800 N", "0 N", "400 N", "100 N"],
     "answer": 0, "explanation": "Vì đang \"rơi đều\" (chuyển động thẳng đều) nên hợp lực bằng 0. Lực cản không khí phải cân bằng với trọng lượng: $F_c = P = mg = 800\\text{ N}."},

    # Nhóm 20: Lực đẩy Archimedes
    {"id": "mc-c2-073", "chapter": "c2", "lesson": "b14", "level": "nb", "dang": "Lực đẩy Archimedes",
     "question": "Công thức tính độ lớn lực đẩy Archimedes tác dụng lên một vật chìm trong chất lỏng là:",
     "choices": ["$F_A = \\rho g V$", "$F_A = m g$", "$F_A = p S$", "$F_A = V / \\rho$"],
     "answer": 0, "explanation": "$\\rho$ là khối lượng riêng của CHẤT LỎNG, $V$ là thể tích phần vật chìm trong chất lỏng, $g$ là gia tốc trọng trường."},
    {"id": "mc-c2-074", "chapter": "c2", "lesson": "b14", "level": "th", "dang": "Lực đẩy Archimedes",
     "question": "Điều kiện để một vật ĐẶC nổi trên mặt chất lỏng là gì?",
     "choices": ["Khối lượng riêng của vật nhỏ hơn khối lượng riêng của chất lỏng", "Vật phải có hình dạng như một cái bát", "Trọng lượng của vật phải bằng 0", "Khối lượng riêng của vật lớn hơn khối lượng riêng của chất lỏng"],
     "answer": 0, "explanation": "Vật đặc nổi khi lực đẩy lớn hơn trọng lượng nếu chìm hoàn toàn $\\Rightarrow \\rho_{vl} g V > \\rho_{vat} g V \\Rightarrow \\rho_{vat} < \\rho_{vl}$."},
    {"id": "mc-c2-075", "chapter": "c2", "lesson": "b14", "level": "vd", "dang": "Tính toán lực đẩy",
     "question": "Một khối sắt đặc thể tích $100\\text{ cm}^3$ được nhúng chìm hoàn toàn trong nước. Khối lượng riêng của nước là $1000\\text{ kg/m}^3, g=10\\text{ m/s}^2$. Độ lớn lực đẩy Archimedes tác dụng lên nó là:",
     "choices": ["1 N", "10 N", "0,1 N", "1000 N"],
     "answer": 0, "explanation": "$V = 100\\text{ cm}^3 = 100 \\cdot 10^{-6}\\text{ m}^3 = 10^{-4}\\text{ m}^3$. $F_A = \\rho \\cdot g \\cdot V = 1000 \\cdot 10 \\cdot 10^{-4} = 1\\text{ N}."},
    {"id": "mc-c2-076", "chapter": "c2", "lesson": "b14", "level": "vd", "dang": "Bài toán thực tế",
     "question": "Cùng một chiếc tàu thủy khi di chuyển từ sông (nước ngọt) ra biển (nước mặn, khối lượng riêng lớn hơn) thì tàu sẽ nổi cao hơn hay chìm sâu hơn?",
     "choices": ["Nổi cao hơn", "Chìm sâu hơn", "Không đổi độ chìm", "Chìm hẳn xuống"],
     "answer": 0, "explanation": "Khi tàu nổi cân bằng, $F_A = P$ (không đổi). Mà $F_A = \\rho_{nước} g V_{\\text{chìm}}$. Biển có $\\rho$ lớn hơn nước ngọt, nên để duy trì $F_A$ không đổi thì $V_{\\text{chìm}}$ phải giảm, nghĩa là tàu nổi cao hơn."},

    # Nhóm 21, 22: Động lượng và Xung lượng
    {"id": "mc-c2-077", "chapter": "c2", "lesson": "b15", "level": "nb", "dang": "Động lượng",
     "question": "Động lượng của một vật được định nghĩa là:",
     "choices": ["Tích khối lượng và vectơ vận tốc của vật", "Tích khối lượng và gia tốc của vật", "Một nửa tích khối lượng và bình phương vận tốc", "Tích lực tác dụng và thời gian"],
     "answer": 0, "explanation": "Định nghĩa $\\vec{p} = m\\vec{v}$. Là một vectơ cùng hướng với vận tốc."},
    {"id": "mc-c2-078", "chapter": "c2", "lesson": "b15", "level": "nb", "dang": "Xung lượng",
     "question": "Xung lượng của lực $\\vec{F}$ không đổi tác dụng trong thời gian $\\Delta t$ là đại lượng:",
     "choices": ["Vectơ $\\vec{F}\\Delta t$", "Vô hướng $F\\Delta t$", "Vectơ $\\vec{F}/\\Delta t$", "Vô hướng $F^2\\Delta t$"],
     "answer": 0, "explanation": "Xung lượng của lực là tích $\\vec{F}\\Delta t$, là một đại lượng vectơ cùng hướng với lực."},
    {"id": "mc-c2-079", "chapter": "c2", "lesson": "b15", "level": "th", "dang": "Mối quan hệ",
     "question": "Dạng khác của định luật 2 Newton viết qua động lượng và xung lượng là:",
     "choices": ["Độ biến thiên động lượng của vật bằng xung lượng của lực tác dụng lên nó: $\\Delta\\vec{p} = \\vec{F}\\Delta t$", "Xung lượng bằng công của lực", "Động lượng bằng động năng chia cho vận tốc", "Lực tác dụng luôn làm bảo toàn động lượng"],
     "answer": 0, "explanation": "Theo Newton: $\\vec{F} = m\\vec{a} = m \\frac{\\Delta \\vec{v}}{\\Delta t} = \\frac{\\Delta \\vec{p}}{\\Delta t} \\Rightarrow \\vec{F}\\Delta t = \\Delta\\vec{p}$."},
    {"id": "mc-c2-080", "chapter": "c2", "lesson": "b15", "level": "vd", "dang": "Tính toán xung lượng",
     "question": "Một quả bóng tennis 0.05 kg đang bay ngang với tốc độ 20 m/s thì bị đập ngược lại bằng vợt với tốc độ 30 m/s. Độ lớn độ biến thiên động lượng của bóng là:",
     "choices": ["2,5 kg.m/s", "0,5 kg.m/s", "50 kg.m/s", "1,5 kg.m/s"],
     "answer": 0, "explanation": "Chọn chiều dương là chiều bật lại. $v_2 = 30$, $v_1 = -20$. $\\Delta p = m(v_2 - v_1) = 0.05(30 - (-20)) = 0.05 \\times 50 = 2,5\\text{ kg.m/s}."},

    {"id": "mc-c2-081", "chapter": "c2", "lesson": "b15", "level": "th", "dang": "Bảo toàn động lượng",
     "question": "Định luật bảo toàn động lượng chỉ áp dụng đúng cho hệ nào sau đây?",
     "choices": ["Hệ kín (cô lập), không chịu tác dụng của ngoại lực (hoặc các ngoại lực triệt tiêu nhau)", "Mọi hệ thống có các vật va chạm", "Hệ thống chịu tác dụng của lực ma sát lớn", "Hệ thống đứng yên"],
     "answer": 0, "explanation": "Điều kiện của định luật bảo toàn động lượng là tổng các ngoại lực tác dụng lên hệ bằng 0."},
    {"id": "mc-c2-082", "chapter": "c2", "lesson": "b15", "level": "vd", "dang": "Bảo toàn động lượng (Nổ)",
     "question": "Một viên đạn pháo đang bay ngang thì nổ thành 2 mảnh có khối lượng bằng nhau. Nếu mảnh 1 bay thẳng đứng lên trên, thì mảnh 2 bắt buộc phải bay theo hướng nào?",
     "choices": ["Xiên xuống phía dưới và ra phía trước", "Thẳng đứng xuống dưới", "Tiếp tục bay ngang", "Bay giật lùi về sau"],
     "answer": 0, "explanation": "Động lượng tổng $\\vec{p}$ hướng ngang. $\\vec{p}_1$ hướng đứng lên. Để $\\vec{p}_1 + \\vec{p}_2 = \\vec{p}$, vectơ $\\vec{p}_2$ phải triệt tiêu thành phần thẳng đứng (hướng xuống) và bù lại động lượng ngang ban đầu (hướng ngang) $\\Rightarrow$ bay xiên xuống dưới, chéo ra trước."},
    {"id": "mc-c2-083", "chapter": "c2", "lesson": "b15", "level": "vd", "dang": "Va chạm mềm",
     "question": "Khối gỗ 2 kg đang nằm yên trên mặt bàn nhẵn. Một viên đạn 0,1 kg bay ngang với vận tốc 210 m/s cắm phập vào khối gỗ. Vận tốc của hệ sau va chạm là:",
     "choices": ["10 m/s", "21 m/s", "0 m/s", "10,5 m/s"],
     "answer": 0, "explanation": "Bảo toàn động lượng: $m\\cdot v + M\\cdot 0 = (m+M)V \\Rightarrow 0,1 \\cdot 210 = (2+0,1) \\cdot V \\Rightarrow 21 = 2,1V \\Rightarrow V = 10\\text{ m/s}."},
    {"id": "mc-c2-084", "chapter": "c2", "lesson": "b15", "level": "vd", "dang": "Chuyển động bằng phản lực",
     "question": "Hiện tượng súng bị giật lùi khi bắn là ứng dụng của định luật nào?",
     "choices": ["Bảo toàn động lượng", "Bảo toàn cơ năng", "Định luật 1 Newton", "Định luật vạn vật hấp dẫn"],
     "answer": 0, "explanation": "Ban đầu $p = 0$. Khi đạn bay về trước, súng giật lùi về sau để tổng động lượng vẫn bằng 0 (hoặc giải thích bằng Định luật 3 Newton)."},

    # Nhóm 23, 24: Tổng hợp lực căng dây, lực đàn hồi, ròng rọc
    {"id": "mc-c2-085", "chapter": "c2", "lesson": "b16", "level": "nb", "dang": "Lực đàn hồi",
     "question": "Phát biểu nào của định luật Hooke là đúng đối với lò xo?",
     "choices": ["Độ lớn lực đàn hồi tỉ lệ thuận với độ biến dạng của lò xo", "Lực đàn hồi luôn hướng ra xa vị trí cân bằng", "Lực đàn hồi tỉ lệ nghịch với độ giãn", "Lò xo càng dài lực đàn hồi càng nhỏ"],
     "answer": 0, "explanation": "$F = k|\\Delta l|$. Độ lớn tỉ lệ thuận với độ biến dạng. Hướng của lực đàn hồi luôn xu hướng chống lại sự biến dạng (kéo về vị trí tự nhiên)."},
    {"id": "mc-c2-086", "chapter": "c2", "lesson": "b16", "level": "th", "dang": "Lực đàn hồi",
     "question": "Lò xo có độ cứng $k=100\\text{ N/m}$. Khi lò xo bị nén $5\\text{ cm}$, lực đàn hồi có độ lớn là:",
     "choices": ["5 N", "500 N", "0,05 N", "20 N"],
     "answer": 0, "explanation": "Đổi $\\Delta l = 5\\text{cm} = 0,05\\text{m}$. $F = 100 \\cdot 0,05 = 5\\text{ N}."},
    {"id": "mc-c2-087", "chapter": "c2", "lesson": "b16", "level": "vd", "dang": "Lò xo treo thẳng đứng",
     "question": "Treo một vật nặng 0,2 kg vào lò xo thẳng đứng ($g=10\\text{ m/s}^2$). Lò xo giãn $4\\text{ cm}$. Độ cứng của lò xo là:",
     "choices": ["50 N/m", "200 N/m", "20 N/m", "5 N/m"],
     "answer": 0, "explanation": "Ở vị trí cân bằng, $F_{\\text{đh}} = P \Rightarrow k\\Delta l = mg \Rightarrow k \\cdot 0,04 = 0,2 \\cdot 10 = 2 \Rightarrow k = 2 / 0,04 = 50\\text{ N/m}."},
    {"id": "mc-c2-088", "chapter": "c2", "lesson": "b16", "level": "vd", "dang": "Ghép lò xo",
     "question": "Cắt lò xo có độ cứng $k$ thành hai phần bằng nhau. Độ cứng của mỗi nửa lò xo lúc này là:",
     "choices": ["2k", "k/2", "k", "4k"],
     "answer": 0, "explanation": "Độ cứng lò xo tỉ lệ nghịch với chiều dài tự nhiên ($k \sim 1/l_0$). Cắt đôi chiều dài $\\Rightarrow$ độ cứng tăng gấp đôi."},

    {"id": "mc-c2-089", "chapter": "c2", "lesson": "b16", "level": "nb", "dang": "Lực căng dây",
     "question": "Lực căng dây (T) có đặc điểm nào sau đây?",
     "choices": ["Điểm đặt ở hai đầu dây, phương trùng với sợi dây, chiều hướng vào giữa dây", "Phương vuông góc với sợi dây", "Chỉ xuất hiện khi dây chùng", "Luôn hướng ra xa sợi dây"],
     "answer": 0, "explanation": "Lực căng dây sinh ra khi dây bị kéo căng, có tác dụng cản trở sự kéo giãn. Vì thế lực từ dây kéo vật luôn hướng theo dọc dây và hướng vào phần giữa dây."},
    {"id": "mc-c2-090", "chapter": "c2", "lesson": "b16", "level": "th", "dang": "Lực căng dây - Ròng rọc",
     "question": "Nếu bỏ qua khối lượng của dây và ma sát ở ròng rọc, lực căng của sợi dây vắt qua ròng rọc có đặc điểm gì?",
     "choices": ["Độ lớn như nhau tại mọi điểm trên dây", "Bên nào vật nặng hơn thì lực căng bên đó lớn hơn", "Phụ thuộc vào bán kính ròng rọc", "Thay đổi liên tục dọc theo dây"],
     "answer": 0, "explanation": "Đối với dây lí tưởng (nhẹ, không giãn) vắt qua ròng rọc trơn, lực căng truyền đi nguyên vẹn trên toàn sợi dây."},
    {"id": "mc-c2-091", "chapter": "c2", "lesson": "b16", "level": "vd", "dang": "Hệ hai vật vắt ròng rọc",
     "question": "Hệ Atwood: Hai vật $m_1 = 3\\text{ kg}$ và $m_2 = 2\\text{ kg}$ treo vào 2 đầu dây vắt qua ròng rọc cố định ($g=10\\text{ m/s}^2$). Bỏ qua khối lượng dây và ròng rọc. Gia tốc của hệ là:",
     "choices": ["2 m/s²", "10 m/s²", "5 m/s²", "4 m/s²"],
     "answer": 0, "explanation": "Áp dụng định luật 2 Newton cho hệ: Lực kéo xuôi $m_1g$, kéo ngược $m_2g$. Hợp lực $F = (m_1 - m_2)g = (3-2)10 = 10\\text{N}$. Gia tốc $a = F / (m_1+m_2) = 10 / 5 = 2\\text{ m/s}^2$."},
    {"id": "mc-c2-092", "chapter": "c2", "lesson": "b16", "level": "vd", "dang": "Hệ hai vật vắt ròng rọc",
     "question": "Trong hệ thống ở câu trên ($m_1=3, m_2=2, g=10, a=2$), lực căng của sợi dây treo hai vật có độ lớn là:",
     "choices": ["24 N", "10 N", "20 N", "30 N"],
     "answer": 0, "explanation": "Xét riêng vật $m_2$ (chuyển động đi LÊN): $T - m_2g = m_2a \Rightarrow T = m_2(g+a) = 2(10+2) = 24\\text{ N}$. (Nếu xét $m_1$ đi XUỐNG: $m_1g - T = m_1a \Rightarrow T = 3(10-2) = 24\\text{ N}$)."},

    # Nhóm 25, 26, 27: Bài tập Động lực học tổng hợp (Mặt phẳng ngang, góc)
    {"id": "mc-c2-093", "chapter": "c2", "lesson": "b17", "level": "vd", "dang": "Lực kéo góc",
     "question": "Một vật khối lượng 5kg được kéo trên sàn phẳng ngang bởi một lực F = 20N hợp với phương ngang một góc $30^\\circ$. Tính gia tốc của vật nếu sàn không có ma sát. (Lấy $\\sqrt{3} \\approx 1,73$)",
     "choices": ["3,46 m/s²", "4 m/s²", "2 m/s²", "0 m/s²"],
     "answer": 0, "explanation": "Thành phần lực gây ra gia tốc là thành phần phương ngang $F_x = F\\cos\\alpha = 20\\cdot \\frac{\\sqrt{3}}{2} = 10\\sqrt{3} \\approx 17,32\\text{ N}$. Gia tốc $a = F_x / m = 17,32 / 5 = 3,464\\text{ m/s}^2$."},
    {"id": "mc-c2-094", "chapter": "c2", "lesson": "b17", "level": "vd", "dang": "Lực kéo góc có ma sát (Lừa áp lực)",
     "question": "Cũng bài toán trên (vật 5kg, kéo F=20N, góc 30 độ), nhưng sàn có ma sát $\\mu = 0,2$. ($g=10$). Biểu thức tính lực ma sát nào ĐÚNG?",
     "choices": ["$F_{ms} = \\mu(mg - F\\sin 30^\\circ)$", "$F_{ms} = \\mu mg$", "$F_{ms} = \\mu(mg + F\\sin 30^\\circ)$", "$F_{ms} = \\mu mg\\cos 30^\\circ$"],
     "answer": 0, "explanation": "Bẫy áp lực: Khi kéo xếch lên, thành phần $F_y = F\\sin 30^\\circ$ đã nâng đỡ bớt một phần trọng lượng. Áp lực vật nén xuống sàn chỉ còn $N = P - F_y = mg - F\\sin 30^\\circ$. Lực ma sát $F_{ms} = \\mu N$."},
    {"id": "mc-c2-095", "chapter": "c2", "lesson": "b17", "level": "vd", "dang": "Hai vật nối dây ngang",
     "question": "Hai vật $m_1=2\\text{kg}, m_2=3\\text{kg}$ nối với nhau bằng 1 sợi dây nằm ngang. Kéo $m_2$ bằng lực F=10N theo phương ngang. Bỏ qua ma sát. Gia tốc của hệ và lực căng dây giữa hai vật là:",
     "choices": ["$a=2\\text{ m/s}^2$, $T=4\\text{ N}$", "$a=2\\text{ m/s}^2$, $T=6\\text{ N}$", "$a=5\\text{ m/s}^2$, $T=10\\text{ N}$", "$a=3,3\\text{ m/s}^2$, $T=4\\text{ N}$"],
     "answer": 0, "explanation": "Coi như 1 hệ $m = 5\\text{kg} \Rightarrow a = 10/5 = 2\\text{ m/s}^2$. Xét riêng $m_1$ (vật bị kéo phía sau), lực duy nhất kéo nó là $T \Rightarrow T = m_1a = 2 \\cdot 2 = 4\\text{ N}$."},
    {"id": "mc-c2-096", "chapter": "c2", "lesson": "b17", "level": "vd", "dang": "Vật trên xe lăn",
     "question": "Một khối gỗ nằm yên trên một chiếc xe đẩy nằm ngang (hệ số ma sát nghỉ là 0,2). Xe đẩy tăng tốc. Gia tốc tối đa của xe để khối gỗ KHÔNG bị trượt lùi về sau là: ($g=10\\text{m/s}^2$)",
     "choices": ["2 m/s²", "0,2 m/s²", "10 m/s²", "Bất kì gia tốc nào"],
     "answer": 0, "explanation": "Khi xe tăng tốc $a$, lực quán tính $-ma$ đẩy gỗ lùi lại (hoặc lực ma sát nghỉ phải đủ lớn $ma$). $F_{ms} \le F_{n\\max} = \\mu mg \Rightarrow ma \le \\mu mg \Rightarrow a \le \\mu g = 0,2 \\cdot 10 = 2\\text{ m/s}^2$."},

    # Nhóm 28, 29, 30: Tổng hợp Momen Lực & Chuyển động quay (Chương 2 thường gộp cân bằng vật rắn)
    {"id": "mc-c2-097", "chapter": "c2", "lesson": "b18", "level": "nb", "dang": "Momen lực",
     "question": "Momen lực đối với một trục quay là đại lượng đặc trưng cho tác dụng gì của lực?",
     "choices": ["Tác dụng làm quay vật của lực", "Tác dụng làm vật chuyển động tịnh tiến", "Làm vật biến dạng", "Làm thay đổi khối lượng vật"],
     "answer": 0, "explanation": "Momen lực $M = F\\cdot d$ là đại lượng đặc trưng cho tác dụng làm quay của lực quanh một trục."},
    {"id": "mc-c2-098", "chapter": "c2", "lesson": "b18", "level": "nb", "dang": "Cánh tay đòn",
     "question": "Trong công thức tính momen lực $M = F\\cdot d$, đại lượng $d$ (cánh tay đòn) là gì?",
     "choices": ["Khoảng cách từ trục quay đến giá của lực", "Khoảng cách từ trục quay đến điểm đặt của lực", "Chiều dài của vật quay", "Hình chiếu của điểm đặt lực lên trục quay"],
     "answer": 0, "explanation": "Cánh tay đòn là khoảng cách hình học từ trục quay (tâm quay) hạ vuông góc xuống 'giá của lực' (đường thẳng chứa lực)."},
    {"id": "mc-c2-099", "chapter": "c2", "lesson": "b18", "level": "th", "dang": "Momen lực",
     "question": "Để mở một cánh cửa, ta nên đẩy ở vị trí nào để lực cần thiết là NHỎ NHẤT?",
     "choices": ["Đẩy ở mép cửa, xa bản lề nhất", "Đẩy ở vị trí chính giữa cánh cửa", "Đẩy ở vị trí sát với bản lề", "Đẩy vào chính bản lề cửa"],
     "answer": 0, "explanation": "Để có cùng Momen lực mở cửa $M$, nếu cánh tay đòn $d$ càng lớn thì lực $F = M/d$ cần dùng càng nhỏ. Nên đẩy ở xa trục quay (bản lề) nhất."},
    {"id": "mc-c2-100", "chapter": "c2", "lesson": "b18", "level": "th", "dang": "Quy tắc momen",
     "question": "Theo quy tắc momen lực, một vật có trục quay cố định sẽ nằm cân bằng khi nào?",
     "choices": ["Tổng các momen lực làm vật quay cùng chiều kim đồng hồ bằng tổng các momen lực làm vật quay ngược chiều kim đồng hồ", "Tổng các lực tác dụng lên vật bằng 0", "Lực tác dụng lên vật có giá đi qua trục quay", "Vật không chịu lực nào tác dụng"],
     "answer": 0, "explanation": "Đây là điều kiện cân bằng quay: $\\sum M_{\\text{thuận}} = \\sum M_{\\text{nghịch}}$."},

    {"id": "mc-c2-101", "chapter": "c2", "lesson": "b18", "level": "vd", "dang": "Tính toán Momen",
     "question": "Dùng một cờ lê dài 20 cm để vặn ốc. Lực tác dụng vuông góc vào đuôi cờ lê là 50 N. Momen lực sinh ra là:",
     "choices": ["10 N.m", "1000 N.m", "2,5 N.m", "250 N.m"],
     "answer": 0, "explanation": "Đổi $d = 20\\text{ cm} = 0,2\\text{ m}$. Lực vuông góc nên cánh tay đòn chính là độ dài cờ lê. $M = F\\cdot d = 50 \\cdot 0,2 = 10\\text{ N.m}."},
    {"id": "mc-c2-102", "chapter": "c2", "lesson": "b18", "level": "vd", "dang": "Quy tắc đòn bẩy",
     "question": "Một đòn bẩy AB tựa trên điểm tựa O (cách A 0,5m và cách B 1,5m). Treo vào A vật nặng 30kg. Để hệ cân bằng ngang, phải treo vào B vật nặng bao nhiêu? (Bỏ qua khối lượng đòn bẩy)",
     "choices": ["10 kg", "90 kg", "30 kg", "15 kg"],
     "answer": 0, "explanation": "Momen bên trái bằng bên phải: $P_A \\cdot OA = P_B \\cdot OB \Rightarrow m_A \\cdot OA = m_B \\cdot OB \Rightarrow 30 \\cdot 0,5 = m_B \\cdot 1,5 \Rightarrow 15 = 1,5 m_B \Rightarrow m_B = 10\\text{ kg}."},
    {"id": "mc-c2-103", "chapter": "c2", "lesson": "b18", "level": "vd", "dang": "Momen lực chéo",
     "question": "Nếu kéo đuôi cờ lê (dài 20cm) với lực 50N nhưng hướng lực hợp với thân cờ lê một góc 30 độ. Momen lực tác dụng lên ốc là:",
     "choices": ["5 N.m", "10 N.m", "8,66 N.m", "0 N.m"],
     "answer": 0, "explanation": "Cánh tay đòn $d = l\\cdot\\sin\\alpha = 0,2 \\cdot \\sin 30^\\circ = 0,2 \\cdot 0,5 = 0,1\\text{m}$. Momen $M = F\\cdot d = 50 \\cdot 0,1 = 5\\text{ N.m}."},
    {"id": "mc-c2-104", "chapter": "c2", "lesson": "b18", "level": "vd", "dang": "Cân bằng tổng quát",
     "question": "Một người gánh 2 thúng gạo $m_1=20\\text{kg}$ và $m_2=30\\text{kg}$. Đòn gánh dài 1,5m. Vai người phải đặt ở đâu để đòn gánh cân bằng nằm ngang? (Bỏ qua khối lượng đòn gánh)",
     "choices": ["Cách thúng 1 là 0,9m", "Cách thúng 1 là 0,6m", "Chính giữa đòn gánh", "Cách thúng 2 là 1m"],
     "answer": 0, "explanation": "Tỉ lệ cánh tay đòn nghịch với khối lượng: $d_1/d_2 = m_2/m_1 = 30/20 = 1.5 \Rightarrow d_1 = 1.5 d_2$. Mà $d_1 + d_2 = 1.5$. Giải ra $d_2 = 0,6\\text{m}$ và $d_1 = 0,9\\text{m}$ (Cách thúng 1 là 0,9m)."},

    # Các câu còn lại 105 - 120 dự phòng/mở rộng Động lực học
    {"id": "mc-c2-105", "chapter": "c2", "lesson": "b19", "level": "th", "dang": "Ngẫu lực",
     "question": "Ngẫu lực là hệ hai lực song song có đặc điểm:",
     "choices": ["Cùng độ lớn, ngược chiều và không cùng giá", "Cùng độ lớn, cùng chiều", "Cùng độ lớn, ngược chiều và cùng giá", "Trọng tâm trùng nhau"],
     "answer": 0, "explanation": "Ngẫu lực là hệ hai lực song song, ngược chiều, có độ lớn bằng nhau và cùng tác dụng vào 1 vật nhưng có giá khác nhau. Ngẫu lực chỉ làm vật quay."},
    {"id": "mc-c2-106", "chapter": "c2", "lesson": "b19", "level": "th", "dang": "Ngẫu lực",
     "question": "Momen của ngẫu lực tính bằng công thức nào? (với $F$ là độ lớn của một lực, $d$ là khoảng cách giữa 2 giá của lực)",
     "choices": ["$M = F \\cdot d$", "$M = 2F \\cdot d$", "$M = F \\cdot d / 2$", "$M = 0$"],
     "answer": 0, "explanation": "Momen của ngẫu lực bằng độ lớn của 1 lực nhân với cánh tay đòn (khoảng cách giữa hai giá của hai lực)."},
    {"id": "mc-c2-107", "chapter": "c2", "lesson": "b19", "level": "nb", "dang": "Trọng tâm",
     "question": "Muốn một vật rắn có mặt chân đế không bị lật đổ, thì đường thẳng đứng đi qua trọng tâm phải:",
     "choices": ["Xuyên qua mặt chân đế", "Nằm ngoài mặt chân đế", "Song song với mặt sàn", "Tiếp xúc mép chân đế"],
     "answer": 0, "explanation": "Điều kiện cân bằng bền của vật có mặt chân đế là giá của trọng lực (đường thẳng đứng qua trọng tâm) phải đi qua mặt chân đế."},
    {"id": "mc-c2-108", "chapter": "c2", "lesson": "b19", "level": "vd", "dang": "Trọng tâm",
     "question": "Vì sao các loại xe đua thường được thiết kế gầm rất thấp và lốp xe bè rộng?",
     "choices": ["Hạ thấp trọng tâm và tăng diện tích mặt chân đế để tăng mức vững vàng chống lật", "Để xe nhẹ hơn", "Giảm ma sát với đường", "Tăng lực nâng khí động học"],
     "answer": 0, "explanation": "Gầm thấp $\\Rightarrow$ trọng tâm thấp. Lốp rộng $\\Rightarrow$ mặt chân đế lớn. Cả hai giúp tăng độ vững vàng, xe không bị lật khi bẻ lái ở tốc độ cao."},

    {"id": "mc-c2-109", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Động lực học thang máy",
     "question": "Một người nặng 50kg đứng trong thang máy. Lấy $g=10$. Khi thang máy đi XUỐNG nhanh dần đều với gia tốc 2 m/s², áp lực của người đó lên sàn là:",
     "choices": ["400 N", "600 N", "500 N", "100 N"],
     "answer": 0, "explanation": "Chiều a hướng XUỐNG. $P - N = ma \Rightarrow N = P - ma = m(g-a) = 50(10-2) = 400\\text{ N}$ (Hiện tượng giảm trọng)."},
    {"id": "mc-c2-110", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Lực căng dây thang máy",
     "question": "Một buồng thang máy nặng 1 tấn (1000kg). Lực căng tối đa cáp chịu được là 15000N. Thang máy có thể được kéo đi LÊN nhanh dần đều với gia tốc tối đa là: (g=10)",
     "choices": ["5 m/s²", "15 m/s²", "10 m/s²", "2 m/s²"],
     "answer": 0, "explanation": "Đi lên NDĐ: $T - P = ma \Rightarrow T = m(g+a)$. $T_{\\max} = 15000 \Rightarrow 1000(10+a) \le 15000 \Rightarrow 10+a \le 15 \Rightarrow a \le 5\\text{ m/s}^2$."},
    {"id": "mc-c2-111", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Hệ vật dính nhau",
     "question": "Hai toa tàu $m_1$ và $m_2$ nối nhau bằng một lò xo, bị đầu máy kéo trượt trên đường ray. Lò xo ở giữa bị giãn. Lực đàn hồi của lò xo lúc này đóng vai trò:",
     "choices": ["Là lực kéo đối với toa 2 và lực cản đối với toa 1", "Là lực kéo cho cả hai toa", "Là lực cản cho cả hai toa", "Chỉ tác dụng lên đầu máy"],
     "answer": 0, "explanation": "Lò xo giãn sẽ xu hướng co lại. Nó kéo đầu sau của toa 1 lùi lại (cản trở toa 1) và kéo đầu trước của toa 2 tiến lên (kéo toa 2)."},
    {"id": "mc-c2-112", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Ném ngang & Động lượng",
     "question": "Một viên bi bay ngang vận tốc v chạm vào tường bật ngược lại với cùng vận tốc v. Độ biến thiên động lượng có phương và chiều như thế nào?",
     "choices": ["Phương ngang, vuông góc và hướng ra khỏi tường", "Bằng 0", "Dọc theo tường", "Vuông góc và hướng vào tường"],
     "answer": 0, "explanation": "$\\Delta\\vec{p} = \\vec{p}_2 - \\vec{p}_1$. $\\vec{p}_2$ hướng ra ngoài, $-\\vec{p}_1$ cũng hướng ra ngoài (do $\\vec{p}_1$ đâm vào tường). Vậy $\\Delta\\vec{p}$ hướng ra khỏi tường (đây cũng là hướng của lực tường tác dụng lên bi)."},

    {"id": "mc-c2-113", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Phân tích hệ tĩnh",
     "question": "Quả cầu nhẵn 2kg treo vào tường bằng 1 sợi dây hợp với tường góc $30^\\circ$. Tính lực căng dây. ($g=10$)",
     "choices": ["$40/\\sqrt{3}\\text{ N}$", "20 N", "10 N", "$20\\sqrt{3}\\text{ N}$"],
     "answer": 0, "explanation": "Vẽ hình: Phân tích T thành 2 thành phần dọc và ngang. Thành phần dọc $T_y = T\\cos 30^\\circ$ phải cân bằng với trọng lượng P. $T\\cos 30^\\circ = P \Rightarrow T \\cdot \\frac{\\sqrt{3}}{2} = 20 \Rightarrow T = 40/\\sqrt{3}\\text{ N}."},
    {"id": "mc-c2-114", "chapter": "c2", "lesson": "b20", "level": "vd", "dang": "Phân tích hệ tĩnh",
     "question": "Cũng quả cầu trên, tính phản lực (N) của tường đẩy ra.",
     "choices": ["$20/\\sqrt{3}\\text{ N}$", "20 N", "10 N", "$10\\sqrt{3}\\text{ N}$"],
     "answer": 0, "explanation": "Thành phần ngang của dây $T_x = T\\sin 30^\\circ$ ép quả cầu vào tường. Tường đẩy ra 1 phản lực $N = T_x = (40/\\sqrt{3}) \\cdot 0.5 = 20/\\sqrt{3}\\text{ N}."},
    {"id": "mc-c2-115", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Ma sát lăn",
     "question": "Vì sao các vòng bi (bạc đạn) trong trục quay xe đạp lại chứa các viên bi thép?",
     "choices": ["Để chuyển ma sát trượt thành ma sát lăn, giảm lực cản trở", "Để tăng thêm ma sát", "Để làm trục xe nặng hơn", "Để tạo âm thanh khi chạy"],
     "answer": 0, "explanation": "Ma sát lăn luôn nhỏ hơn ma sát trượt rất rất nhiều lần. Lắp viên bi để các bề mặt lăn lên nhau thay vì trượt lên nhau."},
    {"id": "mc-c2-116", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "So sánh 3 loại ma sát",
     "question": "Sắp xếp độ lớn của lực ma sát nghỉ CỰC ĐẠI, ma sát TRƯỢT và ma sát LĂN trên cùng một mặt phẳng ngang, cùng vật:",
     "choices": ["Ma sát nghỉ cực đại > Ma sát trượt > Ma sát lăn", "Ma sát trượt > Ma sát nghỉ cực đại > Ma sát lăn", "Ma sát lăn > Ma sát trượt > Ma sát nghỉ", "Bằng nhau"],
     "answer": 0, "explanation": "Thông thường, để bắt đầu làm một vật nhúc nhích (vượt ma sát nghỉ cực đại) khó hơn việc duy trì nó trượt đều. Và lăn thì nhẹ nhất."},

    {"id": "mc-c2-117", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Tổng kết định luật Newton",
     "question": "Câu nói 'Không có lực thì không có chuyển động' là sai theo vật lí hiện đại. Trái lại, 'Không có lực thì...'",
     "choices": ["... không có GIA TỐC (không có sự thay đổi vận tốc)", "... không có VẬN TỐC", "... không có MA SÁT", "... không có QUÁN TÍNH"],
     "answer": 0, "explanation": "Lực là nguyên nhân sinh ra gia tốc. Nếu không có lực, gia tốc bằng 0, vật vẫn có thể đang giữ vận tốc đều không đổi."},
    {"id": "mc-c2-118", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Khối lượng",
     "question": "Một hòn đá được ném trong một tàu vũ trụ đang bay ngoài không gian (trạng thái không trọng lượng). Người phi hành gia dùng ngón tay chặn hòn đá lại. Anh ta có cảm thấy đau không?",
     "choices": ["Có, vì hòn đá vẫn có khối lượng và quán tính, tạo ra lực va chạm khi bị thay đổi vận tốc đột ngột", "Không, vì hòn đá ở trạng thái không trọng lượng nên nhẹ như lông hồng", "Không, vì trong chân không không truyền được cảm giác", "Có, vì nó bị nhiễm phóng xạ"],
     "answer": 0, "explanation": "Khối lượng (đại lượng đo quán tính) luôn tồn tại dù không có lực hấp dẫn (không có trọng lượng). Khi cản hòn đá có khối lượng $m$, tay phải tác dụng lực $F = m \\Delta v/\\Delta t$, lực này (và phản lực) sẽ làm tay bị đau."},
    {"id": "mc-c2-119", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Khối lượng đo bằng lực",
     "question": "Trên trạm vũ trụ quốc tế (ISS), người ta dùng một chiếc ghế có gắn lò xo để đo khối lượng các phi hành gia. Nguyên lí của dụng cụ này là:",
     "choices": ["Dựa vào Định luật 2 Newton, biết lực đàn hồi lò xo đẩy ghế và đo gia tốc sinh ra để suy ra khối lượng", "Đo trọng lượng biểu kiến do trạm vũ trụ quay", "Dùng cân thăng bằng so với quả cân chuẩn", "Dùng tia laser đo thể tích cơ thể rồi nhân khối lượng riêng"],
     "answer": 0, "explanation": "Do $P=0$ nên không thể dùng cân đĩa hay lò xo đo sức nặng. Thiết bị (BMMD - Body Mass Measurement Device) áp dụng $m = F/a$. Lò xo bung ra tác dụng lực F đã biết, quang học đo gia tốc a $\\Rightarrow$ tính được m."},
    {"id": "mc-c2-120", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Quán tính của Trái Đất",
     "question": "Tại sao hàng tỉ người trên Trái Đất cùng nhảy lên một lúc cũng không làm thay đổi quỹ đạo quay của Trái Đất một cách đáng kể?",
     "choices": ["Vì khối lượng (quán tính) của Trái Đất quá khổng lồ so với tổng khối lượng loài người", "Vì Trái Đất bị lực hút Mặt Trời khóa chặt", "Vì mọi người không thể nhảy đồng thời một cách hoàn hảo", "Vì lực của con người bị triệt tiêu bởi không khí"],
     "answer": 0, "explanation": "Mặc dù theo ĐL 3 Newton, người đạp chân xuống đẩy Trái Đất đi 1 lực F. Nhưng $a_{\\text{TĐ}} = F / M_{\\text{TĐ}}$, vì $M_{\\text{TĐ}} \\approx 6 \\times 10^{24}\\text{ kg}$ quá khổng lồ, gia tốc thu được là $0$ trong thực tế."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/ly10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Ly10 C2 Part 2 written successfully.")
