import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 4 HÓA HỌC 10: NĂNG LƯỢNG HÓA HỌC (Phần 2) ---
    {"id": "mc-c4-061", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Sự đổi màu đồng(II) sunfat",
     "question": "Khi nhỏ nước vào tinh thể $CuSO_4$ khan (màu trắng), phản ứng tạo thành $CuSO_4\\cdot 5H_2O$ (màu xanh) xảy ra. Dùng nhiệt kế đo ta thấy nhiệt độ của hệ tăng lên. Điều này chứng tỏ:",
     "choices": ["Quá trình hiđrat hóa (ngậm nước) của $CuSO_4$ là quá trình tỏa nhiệt", "Quá trình này là quá trình thu nhiệt", "Phản ứng không có sự trao đổi nhiệt", "Nước phản ứng với nhiệt kế sinh nhiệt"],
     "answer": 0, "explanation": "Nhiệt độ của hệ tăng lên chứng tỏ phản ứng đã giải phóng nhiệt (Tỏa nhiệt). Môi trường (nước, tinh thể, nhiệt kế) nhận được lượng nhiệt này nên nóng lên."},
    {"id": "mc-c4-062", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Tính chất của phản ứng nung",
     "question": "Phản ứng nhiệt phân $Cu(OH)_2$ tạo ra $CuO$ và $H_2O$. Nếu dừng đun nóng, phản ứng lập tức dừng lại. Khẳng định nào sau đây là đúng?",
     "choices": ["Đây là phản ứng thu nhiệt, cần cung cấp nhiệt liên tục để duy trì", "Đây là phản ứng tỏa nhiệt", "Nhiệt phân sinh ra $O_2$ dập tắt phản ứng", "Đây là phản ứng tự phát ở nhiệt độ phòng"],
     "answer": 0, "explanation": "Dừng đun mà phản ứng dừng lại chứng tỏ phản ứng liên tục cần hấp thụ nhiệt năng từ môi trường để xảy ra. Đó là đặc điểm điển hình của phản ứng thu nhiệt mạnh."},
    {"id": "mc-c4-063", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Khái niệm biến thiên Enthalpy",
     "question": "Kí hiệu $\\Delta_r H$ của một phản ứng hóa học có nghĩa là:",
     "choices": ["Biến thiên enthalpy (nhiệt phản ứng) của quá trình đó", "Năng lượng hoạt hóa của phản ứng", "Nhiệt độ sôi của chất sản phẩm", "Nhiệt lượng tỏa ra khi đốt cháy 1 gam chất"],
     "answer": 0, "explanation": "$\\Delta_r H$ (Reaction Enthalpy / Biến thiên enthalpy phản ứng) là nhiệt lượng tỏa ra hay thu vào của phản ứng hóa học đẳng áp. r là viết tắt của reaction."},
    {"id": "mc-c4-064", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "So sánh 2 phản ứng",
     "question": "Phản ứng (1): Nung đá vôi có $\\Delta_r H^0 = +178,3 \\text{ kJ}$. Phản ứng (2): Đốt cháy cồn có $\\Delta_r H^0 = -1367 \\text{ kJ}$. Phát biểu nào ĐÚNG?",
     "choices": ["Phản ứng (1) thu nhiệt, phản ứng (2) tỏa nhiệt", "Cả 2 đều tỏa nhiệt", "Cả 2 đều thu nhiệt", "Phản ứng (1) tỏa nhiệt, (2) thu nhiệt"],
     "answer": 0, "explanation": "$\\Delta H > 0$ là Thu nhiệt (nhận năng lượng vào hệ). $\\Delta H < 0$ là Tỏa nhiệt (nhả năng lượng ra môi trường)."},

    {"id": "mc-c4-065", "chapter": "c4", "lesson": "b22", "level": "nb", "dang": "Kí hiệu nhiệt tạo thành",
     "question": "Nhiệt tạo thành chuẩn của một chất được kí hiệu là:",
     "choices": ["$\\Delta_f H^0_{298}$", "$\\Delta_r H^0_{298}$", "$\\Delta_c H^0_{298}$", "$\\Delta_s H^0_{298}$"],
     "answer": 0, "explanation": "Kí hiệu 'f' là formation (tạo thành). 'r' là reaction (phản ứng nói chung). 'c' là combustion (đốt cháy)."},
    {"id": "mc-c4-066", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Nhận biết đơn chất chuẩn",
     "question": "Dãy các chất nào sau đây đều có nhiệt tạo thành chuẩn $\\Delta_f H^0_{298}$ bằng 0?",
     "choices": ["$O_2(g), N_2(g), C(\\text{graphite}), Na(s)$", "$O_3(g), Cl_2(g), C(\\text{diamond}), Fe(s)$", "$H_2(g), CO_2(g), O_2(g)$", "$H_2O(l), N_2(g), Al(s)$"],
     "answer": 0, "explanation": "Đơn chất ở trạng thái bền nhất ở đk chuẩn có $\\Delta_f H = 0$. $O_3$ và C (kim cương) không phải dạng bền nhất nên khác 0. $CO_2$ và $H_2O$ là hợp chất nên khác 0."},
    {"id": "mc-c4-067", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Xác định phương trình sinh nhiệt",
     "question": "Phương trình nào ứng với Nhiệt tạo thành chuẩn của khí Ammonia ($NH_3$)?",
     "choices": ["$\\frac{1}{2}N_2(g) + \\frac{3}{2}H_2(g) \\rightarrow NH_3(g)$", "$N_2(g) + 3H_2(g) \\rightarrow 2NH_3(g)$", "$NH_4^+(aq) + OH^-(aq) \\rightarrow NH_3(g) + H_2O(l)$", "$NO_2(g) + \\frac{7}{2}H_2(g) \\rightarrow NH_3(g) + 2H_2O(l)$"],
     "answer": 0, "explanation": "Nhiệt tạo thành (Formation) là tạo ra đúng 1 MOL sản phẩm từ CÁC ĐƠN CHẤT ($N_2, H_2$). Phản ứng A đúng chuẩn. Phản ứng B tạo 2 mol nên giá trị $\\Delta H$ của B sẽ gấp đôi nhiệt tạo thành của NH3."},
    {"id": "mc-c4-068", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Mối quan hệ $\\Delta H_f$ và $\\Delta H_r$",
     "question": "Cho $\\Delta_f H^0(NO_2) = +33,18 \\text{ kJ/mol}$. Biến thiên enthalpy của phản ứng $N_2(g) + 2O_2(g) \\rightarrow 2NO_2(g)$ là:",
     "choices": ["+66,36 kJ", "+33,18 kJ", "-66,36 kJ", "-33,18 kJ"],
     "answer": 0, "explanation": "Phản ứng này tạo ra 2 mol $NO_2$ từ đơn chất. Do đó $\\Delta_r H = 2 \\times \\Delta_f H(NO_2) = 2 \\times 33,18 = +66,36 \\text{ kJ}$."},

    {"id": "mc-c4-069", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Trục tọa độ giản đồ",
     "question": "Trong giản đồ năng lượng, trục tung (trục thẳng đứng) và trục hoành (trục ngang) thường biểu diễn đại lượng nào?",
     "choices": ["Trục tung là Năng lượng (Enthalpy), trục hoành là Tiến trình phản ứng", "Trục tung là Tiến trình phản ứng, trục hoành là Năng lượng", "Trục tung là Nhiệt độ, trục hoành là Thời gian", "Trục tung là Khối lượng, trục hoành là Thời gian"],
     "answer": 0, "explanation": "Giản đồ năng lượng: Trục y là mức năng lượng (H), trục x biểu diễn tiến trình xảy ra của phản ứng (từ chất phản ứng $\\rightarrow$ sản phẩm)."},
    {"id": "mc-c4-070", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Đánh giá mức chênh lệch H",
     "question": "Quan sát giản đồ năng lượng, nếu đoạn chênh lệch giữa chất tham gia và sản phẩm rất lớn và hướng xuống dưới, điều này có ý nghĩa gì?",
     "choices": ["Phản ứng tỏa ra một lượng nhiệt rất lớn, sản phẩm rất bền vững so với chất tham gia", "Phản ứng thu một lượng nhiệt rất lớn", "Phản ứng xảy ra cực kì chậm", "Phản ứng cần đun nóng liên tục"],
     "answer": 0, "explanation": "Hướng xuống = hệ mất năng lượng $\\Rightarrow$ Tỏa nhiệt. Chênh lệch lớn = Tỏa nhiều nhiệt. Trạng thái năng lượng càng thấp thì cấu trúc càng bền vững (SP bền hơn Chất đầu nhiều)."},
    {"id": "mc-c4-071", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Toán Đồ thị",
     "question": "Một phản ứng có mức Enthalpy của chất tham gia là 100 kJ, mức Enthalpy của sản phẩm là 40 kJ. Biến thiên Enthalpy $\\Delta_r H$ của phản ứng là:",
     "choices": ["-60 kJ (Phản ứng tỏa nhiệt)", "+60 kJ (Phản ứng thu nhiệt)", "140 kJ (Thu nhiệt)", "-140 kJ (Tỏa nhiệt)"],
     "answer": 0, "explanation": "$\\Delta_r H = H_{\\text{sản phẩm}} - H_{\\text{chất tham gia}} = 40 - 100 = -60 \\text{ kJ}$. Dấu âm nên là tỏa nhiệt."},
    {"id": "mc-c4-072", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Năng lượng hoạt hóa đồ thị",
     "question": "Trên giản đồ năng lượng, đỉnh cao nhất của đường cong (nằm giữa chất đầu và sản phẩm) thể hiện điều gì?",
     "choices": ["Trạng thái chuyển tiếp có năng lượng cao nhất (liên quan đến năng lượng hoạt hóa $E_a$ cần để khơi mào phản ứng)", "Nhiệt lượng tỏa ra của phản ứng", "Năng lượng của sản phẩm phụ", "Khối lượng bị hao hụt"],
     "answer": 0, "explanation": "Để phản ứng xảy ra, các chất tham gia phải va chạm và vượt qua một \"bức tường năng lượng\" gọi là năng lượng hoạt hóa ($E_a$). Đỉnh núi trên đồ thị biểu diễn trạng thái chuyển tiếp kém bền này."},

    {"id": "mc-c4-073", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Công thức Delta H",
     "question": "Để tính Nhiệt phản ứng $\\Delta_r H^0_{298}$ theo Nhiệt tạo thành $\\Delta_f H^0_{298}$, ta lấy:",
     "choices": ["Tổng Nhiệt tạo thành của SẢN PHẨM trừ đi Tổng Nhiệt tạo thành của CHẤT THAM GIA (có nhân hệ số)", "Tổng CHẤT THAM GIA trừ đi Tổng SẢN PHẨM", "Tích của SẢN PHẨM chia Tích CHẤT THAM GIA", "Không có quy tắc chung"],
     "answer": 0, "explanation": "Công thức: $\\Delta_r H = \\sum \\Delta_f H_{\\text{sản phẩm}} - \\sum \\Delta_f H_{\\text{chất đầu}}$."},
    {"id": "mc-c4-074", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính Toán Cơ Bản",
     "question": "Cho phản ứng: $CH_4(g) + H_2O(g) \\rightarrow CO(g) + 3H_2(g)$. Biết $\\Delta_f H^0 (\\text{kJ/mol})$ của $CH_4$, $H_2O$, $CO$ lần lượt là: -74,8 ; -241,8 ; -110,5. Tính $\\Delta_r H^0_{298}$?",
     "choices": ["+206,1 kJ", "-206,1 kJ", "+106,5 kJ", "-106,5 kJ"],
     "answer": 0, "explanation": "SP: $CO$ (-110,5) + $3H_2$ (0) = -110,5. Đầu: $CH_4$ (-74,8) + $H_2O$ (-241,8) = -316,6. $\\Delta_r H = (-110,5) - (-316,6) = +206,1 \\text{ kJ}$. Phản ứng thu nhiệt mạnh (chỉ xảy ra ở nhiệt độ cao)."},
    {"id": "mc-c4-075", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính toán có hệ số",
     "question": "Tính $\\Delta_r H^0_{298}$ của phản ứng nung vôi: $CaCO_3(s) \\rightarrow CaO(s) + CO_2(g)$. Cho $\\Delta_f H^0$ (kJ/mol): $CaCO_3$ (-1206,9); $CaO$ (-635,1); $CO_2$ (-393,5).",
     "choices": ["+178,3 kJ", "-178,3 kJ", "+2235,5 kJ", "-2235,5 kJ"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = [-635,1 + (-393,5)] - [-1206,9] = -1028,6 + 1206,9 = +178,3 \\text{ kJ}$."},
    {"id": "mc-c4-076", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tìm ẩn Hf từ Delta H",
     "question": "Phản ứng nhiệt nhôm: $2Al + Fe_2O_3 \\rightarrow Al_2O_3 + 2Fe$ có $\\Delta_r H^0 = -851,5 \\text{ kJ}$. Biết $\\Delta_f H^0$ của $Fe_2O_3$ là -824,2 kJ/mol. Tính nhiệt tạo thành chuẩn của $Al_2O_3$?",
     "choices": ["-1675,7 kJ/mol", "-851,5 kJ/mol", "+1675,7 kJ/mol", "-27,3 kJ/mol"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = \\Delta_f H(Al_2O_3) - \\Delta_f H(Fe_2O_3)$. (Vì Al và Fe bằng 0). $\\Rightarrow -851,5 = x - (-824,2) = x + 824,2 \Rightarrow x = -851,5 - 824,2 = -1675,7 \\text{ kJ/mol}$."},

    {"id": "mc-c4-077", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Quy tắc NLLK",
     "question": "Để tính $\\Delta_r H^0$ dựa vào năng lượng liên kết ($E_b$), ta sử dụng công thức nào? (Giả sử các chất đều ở thể khí)",
     "choices": ["Tổng $E_b$ các liên kết bị đứt (Chất tham gia) trừ đi Tổng $E_b$ các liên kết được tạo thành (Sản phẩm)", "Tổng $E_b$ (Sản phẩm) trừ Tổng $E_b$ (Chất tham gia)", "Tổng $E_b$ của tất cả các chất", "Tổng khối lượng liên kết"],
     "answer": 0, "explanation": "Phá vỡ liên kết CẦN CUNG CẤP năng lượng (+). Hình thành liên kết TỎA năng lượng (-). Do đó $\\Delta H = \\sum E_{b(\\text{đầu})} - \\sum E_{b(\\text{sau})}$. Chú ý nó ngược với công thức Nhiệt tạo thành."},
    {"id": "mc-c4-078", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính cơ bản H2 + I2",
     "question": "Tính $\\Delta_r H^0$ của phản ứng: $H_2(g) + I_2(g) \\rightarrow 2HI(g)$. Cho $E_b$ (kJ/mol): $H-H = 436$; $I-I = 151$; $H-I = 299$.",
     "choices": ["-11 kJ", "+11 kJ", "-288 kJ", "-598 kJ"],
     "answer": 0, "explanation": "Tổng $E_b$ đứt $= 436 + 151 = 587$ kJ. Tổng $E_b$ nối $= 2 \\times 299 = 598$ kJ. $\\Delta_r H = 587 - 598 = -11 \\text{ kJ}$."},
    {"id": "mc-c4-079", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Liên kết đôi O=O",
     "question": "Đốt cháy $H_2$: $2H_2(g) + O_2(g) \\rightarrow 2H_2O(g)$. Biết $E_b$ (kJ/mol): $H-H=436$, $O=O=498$, $O-H=464$. Tính $\\Delta_r H^0$?",
     "choices": ["-486 kJ", "+486 kJ", "-243 kJ", "-1370 kJ"],
     "answer": 0, "explanation": "Đầu: 2 phân tử $H_2$ (2 lk H-H) và 1 phân tử $O_2$ (1 lk O=O) $\\Rightarrow E_{\\text{đầu}} = 2 \\times 436 + 498 = 1370$. Sau: 2 phân tử $H_2O$ (có tổng $2 \\times 2 = 4$ lk O-H) $\\Rightarrow E_{\\text{sau}} = 4 \\times 464 = 1856$. $\\Delta_r H = 1370 - 1856 = -486 \\text{ kJ}$."},
    {"id": "mc-c4-080", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính liên kết ẩn",
     "question": "Cho phản ứng $N_2 + 3H_2 \\rightarrow 2NH_3$. $\\Delta_r H = -92 \\text{ kJ}$. Biết $E_b(H-H) = 436 \\text{ kJ/mol}$, $E_b(N-H) = 391 \\text{ kJ/mol}$. Năng lượng liên kết $N\\equiv N$ là:",
     "choices": ["946 kJ/mol", "473 kJ/mol", "918 kJ/mol", "736 kJ/mol"],
     "answer": 0, "explanation": "$E(N\\equiv N) + 3 \\times 436 - 6 \\times 391 = -92$. $E(N\\equiv N) + 1308 - 2346 = -92 \\Rightarrow E(N\\equiv N) = -92 + 1038 = 946 \\text{ kJ/mol}$."},

    {"id": "mc-c4-081", "chapter": "c4", "lesson": "b24", "level": "th", "dang": "Nhiệt lượng kế",
     "question": "Trong phòng thí nghiệm, thiết bị nào được sử dụng để đo trực tiếp nhiệt lượng tỏa ra hoặc thu vào của một phản ứng hóa học (từ đó tính được $\\Delta H$)?",
     "choices": ["Nhiệt lượng kế (Calorimeter)", "Nhiệt kế (Thermometer)", "Cân phân tích", "Áp kế"],
     "answer": 0, "explanation": "Nhiệt lượng kế (Calorimeter) là thiết bị chuyên dụng, cách nhiệt tốt, dùng để đo lượng nhiệt trao đổi thông qua sự thay đổi nhiệt độ $\\Delta t$ của khối nước bên trong."},
    {"id": "mc-c4-082", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Tính Q = m c dT",
     "question": "Hòa tan hoàn toàn 1 lượng muối vào Nhiệt lượng kế chứa 200 gam nước. Nhiệt độ của nước giảm từ $25,0^\\circ\\text{C}$ xuống $20,0^\\circ\\text{C}$. Biết nhiệt dung riêng của nước là $4,18 \\text{ J/(g\\cdot K)}$. Nhiệt lượng môi trường (nước) đã truyền cho hệ phản ứng là:",
     "choices": ["4180 J (hay 4,18 kJ)", "836 J", "-4180 J", "209 J"],
     "answer": 0, "explanation": "Độ giảm nhiệt độ $\\Delta t = 25 - 20 = 5^\\circ\\text{C}$ (hay 5 K). Nhiệt lượng nước mất đi = $m \\cdot c \\cdot \\Delta t = 200 \\times 4,18 \\times 5 = 4180 \\text{ Joule}$. Đây cũng là nhiệt lượng mà phản ứng hòa tan đã hấp thụ (phản ứng thu nhiệt 4,18 kJ)."},
    {"id": "mc-c4-083", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Hòa tan NaOH",
     "question": "Hòa tan 0,1 mol $NaOH$ rắn vào 100g nước trong nhiệt lượng kế. Nhiệt độ nước tăng từ $20^\\circ\\text{C}$ lên $30,6^\\circ\\text{C}$. Nhiệt dung riêng của dung dịch xem như của nước là $4,18 \\text{ J/(g\\cdot K)}$. Bỏ qua nhiệt dung của bình. Biến thiên Enthalpy hòa tan của 1 mol NaOH là bao nhiêu?",
     "choices": ["-44,3 kJ/mol", "+44,3 kJ/mol", "-4,43 kJ/mol", "+4,43 kJ/mol"],
     "answer": 0, "explanation": "Giả sử khối lượng hệ m = 100g (bỏ qua khối lượng NaOH), $Q = mc\\Delta T = 100 \\times 4,18 \\times 10,6 = 4430,8 \\text{ J} \\approx 4,43 \\text{ kJ}$. Vì nhiệt độ tăng $\\Rightarrow$ Tỏa nhiệt. $\\Delta H = -4,43 / 0,1 = -44,3 \\text{ kJ/mol}$."},
    {"id": "mc-c4-084", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "Lượng nhiệt đun nấu",
     "question": "Để đun sôi 1 lít nước (1 kg) từ $30^\\circ\\text{C}$ lên $100^\\circ\\text{C}$ cần cung cấp một nhiệt lượng Q. Biết nhiệt dung riêng của nước là $4,18 \\text{ kJ/(kg\\cdot K)}$. Tính Q?",
     "choices": ["292,6 kJ", "418 kJ", "125,4 kJ", "300 kJ"],
     "answer": 0, "explanation": "$Q = m \\cdot c \\cdot \\Delta t = 1 \\text{ kg} \\times 4,18 \\text{ kJ/(kg.K)} \\times (100 - 30) = 1 \\times 4,18 \\times 70 = 292,6 \\text{ kJ}$."},

    {"id": "mc-c4-085", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Hess tổ hợp 3 PT",
     "question": "Tính $\\Delta H$ của $C(\\text{graphite}) \\rightarrow C(\\text{diamond})$. Biết đốt 1 mol graphite tỏa 393,5 kJ; đốt 1 mol diamond tỏa 395,4 kJ.",
     "choices": ["+1,9 kJ/mol", "-1,9 kJ/mol", "+788,9 kJ/mol", "-788,9 kJ/mol"],
     "answer": 0, "explanation": "Áp dụng định luật Hess bằng cách lấy PT(đốt graphite) trừ đi PT(đốt diamond). Kết quả: $-393,5 - (-395,4) = +1,9 \\text{ kJ/mol}$."},
    {"id": "mc-c4-086", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Tính Enthalpy phản ứng thuận nghịch",
     "question": "Cho $\\Delta_r H^0_{298}$ của phản ứng tổng hợp Amoniac: $N_2(g) + 3H_2(g) \\rightleftharpoons 2NH_3(g)$ là -92 kJ. Nếu phân hủy hoàn toàn 1 mol $NH_3$ thành khí $N_2$ và $H_2$ ở điều kiện chuẩn thì hệ sẽ:",
     "choices": ["Thu vào 46 kJ", "Tỏa ra 46 kJ", "Thu vào 92 kJ", "Tỏa ra 92 kJ"],
     "answer": 0, "explanation": "Phản ứng thuận tạo 2 mol NH3 tỏa 92 kJ ($\\Delta H = -92$). Vậy phản ứng phân hủy 2 mol NH3 sẽ thu 92 kJ ($\\Delta H = +92$). Yêu cầu hỏi cho 1 mol NH3 $\\Rightarrow$ Thu vào $92 / 2 = 46 \\text{ kJ}$."},
    {"id": "mc-c4-087", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhiệt phản ứng tổng",
     "question": "Cho 2 phương trình:\n(I) $2NO(g) + O_2(g) \\rightarrow 2NO_2(g) \\quad \\Delta H = -114 \\text{ kJ}$\n(II) $4NO_2(g) + O_2(g) \\rightarrow 2N_2O_5(g) \\quad \\Delta H = -110 \\text{ kJ}$\nTính $\\Delta H$ của $4NO(g) + 3O_2(g) \\rightarrow 2N_2O_5(g)$.",
     "choices": ["-338 kJ", "-224 kJ", "+4 kJ", "-114 kJ"],
     "answer": 0, "explanation": "Phương trình tổng = 2 $\\times$ (I) + (II). $\\Delta H = 2 \\times (-114) + (-110) = -228 - 110 = -338 \\text{ kJ}$."},

    {"id": "mc-c4-088", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Eb trung bình O=O",
     "question": "Sự phân hủy Ozone: $2O_3(g) \\rightarrow 3O_2(g)$ có $\\Delta H = -285,4 \\text{ kJ}$. Biết cấu tạo của $O_3$ có 1 liên kết $O=O$ và 1 liên kết $O-O$. Tổng $E_b$ của 1 phân tử $O_3$ là 605 kJ/mol. Tính năng lượng liên kết $O=O$ trong phân tử Oxi ($O_2$)?",
     "choices": ["498,5 kJ/mol", "285,4 kJ/mol", "142,7 kJ/mol", "605,0 kJ/mol"],
     "answer": 0, "explanation": "$\\Delta H = 2 \\times E_b(O_3) - 3 \\times E_b(O=O) = -285,4 \\Rightarrow 2 \\times 605 - 3x = -285,4 \\Rightarrow x = 498,47 \\approx 498,5 \\text{ kJ/mol}$."},
    {"id": "mc-c4-089", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Lỗi sai $E_b$",
     "question": "Tính $\\Delta_r H$ của phản ứng $C(\\text{graphite}) + O_2(g) \\rightarrow CO_2(g)$ BẰNG phương pháp Năng lượng liên kết $E_b$. Kết quả tính được sẽ:",
     "choices": ["Không chính xác vì Carbon graphite là chất rắn có cấu trúc mạng tinh thể (không áp dụng $E_b$ cho khí trực tiếp được)", "Rất chính xác, bằng đúng $\\Delta_f H$ của $CO_2$", "Bằng 0", "Luôn ra kết quả dương"],
     "answer": 0, "explanation": "Mạng tinh thể cộng hóa trị của Than chì (rắn) cần nhiệt thăng hoa khổng lồ để tạo thành nguyên tử C (khí). Công thức $E_b$ bỏ qua nhiệt này nên sai."},
    {"id": "mc-c4-090", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Năng lượng lk đa nguyên tử",
     "question": "Trong phân tử $H_2O$, năng lượng bẻ gãy liên kết $O-H$ thứ nhất là 502 kJ/mol. Liên kết $O-H$ thứ hai là 426 kJ/mol. Năng lượng liên kết $E_b (O-H)$ trong bảng tuần hoàn được lấy giá trị nào?",
     "choices": ["Giá trị trung bình của 2 giai đoạn: (502 + 426) / 2 = 464 kJ/mol", "Giá trị lớn nhất: 502 kJ/mol", "Giá trị nhỏ nhất: 426 kJ/mol", "Tổng 2 giá trị: 928 kJ/mol"],
     "answer": 0, "explanation": "Các liên kết giống nhau trong phân tử đa nguyên tử thường có năng lượng bẻ gãy thực tế khác nhau theo từng bước. Do đó bảng dữ liệu sử dụng năng lượng liên kết TRUNG BÌNH (464 kJ/mol)."},
    {"id": "mc-c4-091", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Thực tế Đốt cháy Ethanol",
     "question": "Nhiệt đốt cháy ($\\Delta_c H^0$) của Ethanol ($C_2H_5OH(l)$) là -1367 kJ/mol. Một đèn cồn chứa 46 gam cồn. Biết cồn bị hao hụt bay hơi mất $10\\%$, phần còn lại cháy hoàn toàn. Nhiệt lượng thực tế tỏa ra là:",
     "choices": ["1230,3 kJ", "1367,0 kJ", "136,7 kJ", "2460,6 kJ"],
     "answer": 0, "explanation": "46g cồn = 1 mol. Lượng cồn thực tế cháy = $1 \\times 90\\% = 0,9$ mol. Nhiệt lượng tỏa ra $Q = 0,9 \\times 1367 = 1230,3 \\text{ kJ}$."},

    {"id": "mc-c4-092", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Phản ứng nội sinh cơ thể",
     "question": "Hiện tượng cơ thể con người tỏa nhiệt liên tục ra môi trường xung quanh (giữ thân nhiệt $37^\\circ\\text{C}$) là do:",
     "choices": ["Các quá trình oxi hóa chất dinh dưỡng (hô hấp tế bào) bên trong cơ thể là các phản ứng tỏa nhiệt", "Cơ thể hấp thụ nhiệt từ mặt trời", "Sự ma sát của máu trong mạch", "Tất cả các phản ứng trong cơ thể đều là thu nhiệt"],
     "answer": 0, "explanation": "Quá trình \"đốt cháy\" (oxi hóa) Glucose, chất béo, protein bên trong tế bào là các phản ứng tỏa nhiệt $\\Delta H < 0$. Một phần thành ATP sinh công, một phần thoát ra dưới dạng nhiệt năng sưởi ấm cơ thể."},
    {"id": "mc-c4-093", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Hydrogen làm nhiên liệu",
     "question": "Khí Hydrogen ($H_2$) được coi là nhiên liệu sạch của tương lai. Lí do nào về mặt hóa học là ĐÚNG nhất?",
     "choices": ["Phản ứng cháy của nó tỏa ra năng lượng rất lớn và sản phẩm duy nhất là Nước ($H_2O$), không gây ô nhiễm (không có $CO_2$)", "Vì $H_2$ dễ điều chế từ đá vôi", "Vì $H_2$ không thể cháy, rất an toàn", "Vì $H_2$ phản ứng thu nhiệt làm mát động cơ"],
     "answer": 0, "explanation": "$H_2 + \\frac{1}{2}O_2 \\rightarrow H_2O \\quad \\Delta H = -285,8 \\text{ kJ}$. Tỏa cực nhiều nhiệt theo khối lượng, và KHÔNG phát thải khí nhà kính (Carbon dioxide, $CO_2$)."},
    {"id": "mc-c4-094", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tổng hợp amoniac trong CN",
     "question": "Phản ứng $N_2 + 3H_2 \\rightleftharpoons 2NH_3$ có $\\Delta H = -92 \\text{ kJ}$ (Tỏa nhiệt). Tuy nhiên trong công nghiệp, người ta lại phải đun nóng hỗn hợp khí lên khoảng $450^\\circ\\text{C}$ chứ không để ở nhiệt độ thường. Tại sao?",
     "choices": ["Để cung cấp năng lượng hoạt hóa phá vỡ liên kết $N\\equiv N$ rất bền, làm cho phản ứng xảy ra nhanh hơn", "Vì phản ứng này thu nhiệt", "Để làm bay hơi Amoniac sinh ra", "Vì ở nhiệt độ thường $N_2$ là chất lỏng"],
     "answer": 0, "explanation": "Nhiệt độ cao cung cấp năng lượng hoạt hóa để bẻ gãy liên kết $N\\equiv N$, tăng tốc độ phản ứng (mặc dù làm giảm hiệu suất cân bằng theo Le Chatelier)."},
    {"id": "mc-c4-095", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Nhiệt tạo thành Ozone và Oxi",
     "question": "Ozone ($O_3$) là dạng thù hình có năng lượng cao hơn Oxygen ($O_2$) và dễ phân hủy: $2O_3(g) \\rightarrow 3O_2(g)$. Phản ứng này là tỏa nhiệt hay thu nhiệt?",
     "choices": ["Tỏa nhiệt ($\\Delta H < 0$)", "Thu nhiệt ($\\Delta H > 0$)", "Không có $\\Delta H$", "Chỉ xảy ra ở nhiệt độ âm"],
     "answer": 0, "explanation": "Chất có năng lượng cao ($O_3$) chuyển về chất có năng lượng thấp hơn ($O_2$) $\\Rightarrow$ Phần năng lượng chênh lệch sẽ được BỨC XẠ (tỏa ra) môi trường. $\\Rightarrow \\Delta H < 0$."},

    {"id": "mc-c4-096", "chapter": "c4", "lesson": "b22", "level": "nb", "dang": "Nhận biết biểu thức H",
     "question": "Giá trị của $\\Delta_f H^0$ thường mang dấu âm đối với các hợp chất bền vững. Một chất có $\\Delta_f H^0 > 0$ thì chất đó:",
     "choices": ["Thường kém bền, dễ phân hủy", "Rất bền vững, không thể phân hủy", "Là một đơn chất kim loại", "Là một khí trơ"],
     "answer": 0, "explanation": "$\\Delta_f H^0 > 0$ (Hợp chất thu nhiệt khi tạo thành) $\\Rightarrow$ Trạng thái năng lượng của nó cao hơn các đơn chất tạo ra nó $\\Rightarrow$ Nó có xu hướng tự giải phóng năng lượng để quay về các đơn chất bền vững (Kém bền)."},
    {"id": "mc-c4-097", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Mối quan hệ Enthalpy và phản ứng",
     "question": "Phản ứng nổ của thuốc súng đen ($2KNO_3 + 3C + S \\rightarrow K_2S + N_2 + 3CO_2$) xảy ra cực kì nhanh. Phản ứng này chắc chắn có đặc điểm:",
     "choices": ["Tỏa ra lượng nhiệt rất lớn và sinh ra lượng lớn chất khí ($\\Delta H \\ll 0$)", "Thu nhiệt rất mạnh", "Không sinh ra chất khí", "Có $\\Delta H > 0$"],
     "answer": 0, "explanation": "Bản chất của cháy nổ là phản ứng tỏa nhiệt cực mạnh kèm theo sự tạo thành thể tích khí lớn đột ngột."},
    {"id": "mc-c4-098", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "So sánh 2 giá trị Enthalpy",
     "question": "Phản ứng $H_2(g) + F_2(g) \\rightarrow 2HF(g)$ có $\\Delta H = -546 \\text{ kJ}$. Phản ứng $H_2(g) + Cl_2(g) \\rightarrow 2HCl(g)$ có $\\Delta H = -185 \\text{ kJ}$. Kết luận nào đúng?",
     "choices": ["Liên kết trong $HF$ bền hơn nhiều so với trong $HCl$", "Liên kết trong $HCl$ bền hơn $HF$", "Fluorine ít hoạt động hơn Chlorine", "Cả 2 tạo ra năng lượng như nhau"],
     "answer": 0, "explanation": "Năng lượng tỏa ra càng nhiều $\\Rightarrow$ Hợp chất sinh ra có mức năng lượng càng thấp $\\Rightarrow$ Càng bền vững. (Năng lượng liên kết H-F lớn hơn H-Cl)."},
    {"id": "mc-c4-099", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Toán $\\Delta H$ có $H_2O(l)$",
     "question": "Đốt cháy khí Methane ($CH_4$): $CH_4(g) + 2O_2(g) \\rightarrow CO_2(g) + 2H_2O(l)$. Biết $\\Delta_f H^0(CH_4) = -74,8$; $\\Delta_f H^0(CO_2) = -393,5$; $\\Delta_f H^0(H_2O, l) = -285,8 \\text{ (kJ/mol)}$. Tính $\\Delta_r H^0_{298}$ của phản ứng?",
     "choices": ["-890,3 kJ", "+890,3 kJ", "-604,5 kJ", "-965,1 kJ"],
     "answer": 0, "explanation": "$\\Delta_r H^0 = [-393,5 + 2(-285,8)] - [-74,8 + 0] = [-393,5 - 571,6] + 74,8 = -965,1 + 74,8 = -890,3 \\text{ kJ}$."},
    {"id": "mc-c4-100", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "So sánh PƯ Hóa hơi",
     "question": "Dựa vào câu trên (tạo $H_2O$ lỏng tỏa 890,3 kJ). Nếu nước sinh ra ở thể KHÍ ($H_2O(g)$) thì lượng nhiệt phản ứng tỏa ra sẽ LỚN HƠN hay NHỎ HƠN 890,3 kJ?",
     "choices": ["Nhỏ hơn (tỏa ra ít nhiệt hơn do phải tốn một phần nhiệt để hóa hơi nước)", "Lớn hơn", "Bằng nhau", "Không xác định được"],
     "answer": 0, "explanation": "Để nước lỏng thành nước khí cần CUNG CẤP nhiệt (quá trình thu nhiệt). Nên khi phản ứng chỉ tạo ra nước khí, lượng nhiệt tỏa ra bên ngoài sẽ bị giảm đi (so với khi ngưng tụ thành lỏng)."},

    {"id": "mc-c4-101", "chapter": "c4", "lesson": "b21", "level": "th", "dang": "Đánh giá chất lượng bài toán",
     "question": "Nếu tính toán $\\Delta_r H^0$ của phản ứng cháy của Than củi ($C + O_2 \\rightarrow CO_2$) bằng Năng lượng liên kết ($E_b$) thì sẽ sai số lớn. Tại sao?",
     "choices": ["Vì Than (C) ở thể rắn, công thức $E_b$ chỉ tính đứt gãy liên kết trong phân tử khí, bỏ qua nhiệt thăng hoa khổng lồ của C rắn thành C khí", "Vì không biết liên kết trong $CO_2$", "Vì $O_2$ có liên kết đôi", "Vì $E_b$ chỉ dùng cho hóa hữu cơ"],
     "answer": 0, "explanation": "Áp dụng năng lượng liên kết bỏ qua năng lượng mạng lưới tinh thể hoặc năng lượng thăng hoa của chất rắn, dẫn đến tính toán bị thiếu hụt năng lượng."},
    {"id": "mc-c4-102", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Nhiệt tạo thành của Halogen",
     "question": "Trong các Halogen ở điều kiện chuẩn, chất nào có $\\Delta_f H^0 = 0$?",
     "choices": ["$F_2(g), Cl_2(g), Br_2(l), I_2(s)$", "$F_2(g), Cl_2(g), Br_2(g), I_2(g)$", "$F(g), Cl(g), Br(g), I(g)$", "Chỉ có $Cl_2(g)$"],
     "answer": 0, "explanation": "Ở điều kiện chuẩn ($25^\\circ\\text{C}, 1 \\text{ bar}$): Flo và Clo là chất khí (g), Brom là chất lỏng (l), Iot là chất rắn (s). Đơn chất dạng bền nhất ở điều kiện đó mới có nhiệt tạo thành bằng 0."},
    {"id": "mc-c4-103", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Toán Tổng hợp Nước",
     "question": "Cho NLLK $E_b$ (kJ/mol): H-H (436), O=O (498), O-H (464). Phản ứng $H_2(g) + \\frac{1}{2}O_2(g) \\rightarrow H_2O(g)$ có $\\Delta_r H^0$ là:",
     "choices": ["-243 kJ", "+243 kJ", "-486 kJ", "-300 kJ"],
     "answer": 0, "explanation": "$E_{\\text{đứt}} = 436 + 0,5 \\times 498 = 436 + 249 = 685$. $E_{\\text{nối}} = 2 \\times 464 = 928$ (vì $H_2O$ có 2 liên kết O-H). $\\Delta H = 685 - 928 = -243 \\text{ kJ}$."},
    {"id": "mc-c4-104", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhiệt phản ứng và Khối lượng",
     "question": "Phản ứng nhiệt nhôm $2Al + Fe_2O_3 \\rightarrow Al_2O_3 + 2Fe$ tỏa ra 851,5 kJ. Để hàn một đoạn đường ray tàu hỏa cần sinh ra 8515 kJ nhiệt, khối lượng bột Nhôm (Al) tối thiểu cần dùng là bao nhiêu? (Al=27)",
     "choices": ["540 gam", "270 gam", "54 gam", "1080 gam"],
     "answer": 0, "explanation": "Nhiệt lượng cần gấp 10 lần phương trình chuẩn ($8515 / 851,5 = 10$). Hệ số của Al trong phương trình là 2 mol. Vậy số mol Al thực tế = $2 \\times 10 = 20$ mol. $m_{Al} = 20 \\times 27 = 540 \\text{ gam}$."},

    {"id": "mc-c4-105", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "So sánh $\\Delta H$ khác nhiệt độ",
     "question": "Nhiệt phản ứng $\\Delta_r H$ của một phản ứng hóa học có phụ thuộc vào nhiệt độ mà tại đó phản ứng xảy ra không?",
     "choices": ["Có phụ thuộc (mặc dù sự phụ thuộc thường nhỏ nếu khoảng nhiệt độ không quá lớn)", "Hoàn toàn không phụ thuộc", "Chỉ phụ thuộc nếu có chất xúc tác", "Chỉ phụ thuộc với chất khí"],
     "answer": 0, "explanation": "Nhiệt dung của các chất tham gia và sản phẩm khác nhau. Khi tăng nhiệt độ, Enthalpy của các chất tăng lên không đều nhau (Định luật Kirchhoff). Do đó $\\Delta H$ có thay đổi, dù thường nhỏ."},
    {"id": "mc-c4-106", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Lập luận Hess đơn giản",
     "question": "Biết $C_2H_4(g) + H_2(g) \\rightarrow C_2H_6(g)$ (1) có $\\Delta H = -137 \\text{ kJ}$. Đốt cháy 1 mol $H_2$ tỏa 286 kJ. Đốt cháy 1 mol $C_2H_4$ tỏa 1411 kJ. Đốt cháy 1 mol $C_2H_6$ (Ethane) sẽ tỏa ra bao nhiêu kJ?",
     "choices": ["1560 kJ", "1274 kJ", "1834 kJ", "1697 kJ"],
     "answer": 0, "explanation": "Tính bằng bảo toàn năng lượng/chu trình Born-Haber. Nhiệt cháy $C_2H_6 = (-1411) + (-286) - (-137) = -1560 \\text{ kJ}$."},
    {"id": "mc-c4-107", "chapter": "c4", "lesson": "b23", "level": "th", "dang": "Liên kết và tính trơ",
     "question": "Vì sao khí $N_2$ (nitrogen) cực kì trơ, trong khi khí $F_2$ (fluorine) lại hoạt động hóa học cực kì mãnh liệt, mặc dù cả 2 đều là đơn chất khí?",
     "choices": ["Vì năng lượng liên kết $N\\equiv N$ rất lớn ($\\sim 945 \\text{ kJ/mol}$), khó bị đứt gãy. Còn liên kết F-F rất nhỏ ($\\sim 159 \\text{ kJ/mol}$), dễ bị phá vỡ", "Vì phân tử $N_2$ nặng hơn $F_2$", "Vì F có độ âm điện lớn nhất", "Vì Nitrogen có nhiều điện tử tự do"],
     "answer": 0, "explanation": "Tính phản ứng phụ thuộc vào độ khó bẻ gãy liên kết ban đầu. $N\\equiv N$ quá chắc chắn $\\Rightarrow$ Trơ. F-F quá yếu (do lực đẩy giữa các cặp e không tham gia liên kết trong nguyên tử F nhỏ) $\\Rightarrow$ Dễ đứt, hoạt động mạnh."},
    {"id": "mc-c4-108", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Nhiệt thực phẩm Carbohydrate",
     "question": "Oxi hóa 1 gam Carbohydrate (tinh bột, đường) trong cơ thể sinh ra khoảng 17 kJ. Oxi hóa 1 gam chất béo (Lipid) sinh ra khoảng 38 kJ. Tại sao chất béo lại chứa nhiều năng lượng hơn?",
     "choices": ["Vì chất béo có tỉ lệ Carbon và Hydrogen cao hơn, ít tỉ lệ Oxi hơn so với đường, nên có khả năng bị oxi hóa tiếp nhiều hơn (tỏa nhiều nhiệt hơn)", "Vì chất béo nặng hơn", "Vì chất béo không tan trong nước", "Vì chất béo được cấu tạo từ liên kết ba"],
     "answer": 0, "explanation": "Lipid có mạch Hydrocarbon dài và nghèo Oxi $\\Rightarrow$ Trạng thái số oxi hóa trung bình của C rất thấp. Khi oxi hóa hoàn toàn tạo CO2 sẽ giải phóng nhiều năng lượng hơn."},

    {"id": "mc-c4-109", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Hiểu lầm nhiệt độ phản ứng",
     "question": "Phản ứng: $2H_2(g) + O_2(g) \\rightarrow 2H_2O(l)$ phải dùng mồi lửa (tia lửa điện) mới xảy ra. Vậy nó là phản ứng thu nhiệt đúng không?",
     "choices": ["Sai, đây là phản ứng tỏa nhiệt cực mạnh (nổ). Mồi lửa chỉ để cung cấp năng lượng hoạt hóa ban đầu", "Đúng, vì phải có lửa mới cháy", "Đúng, vì $\\Delta H > 0$", "Sai, vì phản ứng này không xảy ra"],
     "answer": 0, "explanation": "Tuyệt đại đa số phản ứng đốt cháy đều cần \"mồi lửa\" ban đầu để vượt qua rào cản năng lượng. Nhưng khi đã xảy ra, nó tự nhả ra nhiệt khổng lồ, nuôi phản ứng tiếp tục $\\Rightarrow$ Tỏa nhiệt."},
    {"id": "mc-c4-110", "chapter": "c4", "lesson": "b22", "level": "vd", "dang": "Tính enthalpy bay hơi",
     "question": "Enthalpy bay hơi chuẩn của nước ($\\Delta_{\\text{vap}} H^0$) là lượng nhiệt cần để chuyển 1 mol $H_2O(l) \\rightarrow H_2O(g)$. Biết $\\Delta_f H(H_2O, l) = -285,8$ và $\\Delta_f H(H_2O, g) = -241,8$. Tính $\\Delta_{\\text{vap}} H^0$?",
     "choices": ["+44,0 kJ/mol", "-44,0 kJ/mol", "+527,6 kJ/mol", "0 kJ/mol"],
     "answer": 0, "explanation": "$\\Delta H_{\\text{bay hơi}} = \\Delta_f H(H_2O, \\text{khí}) - \\Delta_f H(H_2O, \\text{lỏng}) = (-241,8) - (-285,8) = +44,0 \\text{ kJ/mol}$."},
    {"id": "mc-c4-111", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Bản chất $\\Delta H$ và sự bền vững",
     "question": "Cho $\\Delta_f H^0(NO) = +90,3 \\text{ kJ/mol}$, $\\Delta_f H^0(NO_2) = +33,2 \\text{ kJ/mol}$. Khí NO hay $NO_2$ kém bền nhiệt động hơn?",
     "choices": ["NO kém bền hơn vì nó có Enthalpy tạo thành dương lớn hơn (mức năng lượng cao hơn)", "$NO_2$ kém bền hơn", "NO bền hơn vì phân tử nhỏ hơn", "Bền như nhau"],
     "answer": 0, "explanation": "Chất có Enthalpy càng lớn (càng dương, hoặc càng ít âm) thì càng mang nhiều thế năng dư thừa $\\Rightarrow$ càng dễ bị biến đổi $\\Rightarrow$ Kém bền vững. NO (+90,3) kém bền hơn $NO_2$ (+33,2)."},
    {"id": "mc-c4-112", "chapter": "c4", "lesson": "b24", "level": "th", "dang": "Ứng dụng túi vôi sống",
     "question": "Người ta có thể làm nóng các hộp thực phẩm (ration can) ăn liền bằng cách đập vỡ một túi nhỏ bên trong chứa nước, cho chảy vào một khoang chứa chất bột màu trắng. Chất bột trắng đó rất có thể là:",
     "choices": ["Vôi sống ($CaO$)", "Đường kính", "Cát ($SiO_2$)", "Bột sắt"],
     "answer": 0, "explanation": "Phản ứng $CaO + H_2O \\rightarrow Ca(OH)_2$ tỏa nhiệt mạnh (tôi vôi), ứng dụng để làm nóng đồ ăn nhanh."},

    {"id": "mc-c4-113", "chapter": "c4", "lesson": "b21", "level": "nb", "dang": "Hiểu biết Hệ mở / kín",
     "question": "Một cốc nước nóng để trên bàn từ từ nguội đi. Cốc nước này là một:",
     "choices": ["Hệ mở (trao đổi cả nhiệt và vật chất với môi trường)", "Hệ kín (chỉ trao đổi nhiệt, không trao đổi vật chất)", "Hệ cô lập (không trao đổi gì)", "Hệ đoạn nhiệt"],
     "answer": 0, "explanation": "Vì cốc hở nên hơi nước bay ra (trao đổi vật chất), và nhiệt truyền ra ngoài (trao đổi năng lượng) $\\Rightarrow$ Hệ mở."},
    {"id": "mc-c4-114", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Dấu $\\Delta H$ và chiều phản ứng",
     "question": "Phản ứng $CO(g) + H_2O(g) \\rightleftharpoons CO_2(g) + H_2(g)$ có $\\Delta_r H^0_{298} = -41,2 \\text{ kJ}$. Nếu nhiệt độ tăng, cân bằng sẽ chuyển dịch theo chiều nào (dựa theo Le Chatelier)?",
     "choices": ["Chiều nghịch (từ phải sang trái)", "Chiều thuận (từ trái sang phải)", "Không chuyển dịch", "Phản ứng dừng lại"],
     "answer": 0, "explanation": "Tăng nhiệt độ làm cân bằng dịch chuyển theo chiều thu nhiệt. Vì chiều thuận là tỏa nhiệt (-41,2 kJ), nên chiều nghịch là thu nhiệt (+41,2 kJ)."},
    {"id": "mc-c4-115", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Tính Toán Tổng hợp Năng lượng",
     "question": "Nếu biết nhiệt đốt cháy của $C(\\text{graphite})$ là $-393,5 \\text{ kJ/mol}$, của $CO(g)$ là $-283 \\text{ kJ/mol}$. Tính nhiệt tạo thành chuẩn của $CO(g)$?",
     "choices": ["-110,5 kJ/mol", "+110,5 kJ/mol", "-676,5 kJ/mol", "+676,5 kJ/mol"],
     "answer": 0, "explanation": "Theo Hess: Nhiệt tạo thành $CO = \\Delta H(\\text{cháy } C) - \\Delta H(\\text{cháy } CO) = -393,5 - (-283,0) = -110,5 \\text{ kJ/mol}$."},
    {"id": "mc-c4-116", "chapter": "c4", "lesson": "b24", "level": "vd", "dang": "Độ chính xác Nhiệt lượng kế",
     "question": "Khi làm thí nghiệm nhiệt lượng kế với cốc xốp tĩnh điện, nguyên nhân chủ yếu nào gây ra sai số làm $\\Delta H$ đo được thường có trị tuyệt đối NHỎ HƠN lí thuyết?",
     "choices": ["Do nhiệt lượng bị thất thoát ra ngoài môi trường không khí và bị hấp thụ một phần bởi thành cốc", "Do nhiệt độ kế quá nhạy", "Do lượng hóa chất lấy dư", "Do nước tự sinh ra nhiệt"],
     "answer": 0, "explanation": "Nhiệt thất thoát ra ngoài không gian làm nhiệt độ nước tăng không đạt mức tối đa lí thuyết."},
    
    {"id": "mc-c4-117", "chapter": "c4", "lesson": "b21", "level": "vd", "dang": "Bài toán giá tiền",
     "question": "Giá của 1 bình gas 12 kg (tỏa 594000 kJ) là 350.000 VNĐ. Giá của 1 số điện (1 kWh = 3600 kJ) là 2000 VNĐ. Nếu chỉ xét về nhiệt lượng, đun nước bằng gas hay điện rẻ hơn?",
     "choices": ["Bằng điện rẻ hơn", "Bằng gas rẻ hơn", "Giá bằng nhau", "Chênh lệch không đáng kể"],
     "answer": 0, "explanation": "Tính đơn giá 1000 kJ: Gas = $(350000 / 594) \\approx 589$ đ. Điện = $(2000 / 3,6) \\approx 555$ đ. Đun bằng điện rẻ hơn (chưa xét hiệu suất bếp từ rất cao)."},
    {"id": "mc-c4-118", "chapter": "c4", "lesson": "b22", "level": "th", "dang": "Enthalpy Mạng Lưới",
     "question": "Khi bốc hơi 1 mol $NaCl$ rắn thành các ion khí ($Na^+ + Cl^-$), năng lượng cần cung cấp (Năng lượng mạng lưới tinh thể) lên tới +787 kJ/mol. Điều này cho thấy:",
     "choices": ["Liên kết ion trong mạng tinh thể $NaCl$ cực kì bền chặt", "Muối $NaCl$ rất dễ bay hơi", "Muối $NaCl$ là chất dễ cháy", "Nước không thể hòa tan $NaCl$"],
     "answer": 0, "explanation": "Năng lượng mạng lưới cực lớn chứng tỏ lực hút tĩnh điện giữa các ion ngược dấu rất mạnh $\\Rightarrow$ tinh thể rất bền vững."},
    {"id": "mc-c4-119", "chapter": "c4", "lesson": "b23", "level": "vd", "dang": "Năng lượng LK Carbon",
     "question": "Năng lượng liên kết $C-C$ là 347 kJ/mol, $C=C$ là 614 kJ/mol, $C\\equiv C$ là 839 kJ/mol. Tại sao $C=C$ không gấp đôi $C-C$ (614 < 347x2)?",
     "choices": ["Vì liên kết đôi $C=C$ bao gồm 1 liên kết sigma ($\\sigma$) bền vững và 1 liên kết pi ($\\pi$) kém bền hơn", "Vì liên kết đôi dài hơn liên kết đơn", "Vì liên kết ba hút bớt electron", "Vì nguyên tử Carbon bị biến dạng"],
     "answer": 0, "explanation": "Liên kết đôi gồm 1 lk $\\sigma$ bền và 1 lk $\\pi$ kém bền. $614 - 347 = 267 \\text{ kJ/mol}$ chính là ước lượng năng lượng của lk $\\pi$ (nhỏ hơn lk $\\sigma$)."},
    {"id": "mc-c4-120", "chapter": "c4", "lesson": "b24", "level": "th", "dang": "Tổng kết ý nghĩa chương",
     "question": "Mục đích lớn nhất của việc nghiên cứu Biến thiên Enthalpy (Nhiệt hóa học) đối với nhân loại là gì?",
     "choices": ["Đánh giá, lựa chọn nhiên liệu, thiết kế hệ thống làm mát/gia nhiệt trong kĩ thuật và dự đoán khả năng xảy ra của các quá trình tự nhiên", "Chỉ để làm bài tập hóa học", "Để tìm ra các nguyên tố mới", "Để chứng minh nguyên tử tồn tại"],
     "answer": 0, "explanation": "Nhiệt hóa học cung cấp cơ sở để khai thác và kiểm soát năng lượng hóa học một cách tối ưu, phục vụ phát triển kĩ thuật nhiệt và động cơ."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C4 Part 2 written successfully.")
