import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 1 (TIẾP THEO) - BẢNG TUẦN HOÀN CÁC NGUYÊN TỐ HÓA HỌC ---
    # Nhóm 16, 17: Cấu tạo bảng tuần hoàn (Nguyên tắc, Ô nguyên tố)
    {"id": "mc-c1-061", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Nguyên tắc sắp xếp",
     "question": "Nguyên tắc cơ bản nhất để sắp xếp các nguyên tố trong Bảng tuần hoàn hiện đại là gì?",
     "choices": ["Theo chiều tăng dần của điện tích hạt nhân nguyên tử (số hiệu nguyên tử Z)", "Theo chiều tăng dần của nguyên tử khối", "Theo thứ tự bảng chữ cái tên nguyên tố", "Theo trạng thái tồn tại ở điều kiện thường (rắn, lỏng, khí)"],
     "answer": 0, "explanation": "Ban đầu Mendeleev xếp theo nguyên tử khối, nhưng bảng tuần hoàn hiện đại được xếp theo chiều tăng dần của ĐIỆN TÍCH HẠT NHÂN (số Z)."},
    {"id": "mc-c1-062", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Nguyên tắc nhóm",
     "question": "Các nguyên tố được xếp vào cùng một nhóm (cột dọc) trong bảng tuần hoàn thường có đặc điểm gì chung?",
     "choices": ["Có cấu hình electron lớp ngoài cùng tương tự nhau, dẫn đến tính chất hóa học tương tự nhau", "Có cùng số lớp electron", "Có cùng số hạt nơtron", "Có cùng số electron tổng cộng"],
     "answer": 0, "explanation": "Các nguyên tố trong cùng nhóm A có cùng số electron hóa trị (thường là e ngoài cùng), làm cho chúng có tính chất hóa học tương tự nhau."},
    {"id": "mc-c1-063", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Ý nghĩa ô nguyên tố",
     "question": "Số thứ tự của ô nguyên tố trong bảng tuần hoàn KHÔNG cho biết thông tin nào sau đây?",
     "choices": ["Số hạt neutron trong hạt nhân", "Số hiệu nguyên tử (Z)", "Số electron trong nguyên tử", "Số điện tích hạt nhân (số proton)"],
     "answer": 0, "explanation": "Số thứ tự ô = Số Z = Số proton = Số electron. Không liên quan trực tiếp đến số neutron (tùy thuộc vào đồng vị)."},
    {"id": "mc-c1-064", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bài tập tìm ô nguyên tố",
     "question": "Nguyên tử của nguyên tố X có tổng số hạt cơ bản là 28. Số hạt không mang điện bằng 10. X nằm ở ô số mấy trong Bảng tuần hoàn?",
     "choices": ["Ô số 9", "Ô số 10", "Ô số 18", "Ô số 19"],
     "answer": 0, "explanation": "$2Z + N = 28$. $N = 10$. Suy ra $2Z = 18 \Rightarrow Z = 9$. Vậy X ở ô số 9 (Fluorine)."},

    # Nhóm 18, 19: Chu kì
    {"id": "mc-c1-065", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Khái niệm chu kì",
     "question": "Chu kì trong bảng tuần hoàn là dãy các nguyên tố mà nguyên tử của chúng có đặc điểm gì chung?",
     "choices": ["Có cùng số lớp electron", "Có cùng số electron ở lớp ngoài cùng", "Có cùng số proton", "Có cùng mức năng lượng cao nhất"],
     "answer": 0, "explanation": "Chu kì là dãy nguyên tố xếp theo chiều tăng điện tích hạt nhân, nguyên tử của chúng có CÙNG SỐ LỚP electron. (Số thứ tự chu kì = số lớp e)."},
    {"id": "mc-c1-066", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Phân loại chu kì",
     "question": "Bảng tuần hoàn hiện nay gồm bao nhiêu chu kì và được phân loại như thế nào?",
     "choices": ["7 chu kì: 3 chu kì nhỏ (1, 2, 3) và 4 chu kì lớn (4, 5, 6, 7)", "8 chu kì: 4 chu kì nhỏ và 4 chu kì lớn", "7 chu kì, tất cả đều là chu kì lớn", "18 chu kì, tương ứng với 18 cột"],
     "answer": 0, "explanation": "BTH có 7 chu kì. Chu kì 1, 2, 3 chứa ít nguyên tố (2, 8, 8) gọi là chu kì nhỏ. Chu kì 4, 5, 6, 7 chứa nhiều nguyên tố (18, 18, 32, 32) gọi là chu kì lớn."},
    {"id": "mc-c1-067", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Cấu hình e theo chu kì",
     "question": "Một nguyên tử có cấu hình electron là $1s^2 2s^2 2p^6 3s^2 3p^4$. Nguyên tố này thuộc chu kì mấy?",
     "choices": ["Chu kì 3", "Chu kì 2", "Chu kì 4", "Chu kì 6"],
     "answer": 0, "explanation": "Cấu hình kết thúc ở lớp n=3 (có 3 lớp electron: lớp 1, lớp 2, lớp 3). Do đó nguyên tố thuộc Chu kì 3."},
    {"id": "mc-c1-068", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Số nguyên tố trong chu kì",
     "question": "Số lượng nguyên tố trong chu kì 2 và chu kì 4 lần lượt là bao nhiêu?",
     "choices": ["8 và 18", "8 và 8", "18 và 18", "2 và 8"],
     "answer": 0, "explanation": "Chu kì 1: 2 nguyên tố. Chu kì 2: 8 nguyên tố (từ Li đến Ne). Chu kì 3: 8 nguyên tố. Chu kì 4: 18 nguyên tố (có thêm 10 nguyên tố d)."},

    # Nhóm 20, 21: Nhóm (Nhóm A, Nhóm B)
    {"id": "mc-c1-069", "chapter": "c1", "lesson": "b5", "level": "nb", "dang": "Cấu tạo nhóm",
     "question": "Bảng tuần hoàn hiện tại được chia thành bao nhiêu cột và bao nhiêu nhóm?",
     "choices": ["18 cột chia thành 8 nhóm A và 8 nhóm B", "18 cột chia thành 18 nhóm A", "8 cột chia thành 8 nhóm A", "7 cột chia thành 7 nhóm"],
     "answer": 0, "explanation": "BTH có 18 cột dọc. Hệ thống nhóm chia thành 8 nhóm A (cột 1,2 và 13-18) và 8 nhóm B (cột 3-12, trong đó nhóm VIIIB chiếm 3 cột)."},
    {"id": "mc-c1-070", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Phân loại nhóm A",
     "question": "Nhóm A (nhóm nguyên tố tiêu biểu) bao gồm các loại nguyên tố nào?",
     "choices": ["Các nguyên tố s và nguyên tố p", "Các nguyên tố d và f", "Chỉ gồm các kim loại", "Chỉ gồm các phi kim"],
     "answer": 0, "explanation": "Nhóm A gồm các nguyên tố họ s (nhóm IA, IIA) và họ p (nhóm IIIA đến VIIIA). Electron hóa trị điền vào s và p."},
    {"id": "mc-c1-071", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Xác định nhóm từ cấu hình",
     "question": "Nguyên tố M có cấu hình electron $[Ne] 3s^2 3p^1$. Vị trí nhóm của M trong bảng tuần hoàn là:",
     "choices": ["Nhóm IIIA", "Nhóm IA", "Nhóm IIIB", "Nhóm IVA"],
     "answer": 0, "explanation": "E cuối cùng ở phân lớp p $\\Rightarrow$ Nhóm A. Số electron lớp ngoài cùng = $2+1 = 3$. Vậy thuộc nhóm IIIA."},
    {"id": "mc-c1-072", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Cấu hình nguyên tố nhóm B",
     "question": "Nguyên tố khối d (kim loại chuyển tiếp, thuộc nhóm B) có đặc điểm cấu hình electron lớp ngoài cùng và sát ngoài cùng thường có dạng:",
     "choices": ["$(n-1)d^{1-10} ns^{1-2}$", "$ns^2 np^{1-6}$", "$nd^{1-10} (n-1)s^2$", "$ns^{1-2}$"],
     "answer": 0, "explanation": "Nguyên tố nhóm B có electron phân bố vào phân lớp d chưa bão hòa của lớp sát ngoài cùng. Cấu hình hóa trị: $(n-1)d^a ns^b$ (ví dụ: $3d^5 4s^1$ hoặc $3d^6 4s^2$)."},

    # Nhóm 22, 23: Bài tập xác định vị trí qua cấu hình
    {"id": "mc-c1-073", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bài toán xác định vị trí",
     "question": "Một nguyên tố X có tổng số hạt mang điện là 32. Vị trí của X trong bảng tuần hoàn là:",
     "choices": ["Ô số 16, chu kì 3, nhóm VIA", "Ô số 32, chu kì 4, nhóm IVA", "Ô số 16, chu kì 3, nhóm VIB", "Ô số 16, chu kì 2, nhóm VIA"],
     "answer": 0, "explanation": "Tổng hạt mang điện $2Z = 32 \Rightarrow Z = 16$. Cấu hình: $1s^2 2s^2 2p^6 3s^2 3p^4$. Có 3 lớp e $\\Rightarrow$ Chu kì 3. Lớp ngoài cùng (lớp 3) có $2+4=6$ e và là nguyên tố p $\\Rightarrow$ Nhóm VIA."},
    {"id": "mc-c1-074", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Tìm Z qua nhóm và chu kì",
     "question": "Nguyên tố Y thuộc chu kì 4, nhóm IIA. Cấu hình electron nguyên tử của Y là:",
     "choices": ["$[Ar] 4s^2$", "$[Ar] 3d^2 4s^2$", "$[Ne] 3s^2 3p^2$", "$[Ar] 4s^2 4p^2$"],
     "answer": 0, "explanation": "Chu kì 4 $\\Rightarrow$ 4 lớp. Nhóm IIA $\\Rightarrow$ nguyên tố s, có 2e ngoài cùng $\\Rightarrow 4s^2$. Trọn vẹn là $[Ar] 4s^2$ (Canxi Z=20). (Nhóm IIB hoặc IVB sẽ có cấu hình d)."},
    {"id": "mc-c1-075", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bài toán tổng Z hai nguyên tố",
     "question": "Hai nguyên tố A và B đứng kế tiếp nhau trong cùng một chu kì của bảng tuần hoàn, có tổng điện tích hạt nhân là 25. Số hiệu nguyên tử của A và B lần lượt là:",
     "choices": ["12 và 13", "11 và 14", "10 và 15", "12,5 và 12,5"],
     "answer": 0, "explanation": "Kế tiếp trong cùng chu kì $\\Rightarrow Z_B - Z_A = 1$ (giả sử B lớn hơn). Và $Z_A + Z_B = 25$. Giải hệ: $2Z_A + 1 = 25 \Rightarrow 2Z_A = 24 \Rightarrow Z_A = 12$ (Magnesium). $Z_B = 13$ (Aluminium)."},
    {"id": "mc-c1-076", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bài toán 2 nguyên tố cùng nhóm",
     "question": "Hai nguyên tố X, Y nằm ở hai chu kì liên tiếp thuộc cùng một nhóm A. Tổng số proton của chúng là 32. Hai nguyên tố đó là:",
     "choices": ["Mg (Z=12) và Ca (Z=20)", "N (Z=7) và Mn (Z=25)", "O (Z=8) và Cr (Z=24)", "Na (Z=11) và Sc (Z=21)"],
     "answer": 0, "explanation": "Cùng nhóm A, 2 chu kì liên tiếp (thường hơn kém nhau 8 hoặc 18, 32 ô). Giả sử chu kì nhỏ: $Z_Y - Z_X = 8$. $Z_Y + Z_X = 32$. Hệ: $2Z_Y = 40 \Rightarrow Z_Y = 20$ (Ca), $Z_X = 12$ (Mg). Hai nguyên tố thuộc nhóm IIA (Mg, Ca)."},

    # Nhóm 24, 25: Sự biến đổi tuần hoàn (Bán kính, Độ âm điện)
    {"id": "mc-c1-077", "chapter": "c1", "lesson": "b6", "level": "nb", "dang": "Bán kính nguyên tử",
     "question": "Trong một chu kì, đi từ trái sang phải theo chiều tăng của điện tích hạt nhân, bán kính nguyên tử các nguyên tố nhóm A biến đổi như thế nào?",
     "choices": ["Giảm dần", "Tăng dần", "Không thay đổi", "Tăng rồi giảm"],
     "answer": 0, "explanation": "Trong 1 chu kì, số lớp e không đổi (bằng nhau), nhưng số proton trong hạt nhân tăng dần $\\Rightarrow$ Lực hút của hạt nhân đối với các e lớp ngoài cùng tăng lên $\\Rightarrow$ Kéo các e lại gần hạt nhân hơn $\\Rightarrow$ Bán kính giảm."},
    {"id": "mc-c1-078", "chapter": "c1", "lesson": "b6", "level": "nb", "dang": "Bán kính trong nhóm",
     "question": "Trong một nhóm A, đi từ trên xuống dưới theo chiều tăng của điện tích hạt nhân, bán kính nguyên tử biến đổi thế nào?",
     "choices": ["Tăng dần", "Giảm dần", "Biến đổi tuần hoàn", "Giữ nguyên"],
     "answer": 0, "explanation": "Trong 1 nhóm A đi xuống, số lớp electron tăng lên (1, 2, 3...) làm cự ly từ hạt nhân ra lớp ngoài cùng xa ra. Dù điện tích hạt nhân cũng tăng nhưng hiệu ứng tăng lớp vỏ chiếm ưu thế $\\Rightarrow$ Bán kính tăng dần."},
    {"id": "mc-c1-079", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Khái niệm Độ âm điện",
     "question": "Độ âm điện của một nguyên tử đặc trưng cho khả năng gì?",
     "choices": ["Khả năng hút electron của nguyên tử đó khi hình thành liên kết hóa học", "Khả năng nhường electron để trở thành ion dương", "Khả năng phát ra bức xạ âm", "Khả năng phản ứng với axit"],
     "answer": 0, "explanation": "Độ âm điện (Electronegativity) là đại lượng đặc trưng cho khả năng hút electron dùng chung về phía mình trong liên kết hóa học. Càng dễ nhận e (phi kim) độ âm điện càng lớn."},
    {"id": "mc-c1-080", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Quy luật độ âm điện",
     "question": "Dựa vào quy luật biến đổi tuần hoàn, nguyên tố nào sau đây có độ âm điện LỚN NHẤT trong bảng tuần hoàn? (Không xét khí hiếm)",
     "choices": ["Fluorine (F)", "Oxygen (O)", "Francium (Fr)", "Chlorine (Cl)"],
     "answer": 0, "explanation": "Độ âm điện tăng từ trái sang phải (đỉnh là nhóm VIIA) và giảm từ trên xuống dưới. Vậy nguyên tố góc trên cùng bên phải (nhóm VIIA, chu kì 2) là Fluorine có độ âm điện lớn nhất (3.98)."},

    # Nhóm 26, 27: Biến đổi Tính kim loại, phi kim
    {"id": "mc-c1-081", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Tính kim loại",
     "question": "Tính kim loại là tính chất của một nguyên tố mà nguyên tử của nó dễ:",
     "choices": ["Nhường electron để trở thành ion dương (cation)", "Nhận electron để trở thành ion âm (anion)", "Góp chung electron với nguyên tử khác", "Hút electron mạnh mẽ"],
     "answer": 0, "explanation": "Tính kim loại $\\sim$ tính khử $\\sim$ dễ nhường (mất) electron hóa trị để đạt cấu hình khí hiếm."},
    {"id": "mc-c1-082", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Quy luật tính kim loại",
     "question": "Trong một chu kì, từ trái sang phải, tính kim loại và tính phi kim biến đổi như thế nào?",
     "choices": ["Tính kim loại giảm dần, tính phi kim tăng dần", "Tính kim loại tăng dần, tính phi kim giảm dần", "Cả hai đều tăng", "Cả hai đều giảm"],
     "answer": 0, "explanation": "Từ trái qua phải, bán kính giảm, lực hút e ngoài cùng tăng $\\Rightarrow$ khó nhường e hơn (tính kim loại giảm) và dễ nhận e hơn (tính phi kim tăng)."},
    {"id": "mc-c1-083", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "So sánh tính phi kim",
     "question": "Cho các nguyên tố: N (Z=7), O (Z=8), P (Z=15). Thứ tự tính phi kim TĂNG DẦN của các nguyên tố trên là:",
     "choices": ["P < N < O", "O < N < P", "N < P < O", "P < O < N"],
     "answer": 0, "explanation": "N và P cùng nhóm VA. Từ trên xuống tính phi kim giảm $\\Rightarrow$ P < N. N và O cùng chu kì 2. Từ trái sang phải tính phi kim tăng $\\Rightarrow$ N < O. Kết hợp lại: P < N < O."},
    {"id": "mc-c1-084", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "So sánh tính kim loại",
     "question": "Cho các kim loại: Na (Z=11), Mg (Z=12), K (Z=19). Thứ tự tính kim loại TĂNG DẦN là:",
     "choices": ["Mg < Na < K", "K < Na < Mg", "Na < Mg < K", "Mg < K < Na"],
     "answer": 0, "explanation": "Na và Mg cùng chu kì 3, Na ở nhóm IA, Mg nhóm IIA $\\Rightarrow$ Na > Mg (tính kim loại giảm từ trái sang phải). Na và K cùng nhóm IA, K ở chu kì dưới $\\Rightarrow$ K > Na (tính kim loại tăng từ trên xuống). Vậy: Mg < Na < K."},

    # Nhóm 28, 29: Hóa trị và Công thức oxit cao nhất
    {"id": "mc-c1-085", "chapter": "c1", "lesson": "b7", "level": "nb", "dang": "Hóa trị cao nhất với Oxi",
     "question": "Đối với các nguyên tố nhóm A, hóa trị cao nhất trong hợp chất với oxygen có mối liên hệ thế nào với số thứ tự nhóm?",
     "choices": ["Bằng số thứ tự nhóm (từ nhóm IA đến VIIA, trừ F, O)", "Bằng 8 trừ đi số thứ tự nhóm", "Bằng số lớp electron", "Luôn bằng 2"],
     "answer": 0, "explanation": "Hóa trị cao nhất với oxygen của nguyên tố nhóm A bằng đúng số thứ tự của nhóm (tương ứng số electron hóa trị)."},
    {"id": "mc-c1-086", "chapter": "c1", "lesson": "b7", "level": "th", "dang": "Công thức Oxit cao nhất",
     "question": "Nguyên tố R thuộc nhóm VA. Công thức oxide cao nhất của R là:",
     "choices": ["$R_2O_5$", "$RO_3$", "$R_2O_3$", "$RO_2$"],
     "answer": 0, "explanation": "Nhóm VA $\\Rightarrow$ hóa trị cao nhất với O là V. Oxi hóa trị II. Lập công thức chéo hóa trị: $R_2O_5$."},
    {"id": "mc-c1-087", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Công thức hợp chất khí với Hidro",
     "question": "Nguyên tố R thuộc nhóm VIA. Công thức hợp chất khí với hydrogen của R là:",
     "choices": ["$H_2R$", "$HR$", "$RH_3$", "$RH_4$"],
     "answer": 0, "explanation": "Đối với phi kim (nhóm IVA đến VIIA), hóa trị với Hydrogen = 8 - số thứ tự nhóm. Nhóm VIA $\\Rightarrow$ hóa trị với H là 8 - 6 = 2 (II). Hóa trị của H là I. Công thức là $H_2R$ (hoặc $RH_2$, vd $H_2S$, $H_2O$)."},
    {"id": "mc-c1-088", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Bài toán xác định nguyên tố qua % khối lượng",
     "question": "Hợp chất khí với hydrogen của nguyên tố R có công thức $RH_3$. Trong hợp chất oxide cao nhất của R, oxygen chiếm 74,07% về khối lượng. R là nguyên tố nào?",
     "choices": ["Nitrogen (N = 14)", "Phosphorus (P = 31)", "Arsenic (As = 75)", "Carbon (C = 12)"],
     "answer": 0, "explanation": "Công thức với H là $RH_3 \Rightarrow$ R có hóa trị III với H $\\Rightarrow$ R thuộc nhóm VA (8-3=5). Oxit cao nhất là $R_2O_5$. %O $= \frac{16 \\times 5}{2R + 16 \\times 5} \times 100 = 74,07\\%$. Giải ra: $80 / (2R + 80) = 0,7407 \Rightarrow 80 = 1,4814 R + 59,256 \Rightarrow 1,4814 R = 20,744 \Rightarrow R \approx 14$. Đó là Nitrogen (N)."},

    # Nhóm 30: Định luật tuần hoàn và Tổng hợp
    {"id": "mc-c1-089", "chapter": "c1", "lesson": "b7", "level": "nb", "dang": "Định luật tuần hoàn",
     "question": "Nội dung của định luật tuần hoàn các nguyên tố hóa học là:",
     "choices": ["Tính chất của các nguyên tố và đơn chất cũng như thành phần, tính chất của hợp chất tạo nên từ các nguyên tố đó biến đổi tuần hoàn theo chiều tăng của điện tích hạt nhân", "Tính chất biến đổi tuần hoàn theo chiều tăng của nguyên tử khối", "Tính chất biến đổi phụ thuộc vào số neutron", "Tính chất của nguyên tố chỉ do số lớp electron quyết định"],
     "answer": 0, "explanation": "Định luật tuần hoàn hiện đại do Moseley và các nhà vật lí chứng minh: Điểm cốt lõi là sự tuần hoàn của cấu hình electron ngoài cùng phụ thuộc vào ĐIỆN TÍCH HẠT NHÂN (số Z)."},
    {"id": "mc-c1-090", "chapter": "c1", "lesson": "b7", "level": "th", "dang": "Quy luật tính axit/bazo",
     "question": "Theo chu kì từ trái sang phải, tính acid - base của các oxide và hydroxide biến đổi như thế nào?",
     "choices": ["Tính base giảm dần, tính acid tăng dần", "Tính base tăng dần, tính acid giảm dần", "Tính acid và tính base đều tăng", "Chỉ có tính acid biến đổi"],
     "answer": 0, "explanation": "Trái sang phải tính kim loại giảm $\\Rightarrow$ tính base giảm (VD: $NaOH$ base mạnh $\\rightarrow$ $Mg(OH)_2$ base yếu). Tính phi kim tăng $\\Rightarrow$ tính acid tăng (VD: $H_3PO_4$ acid trung bình $\\rightarrow$ $H_2SO_4$ acid mạnh $\\rightarrow$ $HClO_4$ siêu acid)."},
    {"id": "mc-c1-091", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Sắp xếp tính bazo",
     "question": "Cho các hydroxide: $NaOH, Mg(OH)_2, Al(OH)_3$. Thứ tự tính base GIẢM DẦN là:",
     "choices": ["$NaOH > Mg(OH)_2 > Al(OH)_3$", "$Al(OH)_3 > Mg(OH)_2 > NaOH$", "$Mg(OH)_2 > NaOH > Al(OH)_3$", "Chúng có tính base bằng nhau"],
     "answer": 0, "explanation": "Na, Mg, Al thuộc cùng chu kì 3 (Z=11, 12, 13). Từ trái qua phải tính kim loại giảm $\\Rightarrow$ tính base giảm. Vậy lớn nhất là NaOH (kiềm mạnh), yếu nhất là Al(OH)3 (lưỡng tính)."},
    {"id": "mc-c1-092", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Bài tập tổng hợp R",
     "question": "Nguyên tố R tạo hợp chất oxide cao nhất là $RO_3$. Biết trong hợp chất với hydrogen, R chiếm 94,12% về khối lượng. Nguyên tố R là:",
     "choices": ["Sulfur (S=32)", "Selenium (Se=79)", "Oxygen (O=16)", "Carbon (C=12)"],
     "answer": 0, "explanation": "Oxit cao nhất $RO_3 \Rightarrow$ Hóa trị cao nhất với O là VI $\\Rightarrow$ Thuộc nhóm VIA. Hợp chất khí với H là $RH_2$ (hoặc $H_2R$). %R $= \frac{R}{R + 2} \times 100 = 94,12\\% \Rightarrow \frac{R}{R+2} = 0,9412 \Rightarrow R = 0,9412 R + 1,8824 \Rightarrow 0,0588 R = 1,8824 \Rightarrow R = 32$. Lưu huỳnh (S)."},

    # Các câu 93 - 120 (Mở rộng rèn luyện kỹ năng chương 1)
    {"id": "mc-c1-093", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Lý thuyết Hạt nhân",
     "question": "Phát biểu nào sau đây SAI khi nói về cấu tạo nguyên tử?",
     "choices": ["Đồng vị là các nguyên tử có cùng số proton và cùng số khối", "Số hiệu nguyên tử Z bằng số proton và bằng số electron ở nguyên tử trung hòa", "Khối lượng nguyên tử coi như bằng khối lượng hạt nhân", "Đường kính nguyên tử lớn hơn đường kính hạt nhân hàng vạn lần"],
     "answer": 0, "explanation": "Đồng vị là cùng số proton (Z) nhưng KHÁC SỐ NEUTRON (N), dẫn đến KHÁC SỐ KHỐI (A)."},
    {"id": "mc-c1-094", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Toán hỗn hợp đồng vị",
     "question": "Cho hai đồng vị của Hydrogen là $^1_1H$ (99%) và $^2_1H$ (1%). Số lượng nguyên tử $^2_1H$ có trong 1 mol nước ($H_2O$) là khoảng bao nhiêu? (Biết $N_A = 6,022\\cdot 10^{23}$)",
     "choices": ["$1,2\\cdot 10^{22}$ nguyên tử", "$6,022\\cdot 10^{21}$ nguyên tử", "$1,2\\cdot 10^{21}$ nguyên tử", "$6,022\\cdot 10^{23}$ nguyên tử"],
     "answer": 0, "explanation": "Trong 1 mol H2O có 2 mol nguyên tử H. Số lượng nguyên tử H tổng cộng là $2 \times N_A = 12,044\\cdot 10^{23}$. Số nguyên tử $^2H$ (chiếm 1%) = $0.01 \times 12,044\\cdot 10^{23} = 0,12044\\cdot 10^{23} = 1,2044\\cdot 10^{22}$ nguyên tử."},
    
    {"id": "mc-c1-095", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Cấu hình phức tạp",
     "question": "Cho các cấu hình electron: (X) $1s^2 2s^2 2p^6 3s^2 3p^6 4s^1$; (Y) $1s^2 2s^2 2p^6 3s^2 3p^6 3d^5 4s^1$; (Z) $1s^2 2s^2 2p^6 3s^2 3p^5$. Số nguyên tố là kim loại là:",
     "choices": ["2", "1", "3", "0"],
     "answer": 0, "explanation": "X (4s1): Potassium (K) kim loại kiềm. Y (3d5 4s1): Chromium (Cr) kim loại chuyển tiếp. Z (3s2 3p5): Chlorine (Cl) phi kim nhóm VIIA. Vậy có 2 kim loại."},
    {"id": "mc-c1-096", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Định vị theo hạt",
     "question": "Ion $X^{3+}$ có cấu hình electron phân lớp ngoài cùng là $2p^6$. Vị trí của X trong bảng tuần hoàn là:",
     "choices": ["Chu kì 3, nhóm IIIA", "Chu kì 2, nhóm VIIIA", "Chu kì 3, nhóm VA", "Chu kì 2, nhóm IIIA"],
     "answer": 0, "explanation": "Ion $X^{3+}$ có cấu hình $1s^2 2s^2 2p^6$ (10e). Nó đã nhường 3e, nên nguyên tử X có $10+3=13$ e. Cấu hình X: $1s^2 2s^2 2p^6 3s^2 3p^1$. (Nhôm). Vị trí: Chu kì 3, nhóm IIIA."},
    
    {"id": "mc-c1-097", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Xu hướng độ âm điện",
     "question": "Cấu hình electron của 4 nguyên tố: P ($1s^2 2s^2 2p^6 3s^2 3p^1$); Q ($1s^2 2s^2 2p^6 3s^2$); R ($1s^2 2s^2 2p^5$); T ($1s^2 2s^2 2p^6$). Thứ tự giảm dần độ âm điện là:",
     "choices": ["R > P > Q > T", "T > R > P > Q", "R > Q > P > T", "T > Q > P > R"],
     "answer": 0, "explanation": "T là khí hiếm Neon (không tham gia liên kết, độ âm điện ~ 0 trong thang đo Pauling phổ thông). R là F (chiều cao nhất). P là Al (chu kì 3, nhóm IIIA). Q là Mg (chu kì 3, nhóm IIA). P (Al) > Q (Mg). Vậy R > P > Q > T."},
    {"id": "mc-c1-098", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Oxide cao nhất 2",
     "question": "Hợp chất khí với hydrogen của nguyên tố R là $RH_4$. Oxit cao nhất của nó chứa 53,3% oxygen về khối lượng. R là:",
     "choices": ["Si (28)", "C (12)", "Sn (119)", "Pb (207)"],
     "answer": 0, "explanation": "$RH_4 \Rightarrow$ Hóa trị H là 4 $\Rightarrow$ Hóa trị O là 8-4=4. Oxide cao nhất là $RO_2$. %O = $32 / (R+32) = 0.533 \Rightarrow R+32 = 32 / 0.533 = 60 \Rightarrow R = 28$. Đó là Silicon (Si)."},
    
    {"id": "mc-c1-099", "chapter": "c1", "lesson": "b4", "level": "th", "dang": "Đặc điểm AO",
     "question": "Nhận định nào sau đây là ĐÚNG khi nói về phân lớp d?",
     "choices": ["Phân lớp d xuất hiện bắt đầu từ lớp thứ 3 ($n=3$)", "Phân lớp d chứa tối đa 14 electron", "Phân lớp d có hình cầu", "Phân lớp d có 3 orbital"],
     "answer": 0, "explanation": "Lớp 1 chỉ có s. Lớp 2 có s, p. Lớp 3 có s, p, d. Lớp 4 có s, p, d, f. Vậy phân lớp d bắt đầu có từ n=3 (3d). Nó có 5 AO, chứa tối đa 10e."},
    {"id": "mc-c1-100", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Tính khối lượng thực",
     "question": "Khối lượng tuyệt đối của một nguyên tử O (Z=8, A=16) xấp xỉ bằng bao nhiêu gam? (Biết $1\\text{ amu} = 1,6605\\cdot 10^{-24}\\text{ g}$)",
     "choices": ["$26,568\\cdot 10^{-24}\\text{ g}$", "$16\\text{ g}$", "$13,28\\cdot 10^{-24}\\text{ g}$", "$8\\cdot 10^{-24}\\text{ g}$"],
     "answer": 0, "explanation": "Khối lượng nguyên tử $\\approx$ Số khối A $\times 1$ amu. $16 \\times 1,6605\\cdot 10^{-24} = 26,568\\cdot 10^{-24}\\text{ g}$."},
    
    {"id": "mc-c1-101", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Nhận biết qua e",
     "question": "Ion $Y^{2-}$ có tổng số electron là 18. Nguyên tố Y thuộc loại nguyên tố nào?",
     "choices": ["Phi kim", "Kim loại", "Khí hiếm", "Kim loại chuyển tiếp"],
     "answer": 0, "explanation": "$Y^{2-}$ có 18e $\\Rightarrow$ Y có 16e (Z=16). Cấu hình: $1s^2 2s^2 2p^6 3s^2 3p^4$. Lớp ngoài có 6e $\\Rightarrow$ Phi kim (Lưu huỳnh - S)."},
    {"id": "mc-c1-102", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Số lớp phân lớp",
     "question": "Nguyên tố Z=29 (Cu) có bao nhiêu lớp electron và bao nhiêu phân lớp electron có chứa electron?",
     "choices": ["4 lớp, 7 phân lớp", "4 lớp, 6 phân lớp", "3 lớp, 6 phân lớp", "4 lớp, 8 phân lớp"],
     "answer": 0, "explanation": "Cấu hình: $1s^2 | 2s^2 2p^6 | 3s^2 3p^6 3d^{10} | 4s^1$. Gồm 4 lớp (1,2,3,4). Các phân lớp: 1s, 2s, 2p, 3s, 3p, 3d, 4s. Tổng cộng 7 phân lớp có chứa e."},
    {"id": "mc-c1-103", "chapter": "c1", "lesson": "b2", "level": "vd", "dang": "Tỉ lệ đồng vị",
     "question": "Nitơ tự nhiên có 2 đồng vị $^{14}N$ và $^{15}N$. Nguyên tử khối trung bình là 14,0067. Hãy cho biết cứ 10000 nguyên tử Nitơ thì có khoảng bao nhiêu nguyên tử $^{15}N$?",
     "choices": ["67", "9933", "14", "15"],
     "answer": 0, "explanation": "Gọi x là % $^{15}N$. $15x + 14(100-x) = 1400.67 \Rightarrow x = 0.67\\%$. Trong 10,000 nguyên tử thì số hạt $^{15}N$ = $10000 \times 0.67 / 100 = 67$ nguyên tử."},
    
    {"id": "mc-c1-104", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Bán kính ion",
     "question": "Cho các ion/nguyên tử: $Na^+, Mg^{2+}, Ne, F^-$. Chúng đều có cùng cấu hình electron $1s^2 2s^2 2p^6$ (hệ đẳng electron). Thứ tự bán kính GIẢM DẦN là:",
     "choices": ["$F^- > Ne > Na^+ > Mg^{2+}$", "$Mg^{2+} > Na^+ > Ne > F^-$", "$Ne > F^- > Na^+ > Mg^{2+}$", "$F^- > Na^+ > Mg^{2+} > Ne$"],
     "answer": 0, "explanation": "Hệ đẳng electron (cùng số e lớp vỏ, cùng số lớp). Hạt nhân nào có số điện tích (số proton Z) lớn nhất sẽ hút vỏ mạnh nhất $\\Rightarrow$ Bán kính nhỏ nhất. Số proton: $Mg (12) > Na (11) > Ne (10) > F (9)$. Vậy bán kính giảm dần: $F^- > Ne > Na^+ > Mg^{2+}$."},
    {"id": "mc-c1-105", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Tên nhóm",
     "question": "Các nguyên tố nhóm VIIA (F, Cl, Br, I) được gọi tên chung là gì?",
     "choices": ["Halogen", "Kim loại kiềm", "Khí hiếm", "Chalcogen"],
     "answer": 0, "explanation": "Nhóm IA: kim loại kiềm. IIA: kiềm thổ. VIIA: Halogen (sinh ra muối). VIIIA: khí hiếm."},
    
    {"id": "mc-c1-106", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Góc xoay hạt cơ bản",
     "question": "Nguyên tử R có tổng số hạt p, n, e là 115. Số hạt mang điện nhiều hơn số hạt không mang điện là 25. R là nguyên tố:",
     "choices": ["Bromine (Z=35)", "Krypton (Z=36)", "Rubidium (Z=37)", "Strontium (Z=38)"],
     "answer": 0, "explanation": "$2Z + N = 115$. $2Z - N = 25$. Cộng: $4Z = 140 \Rightarrow Z = 35$ (Bromine - Br). $N = 45$."},
    {"id": "mc-c1-107", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Năng lượng Ion hóa",
     "question": "Năng lượng ion hóa thứ nhất ($I_1$) là năng lượng cần thiết để bứt 1 electron từ nguyên tử ở trạng thái cơ bản. Trong một chu kì từ trái sang phải, $I_1$ thường có xu hướng biến đổi thế nào?",
     "choices": ["Tăng dần do bán kính giảm và lực hút hạt nhân tăng", "Giảm dần do bán kính tăng", "Không đổi", "Tăng rồi giảm"],
     "answer": 0, "explanation": "Trái qua phải: bán kính nguyên tử giảm $\\Rightarrow$ electron ngoài cùng bị hút chặt hơn $\\Rightarrow$ cần nhiều năng lượng hơn để bứt nó ra $\\Rightarrow I_1$ tăng dần."},
    
    {"id": "mc-c1-108", "chapter": "c1", "lesson": "b6", "level": "vd", "dang": "Axit có oxi",
     "question": "Cho các axit: $H_2SiO_3, H_3PO_4, H_2SO_4, HClO_4$. Dãy sắp xếp theo thứ tự tính axit TĂNG DẦN là:",
     "choices": ["$H_2SiO_3 < H_3PO_4 < H_2SO_4 < HClO_4$", "$HClO_4 < H_2SO_4 < H_3PO_4 < H_2SiO_3$", "$H_3PO_4 < H_2SiO_3 < H_2SO_4 < HClO_4$", "Không so sánh được vì khác số nguyên tử H"],
     "answer": 0, "explanation": "Các trung tâm Si, P, S, Cl thuộc cùng chu kì 3 (Z=14,15,16,17). Tính phi kim tăng $\\Rightarrow$ tính axit của hydroxit/oxit tương ứng tăng lên. Silixic (yếu) < Photphoric (TB) < Sunfuric (mạnh) < Pecloric (rất mạnh)."},
    {"id": "mc-c1-109", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Bài toán 2 muối",
     "question": "Hòa tan hoàn toàn 4,6 gam một kim loại kiềm M vào nước, thu được 2,479 lít khí $H_2$ ở đktc chuẩn mới ($25^\\circ\\text{C}, 1\\text{ bar}$, 1 mol = 24,79 L). Kim loại M là:",
     "choices": ["Na (23)", "Li (7)", "K (39)", "Rb (85)"],
     "answer": 0, "explanation": "Phương trình: $2M + 2H_2O \\rightarrow 2MOH + H_2$. Số mol $H_2 = 2,479 / 24,79 = 0,1\\text{ mol}$. Số mol M = $2 \times 0,1 = 0,2\\text{ mol}$. Phân tử khối $M = m / n = 4,6 / 0,2 = 23$. Kim loại Natri (Na)."},
    {"id": "mc-c1-110", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Bài toán muối Halogen",
     "question": "Cho 10,8 gam một kim loại R (nhóm IIIA) tác dụng vừa đủ với khí Chlorine, thu được 53,4 gam muối chloride. R là kim loại nào?",
     "choices": ["Al (27)", "Ga (70)", "In (115)", "B (11)"],
     "answer": 0, "explanation": "Bảo toàn khối lượng: m Cl2 = 53,4 - 10,8 = 42,6 gam. n Cl = 42,6 / 35,5 = 1,2 mol. R hóa trị III nên $RCl_3 \Rightarrow n_R = n_{Cl}/3 = 1,2/3 = 0,4\\text{ mol}$. $M_R = 10,8 / 0,4 = 27$. Nhôm (Al)."},

    # 10 Câu cuối củng cố thêm
    {"id": "mc-c1-111", "chapter": "c1", "lesson": "b1", "level": "th", "dang": "Liên hệ Z, N, A",
     "question": "Biết nguyên tử Uranium có kí hiệu $^{235}_{92}U$. Số nơtron trong hạt nhân của nguyên tử này là:",
     "choices": ["143", "92", "235", "327"],
     "answer": 0, "explanation": "$N = A - Z = 235 - 92 = 143$."},
    {"id": "mc-c1-112", "chapter": "c1", "lesson": "b3", "level": "th", "dang": "Lớp vỏ electron",
     "question": "Kí hiệu nào sau đây ĐÚNG cho một phân lớp electron?",
     "choices": ["3d", "2d", "1p", "3f"],
     "answer": 0, "explanation": "Lớp 1 chỉ có 1s. Lớp 2 có 2s, 2p. Lớp 3 có 3s, 3p, 3d. Lớp 4 có 4s, 4p, 4d, 4f. Vậy 2d, 1p, 3f là những phân lớp không tồn tại."},
    {"id": "mc-c1-113", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Spin Hund",
     "question": "Nitrogen ($1s^2 2s^2 2p^3$) có 3 electron độc thân ở phân lớp 2p. Theo quy tắc Hund, chiều spin của 3 electron này có đặc điểm gì?",
     "choices": ["Cùng chiều với nhau (thường mũi tên hướng lên)", "Có 2 electron hướng lên, 1 hướng xuống", "Luân phiên lên, xuống, lên", "Các spin triệt tiêu lẫn nhau thành 0"],
     "answer": 0, "explanation": "Quy tắc Hund: phân bố sao cho tổng spin là cực đại. Tức là các electron độc thân phải có chiều spin song song và cùng chiều (đều $\\uparrow$)."},
    {"id": "mc-c1-114", "chapter": "c1", "lesson": "b5", "level": "th", "dang": "Khối s p d f",
     "question": "Bảng tuần hoàn được chia thành 4 khối nguyên tố s, p, d, f. Nhóm IA và IIA thuộc khối nguyên tố nào?",
     "choices": ["Khối s", "Khối p", "Khối d", "Khối f"],
     "answer": 0, "explanation": "Các nguyên tố nhóm IA, IIA có e cuối cùng điền vào phân lớp ns $\\Rightarrow$ là các nguyên tố s."},
    {"id": "mc-c1-115", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Hóa trị phi kim",
     "question": "Hóa trị của phi kim trong hợp chất với hydrogen (RHx) biến đổi như thế nào trong 1 chu kì từ nhóm IVA đến VIIA?",
     "choices": ["Giảm dần từ IV xuống I", "Tăng dần từ I lên IV", "Giữ nguyên là IV", "Tăng từ IV lên VII"],
     "answer": 0, "explanation": "Công thức: $RH_4, RH_3, H_2R, HR$. Hóa trị với H giảm dần từ 4 (IVA), 3 (VA), 2 (VIA), 1 (VIIA)."},
    {"id": "mc-c1-116", "chapter": "c1", "lesson": "b4", "level": "vd", "dang": "Mối liên hệ p và s",
     "question": "Nguyên tử của nguyên tố X có tổng số electron ở phân lớp s bằng tổng số electron ở phân lớp p. X thuộc nhóm nào?",
     "choices": ["Nhóm VIA (O)", "Nhóm IVA (C)", "Nhóm IIIA (B)", "Nhóm VIIA (F)"],
     "answer": 0, "explanation": "Thử viết cấu hình: $1s^2 2s^2$ (tổng s=4). Phải có 4e ở phân lớp p $\\Rightarrow 2p^4$. Cấu hình $1s^2 2s^2 2p^4$ (Oxygen Z=8). Lớp ngoài có 6e $\\Rightarrow$ Nhóm VIA."},
    {"id": "mc-c1-117", "chapter": "c1", "lesson": "b5", "level": "vd", "dang": "Nguyên tố M",
     "question": "Hợp chất oxit cao nhất của nguyên tố M có dạng $MO_3$. Trong hợp chất khí với hydrogen, hydro chiếm 5,88% về khối lượng. Xác định M.",
     "choices": ["S (32)", "Se (79)", "Te (127)", "Cr (52)"],
     "answer": 0, "explanation": "$MO_3 \Rightarrow$ hóa trị VI. Khí là $H_2M$. %H = $2 / (M+2) = 0.0588 \Rightarrow M+2 = 2 / 0.0588 = 34 \Rightarrow M = 32$. Đó là S."},
    {"id": "mc-c1-118", "chapter": "c1", "lesson": "b6", "level": "th", "dang": "Quy luật bán kính ngược",
     "question": "Theo chu kì 3, các nguyên tố $Na, Mg, Al, Si, P, S, Cl$. Nguyên tố có bán kính nguyên tử NHỎ NHẤT là:",
     "choices": ["Cl", "Na", "Al", "P"],
     "answer": 0, "explanation": "Trong chu kì từ trái qua phải, bán kính giảm dần. Cl nằm ở cuối chu kì (nhóm VIIA) nên bán kính nhỏ nhất (không tính khí hiếm)."},
    {"id": "mc-c1-119", "chapter": "c1", "lesson": "b1", "level": "vd", "dang": "Độ lớn điện tích",
     "question": "Điện tích hạt nhân của nguyên tử Đồng (Cu) là +29. Nếu tính ra Coulomb (C), điện tích này bằng bao nhiêu? (Biết $e = 1,602\cdot 10^{-19}\\text{ C}$)",
     "choices": ["$+4,646\cdot 10^{-18}\\text{ C}$", "$-4,646\cdot 10^{-18}\\text{ C}$", "$+1,602\cdot 10^{-19}\\text{ C}$", "29 C"],
     "answer": 0, "explanation": "Điện tích hạt nhân $= Z \cdot (+e) = 29 \times 1,602\cdot 10^{-19} = 46,458\cdot 10^{-19} = +4,646\cdot 10^{-18}\\text{ C}$."},
    {"id": "mc-c1-120", "chapter": "c1", "lesson": "b7", "level": "vd", "dang": "Sắp xếp tính kim loại nhóm IA",
     "question": "Cho các nguyên tố nhóm IA: Li, Na, K, Rb, Cs. Nguyên tố có tính kim loại (tính khử) MẠNH NHẤT là:",
     "choices": ["Cs", "Li", "Na", "K"],
     "answer": 0, "explanation": "Trong cùng một nhóm A, tính kim loại tăng dần từ trên xuống dưới. (Do bán kính tăng, lực giữ electron ngoài cùng yếu đi). Cs (Caesium) nằm dưới cùng trong các phương án nên mạnh nhất. (Francium phóng xạ ít gặp)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C1 Part 2 written successfully.")
