import json

with open('data/hoa10/questions/mc.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_qs = [
    # --- CHƯƠNG 2 HÓA HỌC 10: LIÊN KẾT HÓA HỌC (Phần 2) ---
    # Nhóm 16, 17: Năng lượng liên kết
    {"id": "mc-c2-061", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Năng lượng liên kết",
     "question": "Đại lượng nào đặc trưng cho độ bền vững của một liên kết hóa học?",
     "choices": ["Năng lượng liên kết ($E_b$)", "Độ âm điện", "Bán kính nguyên tử", "Nhiệt độ sôi"],
     "answer": 0, "explanation": "Năng lượng liên kết ($E_b$) là năng lượng cần thiết để phá vỡ 1 mol liên kết đó ở thể khí. Càng lớn thì liên kết càng bền."},
    {"id": "mc-c2-062", "chapter": "c2", "lesson": "b10", "level": "nb", "dang": "Chiều dài liên kết",
     "question": "Chiều dài liên kết là khoảng cách giữa hai hạt nhân của hai nguyên tử tham gia liên kết. Mối liên hệ giữa số liên kết (đơn, đôi, ba) và chiều dài liên kết là:",
     "choices": ["Liên kết đơn dài nhất, liên kết ba ngắn nhất", "Liên kết ba dài nhất, liên kết đơn ngắn nhất", "Chiều dài của chúng bằng nhau", "Không có quy luật rõ ràng"],
     "answer": 0, "explanation": "Số liên kết tăng (từ đơn lên đôi, ba) làm lực hút giữa các nguyên tử tăng lên, kéo chúng lại gần nhau hơn $\\Rightarrow$ Chiều dài liên kết giảm dần."},
    {"id": "mc-c2-063", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "So sánh E_b",
     "question": "Trong các liên kết $C-C, C=C, C \\equiv C$, liên kết nào có năng lượng liên kết lớn nhất?",
     "choices": ["$C \\equiv C$", "$C=C$", "$C-C$", "Bằng nhau"],
     "answer": 0, "explanation": "Liên kết ba gồm $1\\sigma$ và $2\\pi$. Năng lượng để bẻ gãy cả 3 liên kết này chắc chắn lớn hơn bẻ gãy 2 liên kết (đôi) hoặc 1 liên kết (đơn). ($E_b$ lk ba > lk đôi > lk đơn)."},
    {"id": "mc-c2-064", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Tính năng lượng phản ứng",
     "question": "Biết năng lượng liên kết $H-H$ là 436 kJ/mol, $Cl-Cl$ là 242 kJ/mol, $H-Cl$ là 432 kJ/mol. Để phá vỡ các liên kết của 1 mol $H_2$ và 1 mol $Cl_2$ để phản ứng tạo thành 2 mol $HCl$, biến thiên enthalpy $\\Delta_r H$ xấp xỉ bằng:",
     "choices": ["-186 kJ", "+186 kJ", "-432 kJ", "+864 kJ"],
     "answer": 0, "explanation": "Tổng NL cần phá vỡ: $E(H-H) + E(Cl-Cl) = 436 + 242 = 678\\text{ kJ/mol}$. NL tỏa ra khi tạo 2 mol HCl: $2 \times E(H-Cl) = 2 \times 432 = 864\\text{ kJ/mol}$. $\\Delta H = \\text{Thu} - \\text{Tỏa} = 678 - 864 = -186\\text{ kJ}$."},

    # Nhóm 18, 19: Tính phân cực của PHÂN TỬ
    {"id": "mc-c2-065", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Phân cực phân tử 1",
     "question": "Phân tử nào sau đây chứa liên kết cộng hóa trị phân cực, nhưng toàn bộ phân tử lại KHÔNG PHÂN CỰC?",
     "choices": ["$CO_2$", "$H_2O$", "$NH_3$", "$HCl$"],
     "answer": 0, "explanation": "Liên kết C=O phân cực. Nhưng $CO_2$ có cấu tạo đường thẳng (O=C=O), hai moment lưỡng cực hướng ngược chiều nhau triệt tiêu lẫn nhau $\\Rightarrow$ phân tử $CO_2$ không phân cực."},
    {"id": "mc-c2-066", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Phân cực phân tử tứ diện",
     "question": "Phân tử $CCl_4$ (Carbon tetrachloride) là một dung môi không phân cực. Điều này được giải thích bởi:",
     "choices": ["Sự đối xứng hình tứ diện đều của 4 liên kết C-Cl làm triệt tiêu các moment lưỡng cực liên kết", "Bởi vì độ âm điện của C và Cl bằng nhau", "Vì phân tử này không có liên kết hóa học", "Vì nó là chất lỏng ở điều kiện thường"],
     "answer": 0, "explanation": "C lai hóa sp3 $\\Rightarrow$ hình tứ diện đều. Bốn vector moment lưỡng cực C-Cl cân bằng và triệt tiêu nhau, tổng bằng 0."},
    {"id": "mc-c2-067", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Góc liên kết và phân cực",
     "question": "Tại sao phân tử $H_2O$ lại phân cực, trong khi $BeCl_2$ (khí) lại không phân cực?",
     "choices": ["Do $H_2O$ có hình chữ V (góc $104,5^\\circ$) nên các vector lưỡng cực không triệt tiêu, còn $BeCl_2$ có hình đường thẳng nên triệt tiêu", "Do liên kết H-O phân cực, còn Be-Cl không phân cực", "Do nước ở thể lỏng, $BeCl_2$ ở thể khí", "Do nguyên tử Oxi lớn hơn Be"],
     "answer": 0, "explanation": "Hình học phân tử quyết định sự phân cực toàn phần. Nước dạng góc (không đối xứng trung tâm) $\\Rightarrow$ phân cực. $BeCl_2$ đường thẳng (đối xứng) $\\Rightarrow$ không phân cực."},
    {"id": "mc-c2-068", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Moment lưỡng cực",
     "question": "Hợp chất nào sau đây có moment lưỡng cực ($\\mu$) lớn hơn 0?",
     "choices": ["$NH_3$", "$CH_4$", "$BF_3$", "$N_2$"],
     "answer": 0, "explanation": "$CH_4$ (tứ diện đều), $BF_3$ (tam giác đều), $N_2$ (đơn chất đối xứng) đều có $\\mu = 0$. $NH_3$ có chóp tam giác (do 1 cặp e tự do trên N) $\\Rightarrow$ bất đối xứng $\\Rightarrow \\mu > 0$ (phân cực)."},

    # Nhóm 20, 21: Liên kết cho - nhận nâng cao
    {"id": "mc-c2-069", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Cho - nhận Ion",
     "question": "Trong ion Amoni ($NH_4^+$), có mấy liên kết cộng hóa trị phân cực và mấy liên kết cho nhận?",
     "choices": ["4 liên kết cộng hóa trị phân cực, trong đó có 1 liên kết cho nhận từ N sang $H^+$", "3 liên kết cộng hóa trị, 1 liên kết ion", "4 liên kết cho nhận", "2 liên kết cộng hóa trị, 2 liên kết cho nhận"],
     "answer": 0, "explanation": "$NH_3$ có 3 liên kết N-H và 1 cặp e tự do trên N. Nó dùng cặp e này để liên kết với $H^+$ (không có electron nào) tạo liên kết $N \\rightarrow H^+$. Tổng cộng có 4 lk, nhưng trong đó có 1 lk cho nhận (sau khi tạo thành, 4 lk này tương đương nhau)."},
    {"id": "mc-c2-070", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Cho - nhận trong HNO3",
     "question": "Phân tử acid Nitric ($HNO_3$) có chứa các loại liên kết nào? (Theo quy tắc Octet cổ điển)",
     "choices": ["1 liên kết đơn O-H, 1 lk đơn N-O, 1 lk đôi N=O và 1 liên kết cho nhận $N \\rightarrow O$", "3 liên kết đôi N=O", "Toàn bộ là liên kết ion", "2 liên kết đôi N=O và 1 lk đơn N-O"],
     "answer": 0, "explanation": "Theo octet, N tối đa 8e. CTCT: $H-O-NO_2$. Xung quanh N: 1 lk đơn N-O (với nhóm OH), 1 lk đôi N=O, và 1 lk cho nhận $N \\rightarrow O$. Lúc này N vừa tròn 8e."},
    {"id": "mc-c2-071", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Ozone",
     "question": "Trong phân tử Ozone ($O_3$), liên kết giữa nguyên tử Oxi trung tâm với 2 nguyên tử Oxi ở hai bên gồm:",
     "choices": ["Một liên kết đôi (O=O) và một liên kết cho nhận ($O \\rightarrow O$)", "Hai liên kết đôi", "Hai liên kết đơn", "Một liên kết ion và một liên kết cộng hóa trị"],
     "answer": 0, "explanation": "Oxi trung tâm (6e) tạo 1 lk đôi O=O (dùng 2e), đạt 8e. Còn dư 1 cặp e tự do (thực tế là 2), nó dùng 1 cặp tạo liên kết cho-nhận với nguyên tử O thứ ba: $O=O \\rightarrow O$."},
    {"id": "mc-c2-072", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Năng lượng cho - nhận",
     "question": "Liên kết cho - nhận khác liên kết cộng hóa trị thường ở điểm nào BẢN CHẤT nhất trong quá trình HÌNH THÀNH?",
     "choices": ["Nguồn gốc của cặp electron dùng chung", "Sức mạnh của liên kết sau khi hình thành", "Độ dài liên kết", "Sự phân cực"],
     "answer": 0, "explanation": "Sự khác biệt chỉ ở nguồn gốc tạo thành: Lk CHT thường thì mỗi bên góp 1e; còn lk cho-nhận thì 1 bên cung cấp cả 2e. Sau khi tạo thành, tính chất (chiều dài, năng lượng) của nó giống hệt liên kết CHT thường tương ứng."},

    # Nhóm 22, 23: Sự xen phủ mở rộng
    {"id": "mc-c2-073", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Phân biệt Sigma s-p",
     "question": "Liên kết $\\sigma$ trong phân tử $HCl$ được hình thành do sự xen phủ của các orbital nào?",
     "choices": ["Orbital s của H và orbital p của Cl", "Orbital s của H và orbital s của Cl", "Orbital p của H và orbital p của Cl", "Orbital s của H và orbital d của Cl"],
     "answer": 0, "explanation": "H chỉ có $1s^1$ (hình cầu). Cl (nhóm VIIA) có e độc thân ở AO 3p. Sự xen phủ s - p dọc theo trục liên kết tạo ra lk $\\sigma$ trong HCl."},
    {"id": "mc-c2-074", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Xen phủ p-p",
     "question": "Phân tử $Cl_2$ được hình thành do sự xen phủ:",
     "choices": ["Trục của hai orbital p (p-p)", "Bên của hai orbital p (p-p)", "Của hai orbital s", "Của orbital s và orbital p"],
     "answer": 0, "explanation": "Mỗi nguyên tử Cl có 1 e độc thân trên phân lớp 3p. Hai AO p này tiến lại gần nhau và xen phủ dọc theo trục $\\Rightarrow$ tạo liên kết $\\sigma$ (xen phủ trục p-p)."},
    {"id": "mc-c2-075", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Xen phủ trong N2",
     "question": "Trong phân tử $N_2$ có liên kết ba. Các liên kết này được hình thành từ những sự xen phủ nào của các orbital 2p?",
     "choices": ["1 xen phủ trục (tạo $1\\sigma$) và 2 xen phủ bên (tạo $2\\pi$)", "3 xen phủ trục (tạo $3\\sigma$)", "3 xen phủ bên (tạo $3\\pi$)", "1 xen phủ bên và 2 xen phủ trục"],
     "answer": 0, "explanation": "N có 3 electron độc thân trên $p_x, p_y, p_z$. Chỉ có 1 cặp AO (vd $p_x$) xen phủ trục được. 2 cặp AO còn lại ($p_y$ và $p_z$) vuông góc với trục liên kết nên phải xen phủ bên $\\Rightarrow 1\\sigma + 2\\pi$."},
    {"id": "mc-c2-076", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Sự tự do xoay trục",
     "question": "Tại sao các phân tử có liên kết đơn ($\\sigma$) có thể xoay tự do quanh trục liên kết, trong khi liên kết đôi (có chứa $\\pi$) thì không thể?",
     "choices": ["Vì liên kết $\\pi$ được tạo bởi sự xen phủ bên, nếu xoay quanh trục thì vùng xen phủ này sẽ bị đứt gãy", "Vì liên kết $\\pi$ mạnh hơn liên kết $\\sigma$", "Vì liên kết $\\sigma$ có kích thước lớn hơn", "Vì liên kết đôi có khối lượng lớn hơn"],
     "answer": 0, "explanation": "Chính xác, xen phủ bên $\\pi$ cản trở sự xoay tự do quanh trục, dẫn đến hiện tượng đồng phân hình học (cis-trans)."},

    # Nhóm 24, 25: Mở rộng Hình học phân tử (VSEPR)
    {"id": "mc-c2-077", "chapter": "c2", "lesson": "b11", "level": "th", "dang": "Dự đoán lai hóa",
     "question": "Trong phân tử Ammoniac ($NH_3$), nguyên tử N ở trạng thái lai hóa gì?",
     "choices": ["$sp^3$", "$sp^2$", "$sp$", "Không lai hóa"],
     "answer": 0, "explanation": "N liên kết với 3 nguyên tử H và còn 1 cặp e chưa liên kết (tổng cộng 4 vùng mật độ electron) $\\Rightarrow$ Lai hóa $sp^3$."},
    {"id": "mc-c2-078", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Góc liên kết NH3",
     "question": "Góc liên kết H-N-H trong $NH_3$ là bao nhiêu và hình học của phân tử là gì?",
     "choices": ["$\sim 107^\\circ$, hình chóp tam giác", "$\sim 109,5^\\circ$, hình tứ diện", "$120^\\circ$, hình tam giác phẳng", "$104,5^\\circ$, hình góc"],
     "answer": 0, "explanation": "Lai hóa $sp^3$ (lý thuyết là $109.5^\\circ$). Tuy nhiên N có 1 cặp e tự do, nó đẩy mạnh hơn cặp e liên kết nên góc bị ép lại còn khoảng $107^\\circ$. Hình dạng là chóp tam giác (Pyramidal)."},
    {"id": "mc-c2-079", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Phân biệt VSEPR",
     "question": "Sử dụng thuyết VSEPR, phân tử $SO_2$ có hình dạng gì?",
     "choices": ["Hình góc (chữ V)", "Hình đường thẳng", "Hình chóp", "Hình tam giác phẳng"],
     "answer": 0, "explanation": "Nguyên tử trung tâm S có: 1 liên kết đôi, 1 liên kết cho-nhận, và 1 cặp e tự do. Tính số cặp e hóa trị theo VSEPR là $AX_2E_1$ (2 nguyên tử phối trí, 1 cặp e tự do) $\\Rightarrow$ hình góc (bent/V-shaped)."},
    {"id": "mc-c2-080", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Lai hóa trong hydrocarbon",
     "question": "Trong phân tử Ethene ($CH_2=CH_2$), hai nguyên tử Carbon ở trạng thái lai hóa gì?",
     "choices": ["$sp^2$", "$sp^3$", "$sp$", "$sp^3d$"],
     "answer": 0, "explanation": "Mỗi nguyên tử C tạo 1 nối đôi (với C) và 2 nối đơn (với 2 H). Tổng cộng 3 vùng không gian (không còn e tự do) $\\Rightarrow$ Lai hóa $sp^2$ (phẳng, góc $\sim 120^\\circ$)."},

    # Nhóm 26, 27: Hợp chất phức tạp
    {"id": "mc-c2-081", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Lỗi octet",
     "question": "Phân tử nào sau đây có tổng số electron hóa trị ở dạng số lẻ (gốc tự do) không thể tuân thủ quy tắc octet?",
     "choices": ["$NO$ (Nitrogen monoxide)", "$CO_2$", "$N_2O$", "$SO_2$"],
     "answer": 0, "explanation": "N có 5e hóa trị, O có 6e hóa trị. Phân tử NO có tổng cộng $5 + 6 = 11$ electron hóa trị. Đây là số lẻ nên không thể nào nhóm thành các cặp 8e. ($NO$ là gốc tự do)."},
    {"id": "mc-c2-082", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Viết Lewis CO",
     "question": "Trong phân tử Carbon monoxide ($CO$), liên kết giữa C và O là:",
     "choices": ["Một liên kết ba (chứa 1 liên kết cho nhận $O \\rightarrow C$)", "Một liên kết đôi (C=O)", "Một liên kết đơn", "Một liên kết ion"],
     "answer": 0, "explanation": "C (4e) và O (6e). Nếu tạo lk đôi, C mới có 6e, O có 8e (C bị thiếu). Do đó O dùng 1 cặp e tự do để tạo thêm 1 lk cho nhận cho C $\\Rightarrow$ Tạo thành liên kết ba $C \\equiv O$, trong đó 1 lk là phối trí. Cả C và O đều đạt 8e."},
    {"id": "mc-c2-083", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Loại liên kết trong Na2SO4",
     "question": "Trong hợp chất $Na_2SO_4$, tồn tại các loại liên kết hóa học nào?",
     "choices": ["Liên kết ion và liên kết cộng hóa trị", "Chỉ có liên kết ion", "Chỉ có liên kết cộng hóa trị", "Liên kết kim loại và liên kết ion"],
     "answer": 0, "explanation": "Giữa ion $Na^+$ và ion $SO_4^{2-}$ là liên kết ion. Nhưng BÊN TRONG ion đa nguyên tử $SO_4^{2-}$, giữa S và các nguyên tử O là các liên kết cộng hóa trị (và cho-nhận)."},
    {"id": "mc-c2-084", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Loại liên kết trong tinh thể",
     "question": "Trong tinh thể băng đá ($H_2O$), có mặt những loại liên kết nào?",
     "choices": ["Liên kết cộng hóa trị phân cực (bên trong phân tử) và liên kết hydrogen (giữa các phân tử)", "Liên kết ion và tương tác van der Waals", "Chỉ có liên kết hydrogen", "Chỉ có liên kết cộng hóa trị"],
     "answer": 0, "explanation": "Bên trong 1 phân tử $H_2O$ là lk cộng hóa trị H-O phân cực. Các phân tử $H_2O$ nối với nhau tạo tinh thể đá bằng mạng liên kết hydrogen."},

    # Nhóm 28, 29: Tương tác liên phân tử mở rộng
    {"id": "mc-c2-085", "chapter": "c2", "lesson": "b13", "level": "th", "dang": "Tương tác VDW mạnh yếu",
     "question": "Yếu tố nào KHÔNG LÀM TĂNG cường độ của tương tác van der Waals giữa các phân tử?",
     "choices": ["Độ đối xứng của mạng tinh thể ion", "Sự tăng kích thước phân tử (khối lượng, thể tích đám mây e)", "Hình dạng phân tử (phân tử thẳng tương tác mạnh hơn phân tử nhánh do diện tích tiếp xúc lớn)", "Sự có mặt của các liên kết CHT phân cực trong phân tử (lưỡng cực vĩnh viễn)"],
     "answer": 0, "explanation": "Tương tác VDW chỉ áp dụng cho các phân tử. Yếu tố 1 thuộc về mạng lưới liên kết ion (rất mạnh), không liên quan đến lực liên phân tử yếu VDW."},
    {"id": "mc-c2-086", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Ứng dụng Liên kết H",
     "question": "Nhờ đặc điểm nào của liên kết Hydrogen mà hai mạch của phân tử DNA (ADN) có thể liên kết với nhau tạo cấu trúc xoắn kép?",
     "choices": ["Liên kết Hydrogen vừa đủ mạnh để giữ 2 mạch lại với nhau, nhưng đủ yếu để có thể tách ra dễ dàng khi DNA nhân đôi", "Vì nó là liên kết mạnh nhất trong hóa học", "Vì nó là liên kết cộng hóa trị", "Vì nó tạo ra dòng điện tĩnh"],
     "answer": 0, "explanation": "DNA gồm 2 mạch poolynucleotide nối bằng các lk H giữa các base nitơ (A=T có 2 lk, G$\\equiv$C có 3 lk). Lk H không quá mạnh, cho phép enzyme dễ dàng tách 2 mạch ra khi sao chép gen."},
    {"id": "mc-c2-087", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Lực phân cực và không phân cực",
     "question": "Trong 3 loại tương tác van der Waals: (1) Lưỡng cực - lưỡng cực, (2) Lưỡng cực - cảm ứng, (3) Khuếch tán (London). Lực nào tồn tại ở MỌI LOẠI phân tử (kể cả không phân cực như $CH_4$)?",
     "choices": ["Lực khuếch tán (Lực London)", "Lực lưỡng cực - lưỡng cực", "Lực lưỡng cực - cảm ứng", "Không có lực nào"],
     "answer": 0, "explanation": "Lực London (khuếch tán / phân tán) sinh ra do sự thăng giáng của đám mây e tạo lưỡng cực tạm thời. Dù phân tử có đối xứng 100% (như He, CH4) thì trong khoảnh khắc $10^{-15}$ s đám mây e vẫn có thể lệch, tạo lưỡng cực tạm thời. Do đó nó tồn tại ở mọi chất."},
    {"id": "mc-c2-088", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Đồng phân H-bond",
     "question": "o-Nitrophenol có nhiệt độ sôi thấp hơn nhiều so với p-Nitrophenol. Sự khác biệt này là do:",
     "choices": ["o-Nitrophenol chủ yếu tạo liên kết hydrogen NỘI PHÂN TỬ, còn p-Nitrophenol tạo liên kết hydrogen LIÊN PHÂN TỬ", "p-Nitrophenol có khối lượng lớn hơn", "o-Nitrophenol không có liên kết hydrogen", "o-Nitrophenol là hợp chất ion"],
     "answer": 0, "explanation": "Nhóm -OH và -NO2 ở vị trí ortho (cạnh nhau) tạo liên kết H với chính nó (nội phân tử). Khi đun, các phân tử ít hút nhau nên dễ bay hơi (T sôi thấp). Ở vị trí para (đối xứng), 2 nhóm ở xa nhau nên phải lk H với phân tử HÀNG XÓM (liên phân tử) $\\Rightarrow$ T sôi cao."},

    # Nhóm 30: Tổng hợp
    {"id": "mc-c2-089", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Biến thiên trạng thái",
     "question": "Để làm nóng chảy $NaCl$ cần nhiệt độ khoảng $801^\\circ\\text{C}$, trong khi $CO_2$ (đá khô) thăng hoa ở $-78,5^\\circ\\text{C}$. Nguyên nhân chính là do:",
     "choices": ["Lực liên kết ion tĩnh điện giữa $Na^+$ và $Cl^-$ trong $NaCl$ mạnh hơn rất nhiều so với lực tương tác van der Waals giữa các phân tử $CO_2$", "Phân tử khối của NaCl lớn hơn $CO_2$", "$CO_2$ không có khối lượng", "$NaCl$ có liên kết hydrogen"],
     "answer": 0, "explanation": "Khái quát bản chất trạng thái vật lí: NaCl rắn ion (nóng chảy phải bẻ gãy lk hóa học), CO2 rắn phân tử (nóng chảy/thăng hoa chỉ cần bẻ gãy VDW yếu ớt)."},
    {"id": "mc-c2-090", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Độ dài và NL LK",
     "question": "Cho độ dài liên kết trung bình: $C-C \\approx 154\\text{ pm}$, $C=C \\approx 134\\text{ pm}$, $C \\equiv C \\approx 120\\text{ pm}$. Chọn phát biểu sai?",
     "choices": ["Liên kết C-C bền hơn liên kết C=C vì nó dài hơn, dễ hấp thụ năng lượng hơn", "Số liên kết càng lớn (đôi, ba) thì khoảng cách giữa 2 hạt nhân càng ngắn lại", "Để bẻ gãy liên kết $C \\equiv C$ cần nhiều năng lượng hơn liên kết C=C", "Liên kết $C \\equiv C$ có chứa 2 liên kết pi"],
     "answer": 0, "explanation": "Độ dài liên kết dài thì LỰC HÚT yếu đi, dễ bị bẻ gãy (năng lượng liên kết thấp hơn). Nên C-C kém bền (năng lượng nhỏ) hơn C=C. Phát biểu A là sai logic hoàn toàn."},
    {"id": "mc-c2-091", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Xác định nhanh VSEPR",
     "question": "Cấu trúc hình học của phân tử $SO_3$ (lưu huỳnh trioxide) là:",
     "choices": ["Hình tam giác phẳng (góc $120^\\circ$)", "Hình chóp tam giác", "Hình chữ T", "Hình tứ diện"],
     "answer": 0, "explanation": "S có 6e hóa trị. Tạo 3 liên kết với 3 nguyên tử O, dùng hết 6e. Quanh S có 3 vùng mật độ (3 liên kết) và 0 cặp e tự do ($AX_3E_0$). Hình tam giác đều/phẳng, lai hóa sp2."},
    {"id": "mc-c2-092", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Lai hóa trong Benzene",
     "question": "Trong phân tử Benzene ($C_6H_6$), các nguyên tử Carbon ở trạng thái lai hóa gì?",
     "choices": ["$sp^2$ (tạo vòng lục giác phẳng)", "$sp^3$", "$sp$", "Không lai hóa"],
     "answer": 0, "explanation": "C trong vòng benzen liên kết với 2 C và 1 H (3 lk $\\sigma$) $\\Rightarrow$ lai hóa sp2. Còn 1 AO p không lai hóa thẳng góc mặt phẳng tham gia tạo hệ $\\pi$ liên hợp vòng."},

    # Câu 93 - 120: Luyện tập
    {"id": "mc-c2-093", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Octet Boron",
     "question": "Hợp chất $BF_3$ thiếu hụt electron vì xung quanh nguyên tử trung tâm B chỉ có:",
     "choices": ["6 electron", "4 electron", "8 electron", "10 electron"],
     "answer": 0, "explanation": "Boron (Z=5) có 3e hóa trị. Góp chung với 3 F được thêm 3e $\\Rightarrow$ Tổng cộng có 6e. $BF_3$ là một ngoại lệ thiếu bát tử (electron-deficient)."},
    {"id": "mc-c2-094", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Bản chất mạng ion",
     "question": "Tinh thể kim loại khác với tinh thể ion ở điểm cơ bản nào?",
     "choices": ["Tinh thể kim loại có chứa các 'electron tự do' di chuyển xuyên suốt mạng lưới cation, còn tinh thể ion không có electron tự do", "Tinh thể kim loại giòn dễ vỡ, tinh thể ion dẻo dễ dát mỏng", "Tinh thể kim loại không dẫn điện", "Tinh thể kim loại có nhiệt độ sôi luôn thấp hơn"],
     "answer": 0, "explanation": "Đám mây electron tự do (đám mây khí electron) là bản chất của liên kết kim loại, tạo ra tính dẫn điện, dẫn nhiệt, tính dẻo và ánh kim. Tinh thể ion thì các e bị khóa chặt ở anion."},
    {"id": "mc-c2-095", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Xác định cực phân tử",
     "question": "Trong các phân tử $CH_4, CHCl_3, CCl_4$. Phân tử nào CÓ phân cực?",
     "choices": ["$CHCl_3$", "$CH_4, CCl_4$", "Cả 3 đều phân cực", "Cả 3 đều không phân cực"],
     "answer": 0, "explanation": "$CH_4$ và $CCl_4$ có dạng $AX_4$ (4 nhóm giống nhau quanh tứ diện) $\\Rightarrow$ triệt tiêu cực $\\Rightarrow \\mu = 0$. $CHCl_3$ (chloroform) có 3 Cl và 1 H, bất đối xứng $\\Rightarrow$ Có phân cực."},
    {"id": "mc-c2-096", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "VSEPR tổng quát",
     "question": "Ion $NO_3^-$ (nitrate) có hình học VSEPR là gì?",
     "choices": ["Tam giác phẳng", "Chóp tam giác", "Đường thẳng", "Tứ diện"],
     "answer": 0, "explanation": "N trung tâm có 5e hóa trị. Thêm 1e (do điện tích -) = 6e. Tạo liên kết với 3 Oxi (mỗi O cần 2e) hết 6e. (hoặc: 1 nối đôi, 2 nối đơn. Tính điện tích hình thức...). Tóm lại quanh N có 3 vùng liên kết, 0 tự do $\\Rightarrow$ Tam giác phẳng ($120^\\circ$)."},
    
    {"id": "mc-c2-097", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Đếm sigma pi phân tử phức",
     "question": "Phân tử Toluen ($C_6H_5-CH_3$) có tổng cộng bao nhiêu liên kết $\\pi$?",
     "choices": ["3", "4", "2", "6"],
     "answer": 0, "explanation": "Vòng benzen có 3 lk đôi xen kẽ (thực chất là liên hợp). Coi như 3 lk $\\pi$. Nhóm methyl (-CH3) chỉ có liên kết đơn. Vậy tổng = $3\\pi$."},
    {"id": "mc-c2-098", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Lk hydro bất thường",
     "question": "Dung dịch Amoniac ($NH_3$) tan cực kì tốt trong nước (1 lít nước hòa tan được 800 lít NH3) chủ yếu là do:",
     "choices": ["$NH_3$ tạo được liên kết hydrogen mạnh với các phân tử $H_2O$", "$NH_3$ là chất khí nhẹ hơn không khí", "$NH_3$ có phản ứng mãnh liệt tạo nổ với nước", "$NH_3$ có phân tử khối bằng với $H_2O$"],
     "answer": 0, "explanation": "$NH_3$ có N (âm điện lớn, có cặp e tự do) $\\Rightarrow$ Tạo mạng liên kết hydro đan chéo với nước (H của H2O lk với N; H của NH3 lk với O). Hiện tượng 'giống nhau thì hòa tan' cực tốt."},
    {"id": "mc-c2-099", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Bài tập điện hóa trị",
     "question": "Cho nguyên tố $X (Z=19)$ và $Y (Z=8)$. Hợp chất tạo bởi X và Y có công thức và loại liên kết là:",
     "choices": ["$X_2Y$, liên kết ion", "$XY_2$, liên kết cộng hóa trị", "$X_2Y$, liên kết cộng hóa trị", "$XY$, liên kết ion"],
     "answer": 0, "explanation": "X (19): Kali (K) nhóm IA, kim loại mạnh. Y (8): Oxi (O) nhóm VIA, phi kim mạnh. $\\Rightarrow$ Lk ion. O cần 2e, K nhường 1e $\\Rightarrow$ cần 2K. Công thức $K_2O$ (tức $X_2Y$)."},
    {"id": "mc-c2-100", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Phân cực theo độ âm điện",
     "question": "Sắp xếp theo thứ tự ĐỘ PHÂN CỰC của liên kết giảm dần: $H-Cl, H-F, H-Br, H-I$.",
     "choices": ["$H-F > H-Cl > H-Br > H-I$", "$H-I > H-Br > H-Cl > H-F$", "$H-F > H-Br > H-Cl > H-I$", "Bằng nhau"],
     "answer": 0, "explanation": "Độ âm điện của Halogen giảm dần: $F > Cl > Br > I$. Hiệu độ âm điện $\\Delta\\chi$ với Hydro cũng giảm dần tương ứng $\\Rightarrow$ Phân cực giảm dần theo thứ tự HF > HCl > HBr > HI."},
    
    {"id": "mc-c2-101", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Momen lưỡng cực VSEPR",
     "question": "Sự tồn tại của Moment lưỡng cực ($\\mu > 0$) trong phân tử $H_2S$ chứng tỏ:",
     "choices": ["Phân tử $H_2S$ có cấu trúc góc chứ không phải đường thẳng", "Phân tử $H_2S$ có liên kết ion", "Phân tử $H_2S$ là khí hiếm", "Lưu huỳnh có độ âm điện nhỏ hơn H"],
     "answer": 0, "explanation": "Nếu là đường thẳng (H-S-H), 2 vector liên kết S-H sẽ triệt tiêu và $\\mu = 0$. Vì $\\mu > 0$ chứng tỏ 2 vector không ngược chiều 180 độ, tức là nó bị bẻ góc (thực tế S lai hóa sp3 có 2 cặp e tự do)."},
    {"id": "mc-c2-102", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Tính chất lk Pi",
     "question": "Vì sao các hợp chất chứa liên kết đôi hoặc ba (như Ethene, Ethyne) thường dễ tham gia phản ứng CỘNG làm đứt liên kết?",
     "choices": ["Vì trong liên kết bội có chứa liên kết $\\pi$ kém bền hơn liên kết $\\sigma$, dễ bị đứt ra để tạo thêm liên kết $\\sigma$ mới", "Vì liên kết $\\pi$ có năng lượng quá lớn làm phân tử phát nổ", "Vì chúng là hợp chất hữu cơ", "Vì cấu trúc phân tử quá nhỏ"],
     "answer": 0, "explanation": "Xen phủ bên $\\pi$ có mật độ electron nằm ngoài trục nối hạt nhân, năng lượng yếu hơn $\\sigma$. Khi gặp tác nhân (như $Br_2, H_2$), liên kết $\\pi$ dễ đứt ra để 2 nguyên tử C tạo 2 liên kết $\\sigma$ bền vững hơn (phản ứng cộng)."},
    {"id": "mc-c2-103", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Điểm sôi H-bond 2",
     "question": "Hydrogen fluoride ($HF$) sôi ở $19,5^\\circ\\text{C}$, trong khi $HCl$ sôi ở $-85^\\circ\\text{C}$. Nguyên nhân là do:",
     "choices": ["Giữa các phân tử HF có mạng liên kết Hydrogen, còn HCl thì không có (hoặc cực yếu)", "Do F có khối lượng lớn hơn Cl", "Do liên kết H-F là liên kết ion", "Do phân tử HF to hơn HCl"],
     "answer": 0, "explanation": "Điều kiện lk H (nguyên tử H gắn với F, O, N). HCl không thỏa mãn $\\Rightarrow$ T sôi thấp."},
    {"id": "mc-c2-104", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "Cấu hình bát tử H",
     "question": "Trong phân tử Natri hydride ($NaH$), nguyên tử Hydrogen có cấu hình electron của khí hiếm nào?",
     "choices": ["Helium ($1s^2$)", "Neon", "Argon", "Không có cấu hình khí hiếm"],
     "answer": 0, "explanation": "NaH là hợp chất ion. $Na^+$ (nhường 1e), $H^-$ (nhận 1e). H từ 1e nhận thêm 1e thành $1s^2$, giống với Helium (Duet)."},
    
    {"id": "mc-c2-105", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Số liên kết CHT cực đại",
     "question": "Phosphorus ($Z=15$) thuộc chu kì 3 có thể tạo ra hợp chất $PCl_5$ (5 liên kết CHT), trong khi Nitrogen ($Z=7$) cùng nhóm VA nhưng chu kì 2 chỉ tạo được $NCl_3$, không có $NCl_5$. Tại sao?",
     "choices": ["Vì P thuộc chu kì 3 có phân lớp 3d trống, có thể kích thích electron lên 3d tạo 5 electron độc thân; còn N ở chu kì 2 không có phân lớp 2d", "Vì P to hơn N nên nhét vừa 5 Cl", "Vì P là kim loại, N là phi kim", "Vì P có độ âm điện lớn hơn N"],
     "answer": 0, "explanation": "N có cấu hình ngoài $2s^2 2p^3$ (chỉ có tối đa 4 AO). P có $3s^2 3p^3 3d^0$, khi bị kích thích 1e từ 3s nhảy lên 3d $\\Rightarrow 3s^1 3p^3 3d^1$ (5 e độc thân) $\\Rightarrow$ tạo 5 liên kết cộng hóa trị (Bát tử mở rộng - hypervalent)."},
    {"id": "mc-c2-106", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Lai hóa C bất đối xứng",
     "question": "Phân tử Hydrogen cyanide ($H-C \\equiv N$) có nguyên tử C lai hóa gì và hình dạng gì?",
     "choices": ["$sp$, đường thẳng", "$sp^2$, tam giác", "$sp^3$, tứ diện", "Không lai hóa"],
     "answer": 0, "explanation": "C liên kết với 2 vùng nguyên tử (1 lk đơn với H, 1 lk ba với N), không có e tự do. Số vùng liên kết = 2 $\\Rightarrow$ Lai hóa $sp$, tạo hình đường thẳng (góc $180^\\circ$)."},
    {"id": "mc-c2-107", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Chất rắn phân tử",
     "question": "Iodine ($I_2$) ở điều kiện thường là chất rắn màu tím đen, dễ thăng hoa. Tại sao chất rắn này lại dễ thăng hoa?",
     "choices": ["Vì tinh thể phân tử Iodine được liên kết bằng lực van der Waals rất yếu", "Vì liên kết cộng hóa trị I-I rất dễ đứt gãy", "Vì Iodine là chất phóng xạ", "Vì Iot phản ứng ngay với không khí"],
     "answer": 0, "explanation": "Lực van der Waals giữa các phân tử $I_2$ (tinh thể phân tử) yếu. Khi đun nóng nhẹ, nhiệt năng đủ phá vỡ VDW làm $I_2$ chuyển thẳng từ rắn sang khí (thăng hoa), nhưng liên kết CHT $I-I$ trong phân tử vẫn nguyên vẹn."},
    {"id": "mc-c2-108", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Độ tan của cồn",
     "question": "Ethanol ($C_2H_5OH$) tan vô hạn trong nước, trong khi Butanol ($C_4H_9OH$) tan ít hơn nhiều. Lý do là vì:",
     "choices": ["Gốc hydrocarbon (kị nước) của Butanol lớn hơn, làm giảm tương đối vai trò của nhóm -OH kề (ưa nước) trong việc tạo liên kết Hydrogen với nước", "Butanol là hợp chất ion", "Ethanol không có gốc hydrocarbon", "Butanol nặng hơn nước nên chìm"],
     "answer": 0, "explanation": "Cả 2 đều có nhóm -OH tạo lk Hydrogen với nước. Tuy nhiên gốc Carbon ($C_4$) của Butanol cồng kềnh, không phân cực (chỉ tương tác VDW), cản trở sự xâm nhập của phân tử nước $\\Rightarrow$ Giảm độ tan."},
    
    {"id": "mc-c2-109", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Octet SO3",
     "question": "Viết công thức Lewis (thỏa bát tử cho mọi nguyên tử) của $SO_3$, ta thấy phân tử có:",
     "choices": ["1 liên kết đôi $S=O$ và 2 liên kết cho nhận $S \\rightarrow O$", "3 liên kết đôi $S=O$", "3 liên kết đơn $S-O$", "1 liên kết ba"],
     "answer": 0, "explanation": "Theo chương trình phổ thông tuân thủ bát tử nghiêm ngặt: $S$ tạo 1 nối đôi và 2 liên kết phối trí với 2 nguyên tử O còn lại."},
    {"id": "mc-c2-110", "chapter": "c2", "lesson": "b9", "level": "vd", "dang": "So sánh nhiệt độ nóng chảy ion",
     "question": "Chất nào sau đây có nhiệt độ nóng chảy CAO NHẤT? (Cho: $NaCl, MgO, KBr$)",
     "choices": ["$MgO$", "$NaCl$", "$KBr$", "Bằng nhau"],
     "answer": 0, "explanation": "Nhiệt độ nóng chảy phụ thuộc vào Năng lượng mạng lưới tinh thể $E \\propto |q_1 q_2| / (r_1 + r_2)$. Điện tích ion trong $MgO$ là $+2, -2$ (tích là 4), trong khi NaCl, KBr là $+1, -1$ (tích là 1). Lực hút Coulomb ở $MgO$ gấp 4 lần $\\Rightarrow$ Nhiệt độ nóng chảy MgO ($\\sim 2852^\\circ\\text{C}$) rất cao so với NaCl ($801^\\circ\\text{C}$)."},
    {"id": "mc-c2-111", "chapter": "c2", "lesson": "b10", "level": "th", "dang": "Lưỡng cực Lưỡng cực",
     "question": "Lực tương tác lưỡng cực - lưỡng cực xảy ra giữa:",
     "choices": ["Các phân tử có cực", "Các phân tử không phân cực", "Giữa ion và phân tử nước", "Giữa các nguyên tử khí hiếm"],
     "answer": 0, "explanation": "Lưỡng cực - lưỡng cực (Dipole-Dipole) chỉ xảy ra khi bản thân phân tử là một lưỡng cực VĨNH VIỄN (phân tử phân cực, vd $HCl, H_2S$)."},
    {"id": "mc-c2-112", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Lai hóa phân tử chứa O",
     "question": "Ozone ($O_3$) có hình góc (bent) $117^\\circ$. Nguyên tử Oxi trung tâm trong Ozone ở trạng thái lai hóa gì?",
     "choices": ["$sp^2$", "$sp^3$", "$sp$", "$sp^3d$"],
     "answer": 0, "explanation": "O trung tâm có 1 lk đôi, 1 lk đơn (tính là 2 vùng liên kết) và còn dư 1 cặp e tự do. Tổng số vùng mật độ = 3 $\\Rightarrow$ Lai hóa $sp^2$. Hình dạng góc $120^\\circ$ (thực tế $117^\\circ$ do lực đẩy)."},
    
    {"id": "mc-c2-113", "chapter": "c2", "lesson": "b12", "level": "th", "dang": "Liên kết ở Trạng thái rắn",
     "question": "Đồng ($Cu$) là một kim loại. Liên kết giữ các nguyên tử Cu trong tinh thể là:",
     "choices": ["Liên kết kim loại (mạng lưới cation được nhúng trong đám mây electron tự do)", "Liên kết ion", "Liên kết cộng hóa trị", "Lực van der Waals"],
     "answer": 0, "explanation": "Tinh thể kim loại gồm các Cation nằm ở nút mạng và các electron hóa trị bứt ra bơi lội tự do như một \"chất lỏng\" giữa các ion này."},
    {"id": "mc-c2-114", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "VDW Lực London",
     "question": "Vì sao khi áp suất cao và nhiệt độ cực thấp, các khí như Heli hay Nito lại có thể hóa lỏng?",
     "choices": ["Vì động năng phân tử giảm, lúc này lực phân tán London (van der Waals) dù rất yếu nhưng đủ lớn để giữ các phân tử lại với nhau tạo pha lỏng", "Vì chúng sinh ra liên kết hóa học", "Vì phản ứng hạt nhân", "Vì ở nhiệt độ thấp sinh ra liên kết ion"],
     "answer": 0, "explanation": "Nhiệt độ cực thấp $\\Rightarrow$ động năng $E_k$ rất nhỏ. Lực London (sinh ra do thăng giáng đám mây e) dù yếu cỡ vài kJ/mol cũng thắng được $E_k$, ép các phân tử tụ lại thành lỏng."},
    {"id": "mc-c2-115", "chapter": "c2", "lesson": "b8", "level": "vd", "dang": "Cation dị nguyên tử",
     "question": "Ion $H_3O^+$ (Hydroxonium) được hình thành khi phân tử $H_2O$ nhận thêm 1 proton $H^+$. Liên kết mới hình thành giữa O và $H^+$ là loại liên kết gì?",
     "choices": ["Liên kết cho - nhận (O dùng cặp electron tự do cho $H^+$ nhận chung)", "Liên kết ion", "Liên kết kim loại", "Lực van der Waals"],
     "answer": 0, "explanation": "$H^+$ rỗng (không có e). O trong $H_2O$ có 2 cặp e tự do. O đóng góp 1 cặp e cho $H^+$ dùng chung $\\Rightarrow$ Lk phối trí (cho - nhận)."},
    {"id": "mc-c2-116", "chapter": "c2", "lesson": "b9", "level": "th", "dang": "Bền nhiệt ion",
     "question": "Nhận định nào sau đây ĐÚNG về sự bay hơi của tinh thể muối ăn ($NaCl$)?",
     "choices": ["Khi đun nóng đến $>1413^\\circ\\text{C}$ (nhiệt độ sôi), nó bay hơi và trong pha khí tồn tại chủ yếu các CẶP ion (phân tử $NaCl$ cô lập) do bị tách khỏi mạng lưới", "Nó bay hơi tạo thành khí $Na$ và khí $Cl_2$", "Nó bay hơi tạo thành các ion rời rạc hoàn toàn $Na^+$ và $Cl^-$ độc lập", "Nó không bao giờ bay hơi"],
     "answer": 0, "explanation": "Khi sôi, năng lượng nhiệt đánh bật các ion ra khỏi khối tinh thể lỏng, chúng bay ra dưới dạng các cặp phân tử $NaCl$ (một $Na^+$ dính chặt với một $Cl^-$). Phân li hoàn toàn chỉ xảy ra ở nhiệt độ cực kì cao (plasma)."},
    {"id": "mc-c2-117", "chapter": "c2", "lesson": "b10", "level": "vd", "dang": "Giải thích tính cứng",
     "question": "Kim cương rất cứng, trong khi Graphite (than chì) lại rất mềm và trơn dẫu cả hai đều làm từ Carbon. Giải thích theo liên kết hóa học:",
     "choices": ["Kim cương có cấu trúc mạng 3D tứ diện (lai hóa $sp^3$) liên kết CHT cực bền. Than chì có cấu trúc lớp 2D (lai hóa $sp^2$), các lớp xếp chồng lên nhau và giữ bằng lực van der Waals yếu nên dễ trượt", "Than chì bị phân hủy ở điều kiện thường", "Kim cương có khối lượng riêng nhẹ hơn", "Than chì có liên kết ion"],
     "answer": 0, "explanation": "Các lớp than chì (graphene) chỉ hút nhau bằng VDW yếu (London) $\\Rightarrow$ Dễ trượt lên nhau (dùng làm ruột bút chì). Kim cương là mạng $3D$ đồng nhất $\\Rightarrow$ cứng nhất nhì tự nhiên."},
    {"id": "mc-c2-118", "chapter": "c2", "lesson": "b11", "level": "vd", "dang": "Số lk hóa trị nhiều",
     "question": "Nguyên tử nguyên tố Lưu huỳnh ($Z=16$) có thể có bao nhiêu electron độc thân khi ở trạng thái kích thích?",
     "choices": ["Có thể có 4 hoặc 6 electron độc thân (Bát tử mở rộng)", "Chỉ có tối đa 2", "Chỉ có 3", "Có 8 electron độc thân"],
     "answer": 0, "explanation": "Cấu hình ngoài $3s^2 3p^4 3d^0$ (2 e độc thân). Kích thích 1e từ p lên d $\\Rightarrow 3s^2 3p^3 3d^1$ (4 e độc thân, tạo $SF_4, SO_2$). Kích thích tiếp 1e từ s lên d $\\Rightarrow 3s^1 3p^3 3d^2$ (6 e độc thân, tạo $SF_6, SO_3$)."},
    {"id": "mc-c2-119", "chapter": "c2", "lesson": "b12", "level": "vd", "dang": "Tổng $\\pi$ và $\\sigma$ trong HNO3",
     "question": "Đếm lại tổng số liên kết $\\sigma$ và $\\pi$ trong 1 phân tử acid $HNO_3$ (Công thức Lewis cổ điển: $H-O-NO_2$):",
     "choices": ["4 $\\sigma$ và 1 $\\pi$", "3 $\\sigma$ và 2 $\\pi$", "5 $\\sigma$", "2 $\\sigma$ và 3 $\\pi$"],
     "answer": 0, "explanation": "Các lk: 1 lk đơn H-O (1 $\\sigma$). 1 lk đơn O-N (1 $\\sigma$). 1 lk đôi N=O (1 $\\sigma$, 1 $\\pi$). 1 lk cho nhận $N \\rightarrow O$ (tính như liên kết đơn về mặt cấu trúc $\\Rightarrow 1\\sigma$). Tổng = 4 $\\sigma$, 1 $\\pi$."},
    {"id": "mc-c2-120", "chapter": "c2", "lesson": "b13", "level": "vd", "dang": "Sức căng bề mặt của nước",
     "question": "Giọt sương trên lá sen có hình cầu, hay một con nhện nước có thể đứng trên mặt ao mà không chìm là do 'sức căng bề mặt' của nước rất lớn. Sức căng bề mặt này bản chất sinh ra từ lực hóa học nào?",
     "choices": ["Liên kết Hydrogen giữa các phân tử nước ở lớp bề mặt hút chặt nhau vào bên trong", "Lực hút tĩnh điện của ion", "Liên kết cộng hóa trị", "Độ nhớt của không khí"],
     "answer": 0, "explanation": "Phân tử nước ở bề mặt không có phân tử nước nào bên trên để hút, nên các lực hút (liên kết hydro) bị kéo lệch hướng vào trong khối chất lỏng, tạo ra một 'màng đàn hồi' vô hình (sức căng bề mặt)."}
]

for i in range(len(data['questions'])):
    qid = data['questions'][i]['id']
    match = next((q for q in new_qs if q['id'] == qid), None)
    if match:
        data['questions'][i] = match

with open('data/hoa10/questions/mc.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Hoa10 C2 Part 2 written successfully.")
